
import sys; sys.path.insert(0,'.')
from util import *

DEPARTMENTS_2 = [

# ── LEGAL & CORPORATE SECRETARIAL ─────────────────────────────────────────
ind('dept-legal','department','Legal & Corporate Secretarial','⚖️','#4A148C','#6A1B9A',
    'Zava Group Holdings — Group Legal Division',
    'NDA pipeline, JV agreements, Bursa disclosures, BPOM/BNM regulatory response management.',
    'The Group Legal Division manages contract review, regulatory compliance, M&A legal support, and corporate secretarial obligations for the dual-listed Zava Group (Bursa Malaysia + IDX Jakarta). Current workload includes 14 active NDAs, 3 JV agreement negotiations, 2 regulatory responses (BNM and BPOM), and an upcoming Bursa Malaysia circular for shareholder approval of the REIT IPO.',
    ['02_Zava_Group_Policy_Handbook.docx','Email_07_Emergency_Board_Meeting.docx'],
    [
      tool(T_CHAT, FREE_LIC, FREE_ACCT, [
        'I am the Group General Counsel of a dual-listed ASEAN conglomerate. We have 3 concurrent JV agreement negotiations — in Indonesia (property development), Singapore (commodity trading), and India (BPO). Draft a 250-word brief for our legal team on: (1) The 3 most critical clauses in any JV agreement that must be negotiated from strength, (2) How deadlock resolution mechanisms differ between MY, ID, and SG legal frameworks, (3) The typical timeline and process for Bursa Malaysia approval of a material JV transaction.',
        'What are a listed company\'s disclosure obligations on Bursa Malaysia when it enters into a material transaction? What is the threshold for "interested person transactions" and when is shareholder approval required? How does this differ from the equivalent IDX (Indonesia Stock Exchange) requirement?',
        'Explain GDPR vs Malaysia PDPA vs Indonesia UU PDP differences in terms of data processor obligations, cross-border transfer restrictions, and breach notification requirements. Which applies to Zava Group given our MYR 45B revenue across MY and ID?'
      ]),
      tool(T_RESEARCHER, M365_LIC, M365_ACCT, [
        'Research the legal framework for cross-border M&A transactions involving Malaysian and Indonesian companies. What are the key regulatory approvals required (MIDA, BKPM, competition authorities)? What deal structures are commonly used to navigate foreign ownership restrictions in Indonesia? Cite legal sources.',
        'Research the latest Malaysia Anti-Corruption Commission (MACC) guidelines for corporate compliance. What are the requirements under Section 17A of the MACC Act 2009 for GLCs and listed companies? What are the key elements of an "adequate procedures" compliance programme? Cite official MACC resources.'
      ], DESC_RESEARCHER),
      tool(T_ANALYST, M365_LIC, M365_ACCT, [
        'Upload 02_Zava_Group_Policy_Handbook.docx (use as reference). Ask Analyst to help structure: Build a legal matter tracking model. For 14 active NDAs: categorise by counterparty risk (high/medium/low), expiry date, and whether a renewal or escalation to full agreement is needed. For 3 JV agreements: calculate negotiation timeline, key milestone dates, and risk-weighted deal value. Show as a prioritised legal workload matrix.',
        'Ask Analyst: Build a regulatory response timeline model. For the BNM remediation plan (90-day deadline, 6 action items) and the BPOM corrective action plan (60-day deadline, 8 action items), create a Gantt chart showing all tasks, dependencies, responsible parties, and completion %. Flag any task on the critical path that risks missing the regulatory deadline.'
      ], DESC_ANALYST),
      tool(T_EXCEL, M365_LIC, M365_ACCT, [
        'Open 02_Zava_Group_Policy_Handbook.docx. Create a companion Legal Matter Tracker workbook. Ask Copilot: Create Sheet 1 with columns: Matter | Type (NDA/JV/Regulatory/Litigation) | Division | Counterparty | Status | Key Risk | Next Action | Deadline | External Counsel | Estimated Cost (MYR M). Add conditional formatting: red = overdue, amber = due within 7 days, green = on track. Sort by deadline.',
        'Ask Copilot: Create a Bursa Disclosure Calendar on Sheet 2. For each material transaction or event requiring Bursa announcement (REIT IPO circular, JV agreements, Board changes, results announcements, dividend declarations), show: event, Bursa deadline, draft due from Legal, Board approval date, expected announcement date. Highlight any where Legal\'s internal deadline has passed.',
        'Ask Copilot: Build a contract expiry tracker on Sheet 3. For all major contracts — BPO client agreements, plant offtake agreements, banking facilities, insurance policies — show: contract party, division, value (MYR M), expiry date, auto-renewal clause (Y/N), renegotiation lead time needed (months), action status. Flag contracts expiring within 6 months with no renegotiation started.'
      ]),
      tool(T_WORD, M365_LIC, M365_ACCT, [
        'Open 02_Zava_Group_Policy_Handbook.docx. Ask Copilot: Review the Data Privacy & Cybersecurity Policy section. Identify: (1) Any gaps vs the new Malaysia PDPA 2024 amendments, (2) Any gaps vs Indonesia\'s UU PDP 2022, (3) Recommended policy updates for each gap. Present as a gap analysis table: Current Policy Clause | Gap | Required Update | Urgency (High/Medium/Low).',
        'Ask Copilot: Draft a template Non-Disclosure Agreement for Zava Group. The NDA should: cover bilateral confidentiality, define confidential information broadly (including oral disclosures with 48-hour written confirmation), include a 3-year confidentiality period post-termination, specify Malaysian law and KL courts as jurisdiction, and include a specific carve-out for information required by Bursa Malaysia or IDX disclosure obligations. 4-page formal NDA.',
        'Open Email_07_Emergency_Board_Meeting.docx. Ask Copilot: Draft the Board resolution for the emergency meeting. The resolution should: confirm quorum, approve the 3 decisions required (coal trading breach remediation plan, Zava Bank corrective action plan, REIT IPO timeline approval), and record the Director votes. Use standard Malaysian Board resolution format.'
      ]),
      tool(T_PPT, M365_LIC, M365_ACCT, [
        'Ask Copilot in PowerPoint: Create a 5-slide Group Legal & Compliance quarterly update for the Board Audit Committee. Include: (1) Litigation risk register — 8 matters, quantum, and provision status, (2) Regulatory compliance status — BNM, BPOM, Bursa, MACC, (3) M&A legal workstream — 3 JV agreements, status, (4) Data privacy — PDPA/UU PDP compliance rating, (5) Legal spend vs budget. Purple and white colour scheme.',
        'Ask Copilot: Create a 2-slide MACC Section 17A compliance overview for the Audit Committee. Slide 1: What is "adequate procedures" under Section 17A and our current compliance rating. Slide 2: The 3 actions required to strengthen our anti-corruption programme before the annual compliance assessment.',
        'Ask Copilot: Create a Bursa Malaysia disclosure timeline slide for the REIT IPO. Show: all required Bursa filings, shareholder circular deadlines, SC application timeline, expected announcement dates, and the final IPO day. As a horizontal timeline visual.'
      ]),
      tool(T_OUTLOOK, M365_LIC, M365_ACCT, [
        'Ask Copilot in Outlook: Draft the legal instruction letter to our external counsel (Skrine & Co) on the Indonesia JV agreement negotiation. The letter should: confirm the commercial terms agreed by the business (50:50 equity, Zava as managing partner, 10-year term), instruct counsel to draft the JV agreement, highlight 3 non-negotiable clauses (drag-along rights, deadlock by third-party arbitration, ASEAN ADRIC rules), and set the first draft deadline at 3 weeks.',
        'Ask Copilot: Draft a cease-and-desist letter to a competitor who has been using Zava Group\'s registered trademark "ZavaGen" for pharmaceutical products without licence. The letter should: identify the trademark registration details, describe the infringing use, demand immediate cessation within 14 days, and note that legal proceedings will be commenced if the demand is not complied with.',
        'Ask Copilot: Draft the Group General Counsel\'s email to all Division Legal Heads reminding them of the updated Delegation of Authority for contract signing. Specifically: all JV agreements above MYR 50M require Group GC and Group CEO sign-off; all NDAs may be signed by Division MD. Attach the updated DOA matrix as reference.'
      ]),
      tool(T_TEAMS, M365_LIC, M365_ACCT, [
        'Open an existing recorded Teams meeting recap from a legal or risk committee meeting. Ask Copilot: Identify all legal matters discussed — active litigations, regulatory deadlines, JV negotiation issues. Create an action tracker with the legal team owner and deadline for each item.',
        'Ask Copilot: Draft the post-meeting legal team tasks from the regulatory response review. Group by matter: BNM Response | BPOM Corrective Action | Bursa Circular | MACC Compliance. Include responsible lawyer and deadline.',
        'Ask Copilot: Were there any discussions about the coal trading breach and potential securities disclosure obligations? What was the General Counsel\'s advice on timing of the Bursa announcement?'
      ], DESC_TEAMS),
      tool(T_NOTEBOOK, M365_LIC, M365_ACCT, [
        'Upload 02_Zava_Group_Policy_Handbook.docx and Email_07_Emergency_Board_Meeting.docx to Copilot Notebook. Set instruction: "You are advising the Group GC on legal risk management for the Board emergency meeting." Ask: What are the top 3 legal risks the Board must be advised of at Monday\'s emergency meeting? For each, what is the maximum exposure and what immediate action should the Board authorise?',
        'Upload 02_Zava_Group_Policy_Handbook.docx. Ask: Our anti-bribery policy requires all Zava employees and agents to complete annual MACC training. We have 87,420 employees. Only 62% have completed this year\'s training. Does this incomplete compliance constitute a "failure of adequate procedures" under MACC Section 17A? What is the legal risk and what remedial action is needed within 30 days?'
      ], DESC_NOTEBOOK),
      tool(T_COWORK, FRONTIER_LIC, M365_ACCT, [
        'Do all of the following: (1) Research MACC Section 17A adequate procedures guidelines and the latest 2024 updates. (2) Audit our 02_Zava_Group_Policy_Handbook.docx anti-bribery chapter against the 5 required adequate procedures pillars. (3) Draft a gap analysis and remediation plan for any missing elements. (4) Save to OneDrive as "MACC Section 17A Compliance Audit". (5) Email to GC and CFO requesting urgent review before the Board audit committee meeting.',
        'Do all of the following for the JV agreement: (1) Research the key legal requirements for a 50:50 JV company registration in Indonesia (PT PMA). (2) Draft a term sheet for the Indonesia JV based on the agreed commercial terms. (3) Email to external counsel requesting confirmation that the term sheet is consistent with Indonesian company law. (4) Create a JV legal project folder in SharePoint. (5) Schedule a weekly JV legal steering meeting until signing.'
      ], DESC_COWORK),
      tool(T_WORD_AGT, M365_LIC, M365_ACCT, [
        'Open 02_Zava_Group_Policy_Handbook.docx in Word for Web. Create an agent called "Zava Group Legal & Compliance Policy Bot". Description: "Answers questions from Zava employees, managers, and Division legal teams on anti-bribery policy, data privacy obligations, contract signing authority, Bursa disclosure requirements, and legal compliance procedures." Share with all Division legal teams and publish to the employee portal.',
        'Demo: A senior manager asks "A government procurement officer has invited me to a golf day organised by the government — value approximately MYR 800. Under our Gifts & Hospitality Policy, can I accept? And do I need to declare it even if I decline?" Show the agent providing a precise, policy-grounded anti-bribery compliance answer.'
      ], DESC_WORD_AGT),
      tool(T_PPT_AGT, M365_LIC, M365_ACCT, [
        'Create a PowerPoint from the Board legal update. Create an agent called "Group Legal Update Q&A Bot". Share with the Audit Committee and Board.',
        'Demo: An Audit Committee member asks "What is our total litigation exposure across all 8 active matters and how much have we provisioned vs the risk-weighted exposure? Are any of the 8 matters potentially material enough to require Bursa disclosure?" Show the agent providing a litigation-risk-and-disclosure-grounded answer.'
      ], DESC_PPT_AGT),
      tool(T_XL_AGT, M365_LIC, M365_ACCT, [
        'Create the Legal Matter Tracker workbook and open in Excel for Web. Create an agent called "Group Legal Matter Tracker Q&A". Description: "Instant answers on active legal matters, contract expiry deadlines, regulatory response timelines, and Bursa disclosure obligations for the GC and Division Legal Heads." Share with the Group Legal team.',
        'Demo: Ask "Which contracts are expiring within 90 days with no renegotiation started?" Then: "Are there any regulatory deadlines (BNM or BPOM) that we risk missing in the next 30 days and which matters are on critical path?" Show the GC getting instant legal risk intelligence.'
      ], DESC_XL_AGT),
      tool(T_BUILDER, M365_LIC, M365_ACCT, [
        'Go to copilotstudio.microsoft.com > Create > New Agent. Name it "Zava Legal Intelligence Agent". Description: "Supports the Group Legal Division and Division Legal teams with instant answers on contract management, MACC compliance, Bursa disclosure obligations, data privacy requirements, regulatory deadlines, and cross-border legal frameworks — enabling faster, consistent, and legally sound decisions across the Zava Group." Upload 02_Zava_Group_Policy_Handbook.docx and Email_07_Emergency_Board_Meeting.docx. Add topics: "Contract Management", "MACC Compliance", "Bursa Disclosure", "Data Privacy", "Regulatory Deadlines". Publish to Teams.',
        'Demo the agent: The Group GC receives a WhatsApp message from a journalist at 7pm on a Friday: "I have documents suggesting Zava Group knowingly continued operating the Cilegon plant for 6 weeks after receiving an BPOM enforcement notice. Can you comment for my story running tomorrow?" The GC immediately asks the agent: "What are our legal obligations to respond to a media inquiry about regulatory enforcement, does our press relations policy require a response within a specific timeframe, and what language should I categorically NOT use in any statement related to an active regulatory matter?" Show how the agent provides an instant, legally-grounded crisis communication guidance.'
      ], DESC_BUILDER),
    ]),

# ── RISK & GOVERNANCE ─────────────────────────────────────────────────────
ind('dept-risk','department','Risk & Internal Audit','🛡','#B71C1C','#C62828',
    'Zava Group Holdings — Group Risk Division',
    'ERM framework refresh, coal trading limit breach, Zava Bank NPL, Cilegon enforcement — 4 active risk events.',
    'The Group Risk Division manages Enterprise Risk Management, Internal Audit, and Board Risk Committee reporting across Zava Group. Four active risk events: coal trading position limit breach, Zava Bank NPL breach, Cilegon plant 3 BPOM enforcement notices, Perkebunan Lestari RSPO suspension. Board Risk Committee meets monthly; a special meeting has been called.',
    ['01_Zava_Group_Financial_Performance.xlsx','20_Zava_ESG_Sustainability_Framework.docx'],
    [
      tool(T_CHAT, FREE_LIC, FREE_ACCT, [
        'I am the Group Chief Risk Officer of a diversified ASEAN conglomerate. We have 4 simultaneous active risk events: (1) coal trading limit breach USD 2.4M, (2) bank NPL breach 21.7%, (3) chemical plant 3 regulatory enforcement notices, (4) plantation RSPO suspension. Draft a 250-word brief for the Board Risk Committee on: how to prioritise the 4 events by systemic impact, what is the combined worst-case financial exposure, and what is the primary governance question the Board must decide.',
        'What is an Enterprise Risk Management (ERM) framework and how does it differ for a diversified conglomerate vs a single-industry company? Explain the ISO 31000 standard and how it applies to a group with 11 divisions and MYR 45B revenue.',
        'What is the "three lines of defence" model in risk management? How should each line (business units, risk function, internal audit) respond to the 4 active risk events at a conglomerate? Who is responsible for what?'
      ]),
      tool(T_RESEARCHER, M365_LIC, M365_ACCT, [
        'Research enterprise risk management frameworks for diversified conglomerates in Southeast Asia. How do comparable groups (Sime Darby, IJM, Axiata) structure their ERM frameworks? What are the best practices for Group-level risk aggregation when you have 11 diverse business units? Cite ISO 31000, COSO ERM 2017, or comparable frameworks.',
        'Research Malaysian listed company risk disclosure requirements. What does Bursa Malaysia require in the annual report risk section for a company in multiple sectors? How do companies like Petronas and Maybank communicate risk appetite and emerging risks to shareholders? Cite Bursa guidelines.'
      ], DESC_RESEARCHER),
      tool(T_ANALYST, M365_LIC, M365_ACCT, [
        'Upload 01_Zava_Group_Financial_Performance.xlsx to Analyst. Ask: Build an enterprise risk heat map. For 15 key risks (commodity price, FOREX, NPL/credit, regulatory/enforcement, ESG/RSPO, operational/OEE, succession, cyber, climate, trading limits), score each on: (1) likelihood (1-5), (2) financial impact (1-5 mapped to MYR M thresholds), (3) velocity (how fast it can materialise). Plot on a 5x5 heat map. Identify the top 5 risks requiring immediate Board attention.',
        'Upload 01_Zava_Group_Financial_Performance.xlsx. Ask: Stress test the group financials against a combined adverse scenario: CPO -15%, IDR -10% vs MYR, Zava Bank NPL provisions +MYR 600M, Cilegon plant production loss 6 months, coal trading counterparty default (USD 6.8M loss). Calculate: (1) Impact on group EBITDA, (2) Impact on PAT, (3) New net gearing ratio, (4) Whether any debt covenant is breached. Show as a stress scenario table.'
      ], DESC_ANALYST),
      tool(T_EXCEL, M365_LIC, M365_ACCT, [
        'Open 01_Zava_Group_Financial_Performance.xlsx. Navigate to the risk data section. Ask Copilot: Build a 4-event risk dashboard on a new sheet. For each of the 4 active risk events (coal trading breach, bank NPL, Cilegon enforcement, RSPO suspension), show: (1) Event description, (2) Financial exposure (MYR M), (3) Provision taken, (4) Unresolved exposure, (5) Remediation status (% complete), (6) Board action required (Y/N), (7) Next deadline. Apply RAG status. Add a total group exposure row.',
        'Ask Copilot: Create an Internal Audit progress tracker on a new sheet. For each of the 24 internal audit engagements planned for FY2025 (across 11 divisions), show: (1) Entity and area, (2) Planned start and end date, (3) Status, (4) High/medium/low findings count, (5) Management response received (Y/N), (6) Overdue findings from prior audit. Highlight engagements where the management response is overdue.',
        'Ask Copilot: Build a risk appetite statement dashboard on a new sheet. For each risk category (credit, market, operational, compliance, ESG, strategic), show: (1) Risk appetite statement (one sentence), (2) Key risk metric, (3) Tolerance threshold, (4) Current level, (5) Status (Within / Approaching / Breaching). Flag breaching risks in red.'
      ]),
      tool(T_WORD, M365_LIC, M365_ACCT, [
        'Open 20_Zava_ESG_Sustainability_Framework.docx. Ask Copilot: Draft the Board Risk Committee special meeting report on the 4 concurrent risk events. For each event: (1) 1-paragraph situation summary, (2) Quantified financial exposure, (3) Immediate actions taken, (4) Remediation timeline, (5) Board decision required. Include an opening executive summary covering the aggregate risk exposure and a single recommendation for the Board. 12 pages, formal Board Risk Committee paper format.',
        'Ask Copilot: Draft an update to Zava Group\'s Risk Appetite Statement. Current appetites are defined for 6 risk categories. The 4 active risk events suggest our risk appetite in operational risk and trading was set too broadly. Propose revised appetite thresholds for: (1) Single counterparty trading exposure (reduce from USD 20M to USD 15M), (2) Regulatory enforcement tolerance (zero tolerance for >2 enforcement notices at any single facility), (3) NPL appetite for Zava Bank consumer loans (reduce from 5% to 3.5% triggering immediate CRO notification). Format as a Risk Appetite Statement amendment paper.',
        'Ask Copilot: Draft the Internal Audit findings management letter to the Cilegon Plant Manager on the 3 BPOM enforcement notices. The letter should: summarise the audit findings (control failure in EHS compliance monitoring), list 8 required management actions, set a 60-day deadline for each, and note that a follow-up audit will be conducted within 90 days. Formal audit management letter format.'
      ]),
      tool(T_PPT, M365_LIC, M365_ACCT, [
        'Ask Copilot in PowerPoint: Create an 8-slide Board Risk Committee special meeting deck. Include: (1) Agenda — 4 active risk events, (2) Event 1: Coal Trading Breach — situation, exposure, remediation, (3) Event 2: Zava Bank NPL — situation, provisioning, BNM plan, (4) Event 3: Cilegon Enforcement — situation, corrective action, (5) Event 4: RSPO Suspension — situation, remediation, (6) Combined risk exposure — stress test results, (7) ERM framework gap — what control failed in each event, (8) Board decisions required. Red and white colour scheme — this is a crisis meeting.',
        'Ask Copilot: Create a 2-slide ERM framework gap analysis. Slide 1: For each of the 4 events, identify the specific ERM control that failed — monitoring frequency? Escalation trigger? Risk appetite threshold? Slide 2: The 5 specific ERM enhancements that would have prevented or minimised each event.',
        'Ask Copilot: Create a group risk heat map slide showing 15 key risks on a 5x5 likelihood-impact matrix. Colour the matrix: green (low), yellow (medium), orange (high), red (critical). Mark the 4 active risk events with a special marker showing they have already materialised.'
      ]),
      tool(T_OUTLOOK, M365_LIC, M365_ACCT, [
        'Ask Copilot in Outlook: Draft the CRO\'s notification email to all Division Risk Officers and CEOs announcing the 4 active risk events at Group level. The email should: state that a special Board Risk Committee meeting has been called, request each division to review their own risk registers for similar exposures, and ask for a written risk status update from each division by end of week. Tone: serious, professional, and urgent.',
        'Ask Copilot: Draft the Group Risk Division\'s quarterly update letter to KPMG (external auditors) informing them of the 4 active risk events and the related financial provisions. The letter should disclose: coal trading exposure MYR 28.4M, Zava Bank provision MYR 420M additional, Cilegon production loss estimate MYR 85M, RSPO remediation cost estimate MYR 42M. Request their view on any additional audit procedures required.',
        'Ask Copilot: Draft the CRO\'s email to the internal audit team instructing a special unplanned audit of the Group Trading Desk following the coal trading limit breach. The audit should cover: position limit monitoring controls, daily mark-to-market reporting process, Risk Committee escalation procedures, and the approval process for limit increases. Timeline: 3-week fieldwork, report in 6 weeks.'
      ]),
      tool(T_TEAMS, M365_LIC, M365_ACCT, [
        'Open an existing recorded Teams meeting recap from a risk committee or crisis management meeting. Ask Copilot: Identify all risk events discussed, risk mitigation actions committed, and any decisions made about escalation or disclosure. Create an action tracker.',
        'Ask Copilot: Draft the post-meeting risk management team follow-up actions. Group by risk event: Trading Breach | Bank NPL | Cilegon Enforcement | RSPO. Include action, owner, and deadline.',
        'Ask Copilot: From this meeting, which Board members expressed the most concern about the combined risk exposure? What additional information did they request before the next Board meeting?'
      ], DESC_TEAMS),
      tool(T_NOTEBOOK, M365_LIC, M365_ACCT, [
        'Upload 01_Zava_Group_Financial_Performance.xlsx and 20_Zava_ESG_Sustainability_Framework.docx to Copilot Notebook. Set instruction: "You are the Group CRO preparing for the Board Risk Committee special meeting." Ask: Which of the 4 active risk events poses the highest systemic risk to the group — considering financial exposure, regulatory implications, reputation impact, and speed of escalation? What is the single most important decision the Board must make at Monday\'s special meeting?',
        'Upload 20_Zava_ESG_Sustainability_Framework.docx. Ask: Our ERM framework last had a full refresh in 2021. The 4 concurrent risk events suggest the framework has gaps. Identify the 5 most critical ERM framework improvements that would have provided earlier warning of these 4 events. Prioritise by ease of implementation and impact.'
      ], DESC_NOTEBOOK),
      tool(T_COWORK, FRONTIER_LIC, M365_ACCT, [
        'Do all of the following immediately: (1) Research how comparable ASEAN conglomerates have responded to simultaneous multi-division risk events — identify best practice from Sime Darby or Axiata crisis management. (2) Draft a 2-page crisis risk management protocol for the Group CRO to activate when 3 or more major risk events are active simultaneously. (3) Save to OneDrive as "Group Crisis Risk Protocol". (4) Email to CRO and GC for review. (5) Schedule a crisis management taskforce meeting with all Division CROs for tomorrow.',
        'Do all of the following for the Board Risk Committee meeting: (1) Compile the 4 active risk event summaries from the divisional CROs into one master Board Risk Committee brief. (2) Calculate the combined worst-case financial exposure. (3) Create a colour-coded risk dashboard for the Board presentation. (4) Email to Board Secretary for inclusion in the Board papers. (5) Schedule a 1-hour pre-Board CRO briefing with the Chairman of the Risk Committee.'
      ], DESC_COWORK),
      tool(T_WORD_AGT, M365_LIC, M365_ACCT, [
        'Open 20_Zava_ESG_Sustainability_Framework.docx in Word for Web. Create an agent called "Zava Group Risk & Audit Policy Bot". Description: "Answers questions from Division Risk Officers, Internal Auditors, and business leaders on the ERM framework, risk appetite thresholds, internal audit procedures, escalation requirements, and regulatory compliance obligations." Share with all Division Risk Officers.',
        'Demo: A Division Risk Officer asks "Our plantation division has just received its 2nd BPOM enforcement notice this year. Under the Group Risk Appetite Statement, does a 2nd enforcement notice at a single facility trigger mandatory escalation to Group CRO? And what is the timeframe for the escalation?" Show the agent providing a policy-grounded, escalation-clear risk management answer.'
      ], DESC_WORD_AGT),
      tool(T_PPT_AGT, M365_LIC, M365_ACCT, [
        'Create a PowerPoint from the Board Risk Committee presentation. Create an agent called "Board Risk Committee Q&A Bot". Share with Board Risk Committee members.',
        'Demo: A Board member asks "If the RSPO suspension at Perkebunan Lestari continues for 18 months instead of 6, what is the additional financial impact and does it change our FY2025 EBITDA guidance?" Show the agent providing a risk-scenario-grounded financial impact answer.'
      ], DESC_PPT_AGT),
      tool(T_XL_AGT, M365_LIC, M365_ACCT, [
        'Open 01_Zava_Group_Financial_Performance.xlsx in Excel for Web. Create an agent called "Group Risk Dashboard Q&A". Description: "Instant answers on active risk events, financial exposures, ERM risk register status, and internal audit findings for the CRO and Board Risk Committee." Share with risk leadership.',
        'Demo: Ask "What is the combined worst-case financial exposure from all 4 active risk events if none are resolved?" Then: "Which division has the highest number of overdue internal audit findings and what is the total value at risk from those findings?" Show the CRO getting instant risk intelligence.'
      ], DESC_XL_AGT),
      tool(T_BUILDER, M365_LIC, M365_ACCT, [
        'Go to copilotstudio.microsoft.com > Create > New Agent. Name it "Zava Risk Intelligence Agent". Description: "Supports the Group CRO, Division Risk Officers, and Internal Audit with instant answers on risk event status, ERM framework requirements, risk appetite thresholds, audit procedures, and regulatory compliance obligations — enabling faster, more consistent risk management decisions across all 11 Zava divisions." Upload 01_Zava_Group_Financial_Performance.xlsx and 20_Zava_ESG_Sustainability_Framework.docx. Add topics: "Risk Events", "ERM Framework", "Internal Audit", "Risk Appetite", "Regulatory Compliance". Publish to Teams for risk and audit teams.',
        'Demo the agent: The Group CRO receives an urgent Saturday morning call from the Cilegon Plant Manager: the plant has just received a 4th BPOM enforcement notice — this time for an accidental chemical release that requires a 72-hour production shutdown. The CRO asks the agent: "Under our ERM escalation protocol, does a 4th enforcement notice at the same facility triggering a production shutdown require immediate Board notification? What is the maximum financial exposure from a 72-hour shutdown and does this breach our operational risk appetite threshold?" Show the agent enabling a swift, policy-grounded crisis response decision.'
      ], DESC_BUILDER),
    ]),

# ── STRATEGY & M&A ────────────────────────────────────────────────────────
ind('dept-strategy','department','Strategy & M&A','🎯','#E65100','#F57C00',
    'Zava Group Holdings — Group Strategy Division',
    'ZAVA FORWARD 2030 — 4 healthcare M&A targets, REIT IPO, pharma Vietnam expansion.',
    'The Group Strategy Division drives the ZAVA FORWARD 2030 strategic plan — 5 pillars, MYR 12.4B capex over 5 years. Current M&A pipeline: 4 healthcare targets in evaluation (PrimeCare Holdings being the priority), REIT IPO 2026, Pharma expansion into Vietnam and Philippines. Divestment: 2 non-core assets identified.',
    ['04_Zava_MA_Evaluation_Framework.docx','01_Zava_Group_Financial_Performance.xlsx'],
    [
      tool(T_CHAT, FREE_LIC, FREE_ACCT, [
        'I am the Group Chief Strategy Officer of a MYR 45B ASEAN conglomerate. We have 4 healthcare M&A targets in active evaluation. Our Board has set a strict criteria: deals must be EPS-accretive within 3 years and ROIC must exceed our WACC of 9.2% by Year 5. Draft a 250-word brief explaining: (1) How to determine if a healthcare acquisition is EPS-accretive within 3 years — key assumptions needed, (2) How ROIC is calculated for an M&A deal and what synergies count towards ROIC, (3) Why the healthcare sector commands a premium valuation multiple and whether the premium is justified given our strategic rationale.',
        'Explain what a strategic portfolio review is for a diversified conglomerate. How should a Board decide which businesses to grow, hold, or divest? What frameworks (GE-McKinsey, BCG matrix) are most useful and how are they adapted for a conglomerate with 11 divisions?',
        'What does "ZAVA FORWARD 2030" as a strategic plan need to include to be credible to institutional investors and analysts? What are the 5 most important components of a well-structured 5-year conglomerate strategy and how should it be communicated on Investor Day?'
      ]),
      tool(T_RESEARCHER, M365_LIC, M365_ACCT, [
        'Research the Southeast Asian private hospital and healthcare M&A market. I need: (1) Current EV/EBITDA multiples for hospital acquisitions in Malaysia and Indonesia, (2) Key strategic rationale for conglomerate hospital investments — IHH, Columbia Asia, Pantai, (3) How healthcare M&A deals are structured in Malaysia (acquisition of shares vs assets, minority buy-in vs full acquisition). Cite Mergermarket or healthcare sector M&A reports.',
        'Research Vietnam pharma market entry strategies for Malaysian generic drug manufacturers. What are the licensing requirements from the DAV (Drug Administration of Vietnam)? Who are the existing Malaysian pharma companies in Vietnam and what entry mode did they use (greenfield, JV, acquisition, distributor)? Cite industry sources.'
      ], DESC_RESEARCHER),
      tool(T_ANALYST, M365_LIC, M365_ACCT, [
        'Upload 04_Zava_MA_Evaluation_Framework.docx and 01_Zava_Group_Financial_Performance.xlsx. Ask Analyst: Evaluate the 4 healthcare M&A targets against the 7-category framework. Score each target on: (1) Strategic fit (1-5), (2) Financial performance — EBITDA margin and growth, (3) Integration complexity, (4) Price vs comparable transactions, (5) Management quality, (6) Regulatory risk, (7) ESG profile. Rank the 4 targets from most to least attractive. Identify which target best meets our ROIC>WACC threshold by Year 5.',
        'Upload 01_Zava_Group_Financial_Performance.xlsx. Ask: Build an M&A deal capacity analysis. Current net debt MYR 18.4B, EBITDA MYR 7.2B, gearing 0.82x. Covenant: net debt/EBITDA < 3.5x. Assuming we maintain gearing below 2.5x (conservative target), what is the maximum deal size we can fund with: (1) 100% debt financing, (2) 70% debt / 30% equity (rights issue or new shares), (3) Using REIT IPO proceeds as partial funding? Calculate for each.'
      ], DESC_ANALYST),
      tool(T_EXCEL, M365_LIC, M365_ACCT, [
        'Open 01_Zava_Group_Financial_Performance.xlsx. Navigate to the M&A sheet. Ask Copilot: Build a deal scorecard on a new sheet for the 4 healthcare targets. For each target, show: (1) Enterprise value (MYR M), (2) EV/EBITDA multiple paid, (3) Revenue and EBITDA (current year), (4) Projected Year 3 EBITDA with synergies, (5) EPS accretion in Year 3 (bps), (6) ROIC at Year 5 vs WACC 9.2%, (7) Recommended action (Proceed / Further Diligence / Pass). Apply colour coding.',
        'Ask Copilot: Create a strategic portfolio matrix on a new sheet. For each of the 11 Zava divisions, plot on a 3x3 McKinsey matrix (Industry Attractiveness vs Business Unit Strength). Classify each as Grow (top-right), Hold (diagonal), or Divest (bottom-left). For the 2 non-core assets identified for divestment, calculate estimated divestment proceeds and the use of proceeds.',
        'Ask Copilot: Build a ZAVA FORWARD 2030 capex tracker. For MYR 12.4B total capex over 5 years, show allocation by: (1) Division (Healthcare expansion MYR 3.2B, Properties REIT MYR 1.4B, Pharma MYR 0.8B, Manufacturing upgrade MYR 1.6B, Digital transformation MYR 0.9B, others), (2) Year, (3) Funding source (own cash, debt, REIT IPO proceeds). Show cumulative capex vs budget by year.'
      ]),
      tool(T_WORD, M365_LIC, M365_ACCT, [
        'Open 04_Zava_MA_Evaluation_Framework.docx. Ask Copilot: Update the M&A Evaluation Framework to add a new ESG scoring category. The new category should include: (1) GHG Scope 1/2 intensity vs sector benchmark, (2) RSPO/ISPO certification status if plantation involved, (3) Labour practices and human rights screening, (4) Governance quality — independent directors, related party transaction history, (5) EUDR compliance if applicable. Assign a 15% weight to ESG in the overall deal score. Revise the framework document accordingly.',
        'Ask Copilot: Draft the Executive Summary of the PrimeCare Holdings M&A Information Memorandum. The IM should cover: (1) Transaction overview — Zava Group\'s proposed acquisition of 60% equity stake, (2) PrimeCare overview — 8 hospitals, MYR 680M revenue, 14.2% EBITDA margin, (3) Strategic rationale — accelerates Zava Healthcare to 18 hospitals, fills MY Central region gap, (4) Valuation — MYR 1.84B EV at 11.2x EV/EBITDA, (5) Deal structure — MYR 1.1B upfront, MYR 280M deferred, (6) Key conditions — regulatory approval, CIMSA accreditation maintained. 4 pages, investment banking IM style.',
        'Ask Copilot: Draft the Board paper recommending approval of the PrimeCare acquisition. Cover: strategic rationale, financial impact (EPS accretion Year 3), deal structure, risk factors and mitigants, WACC vs ROIC analysis, regulatory approval timeline, and the Board resolution requested. 15 pages, formal Board paper.'
      ]),
      tool(T_PPT, M365_LIC, M365_ACCT, [
        'Ask Copilot in PowerPoint: Create a 14-slide Investor Day strategy presentation for ZAVA FORWARD 2030. Include: (1) Group overview — MYR 44.8B, 11 divisions, (2) Market context — ASEAN growth outlook, (3) 5 strategic pillars, (4) Portfolio optimisation — grow, hold, divest decisions, (5) Healthcare M&A — pipeline and PrimeCare, (6) Properties REIT IPO 2026, (7) Pharma expansion — Vietnam and Philippines, (8) Digital transformation, (9) ESG leadership, (10) Capital allocation — MYR 12.4B, (11) 5-year financial targets, (12) Dividend policy, (13) Key risks and mitigants, (14) Summary — why Zava Group is the ASEAN conglomerate to own. Dark navy and gold.',
        'Ask Copilot: Create a 5-slide M&A strategy summary for the Board\'s Strategy & Investment Committee. Slide 1: M&A deal capacity. Slides 2-5: Each of the 4 healthcare targets — one slide each with scorecard, recommendation, and key condition.',
        'Ask Copilot: Create a 3-slide Vietnam pharma market entry analysis. Slide 1: Vietnam pharma market — size, growth, key therapeutic areas. Slide 2: Entry options — JV vs greenfield vs acquisition, comparing speed, cost, and risk. Slide 3: Recommended entry mode and 24-month implementation plan.'
      ]),
      tool(T_OUTLOOK, M365_LIC, M365_ACCT, [
        'Ask Copilot in Outlook: Draft a Non-Disclosure Agreement cover letter to PrimeCare Holdings\' CEO proposing the commencement of due diligence. The letter should: confirm our interest in exploring a 60% equity acquisition, request execution of the mutual NDA, and propose a 2-week timeline for the management presentation. Confidential, professional M&A engagement letter tone.',
        'Ask Copilot: Draft the strategy communication to all Division CEOs following the ZAVA FORWARD 2030 Investor Day. The email should: summarise the 5 strategic pillars as they apply to each division, confirm the individual division capex allocation, and call for division 3-year operating plans to be submitted within 6 weeks. Energising, leadership tone.',
        'Ask Copilot: Draft an email to our financial advisors (Goldman Sachs and Maybank Investment Bank) confirming the mandate for the PrimeCare M&A advisory engagement. Confirm: deal structure, advisory fee structure (retainer MYR 180K/month + success fee 0.8% of deal value), milestones for success fee trigger, and the 6-month exclusivity period.'
      ]),
      tool(T_TEAMS, M365_LIC, M365_ACCT, [
        'Open an existing recorded Teams meeting recap from a strategy or M&A committee meeting. Ask Copilot: Identify all M&A target discussions, deal structure debates, and strategic divestment mentions. Extract the 3 most important decisions made and the follow-up actions for the deal team.',
        'Ask Copilot: Draft the M&A deal team weekly update. Structure: (1) PrimeCare — due diligence status, (2) 3 other targets — preliminary status, (3) Regulatory approval timeline, (4) Board paper preparation timeline, (5) Financial advisor engagement.',
        'Ask Copilot: From this meeting, what concerns did the CFO raise about the combined M&A capacity? What was the debate about whether to proceed with 1 deal now or to wait until the REIT IPO proceeds are available?'
      ], DESC_TEAMS),
      tool(T_NOTEBOOK, M365_LIC, M365_ACCT, [
        'Upload 04_Zava_MA_Evaluation_Framework.docx and 01_Zava_Group_Financial_Performance.xlsx to Copilot Notebook. Set instruction: "You are advising the Group CSO on the healthcare M&A strategy." Ask: Based on the evaluation framework and financial capacity, should Zava Group proceed with the PrimeCare acquisition now or wait 12 months until the REIT IPO proceeds are available to reduce the debt financing proportion? What is the quantified cost/benefit of waiting?',
        'Upload 04_Zava_MA_Evaluation_Framework.docx. Ask: One of the 4 healthcare M&A targets is a Shariah-compliant hospital group in Malaysia. They require that any acquisition be structured using Islamic financing (Sukuk) and that the hospital operations maintain JAKIM halal certification. How does this constraint affect our deal structure and ROIC calculation? Does an Islamic deal structure typically deliver a better or worse outcome for the acquirer than conventional financing at our current cost of debt of 5.8%?'
      ], DESC_NOTEBOOK),
      tool(T_COWORK, FRONTIER_LIC, M365_ACCT, [
        'Do all of the following for PrimeCare M&A: (1) Research PrimeCare Holdings\' publicly available information — financial performance, hospital locations, JCI accreditation status, and any news in the past 12 months. (2) Draft a 3-page target profile summary. (3) Create a PrimeCare due diligence data room structure in SharePoint with 12 folders covering all due diligence workstreams. (4) Email to the M&A deal team lead, GC, and CFO confirming the data room structure and access permissions. (5) Schedule a weekly M&A deal team meeting for 20 weeks.',
        'Do all of the following for ZAVA FORWARD 2030 Investor Day: (1) Research the top 10 questions that ASEAN conglomerate analysts ask at strategy Investor Days — compile from Morgan Stanley, UBS, and CIMB research. (2) Draft a 2-page investor Q&A preparation guide for the CEO and CFO covering the 10 most challenging anticipated questions. (3) Save to OneDrive as "Investor Day Q&A Prep - CONFIDENTIAL". (4) Email to CEO, CFO, and Head of IR for review. (5) Schedule a 3-hour investor day rehearsal 2 weeks before the event.'
      ], DESC_COWORK),
      tool(T_WORD_AGT, M365_LIC, M365_ACCT, [
        'Open 04_Zava_MA_Evaluation_Framework.docx in Word for Web. Create an agent called "Zava M&A Strategy Bot". Description: "Answers questions from the Group Strategy and M&A team on the M&A evaluation framework, deal scoring methodology, healthcare sector M&A norms, regulatory approval requirements, and ZAVA FORWARD 2030 strategic priorities." Share with the Strategy and M&A team.',
        'Demo: An M&A analyst asks "Our second-ranked target has a 38% founding family minority stake. They have refused drag-along rights and want a preferred dividend of 8% before common shareholders. How does this minority shareholder structure affect our ROIC calculation and does it change our deal recommendation?" Show the agent providing a deal-structure-aware M&A answer.'
      ], DESC_WORD_AGT),
      tool(T_PPT_AGT, M365_LIC, M365_ACCT, [
        'Create a PowerPoint from the Investor Day presentation. Create an agent called "ZAVA FORWARD 2030 Investor Q&A Bot". Share with institutional investors and the IR team.',
        'Demo: An analyst asks "Your 5-year capex is MYR 12.4B against current EBITDA of MYR 7.2B. That\'s nearly 2x EBITDA. How do you fund this without breaching your 2.5x gearing target and why should shareholders not expect a rights issue?" Show the agent providing a capital-allocation-grounded answer to a tough Investor Day question.'
      ], DESC_PPT_AGT),
      tool(T_XL_AGT, M365_LIC, M365_ACCT, [
        'Open 01_Zava_Group_Financial_Performance.xlsx in Excel for Web. Create an agent called "Zava Strategy & M&A Q&A". Description: "Instant answers on M&A deal capacity, portfolio matrix scores, capex allocation, ZAVA FORWARD 2030 targets, and deal scoring for the CSO, CFO, and M&A team." Share with the strategy leadership.',
        'Demo: Ask "What is our current M&A deal capacity in MYR M if we maintain gearing below 2.5x?" Then: "Based on the deal scoring, which of the 4 healthcare targets has the highest ROIC vs WACC by Year 5?" Show the CSO getting instant strategic portfolio intelligence.'
      ], DESC_XL_AGT),
      tool(T_BUILDER, M365_LIC, M365_ACCT, [
        'Go to copilotstudio.microsoft.com > Create > New Agent. Name it "Zava Strategy Intelligence Agent". Description: "Supports the Group Strategy and M&A team with instant answers on M&A evaluation criteria, deal capacity, ZAVA FORWARD 2030 strategic priorities, portfolio matrix scores, healthcare sector norms, and pharma expansion requirements — enabling faster, smarter strategic decisions across the Zava Group." Upload 04_Zava_MA_Evaluation_Framework.docx and 01_Zava_Group_Financial_Performance.xlsx. Add topics: "M&A Evaluation", "Portfolio Strategy", "Healthcare Expansion", "Pharma", "REIT IPO". Publish to Teams for the Strategy Division.',
        'Demo the agent: The Group CSO gets a call from a Goldman Sachs banker at 6pm on a Friday: "A distressed hospital group with 12 hospitals in Peninsular Malaysia has just hired us. Their Board is looking for a buyer within 90 days. EV is approximately MYR 2.1B. Given your publicly stated healthcare strategy, would Zava Group be interested?" The CSO asks the agent: "How does a MYR 2.1B deal for a 12-hospital group compare to our 4 existing targets on EV/hospital metrics? Do we have the balance sheet capacity without a rights issue? And does the 90-day timeline leave enough time for our M&A evaluation and Board approval process?" Show how the agent enables an instant, data-backed strategic response call.'
      ], DESC_BUILDER),
    ]),
]

print(f"Departments 2 written: {len(DEPARTMENTS_2)} entries")
