
import sys; sys.path.insert(0,'.')
from util import *

DEPARTMENTS = [

# ── HUMAN RESOURCES ───────────────────────────────────────────────────────
ind('dept-hr','department','Human Resources','👥','#1565C0','#1976D2',
    'Zava Group Holdings — Group HR Division',
    '87,000 employees, 32% BPO attrition crisis, ESG DEI targets, plantation replanting displacement.',
    'The Group HR Division manages talent strategy, compensation, and people analytics for 87,420 employees across 11 divisions and 3 countries. Critical issues: Bengaluru BPO attrition at 31.2%, plantation estate worker displacement from replanting, Zava Bank losing talent to fintech, and new DEI commitment (40% women leadership by 2028).',
    ['18_Zava_HR_Analytics.xlsx','02_Zava_Group_Policy_Handbook.docx'],
    [
      tool(T_CHAT, FREE_LIC, FREE_ACCT, [
        'I am the Group CHRO of a Malaysian conglomerate with 87,420 employees. Our BPO division in Bengaluru has 31.2% annual attrition — one of the highest in our group. Research shows the main causes are: IT sector salary competition, limited career progression, and remote work policy restrictions. Draft a 250-word retention strategy brief for the BPO MD covering: 3 immediate retention levers, 2 medium-term structural changes, and how we measure success in 12 months.',
        'What is the HR analytics maturity model and where should a large conglomerate HR function be on that model? We currently use basic headcount and attrition reports. What are the 5 most impactful people analytics use cases for a 87,000-employee conglomerate?',
        'Explain what a 40% women in leadership target means in practice. How do leading Malaysian conglomerates measure "leadership" — is it C-suite only, all management grades, or a specific band? What policies and programmes have proven most effective at closing the gender leadership gap in Asian corporate settings?'
      ]),
      tool(T_RESEARCHER, M365_LIC, M365_ACCT, [
        'Research BPO industry attrition best practices in India (Bengaluru, Hyderabad, Chennai). What attrition benchmarks exist for Malaysian-owned BPO operators in India? What retention programmes have worked for mid-size BPO companies competing with IT majors like Infosys and Wipro? Cite industry reports.',
        'Research DEI (Diversity, Equity, Inclusion) best practices in Malaysian GLCs and conglomerates. What are the most effective programmes for increasing women in senior leadership? How have companies like Maybank, Sime Darby, and Petronas progressed on their DEI targets? Cite MSWG or MyCERT data.'
      ], DESC_RESEARCHER),
      tool(T_ANALYST, M365_LIC, M365_ACCT, [
        'Upload 18_Zava_HR_Analytics.xlsx to Analyst. Ask: Run an attrition regression analysis. Which factors (salary vs benchmark, commute distance, team size, manager tenure) correlate most strongly with attrition across divisions? For the BPO Bengaluru centre, identify the 3 highest-risk employee segments — rank by predicted attrition probability. Create a risk heatmap: X-axis = grade, Y-axis = years of service.',
        'Upload 18_Zava_HR_Analytics.xlsx. Ask: Build a succession planning gap analysis. For C5-C7 grade positions across the 11 divisions, how many have a ready successor identified vs no successor? Calculate the bench strength ratio (successors/positions). Identify the 5 most critical "succession desert" roles — high business impact, no successor. Create a visual showing the succession pipeline strength by division.'
      ], DESC_ANALYST),
      tool(T_EXCEL, M365_LIC, M365_ACCT, [
        'Open 18_Zava_HR_Analytics.xlsx. Navigate to the Attrition Analysis sheet. Ask Copilot: Build a compensation benchmark dashboard on a new sheet. For each grade (C1-C7) and country (MY, ID, IN), show: (1) Current median salary at Zava, (2) Market median salary (sourced from Aon Hewitt or Mercer benchmark), (3) Compa-ratio (our median / market median), (4) % below market, (5) RAG status: green (90-110% of market), amber (80-89%), red (<80%). Highlight any grade/country where we are more than 15% below market.',
        'Ask Copilot: Create a DEI progress tracker on a new sheet. For each division and each management grade (C5+), show: (1) Total positions, (2) Women in role, (3) Women %, (4) Target %, (5) Gap to target (positions needed). Sum to group level. Calculate how many women need to be promoted to C5+ to reach the 40% target by 2028 — assuming 3% annual promotion pool.',
        'Ask Copilot: Build a learning & development ROI dashboard. For each training programme in FY2024 (leadership, technical, compliance, DEI), show: (1) Participants, (2) Cost per participant (MYR), (3) Total cost (MYR M), (4) 90-day retention rate post-training vs non-participants, (5) Productivity score change (if measured), (6) Estimated ROI. Rank by ROI and flag any programme with negative ROI.'
      ]),
      tool(T_WORD, M365_LIC, M365_ACCT, [
        'Open 02_Zava_Group_Policy_Handbook.docx. Ask Copilot: Draft a new chapter "AI & Copilot Usage Policy" for the Policy Handbook. Cover: (1) Approved AI tools — Microsoft 365 Copilot and its applications, (2) Prohibited uses — sharing confidential data, generating misleading content, bypassing compliance review, (3) Prompt writing guidelines — GCSE framework, (4) Data classification rules — what data may be used as Copilot context, (5) Responsibility — employee accountability for AI-generated output, (6) Training requirement — all employees must complete the Zava AI Literacy module before using Copilot. 4 pages, policy format.',
        'Ask Copilot: Draft a Group HR communication to all 87,420 employees (filtered for managers C5+) announcing the Microsoft 365 Copilot rollout. The email should: explain what Copilot is in simple terms, note the 3 key benefits for their day-to-day work, announce the training schedule (2-hour mandatory session within 30 days), and share 3 simple use cases from the HR function — drafting JDs, analysing attrition data, and summarising engagement surveys. Engaging, positive tone.',
        'Ask Copilot: Draft the Zava Group FY2025 Annual Workforce Report (30 pages). Cover all sections: Headcount summary by division and country, Attrition analysis, Compensation benchmarking, DEI progress, L&D investment, Safety statistics, Employee engagement score, Talent pipeline, and People strategy outlook. Use data from the HR Analytics file.'
      ]),
      tool(T_PPT, M365_LIC, M365_ACCT, [
        'Ask Copilot in PowerPoint: Create a 10-slide Group HR presentation for the Board. Include: (1) Workforce overview — 87,420 employees, (2) Attrition crisis — BPO Bengaluru 31.2%, (3) Retention programme — cost and expected impact, (4) Compensation benchmarking — 3 grades below market, (5) DEI progress — 28% women in leadership vs 40% target, (6) L&D investment — ROI by programme, (7) Succession planning — bench strength by division, (8) People analytics upgrade — 3-year roadmap, (9) FY2026 HR priorities, (10) Board decisions. Blue and white colour scheme.',
        'Ask Copilot: Create a 2-slide M365 Copilot for HR use case pitch. Slide 1: 5 HR use cases with Copilot (JD generation, attrition analysis, engagement survey synthesis, policy update drafting, exit interview summarisation) — each with time saved per month. Slide 2: Investment vs time savings ROI calculation — show payback in months.',
        'Ask Copilot: Create a DEI roadmap slide showing the 2025-2028 timeline with 4 milestones: 30% women in leadership (FY2025), 35% (FY2026), 38% (FY2027), 40% (FY2028). Show current position at 28% and the specific programmes at each milestone that will drive progress.'
      ]),
      tool(T_OUTLOOK, M365_LIC, M365_ACCT, [
        'Ask Copilot in Outlook: Draft an email to all BPO Bengaluru team leaders and managers (620 people) announcing the new retention programme. The email should: acknowledge the high attrition and thank existing employees for their commitment, announce the 3 new retention benefits (12-month cliff bonus, remote work 3 days/week, accelerated career track programme), state the effective date (1 month from today), and invite questions at the Q&A session next Friday. Warm, human tone.',
        'Ask Copilot: Draft a targeted email to our 148 employees at Bengaluru who have been with Zava BPO for 3+ years. The email should: personalise the opening ("You have been with us for over 3 years — and that means a great deal"), announce the senior employee retention benefit (additional 10% salary uplift for C2-C3 staff with 3+ years tenure), and express genuine appreciation. CONFIDENTIAL — only for this segment.',
        'Ask Copilot: Draft a letter to the estate worker union representatives at Ladang Sri Murni (Sarawak) regarding the replanting programme that will displace 240 workers for 18 months. The letter should: explain the replanting necessity (aging palms, declining yield), outline the 18-month support package (housing maintained, 85% salary retention), describe the retraining options (machinery operation, safety certification), and note the priority re-hire commitment. Empathetic, respectful tone.'
      ]),
      tool(T_TEAMS, M365_LIC, M365_ACCT, [
        'Open an existing recorded Teams meeting recap from an HR leadership or town hall meeting. Ask Copilot: Identify all workforce concerns discussed — attrition, compensation, DEI, L&D. Create an action tracker for the CHRO team with owner and deadline.',
        'Ask Copilot: Draft follow-up actions from the quarterly HR leadership review. Group by workstream: Attrition & Retention | Compensation Benchmarking | DEI | L&D | People Analytics. Include HRBP owner and deadline.',
        'Ask Copilot: Were there any discussions about the BNM salary increase for bank officers affecting Zava Bank\'s ability to retain staff? What retention measures were proposed and what is the budget implication?'
      ], DESC_TEAMS),
      tool(T_NOTEBOOK, M365_LIC, M365_ACCT, [
        'Upload 18_Zava_HR_Analytics.xlsx and 02_Zava_Group_Policy_Handbook.docx to Copilot Notebook. Set instruction: "You are the Group CHRO preparing the people strategy for the Board." Ask: Based on the workforce data and company policies, what is the single biggest talent risk facing Zava Group in FY2026? What is the recommended 90-day action plan to address it?',
        'Upload 18_Zava_HR_Analytics.xlsx. Ask: Our replacement cost is MYR 1.5x annual salary per departing employee. The Bengaluru BPO has 2,960 staff with 31.2% attrition. Calculate the annual turnover cost. If a retention programme costing MYR 8.4M reduces attrition to 22%, calculate the net saving and the ROI of the retention investment.'
      ], DESC_NOTEBOOK),
      tool(T_COWORK, FRONTIER_LIC, M365_ACCT, [
        'Do all of the following: (1) Research salary benchmarks for BPO analysts and senior analysts in Bengaluru for 2025 — compare to Infosys, Wipro, and TCS. (2) Identify the 3 salary grades where Zava BPO is most below market. (3) Draft a compensation correction proposal for CFO approval — estimated cost MYR 14.2M annually. (4) Email to CHRO and CFO asking for an urgent review before the Q2 compensation review cycle. (5) Schedule a compensation committee meeting within 2 weeks.',
        'Do all of the following for DEI: (1) Research the most effective sponsorship and mentoring programmes for women in leadership in Malaysian corporates. (2) Draft a "Zava Women in Leadership" programme design covering: sponsorship programme, accelerated development track, external Board director placement, and flexible work policy. (3) Save to OneDrive as "Zava Women in Leadership Programme". (4) Email to the CHRO and Group CEO for approval. (5) Schedule a DEI taskforce kickoff meeting with Division HRBPs.'
      ], DESC_COWORK),
      tool(T_WORD_AGT, M365_LIC, M365_ACCT, [
        'Open 02_Zava_Group_Policy_Handbook.docx in Word for Web. Create an agent called "Zava Group HR Policy Bot". Description: "Answers questions from managers, HRBPs, and employees across all 11 divisions on HR policies, compensation bands, leave entitlements, performance management, DEI commitments, and people processes — ensuring consistent policy application across 87,420 employees." Share with all 11 Division HRBPs and publish to the employee portal.',
        'Demo: A Line Manager at Zava Bank asks "I want to put my team member on a Performance Improvement Plan (PIP). She has been underperforming for 3 months but she is also 4 months pregnant. What are the HR policy requirements for issuing a PIP, and are there any special considerations or protections that apply during pregnancy?" Show how the agent provides a policy-grounded, legally-aware HR guidance answer that protects both the employee and the company.'
      ], DESC_WORD_AGT),
      tool(T_PPT_AGT, M365_LIC, M365_ACCT, [
        'Create a PowerPoint from the Board HR presentation. Create an agent called "Group HR Board Q&A Bot". Share with Board members and the Group CEO.',
        'Demo: A Board member asks "Our BPO Bengaluru attrition is the highest in the group. If it stays at 31.2%, how long until we lose the senior talent required to maintain the PETRONAS Chemicals BPO contract — and what is the revenue risk?" Show the agent providing a workforce-risk-to-commercial-risk answer.'
      ], DESC_PPT_AGT),
      tool(T_XL_AGT, M365_LIC, M365_ACCT, [
        'Open 18_Zava_HR_Analytics.xlsx in Excel for Web. Create an agent called "Group HR Analytics Q&A". Description: "Instant answers on headcount, attrition, compensation benchmarking, DEI progress, and L&D ROI for the CHRO, Group CEO, and Division HRBPs." Share with HR leadership.',
        'Demo: Ask "Which division has the highest attrition-related replacement cost this year and what is the MYR amount?" Then: "How many women are currently in C5+ leadership roles and how many more need to be promoted each year to reach the 40% target by 2028?" Show the CHRO getting instant people analytics intelligence.'
      ], DESC_XL_AGT),
      tool(T_BUILDER, M365_LIC, M365_ACCT, [
        'Go to copilotstudio.microsoft.com > Create > New Agent. Name it "Zava Group HR Intelligence Agent". Description: "The Group HR team\'s intelligent assistant — answers questions on workforce analytics, policy interpretation, compensation benchmarking, DEI progress, and talent risk across all 11 divisions and 87,420 employees. Helps HR leaders make faster, more consistent, data-driven people decisions." Upload 18_Zava_HR_Analytics.xlsx and 02_Zava_Group_Policy_Handbook.docx. Add topics: "Compensation & Benefits", "Attrition & Retention", "DEI", "Policy Guidance", "Succession Planning". Publish to Teams for HR leaders.',
        'Demo the agent: The CHRO is in a Board meeting when a director asks an unexpected question: "We have 87,420 employees but our revenue per employee is only MYR 513K — how does that compare to similar conglomerates and which of our 11 divisions is the most and least productive on a revenue-per-employee basis?" The CHRO discreetly asks the HR agent on their phone and gets an instant, data-backed answer to share with the Board.'
      ], DESC_BUILDER),
    ]),

# ── FINANCE ───────────────────────────────────────────────────────────────
ind('dept-finance','department','Finance & Treasury','💰','#1B5E20','#2E7D32',
    'Zava Group Holdings — Group Finance Division',
    'MYR 18.4B net debt, FOREX hedging 11 currencies, NPL breach remediation, REIT IPO structuring.',
    'The Group Finance Division manages group treasury, reporting, tax, and investor relations. Net debt is MYR 18.4B at 0.82x gearing. FOREX exposure spans MYR, IDR, USD, SGD, INR, and 6 other currencies. Group CFO Hadar Caspit is preparing the FY2025 half-year results, the REIT IPO financial model, and the BNM remediation plan for Zava Bank.',
    ['01_Zava_Group_Financial_Performance.xlsx','03_Zava_Group_Strategy_Framework.docx'],
    [
      tool(T_CHAT, FREE_LIC, FREE_ACCT, [
        'I am the Group CFO of a MYR 44.8B revenue conglomerate with MYR 18.4B net debt. Our gearing is 0.82x net debt/EBITDA. Our debt covenants require us to maintain gearing below 3.5x on a net debt/EBITDA basis — we are well within that. However, 2 divisions are underperforming and the Zava Bank NPL issue has increased provisioning costs by MYR 420M. Draft a 250-word brief for the Board\'s Audit Committee covering: (1) The current group financial position, (2) The impact of Zava Bank provisioning on group PAT, (3) The FOREX exposure — 11 currencies, largest being IDR (MYR 2.1B equivalent), (4) The hedge ratio and our FOREX hedging strategy.',
        'Explain how a conglomerate treasury manages FOREX risk across 11 operating currencies. What is a natural hedge and when is it insufficient? What derivative instruments (forwards, options, cross-currency swaps) are appropriate for each currency pair in a Malaysian conglomerate with significant IDR and USD exposure?',
        'What is a REIT IPO financial model? How does a property company calculate the NAV per unit, distribution per unit (DPU), and target IPO price for a REIT? What are the key inputs — NOI, cap rate, gearing, distribution rate — and how does the REIT IPO price relate to NAV?'
      ]),
      tool(T_RESEARCHER, M365_LIC, M365_ACCT, [
        'Research the current Malaysian ringgit (MYR) and Indonesian rupiah (IDR) outlook for FY2025-FY2026. I need: (1) Consensus MYR/USD and IDR/USD forecasts from investment banks, (2) Key risk factors — US Fed policy, Bank Negara Malaysia stance, oil prices, (3) How other Malaysian conglomerates with significant IDR exposure are managing FOREX risk. Cite Bloomberg consensus or investment bank research.',
        'Research FY2025 earnings guidance trends for Malaysian listed conglomerates. What are analysts saying about Sime Darby, IOI, and IHH in terms of earnings recovery? How is the plantation sector expected to perform given CPO price movements? Cite broker research or Bloomberg.'
      ], DESC_RESEARCHER),
      tool(T_ANALYST, M365_LIC, M365_ACCT, [
        'Upload 01_Zava_Group_Financial_Performance.xlsx to Analyst. Ask: Build a group financial performance dashboard. For FY2022, FY2023, FY2024, and FY2025 YTD: (1) Revenue by division, (2) EBITDA by division, (3) EBITDA margin %, (4) PAT, (5) PATAMI. Create a waterfall chart showing the FY2023-to-FY2024 EBITDA bridge by division — show which divisions contributed positively and which negatively to the change. Highlight the Zava Bank provisioning impact in a separate bar.',
        'Upload 01_Zava_Group_Financial_Performance.xlsx. Ask: Run 3 FY2025 full-year scenarios: (A) Base — all divisions at current trajectory, (B) Bear — Zava Bank NPL worsens by 30%, CPO price -10%, IDR weakens 8% vs MYR, (C) Bull — Zava Bank NPL stabilises, CPO price +15%, IDR stable. For each scenario, calculate: group revenue, EBITDA, PATAMI, EPS, net gearing, and interest coverage ratio. Show as a 3-column comparison table.'
      ], DESC_ANALYST),
      tool(T_EXCEL, M365_LIC, M365_ACCT, [
        'Open 01_Zava_Group_Financial_Performance.xlsx. Navigate to the Group P&L sheet. Ask Copilot: Build a FOREX sensitivity analysis on a new sheet. Show the group PATAMI impact of currency movements: MYR/USD ±5%, IDR/MYR ±5%, INR/MYR ±5%, SGD/MYR ±3%. Create a 2-dimensional sensitivity table: Y-axis = MYR/USD movement (-10% to +10%), X-axis = IDR/MYR movement (-10% to +10%). Each cell shows PATAMI impact in MYR M. Highlight cells where PATAMI drops >10% in red.',
        'Ask Copilot: In the Balance Sheet sheet, calculate the group net gearing under 3 scenarios: (1) REIT IPO proceeds MYR 3.2B used to pay down debt, (2) No REIT IPO, (3) REIT IPO proceeds reinvested in new assets. For each scenario, calculate: net debt, EBITDA, net gearing ratio, and debt covenant headroom. Show side-by-side. Highlight any scenario that breaches the 3.5x covenant.',
        'Ask Copilot: Build a half-year earnings release model. Using the FY2024 actuals and H1 FY2025 data, draft the P&L for H1 FY2025 showing: revenue growth vs H1 FY2024, EBITDA margin expansion/contraction, exceptional items (Zava Bank provision), and PATAMI. Add analyst consensus comparison column. Flag any line where we are >5% below consensus in red.'
      ]),
      tool(T_WORD, M365_LIC, M365_ACCT, [
        'Open 03_Zava_Group_Strategy_Framework.docx. Ask Copilot: Draft the Group CFO\'s commentary for the H1 FY2025 financial results announcement. The commentary should: (1) Open with the group headline — revenue, EBITDA, and PATAMI, (2) Explain the Zava Bank provisioning impact — transparent but measured, (3) Comment on CPO price tailwinds for the Agribusiness division, (4) Note the Manufacturing division\'s OEE improvement programme, (5) Provide FY2025 full-year guidance — revenue growth 4-6%, EBITDA margin 15.5-16.5%. Tone: confident, transparent, and forward-looking. Analyst investor communication style.',
        'Ask Copilot: Draft the Group Treasury Policy update paper for the Finance Committee. Propose: (1) Updated FOREX hedge ratio targets (from current 60% to 75% of 12-month FOREX exposure), (2) Centralisation of IDR hedging — all 5 Indonesian divisions to use the Group Treasury desk, (3) New derivative instruments to be approved — USD put options for plantation USD revenue, (4) Updated counterparty limits for derivative transactions. 5 pages, formal committee paper.',
        'Ask Copilot: Draft the investor Q&A preparation document for the H1 FY2025 results briefing. Anticipate the 10 most likely analyst questions (Zava Bank NPL, commodity price outlook, REIT IPO timeline, debt reduction plan, FY2025 guidance). For each question, provide a suggested 2-3 sentence answer. This is an internal briefing tool for the CFO and IR team.'
      ]),
      tool(T_PPT, M365_LIC, M365_ACCT, [
        'Ask Copilot in PowerPoint: Create a 14-slide H1 FY2025 results investor presentation. Include: (1) H1 headline — revenue, EBITDA, PATAMI, (2) Group financial highlights, (3) Division performance — revenue and EBITDA by division, (4) Zava Bank — NPL situation and provisioning, (5) Agribusiness — CPO production and price, (6) FOREX exposure and hedge ratio, (7) Balance sheet and gearing, (8) REIT IPO — timeline and expected proceeds, (9) Capital allocation — FY2025-2026 capex, (10) FY2025 full-year guidance, (11) Dividend — DPS and yield, (12) ESG highlight, (13) Analyst consensus vs actual, (14) Q&A slide. Standard investor presentation format.',
        'Ask Copilot: Create a 3-slide REIT IPO investor teaser. Slide 1: Asset overview — 12 REIT-eligible assets, MYR 8.2B. Slide 2: Key investment highlights — NPI yield, WALE, occupancy. Slide 3: Transaction overview — IPO structure, indicative timeline, expected DPU yield.',
        'Ask Copilot: Create a slide showing the FY2025 guidance visual — a bridge from H1 actuals to the full-year guidance range. Show the key drivers: Agribusiness CPO second half, Manufacturing recovery, BPO revenue growth, offset by Bank provisioning. Use a waterfall chart format.'
      ]),
      tool(T_OUTLOOK, M365_LIC, M365_ACCT, [
        'Ask Copilot in Outlook: Draft the H1 FY2025 results analyst briefing invitation. Send to 48 analysts covering Zava Group on Bursa Malaysia and IDX Jakarta. The invitation should: confirm the date/time/format (in-person KL + virtual), note the pre-results quiet period (no discussion of financial performance), attach the results presentation and press release (redacted — placeholders only), and provide the audio webcast link. Include a Q&A session calendar invite.',
        'Ask Copilot: Draft the Group CFO\'s email to all Division CFOs ahead of the H1 FY2025 results. The email should: confirm the group financial position, note the 3 key messages for the H1 announcement, remind all Division CFOs that no divisional results should be shared externally before the Bursa announcement, and request final division P&L sign-off by end of business tomorrow.',
        'Ask Copilot: Draft a letter to the 3 lead relationship banks (CIMB, Maybank, and Hong Leong Bank) providing the semi-annual covenant compliance certificate for the MYR 6.4B revolving credit facility. Confirm: net gearing 0.82x vs covenant 3.5x, interest coverage 4.8x vs covenant 2.5x, EBITDA MYR 7.2B vs minimum MYR 4.8B. All covenants satisfied.'
      ]),
      tool(T_TEAMS, M365_LIC, M365_ACCT, [
        'Open an existing recorded Teams meeting recap from a finance or CFO leadership meeting. Ask Copilot: Identify all financial performance concerns discussed, FOREX positions flagged, and decisions made about debt management or investor communications. Create an action tracker.',
        'Ask Copilot: Draft the Group Finance weekly update for the CFO. Structure: (1) Cash position and liquidity, (2) FOREX movements this week vs hedge positions, (3) Division P&L variance vs budget — top 3 movers, (4) Zava Bank NPL status, (5) REIT IPO progress, (6) Upcoming investor/analyst engagements.',
        'Ask Copilot: From this meeting transcript, what was decided about the Group Treasury\'s proposed IDR hedge ratio increase? What concerns did the Division CFOs raise about the centralised hedging model?'
      ], DESC_TEAMS),
      tool(T_NOTEBOOK, M365_LIC, M365_ACCT, [
        'Upload 01_Zava_Group_Financial_Performance.xlsx and 03_Zava_Group_Strategy_Framework.docx to Copilot Notebook. Set instruction: "You are advising the Group CFO on H1 FY2025 results communication." Ask: Based on the financial data and strategy, what is the single most important narrative the CFO must control in the H1 FY2025 analyst briefing? What is the question that analysts will ask that poses the biggest risk and what is the best answer?',
        'Upload 01_Zava_Group_Financial_Performance.xlsx. Ask: The group is targeting FY2025 PATAMI growth of 8-12%. With Zava Bank provisioning MYR 420M above budget, is this guidance achievable? Which divisions must outperform their H2 budget to offset the Bank shortfall? Quantify the required outperformance for each division.'
      ], DESC_NOTEBOOK),
      tool(T_COWORK, FRONTIER_LIC, M365_ACCT, [
        'Do all of the following for H1 results preparation: (1) Research what analyst consensus is for Zava Group\'s H1 FY2025 results based on publicly available broker estimates. (2) Draft the key messages document for the H1 investor briefing. (3) Create a Q&A preparation document with 12 anticipated questions and suggested answers. (4) Email to CFO and Head of Investor Relations for review. (5) Schedule the results analyst briefing and create the Teams webcast event.',
        'Do all of the following for treasury: (1) Research current MYR/IDR cross rate and 12-month forward rate from Bloomberg. (2) Calculate the unhedged IDR exposure impact on group PATAMI if IDR weakens 8% over 12 months. (3) Draft a hedging recommendation paper for the Finance Committee. (4) Email to the Group Treasurer asking for market data validation. (5) Schedule an urgent Finance Committee call to approve the updated hedge ratio.'
      ], DESC_COWORK),
      tool(T_WORD_AGT, M365_LIC, M365_ACCT, [
        'Open 03_Zava_Group_Strategy_Framework.docx in Word for Web. Create an agent called "Group Finance & Strategy Q&A Bot". Description: "Supports the Group Finance team and Division CFOs with instant answers on group financial policies, FOREX hedging guidelines, covenant requirements, REIT IPO structuring, and investor communication protocols." Share with all Division CFOs.',
        'Demo: A Division CFO asks "We have a USD 12M receivable from a US customer due in 90 days. Should I hedge this at the Group Treasury desk or manage it ourselves? What is the Group Treasury Policy on Division-level FOREX hedging and what are the authorised instruments?" Show the agent providing a treasury-policy-grounded answer.'
      ], DESC_WORD_AGT),
      tool(T_PPT_AGT, M365_LIC, M365_ACCT, [
        'Create a PowerPoint from the H1 results investor presentation. Create an agent called "Zava Group Investor Relations Q&A Bot". Share with analysts, fund managers, and the IR team.',
        'Demo: An analyst asks "What is the Group\'s sensitivity to a 10% decline in CPO prices and how would that affect FY2025 PATAMI guidance? Also, at what gearing level would you need to cut the dividend?" Show the agent providing a financial model-grounded investor Q&A answer.'
      ], DESC_PPT_AGT),
      tool(T_XL_AGT, M365_LIC, M365_ACCT, [
        'Open 01_Zava_Group_Financial_Performance.xlsx in Excel for Web. Create an agent called "Group Finance Performance Q&A". Description: "Instant answers on group P&L, EBITDA by division, FOREX sensitivity, gearing, covenant headroom, and REIT IPO financials for the CFO, Group CEO, and Division CFOs." Share with Group Finance leadership.',
        'Demo: Ask "What is the group net gearing now and what would it be after REIT IPO proceeds are used to repay debt?" Then: "Which 3 divisions are most below their H1 FY2025 EBITDA budget and by how much in MYR M?" Show the CFO getting instant group financial intelligence.'
      ], DESC_XL_AGT),
      tool(T_BUILDER, M365_LIC, M365_ACCT, [
        'Go to copilotstudio.microsoft.com > Create > New Agent. Name it "Zava Group Finance Intelligence Agent". Description: "The Group CFO\'s intelligent assistant — provides instant answers on group P&L performance, FOREX exposure, covenant compliance, REIT IPO financial modelling, investor communication requirements, and divisional financial KPIs. Supports faster, more data-driven financial decision-making across the Zava Group." Upload 01_Zava_Group_Financial_Performance.xlsx and 03_Zava_Group_Strategy_Framework.docx. Add topics: "Group P&L", "FOREX & Treasury", "REIT IPO", "Investor Relations", "Covenants". Publish to Teams for Group Finance leadership.',
        'Demo the agent: The Group CFO is at a dinner with Malaysia\'s largest institutional fund manager, who asks unexpectedly: "I\'m thinking of increasing my position in Zava Group but I\'m worried about the Zava Bank NPL exposure. Can you walk me through the worst-case provisioning scenario and confirm that your MYR 6.4B RCF has no cross-default clause linked to Zava Bank\'s NPL ratio?" The CFO discreetly asks the Finance agent on their phone and gets a precise, numbers-backed answer to continue the investor conversation with confidence.'
      ], DESC_BUILDER),
    ]),
]

print(f"Departments written: {len(DEPARTMENTS)} entries")
