
import sys; sys.path.insert(0,'.')
from util import *

DEPARTMENTS_4 = [

# ── OPERATIONS / COO OFFICE ───────────────────────────────────────────────
ind('dept-operations','department','Operations & COO Office','⚙️','#37474F','#455A64',
    'Zava Group Holdings — Group COO Office',
    'Nilai plant OEE crisis, Cilegon enforcement notices, supply chain resilience, cross-division OpEx.',
    'The Group COO Office oversees operational excellence across 6 factories, 12 plantations, 3 chemical plants, 10 hospitals, and 5 BPO delivery centres. Live crises: Nilai automotive plant OEE has declined from 76% to 62% in 18 months, Cilegon Chemicals has 3 BPOM enforcement notices, and the CPO feedstock shortage is impacting chemical plant utilisation. Group-wide OpEx reduction target: MYR 480M in FY2025.',
    ['12_Zava_Manufacturing_KPIs.xlsx','15_Zava_BPO_Operations.xlsx'],
    [
      tool(T_CHAT, FREE_LIC, FREE_ACCT, [
        'I am the Group COO of an ASEAN conglomerate. Our Nilai automotive plant OEE has declined from 76% to 62% in 18 months. The primary cause is unplanned spindle motor failures on our 12-year-old CNC machines, but there are also quality issues (defect rate rising from 1.2% to 3.8%) and a maintenance backlog. Draft a 250-word brief on: (1) What OEE recovery actions can be implemented immediately at zero cost, (2) What the financial impact of 62% vs 76% OEE is at 850 units/day capacity with MYR 1,200 revenue per unit and 310 working days, (3) The business case threshold for replacing the spindle motors vs replacing the machines entirely.',
        'What is Total Productive Maintenance (TPM) and how is it used to sustainably improve OEE? What are the 8 TPM pillars and which ones would address our specific issues of unplanned breakdowns, quality defects, and slow changeovers?',
        'How should a group COO manage OpEx reduction when every division head claims their operations are already at minimum cost? What is the structured approach to identifying genuine OpEx reduction opportunities vs cost cuts that damage capability?'
      ]),
      tool(T_RESEARCHER, M365_LIC, M365_ACCT, [
        'Research OEE benchmarks for automotive component manufacturing plants in ASEAN. What is a world-class OEE for precision stamping and CNC machining? What are the documented root causes of OEE decline in aging manufacturing plants and what are the proven remediation approaches? Cite industry sources like ARC Advisory, LNS Research, or Siemens.',
        'Research process safety management best practices for chemical plants in Indonesia regulated by BPOM. What are the BPOM enforcement procedures when an enforcement notice is issued? What are the typical timeline and requirements to lift a production suspension? Cite BPOM regulations or official Indonesian industrial safety sources.'
      ], DESC_RESEARCHER),
      tool(T_ANALYST, M365_LIC, M365_ACCT, [
        'Upload 12_Zava_Manufacturing_KPIs.xlsx. Ask Analyst: (1) Plot the Nilai plant OEE decline from Jan 2023 to Dec 2024 on a time series chart. Overlay the dates of key events (first spindle failure, parts ordered, training scheduled) to show the correlation. (2) Calculate the revenue lost due to OEE decline vs the world-class OEE benchmark of 85% — show monthly and cumulative. (3) Decompose the OEE into Availability, Performance, and Quality components and show which is contributing most to the decline. Highlight the trend clearly.',
        'Upload 15_Zava_BPO_Operations.xlsx. Ask Analyst: (1) Calculate the total annual revenue at risk from the 3 BPO contracts expiring within 6 months. (2) For each expiring contract, score the renewal probability (High/Medium/Low) based on NPS score and SLA performance. (3) If all 3 are lost, calculate the impact on BPO Division revenue, headcount utilisation, and profitability. (4) Plot a revenue cliff chart showing the contracted revenue falling off in the next 12 months if no renewals are secured.'
      ], DESC_ANALYST),
      tool(T_EXCEL, M365_LIC, M365_ACCT, [
        'Open 12_Zava_Manufacturing_KPIs.xlsx. Ask Copilot: Add a column on Sheet 1 (Factory Dashboard) calculating the annual revenue impact of current OEE vs target OEE (85%) for each factory. Formula: (Target OEE% - Actual OEE%) × Installed Capacity/day × Working Days × Revenue per Unit. Show as a revenue opportunity column. Highlight factories where the gap represents more than MYR 20M annual revenue opportunity in red.',
        'Open 15_Zava_BPO_Operations.xlsx. Ask Copilot: Add a contract risk score on Sheet 1 (Client Dashboard) based on: NPS score < 45 = 2 points, SLA score < 92% = 2 points, contract expiry within 6 months = 3 points, renewal status "At Risk" = 3 points. Sum the scores. Score 6+ = High Risk (red), 3-5 = Medium Risk (amber), 0-2 = Low Risk (green). Calculate the total revenue at risk for High Risk contracts.',
        'Ask Copilot: Create an OpEx tracker on a new sheet. For each of the 11 divisions, show: (1) FY2024 OpEx (MYR M), (2) FY2025 OpEx Budget, (3) FY2025 YTD Actual, (4) Variance MYR M, (5) Variance %, (6) OpEx reduction target (MYR M), (7) Savings achieved to date, (8) % of target achieved. Sum group totals. Highlight divisions where savings are below 30% of target in red — these need COO intervention.'
      ]),
      tool(T_WORD, M365_LIC, M365_ACCT, [
        'Open 12_Zava_Manufacturing_KPIs.xlsx. Ask Copilot to draft a briefing document: "Nilai Plant OEE Crisis — Root Cause Analysis and Recovery Plan". Structure: (1) Executive Summary — OEE at 62%, financial impact, recovery timeline, (2) Root Cause Analysis — 5-Why analysis of spindle motor failures, (3) Immediate actions — 5 things that can start this week, (4) Short-term actions (30-90 days) — maintenance programme, spare parts, training, (5) Long-term investment — MYR 8.2M spindle motor replacement business case, (6) Recovery milestones — OEE targets at 30/60/90/180 days. 4 pages.',
        'Ask Copilot: Draft the formal response letter to BPOM regarding the 3 enforcement notices at Cilegon Specialty Chemicals. The letter should: reference each enforcement notice number and date, for each notice provide (1) root cause, (2) immediate corrective action taken, (3) preventive measure implemented, (4) evidence attached. Request a reinspection to lift the production suspension. Formal Indonesian regulatory correspondence format.',
        'Ask Copilot: Write the Group COO\'s quarterly Operations Review narrative for the Board. Structure: (1) Group OEE performance — 3 world class plants, 2 acceptable, 1 crisis (Nilai), (2) Quality performance — group defect rate trend, (3) Safety — TRIR vs benchmark, any critical incidents, (4) BPO contract risk — 3 contracts expiring, renewal status, (5) OpEx reduction — progress vs MYR 480M target, (6) Capex programme — 12 projects status, (7) Division-by-division operational highlights and concerns. 6 pages, Board report format.'
      ]),
      tool(T_PPT, M365_LIC, M365_ACCT, [
        'Ask Copilot in PowerPoint: Create a 12-slide Operations Review Board presentation. Include: (1) Group operational highlights, (2) Manufacturing OEE dashboard — 6 factories, (3) Nilai plant crisis — OEE trend and recovery plan, (4) Quality performance — defect rate trend, (5) Safety performance — TRIR, enforcement notices, (6) BPO contract renewal risk — 3 expiring contracts revenue at risk, (7) BPO headcount and delivery centre utilisation, (8) Chemicals — Cilegon enforcement notice status, (9) Plantation operations — CPO production vs target, (10) OpEx reduction — division by division vs target, (11) Capex programme — 12 projects traffic light, (12) Actions required from Board. Grey and navy operations colour scheme.',
        'Ask Copilot: Create a 3-slide Nilai Plant Recovery Plan for the Plant Manager town hall. Slide 1: The OEE crisis in plain numbers — what 62% vs 85% means for our revenue and jobs. Slide 2: The 7 recovery actions — 3 this week, 4 in 30 days. Slide 3: The 6-month OEE improvement targets. Straightforward, factory-worker-facing language.',
        'Ask Copilot: Create a 2-slide BPO Contract Retention Strategy for the EXCO. Slide 1: The 3 contracts at risk — USD 26.4M combined ARR, renewal probability and reasoning. Slide 2: The retention playbook — price, scope, relationship, and service improvement actions for each client.'
      ]),
      tool(T_OUTLOOK, M365_LIC, M365_ACCT, [
        'Ask Copilot in Outlook: Draft the Group COO\'s urgent email to the Nilai Plant Manager and Group Manufacturing VP escalating the OEE crisis. The email should: state the financial impact (revenue loss vs 85% OEE benchmark: MYR 40M annualised), note the spindle motor replacement has been pending approval for 6 months, request a 5-day OEE recovery plan submission, and schedule a site visit for the following week. Firm but constructive tone.',
        'Ask Copilot: Draft the Group COO\'s email to the Zava BPO CEO regarding the 3 expiring BPO contracts. The email should: name the 3 contracts (Bank Mandiri, Sime Darby, Pan Pacific Hotels), note the combined USD 26.4M ARR at risk, request the current renewal negotiation status and the retention strategy for each, and set a deadline of 2 weeks for a detailed renewal plan.',
        'Ask Copilot: Draft the Board Operations Committee invitation for an emergency meeting to discuss the Nilai plant OEE crisis and Cilegon enforcement notices. The agenda should: cover the financial impact of both issues, the recovery plans, the capital investment required (MYR 8.2M Nilai + MYR 2.4M Cilegon remediation), and the Board decisions required. Professional committee meeting format.'
      ]),
      tool(T_TEAMS, M365_LIC, M365_ACCT, [
        'Open an existing recorded Teams meeting recap from a manufacturing or operations review meeting. Ask Copilot: What operational KPIs were discussed? Identify the 3 most critical operational issues raised and the decisions made. Create a COO action log.',
        'Ask Copilot: Draft the COO\'s daily operations flash report for today. Structure: (1) Manufacturing — any unplanned downtime or quality alerts across 6 factories, (2) BPO — any SLA breaches or client escalations, (3) Chemicals — Cilegon status, any new BPOM developments, (4) Plantation — production vs plan, (5) Actions required by 5pm today.',
        'Ask Copilot: From this Operations Review meeting, what was the disagreement between the Manufacturing VP and the Plant Manager about the root cause of the Nilai OEE decline? Was it resolved and what was the agreed action?'
      ], DESC_TEAMS),
      tool(T_NOTEBOOK, M365_LIC, M365_ACCT, [
        'Upload 12_Zava_Manufacturing_KPIs.xlsx and 15_Zava_BPO_Operations.xlsx to Copilot Notebook. Set instruction: "You are the Group COO reviewing all operational risks." Ask: Based on all operational data, which 3 operational issues have the largest combined financial impact on the Group in the next 12 months? For each, what is the single most important action that the COO should personally drive in the next 30 days?',
        'Upload 12_Zava_Manufacturing_KPIs.xlsx. Ask: The Nilai plant has an 8.2M MYR spindle motor replacement project that has been 15% complete for 6 months. Also the plant has a 12.4M MYR MES system that has not started. Given the OEE crisis, should we sequence these projects differently? What would be the OEE impact of completing the spindle motor replacement first?'
      ], DESC_NOTEBOOK),
      tool(T_COWORK, FRONTIER_LIC, M365_ACCT, [
        'Do all of the following for the Nilai plant crisis: (1) Research lean manufacturing OEE improvement methodologies from the Toyota Production System and Siemens SCADA platforms. (2) Draft a 90-day Nilai Plant OEE Recovery Action Plan. (3) Calculate the financial impact of each 1% OEE improvement. (4) Email to the Group Manufacturing VP and Plant Manager for implementation. (5) Create a daily OEE recovery tracker in SharePoint. (6) Schedule weekly COO check-in on Nilai plant OEE until it reaches 72%.',
        'Do all of the following for BPO contract retention: (1) Research best practice BPO contract renewal negotiation strategies for contracts with NPS below 50. (2) For each of the 3 at-risk contracts (Bank Mandiri, Sime Darby, Pan Pacific), draft a tailored retention proposal addressing their specific SLA breaches and NPS issues. (3) Email each proposal to the respective BPO client relationship manager. (4) Schedule face-to-face retention meetings with each client within 3 weeks.'
      ], DESC_COWORK),
      tool(T_WORD_AGT, M365_LIC, M365_ACCT, [
        'Open 12_Zava_Manufacturing_KPIs.xlsx in Word for Web (or create a companion Word summary). Create an agent called "Zava Operations Intelligence Bot". Description: "Answers questions from Plant Managers, Division Operations heads, and the Group COO on OEE benchmarks, manufacturing best practices, BPO SLA standards, safety protocols, and Cilegon enforcement notice compliance requirements." Share with all 6 factory managers and BPO centre managers.',
        'Demo: A Plant Manager at the Shah Alam Consumer Goods factory asks "Our OEE dropped from 82.4% to 79.1% in the last 2 months. We\'ve identified that the main cause is scheduled changeover time on our bottle cap line increasing from 45 to 75 minutes. Under our Group TPM standards, what is the target changeover time for a consumer goods line of this type and what is the SMED methodology we should apply?" Show the agent providing a technically grounded, actionable answer.'
      ], DESC_WORD_AGT),
      tool(T_PPT_AGT, M365_LIC, M365_ACCT, [
        'Create a PowerPoint from the Operations Review Board presentation. Create an agent called "Operations Review Q&A Bot". Share with Board Operations Committee.',
        'Demo: A Board member asks "The Cilegon enforcement notices have now been outstanding for 4 months. What is the total revenue and EBITDA impact of the 2 suspended product lines and when do we expect BPOM to lift the suspension?" Show the agent providing a financially quantified, timeline-grounded answer.'
      ], DESC_PPT_AGT),
      tool(T_XL_AGT, M365_LIC, M365_ACCT, [
        'Open the Manufacturing KPIs and BPO Operations workbooks in Excel for Web. Create an agent called "COO Operations Dashboard Q&A". Description: "Instant answers on OEE by factory, quality metrics, BPO SLA performance, contract renewal risk, OpEx vs target, and capex programme status for the Group COO." Share with COO leadership.',
        'Demo: Ask "Which factory has the highest OEE and which has the lowest — and what is the MYR revenue gap between their actual output and what they would produce at 85% OEE?" Then: "For the 3 BPO contracts expiring in the next 6 months, what is the total contracted USD value at risk?" Show the COO getting instant cross-division operational intelligence.'
      ], DESC_XL_AGT),
      tool(T_BUILDER, M365_LIC, M365_ACCT, [
        'Go to copilotstudio.microsoft.com > Create > New Agent. Name it "Zava Operations Intelligence Agent". Description: "Supports the Group COO, Plant Managers, and Division Operations heads with instant answers on OEE benchmarks, manufacturing standards, BPO contract risk, safety compliance, OpEx reduction targets, and capex programme status — enabling faster, data-driven operational decisions across 6 factories, 3 chemical plants, 12 estates, and 5 BPO delivery centres." Upload 12_Zava_Manufacturing_KPIs.xlsx and 15_Zava_BPO_Operations.xlsx. Add topics: "OEE Management", "Quality Control", "BPO Contract Risk", "Safety Compliance", "OpEx Reduction". Publish to Teams.',
        'Demo the agent: The Group COO receives a call from the Nilai Plant Manager at 11pm: "We\'ve just had 3 CNC machines go down simultaneously — a catastrophic spindle failure across the C, D, and E lines. This will stop all production for at least 5 days. We need 3 replacement spindles urgently — the procurement team says the standard lead time is 12 weeks." The COO asks the agent: "What is the financial impact per day of having 3 lines down at Nilai, what is our approved emergency procurement protocol for critical spare parts that bypasses the standard 12-week lead time, and do we have any risk buffer stock of spindle motors at any other Zava manufacturing facility?" Show how the agent enables an instant, data-informed crisis response.'
      ], DESC_BUILDER),
    ]),

# ── BOARD & EXECUTIVE OFFICE ──────────────────────────────────────────────
ind('dept-board','department','Board & Executive Office','🏛','#1A237E','#283593',
    'Zava Group Holdings — Group CEO & Board Secretariat',
    'Q1 FY2025 Board pack, ZAVA FORWARD 2030 strategy briefing, dual listing compliance.',
    'The Group CEO and Board Secretariat serve the 11-member Board of Directors of Zava Group Holdings Berhad (Bursa main market, IDX dual-listed). Priorities: Q1 FY2025 Board pack covering NPL breach, RSPO suspension, coal breach, and OEE crisis. Annual General Meeting preparation. ZAVA FORWARD 2030 strategy presentation. Corporate governance compliance for Bursa and IDX simultaneous disclosure obligations.',
    ['01_Zava_Group_Financial_Performance.xlsx','Email_07_Emergency_Board_Meeting.docx'],
    [
      tool(T_CHAT, FREE_LIC, FREE_ACCT, [
        'I am the Company Secretary of a dual-listed ASEAN conglomerate (Bursa Malaysia and Indonesia Stock Exchange). We have 4 simultaneous material issues that must be disclosed at the upcoming Board meeting: (1) Zava Bank retail personal loans NPL at 21.7% — breaching the BNM 3.5% threshold, (2) Perkebunan Lestari RSPO certification suspended, (3) Coal trading position limit breach USD 22.4M vs USD 20M limit, (4) Nilai manufacturing plant OEE at 62% with MYR 40M annualised revenue impact. Draft a 200-word brief on the sequence in which these should be presented to the Board — which is the most material for Bursa disclosure and why?',
        'What is the Corporate Governance Code of Best Practices (MCCG) requirement for a Malaysian main board listed company regarding Board Risk Committee composition and meeting frequency? How does dual listing on IDX change the governance obligations?',
        'Explain what a Board succession planning framework looks like for a diversified conglomerate with an 11-member Board. What skills matrix should be used, what is the typical director tenure policy, and how is independence of NEDs assessed under MCCG 2021?'
      ]),
      tool(T_RESEARCHER, M365_LIC, M365_ACCT, [
        'Research Bursa Malaysia\'s mandatory immediate announcement requirements under the Listing Requirements. When must a company make an immediate announcement vs a next business day announcement? What specifically must be disclosed when a subsidiary bank breaches a regulatory capital ratio or NPL threshold? Cite Bursa Listing Requirements or SC circulars.',
        'Research Malaysian corporate governance best practices for conglomerate holding company boards. What are the MCCG 2021 requirements for Board composition (executive vs non-executive, independent), Board committees (Audit, Risk, Remuneration, Nomination), and Board effectiveness evaluation? How are the top Malaysian conglomerates (Sime Darby, IHH, IOI) rated on governance by MSWG or Bursa? Cite MCCG 2021 or governance rating reports.'
      ], DESC_RESEARCHER),
      tool(T_ANALYST, M365_LIC, M365_ACCT, [
        'Upload 01_Zava_Group_Financial_Performance.xlsx. Ask Analyst: (1) Create an EPS bridge from FY2023 to FY2024 showing the contribution of each division to the change in group EPS. (2) Plot the FY2022-FY2025F earnings trajectory and analyst consensus vs actual for the last 4 quarters. (3) Calculate the implied P/E ratio vs the group\'s 5-year historical average and vs sector peer (Sime Darby, IOI, IHH). (4) Identify which single division contributed most to the FY2024 vs FY2023 EBITDA improvement and which most to the decline. Present as Board-ready charts.',
        'Upload 01_Zava_Group_Financial_Performance.xlsx. Ask: Model the financial impact of 3 simultaneous downside scenarios for FY2025F: (A) Zava Bank NPL requires MYR 800M additional provision, (B) Perkebunan Lestari suspension continues for full year — CPO volume loss at MYR 3,920/MT, (C) Nilai plant continues at 62% OEE for full year vs 85% target. Calculate: (1) Impact on Group EBITDA, (2) Impact on Group PAT, (3) Impact on EPS, (4) Impact on Net Gearing. Then show combined scenario if all 3 occur simultaneously.'
      ], DESC_ANALYST),
      tool(T_EXCEL, M365_LIC, M365_ACCT, [
        'Open 01_Zava_Group_Financial_Performance.xlsx. Ask Copilot: Create a Board KPI Dashboard sheet. For each of 15 Group-level KPIs (Revenue, EBITDA margin, PATAMI, EPS, Net Gearing, ROAE, DPS, Zava Bank NPL, Group TRIR, Group RSPO compliance, OEE weighted average, BPO SLA weighted average, Employee engagement, Women in leadership, ESG rating), show: (1) FY2024 Actual, (2) FY2025 Target, (3) FY2025 YTD, (4) Status (On Track/At Risk/Off Track). Apply RAG formatting. Create the Board\'s single-page Group performance dashboard.',
        'Ask Copilot: Build a Board meeting tracker on a new sheet. For each of the last 4 Board meetings, show: (1) Meeting date, (2) Key resolutions passed, (3) Outstanding actions from previous meeting, (4) Status of each action, (5) Days since resolution and overdue actions. Highlight overdue Board actions in red.',
        'Ask Copilot: Build an investor relations dashboard. For each of our 15 top institutional shareholders (approximate): (1) Fund name, (2) Country, (3) Estimated % stake, (4) Last engagement date, (5) Current sentiment (Positive/Neutral/Negative), (6) Key concerns raised, (7) Next engagement planned. Highlight shareholders with negative sentiment and no engagement in the last 90 days in amber.'
      ]),
      tool(T_WORD, M365_LIC, M365_ACCT, [
        'Open Email_07_Emergency_Board_Meeting.docx. Ask Copilot: Draft the Group CEO\'s Board Paper on the Q1 FY2025 simultaneous crises. Section 1: Group financial performance — revenue and EBITDA vs target. Section 2: Zava Bank NPL crisis — current status, BNM response, remediation plan, provision impact. Section 3: Perkebunan Lestari RSPO suspension — situation, commercial impact, remediation timeline. Section 4: Coal trading limit breach — what happened, risk control failure, immediate actions. Section 5: Nilai plant OEE crisis — financial impact, recovery plan, capex required. Section 6: Recommendations — 7 specific Board resolutions required. 12 pages, Board paper format with executive summary.',
        'Ask Copilot: Draft the Board resolution template for the 7 Board decisions required at the Q1 FY2025 emergency Board meeting: (1) Approve Zava Bank NPL remediation plan and MYR 800M provision, (2) Approve Perkebunan Lestari RSPO remediation budget MYR 140M, (3) Approve Coal Trading Risk Control enhancement — position limit reduction and risk committee oversight, (4) Approve Nilai plant spindle motor replacement MYR 8.2M, (5) Approve Group CEO authority to engage with BNM on NPL breach, (6) Approve RSPO CAP submission to RSPO certification body, (7) Approve EUDR compliance investment MYR 28M. Standard Malaysian Board resolution format.',
        'Ask Copilot: Draft the Chairman\'s opening address for the Board meeting. The address should: acknowledge the extraordinary challenges of the quarter honestly, frame the 4 crises as manageable and being actively remediated, express confidence in the management team, remind Directors of their fiduciary duties and the Bursa disclosure obligations, and set the tone for a constructive and decisive Board discussion. Statesman-like, measured tone.'
      ]),
      tool(T_PPT, M365_LIC, M365_ACCT, [
        'Ask Copilot in PowerPoint: Create the full Q1 FY2025 Board presentation (20 slides). Include: (1) Chairman\'s opening remarks context, (2) Q1 FY2025 Group financial highlights, (3) Division performance scorecard — 11 divisions, (4) Group financial KPI dashboard, (5) Zava Bank NPL crisis and remediation, (6) Perkebunan Lestari RSPO suspension, (7) Coal trading breach and risk control response, (8) Nilai plant OEE crisis and recovery, (9) Group ESG performance, (10) IT Digital transformation update, (11) M&A pipeline, (12) REIT IPO preparation, (13) ZAVA FORWARD 2030 progress, (14) FY2025 full-year guidance revision, (15) Capital allocation update, (16) Dividend consideration, (17) Investor relations update, (18) Regulatory engagement update, (19) Board decisions required, (20) Appendix — supporting data. Dark navy Board presentation.',
        'Ask Copilot: Create the ZAVA FORWARD 2030 strategy presentation for the Annual General Meeting (15 slides). Include: (1) Our journey — Zava Group from founding to today, (2) ASEAN opportunity, (3) Vision 2030 — Asia\'s most trusted diversified conglomerate, (4) 5 Strategic Pillars overview, (5) Pillar 1: Portfolio Optimisation — healthcare M&A, REIT IPO, (6) Pillar 2: Digital Transformation — Copilot, SAP, data lake, (7) Pillar 3: ESG Leadership — Net Zero, RSPO, EUDR, (8) Pillar 4: Talent Excellence — 87K employees, DEI, (9) Pillar 5: Capital Efficiency — 0.82x gearing to 0.65x, (10) Financial targets FY2027: Revenue MYR 52B, EBITDA 18%, (11) Dividend commitment — progressive policy, (12) Our people, (13) Our communities, (14) Our planet, (15) The Zava Promise. Polished investor-facing design.',
        'Ask Copilot: Create a 3-slide media briefing pack for the Q1 FY2025 results announcement. Slide 1: 3 key messages from the Group CEO. Slide 2: Q1 financial highlights in clean table format. Slide 3: FY2025 guidance — revenue range, EBITDA margin target, and DPS forecast. Journalist-accessible, no jargon.'
      ]),
      tool(T_OUTLOOK, M365_LIC, M365_ACCT, [
        'Ask Copilot in Outlook: Draft the Group CEO\'s email to all 11 Division CEOs and CFOs calling for urgent submissions for the emergency Board meeting. The email should: list the 4 simultaneous issues requiring Board presentation, request a 2-page "situation-action-status" brief from each affected division by Friday noon, confirm the emergency Board meeting date, and emphasise that the Board will ask tough questions — all answers must be evidenced and quantified. Authoritative, urgent tone.',
        'Ask Copilot: Draft the Company Secretary\'s Bursa Malaysia announcement for the Zava Bank NPL situation. Under Bursa Listing Requirements, the announcement must: describe the material information (Retail Personal Loans NPL at 21.7%, breach of BNM threshold), note the date of discovery, confirm BNM has been notified, state management actions (MYR 800M provision, remediation plan), and provide guidance on financial impact. Formal Bursa announcement format.',
        'Ask Copilot: Draft the Chairman\'s personal letter to the 4 largest institutional shareholders (EPF, KWAP, PNB, Permodalan MY) providing advance notification of the Q1 FY2025 challenges. The letter should: acknowledge the issues candidly, describe the remediation actions management has taken, express personal confidence in the strategy and management team, and invite a bilateral engagement before the public results announcement. Personal, statesman-like tone.'
      ]),
      tool(T_TEAMS, M365_LIC, M365_ACCT, [
        'Open an existing recorded Teams meeting recap from a Board or EXCO meeting. Ask Copilot: What were the key strategic decisions made and what Board resolutions were passed? Identify all action items assigned to the CEO and their deadlines. Create a Board action tracker.',
        'Ask Copilot: Draft the Group CEO\'s weekly executive report for the Board. Structure: (1) Top 3 strategic priorities this week, (2) Financial performance flash — revenue and EBITDA vs plan, (3) Critical issues — Zava Bank NPL, RSPO, coal breach, Nilai — status update, (4) External environment — any regulatory or market developments, (5) Upcoming key decisions and decisions needed from Board.',
        'Ask Copilot: From this Board meeting recap, what was the Board\'s reaction to the NPL breach disclosure? Were there any dissenting views among Board members? What specific questions did the Board ask management that were not answered satisfactorily?'
      ], DESC_TEAMS),
      tool(T_NOTEBOOK, M365_LIC, M365_ACCT, [
        'Upload 01_Zava_Group_Financial_Performance.xlsx and Email_07_Emergency_Board_Meeting.docx to Copilot Notebook. Set instruction: "You are the Group CEO preparing for an emergency Board meeting." Ask: Based on the financial data and the email context, if I were the Board Chairman seeing these 4 simultaneous crises for the first time, what would be my 5 hardest questions for management? For each question, draft a 3-sentence answer that management should prepare.',
        'Upload 01_Zava_Group_Financial_Performance.xlsx. Ask: The Board must decide whether to revise down the FY2025 guidance that was given to Bursa at the Q4 FY2024 results. Original guidance: Revenue MYR 47.2B, EBITDA margin 16.8%. Based on the 4 simultaneous issues and their financial impact, should guidance be revised? If so, what is the defensible revised guidance range and what is the rationale that management should present?'
      ], DESC_NOTEBOOK),
      tool(T_COWORK, FRONTIER_LIC, M365_ACCT, [
        'Do all of the following to prepare for the emergency Board meeting: (1) Compile the Q1 FY2025 Board pack by pulling together: Group financial flash, Zava Bank NPL brief, RSPO situation brief, Coal trading breach brief, and Nilai OEE brief. (2) Draft the Chairman\'s briefing note on the 7 Board resolutions required. (3) Create the Board action log tracking all outstanding items from the previous 2 Board meetings. (4) Send all Board materials to Board members 5 days before the meeting via secure SharePoint link. (5) Schedule pre-meeting calls between the Chairman and each independent NED to brief them privately before the full Board meeting.',
        'Do all of the following for the Annual General Meeting: (1) Draft the full AGM Notice of Meeting including agenda, proxy form, and Explanatory Notes on resolutions. (2) Prepare the Integrated Annual Report summary (4-page highlights version). (3) Draft Q&A talking points for the Chairman and Group CEO covering the 20 most likely shareholder questions. (4) Prepare the ZAVA FORWARD 2030 strategy video script for the AGM screening. (5) Email the AGM Notice to the Company\'s share registrar for mailing to all registered shareholders.'
      ], DESC_COWORK),
      tool(T_WORD_AGT, M365_LIC, M365_ACCT, [
        'Open Email_07_Emergency_Board_Meeting.docx in Word for Web. Create an agent called "Zava Board & Governance Q&A Bot". Description: "Answers questions from Board Directors, the Chairman, Group CEO, and Company Secretary on Bursa Listing Requirements, MCCG 2021 governance obligations, Board resolution procedures, dual-listing disclosure requirements, and Board meeting protocols." Share with Board members and the Company Secretary.',
        'Demo: An Independent Non-Executive Director asks "A whistleblower email has just been forwarded to me by an employee alleging that a senior manager at Zava Trading has been inflating commodity trading profits to avoid a bonus malus. As an INED, what is my disclosure obligation under Bursa Listing Requirements, what is the proper escalation pathway under our Whistleblower Policy, and must I disclose this to the full Board at the next meeting or can I handle it privately through the Audit Committee?" Show the agent providing a governance-grounded, regulatory-precise answer.'
      ], DESC_WORD_AGT),
      tool(T_PPT_AGT, M365_LIC, M365_ACCT, [
        'Create a PowerPoint from the ZAVA FORWARD 2030 AGM presentation. Create an agent called "ZAVA FORWARD 2030 Strategy Q&A". Share with Board members, EXCO, and investor relations team.',
        'Demo: An institutional shareholder analyst asks "In your ZAVA FORWARD 2030, you target EBITDA margin improvement from 16.1% to 18.0% by FY2027. But you currently have 4 simultaneous operational crises. Which of the 5 strategic pillars is most at risk and what is the contingency if EBITDA margin misses the 18% target by more than 1 percentage point?" Show the agent providing a strategy-grounded, quantified investor response.'
      ], DESC_PPT_AGT),
      tool(T_XL_AGT, M365_LIC, M365_ACCT, [
        'Open the Group Financial Performance workbook in Excel for Web. Create an agent called "Group Financial Intelligence Q&A". Description: "Instant answers on Group financial performance, division P&L, EPS trend, analyst consensus, net gearing, and FY2025 guidance for the Group CEO, CFO, and Board." Share with Board members and EXCO.',
        'Demo: Ask "What is our Q1 FY2025 EBITDA margin vs target and which division has the largest negative variance?" Then: "If the Zava Bank NPL requires an MYR 800M provision, what is the impact on Group PAT and EPS — and does it breach any of our debt covenants?" Show the Board getting instant, scenario-aware financial intelligence.'
      ], DESC_XL_AGT),
      tool(T_BUILDER, M365_LIC, M365_ACCT, [
        'Go to copilotstudio.microsoft.com > Create > New Agent. Name it "Zava Board Intelligence Agent". Description: "Supports the Group CEO, Chairman, Board Directors, Company Secretary, and Investor Relations team with instant answers on Group financial performance, governance obligations, Bursa/IDX disclosure requirements, MCCG compliance, Board resolution procedures, and ZAVA FORWARD 2030 strategy — enabling faster, governance-consistent Board decision-making across the Zava Group conglomerate." Upload 01_Zava_Group_Financial_Performance.xlsx and Email_07_Emergency_Board_Meeting.docx. Add topics: "Group Financial Performance", "Bursa Disclosure", "Board Governance", "MCCG 2021", "Strategy". Publish to Teams for Board members.',
        'Demo the agent: The Group CEO receives a call from a Bloomberg journalist at 6am: "We have received a tip that Zava Group is planning a major rights issue to address the Zava Bank capital ratio decline. Is this true and do you have a comment?" The CEO asks the agent: "Under Bursa Listing Requirements, is a potential rights issue a price-sensitive immediate announcement trigger? Am I allowed to say No Comment, and if I confirm or deny, which statement puts us in a stronger Bursa disclosure position?" Show how the agent enables an instant, legally grounded media handling decision at 6am.'
      ], DESC_BUILDER),
    ]),
]

print(f"Departments 4 written: {len(DEPARTMENTS_4)} entries")
