
import sys; sys.path.insert(0,'.')
from util import *

INDUSTRIES_3 = [

# ── HOSPITAL NETWORK ───────────────────────────────────────────────────────
ind('hospital-network','healthcare','Hospital Network','🏥','#1B5E20','#2E7D32',
    'Apex Health Group Berhad',
    '18.4% nurse attrition + 6-week oncology wait — MYR 2.84B revenue at risk.',
    'Apex Health Group Berhad operates 12 hospitals across Malaysia and Indonesia with MYR 2.84B in revenue. Nurse attrition has reached 18.4%, creating ward coverage gaps. Oncology waiting time has stretched to 6 weeks against a 2-week clinical target. A Ministry of Health accreditation review is due in 10 weeks.',
    ['HC_01_Apex_Health_Group.xlsx','HC_02_Apex_Health_Strategy.docx'],
    [
      tool(T_CHAT, FREE_LIC, FREE_ACCT, [
        'I am the COO of a private hospital group managing 12 hospitals across Malaysia and Indonesia. Nurse attrition has reached 18.4% — nearly double the industry benchmark of 10%. Draft a structured root cause analysis framework I can use to run a half-day workshop with my nursing directors. The framework should identify the five most common reasons nurses leave private hospitals in Southeast Asia, suggest data sources to validate each hypothesis, and propose one intervention per root cause that can be implemented within 60 days without significant capital outlay.',
        'Explain the MOH Malaysia hospital accreditation process — what is the scope of review, what clinical and administrative standards are assessed, and what are the consequences for a private hospital that fails the inspection? I need to brief my Board in 5 minutes, so keep the answer to 150 words.',
        'What are the five most effective evidence-based interventions to reduce oncology waiting times in a private hospital setting? For each intervention, indicate the typical implementation timeline, estimated cost range, and the clinical benefit in terms of waiting time reduction. Focus on approaches that can be implemented with existing technology and staff.'
      ]),
      tool(T_RESEARCHER, M365_LIC, M365_ACCT, [
        'Research nurse retention strategies used by private hospital groups in Southeast Asia that have successfully reduced attrition from above 15% to below 10% within 18 months. I need: (1) The specific interventions used, (2) The cost per FTE of implementing the programme, (3) The return on investment compared to replacement cost. Provide citations from healthcare management journals or industry reports.',
        'Research the regulatory environment for private hospitals in Malaysia — specifically the Private Healthcare Facilities and Services Act (PHFSA) requirements for clinical staffing ratios, patient safety reporting, and data protection for medical records. Summarise the five most critical compliance obligations and recent MOH enforcement actions. Cite sources.'
      ], DESC_RESEARCHER),
      tool(T_ANALYST, M365_LIC, M365_ACCT, [
        'Upload HC_01_Apex_Health_Group.xlsx to Analyst. Ask: Analyse nurse attrition data by hospital, department, and seniority band (junior 0-3 years, mid 4-7 years, senior 8+ years). Which hospital has the highest attrition? Which seniority band is leaving fastest? Calculate the annual replacement cost per nurse (assume MYR 18,000 in recruitment and training cost per hire) and the total group-level cost of current attrition. Present as a heat map table and a cost waterfall chart.',
        'Upload HC_01_Apex_Health_Group.xlsx. Ask Analyst: Analyse the oncology department waiting time data across all 12 hospitals. Which hospitals have the longest average waiting time for first oncologist consultation? Calculate the revenue at risk — assume each week of excess wait costs 1.4% patient leakage to competitor hospitals and each oncology patient generates MYR 85,000 in average annual revenue. Show as a ranked table and a bar chart.'
      ], DESC_ANALYST),
      tool(T_EXCEL, M365_LIC, M365_ACCT, [
        'Open HC_01_Apex_Health_Group.xlsx. Navigate to the Workforce Planning sheet. Ask Copilot: Create a nurse attrition prediction model. For each hospital, calculate: (1) current attrition rate, (2) projected ward coverage gap if attrition continues at the same rate for 6 more months, (3) the minimum number of new nurse hires required to maintain safe patient-to-nurse ratios. Flag any hospital in red where the coverage gap exceeds 15%.',
        'Ask Copilot: Build an MOH accreditation readiness tracker on a new sheet. List the 20 key accreditation criteria from the strategy document. For each criterion, add columns: Current Status (Compliant/Gap/Unknown), Evidence Required, Responsible Department, and Target Completion Date. Apply conditional formatting: green for Compliant, yellow for In Progress, red for Gap.',
        'Ask Copilot: In the Revenue by Specialty sheet, calculate the revenue contribution of oncology, cardiology, and orthopaedics as a percentage of total group revenue for each of the last 4 years. Show the trend as a stacked area chart. Flag any specialty where revenue share has declined more than 3 percentage points year-on-year.',
      ]),
      tool(T_WORD, M365_LIC, M365_ACCT, [
        'Open HC_02_Apex_Health_Strategy.docx. Ask Copilot: Draft a nurse retention action plan of 2 pages. Cover: (1) Current attrition rate and financial impact, (2) Three root causes identified from our exit interview data, (3) Five specific retention interventions with timelines and costs, (4) KPIs: target attrition rate of 12% within 6 months, (5) Governance — who is accountable. Write in a formal healthcare management style.',
        'Ask Copilot in Word: Identify all sections in this strategy document that reference clinical quality or patient safety. Summarise each section\'s key commitment in one sentence and create a compliance gap table showing which commitments have measurable KPIs and which do not.',
        'Ask Copilot: Draft a 300-word CEO statement for the group\'s MOH accreditation submission. The statement should demonstrate commitment to patient safety, acknowledge the oncology waiting time challenge and the corrective actions underway, and reaffirm the group\'s investment in clinical excellence and nursing capability.'
      ]),
      tool(T_PPT, M365_LIC, M365_ACCT, [
        'Ask Copilot in PowerPoint: Create a 10-slide Board presentation titled "Clinical Operations Transformation — FY2026 Priorities". Include: (1) Executive summary — key challenges (attrition, oncology wait, accreditation), (2) Nurse attrition dashboard, (3) Root cause analysis, (4) Retention programme — 5 initiatives, (5) Oncology capacity expansion plan, (6) MOH accreditation readiness — RAG status, (7) Financial impact if we solve vs do nothing, (8) Capital investment required, (9) Risk register, (10) Board decisions required. Use a professional green and white colour scheme.',
        'Ask Copilot: For each slide, write speaker notes that anticipate Board questions. The Chairman has a clinical background, so the notes should go deeper on patient safety implications than on financials.',
        'Ask Copilot: Create a one-slide oncology waiting time comparison chart showing our 6-week average against the 2-week clinical target and the 3.5-week industry benchmark for private hospitals in Malaysia. Add a call-out box showing the estimated annual revenue at risk from patient leakage.'
      ]),
      tool(T_OUTLOOK, M365_LIC, M365_ACCT, [
        'Ask Copilot in Outlook: Draft a letter to the MOH accreditation team requesting a 30-day extension on the submission of our clinical staffing compliance documentation. The letter should acknowledge the reason for the delay (nursing staff restructuring in progress), describe the remediation actions we have taken, and provide a specific new submission date. Use the formal tone required for MOH correspondence.',
        'Ask Copilot: Draft an internal email to all 12 Hospital Directors briefing them on the MOH accreditation review in 10 weeks. The email should: list the 5 highest-risk accreditation criteria based on our gap assessment, assign each Hospital Director specific pre-inspection actions, request confirmation of their hospital\'s readiness status by next Friday, and stress the importance of accurate, consistent documentation.',
        'Ask Copilot: I have received 3 complaints from oncology patients about their waiting time. Draft personalised, empathetic response emails for each patient that: acknowledge the delay without making legal admissions, explain what steps we are taking to reduce waiting times, and offer to personally expedite their case review. Use a warm, caring tone appropriate for clinical communication.'
      ]),
      tool(T_TEAMS, M365_LIC, M365_ACCT, [
        'Open a recorded Teams meeting recap from a clinical leadership or operations committee meeting. Ask Copilot: Identify all patient safety issues discussed, the corrective actions committed to, and any incidents that require escalation to the MOH or the Medical Advisory Board. Format as a clinical governance meeting summary.',
        'Ask Copilot in the recap: Draft follow-up action items for the nurse retention taskforce. Include: the specific hospital or department where each action applies, the nurse manager responsible, the completion deadline, and the KPI that will confirm the action was effective.',
        'Ask Copilot: Were any specific financial figures discussed in this meeting related to attrition costs or oncology revenue? Extract and list them with context so I can update the financial impact model.'
      ], DESC_TEAMS),
      tool(T_NOTEBOOK, M365_LIC, M365_ACCT, [
        'Upload HC_01_Apex_Health_Group.xlsx and HC_02_Apex_Health_Strategy.docx to Copilot Notebook. Set instruction: "You are a healthcare management consultant. Help the COO prioritise clinical and operational interventions." Ask: Based on the workforce and revenue data and our strategic priorities, which single intervention — nurse retention programme or oncology capacity expansion — will deliver the highest financial return within 12 months? Show the reasoning and key assumptions.',
        'Upload HC_01_Apex_Health_Group.xlsx and HC_02_Apex_Health_Strategy.docx. Ask: The strategy document commits to expanding oncology services to 3 new hospitals. The workforce data shows we already have a nursing shortage in our existing hospitals. Are these two objectives compatible? What workforce plan would be needed before the oncology expansion can proceed safely?'
      ], DESC_NOTEBOOK),
      tool(T_COWORK, FRONTIER_LIC, M365_ACCT, [
        'Do all of the following for MOH accreditation prep: (1) Research MOH Malaysia\'s latest PHFSA inspection criteria updated in 2024 or 2025. (2) Draft a 10-point pre-inspection checklist for Hospital Directors covering the highest-risk compliance areas. (3) Save to OneDrive as "MOH Accreditation Pre-Inspection Checklist". (4) Email to all 12 Hospital Directors with subject "Action Required: MOH Accreditation Prep — 10 Weeks to Inspection" asking each to complete the self-assessment and return it within 2 weeks. (5) Schedule a 90-minute Group Clinical Governance Review via Teams for 3 weeks before the inspection date.',
        'Do all of the following for nurse retention: (1) Identify the 3 hospitals with the highest nurse attrition rates from the data. (2) Draft personalised retention initiative proposals for each hospital — customised based on their specific attrition drivers. (3) Email the proposals to each Hospital Director and Nursing Director. (4) Create a retention programme tracker spreadsheet in OneDrive with weekly attrition rate tracking for each hospital. (5) Post in the #clinical-operations Teams channel: "Nurse Retention Programme launched for 3 priority hospitals — see OneDrive for trackers."'
      ], DESC_COWORK),
      tool(T_WORD_AGT, M365_LIC, M365_ACCT, [
        'Open HC_02_Apex_Health_Strategy.docx in Word for Web. Create an agent called "Clinical Governance Policy Bot". Description: "Answers questions from Hospital Directors, nursing managers, and clinical staff about Apex Health\'s clinical governance policies, MOH accreditation requirements, staffing ratios, and patient safety protocols." Share with all 12 hospitals.',
        'Demo: A nursing manager asks "What is the minimum nurse-to-patient ratio for a general medical ward during night shift under our current policy? And what is the escalation procedure if we fall below the minimum due to unexpected absenteeism?" Show how the agent provides an immediate, policy-grounded answer.'
      ], DESC_WORD_AGT),
      tool(T_PPT_AGT, M365_LIC, M365_ACCT, [
        'Create a PowerPoint from the Board presentation and open in PowerPoint for Web. Create an agent called "Clinical Ops Board Q&A Bot". Share with Board members and the Medical Advisory Board.',
        'Demo: A Board member asks "If we implement all 5 nurse retention initiatives, what is the projected attrition rate at the end of FY2026 and what does that mean for ward coverage at our largest hospital?" Show how Board members get scenario-specific answers before the meeting.'
      ], DESC_PPT_AGT),
      tool(T_XL_AGT, M365_LIC, M365_ACCT, [
        'Open HC_01_Apex_Health_Group.xlsx in Excel for Web. Create an agent called "Apex Health Operations Q&A". Description: "Instant answers on nurse attrition, oncology waiting times, revenue by specialty, and MOH compliance indicators for COO and Hospital Directors." Share with clinical and operational leadership.',
        'Demo: Ask "Which hospital has the lowest nurse retention rate and what is the current patient-to-nurse ratio in its ICU?" Then: "How much revenue did oncology generate across the group in FY2025 and which hospital contributed the most?" Show how the COO gets rapid operational intelligence.'
      ], DESC_XL_AGT),
      tool(T_BUILDER, M365_LIC, M365_ACCT, [
        'Go to copilotstudio.microsoft.com > Create > New Agent. Name it "Apex Health Clinical Assistant". Description: "Supports clinical and operations teams across all 12 Apex Health hospitals — answers questions on clinical governance policies, nurse staffing standards, MOH accreditation requirements, and patient safety protocols. Ensures consistent, policy-grounded responses across the hospital network." Upload HC_02_Apex_Health_Strategy.docx. Add topics: "Staffing Standards", "MOH Accreditation", "Patient Safety", "Oncology Protocols". Publish to Teams for all hospital staff.',
        'Demo the agent: A junior doctor asks: "A patient in my oncology clinic has been waiting 8 weeks for their second chemotherapy cycle due to scheduling issues. What is the clinical escalation pathway and am I required to file an incident report? Who do I notify?" Show how the agent gives a clear, policy-grounded escalation guidance that protects both the patient and the clinician.'
      ], DESC_BUILDER),
    ]),

# ── PHARMACEUTICAL ─────────────────────────────────────────────────────────
ind('pharmaceutical','healthcare','Pharmaceutical','💊','#2E7D32','#388E3C',
    'ZavaGen Pharmaceutical (Zava Pharma)',
    '3 BPOM enforcement notices closed — Sitagliptin 100mg BPfK registration in progress.',
    'ZavaGen Pharmaceutical is the pharmaceutical arm of Zava Group, operating plants in Cikarang (Indonesia) and Johor (Malaysia). Three BPOM enforcement notices were received and all closed as of April 2025. BPfK registration for Sitagliptin 100mg is in progress. Four products are in Phase II/III clinical trials. GMP certification renewal is due in 3 months.',
    ['17_Zava_Pharma_Pipeline.xlsx','Email_11_Sitagliptin_BPOM_Registration.docx'],
    [
      tool(T_CHAT, FREE_LIC, FREE_ACCT, [
        'I am the Head of Regulatory Affairs at a pharmaceutical company with manufacturing plants in Malaysia and Indonesia. We have just closed three BPOM enforcement notices and need to demonstrate to BPOM and our investors that our quality management system is now fully compliant. Draft a 300-word regulatory remediation statement that I can use in investor communications and regulatory correspondence. The statement should acknowledge the issues, explain the root cause at a high level, describe the corrective and preventive actions (CAPAs) implemented, and assert our current compliance status without creating liability.',
        'Explain the difference between BPOM (Indonesia) and BPfK (Malaysia) drug registration processes for a generic pharmaceutical product. What are the key differences in documentation requirements, review timelines, and post-approval obligations? Keep the answer under 250 words and suitable for briefing a CEO who is not a regulatory expert.',
        'What are the GMP (Good Manufacturing Practice) requirements under ASEAN harmonised guidelines for pharmaceutical tablet manufacturing? List the five most critical areas an inspector looks at during a GMP audit and the most common findings that lead to a warning letter or enforcement notice.'
      ]),
      tool(T_RESEARCHER, M365_LIC, M365_ACCT, [
        'Research the market opportunity for Sitagliptin (a DPP-4 inhibitor for Type 2 diabetes) in Malaysia and Indonesia. I need: (1) Market size and growth rate for diabetes medications in both countries, (2) Current competitors and their market share, (3) Any pricing regulations or reimbursement status under MOH Malaysia and BPJS Indonesia. Provide citations.',
        'Research the latest ASEAN GMP guidelines updates and any BPOM enforcement trends in the Indonesian pharmaceutical sector in 2024 and 2025. Are there specific areas where enforcement has been more active? Have any major multinational pharmaceutical companies received enforcement actions? Provide citations.'
      ], DESC_RESEARCHER),
      tool(T_ANALYST, M365_LIC, M365_ACCT, [
        'Upload 17_Zava_Pharma_Pipeline.xlsx to Analyst. Ask: Analyse the clinical trial pipeline — 4 products in Phase II/III. For each product, show the estimated market size, probability of approval (use industry average Phase II→III success rate of 52% and Phase III→approval rate of 68%), and projected revenue at Year 3 post-launch. Rank the pipeline by expected value (market size × approval probability). Present as a ranked table and a bubble chart.',
        'Upload 17_Zava_Pharma_Pipeline.xlsx. Ask: Build a GMP compliance risk dashboard. For each manufacturing site, show: (1) Last GMP inspection date and outcome, (2) Number of open CAPAs by severity (critical, major, minor), (3) Days until next GMP certification renewal. Highlight in red any site with a critical CAPA open for more than 60 days or a renewal due within 90 days.'
      ], DESC_ANALYST),
      tool(T_EXCEL, M365_LIC, M365_ACCT, [
        'Open 17_Zava_Pharma_Pipeline.xlsx. Navigate to the Pipeline sheet. Ask Copilot: Create a product launch revenue model for Sitagliptin 100mg assuming BPfK approval in Q3 FY2026. Assume: Year 1 market share 3%, Year 2 5%, Year 3 8% of a MYR 420M total addressable market. Calculate annual revenue, gross margin at 62%, and contribution after regulatory and marketing costs. Show as a 5-year P&L projection.',
        'Ask Copilot: In the CAPA Tracker sheet, identify all open CAPAs where the target completion date has passed. For each overdue CAPA, calculate the number of days overdue and flag the severity level. Create a summary showing: Total Open CAPAs | Critical Overdue | Major Overdue | Minor Overdue. This summary should be the first thing a BPOM inspector sees.',
        'Ask Copilot: Build a batch release productivity model on a new sheet. For the Cikarang plant, calculate: (1) Average batch release cycle time (days from manufacturing to QA release), (2) Percentage of batches released within the 14-day SLA, (3) Percentage of batches requiring OOS (Out of Specification) investigation. Flag any trend of increasing OOS rate over the last 6 months.'
      ]),
      tool(T_WORD, M365_LIC, M365_ACCT, [
        'Open Email_11_Sitagliptin_BPOM_Registration.docx. Ask Copilot: Draft a BPfK drug registration covering letter for Sitagliptin 100mg. The letter should: identify the product and applicant, reference the CTD (Common Technical Document) dossier being submitted, highlight the key data supporting safety and efficacy (Phase III results: HbA1c reduction 0.82%, placebo-adjusted), note the ASEAN harmonised registration pathway being used, and request acknowledgement of receipt. Use the formal BPfK correspondence format.',
        'Ask Copilot in Word: Draft a CAPA summary report for submission to BPOM covering the three enforcement notices now closed. For each notice, provide: (1) The original finding, (2) Root cause identified, (3) CAPA implemented, (4) Evidence of effectiveness, (5) Date of closure. Use the BPOM CAPA report format with numbered sections.',
        'Ask Copilot: Draft a GMP audit readiness checklist in Word format. The checklist should cover the 10 key areas a GMP inspector will review: documentation, personnel training, equipment qualification, environmental monitoring, batch records, QA release procedures, deviation management, CAPA system, product complaints, and change control. For each area, include a self-assessment column and an evidence required column.'
      ]),
      tool(T_PPT, M365_LIC, M365_ACCT, [
        'Ask Copilot in PowerPoint: Create an 8-slide pharmaceutical pipeline investor update presentation for ZavaGen. Include: (1) Company overview and manufacturing footprint, (2) Regulatory compliance update — 3 BPOM notices closed, (3) Pipeline overview — 4 products in Phase II/III, (4) Sitagliptin 100mg — BPfK registration status and market opportunity, (5) GMP certification renewal plan, (6) Financial projections — pipeline NPV, (7) Partnerships and licensing opportunities, (8) Investment thesis. Use a professional blue and white design.',
        'Ask Copilot: Create a 3-slide GMP remediation update for the ZavaGen Cikarang plant. Slides: (1) Before/after — the 3 BPOM enforcement notices and what we fixed, (2) Current GMP compliance scorecard — 10 key criteria with RAG status, (3) GMP certification renewal plan and timeline. Keep it factual and confidence-building for a regulatory audience.',
        'Ask Copilot: Add a risk matrix slide to the investor presentation showing the top 5 risks to our pipeline — regulatory delay, manufacturing failure, competitor generic launch, IP challenge, and market access — each positioned on a likelihood vs impact matrix with a one-line mitigation.'
      ]),
      tool(T_OUTLOOK, M365_LIC, M365_ACCT, [
        'Open Email_11_Sitagliptin_BPOM_Registration.docx. Ask Copilot in Outlook: Draft a follow-up email to our BPfK regulatory contact requesting an update on the Sitagliptin 100mg registration status. The submission has been pending for 4 months. The email should be professional and persistent without being aggressive, reference the submission date and dossier reference number, and ask for an estimated review completion timeline.',
        'Ask Copilot: Draft an email to our GMP consultant requesting a pre-audit inspection simulation for the Cikarang plant ahead of the certification renewal in 3 months. The email should specify the scope of the simulation (all 10 GMP areas), the preferred dates (within the next 4 weeks), and request a quote for the engagement.',
        'Ask Copilot: Summarise the email thread in Email_11_Sitagliptin_BPOM_Registration.docx. What are the key outstanding documentation gaps identified by BPfK? List each gap with the section of the dossier it refers to and the deadline for submission.'
      ]),
      tool(T_TEAMS, M365_LIC, M365_ACCT, [
        'Open an existing recorded Teams meeting recap from a regulatory affairs or quality management meeting. Ask Copilot: Identify all regulatory submission milestones discussed, the current status of each, and any at-risk items where the deadline may be missed. Format as a regulatory affairs status report.',
        'Ask Copilot in the recap: Draft follow-up actions for the GMP certification renewal project. Include: the specific action, the department responsible, the completion deadline, and the dependency on any other action that must come first. Present as a project task list.',
        'Ask Copilot: Were any batch manufacturing issues or quality failures discussed in this meeting? List each with: the product, the nature of the issue, the investigation status, and whether BPOM or BPfK notification was discussed.'
      ], DESC_TEAMS),
      tool(T_NOTEBOOK, M365_LIC, M365_ACCT, [
        'Upload 17_Zava_Pharma_Pipeline.xlsx and Email_11_Sitagliptin_BPOM_Registration.docx to Copilot Notebook. Set instruction: "You are a pharmaceutical regulatory strategist." Ask: Based on our pipeline data and the Sitagliptin registration status, what is the earliest realistic date we can begin generating revenue from our Phase III pipeline? What are the top 3 risks to that timeline and how should we mitigate them?',
        'Upload 17_Zava_Pharma_Pipeline.xlsx and Email_11_Sitagliptin_BPOM_Registration.docx. Ask: Our pipeline has 4 products in Phase II/III. Given that 3 BPOM enforcement notices were recently closed and our GMP certification is up for renewal, is it realistic to pursue all 4 products simultaneously? Should we prioritise and deprioritise based on regulatory risk, market size, or manufacturing complexity? Recommend a portfolio strategy.'
      ], DESC_NOTEBOOK),
      tool(T_COWORK, FRONTIER_LIC, M365_ACCT, [
        'Do all of the following: (1) Research the BPfK review timeline for Type 2 diabetes generic medications and identify if there are expedited review pathways available. (2) Draft a BPfK expedited review application letter for Sitagliptin 100mg, citing the unmet need in the Malaysian diabetes patient population. (3) Save to OneDrive as "Sitagliptin BPfK Expedited Review Application". (4) Email to our Regulatory Affairs Director and General Counsel for review by Wednesday. (5) Schedule a Regulatory Strategy Meeting for Thursday with the Head of Regulatory Affairs, CMO, and CFO.',
        'Do all of the following for GMP certification renewal: (1) Compile a pre-audit checklist of all documentation required for the Cikarang plant GMP renewal. (2) Send a request to each department head (QA, Production, Engineering, Warehouse) asking them to self-assess their readiness against the checklist and respond within 5 business days. (3) Schedule a pre-audit simulation with our external GMP consultant for 6 weeks from today. (4) Create a GMP renewal tracker in SharePoint with a column for each of the 10 audit areas and status (Ready/In Progress/Not Ready). (5) Post in the #quality-operations Teams channel: "GMP certification renewal is in 3 months. Pre-audit simulation scheduled. Please complete your self-assessments by [date]."'
      ], DESC_COWORK),
      tool(T_WORD_AGT, M365_LIC, M365_ACCT, [
        'Open Email_11_Sitagliptin_BPOM_Registration.docx in Word for Web. Create an agent called "Regulatory Submission Tracker". Description: "Answers questions from the regulatory affairs team about the status of drug registration submissions, outstanding documentation gaps, and correspondence with BPOM and BPfK. Grounded in official regulatory correspondence files." Share with the regulatory affairs team.',
        'Demo: Ask the Regulatory Tracker "What documentation gaps did BPfK identify in the Sitagliptin 100mg dossier review and have all of them been addressed?" Show how the team gets instant, document-grounded status updates without digging through email threads.'
      ], DESC_WORD_AGT),
      tool(T_PPT_AGT, M365_LIC, M365_ACCT, [
        'Create a PowerPoint from the pipeline investor presentation. Create an agent called "ZavaGen Pipeline Investor Q&A". Share with investor relations and institutional investors.',
        'Demo: An investor asks "What is the expected approval date for Sitagliptin 100mg and what is the projected market share in Year 2 post-launch in Malaysia?" Show how the IR team handles investor questions consistently using the agent during roadshows.'
      ], DESC_PPT_AGT),
      tool(T_XL_AGT, M365_LIC, M365_ACCT, [
        'Open 17_Zava_Pharma_Pipeline.xlsx in Excel for Web. Create an agent called "Pharma Pipeline Analytics Q&A". Description: "Answers questions about ZavaGen\'s product pipeline, GMP compliance status, CAPA tracker, and Sitagliptin registration — for the regulatory affairs, QA, and finance teams." Share broadly.',
        'Demo: Ask "How many open CAPAs are there at the Cikarang plant and how many are critical?" Then: "What is the probability-adjusted NPV of our Phase II pipeline assuming 52% transition success rate?" Show how management gets rapid pipeline intelligence.'
      ], DESC_XL_AGT),
      tool(T_BUILDER, M365_LIC, M365_ACCT, [
        'Go to copilotstudio.microsoft.com > Create > New Agent. Name it "ZavaGen Regulatory Intelligence Bot". Description: "Supports ZavaGen\'s regulatory affairs and quality teams with instant answers on BPOM and BPfK submission requirements, GMP standards, CAPA management, and pipeline registration status. Grounded in regulatory submissions and quality management documents." Upload 17_Zava_Pharma_Pipeline.xlsx and Email_11_Sitagliptin_BPOM_Registration.docx. Add topics: "BPOM Requirements", "BPfK Submission", "GMP Standards", "CAPA Management". Publish to Teams.',
        'Demo the agent: A QA manager at the Cikarang plant asks: "We have discovered a batch of Sitagliptin tablets where the dissolution rate is 2% below the lower specification limit. What is the OOS investigation procedure, do I need to quarantine the batch, and does this need to be reported to BPOM?" Show how the agent walks the QA manager through the correct procedure step by step.'
      ], DESC_BUILDER),
    ]),

# ── OIL & GAS UPSTREAM ─────────────────────────────────────────────────────
ind('og-upstream','og-energy','Oil & Gas — Upstream','⛽','#E65100','#F57C00',
    'Nusantara Energy Berhad',
    'Tier 1 PSE at Miri field — PETRONAS HSE audit in 6 weeks. 2 offshore spill incidents.',
    'Nusantara Energy Berhad is an upstream oil and gas operator with a Tier 1 Process Safety Event (PSE) at its Miri offshore field. Two minor offshore spill incidents were reported to PETRONAS in Q3. The HSE audit is scheduled in 6 weeks. Net Zero 2050 commitments require a 30% GHG reduction plan by Q1 FY2027.',
    ['OG_01_Nusantara_Energy.xlsx','OG_02_Nusantara_HSE_Report.docx','Email_04_PETRONAS_Meeting_Prep.docx'],
    [
      tool(T_CHAT, FREE_LIC, FREE_ACCT, [
        'I am the Head of HSE at a Malaysian upstream oil and gas company. We have experienced two minor offshore spill incidents this quarter and a Tier 1 Process Safety Event at our Miri field. A PETRONAS HSE audit is in 6 weeks. Draft a 300-word incident investigation brief I can use to brief the PETRONAS audit team. The brief should: describe the nature of the Tier 1 PSE without minimising it, explain the investigation methodology used, summarise the root cause findings, and list the corrective actions implemented. Tone: transparent, professional, and accountability-focused.',
        'Explain the PETRONAS Process Safety Management (PSM) framework for upstream offshore operations. What are the five key elements of the framework, what does a Tier 1 PSE classification mean, and what are the regulatory reporting obligations under the Malaysia Energy Commission (ST) and Department of Environment (DOE) following such an event?',
        'What are the best practices for managing GHG emissions in upstream offshore oil and gas operations? Focus on practical measures that can be implemented within 12–18 months without major capital investment. Include examples of measures used by operators in Southeast Asia and their typical GHG reduction impact in percentage terms.'
      ]),
      tool(T_RESEARCHER, M365_LIC, M365_ACCT, [
        'Research PETRONAS HSE audit requirements and the typical findings that upstream operators receive. I need: (1) The key HSE performance indicators PETRONAS measures during audits, (2) The most common non-conformances issued to upstream operators in Malaysia in 2023–2025, (3) Any PETRONAS HSE circulars or updates issued in the past 12 months. Provide citations.',
        'Research global upstream oil and gas Net Zero 2050 strategies adopted by operators of similar scale to Nusantara Energy (production 50,000–100,000 BOE/day). What are the most cost-effective GHG reduction levers? How are operators in Southeast Asia balancing production growth with decarbonisation commitments? Cite recent industry reports.'
      ], DESC_RESEARCHER),
      tool(T_ANALYST, M365_LIC, M365_ACCT, [
        'Upload OG_01_Nusantara_Energy.xlsx to Analyst. Ask: Analyse the HSE incident data for the past 3 years. What is the trend in Total Recordable Incident Rate (TRIR), Lost Time Incident Rate (LTIR), and Process Safety Events (PSE) by severity tier? Are incidents concentrated at specific offshore platforms or in specific operations (drilling, production, maintenance)? Create a trend chart and an incident heat map by platform.',
        'Upload OG_01_Nusantara_Energy.xlsx. Ask: Build a GHG emissions analysis. Show Scope 1 and Scope 2 emissions by platform and operating unit for FY2023–FY2025. Calculate the GHG intensity (tCO2e per BOE produced). Identify the 3 highest-emitting platforms and estimate the GHG reduction potential if each implemented the top emission reduction measure appropriate for that platform type. Show as a ranked table with reduction potential in tCO2e and as a percentage of total Scope 1 emissions.'
      ], DESC_ANALYST),
      tool(T_EXCEL, M365_LIC, M365_ACCT, [
        'Open OG_01_Nusantara_Energy.xlsx. Navigate to the HSE KPI sheet. Ask Copilot: Create a PETRONAS HSE audit readiness dashboard on a new sheet. For each of the 12 key HSE performance indicators PETRONAS measures, show: (1) Our current performance, (2) PETRONAS threshold, (3) Status (Above/Below threshold), (4) Trend (Improving/Stable/Deteriorating). Highlight in red any indicator that is below threshold and deteriorating.',
        'Ask Copilot: Build a corrective action plan (CAP) tracker on a new sheet. List all open CAPAs from the Tier 1 PSE investigation and the two spill incidents. For each CAPA, include: Description | Root Cause Category | Priority (Critical/High/Medium) | Owner | Due Date | Status | % Complete. Apply conditional formatting: overdue critical items in red, overdue high items in orange.',
        'Ask Copilot: In the Production Data sheet, calculate the production uptime percentage for each offshore platform over the past 4 quarters. Identify which platforms have experienced the most unplanned shutdowns and whether there is a correlation between unplanned shutdowns and the incidents in the HSE data sheet. Show as a scatter plot.'
      ]),
      tool(T_WORD, M365_LIC, M365_ACCT, [
        'Open OG_02_Nusantara_HSE_Report.docx. Ask Copilot: Rewrite the Executive Summary of this HSE report to address the PETRONAS audit team directly. The new summary should: acknowledge the Tier 1 PSE transparently, demonstrate that our incident investigation followed PETRONAS PSM guidelines, highlight the 5 most significant corrective actions implemented, and project our target TRIR for the next 12 months. Use a confident but accountable regulatory tone.',
        'Ask Copilot in Word: Create a Net Zero 2050 GHG reduction roadmap section for the annual sustainability report. Cover: (1) Our current Scope 1+2 baseline in tCO2e, (2) 5 key reduction levers — flare reduction, electrification, energy efficiency, methane leak detection, and carbon capture feasibility, (3) 2030 interim target: 30% reduction vs 2020 baseline, (4) Investment required and payback period for each lever. Format as a structured narrative with a table.',
        'Ask Copilot: Draft a PETRONAS pre-audit submission letter. The letter should: confirm our readiness for the scheduled audit, provide a summary of corrective actions since the last audit, highlight our HSE improvement initiatives, and request 30 minutes at the start of the audit for a management presentation. Use the formal correspondence format required for PETRONAS regulatory submissions.'
      ]),
      tool(T_PPT, M365_LIC, M365_ACCT, [
        'Ask Copilot in PowerPoint: Create a 12-slide PETRONAS HSE audit management presentation. Include: (1) Company overview and operational scope, (2) HSE performance dashboard — 3-year trend, (3) Tier 1 PSE — incident, investigation, root cause, (4) Corrective actions implemented — CAPA tracker summary, (5) Two spill incidents — cause and remediation, (6) HSE management system maturity assessment, (7) Contractor HSE performance, (8) Emergency response readiness, (9) Net Zero 2050 — GHG reduction roadmap, (10) HSE investment plan FY2026, (11) Key risks and mitigants, (12) Our commitment to PETRONAS HSE standards. Use a dark green and white professional colour scheme.',
        'Ask Copilot: For each slide, generate speaker notes that anticipate the PETRONAS audit team\'s follow-up questions. The audit lead is known to probe hard on root cause analysis quality — the notes should show that we have used structured RCA methodology (such as 5-Why or Bowtie).',
        'Ask Copilot: Add a bowtie diagram on slide 3 showing the Tier 1 PSE event — the threat on the left, the top event in the middle, the consequences on the right, with prevention barriers on the left side and recovery barriers on the right. Include which barriers failed and which held.'
      ]),
      tool(T_OUTLOOK, M365_LIC, M365_ACCT, [
        'Open Email_04_PETRONAS_Meeting_Prep.docx. Ask Copilot in Outlook: Draft a formal pre-audit meeting request to our PETRONAS account manager. The email should: reference the upcoming HSE audit date, request a 30-minute pre-audit briefing to present our self-assessment and corrective action progress, propose two available dates, and attach the executive summary of our HSE performance report (note: attach separately). Use formal energy industry correspondence tone.',
        'Ask Copilot: Draft an internal email to the Miri Platform management team briefing them on the PETRONAS HSE audit in 6 weeks. The email should: list the 5 areas the audit team will focus on based on our previous audit findings, assign a responsible person for each area, request that all documentation be ready for review 2 weeks before the audit, and remind the team of the confidentiality requirements during the audit.',
        'Ask Copilot: Summarise the email thread in Email_04_PETRONAS_Meeting_Prep.docx. What specific documentation has PETRONAS requested for the audit? List each requested document, the section of the PSM framework it relates to, and whether we currently have the document ready.'
      ]),
      tool(T_TEAMS, M365_LIC, M365_ACCT, [
        'Open an existing recorded Teams meeting recap from an HSE or operations review meeting. Ask Copilot: Identify all safety-critical action items discussed, the owner of each, and the due date. Flag any action item that is related to the Tier 1 PSE CAPA plan as "Priority". Format as an HSE action register.',
        'Ask Copilot: Draft a post-incident communication for the Miri platform crew following the Tier 1 PSE. The communication should: acknowledge the incident without assigning blame, explain the immediate corrective actions taken to make the platform safe, outline the lessons-learned review process, and thank the crew for their cooperation. Tone: open, safety-first, respectful.',
        'Ask Copilot: Based on this meeting transcript, identify any discussion about GHG or emissions topics. List any emissions reduction targets or milestones mentioned and check whether they are consistent with our stated Net Zero 2050 commitment.'
      ], DESC_TEAMS),
      tool(T_NOTEBOOK, M365_LIC, M365_ACCT, [
        'Upload OG_01_Nusantara_Energy.xlsx, OG_02_Nusantara_HSE_Report.docx, and Email_04_PETRONAS_Meeting_Prep.docx to Copilot Notebook. Set instruction: "You are a senior HSE consultant preparing a company for a PETRONAS regulatory audit." Ask: Based on the HSE performance data, the incident report, and the PETRONAS correspondence, what are the three most likely areas of non-conformance in the upcoming audit? For each, what evidence should we prepare to demonstrate that the corrective action has been effective?',
        'Upload OG_01_Nusantara_Energy.xlsx and OG_02_Nusantara_HSE_Report.docx. Ask: The HSE report commits to a 30% GHG reduction by 2030. Based on the current production data and emissions data, what is the implied annual reduction required? Which single platform — if it implemented all identified GHG reduction measures — would contribute most to achieving the 2030 target? Is the target achievable without reducing production?'
      ], DESC_NOTEBOOK),
      tool(T_COWORK, FRONTIER_LIC, M365_ACCT, [
        'Do all of the following for the PETRONAS HSE audit: (1) Research PETRONAS\'s latest Process Safety Management framework and any updated audit criteria published in 2024 or 2025. (2) Draft a self-assessment gap analysis comparing our current practices against the updated criteria. (3) Save to OneDrive as "PETRONAS HSE Audit Self-Assessment - [Date]". (4) Email to the VP HSE and the Miri Platform HSE Manager asking for review and input within 3 days. (5) Schedule a 2-hour "PETRONAS Audit Prep Workshop" for 5 weeks before the audit date and invite all platform HSE leads.',
        'Do all of the following for the Net Zero roadmap: (1) Research the carbon credit market for oil and gas operators in Malaysia and Indonesia — specifically VERRA and Gold Standard certification. (2) Draft a 2-page carbon credit strategy brief covering: voluntary offset opportunities, estimated cost per tCO2e, and whether offsets should be used to bridge the gap in the 2030 target. (3) Save to OneDrive. (4) Email to the Sustainability Director and CFO. (5) Schedule a Carbon Strategy Workshop for the sustainability team.'
      ], DESC_COWORK),
      tool(T_WORD_AGT, M365_LIC, M365_ACCT, [
        'Open OG_02_Nusantara_HSE_Report.docx in Word for Web. Create an agent called "HSE Policy & Incident Agent". Description: "Answers questions from operations staff and HSE teams about Nusantara Energy\'s HSE policies, incident investigation procedures, PETRONAS reporting requirements, and corrective action obligations." Share with all platform HSE leads.',
        'Demo: A platform supervisor asks "We have just detected a small oil sheen approximately 20 metres from Platform Miri-A. What is the immediate response procedure, who do I notify in the first hour, and is this reportable to PETRONAS and DOE?" Show how the agent walks the supervisor through the emergency response protocol step by step.'
      ], DESC_WORD_AGT),
      tool(T_PPT_AGT, M365_LIC, M365_ACCT, [
        'Create a PowerPoint from the PETRONAS audit management presentation. Create an agent called "PETRONAS Audit Prep Bot". Share with the PETRONAS audit team as a pre-reading tool and with internal leadership.',
        'Demo: The PETRONAS audit lead asks the agent "What corrective action did Nusantara implement following the Tier 1 PSE at Miri, and what evidence is available that the corrective action has been effective?" Show how the agent provides a precise, document-grounded answer that demonstrates accountability.'
      ], DESC_PPT_AGT),
      tool(T_XL_AGT, M365_LIC, M365_ACCT, [
        'Open OG_01_Nusantara_Energy.xlsx in Excel for Web. Create an agent called "Nusantara HSE & Operations Q&A". Description: "Instant answers on HSE KPIs, incident data, platform uptime, GHG emissions, and CAPA tracker status for the HSE leadership and audit preparation teams." Share with VP HSE and platform managers.',
        'Demo: Ask "What was our Lost Time Incident Rate for FY2025 and how does it compare to the PETRONAS threshold?" Then: "Which platform has the highest Scope 1 GHG emissions intensity and by how much does it exceed the group average?" Show how the HSE team gets rapid data-grounded answers.'
      ], DESC_XL_AGT),
      tool(T_BUILDER, M365_LIC, M365_ACCT, [
        'Go to copilotstudio.microsoft.com > Create > New Agent. Name it "Nusantara HSE Compliance Assistant". Description: "Supports Nusantara Energy\'s HSE teams with instant answers on incident reporting procedures, PETRONAS PSM requirements, GHG reduction targets, emergency response protocols, and corrective action tracking. Ensures consistent, standard-compliant responses across all offshore platforms." Upload OG_01_Nusantara_Energy.xlsx and OG_02_Nusantara_HSE_Report.docx. Add topics: "Incident Reporting", "PETRONAS PSM", "Emergency Response", "GHG & Sustainability". Publish to Teams for all HSE staff.',
        'Demo the agent: A drilling supervisor asks "We have a well control incident — a kick — on the Miri-B drilling rig. Gas is showing at the shakers. What is the Level 1 emergency response procedure, who is in the Emergency Command Team, and what do I report to PETRONAS and at what point?" Show how the agent gives an immediate, complete emergency response guidance in a high-stakes situation.'
      ], DESC_BUILDER),
    ]),
]

print(f"Batch 3 written: {len(INDUSTRIES_3)} entries")
