
import sys; sys.path.insert(0,'.')
from util import *

INDUSTRIES_1 = [

# ── GENERAL ───────────────────────────────────────────────────────────────
ind('general','general','⭐ General (Any Role)','⭐','#FF6B35','#FF8C42',
    'Zava Group Berhad',
    'FY2025 EBITDA misses budget by 18% — Board emergency review in 48 hours.',
    'Zava Group Berhad is a Malaysian diversified conglomerate with 11 divisions and about 8,400 employees. FY2025 EBITDA has missed budget by 18%, with 3 divisions now in negative EBITDA and investor confidence starting to wobble. The Group CEO has 48 hours to walk into an emergency Board review with a sharp briefing pack, a defensible variance analysis, and regulatory communications ready to go.',
    ['01_Zava_Group_Financial_Performance.xlsx','02_Zava_Group_Policy_Handbook.docx','03_Zava_Group_Strategy_Framework.docx'],
    [
      tool(T_CHAT, FREE_LIC, FREE_ACCT, [
        'You are the Group Chief of Staff at Zava Group Berhad. FY2025 EBITDA is 18% below budget, 3 divisions are in negative EBITDA, and the Board has called an emergency review in 48 hours. Draft a crisp 1-page CEO briefing that explains the situation in plain language, the likely questions directors will ask first, and the 5 decisions that must be ready before the meeting opens. Present as a structured table with columns for Issue, Why It Matters, Board Question, and Recommended Answer.',
        'You are the Group CFO at Zava Group Berhad. The CEO needs a verbal opening script for a high-pressure Board session after an 18% EBITDA miss across an 11-division conglomerate with 8,400 employees. Write a 90-second opening statement that acknowledges the underperformance directly, explains why 3 divisions have fallen into negative EBITDA, and signals immediate corrective action without sounding defensive. End with 3 talking points the CEO can use if directors challenge management credibility.',
        'You are the Head of Corporate Affairs at Zava Group Berhad. Prepare a stakeholder communication map for an 18% FY2025 EBITDA miss, 3 negative-EBITDA divisions, and an emergency Board review in 48 hours. Identify the priority audiences, the message each audience needs, the timing, and the main communication risk if the message is mishandled. Present as a RAG table with Red for immediate same-day communication needs, Amber for 24-hour needs, and Green for monitor-only audiences.'
      ]),
      tool(T_RESEARCHER, M365_LIC, M365_ACCT, [
        'You are the Group Strategy Director at Zava Group Berhad. Research how large diversified conglomerates in Malaysia and Indonesia have responded to EBITDA shortfalls of more than 15% against budget from 2022 to 2025. For at least 3 published case studies, identify the trigger event, the Board response within 30 days, and the financial outcome 12 months later. Cite all sources including publication dates and flag any claim that could not be independently verified against an original source.',
        'You are the Group Company Secretary at Zava Group Berhad. Research the disclosure, governance, and investor communication expectations that listed Malaysian and Indonesian conglomerates typically face after a material earnings miss and emergency Board review. Focus on Bursa Malaysia, OJK, IDX, and comparable listed-company guidance from 2022 to 2025, then distinguish mandatory obligations from market practice. Present as a table with columns for Requirement, Malaysia, Indonesia, Timing, and Practical Implication for Management.',
        'You are the Group CEO at Zava Group Berhad. Research turnaround actions used by ASEAN conglomerates when multiple divisions move into negative EBITDA at the same time, especially cost reset programmes, capital allocation changes, portfolio exits, and leadership interventions. Find examples published between 2022 and 2025 and note what happened in the first 100 days after the trigger event. Present as a RAG table with Red for actions usually required within 30 days, Amber for 31 to 90 days, and Green for longer-horizon actions, with citations for every case.'
      ], DESC_RESEARCHER),
      tool(T_ANALYST, M365_LIC, M365_ACCT, [
        'You are the Group CFO of Zava Group Berhad preparing for tomorrow\'s emergency Board review. Upload 01_Zava_Group_Financial_Performance.xlsx to Analyst. Using the Group P&L Summary tab, calculate the absolute and percentage revenue and EBITDA variance against FY2025 budget for each of the 11 divisions, identify the 3 divisions with the largest unfavourable EBITDA variance in MYR millions, and quantify the group-level gap behind the 18% miss. Flag divisions where EBITDA variance is worse than -20% as Red, -10% to -20% as Amber, and above -10% as Green. Present as a RAG summary table with one recommended corrective action per Red-status division.',
        'You are the Head of FP&A at Zava Group Berhad. Upload 01_Zava_Group_Financial_Performance.xlsx to Analyst. Using the Division Revenue Bridge tab and the Quarterly Earnings Tracker tab, identify which revenue and margin drivers explain why 3 divisions have fallen into negative EBITDA and whether the deterioration accelerated in Q4. Quantify the contribution of volume, pricing, mix, and cost movements where visible in the data, then show which divisions are stabilising versus worsening. Present as a structured RAG table with columns for Division, Main Driver, Q4 Change, Negative EBITDA Risk, and Recommended Action.',
        'You are the Group Treasurer at Zava Group Berhad. Upload 01_Zava_Group_Financial_Performance.xlsx to Analyst. Using the Balance Sheet Summary tab and the Key Financial Ratios tab, assess whether the FY2025 18% EBITDA miss creates pressure on leverage, interest cover, liquidity, or covenant headroom at group level, and identify which 3 metrics the Board should monitor weekly over the next 8 weeks. Flag metrics with immediate escalation risk as Red, heightened watchlist risk as Amber, and stable metrics as Green. Present as a RAG dashboard table with a short note on the likely implication for lenders and regulators.'
      ], DESC_ANALYST),
      tool(T_EXCEL, M365_LIC, M365_ACCT, [
        'Using the Group P&L Summary tab in this workbook, build a variance analysis dashboard on a new sheet called "Board Variance Dashboard". For each of the 11 divisions, calculate absolute revenue variance versus FY2025 budget in MYR M, percentage EBITDA variance, and year-on-year EBITDA margin change, then add a group-level summary row at the top. Apply conditional formatting so EBITDA variance worse than -20% is red, -10% to -20% is amber, and above -10% is green. The CFO is presenting this to the Board in 2 hours.',
        'Using the Division Revenue Bridge tab in this workbook, create a new sheet called "Recovery Bridge" that shows for each division the movement from FY2025 budget EBITDA to actual EBITDA using the major bridge drivers available in the data. Sort the divisions from worst to best by EBITDA gap, highlight the 3 divisions already in negative EBITDA, and add a short text box beside each Red division summarising the likely driver in one sentence. Present the result so it can be pasted directly into a Board pack.',
        'Using the Quarterly Earnings Tracker tab and the Key Financial Ratios tab in this workbook, create an early-warning tracker on a new sheet called "8-Week Watchlist". Show quarterly EBITDA trend, revenue trend, net debt to EBITDA, and interest cover for the group, then calculate whether each trend is improving, flat, or deteriorating. Flag metrics deteriorating for 2 or more consecutive periods as Red, 1 period as Amber, and stable or improving as Green. Present as a compact RAG table with sparklines that the CEO can review weekly.'
      ]),
      tool(T_WORD, M365_LIC, M365_ACCT, [
        'You are the Group Company Secretary at Zava Group Berhad. Using 02_Zava_Group_Policy_Handbook.docx, draft a 2-page Board paper for the emergency review covering governance obligations, escalation triggers, disclosure controls, and management accountabilities after an 18% EBITDA miss. Include sections for Immediate Facts, Governance Obligations, Decisions Required, and Next 30-Day Actions. Present in formal Board paper style with a short RAG summary at the top.',
        'You are the Group Strategy Director at Zava Group Berhad. Using 03_Zava_Group_Strategy_Framework.docx, draft a 2-page CEO briefing that explains which strategic priorities remain valid despite the FY2025 EBITDA miss and which priorities should be paused, reset, or accelerated across the 11 divisions. Specifically address the 3 divisions now in negative EBITDA and the implications for capital allocation over the next 2 quarters. Present as a Board-ready paper with a RAG table for Continue, Reset, and Pause decisions.',
        'You are the Head of Corporate Affairs at Zava Group Berhad. Using 02_Zava_Group_Policy_Handbook.docx and the tone of 03_Zava_Group_Strategy_Framework.docx, draft a stakeholder communication annex for the Board pack covering regulators, lenders, employees, and investors. For each audience, state the core message, approval owner, timing window, and the main risk if the wording is wrong. Present as a structured table followed by a 200-word holding statement the CEO can adapt quickly.'
      ]),
      tool(T_PPT, M365_LIC, M365_ACCT, [
        'You are the Group Chief of Staff at Zava Group Berhad. Create a 5-slide emergency Board deck on the FY2025 EBITDA miss using 01_Zava_Group_Financial_Performance.xlsx and 03_Zava_Group_Strategy_Framework.docx as the source context. Cover: group performance versus budget, the 3 negative-EBITDA divisions, the likely root causes, immediate management actions, and the decisions required in the next 48 hours. Use a serious executive design and present the output as a 5-slide deck with one headline message per slide.',
        'You are the Group CFO at Zava Group Berhad. Create a 5-slide briefing deck for the CEO to use in lender and regulator conversations after the Board review. Show the 18% EBITDA miss, balance sheet resilience, corrective actions, and the expected timeline for recovery across the 11 divisions. Flag the most material risk on each slide as Red, Amber, or Green and include speaker notes that keep the tone factual and controlled.',
        'You are the Head of Investor Relations at Zava Group Berhad. Build a 5-slide analyst call deck that explains the FY2025 variance without sounding defensive, focusing on what happened, what management is changing, and what investors should monitor next quarter. Include one slide that separates structural issues from one-off issues and one slide that summarises the 3 negative-EBITDA divisions. Format as a 5-slide deck with concise headlines, minimal text, and a closing slide titled "Management Commitments for the Next 90 Days".'
      ]),
      tool(T_OUTLOOK, M365_LIC, M365_ACCT, [
        'You are the Group Company Secretary at Zava Group Berhad. Draft the Board emergency meeting email for a session taking place in 48 hours on the FY2025 EBITDA miss. The email should explain the purpose, list the 3 agenda items, mention that 3 divisions are in negative EBITDA, and instruct directors to review the briefing pack before the meeting. Keep it under 180 words and professional, urgent, and discreet.',
        'You are the Group CFO at Zava Group Berhad. Draft an email to the lead relationship banks explaining that FY2025 EBITDA missed budget by 18% but that management is already preparing an emergency Board review and liquidity actions. Reassure lenders that balance sheet monitoring is active, note that a fuller update will follow after the Board meeting, and avoid making promises not yet approved. Present as a polished external email with a strong subject line.',
        'You are the Head of Corporate Affairs at Zava Group Berhad. Draft an internal email to all division CEOs immediately after the emergency Board review summarising the key decisions, the expectations for Red-status divisions, and the rules for external communications until approved messaging is issued. Keep the tone firm and aligned, and end with 3 bullet points titled "What you must do today".'
      ]),
      tool(T_TEAMS, M365_LIC, M365_ACCT, [
        'You are the Group Chief of Staff at Zava Group Berhad. Using this recorded Teams meeting recap from the executive committee, identify the decisions, unresolved issues, and action items related to the FY2025 EBITDA miss and the 3 divisions in negative EBITDA. Note who owns each item and whether it must be resolved before the Board emergency review in 48 hours. Present as a RAG table with Red for must-close before the Board, Amber for can close this week, and Green for monitor only.',
        'You are the Group CFO at Zava Group Berhad. Using this Teams meeting recap, extract every statement relevant to variance drivers, liquidity, covenant pressure, or regulatory communication readiness. Summarise the discussion in 4 sections: Key Facts, Risks Raised, Decisions Taken, and Follow-Up Actions with owners and due dates. End with a one-paragraph executive summary the CEO can paste into the Board pack.',
        'You are the Head of Investor Relations at Zava Group Berhad. Using this Teams meeting recap, identify which discussion points would worry investors most if they leaked before the Board review and which points demonstrate that management has control of the situation. Flag high-leak-risk items as Red, sensitive-but-manageable items as Amber, and safe factual items as Green. Present as a RAG table with suggested holding lines for each Red item.'
      ], DESC_TEAMS),
      tool(T_NOTEBOOK, M365_LIC, M365_ACCT, [
        'You are the Group CEO at Zava Group Berhad. Upload 01_Zava_Group_Financial_Performance.xlsx, 02_Zava_Group_Policy_Handbook.docx, and 03_Zava_Group_Strategy_Framework.docx to Copilot Notebook. Set the instruction: "You are my executive war-room analyst. Synthesize across all files, cite the source file for every major point, and focus on actions needed in the next 48 hours." Then ask for the 10-slide-equivalent story the Board needs, including the 18% EBITDA miss, the 3 negative-EBITDA divisions, the main governance obligations, and the top 5 decisions management must bring forward.',
        'You are the Group CFO at Zava Group Berhad. Upload 01_Zava_Group_Financial_Performance.xlsx and 03_Zava_Group_Strategy_Framework.docx to Copilot Notebook. Ask which strategic priorities appear underfunded or mis-sequenced given the FY2025 results, and which priorities should be accelerated, deferred, or stopped across the 11 divisions. Require Notebook to cite the exact source document for every recommendation and to present the answer as a RAG table with financial rationale.',
        'You are the Group Company Secretary at Zava Group Berhad. Upload 01_Zava_Group_Financial_Performance.xlsx, 02_Zava_Group_Policy_Handbook.docx, and 03_Zava_Group_Strategy_Framework.docx to Copilot Notebook. Ask Notebook to identify where the strategy narrative, the financial reality, and the policy obligations are misaligned ahead of the emergency Board review. Request a concise answer with 3 sections: Contradictions to Resolve, Questions Directors Will Ask, and Recommended Pre-Reads, all with citations to the source files.'
      ], DESC_NOTEBOOK),
      tool(T_COWORK, FRONTIER_LIC, M365_ACCT, [
        'You are the Group Chief of Staff at Zava Group Berhad. Do all of the following autonomously: research comparable Malaysian and Indonesian conglomerate responses to EBITDA misses above 15%, draft a 2-page Word document titled "Emergency Board Review Brief", save it to OneDrive, email it to the Group CEO and CFO for review, and schedule a 30-minute Teams prep meeting for tomorrow morning. Keep the brief focused on Board actions, disclosure risk, and the first 30 days of recovery.',
        'You are the Group Company Secretary at Zava Group Berhad. Do all of the following autonomously: create the emergency Board review meeting invite for 48 hours from now, attach a placeholder agenda, set a reminder 12 hours before the meeting, create a OneDrive folder called "Board Emergency Review - FY2025 EBITDA", and email all directors asking them to expect the final pack within 24 hours. Keep the wording discreet and clearly marked confidential.',
        'You are the Group CFO at Zava Group Berhad. Do all of the following autonomously: draft a lender update email, draft a regulator holding note, create a task list for the finance leadership team covering variance analysis, liquidity review, and divisional recovery plans, then send the task list to the relevant owners and schedule a 20-minute checkpoint meeting for this afternoon. The context is an 18% FY2025 EBITDA miss with 3 divisions in negative EBITDA and an emergency Board review in 48 hours.'
      ], DESC_COWORK),
      tool(T_EDIT_COPILOT, M365_LIC, M365_ACCT, [
        'You are the Group Company Secretary at Zava Group Berhad. Using 02_Zava_Group_Policy_Handbook.docx in Word for the web, add an appendix titled "Emergency Earnings Review Governance Protocol" and populate it with a decision-rights table, escalation timeline, and approval matrix for regulator, lender, investor, and employee communications. Keep the language consistent with the existing handbook and add a short note wherever legal review is required before external release.',
        'Using the Group P&L Summary tab and the Key Financial Ratios tab in 01_Zava_Group_Financial_Performance.xlsx, create a new worksheet called "Board Recovery Tracker" that combines divisional EBITDA variance, RAG status, leverage metrics, and an owner column for each corrective action. Reorder the columns so Board readers see the Red issues first, apply consistent styling, and add formulas that automatically refresh the group summary at the top when divisional values change.',
        'You are the Group Chief of Staff at Zava Group Berhad. Using the current Board presentation in PowerPoint for the web, restructure the deck so the first 5 slides tell a tighter crisis narrative on the FY2025 EBITDA miss. Consolidate duplicative slides, rewrite slide titles into action-oriented headlines, move detailed backup charts to an appendix, and add a final decisions slide that clearly separates approve today, review next week, and monitor monthly.'
      ], DESC_EDIT_COPILOT),
      tool(T_WORD_AGT, M365_LIC, M365_ACCT, [
        'You are the Group Company Secretary at Zava Group Berhad. Open 02_Zava_Group_Policy_Handbook.docx in Word for Web and create a new agent called "Zava Governance Guide". Describe it as an assistant that answers questions on governance obligations, escalation rules, disclosure controls, and approval authorities during performance or crisis situations. Set the document as the knowledge source and share it with the CEO office, finance, and corporate affairs teams.',
        'You are the Head of Corporate Affairs at Zava Group Berhad. Demo the Zava Governance Guide agent by asking: "An 18% EBITDA miss has triggered an emergency Board review. What approvals do I need before sending a regulator update, a lender email, and an employee note, and who owns each approval?" Show how the agent responds with policy-grounded guidance that cites the source document.'
      ], DESC_WORD_AGT),
      tool(T_PPT_AGT, M365_LIC, M365_ACCT, [
        'You are the Group Chief of Staff at Zava Group Berhad. Build the emergency Board review deck in PowerPoint for Web, then create a new agent called "Board Pack Navigator". Describe it as an assistant that helps directors and executives find the right slide, chart, or message on group performance, divisional issues, and next-step decisions. Share it with the Board office and senior leadership team only.',
        'You are the Group CFO at Zava Group Berhad. Demo the Board Pack Navigator agent by asking: "Which 3 divisions are in negative EBITDA, what is the size of each gap versus budget, and which slide should I open if a director asks about leverage impact?" Then ask it to summarise the 3 most important decisions on the final slide in under 80 words.'
      ], DESC_PPT_AGT),
      tool(T_XL_AGT, M365_LIC, M365_ACCT, [
        'You are the Group CFO at Zava Group Berhad. Open 01_Zava_Group_Financial_Performance.xlsx in Excel for Web and create a new agent called "Zava Performance Q&A". Describe it as an assistant that answers questions on the Group P&L Summary, Division Revenue Bridge, Balance Sheet Summary, Quarterly Earnings Tracker, and Key Financial Ratios tabs for the emergency Board review. Share it with the Group CEO, finance leadership team, and strategy office.',
        'You are the Group CEO at Zava Group Berhad. Demo the Zava Performance Q&A agent by asking: "Which 3 divisions have the largest unfavourable EBITDA variance in FY2025, what is the group-level miss versus budget, and has liquidity or leverage materially worsened?" Then ask it to classify each answer as Red, Amber, or Green so the CEO gets an instant decision-oriented summary.'
      ], DESC_XL_AGT),
      tool(T_BUILDER, M365_LIC, M365_ACCT, [
        'You are the Group Chief of Staff at Zava Group Berhad. Go to copilotstudio.microsoft.com and create a new agent called "Zava Executive War Room". Describe it as an assistant for Board, CEO, CFO, and corporate affairs teams managing the FY2025 EBITDA miss, and upload 01_Zava_Group_Financial_Performance.xlsx, 02_Zava_Group_Policy_Handbook.docx, and 03_Zava_Group_Strategy_Framework.docx as knowledge sources. Add starter topics for Board Review, Divisional Recovery, Stakeholder Communications, and Governance Approvals, then publish it to Teams for authorised executives only.',
        'You are the Group CEO at Zava Group Berhad. Demo the published Zava Executive War Room agent in Teams by asking: "Give me the 60-second version of the FY2025 EBITDA problem, the 3 divisions in negative EBITDA, the top governance obligations, and the decisions I must take to the Board in 48 hours." Then ask a second question: "Draft my first message to division CEOs after the Board meeting."'
      ], DESC_BUILDER),
    ],
    'PT Wahana Makmur Nusantara Tbk',
    'EBITDA FY2025 meleset 18% — review darurat direksi dalam 48 jam.'),

# ── COMMERCIAL BANKING ─────────────────────────────────────────────────────
ind('commercial-banking','banking-fs','Commercial Banking','🏦','#0D47A1','#1976D2',
    'Perdana Commerce Bank Berhad',
    'Gross impaired loans at 6.8% and provision coverage at 71% ahead of a BNM bilateral review.',
    'Perdana Commerce Bank Berhad is a mid-tier Malaysian commercial bank with about 7,200 employees, 138 branches, and MYR 74.6B in gross loans across Corporate Banking, SME, Consumer, Treasury, and Special Assets divisions. Over the last four quarters, gross impaired loans have climbed from 4.1% to 6.8%, driven by stress in construction-linked SMEs, used-car financing, and several leveraged transport accounts, while Stage 2 balances have expanded to MYR 8.9B. Provision coverage is now 71% against an internal floor of 80%, CET1 has narrowed to 13.1%, and 19 borrower facilities on the Covenant Monitor are already in waiver or breach discussions. The Credit Rating Watch tab shows 27 obligors downgraded in the last 90 days, including 6 names that contribute more than MYR 420M of exposure. BNM has scheduled a bilateral asset-quality review in five days and wants a defensible narrative on underwriting discipline, restructuring activity, and management overlays. At the same time, the Investor Relations and Finance teams are preparing Bursa-sensitive messaging because wholesale funding counterparties have started asking whether the bank\'s FY2026 guidance still assumes normalised credit costs.',
    ['BNK_01_Group_Loan_Portfolio.xlsx', 'BNK_02_Regulatory_Reporting_Pack.docx', 'BNK_03_Credit_Risk_Policy.docx'],
    [
      tool(T_CHAT, FREE_LIC, FREE_ACCT, [
        'You are the Group CFO at Perdana Commerce Bank Berhad. Using BNK_01_Group_Loan_Portfolio.xlsx as context, analyse why gross impaired loans moved from 4.1% to 6.8%, which 3 segments in the Loan Book Summary and NPL Tracker tabs are driving the increase, and how much of the pressure comes from SME construction, transport, and unsecured retail. Distinguish deterioration caused by origination quality from deterioration caused by recovery lag so the Board can see what is structural versus fixable within 90 days. Flag segments with immediate capital or provisioning pressure as Red, heightened but manageable pressure as Amber, and stable segments as Green. Present as a RAG table.',
        'You are the Chief Risk Officer at Perdana Commerce Bank Berhad. Using the Covenant Monitor and Credit Rating Watch tabs in BNK_01_Group_Loan_Portfolio.xlsx together with BNK_03_Credit_Risk_Policy.docx, assess whether current stress is concentrated in a few large obligors or is broad-based across the loan book. Identify which covenant breaches appear most likely to migrate into Stage 3 within the next 2 quarters and which policy limits are closest to being breached. Flag immediate escalation items as Red, close-watch items as Amber, and contained items as Green. Present as a RAG table.',
        'You are the Head of Investor Relations at Perdana Commerce Bank Berhad. Using BNK_02_Regulatory_Reporting_Pack.docx and the Loan Book Summary tab in BNK_01_Group_Loan_Portfolio.xlsx, assess which asset-quality metrics would attract the most scrutiny from BNM, Bursa Malaysia analysts, and wholesale funding counterparties if disclosed today. Separate items that can be explained as cyclical portfolio stress from items that imply governance or underwriting weakness, and note where wording discipline matters most. Flag disclosure items requiring immediate Board alignment as Red, items needing supporting context as Amber, and low-sensitivity items as Green. Present as a RAG table.',
      ]),
      tool(T_RESEARCHER, FREE_LIC, FREE_ACCT, [
        'You are the Head of Credit Risk Strategy at Perdana Commerce Bank Berhad. Research published 2023 to 2025 data on gross impaired loan ratios, Stage 2 trends, and provision coverage for Malaysian and Indonesian commercial banks with meaningful SME books, and compare them with the stress indicators implied by the Loan Book Summary and NPL Tracker tabs in BNK_01_Group_Loan_Portfolio.xlsx. Separate findings that are regulatory benchmarks from peer practice, and note any BNM, OJK, Bank Indonesia, or IDX commentary that investors would view as a warning sign. Flag peer positions materially worse than market norms as Red, elevated but recoverable as Amber, and resilient as Green. Present as a RAG table. Flag any claim that could not be independently verified.',
        'You are the Head of Special Assets at Perdana Commerce Bank Berhad. Research 2022 to 2025 case studies of ASEAN commercial banks that reduced impaired-loan ratios after a sharp rise in SME or retail stress, focusing on workout sequencing, collections redesign, restructuring discipline, and management overlays. Compare those cases with the problem themes visible in the Segment Performance and Covenant Monitor tabs of BNK_01_Group_Loan_Portfolio.xlsx, and distinguish actions that showed results within 2 quarters from actions that took longer than a year. Flag approaches with immediate relevance to our portfolio as Red, useful medium-term plays as Amber, and low-transferability cases as Green. Present as a RAG table. Flag any claim that could not be independently verified.',
        'You are the Group Company Secretary at Perdana Commerce Bank Berhad. Research the latest 2024 to 2025 supervisory expectations from BNM, OJK, Bank Indonesia, and public-market disclosure guidance relevant to deteriorating commercial-bank asset quality, especially around provisioning adequacy, covenant monitoring, and communication with investors when stress is visible in loan portfolios. Use the issues surfaced in BNK_02_Regulatory_Reporting_Pack.docx and the Credit Rating Watch tab in BNK_01_Group_Loan_Portfolio.xlsx as the practical lens for what management needs to disclose or defend. Distinguish mandatory expectations from market practice and note where Malaysia and Indonesia differ most. Flag requirements that demand immediate management attention as Red, items that can be addressed in the next reporting cycle as Amber, and monitor-only items as Green. Present as a RAG table. Flag any claim that could not be independently verified.',
      ], DESC_RESEARCHER),
      tool(T_ANALYST, M365_LIC, M365_ACCT, [
        'You are the Group Chief Credit Officer at Perdana Commerce Bank Berhad. Upload BNK_01_Group_Loan_Portfolio.xlsx to Analyst and use the Loan Book Summary and NPL Tracker tabs to quantify which business lines have contributed most to the move from 4.1% to 6.8% gross impaired loans. Calculate the provision top-up needed to bring each major business line to 80% coverage, estimate the pre-tax profit impact, and show what share of total stressed balances comes from the top 5 segments. Flag segments requiring immediate balance-sheet action as Red, segments needing tighter watchlist management as Amber, and segments that remain stable as Green. Present as a RAG table.',
        'You are the Head of Portfolio Management at Perdana Commerce Bank Berhad. Upload BNK_01_Group_Loan_Portfolio.xlsx to Analyst and use the Segment Performance, Covenant Monitor, and Credit Rating Watch tabs to identify the obligor, sector, and region combinations most likely to worsen over the next 2 quarters. Compare downgrade momentum with covenant waiver frequency, highlight where warning signals are converging, and estimate how much exposure sits behind those clusters in MYR millions. Flag clusters with likely Stage 3 migration as Red, clusters needing intensified monitoring as Amber, and clusters showing stabilisation as Green. Present as a RAG table.',
        'You are the Group Treasurer at Perdana Commerce Bank Berhad. Upload BNK_01_Group_Loan_Portfolio.xlsx to Analyst and use the Loan Book Summary, NPL Tracker, and Covenant Monitor tabs to assess what happens to provision coverage, CET1, and earnings if management pursues cure, restructure, or write-off paths over the next 90 days. Show which path best protects capital without understating credit stress, and identify where management overlays look most justified based on the available data. Flag scenarios with material capital pressure as Red, scenarios that are manageable with active intervention as Amber, and scenarios that preserve headroom as Green. Present as a RAG table.',
      ], DESC_ANALYST),
      tool(T_EXCEL, M365_LIC, M365_ACCT, [
        'Using the Loan Book Summary tab in this workbook, create a new sheet called "BNM Bilateral Dashboard" that summarises portfolio size, gross impaired loans, Stage 2 exposure, and provision coverage by business line. Pull deterioration trends from the NPL Tracker tab, show the 5 segments with the largest MYR increase in impaired balances over the last 4 quarters, and add a short management-comment column that distinguishes cyclical stress from underwriting or collections issues. Flag business lines needing immediate intervention as Red, watchlist lines as Amber, and stable lines as Green. Present as a RAG table.',
        'Using the Covenant Monitor tab in this workbook, create a new sheet called "Waiver Pressure Map" that groups covenant breaches by sector, facility type, and relationship manager, then cross-reference downgrade signals from the Credit Rating Watch tab. Analyse which breached facilities are most likely to become Stage 3 within the next 180 days, quantify total exposure at risk, and add a column showing whether each case breaches internal policy tolerance in BNK_03_Credit_Risk_Policy.docx. Flag immediate remediation cases as Red, tight-watch cases as Amber, and contained cases as Green. Present as a RAG table.',
        'Using the Segment Performance tab in this workbook, create a new sheet called "Collections Focus List" that ranks sectors and products by deterioration in arrears, recoveries, and restructuring outcomes, then bring in matching impaired-balance trends from the NPL Tracker tab. Analyse whether the bank is losing control through new inflows, weak cures, or slow recoveries, and add a recommended-owner column for Collections, Business, or Special Assets. Flag segments needing immediate recovery sprints as Red, segments needing management review as Amber, and segments showing improving momentum as Green. Present as a RAG table.',
      ]),
      tool(T_WORD, M365_LIC, M365_ACCT, [
        'You are the Group Company Secretary at Perdana Commerce Bank Berhad. Using BNK_02_Regulatory_Reporting_Pack.docx, BNK_03_Credit_Risk_Policy.docx, and the Loan Book Summary tab in BNK_01_Group_Loan_Portfolio.xlsx, draft a Board Risk Committee paper that explains the asset-quality deterioration, the current provision coverage gap, and the governance decisions management needs before the BNM bilateral review. Separate analysis of business-line stress from analysis of policy adherence so directors can see what is commercial pressure versus control weakness. Flag items requiring same-week Board direction as Red, items for management follow-up as Amber, and information-only items as Green. Present as a RAG table.',
        'You are the Head of Regulatory Affairs at Perdana Commerce Bank Berhad. Using BNK_02_Regulatory_Reporting_Pack.docx and the Covenant Monitor and Credit Rating Watch tabs in BNK_01_Group_Loan_Portfolio.xlsx, draft a bilateral-review briefing note that anticipates the questions BNM is likely to ask on impaired loans, covenant management, and management overlays. Distinguish where the bank has credible evidence of stabilisation from where the narrative is still too thin and needs more support. Flag discussion points that are high-risk if poorly answered as Red, points needing tighter evidence as Amber, and points that are already well-supported as Green. Present as a RAG table.',
        'You are the Head of Credit Governance at Perdana Commerce Bank Berhad. Using BNK_03_Credit_Risk_Policy.docx and the Segment Performance and NPL Tracker tabs in BNK_01_Group_Loan_Portfolio.xlsx, prepare a policy gap analysis showing where current portfolio behaviour appears misaligned with stated underwriting, watchlist, and restructuring standards. Highlight whether the apparent gaps are concentrated in a few products or show a broader discipline problem across the bank. Flag policy areas requiring immediate remediation as Red, areas needing calibration or clarification as Amber, and policy areas still operating effectively as Green. Present as a RAG table.',
      ]),
      tool(T_PPT, M365_LIC, M365_ACCT, [
        'You are the Group Chief of Staff at Perdana Commerce Bank Berhad. Create a 6-slide Board Risk Committee deck using BNK_01_Group_Loan_Portfolio.xlsx, BNK_02_Regulatory_Reporting_Pack.docx, and BNK_03_Credit_Risk_Policy.docx as source context. Cover the Loan Book Summary and NPL Tracker trends, the largest Covenant Monitor hotspots, the policy and governance questions directors must address, and the management actions planned before the BNM bilateral review. Flag the main message on each slide as Red, Amber, or Green so directors can see urgency at a glance. Present as a RAG table.',
        'You are the Group CFO at Perdana Commerce Bank Berhad. Build a 5-slide regulator briefing deck that uses the Loan Book Summary, Credit Rating Watch, and Covenant Monitor tabs in BNK_01_Group_Loan_Portfolio.xlsx to explain what has deteriorated, what management has already done, and where the remaining uncertainty sits. Use BNK_02_Regulatory_Reporting_Pack.docx to keep the tone factual and supervisory-ready, and make sure one slide isolates provision coverage and capital resilience. Flag high-concern messages as Red, messages needing explanatory support as Amber, and stabilising indicators as Green. Present as a RAG table.',
        'You are the Head of Treasury Funding at Perdana Commerce Bank Berhad. Create a 5-slide funding-counterparty deck using BNK_02_Regulatory_Reporting_Pack.docx and the Loan Book Summary and Segment Performance tabs in BNK_01_Group_Loan_Portfolio.xlsx to explain asset-quality stress without sounding defensive. Show what counterparties should monitor over the next 2 quarters, where management sees recoverability, and which indicators still require caution. Flag messages that demand immediate relationship-manager handling as Red, messages that need careful narrative framing as Amber, and messages that can be communicated confidently as Green. Present as a RAG table.',
      ]),
      tool(T_OUTLOOK, M365_LIC, M365_ACCT, [
        'You are the Group CFO at Perdana Commerce Bank Berhad. Using BNK_02_Regulatory_Reporting_Pack.docx and the Loan Book Summary and NPL Tracker tabs in BNK_01_Group_Loan_Portfolio.xlsx, analyse which issues must appear in the first email to the BNM supervision team, which belong in attachments, and which should remain internal until the bilateral review. Then draft the email in a calm regulatory tone that acknowledges deterioration, points to the current management response, and avoids over-promising before Board review. Flag must-state items as Red, supporting items as Amber, and internal-only items as Green. Present as a RAG table.',
        'You are the Chief Risk Officer at Perdana Commerce Bank Berhad. Using the Covenant Monitor and Credit Rating Watch tabs in BNK_01_Group_Loan_Portfolio.xlsx together with BNK_03_Credit_Risk_Policy.docx, analyse which commitments you need from business heads before the BNM meeting and draft an email that requests status updates on waivers, restructures, and deteriorating names. Make the email strong enough to drive action but precise enough that recipients can separate urgent cases from watchlist cases. Flag immediate response requests as Red, this-week follow-ups as Amber, and information-only reminders as Green. Present as a RAG table.',
        'You are the Head of Corporate Communications at Perdana Commerce Bank Berhad. Using BNK_02_Regulatory_Reporting_Pack.docx and the Segment Performance tab in BNK_01_Group_Loan_Portfolio.xlsx, assess what branch managers need to know about the loan-quality situation before customer or media questions start, then draft an internal note that keeps the message disciplined and non-alarmist. Separate what staff may say about restructuring support, what must be escalated to Risk, and what should never be improvised. Flag message points with reputational sensitivity as Red, points needing manager briefing as Amber, and safe factual points as Green. Present as a RAG table.',
      ]),
      tool(T_TEAMS, M365_LIC, M365_ACCT, [
        'You are the Group Chief of Staff at Perdana Commerce Bank Berhad. Using this recorded Teams meeting recap from the credit or risk committee, identify every discussion point linked to the Loan Book Summary, NPL Tracker, or Covenant Monitor issues in BNK_01_Group_Loan_Portfolio.xlsx. Separate decisions already taken from unresolved issues, note who owns each follow-up, and highlight anything that must be closed before the BNM bilateral review. Flag must-close items as Red, this-week actions as Amber, and monitor-only items as Green. Present as a RAG table.',
        'You are the Group CFO at Perdana Commerce Bank Berhad. Using this recorded Teams meeting recap and the stress themes visible in the Credit Rating Watch and Segment Performance tabs of BNK_01_Group_Loan_Portfolio.xlsx, identify statements about targets, recoveries, or provisioning that could later be interpreted as management commitments. Quote the relevant speaker, explain why the wording matters, and distinguish between realistic commitments and aspirational comments. Flag statements that should be reviewed by Legal or Regulatory Affairs as Red, statements needing clarification as Amber, and statements safe to reuse as Green. Present as a RAG table.',
        'You are the Head of Regulatory Affairs at Perdana Commerce Bank Berhad. Using this Teams meeting recap together with BNK_03_Credit_Risk_Policy.docx and the Covenant Monitor tab in BNK_01_Group_Loan_Portfolio.xlsx, assess whether the meeting reflects policy-consistent decision making on waivers, restructures, and watchlist escalation. Highlight where management debate suggests control uncertainty or inconsistency between business and risk teams. Flag control concerns requiring immediate escalation as Red, issues needing documented follow-up as Amber, and policy-consistent discussion points as Green. Present as a RAG table.',
      ], DESC_TEAMS),
      tool(T_NOTEBOOK, M365_LIC, M365_ACCT, [
        'You are the Group CEO at Perdana Commerce Bank Berhad. In Copilot Notebook, use BNK_01_Group_Loan_Portfolio.xlsx, BNK_02_Regulatory_Reporting_Pack.docx, and BNK_03_Credit_Risk_Policy.docx, and tell Notebook to synthesise across the Loan Book Summary, NPL Tracker, Covenant Monitor, and Credit Rating Watch tabs with citations to the source file for every major point. Ask for the 10 issues most likely to come up in the BNM bilateral review, the evidence management has for each answer, and the gaps that still need closing. Flag issues that could materially weaken management credibility as Red, issues that need tighter support as Amber, and issues already defensible as Green. Present as a RAG table.',
        'You are the Head of Portfolio Strategy at Perdana Commerce Bank Berhad. In Copilot Notebook, use BNK_01_Group_Loan_Portfolio.xlsx and BNK_03_Credit_Risk_Policy.docx, and ask Notebook to compare what the Segment Performance and Covenant Monitor tabs imply about real portfolio behaviour with what the policy says should happen on watchlist migration, waiver approvals, and restructuring discipline. Require direct citations to the workbook tabs and policy sections for every conclusion. Flag contradictions that need immediate executive attention as Red, tensions that need clarification as Amber, and areas where practice matches policy as Green. Present as a RAG table.',
        'You are the Head of Finance at Perdana Commerce Bank Berhad. In Copilot Notebook, use BNK_01_Group_Loan_Portfolio.xlsx and BNK_02_Regulatory_Reporting_Pack.docx, and ask Notebook to connect the Loan Book Summary and NPL Tracker trends with the external narrative management has prepared for regulators, investors, and wholesale funders. Ask where the narrative is strongest, where it sounds incomplete, and which numbers will draw the hardest questions if counterparties compare quarters. Flag narrative gaps that are highest risk in live conversations as Red, gaps that need supporting detail as Amber, and areas already coherent as Green. Present as a RAG table.',
      ], DESC_NOTEBOOK),
      tool(T_COWORK, M365_LIC, M365_ACCT, [
        'You are the Group Chief of Staff at Perdana Commerce Bank Berhad. Research the latest BNM and regional supervisory commentary relevant to the issues visible in the Loan Book Summary and Covenant Monitor tabs of BNK_01_Group_Loan_Portfolio.xlsx, draft a 2-page OneDrive brief titled "BNM Bilateral Readiness - Commercial Banking", email it to the CEO, CFO, CRO, and Head of Regulatory Affairs, and schedule a 30-minute prep meeting for tomorrow morning. Ask Cowork to place a one-page summary at the front of the brief that flags immediate review items as Red, this-week follow-ups as Amber, and stable areas as Green. Present as a RAG table.',
        'You are the Chief Risk Officer at Perdana Commerce Bank Berhad. Review outstanding tasks, recent emails, and calendar items linked to deteriorating names in the Credit Rating Watch and Segment Performance tabs of BNK_01_Group_Loan_Portfolio.xlsx, then send follow-ups to overdue owners, create a consolidated action list in Word, and post a short update in Teams for the risk leadership group. Ask Cowork to classify each action by urgency and owner readiness so management can see what must move before the BNM meeting. Flag immediate overdue actions as Red, actions still recoverable this week as Amber, and actions on track as Green. Present as a RAG table.',
      ], DESC_COWORK),
      tool(T_EDIT_COPILOT, M365_LIC, M365_ACCT, [
        'You are the Head of Regulatory Affairs at Perdana Commerce Bank Berhad. Using BNK_02_Regulatory_Reporting_Pack.docx in Word for the web, restructure the document so the opening section speaks directly to the deterioration seen in the Loan Book Summary and NPL Tracker tabs of BNK_01_Group_Loan_Portfolio.xlsx, then add a short appendix on covenant-waiver governance drawn from BNK_03_Credit_Risk_Policy.docx. Make the revised document easier for executives to navigate by grouping facts, supervisory questions, and management responses. Flag sections that need immediate senior review as Red, sections needing factual enhancement as Amber, and sections already fit for use as Green. Present as a RAG table.',
        'Using the Loan Book Summary, NPL Tracker, Covenant Monitor, and Credit Rating Watch tabs in BNK_01_Group_Loan_Portfolio.xlsx, create a new worksheet called "Executive Credit Heatmap" that consolidates impaired-loan trends, provision coverage, covenant status, and downgrade momentum into one view for the CEO and Board. Reorder the content so the highest-risk segments and obligors appear first, add concise commentary cells, and ensure the summary at the top updates when the underlying tabs change. Flag immediate intervention cases as Red, close-watch cases as Amber, and contained cases as Green. Present as a RAG table.',
      ], DESC_EDIT_COPILOT),
      tool(T_WORD_AGT, M365_LIC, M365_ACCT, [
        'You are the Head of Credit Governance at Perdana Commerce Bank Berhad. Open BNK_03_Credit_Risk_Policy.docx in Word for Web and create an agent called "Perdana Credit Policy Guide". Describe it as an assistant that answers questions on underwriting standards, covenant governance, watchlist escalation, and restructuring rules, using the same terminology reflected in the Covenant Monitor and Credit Rating Watch tabs of BNK_01_Group_Loan_Portfolio.xlsx. Share it with Risk, Special Assets, and selected business heads. Flag intended users with immediate need as Red, secondary users as Amber, and optional users as Green. Present as a RAG table.',
        'You are the Group CRO at Perdana Commerce Bank Berhad. Demo the Perdana Credit Policy Guide agent by asking how a leveraged SME account on the Covenant Monitor should move from waiver to restructuring under current policy, and then ask how downgrade triggers on the Credit Rating Watch tab should affect approval authority. Have the agent classify each answer by urgency for front-line users. Flag guidance requiring immediate frontline reinforcement as Red, guidance needing manager coaching as Amber, and guidance that is already well understood as Green. Present as a RAG table.',
      ], DESC_WORD_AGT),
      tool(T_PPT_AGT, M365_LIC, M365_ACCT, [
        'You are the Group Chief of Staff at Perdana Commerce Bank Berhad. Build the credit-risk briefing deck in PowerPoint for Web and create an agent called "BNM Bilateral Deck Navigator". Describe it as an assistant that answers questions on the Loan Book Summary, NPL Tracker, Covenant Monitor, and provisioning story so executives can find the right slide quickly during Board and regulator prep. Share it with the CEO office, Finance, Risk, and Regulatory Affairs teams. Flag user groups that need immediate access as Red, useful access as Amber, and optional access as Green. Present as a RAG table.',
        'You are the Group CFO at Perdana Commerce Bank Berhad. Demo the BNM Bilateral Deck Navigator agent by asking which 3 segments drove the increase shown on the NPL Tracker tab, what the current coverage gap versus the internal 80% floor is, and which slide best explains the largest Covenant Monitor hotspots. Then ask it to classify each answer so the speaker knows what to emphasise first. Flag messages that need front-page prominence as Red, backup discussion points as Amber, and appendix-only material as Green. Present as a RAG table.',
      ], DESC_PPT_AGT),
      tool(T_XL_AGT, M365_LIC, M365_ACCT, [
        'You are the Group CFO at Perdana Commerce Bank Berhad. Open BNK_01_Group_Loan_Portfolio.xlsx in Excel for Web and create an agent called "Perdana Loan Portfolio Q&A". Describe it as an assistant that answers questions from the Loan Book Summary, NPL Tracker, Segment Performance, Covenant Monitor, and Credit Rating Watch tabs for executive and regulator prep. Share it with Finance, Risk, Special Assets, and Treasury. Flag functions with immediate need for live workbook access as Red, functions with useful but secondary need as Amber, and optional functions as Green. Present as a RAG table.',
        'You are the Head of Special Assets at Perdana Commerce Bank Berhad. Demo the Perdana Loan Portfolio Q&A agent by asking which sector has the largest impaired-balance increase on the NPL Tracker tab, which obligors on the Covenant Monitor are closest to Stage 3 migration, and whether downgrade momentum on the Credit Rating Watch tab is accelerating or stabilising. Ask the agent to classify each answer by urgency. Flag immediate recovery priorities as Red, watchlist priorities as Amber, and stable exposures as Green. Present as a RAG table.',
      ], DESC_XL_AGT),
      tool(T_BUILDER, M365_LIC, M365_ACCT, [
        'You are the Group Chief of Staff at Perdana Commerce Bank Berhad. Go to Copilot Studio and create a new agent called "Perdana Credit Risk War Room" using BNK_01_Group_Loan_Portfolio.xlsx, BNK_02_Regulatory_Reporting_Pack.docx, and BNK_03_Credit_Risk_Policy.docx as knowledge sources. Give it starter topics for BNM Bilateral Review, Provision Coverage, Covenant Escalation, and Recovery Priorities, and make sure the workbook tabs most often referenced are Loan Book Summary, NPL Tracker, Covenant Monitor, and Credit Rating Watch. Publish it to Teams for senior executives and core control functions. Flag audiences needing immediate access as Red, follow-on audiences as Amber, and optional audiences as Green. Present as a RAG table.',
        'You are the Group CEO at Perdana Commerce Bank Berhad. Demo the published Perdana Credit Risk War Room agent by asking for the 60-second version of why gross impaired loans reached 6.8%, which items on the Covenant Monitor deserve the first call in tomorrow\'s prep session, and which policy questions from BNK_03_Credit_Risk_Policy.docx are still most exposed. Then ask the agent to classify each answer by urgency for the executive team. Flag immediate decision items as Red, near-term management items as Amber, and monitor-only items as Green. Present as a RAG table.',
      ], DESC_BUILDER)
    ],
    'PT Bank Sinar Niaga Sentosa Tbk',
    'Rasio kredit bermasalah 6,8% dan coverage 71% menjelang review OJK serta sorotan investor IDX.'),

# ── ISLAMIC BANKING ────────────────────────────────────────────────────────
ind('islamic-banking','banking-fs','Islamic Banking','🕌','#1A237E','#283593',
    'Amanah Tijarah Bank Berhad',
    'Stage 2 financing at 11.6% and GIA outflows threaten a MYR 2.4B sukuk plan before BNM review.',
    'Amanah Tijarah Bank Berhad is a Malaysian Islamic bank with about 4,600 employees, MYR 31.4B in financing assets, and core Retail, SME, Treasury, Shariah Governance, and Wealth divisions serving more than 1.1 million customers. Stage 2 financing has risen to 11.6% of the book, gross impaired financing has edged up to 2.7%, and MYR 1.1B of General Investment Account balances have rolled off in the last two quarters as customers chase higher returns elsewhere. The Murabahah Book and Tawarruq Tracker tabs show stress in cash-line and dealer-financing portfolios, while the GIA Performance tab shows payout pressure that has widened the profit-distribution gap to 42 basis points. The bank is simultaneously preparing a MYR 2.4B Sukuk Wakalah programme, but the Shariah Committee has highlighted weaknesses in tawarruq documentation, wakalah fee recognition, and exception approvals on 14 large accounts. BNM has requested an IFSA-focused supervisory meeting in four weeks covering Shariah governance, displaced commercial risk, and treatment of management overlays. Finance and Treasury need one consistent narrative on liquidity resilience, customer fairness, and remediation timing before questions intensify from institutional investors, auditors, and the Board Risk and Shariah Committees.',
    ['ISL_01_Financing_Portfolio.xlsx', 'ISL_02_Shariah_Governance_Report.docx', 'ISL_03_Islamic_Finance_Policy.docx'],
    [
      tool(T_CHAT, FREE_LIC, FREE_ACCT, [
        'You are the Group CFO at Amanah Tijarah Bank Berhad. Using ISL_01_Financing_Portfolio.xlsx as context, analyse why Stage 2 financing reached 11.6%, which exposures in the Murabahah Book, Tawarruq Tracker, and GIA Performance tabs are putting the most pressure on earnings and liquidity, and how much of the issue looks cyclical versus behavioural. Distinguish portfolio-quality stress from displaced commercial risk so the Board can see whether pricing, documentation, or customer runoff is the bigger problem. Flag issues requiring immediate management intervention as Red, issues that can be stabilised this quarter as Amber, and stable areas as Green. Present as a RAG table.',
        'You are the Head of Shariah Governance at Amanah Tijarah Bank Berhad. Using the Wakalah Summary and Tawarruq Tracker tabs in ISL_01_Financing_Portfolio.xlsx together with ISL_02_Shariah_Governance_Report.docx, assess whether current concerns are mostly documentation lapses, structuring weaknesses, or approval-discipline failures. Identify which gaps are most likely to attract BNM attention under IFSA and which ones could be remediated without changing the product economics. Flag high-severity Shariah concerns as Red, remedial but manageable concerns as Amber, and fully controlled areas as Green. Present as a RAG table.',
        'You are the Head of Treasury at Amanah Tijarah Bank Berhad. Using ISL_02_Shariah_Governance_Report.docx and the GIA Performance and Wakalah Summary tabs in ISL_01_Financing_Portfolio.xlsx, assess what message management should give on GIA runoff, profit-distribution pressure, and readiness for the MYR 2.4B Sukuk Wakalah programme. Separate issues that reflect genuine liquidity or conduct concern from issues that mainly require better explanation to investors and depositors. Flag messages needing immediate Board alignment as Red, messages needing supporting evidence as Amber, and messages already defensible as Green. Present as a RAG table.',
      ]),
      tool(T_RESEARCHER, FREE_LIC, FREE_ACCT, [
        'You are the Head of Islamic Risk Strategy at Amanah Tijarah Bank Berhad. Research published 2023 to 2025 data on Stage 2 financing trends, gross impaired financing, and displaced commercial risk for Malaysian and Indonesian Islamic banks, and compare those patterns with the Murabahah Book, Tawarruq Tracker, and GIA Performance signals in ISL_01_Financing_Portfolio.xlsx. Distinguish what BNM, OJK, Bank Indonesia, and IDX disclosures treat as supervisory concern from what peers describe as normal market volatility. Flag peer situations that suggest immediate management concern as Red, elevated but recoverable positions as Amber, and resilient positions as Green. Present as a RAG table. Flag any claim that could not be independently verified.',
        'You are the Head of Shariah Governance at Amanah Tijarah Bank Berhad. Research 2022 to 2025 public case studies and regulatory commentary on Islamic banks that faced tawarruq documentation weaknesses, wakalah governance issues, or deposit-rate pressure while preparing sukuk issuance. Compare those cases with the issues implied by ISL_02_Shariah_Governance_Report.docx and the Wakalah Summary and Tawarruq Tracker tabs in ISL_01_Financing_Portfolio.xlsx, and note which remediation actions produced quick supervisory comfort versus longer-term structural fixes. Flag actions with immediate relevance for our IFSA review as Red, useful medium-term lessons as Amber, and low-transferability examples as Green. Present as a RAG table. Flag any claim that could not be independently verified.',
        'You are the Group Company Secretary at Amanah Tijarah Bank Berhad. Research the latest 2024 to 2025 BNM, OJK, and Bank Indonesia expectations on Islamic-bank disclosures, Shariah governance, and liquidity messaging when profit-distribution pressure and financing-quality deterioration happen at the same time. Use the issues surfaced in ISL_02_Shariah_Governance_Report.docx and the GIA Performance tab in ISL_01_Financing_Portfolio.xlsx as the lens for what management may need to explain to boards, investors, and regulators. Distinguish mandatory expectations from market practice, and note where Malaysia and Indonesia differ in tone or timing. Flag requirements that need immediate management action as Red, items that fit the next reporting cycle as Amber, and monitor-only items as Green. Present as a RAG table. Flag any claim that could not be independently verified.',
      ], DESC_RESEARCHER),
      tool(T_ANALYST, M365_LIC, M365_ACCT, [
        'You are the Chief Risk Officer at Amanah Tijarah Bank Berhad. Upload ISL_01_Financing_Portfolio.xlsx to Analyst and use the Murabahah Book, Tawarruq Tracker, and Ijarah Portfolio tabs to quantify which contracts, sectors, and customer groups are driving the increase in Stage 2 financing. Estimate how much of total stress comes from the top 10 exposures, show the gross impaired financing trend, and highlight where documentation exceptions overlap with credit deterioration. Flag exposures requiring immediate remediation as Red, exposures needing tighter watchlist treatment as Amber, and exposures showing stabilisation as Green. Present as a RAG table.',
        'You are the Group Treasurer at Amanah Tijarah Bank Berhad. Upload ISL_01_Financing_Portfolio.xlsx to Analyst and use the GIA Performance and Wakalah Summary tabs to assess how further runoff, repricing pressure, or profit-equalisation support would affect liquidity, earnings, and sukuk readiness over the next 2 quarters. Show where displaced commercial risk is most acute, and identify whether management has enough buffer before the MYR 2.4B Sukuk Wakalah programme launches. Flag scenarios with immediate liquidity or earnings pressure as Red, manageable pressure as Amber, and resilient scenarios as Green. Present as a RAG table.',
        'You are the Head of Portfolio Remediation at Amanah Tijarah Bank Berhad. Upload ISL_01_Financing_Portfolio.xlsx to Analyst and use the Murabahah Book, Ijarah Portfolio, and Tawarruq Tracker tabs to compare cure, restructure, and exit paths for stressed accounts over the next 90 days. Quantify the likely impact on gross impaired financing, management overlays, and profit income, and show where Shariah or documentation constraints limit the bank\'s options. Flag remediation paths that need immediate executive approval as Red, paths that are viable with governance follow-up as Amber, and paths already well supported as Green. Present as a RAG table.',
      ], DESC_ANALYST),
      tool(T_EXCEL, M365_LIC, M365_ACCT, [
        'Using the Murabahah Book tab in this workbook, create a new sheet called "IFSA Risk Dashboard" that summarises outstanding balance, Stage 2 share, gross impaired financing, and documentation exceptions by product line. Pull supporting trends from the Tawarruq Tracker and Ijarah Portfolio tabs, show the 5 biggest MYR contributors to deterioration over the last 4 quarters, and add a commentary column that separates credit stress from Shariah-process weakness. Flag product lines requiring immediate intervention as Red, watchlist product lines as Amber, and stable product lines as Green. Present as a RAG table.',
        'Using the GIA Performance tab in this workbook, create a new sheet called "Profit Distribution Pressure" that analyses runoff, customer return expectations, and the profitability impact of support actions across GIA cohorts. Cross-reference the Wakalah Summary tab so management can see whether funding pressure, asset repricing, or fee recognition is contributing more to the current strain, and add a short note on implications for the planned Sukuk Wakalah programme. Flag customer segments with immediate runoff concern as Red, segments needing active monitoring as Amber, and stable segments as Green. Present as a RAG table.',
        'Using the Tawarruq Tracker tab in this workbook, create a new sheet called "Shariah Exception Map" that groups documentation gaps, approval exceptions, and delinquency trends by relationship team and customer segment. Cross-reference the Murabahah Book and Wakalah Summary tabs to identify whether problem cases are isolated or recurring across similar structures, and add an owner column for Business, Shariah, or Operations remediation. Flag cases needing immediate Shariah Committee review as Red, cases needing management action this month as Amber, and cases already contained as Green. Present as a RAG table.',
      ]),
      tool(T_WORD, M365_LIC, M365_ACCT, [
        'You are the Group Company Secretary at Amanah Tijarah Bank Berhad. Using ISL_02_Shariah_Governance_Report.docx, ISL_03_Islamic_Finance_Policy.docx, and the Murabahah Book and GIA Performance tabs in ISL_01_Financing_Portfolio.xlsx, draft a Board paper that explains the rise in Stage 2 financing, the pressure on profit distribution, and the Shariah-governance decisions management needs before the BNM IFSA review. Separate commercial stress from governance gaps so directors can see where the bank has an earnings problem versus a control problem. Flag matters requiring immediate Board or Shariah Committee direction as Red, management follow-up items as Amber, and information-only items as Green. Present as a RAG table.',
        'You are the Head of Shariah Governance at Amanah Tijarah Bank Berhad. Using ISL_02_Shariah_Governance_Report.docx and the Wakalah Summary and Tawarruq Tracker tabs in ISL_01_Financing_Portfolio.xlsx, draft a remediation note for the Shariah Committee that explains the most material documentation and approval weaknesses, the likely customer impact, and the expected time required to close each gap. Distinguish issues that can be remediated operationally from issues that may require product or policy changes. Flag immediate governance concerns as Red, remediable gaps as Amber, and already controlled areas as Green. Present as a RAG table.',
        'You are the Head of Islamic Product Governance at Amanah Tijarah Bank Berhad. Using ISL_03_Islamic_Finance_Policy.docx and the Murabahah Book, Ijarah Portfolio, and Tawarruq Tracker tabs in ISL_01_Financing_Portfolio.xlsx, prepare a policy gap analysis showing where current portfolio behaviour appears misaligned with approved structures, exception tolerances, or escalation rules. Highlight whether the pattern suggests isolated execution drift or a broader need to tighten product governance. Flag policy areas needing immediate amendment or enforcement as Red, areas needing clarification as Amber, and areas that remain fit for purpose as Green. Present as a RAG table.',
      ]),
      tool(T_PPT, M365_LIC, M365_ACCT, [
        'You are the Group Chief of Staff at Amanah Tijarah Bank Berhad. Create a 6-slide Board Risk and Shariah Committee deck using ISL_01_Financing_Portfolio.xlsx, ISL_02_Shariah_Governance_Report.docx, and ISL_03_Islamic_Finance_Policy.docx as source context. Cover the Murabahah Book and GIA Performance trends, the Tawarruq Tracker and Wakalah Summary governance issues, the implications for the Sukuk Wakalah plan, and the management actions required before the BNM IFSA review. Flag the main message on each slide as Red, Amber, or Green so directors can see urgency at a glance. Present as a RAG table.',
        'You are the Group CFO at Amanah Tijarah Bank Berhad. Build a 5-slide regulator briefing deck that uses the Murabahah Book, Tawarruq Tracker, and GIA Performance tabs in ISL_01_Financing_Portfolio.xlsx to explain what has deteriorated, what management has already done, and where uncertainty remains. Use ISL_02_Shariah_Governance_Report.docx to maintain an IFSA-ready tone, and include one slide that isolates liquidity and profit-distribution resilience ahead of the sukuk programme. Flag high-concern messages as Red, messages needing explanatory support as Amber, and stabilising indicators as Green. Present as a RAG table.',
        'You are the Head of Treasury Funding at Amanah Tijarah Bank Berhad. Create a 5-slide investor and depositor confidence deck using ISL_02_Shariah_Governance_Report.docx and the GIA Performance and Wakalah Summary tabs in ISL_01_Financing_Portfolio.xlsx. Show which issues are operationally fixable, which issues affect funding confidence most, and what management can credibly say about timing, fairness, and sukuk readiness. Flag messages that need immediate stakeholder handling as Red, messages needing careful framing as Amber, and messages already defensible as Green. Present as a RAG table.',
      ]),
      tool(T_OUTLOOK, M365_LIC, M365_ACCT, [
        'You are the Group CFO at Amanah Tijarah Bank Berhad. Using ISL_02_Shariah_Governance_Report.docx and the Murabahah Book and GIA Performance tabs in ISL_01_Financing_Portfolio.xlsx, analyse which issues must appear in the first email to the BNM supervision team, which belong in appendices, and which should remain internal until the IFSA review meeting. Then draft the email in a calm regulatory tone that acknowledges the current pressure, points to management\'s remediation path, and avoids implying that all issues are already closed. Flag must-state items as Red, supporting items as Amber, and internal-only items as Green. Present as a RAG table.',
        'You are the Head of Shariah Governance at Amanah Tijarah Bank Berhad. Using the Wakalah Summary and Tawarruq Tracker tabs in ISL_01_Financing_Portfolio.xlsx together with ISL_03_Islamic_Finance_Policy.docx, analyse which decisions you need from the Shariah Committee before the next meeting and draft an email that frames the issues clearly without overstating the severity. Separate items requiring immediate fatwa or approval attention from items that can be handled through management remediation. Flag agenda items needing urgent member attention as Red, items for scheduled review as Amber, and information-only items as Green. Present as a RAG table.',
        'You are the Head of Retail and Branch Banking at Amanah Tijarah Bank Berhad. Using the GIA Performance tab in ISL_01_Financing_Portfolio.xlsx and ISL_02_Shariah_Governance_Report.docx, assess what branch leaders should tell customers about GIA returns, service fairness, and the bank\'s response to current market conditions, then draft an internal note that keeps messaging disciplined and consistent. Separate what staff may say confidently, what must be escalated, and what should never be improvised in customer conversations. Flag message points with immediate conduct risk as Red, points needing manager coaching as Amber, and safe factual points as Green. Present as a RAG table.',
      ]),
      tool(T_TEAMS, M365_LIC, M365_ACCT, [
        'You are the Group Chief of Staff at Amanah Tijarah Bank Berhad. Using this recorded Teams meeting recap from the ALCO, Board Risk Committee, or Shariah Committee, identify every discussion point linked to the Murabahah Book, Tawarruq Tracker, Wakalah Summary, or GIA Performance issues in ISL_01_Financing_Portfolio.xlsx. Separate decisions already taken from unresolved issues, note owners and deadlines, and highlight anything that must be closed before the BNM IFSA review. Flag must-close items as Red, this-month actions as Amber, and monitor-only items as Green. Present as a RAG table.',
        'You are the Group CFO at Amanah Tijarah Bank Berhad. Using this recorded Teams meeting recap and the stress themes visible in the GIA Performance and Murabahah Book tabs of ISL_01_Financing_Portfolio.xlsx, identify statements about liquidity resilience, profit-distribution support, or remediation timing that could later be interpreted as management commitments. Quote the relevant speaker, explain why the wording matters, and distinguish between defensible commitments and aspirational comments. Flag statements that should be reviewed by Legal or Regulatory Affairs as Red, statements needing clarification as Amber, and statements safe to reuse as Green. Present as a RAG table.',
        'You are the Head of Shariah Governance at Amanah Tijarah Bank Berhad. Using this Teams meeting recap together with ISL_03_Islamic_Finance_Policy.docx and the Wakalah Summary and Tawarruq Tracker tabs in ISL_01_Financing_Portfolio.xlsx, assess whether the meeting reflects policy-consistent decision making on exception approvals, customer treatment, and Shariah remediation. Highlight where the discussion suggests uncertainty between Business, Treasury, Shariah, and Operations on who owns the fixes. Flag governance concerns requiring immediate escalation as Red, issues needing documented follow-up as Amber, and policy-consistent discussion points as Green. Present as a RAG table.',
      ], DESC_TEAMS),
      tool(T_NOTEBOOK, M365_LIC, M365_ACCT, [
        'You are the Group CEO at Amanah Tijarah Bank Berhad. In Copilot Notebook, use ISL_01_Financing_Portfolio.xlsx, ISL_02_Shariah_Governance_Report.docx, and ISL_03_Islamic_Finance_Policy.docx, and tell Notebook to synthesise across the Murabahah Book, Tawarruq Tracker, Wakalah Summary, and GIA Performance tabs with citations for every major point. Ask for the 10 issues most likely to come up in the BNM IFSA review, the evidence management has for each answer, and the gaps that still need closing before the sukuk programme moves ahead. Flag issues that could materially weaken management credibility as Red, issues that need tighter support as Amber, and issues already defensible as Green. Present as a RAG table.',
        'You are the Head of Islamic Product Strategy at Amanah Tijarah Bank Berhad. In Copilot Notebook, use ISL_01_Financing_Portfolio.xlsx and ISL_03_Islamic_Finance_Policy.docx, and ask Notebook to compare what the Murabahah Book, Ijarah Portfolio, and Tawarruq Tracker tabs imply about real portfolio behaviour with what the policy says should happen on product structure, exception handling, and escalation. Require direct citations to the workbook tabs and policy sections for every conclusion. Flag contradictions that need immediate executive attention as Red, tensions that need clarification as Amber, and areas where practice matches policy as Green. Present as a RAG table.',
        'You are the Group Treasurer at Amanah Tijarah Bank Berhad. In Copilot Notebook, use ISL_01_Financing_Portfolio.xlsx and ISL_02_Shariah_Governance_Report.docx, and ask Notebook to connect the GIA Performance and Wakalah Summary trends with the external narrative management wants to give on liquidity, customer fairness, and sukuk readiness. Ask where the narrative is strongest, where it sounds incomplete, and which data points will draw the hardest questions from investors or auditors. Flag narrative gaps that are highest risk in live conversations as Red, gaps that need supporting detail as Amber, and areas already coherent as Green. Present as a RAG table.',
      ], DESC_NOTEBOOK),
      tool(T_COWORK, M365_LIC, M365_ACCT, [
        'You are the Group Chief of Staff at Amanah Tijarah Bank Berhad. Research the latest BNM and regional Islamic-banking commentary relevant to the issues visible in the Murabahah Book, GIA Performance, and Wakalah Summary tabs of ISL_01_Financing_Portfolio.xlsx, draft a 2-page OneDrive brief titled "IFSA Review Readiness - Islamic Banking", email it to the CEO, CFO, Head of Shariah Governance, and Treasurer, and schedule a 30-minute prep meeting for tomorrow morning. Ask Cowork to put a one-page summary at the front that flags immediate review items as Red, this-month follow-ups as Amber, and stable areas as Green. Present as a RAG table.',
        'You are the Head of Shariah Governance at Amanah Tijarah Bank Berhad. Review outstanding tasks, recent emails, and calendar items linked to the documentation and exception issues visible in the Tawarruq Tracker and Wakalah Summary tabs of ISL_01_Financing_Portfolio.xlsx, then send follow-ups to overdue owners, create a consolidated action list in Word, and post a short status update in Teams for the Islamic leadership group. Ask Cowork to classify each action by urgency and owner readiness so management can see what must move before the BNM review and sukuk sign-off. Flag immediate overdue actions as Red, actions still recoverable this month as Amber, and actions on track as Green. Present as a RAG table.',
      ], DESC_COWORK),
      tool(T_EDIT_COPILOT, M365_LIC, M365_ACCT, [
        'You are the Head of Regulatory Affairs at Amanah Tijarah Bank Berhad. Using ISL_02_Shariah_Governance_Report.docx in Word for the web, restructure the document so the opening section speaks directly to the pressures visible in the Murabahah Book, Tawarruq Tracker, and GIA Performance tabs of ISL_01_Financing_Portfolio.xlsx, then add a short appendix on exception governance drawn from ISL_03_Islamic_Finance_Policy.docx. Make the revised document easier for executives to navigate by grouping facts, supervisory questions, and management responses. Flag sections that need immediate senior review as Red, sections needing factual enhancement as Amber, and sections already fit for use as Green. Present as a RAG table.',
        'Using the Murabahah Book, Ijarah Portfolio, Wakalah Summary, Tawarruq Tracker, and GIA Performance tabs in ISL_01_Financing_Portfolio.xlsx, create a new worksheet called "Islamic Executive Heatmap" that consolidates financing deterioration, Shariah exceptions, profit-distribution pressure, and liquidity indicators into one view for the CEO and Shariah Committee. Reorder the content so the highest-risk products and customer clusters appear first, add concise commentary cells, and ensure the summary at the top refreshes when the underlying tabs change. Flag immediate intervention cases as Red, close-watch cases as Amber, and contained cases as Green. Present as a RAG table.',
      ], DESC_EDIT_COPILOT),
      tool(T_WORD_AGT, M365_LIC, M365_ACCT, [
        'You are the Head of Islamic Product Governance at Amanah Tijarah Bank Berhad. Open ISL_03_Islamic_Finance_Policy.docx in Word for Web and create an agent called "Amanah Shariah Policy Guide". Describe it as an assistant that answers questions on approved structures, exception governance, customer treatment, and escalation rules, using the same terminology reflected in the Murabahah Book, Tawarruq Tracker, and Wakalah Summary tabs of ISL_01_Financing_Portfolio.xlsx. Share it with Shariah, Product, Risk, and selected business heads. Flag intended users with immediate need as Red, secondary users as Amber, and optional users as Green. Present as a RAG table.',
        'You are the Head of Shariah Governance at Amanah Tijarah Bank Berhad. Demo the Amanah Shariah Policy Guide agent by asking how a tawarruq account with repeated documentation exceptions should move through approval and remediation under current policy, and then ask how Wakalah Summary exceptions should affect governance escalation if customer fairness is at stake. Have the agent classify each answer by urgency for front-line users. Flag guidance requiring immediate frontline reinforcement as Red, guidance needing manager coaching as Amber, and guidance already well understood as Green. Present as a RAG table.',
      ], DESC_WORD_AGT),
      tool(T_PPT_AGT, M365_LIC, M365_ACCT, [
        'You are the Group Chief of Staff at Amanah Tijarah Bank Berhad. Build the IFSA and sukuk readiness deck in PowerPoint for Web and create an agent called "Islamic Review Deck Navigator". Describe it as an assistant that answers questions on the Murabahah Book, GIA Performance, Tawarruq Tracker, and Wakalah Summary story so executives can find the right slide quickly during Board, Shariah Committee, and regulator prep. Share it with the CEO office, Finance, Treasury, and Shariah Governance teams. Flag user groups that need immediate access as Red, useful access as Amber, and optional access as Green. Present as a RAG table.',
        'You are the Group CFO at Amanah Tijarah Bank Berhad. Demo the Islamic Review Deck Navigator agent by asking which product clusters drove the rise in Stage 2 financing, what the GIA Performance tab says about runoff pressure, and which slide best explains the main issues in the Tawarruq Tracker before the BNM review. Then ask it to classify each answer so the speaker knows what to emphasise first. Flag messages that need front-page prominence as Red, backup discussion points as Amber, and appendix-only material as Green. Present as a RAG table.',
      ], DESC_PPT_AGT),
      tool(T_XL_AGT, M365_LIC, M365_ACCT, [
        'You are the Group CFO at Amanah Tijarah Bank Berhad. Open ISL_01_Financing_Portfolio.xlsx in Excel for Web and create an agent called "Amanah Financing Portfolio Q&A". Describe it as an assistant that answers questions from the Murabahah Book, Ijarah Portfolio, Wakalah Summary, Tawarruq Tracker, and GIA Performance tabs for executive, Shariah Committee, and regulator prep. Share it with Finance, Treasury, Risk, Shariah Governance, and Special Assets. Flag functions with immediate need for live workbook access as Red, functions with useful but secondary need as Amber, and optional functions as Green. Present as a RAG table.',
        'You are the Head of Portfolio Remediation at Amanah Tijarah Bank Berhad. Demo the Amanah Financing Portfolio Q&A agent by asking which product on the Murabahah Book or Tawarruq Tracker tab has the fastest deterioration, which GIA cohorts on the GIA Performance tab are most sensitive to return pressure, and whether Wakalah Summary exceptions are clustering or stabilising. Ask the agent to classify each answer by urgency. Flag immediate management priorities as Red, watchlist priorities as Amber, and stable exposures as Green. Present as a RAG table.',
      ], DESC_XL_AGT),
      tool(T_BUILDER, M365_LIC, M365_ACCT, [
        'You are the Group Chief of Staff at Amanah Tijarah Bank Berhad. Go to Copilot Studio and create a new agent called "Amanah IFSA War Room" using ISL_01_Financing_Portfolio.xlsx, ISL_02_Shariah_Governance_Report.docx, and ISL_03_Islamic_Finance_Policy.docx as knowledge sources. Give it starter topics for IFSA Review, Shariah Exceptions, GIA Pressure, and Sukuk Readiness, and make sure the workbook tabs most often referenced are Murabahah Book, Tawarruq Tracker, Wakalah Summary, and GIA Performance. Publish it to Teams for senior executives and core control functions. Flag audiences needing immediate access as Red, follow-on audiences as Amber, and optional audiences as Green. Present as a RAG table.',
        'You are the Group CEO at Amanah Tijarah Bank Berhad. Demo the published Amanah IFSA War Room agent by asking for the 60-second version of why Stage 2 financing reached 11.6%, which issues in the Tawarruq Tracker deserve the first call in tomorrow\'s prep session, and which governance questions from ISL_03_Islamic_Finance_Policy.docx remain most exposed before the BNM review. Then ask the agent to classify each answer by urgency for the executive team. Flag immediate decision items as Red, near-term management items as Amber, and monitor-only items as Green. Present as a RAG table.',
      ], DESC_BUILDER)
    ],
    'PT Bank Syariah Cakrawala Sentosa Tbk',
    'Pembiayaan Stage 2 di 11,6% dan arus keluar DPK investasi menekan rencana sukuk menjelang review OJK, BI, dan pasar IDX.')

]

print(f"Industries batch 1 written: {len(INDUSTRIES_1)} entries")
