import sys; sys.path.insert(0,'.')
from util import *

INDUSTRIES_4 = [

# ── OG DOWNSTREAM ───────────────────────────────────────────────────────
ind('og-downstream', 'og-energy', 'Oil & Gas Downstream', '🏭', '#BF360C', '#D84315',
    'Bumi Seri Refining Berhad',
    'DOSH and DOE focus intensifies as margin drops to USD5.1/bbl ahead of turnaround season.',
    'Bumi Seri Refining Berhad runs a coastal refinery supplying transport fuels and petrochemical feedstock into Malaysia and selected Indonesian counterparties. The Refinery Run Rate sheet shows utilisation slipping to 84% after repeated reliability interruptions on one conversion unit, while Product Yield Summary indicates weaker middle-distillate recovery than plan. Margin Tracker has compressed to USD5.1 per barrel, only slightly above the internal alert threshold, and Feedstock Cost Log shows crude slate penalties widening with sour cargo volatility. The Turnaround Schedule sheet confirms a major unit shutdown is now less than four months away, making maintenance sequencing and contractor readiness a Board-level issue. DOSH process-safety expectations and Department of Environment emissions scrutiny are both tightening as flaring variance increases. Management wants the action plan in OGD_03_Refinery_Maintenance_Plan.docx to line up more clearly with the compliance obligations in OGD_02_Environmental_Compliance.docx before lenders and insurers start asking harder questions. The Indonesian affiliate is also benchmarking performance against Pertamina-linked downstream peers, so credibility on execution matters immediately.',
    [
        'OGD_01_Refinery_Operations.xlsx',
        'OGD_02_Environmental_Compliance.docx',
        'OGD_03_Refinery_Maintenance_Plan.docx'
    ],
    [
      tool(T_CHAT, FREE_LIC, FREE_ACCT, [
        'You are the COO at Bumi Seri Refining Berhad. Using the Refinery Run Rate, Product Yield Summary, Margin Tracker, and Turnaround Schedule sheets in OGD_01_Refinery_Operations.xlsx, prepare a one-page operating diagnostic that explains why margin compression and turnaround and compliance execution risk are worsening at the same time. Present the answer as a RAG table with columns for Issue, Evidence from Sheet, Likely Root Cause, and 30-Day Action.',
        'You are the Chief Strategy Officer at Bumi Seri Refining Berhad. Using OGD_02_Environmental_Compliance.docx, OGD_03_Refinery_Maintenance_Plan.docx, and the Feedstock Cost Log sheet in OGD_01_Refinery_Operations.xlsx, identify the 5 decisions management must make before the next executive review so that growth ambitions do not outpace control discipline. Present the answer as a prioritised table with columns for Decision, Why Now, Evidence Source, and Consequence if Deferred.',
        'You are the Head of Corporate Affairs at Bumi Seri Refining Berhad. Using the trends implied by the Refinery Run Rate, Margin Tracker, and Turnaround Schedule sheets in OGD_01_Refinery_Operations.xlsx, draft a stakeholder communication map covering the Board, regulators, frontline teams, and external partners. Present the answer as a RAG table with columns for Audience, Key Message, Timing, and Communication Risk.'
      ]),
      tool(T_RESEARCHER, FREE_LIC, FREE_ACCT, [
        'You are the Strategy Director at Bumi Seri Refining Berhad. Research how comparable organisations in this sector responded when margin compression became visible in operating data like the Refinery Run Rate and Margin Tracker sheets in OGD_01_Refinery_Operations.xlsx. Present the answer as a table with columns for Organisation, Trigger, Intervention, Measured Outcome, and Relevance to Bumi Seri Refining Berhad. Flag any claim that could not be independently verified.',
        'You are the Compliance Director at Bumi Seri Refining Berhad. Research the latest guidance, enforcement themes, and supervisory expectations relevant to DOSH and DOE Malaysia and the affiliated Indonesian context of Pertamina stakeholders, then link them to the control areas implied by OGD_02_Environmental_Compliance.docx and the Turnaround Schedule sheet in OGD_01_Refinery_Operations.xlsx. Present the answer as a RAG table with columns for Requirement, Malaysia Context, Indonesia Context, Practical Impact, and Immediate Management Action. Flag any claim that could not be independently verified.',
        'You are the CEO at Bumi Seri Refining Berhad. Research three recent sector benchmarks on how peers balanced short-term recovery with longer-term priorities when facing turnaround and compliance execution risk, using the tension visible between the Product Yield Summary and Feedstock Cost Log sheets in OGD_01_Refinery_Operations.xlsx as the framing context. Present the answer as a table with columns for Peer, What They Changed, Time to Impact, Reported Result, and Lesson for Bumi Seri Refining Berhad. Flag any claim that could not be independently verified.'
      ], DESC_RESEARCHER),
      tool(T_ANALYST, M365_LIC, M365_ACCT, [
        'You are the Head of FP&A at Bumi Seri Refining Berhad. Upload OGD_01_Refinery_Operations.xlsx to Analyst and use the Refinery Run Rate, Product Yield Summary, Margin Tracker, and Turnaround Schedule sheets to identify which refinery units are driving the largest share of margin compression and turnaround and compliance execution risk. Present the output as a RAG table with columns for Refinery Unit, Performance Signal, Financial Impact, Control Risk, and Recommended Owner.',
        'You are the CFO at Bumi Seri Refining Berhad. Upload OGD_01_Refinery_Operations.xlsx to Analyst and quantify the revenue, margin, or cash exposure linked to the patterns in the Margin Tracker, Feedstock Cost Log, and Turnaround Schedule sheets, then show where management should intervene first. Present the answer as a ranked table and include one chart that makes the biggest pressure point obvious.',
        'You are the Operations Director at Bumi Seri Refining Berhad. Upload OGD_01_Refinery_Operations.xlsx to Analyst and build a 3-scenario view for the next two quarters using the Refinery Run Rate, Product Yield Summary, Margin Tracker, and Feedstock Cost Log sheets: recover quickly, stabilise slowly, or deteriorate further. Present the result as a RAG table with threshold assumptions, earliest warning sign, and the action that should be triggered in each scenario.'
      ], DESC_ANALYST),
      tool(T_EXCEL, M365_LIC, M365_ACCT, [
        'You are the Business Planning Manager at Bumi Seri Refining Berhad. Using the Refinery Run Rate, Product Yield Summary, Margin Tracker, and Turnaround Schedule sheets in this workbook, create a new worksheet called Executive RAG Dashboard that summarises the top operating and control risks by refinery unit. Add conditional formatting so leaders can instantly see Red, Amber, and Green status plus the numeric driver behind each status.',
        'You are the Performance Manager at Bumi Seri Refining Berhad. Using the Feedstock Cost Log, Margin Tracker, and Turnaround Schedule sheets in OGD_01_Refinery_Operations.xlsx, create a new worksheet called Intervention Tracker that logs the top 10 corrective actions, the accountable owner, the due date, the expected benefit, and the latest status. Include formulas that highlight overdue actions in red and roll up the count of open Reds at the top of the sheet.',
        "You are the Finance Transformation Lead at Bumi Seri Refining Berhad. Using the Refinery Run Rate, Product Yield Summary, and Margin Tracker sheets in OGD_01_Refinery_Operations.xlsx, build a sensitivity model on a new worksheet that shows how small changes in operating throughput, quality or compliance performance, and unit economics would change the overall outcome. Present the result as an easy-to-read decision table that management can use in tomorrow's review."
      ]),
      tool(T_WORD, M365_LIC, M365_ACCT, [
        'You are the Company Secretary at Bumi Seri Refining Berhad. Using OGD_02_Environmental_Compliance.docx, OGD_03_Refinery_Maintenance_Plan.docx, and the evidence implied by the Refinery Run Rate, Margin Tracker, and Turnaround Schedule sheets in OGD_01_Refinery_Operations.xlsx, draft a 2-page Board paper on the current situation, the main risks, and the governance actions required in the next 30 days. Start with a short RAG summary and then move into decisions, owners, and timing.',
        'You are the Head of Internal Audit at Bumi Seri Refining Berhad. Using OGD_02_Environmental_Compliance.docx and the pressure points visible in the Turnaround Schedule and Margin Tracker sheets in OGD_01_Refinery_Operations.xlsx, draft a control-gap memorandum that identifies where process design and frontline execution are drifting apart. Present the core findings as a table with columns for Control Area, Current Gap, Risk if Unresolved, and Proposed Remediation.',
        'You are the CEO at Bumi Seri Refining Berhad. Using OGD_03_Refinery_Maintenance_Plan.docx, the Refinery Run Rate sheet, and the Feedstock Cost Log sheet in OGD_01_Refinery_Operations.xlsx, draft a one-page management note that explains what can still be delivered this year, what must be reset, and how leadership should talk about the change in priorities. Keep the tone candid, steady, and evidence-based.'
      ]),
      tool(T_PPT, M365_LIC, M365_ACCT, [
        'You are the Chief of Staff at Bumi Seri Refining Berhad. Create a 6-slide executive deck using OGD_01_Refinery_Operations.xlsx, OGD_02_Environmental_Compliance.docx, and OGD_03_Refinery_Maintenance_Plan.docx as the source context, covering current performance, the root causes behind margin compression and turnaround and compliance execution risk, the top Red risks, the first 90-day actions, and the decisions required from leadership. Give each slide a headline that states the message, not just the topic.',
        'You are the CFO at Bumi Seri Refining Berhad. Create a 5-slide update deck for leadership that uses the Margin Tracker, Feedstock Cost Log, and Turnaround Schedule sheets in OGD_01_Refinery_Operations.xlsx to show where financial exposure is concentrated and how quickly it can be reduced. Include speaker notes that explain the Red issues in plain language for a non-technical audience.',
        'You are the Strategy Director at Bumi Seri Refining Berhad. Create a single summary slide that links the signals in the Refinery Run Rate, Product Yield Summary, and Turnaround Schedule sheets in OGD_01_Refinery_Operations.xlsx to the priorities in OGD_03_Refinery_Maintenance_Plan.docx. Present it as a RAG matrix with one sentence of management action beside each Red item.'
      ]),
      tool(T_OUTLOOK, M365_LIC, M365_ACCT, [
        'You are the Regulatory Affairs Lead at Bumi Seri Refining Berhad. Draft an email to the relevant authorities and senior internal stakeholders that acknowledges the current pressure areas indicated by the Turnaround Schedule sheet in OGD_01_Refinery_Operations.xlsx, outlines the corrective steps already under way, and requests alignment on the next review checkpoint. Keep the tone factual, controlled, and suitable for scrutiny by DOSH and DOE Malaysia and Pertamina stakeholders counterparts.',
        'You are the COO at Bumi Seri Refining Berhad. Draft an internal email to Refinery, maintenance, and HSE leaders summarising the top three risks shown in the Refinery Run Rate, Margin Tracker, and Turnaround Schedule sheets in OGD_01_Refinery_Operations.xlsx, the required actions this week, and the consequences of delay. End with a bullet list titled What I need from you by Friday.',
        'You are the Head of Stakeholder Management at Bumi Seri Refining Berhad. Draft an external-facing update that explains the current operating situation using plain language consistent with OGD_02_Environmental_Compliance.docx and OGD_03_Refinery_Maintenance_Plan.docx, without overpromising outcomes or admitting fault. Use the evidence implied by the Feedstock Cost Log and Margin Tracker sheets in OGD_01_Refinery_Operations.xlsx to keep the message disciplined.'
      ]),
      tool(T_TEAMS, M365_LIC, M365_ACCT, [
        'You are the Chief of Staff at Bumi Seri Refining Berhad. Using this recorded Teams meeting recap, identify the decisions, unresolved issues, and action items that connect directly to the Refinery Run Rate, Margin Tracker, and Turnaround Schedule sheets in OGD_01_Refinery_Operations.xlsx. Present the output as a RAG table with columns for Topic, What Was Said, Owner, Due Date, and Escalation Level.',
        'You are the Operations Director at Bumi Seri Refining Berhad. Using this Teams recap, draft follow-up actions for the teams responsible for the areas covered in OGD_02_Environmental_Compliance.docx and the Product Yield Summary sheet in OGD_01_Refinery_Operations.xlsx. Group the actions by workstream and include a success measure for each one.',
        'You are the CFO at Bumi Seri Refining Berhad. Using this Teams recap, extract every financial, compliance, or customer-impact figure that would help explain the trends in the Margin Tracker, Feedstock Cost Log, and Turnaround Schedule sheets in OGD_01_Refinery_Operations.xlsx. Present the result as a structured note with sections for Facts, Risks, Commitments, and Missing Information.'
      ], DESC_TEAMS),
      tool(T_NOTEBOOK, M365_LIC, M365_ACCT, [
        'You are the CEO at Bumi Seri Refining Berhad. Upload OGD_01_Refinery_Operations.xlsx, OGD_02_Environmental_Compliance.docx, OGD_03_Refinery_Maintenance_Plan.docx to Copilot Notebook, set the instruction to synthesise across all files with citations, and ask for the 10-slide-equivalent story leadership needs right now. Require Notebook to reconcile the signals from the Refinery Run Rate, Margin Tracker, and Turnaround Schedule sheets in OGD_01_Refinery_Operations.xlsx with the commitments in OGD_02_Environmental_Compliance.docx and OGD_03_Refinery_Maintenance_Plan.docx.',
        'You are the COO at Bumi Seri Refining Berhad. Upload OGD_01_Refinery_Operations.xlsx, OGD_02_Environmental_Compliance.docx, OGD_03_Refinery_Maintenance_Plan.docx to Copilot Notebook and ask whether the priorities implied by the Product Yield Summary and Feedstock Cost Log sheets in OGD_01_Refinery_Operations.xlsx are still realistic given the risk picture in the Turnaround Schedule sheet. Require a RAG table with columns for Priority, Evidence, Risk to Delivery, and Recommendation, all with citations.',
        'You are the Board Liaison at Bumi Seri Refining Berhad. Upload OGD_01_Refinery_Operations.xlsx, OGD_02_Environmental_Compliance.docx, OGD_03_Refinery_Maintenance_Plan.docx to Copilot Notebook and ask for the contradictions management must resolve before the next review, especially where operational ambition, control capability, and financial reality do not line up. Request a concise answer with sections for Contradictions, Questions Directors Will Ask, and Pre-Reads to Send.'
      ], DESC_NOTEBOOK),
      tool(T_COWORK, M365_LIC, M365_ACCT, [
        'You are the COO at Bumi Seri Refining Berhad. Do all of the following autonomously: create a recovery action plan grounded in the Refinery Run Rate, Margin Tracker, and Turnaround Schedule sheets in OGD_01_Refinery_Operations.xlsx; save it to OneDrive; email it to Refinery, maintenance, and HSE leaders; and schedule a 45-minute review meeting for next week. Make the plan easy to track with RAG status and owner-by-owner accountability.',
        'You are the Chief of Staff at Bumi Seri Refining Berhad. Do all of the following autonomously: turn the main obligations from OGD_02_Environmental_Compliance.docx and the priorities from OGD_03_Refinery_Maintenance_Plan.docx into a working checklist, save it in OneDrive, email the checklist to the accountable leaders, and create calendar reminders for each major milestone. Keep the wording clear enough that teams can act without a second briefing.'
      ], DESC_COWORK),
      tool(T_EDIT_COPILOT, M365_LIC, M365_ACCT, [
        'You are the Company Secretary at Bumi Seri Refining Berhad. Using OGD_02_Environmental_Compliance.docx in Word for the web, add an appendix titled Operating Escalation and RAG Governance Protocol and populate it with decision rights, escalation thresholds, evidence requirements, and sign-off owners that mirror the issues visible in the Turnaround Schedule and Margin Tracker sheets in OGD_01_Refinery_Operations.xlsx. Keep the style consistent with the existing document.',
        'You are the Performance Manager at Bumi Seri Refining Berhad. Using OGD_01_Refinery_Operations.xlsx in Excel for the web, create a new worksheet called Leadership Recovery Tracker that combines the Refinery Run Rate, Margin Tracker, Feedstock Cost Log, and Turnaround Schedule sheets into a single view with owner, due date, expected impact, and live RAG status. Reorder the layout so the Red issues appear first and add formulas that refresh the summary automatically.'
      ], DESC_EDIT_COPILOT),
      tool(T_WORD_AGT, M365_LIC, M365_ACCT, [
        'You are the Knowledge Manager at Bumi Seri Refining Berhad. Open OGD_02_Environmental_Compliance.docx in Word for Web and create an agent called Refinery Compliance Navigator. Describe it as an assistant that answers questions about the policies, thresholds, and escalation rules that matter when the Turnaround Schedule sheet and the Margin Tracker sheet in OGD_01_Refinery_Operations.xlsx start to move against plan, then share it with the core leadership team.',
        'You are the COO at Bumi Seri Refining Berhad. Demo the Refinery Compliance Navigator agent by asking: The hydrocracker is underperforming, turnaround readiness is Amber, and flare-related compliance risk is rising. What are the immediate actions, which documents should the turnaround manager update first, and what evidence will DOSH or insurers ask to see? Show how the answer cites the source document and gives a clear next step.'
      ], DESC_WORD_AGT),
      tool(T_PPT_AGT, M365_LIC, M365_ACCT, [
        'You are the Chief of Staff at Bumi Seri Refining Berhad. Create the leadership deck in PowerPoint for Web, then create an agent called Margin Recovery Board Bot that helps executives find the right slide, chart, and message quickly. Make sure it can answer questions grounded in the Refinery Run Rate, Margin Tracker, and Turnaround Schedule sheets in OGD_01_Refinery_Operations.xlsx.',
        'You are the CFO at Bumi Seri Refining Berhad. Demo the Margin Recovery Board Bot agent by asking which Red issue needs leadership attention first, what slide supports that answer, and what decision should be taken this week. Keep the response short enough to use in a live meeting.'
      ], DESC_PPT_AGT),
      tool(T_XL_AGT, M365_LIC, M365_ACCT, [
        'You are the Data Product Owner at Bumi Seri Refining Berhad. Open OGD_01_Refinery_Operations.xlsx in Excel for Web and create an agent called Refinery Operations Q&A. Describe it as an assistant that answers plain-English questions about the Refinery Run Rate, Product Yield Summary, Margin Tracker, Feedstock Cost Log, and Turnaround Schedule sheets and share it with the teams that need faster insight.',
        'You are the COO at Bumi Seri Refining Berhad. Demo the Refinery Operations Q&A agent by asking which refinery unit is currently Red, what is driving the status, and what leading indicator should be watched next. Then ask for the one figure from the workbook that leadership should remember before the next review.'
      ], DESC_XL_AGT),
      tool(T_BUILDER, M365_LIC, M365_ACCT, [
        'You are the Digital Transformation Lead at Bumi Seri Refining Berhad. Go to copilotstudio.microsoft.com, create a new agent called Bumi Seri Refinery Assistant, use OGD_01_Refinery_Operations.xlsx, OGD_02_Environmental_Compliance.docx, OGD_03_Refinery_Maintenance_Plan.docx as the knowledge sources, and configure topics for Margin Recovery, Turnaround Readiness, Environmental Compliance, Feedstock Decisions. Publish it to Teams with instructions that it should answer in a concise, evidence-based way and surface a clear escalation path when users ask high-risk questions.',
        'You are the Operations Director at Bumi Seri Refining Berhad. Demo the Bumi Seri Refinery Assistant agent by asking: The hydrocracker is underperforming, turnaround readiness is Amber, and flare-related compliance risk is rising. What are the immediate actions, which documents should the turnaround manager update first, and what evidence will DOSH or insurers ask to see? Show how the agent responds with the relevant file, the recommended action, and the owner who should take the next step.'
      ], DESC_BUILDER),
    ],
    companyID='PT Bumi Seri Refinery Tbk',
    taglineID='Pertamina-facing margin turun ke USD5.1/bbl saat kesiapan turnaround disorot.'),

# ── RENEWABLE ENERGY ───────────────────────────────────────────────────────
ind('renewable-energy', 'og-energy', 'Renewable Energy', '☀️', '#F9A825', '#F57F17',
    'Suria Angin Utilities Berhad',
    'ST and TNB negotiations tighten as curtailment reaches 8.6% and O&M costs jump 14%.',
    'Suria Angin Utilities Berhad owns utility-scale solar and wind assets in Malaysia and is building a cross-border project development pipeline with an Indonesian affiliate. The Solar Generation Log and Wind Farm Output sheets show solid nameplate availability, but Grid Curtailment Tracker reveals curtailment has reached 8.6% at two sites because of transmission constraints. PPA Revenue Tracker indicates revenue leakage is now material, while O&M Cost Summary has risen 14% year on year due to inverter replacements, blade inspections, and imported spare parts. Management is in active discussions with Tenaga Nasional and Suruhanjaya Tenaga on dispatch performance, while the Indonesian team is tracking PLN and Kementerian ESDM expectations for comparable projects. The Board wants clearer evidence that RE_03_Asset_Management_Plan.docx is still the right operating playbook and that the ESG disclosures in RE_02_ESG_Reporting_Framework.docx can withstand lender scrutiny. If curtailment and maintenance inflation are not stabilised before the next quarter, refinancing terms and growth capex sequencing may both be affected.',
    [
        'RE_01_Plant_Performance.xlsx',
        'RE_02_ESG_Reporting_Framework.docx',
        'RE_03_Asset_Management_Plan.docx'
    ],
    [
      tool(T_CHAT, FREE_LIC, FREE_ACCT, [
        'You are the COO at Suria Angin Utilities Berhad. Using the Solar Generation Log, Wind Farm Output, PPA Revenue Tracker, and Grid Curtailment Tracker sheets in RE_01_Plant_Performance.xlsx, prepare a one-page operating diagnostic that explains why curtailment-driven revenue leakage and asset reliability and cost inflation are worsening at the same time. Present the answer as a RAG table with columns for Issue, Evidence from Sheet, Likely Root Cause, and 30-Day Action.',
        'You are the Chief Strategy Officer at Suria Angin Utilities Berhad. Using RE_02_ESG_Reporting_Framework.docx, RE_03_Asset_Management_Plan.docx, and the O&M Cost Summary sheet in RE_01_Plant_Performance.xlsx, identify the 5 decisions management must make before the next executive review so that growth ambitions do not outpace control discipline. Present the answer as a prioritised table with columns for Decision, Why Now, Evidence Source, and Consequence if Deferred.',
        'You are the Head of Corporate Affairs at Suria Angin Utilities Berhad. Using the trends implied by the Solar Generation Log, PPA Revenue Tracker, and Grid Curtailment Tracker sheets in RE_01_Plant_Performance.xlsx, draft a stakeholder communication map covering the Board, regulators, frontline teams, and external partners. Present the answer as a RAG table with columns for Audience, Key Message, Timing, and Communication Risk.'
      ]),
      tool(T_RESEARCHER, FREE_LIC, FREE_ACCT, [
        'You are the Strategy Director at Suria Angin Utilities Berhad. Research how comparable organisations in this sector responded when curtailment-driven revenue leakage became visible in operating data like the Solar Generation Log and PPA Revenue Tracker sheets in RE_01_Plant_Performance.xlsx. Present the answer as a table with columns for Organisation, Trigger, Intervention, Measured Outcome, and Relevance to Suria Angin Utilities Berhad. Flag any claim that could not be independently verified.',
        'You are the Compliance Director at Suria Angin Utilities Berhad. Research the latest guidance, enforcement themes, and supervisory expectations relevant to Suruhanjaya Tenaga and TNB and the affiliated Indonesian context of PLN and Kementerian ESDM, then link them to the control areas implied by RE_02_ESG_Reporting_Framework.docx and the Grid Curtailment Tracker sheet in RE_01_Plant_Performance.xlsx. Present the answer as a RAG table with columns for Requirement, Malaysia Context, Indonesia Context, Practical Impact, and Immediate Management Action. Flag any claim that could not be independently verified.',
        'You are the CEO at Suria Angin Utilities Berhad. Research three recent sector benchmarks on how peers balanced short-term recovery with longer-term priorities when facing asset reliability and cost inflation, using the tension visible between the Wind Farm Output and O&M Cost Summary sheets in RE_01_Plant_Performance.xlsx as the framing context. Present the answer as a table with columns for Peer, What They Changed, Time to Impact, Reported Result, and Lesson for Suria Angin Utilities Berhad. Flag any claim that could not be independently verified.'
      ], DESC_RESEARCHER),
      tool(T_ANALYST, M365_LIC, M365_ACCT, [
        'You are the Head of FP&A at Suria Angin Utilities Berhad. Upload RE_01_Plant_Performance.xlsx to Analyst and use the Solar Generation Log, Wind Farm Output, PPA Revenue Tracker, and Grid Curtailment Tracker sheets to identify which plant or sites are driving the largest share of curtailment-driven revenue leakage and asset reliability and cost inflation. Present the output as a RAG table with columns for Plant Or Site, Performance Signal, Financial Impact, Control Risk, and Recommended Owner.',
        'You are the CFO at Suria Angin Utilities Berhad. Upload RE_01_Plant_Performance.xlsx to Analyst and quantify the revenue, margin, or cash exposure linked to the patterns in the PPA Revenue Tracker, O&M Cost Summary, and Grid Curtailment Tracker sheets, then show where management should intervene first. Present the answer as a ranked table and include one chart that makes the biggest pressure point obvious.',
        'You are the Operations Director at Suria Angin Utilities Berhad. Upload RE_01_Plant_Performance.xlsx to Analyst and build a 3-scenario view for the next two quarters using the Solar Generation Log, Wind Farm Output, PPA Revenue Tracker, and O&M Cost Summary sheets: recover quickly, stabilise slowly, or deteriorate further. Present the result as a RAG table with threshold assumptions, earliest warning sign, and the action that should be triggered in each scenario.'
      ], DESC_ANALYST),
      tool(T_EXCEL, M365_LIC, M365_ACCT, [
        'You are the Business Planning Manager at Suria Angin Utilities Berhad. Using the Solar Generation Log, Wind Farm Output, PPA Revenue Tracker, and Grid Curtailment Tracker sheets in this workbook, create a new worksheet called Executive RAG Dashboard that summarises the top operating and control risks by plant or site. Add conditional formatting so leaders can instantly see Red, Amber, and Green status plus the numeric driver behind each status.',
        'You are the Performance Manager at Suria Angin Utilities Berhad. Using the O&M Cost Summary, PPA Revenue Tracker, and Grid Curtailment Tracker sheets in RE_01_Plant_Performance.xlsx, create a new worksheet called Intervention Tracker that logs the top 10 corrective actions, the accountable owner, the due date, the expected benefit, and the latest status. Include formulas that highlight overdue actions in red and roll up the count of open Reds at the top of the sheet.',
        "You are the Finance Transformation Lead at Suria Angin Utilities Berhad. Using the Solar Generation Log, Wind Farm Output, and PPA Revenue Tracker sheets in RE_01_Plant_Performance.xlsx, build a sensitivity model on a new worksheet that shows how small changes in operating throughput, quality or compliance performance, and unit economics would change the overall outcome. Present the result as an easy-to-read decision table that management can use in tomorrow's review."
      ]),
      tool(T_WORD, M365_LIC, M365_ACCT, [
        'You are the Company Secretary at Suria Angin Utilities Berhad. Using RE_02_ESG_Reporting_Framework.docx, RE_03_Asset_Management_Plan.docx, and the evidence implied by the Solar Generation Log, PPA Revenue Tracker, and Grid Curtailment Tracker sheets in RE_01_Plant_Performance.xlsx, draft a 2-page Board paper on the current situation, the main risks, and the governance actions required in the next 30 days. Start with a short RAG summary and then move into decisions, owners, and timing.',
        'You are the Head of Internal Audit at Suria Angin Utilities Berhad. Using RE_02_ESG_Reporting_Framework.docx and the pressure points visible in the Grid Curtailment Tracker and PPA Revenue Tracker sheets in RE_01_Plant_Performance.xlsx, draft a control-gap memorandum that identifies where process design and frontline execution are drifting apart. Present the core findings as a table with columns for Control Area, Current Gap, Risk if Unresolved, and Proposed Remediation.',
        'You are the CEO at Suria Angin Utilities Berhad. Using RE_03_Asset_Management_Plan.docx, the Solar Generation Log sheet, and the O&M Cost Summary sheet in RE_01_Plant_Performance.xlsx, draft a one-page management note that explains what can still be delivered this year, what must be reset, and how leadership should talk about the change in priorities. Keep the tone candid, steady, and evidence-based.'
      ]),
      tool(T_PPT, M365_LIC, M365_ACCT, [
        'You are the Chief of Staff at Suria Angin Utilities Berhad. Create a 6-slide executive deck using RE_01_Plant_Performance.xlsx, RE_02_ESG_Reporting_Framework.docx, and RE_03_Asset_Management_Plan.docx as the source context, covering current performance, the root causes behind curtailment-driven revenue leakage and asset reliability and cost inflation, the top Red risks, the first 90-day actions, and the decisions required from leadership. Give each slide a headline that states the message, not just the topic.',
        'You are the CFO at Suria Angin Utilities Berhad. Create a 5-slide update deck for leadership that uses the PPA Revenue Tracker, O&M Cost Summary, and Grid Curtailment Tracker sheets in RE_01_Plant_Performance.xlsx to show where financial exposure is concentrated and how quickly it can be reduced. Include speaker notes that explain the Red issues in plain language for a non-technical audience.',
        'You are the Strategy Director at Suria Angin Utilities Berhad. Create a single summary slide that links the signals in the Solar Generation Log, Wind Farm Output, and Grid Curtailment Tracker sheets in RE_01_Plant_Performance.xlsx to the priorities in RE_03_Asset_Management_Plan.docx. Present it as a RAG matrix with one sentence of management action beside each Red item.'
      ]),
      tool(T_OUTLOOK, M365_LIC, M365_ACCT, [
        'You are the Regulatory Affairs Lead at Suria Angin Utilities Berhad. Draft an email to the relevant authorities and senior internal stakeholders that acknowledges the current pressure areas indicated by the Grid Curtailment Tracker sheet in RE_01_Plant_Performance.xlsx, outlines the corrective steps already under way, and requests alignment on the next review checkpoint. Keep the tone factual, controlled, and suitable for scrutiny by Suruhanjaya Tenaga and TNB and PLN and Kementerian ESDM counterparts.',
        'You are the COO at Suria Angin Utilities Berhad. Draft an internal email to Asset management, finance, and ESG leaders summarising the top three risks shown in the Solar Generation Log, PPA Revenue Tracker, and Grid Curtailment Tracker sheets in RE_01_Plant_Performance.xlsx, the required actions this week, and the consequences of delay. End with a bullet list titled What I need from you by Friday.',
        'You are the Head of Stakeholder Management at Suria Angin Utilities Berhad. Draft an external-facing update that explains the current operating situation using plain language consistent with RE_02_ESG_Reporting_Framework.docx and RE_03_Asset_Management_Plan.docx, without overpromising outcomes or admitting fault. Use the evidence implied by the O&M Cost Summary and PPA Revenue Tracker sheets in RE_01_Plant_Performance.xlsx to keep the message disciplined.'
      ]),
      tool(T_TEAMS, M365_LIC, M365_ACCT, [
        'You are the Chief of Staff at Suria Angin Utilities Berhad. Using this recorded Teams meeting recap, identify the decisions, unresolved issues, and action items that connect directly to the Solar Generation Log, PPA Revenue Tracker, and Grid Curtailment Tracker sheets in RE_01_Plant_Performance.xlsx. Present the output as a RAG table with columns for Topic, What Was Said, Owner, Due Date, and Escalation Level.',
        'You are the Operations Director at Suria Angin Utilities Berhad. Using this Teams recap, draft follow-up actions for the teams responsible for the areas covered in RE_02_ESG_Reporting_Framework.docx and the Wind Farm Output sheet in RE_01_Plant_Performance.xlsx. Group the actions by workstream and include a success measure for each one.',
        'You are the CFO at Suria Angin Utilities Berhad. Using this Teams recap, extract every financial, compliance, or customer-impact figure that would help explain the trends in the PPA Revenue Tracker, O&M Cost Summary, and Grid Curtailment Tracker sheets in RE_01_Plant_Performance.xlsx. Present the result as a structured note with sections for Facts, Risks, Commitments, and Missing Information.'
      ], DESC_TEAMS),
      tool(T_NOTEBOOK, M365_LIC, M365_ACCT, [
        'You are the CEO at Suria Angin Utilities Berhad. Upload RE_01_Plant_Performance.xlsx, RE_02_ESG_Reporting_Framework.docx, RE_03_Asset_Management_Plan.docx to Copilot Notebook, set the instruction to synthesise across all files with citations, and ask for the 10-slide-equivalent story leadership needs right now. Require Notebook to reconcile the signals from the Solar Generation Log, PPA Revenue Tracker, and Grid Curtailment Tracker sheets in RE_01_Plant_Performance.xlsx with the commitments in RE_02_ESG_Reporting_Framework.docx and RE_03_Asset_Management_Plan.docx.',
        'You are the COO at Suria Angin Utilities Berhad. Upload RE_01_Plant_Performance.xlsx, RE_02_ESG_Reporting_Framework.docx, RE_03_Asset_Management_Plan.docx to Copilot Notebook and ask whether the priorities implied by the Wind Farm Output and O&M Cost Summary sheets in RE_01_Plant_Performance.xlsx are still realistic given the risk picture in the Grid Curtailment Tracker sheet. Require a RAG table with columns for Priority, Evidence, Risk to Delivery, and Recommendation, all with citations.',
        'You are the Board Liaison at Suria Angin Utilities Berhad. Upload RE_01_Plant_Performance.xlsx, RE_02_ESG_Reporting_Framework.docx, RE_03_Asset_Management_Plan.docx to Copilot Notebook and ask for the contradictions management must resolve before the next review, especially where operational ambition, control capability, and financial reality do not line up. Request a concise answer with sections for Contradictions, Questions Directors Will Ask, and Pre-Reads to Send.'
      ], DESC_NOTEBOOK),
      tool(T_COWORK, M365_LIC, M365_ACCT, [
        'You are the COO at Suria Angin Utilities Berhad. Do all of the following autonomously: create a recovery action plan grounded in the Solar Generation Log, PPA Revenue Tracker, and Grid Curtailment Tracker sheets in RE_01_Plant_Performance.xlsx; save it to OneDrive; email it to Asset management, finance, and ESG leaders; and schedule a 45-minute review meeting for next week. Make the plan easy to track with RAG status and owner-by-owner accountability.',
        'You are the Chief of Staff at Suria Angin Utilities Berhad. Do all of the following autonomously: turn the main obligations from RE_02_ESG_Reporting_Framework.docx and the priorities from RE_03_Asset_Management_Plan.docx into a working checklist, save it in OneDrive, email the checklist to the accountable leaders, and create calendar reminders for each major milestone. Keep the wording clear enough that teams can act without a second briefing.'
      ], DESC_COWORK),
      tool(T_EDIT_COPILOT, M365_LIC, M365_ACCT, [
        'You are the Company Secretary at Suria Angin Utilities Berhad. Using RE_02_ESG_Reporting_Framework.docx in Word for the web, add an appendix titled Operating Escalation and RAG Governance Protocol and populate it with decision rights, escalation thresholds, evidence requirements, and sign-off owners that mirror the issues visible in the Grid Curtailment Tracker and PPA Revenue Tracker sheets in RE_01_Plant_Performance.xlsx. Keep the style consistent with the existing document.',
        'You are the Performance Manager at Suria Angin Utilities Berhad. Using RE_01_Plant_Performance.xlsx in Excel for the web, create a new worksheet called Leadership Recovery Tracker that combines the Solar Generation Log, PPA Revenue Tracker, O&M Cost Summary, and Grid Curtailment Tracker sheets into a single view with owner, due date, expected impact, and live RAG status. Reorder the layout so the Red issues appear first and add formulas that refresh the summary automatically.'
      ], DESC_EDIT_COPILOT),
      tool(T_WORD_AGT, M365_LIC, M365_ACCT, [
        'You are the Knowledge Manager at Suria Angin Utilities Berhad. Open RE_02_ESG_Reporting_Framework.docx in Word for Web and create an agent called Renewables ESG Navigator. Describe it as an assistant that answers questions about the policies, thresholds, and escalation rules that matter when the Grid Curtailment Tracker sheet and the PPA Revenue Tracker sheet in RE_01_Plant_Performance.xlsx start to move against plan, then share it with the core leadership team.',
        'You are the COO at Suria Angin Utilities Berhad. Demo the Renewables ESG Navigator agent by asking: Curtailment at one solar site is above threshold and O&M cost inflation is eroding PPA value. What should the asset manager escalate first, what evidence belongs in the ESG framework, and what options should be discussed with TNB or PLN counterparts? Show how the answer cites the source document and gives a clear next step.'
      ], DESC_WORD_AGT),
      tool(T_PPT_AGT, M365_LIC, M365_ACCT, [
        'You are the Chief of Staff at Suria Angin Utilities Berhad. Create the leadership deck in PowerPoint for Web, then create an agent called Generation Review Board Bot that helps executives find the right slide, chart, and message quickly. Make sure it can answer questions grounded in the Solar Generation Log, PPA Revenue Tracker, and Grid Curtailment Tracker sheets in RE_01_Plant_Performance.xlsx.',
        'You are the CFO at Suria Angin Utilities Berhad. Demo the Generation Review Board Bot agent by asking which Red issue needs leadership attention first, what slide supports that answer, and what decision should be taken this week. Keep the response short enough to use in a live meeting.'
      ], DESC_PPT_AGT),
      tool(T_XL_AGT, M365_LIC, M365_ACCT, [
        'You are the Data Product Owner at Suria Angin Utilities Berhad. Open RE_01_Plant_Performance.xlsx in Excel for Web and create an agent called Renewables Portfolio Q&A. Describe it as an assistant that answers plain-English questions about the Solar Generation Log, Wind Farm Output, PPA Revenue Tracker, O&M Cost Summary, and Grid Curtailment Tracker sheets and share it with the teams that need faster insight.',
        'You are the COO at Suria Angin Utilities Berhad. Demo the Renewables Portfolio Q&A agent by asking which plant or site is currently Red, what is driving the status, and what leading indicator should be watched next. Then ask for the one figure from the workbook that leadership should remember before the next review.'
      ], DESC_XL_AGT),
      tool(T_BUILDER, M365_LIC, M365_ACCT, [
        'You are the Digital Transformation Lead at Suria Angin Utilities Berhad. Go to copilotstudio.microsoft.com, create a new agent called Suria Angin Asset Assistant, use RE_01_Plant_Performance.xlsx, RE_02_ESG_Reporting_Framework.docx, RE_03_Asset_Management_Plan.docx as the knowledge sources, and configure topics for Curtailment, PPA Value, ESG Reporting, O&M Control. Publish it to Teams with instructions that it should answer in a concise, evidence-based way and surface a clear escalation path when users ask high-risk questions.',
        'You are the Operations Director at Suria Angin Utilities Berhad. Demo the Suria Angin Asset Assistant agent by asking: Curtailment at one solar site is above threshold and O&M cost inflation is eroding PPA value. What should the asset manager escalate first, what evidence belongs in the ESG framework, and what options should be discussed with TNB or PLN counterparts? Show how the agent responds with the relevant file, the recommended action, and the owner who should take the next step.'
      ], DESC_BUILDER),
    ],
    companyID='PT Suria Angin Energi Tbk',
    taglineID='PLN dan Kementerian ESDM menekan saat curtailment 8.6% dan biaya O&M naik 14%.'),

# ── INDUSTRIAL MANUFACTURING ───────────────────────────────────────────────────────
ind('industrial-manufacturing', 'manufacturing', 'Industrial Manufacturing', '⚙️', '#263238', '#37474F',
    'Maju Teknika Industries Berhad',
    'MITI and key customers are watching as OEE stalls at 68% and rejects rise to 4.9%.',
    'Maju Teknika Industries Berhad operates precision component and sub-assembly plants in Nilai and Batu Kawan, supplying automotive, electronics, and industrial OEM customers. The Line OEE Dashboard shows network OEE stuck at 68%, well below the 75% recovery target approved at the start of the year. Quality Reject Log indicates defect rates have risen to 4.9%, with rework concentrated in two high-volume customer programmes. Production Plan vs Actual shows chronic shortfalls on weekend shifts, while Raw Material Cost Tracker captures continuing volatility in resin, copper, and imported machining consumables. Customer Order Fulfillment has slipped to 91% OTIF, raising the risk of penalties and allocation losses on the next sourcing round. MITI incentive reporting, DOSH workplace safety discipline, and SIRIM quality expectations all intersect with the operating reset described in MFG_03_Lean_Manufacturing_Guide.docx and the controls documented in MFG_02_Quality_Management_System.docx. The Indonesian affiliate is also under pressure to mirror the same corrective actions quickly if shared customers escalate regionally.',
    [
        'MFG_01_Production_Metrics.xlsx',
        'MFG_02_Quality_Management_System.docx',
        'MFG_03_Lean_Manufacturing_Guide.docx'
    ],
    [
      tool(T_CHAT, FREE_LIC, FREE_ACCT, [
        'You are the COO at Maju Teknika Industries Berhad. Using the Line OEE Dashboard, Quality Reject Log, Raw Material Cost Tracker, and Production Plan vs Actual sheets in MFG_01_Production_Metrics.xlsx, prepare a one-page operating diagnostic that explains why productivity stagnation and quality and delivery erosion are worsening at the same time. Present the answer as a RAG table with columns for Issue, Evidence from Sheet, Likely Root Cause, and 30-Day Action.',
        'You are the Chief Strategy Officer at Maju Teknika Industries Berhad. Using MFG_02_Quality_Management_System.docx, MFG_03_Lean_Manufacturing_Guide.docx, and the Customer Order Fulfillment sheet in MFG_01_Production_Metrics.xlsx, identify the 5 decisions management must make before the next executive review so that growth ambitions do not outpace control discipline. Present the answer as a prioritised table with columns for Decision, Why Now, Evidence Source, and Consequence if Deferred.',
        'You are the Head of Corporate Affairs at Maju Teknika Industries Berhad. Using the trends implied by the Line OEE Dashboard, Raw Material Cost Tracker, and Production Plan vs Actual sheets in MFG_01_Production_Metrics.xlsx, draft a stakeholder communication map covering the Board, regulators, frontline teams, and external partners. Present the answer as a RAG table with columns for Audience, Key Message, Timing, and Communication Risk.'
      ]),
      tool(T_RESEARCHER, FREE_LIC, FREE_ACCT, [
        'You are the Strategy Director at Maju Teknika Industries Berhad. Research how comparable organisations in this sector responded when productivity stagnation became visible in operating data like the Line OEE Dashboard and Raw Material Cost Tracker sheets in MFG_01_Production_Metrics.xlsx. Present the answer as a table with columns for Organisation, Trigger, Intervention, Measured Outcome, and Relevance to Maju Teknika Industries Berhad. Flag any claim that could not be independently verified.',
        'You are the Compliance Director at Maju Teknika Industries Berhad. Research the latest guidance, enforcement themes, and supervisory expectations relevant to MITI, DOSH, and SIRIM and the affiliated Indonesian context of regional customer and plant leadership, then link them to the control areas implied by MFG_02_Quality_Management_System.docx and the Production Plan vs Actual sheet in MFG_01_Production_Metrics.xlsx. Present the answer as a RAG table with columns for Requirement, Malaysia Context, Indonesia Context, Practical Impact, and Immediate Management Action. Flag any claim that could not be independently verified.',
        'You are the CEO at Maju Teknika Industries Berhad. Research three recent sector benchmarks on how peers balanced short-term recovery with longer-term priorities when facing quality and delivery erosion, using the tension visible between the Quality Reject Log and Customer Order Fulfillment sheets in MFG_01_Production_Metrics.xlsx as the framing context. Present the answer as a table with columns for Peer, What They Changed, Time to Impact, Reported Result, and Lesson for Maju Teknika Industries Berhad. Flag any claim that could not be independently verified.'
      ], DESC_RESEARCHER),
      tool(T_ANALYST, M365_LIC, M365_ACCT, [
        'You are the Head of FP&A at Maju Teknika Industries Berhad. Upload MFG_01_Production_Metrics.xlsx to Analyst and use the Line OEE Dashboard, Quality Reject Log, Raw Material Cost Tracker, and Production Plan vs Actual sheets to identify which line or plants are driving the largest share of productivity stagnation and quality and delivery erosion. Present the output as a RAG table with columns for Line Or Plant, Performance Signal, Financial Impact, Control Risk, and Recommended Owner.',
        'You are the CFO at Maju Teknika Industries Berhad. Upload MFG_01_Production_Metrics.xlsx to Analyst and quantify the revenue, margin, or cash exposure linked to the patterns in the Raw Material Cost Tracker, Customer Order Fulfillment, and Production Plan vs Actual sheets, then show where management should intervene first. Present the answer as a ranked table and include one chart that makes the biggest pressure point obvious.',
        'You are the Operations Director at Maju Teknika Industries Berhad. Upload MFG_01_Production_Metrics.xlsx to Analyst and build a 3-scenario view for the next two quarters using the Line OEE Dashboard, Quality Reject Log, Raw Material Cost Tracker, and Customer Order Fulfillment sheets: recover quickly, stabilise slowly, or deteriorate further. Present the result as a RAG table with threshold assumptions, earliest warning sign, and the action that should be triggered in each scenario.'
      ], DESC_ANALYST),
      tool(T_EXCEL, M365_LIC, M365_ACCT, [
        'You are the Business Planning Manager at Maju Teknika Industries Berhad. Using the Line OEE Dashboard, Quality Reject Log, Raw Material Cost Tracker, and Production Plan vs Actual sheets in this workbook, create a new worksheet called Executive RAG Dashboard that summarises the top operating and control risks by line or plant. Add conditional formatting so leaders can instantly see Red, Amber, and Green status plus the numeric driver behind each status.',
        'You are the Performance Manager at Maju Teknika Industries Berhad. Using the Customer Order Fulfillment, Raw Material Cost Tracker, and Production Plan vs Actual sheets in MFG_01_Production_Metrics.xlsx, create a new worksheet called Intervention Tracker that logs the top 10 corrective actions, the accountable owner, the due date, the expected benefit, and the latest status. Include formulas that highlight overdue actions in red and roll up the count of open Reds at the top of the sheet.',
        "You are the Finance Transformation Lead at Maju Teknika Industries Berhad. Using the Line OEE Dashboard, Quality Reject Log, and Raw Material Cost Tracker sheets in MFG_01_Production_Metrics.xlsx, build a sensitivity model on a new worksheet that shows how small changes in operating throughput, quality or compliance performance, and unit economics would change the overall outcome. Present the result as an easy-to-read decision table that management can use in tomorrow's review."
      ]),
      tool(T_WORD, M365_LIC, M365_ACCT, [
        'You are the Company Secretary at Maju Teknika Industries Berhad. Using MFG_02_Quality_Management_System.docx, MFG_03_Lean_Manufacturing_Guide.docx, and the evidence implied by the Line OEE Dashboard, Raw Material Cost Tracker, and Production Plan vs Actual sheets in MFG_01_Production_Metrics.xlsx, draft a 2-page Board paper on the current situation, the main risks, and the governance actions required in the next 30 days. Start with a short RAG summary and then move into decisions, owners, and timing.',
        'You are the Head of Internal Audit at Maju Teknika Industries Berhad. Using MFG_02_Quality_Management_System.docx and the pressure points visible in the Production Plan vs Actual and Raw Material Cost Tracker sheets in MFG_01_Production_Metrics.xlsx, draft a control-gap memorandum that identifies where process design and frontline execution are drifting apart. Present the core findings as a table with columns for Control Area, Current Gap, Risk if Unresolved, and Proposed Remediation.',
        'You are the CEO at Maju Teknika Industries Berhad. Using MFG_03_Lean_Manufacturing_Guide.docx, the Line OEE Dashboard sheet, and the Customer Order Fulfillment sheet in MFG_01_Production_Metrics.xlsx, draft a one-page management note that explains what can still be delivered this year, what must be reset, and how leadership should talk about the change in priorities. Keep the tone candid, steady, and evidence-based.'
      ]),
      tool(T_PPT, M365_LIC, M365_ACCT, [
        'You are the Chief of Staff at Maju Teknika Industries Berhad. Create a 6-slide executive deck using MFG_01_Production_Metrics.xlsx, MFG_02_Quality_Management_System.docx, and MFG_03_Lean_Manufacturing_Guide.docx as the source context, covering current performance, the root causes behind productivity stagnation and quality and delivery erosion, the top Red risks, the first 90-day actions, and the decisions required from leadership. Give each slide a headline that states the message, not just the topic.',
        'You are the CFO at Maju Teknika Industries Berhad. Create a 5-slide update deck for leadership that uses the Raw Material Cost Tracker, Customer Order Fulfillment, and Production Plan vs Actual sheets in MFG_01_Production_Metrics.xlsx to show where financial exposure is concentrated and how quickly it can be reduced. Include speaker notes that explain the Red issues in plain language for a non-technical audience.',
        'You are the Strategy Director at Maju Teknika Industries Berhad. Create a single summary slide that links the signals in the Line OEE Dashboard, Quality Reject Log, and Production Plan vs Actual sheets in MFG_01_Production_Metrics.xlsx to the priorities in MFG_03_Lean_Manufacturing_Guide.docx. Present it as a RAG matrix with one sentence of management action beside each Red item.'
      ]),
      tool(T_OUTLOOK, M365_LIC, M365_ACCT, [
        'You are the Regulatory Affairs Lead at Maju Teknika Industries Berhad. Draft an email to the relevant authorities and senior internal stakeholders that acknowledges the current pressure areas indicated by the Production Plan vs Actual sheet in MFG_01_Production_Metrics.xlsx, outlines the corrective steps already under way, and requests alignment on the next review checkpoint. Keep the tone factual, controlled, and suitable for scrutiny by MITI, DOSH, and SIRIM and regional customer and plant leadership counterparts.',
        'You are the COO at Maju Teknika Industries Berhad. Draft an internal email to Plant, quality, and supply-chain leaders summarising the top three risks shown in the Line OEE Dashboard, Raw Material Cost Tracker, and Production Plan vs Actual sheets in MFG_01_Production_Metrics.xlsx, the required actions this week, and the consequences of delay. End with a bullet list titled What I need from you by Friday.',
        'You are the Head of Stakeholder Management at Maju Teknika Industries Berhad. Draft an external-facing update that explains the current operating situation using plain language consistent with MFG_02_Quality_Management_System.docx and MFG_03_Lean_Manufacturing_Guide.docx, without overpromising outcomes or admitting fault. Use the evidence implied by the Customer Order Fulfillment and Raw Material Cost Tracker sheets in MFG_01_Production_Metrics.xlsx to keep the message disciplined.'
      ]),
      tool(T_TEAMS, M365_LIC, M365_ACCT, [
        'You are the Chief of Staff at Maju Teknika Industries Berhad. Using this recorded Teams meeting recap, identify the decisions, unresolved issues, and action items that connect directly to the Line OEE Dashboard, Raw Material Cost Tracker, and Production Plan vs Actual sheets in MFG_01_Production_Metrics.xlsx. Present the output as a RAG table with columns for Topic, What Was Said, Owner, Due Date, and Escalation Level.',
        'You are the Operations Director at Maju Teknika Industries Berhad. Using this Teams recap, draft follow-up actions for the teams responsible for the areas covered in MFG_02_Quality_Management_System.docx and the Quality Reject Log sheet in MFG_01_Production_Metrics.xlsx. Group the actions by workstream and include a success measure for each one.',
        'You are the CFO at Maju Teknika Industries Berhad. Using this Teams recap, extract every financial, compliance, or customer-impact figure that would help explain the trends in the Raw Material Cost Tracker, Customer Order Fulfillment, and Production Plan vs Actual sheets in MFG_01_Production_Metrics.xlsx. Present the result as a structured note with sections for Facts, Risks, Commitments, and Missing Information.'
      ], DESC_TEAMS),
      tool(T_NOTEBOOK, M365_LIC, M365_ACCT, [
        'You are the CEO at Maju Teknika Industries Berhad. Upload MFG_01_Production_Metrics.xlsx, MFG_02_Quality_Management_System.docx, MFG_03_Lean_Manufacturing_Guide.docx to Copilot Notebook, set the instruction to synthesise across all files with citations, and ask for the 10-slide-equivalent story leadership needs right now. Require Notebook to reconcile the signals from the Line OEE Dashboard, Raw Material Cost Tracker, and Production Plan vs Actual sheets in MFG_01_Production_Metrics.xlsx with the commitments in MFG_02_Quality_Management_System.docx and MFG_03_Lean_Manufacturing_Guide.docx.',
        'You are the COO at Maju Teknika Industries Berhad. Upload MFG_01_Production_Metrics.xlsx, MFG_02_Quality_Management_System.docx, MFG_03_Lean_Manufacturing_Guide.docx to Copilot Notebook and ask whether the priorities implied by the Quality Reject Log and Customer Order Fulfillment sheets in MFG_01_Production_Metrics.xlsx are still realistic given the risk picture in the Production Plan vs Actual sheet. Require a RAG table with columns for Priority, Evidence, Risk to Delivery, and Recommendation, all with citations.',
        'You are the Board Liaison at Maju Teknika Industries Berhad. Upload MFG_01_Production_Metrics.xlsx, MFG_02_Quality_Management_System.docx, MFG_03_Lean_Manufacturing_Guide.docx to Copilot Notebook and ask for the contradictions management must resolve before the next review, especially where operational ambition, control capability, and financial reality do not line up. Request a concise answer with sections for Contradictions, Questions Directors Will Ask, and Pre-Reads to Send.'
      ], DESC_NOTEBOOK),
      tool(T_COWORK, M365_LIC, M365_ACCT, [
        'You are the COO at Maju Teknika Industries Berhad. Do all of the following autonomously: create a recovery action plan grounded in the Line OEE Dashboard, Raw Material Cost Tracker, and Production Plan vs Actual sheets in MFG_01_Production_Metrics.xlsx; save it to OneDrive; email it to Plant, quality, and supply-chain leaders; and schedule a 45-minute review meeting for next week. Make the plan easy to track with RAG status and owner-by-owner accountability.',
        'You are the Chief of Staff at Maju Teknika Industries Berhad. Do all of the following autonomously: turn the main obligations from MFG_02_Quality_Management_System.docx and the priorities from MFG_03_Lean_Manufacturing_Guide.docx into a working checklist, save it in OneDrive, email the checklist to the accountable leaders, and create calendar reminders for each major milestone. Keep the wording clear enough that teams can act without a second briefing.'
      ], DESC_COWORK),
      tool(T_EDIT_COPILOT, M365_LIC, M365_ACCT, [
        'You are the Company Secretary at Maju Teknika Industries Berhad. Using MFG_02_Quality_Management_System.docx in Word for the web, add an appendix titled Operating Escalation and RAG Governance Protocol and populate it with decision rights, escalation thresholds, evidence requirements, and sign-off owners that mirror the issues visible in the Production Plan vs Actual and Raw Material Cost Tracker sheets in MFG_01_Production_Metrics.xlsx. Keep the style consistent with the existing document.',
        'You are the Performance Manager at Maju Teknika Industries Berhad. Using MFG_01_Production_Metrics.xlsx in Excel for the web, create a new worksheet called Leadership Recovery Tracker that combines the Line OEE Dashboard, Raw Material Cost Tracker, Customer Order Fulfillment, and Production Plan vs Actual sheets into a single view with owner, due date, expected impact, and live RAG status. Reorder the layout so the Red issues appear first and add formulas that refresh the summary automatically.'
      ], DESC_EDIT_COPILOT),
      tool(T_WORD_AGT, M365_LIC, M365_ACCT, [
        'You are the Knowledge Manager at Maju Teknika Industries Berhad. Open MFG_02_Quality_Management_System.docx in Word for Web and create an agent called Quality System Navigator. Describe it as an assistant that answers questions about the policies, thresholds, and escalation rules that matter when the Production Plan vs Actual sheet and the Raw Material Cost Tracker sheet in MFG_01_Production_Metrics.xlsx start to move against plan, then share it with the core leadership team.',
        'You are the COO at Maju Teknika Industries Berhad. Demo the Quality System Navigator agent by asking: One customer programme has low OEE, high rejects, and missed deliveries in the same month. What should the plant manager escalate first, which quality-system controls apply, and what evidence from the workbook should be used in the next customer review? Show how the answer cites the source document and gives a clear next step.'
      ], DESC_WORD_AGT),
      tool(T_PPT_AGT, M365_LIC, M365_ACCT, [
        'You are the Chief of Staff at Maju Teknika Industries Berhad. Create the leadership deck in PowerPoint for Web, then create an agent called Operations Recovery Board Bot that helps executives find the right slide, chart, and message quickly. Make sure it can answer questions grounded in the Line OEE Dashboard, Raw Material Cost Tracker, and Production Plan vs Actual sheets in MFG_01_Production_Metrics.xlsx.',
        'You are the CFO at Maju Teknika Industries Berhad. Demo the Operations Recovery Board Bot agent by asking which Red issue needs leadership attention first, what slide supports that answer, and what decision should be taken this week. Keep the response short enough to use in a live meeting.'
      ], DESC_PPT_AGT),
      tool(T_XL_AGT, M365_LIC, M365_ACCT, [
        'You are the Data Product Owner at Maju Teknika Industries Berhad. Open MFG_01_Production_Metrics.xlsx in Excel for Web and create an agent called Plant Performance Q&A. Describe it as an assistant that answers plain-English questions about the Line OEE Dashboard, Quality Reject Log, Raw Material Cost Tracker, Customer Order Fulfillment, and Production Plan vs Actual sheets and share it with the teams that need faster insight.',
        'You are the COO at Maju Teknika Industries Berhad. Demo the Plant Performance Q&A agent by asking which line or plant is currently Red, what is driving the status, and what leading indicator should be watched next. Then ask for the one figure from the workbook that leadership should remember before the next review.'
      ], DESC_XL_AGT),
      tool(T_BUILDER, M365_LIC, M365_ACCT, [
        'You are the Digital Transformation Lead at Maju Teknika Industries Berhad. Go to copilotstudio.microsoft.com, create a new agent called Maju Teknika Operations Assistant, use MFG_01_Production_Metrics.xlsx, MFG_02_Quality_Management_System.docx, MFG_03_Lean_Manufacturing_Guide.docx as the knowledge sources, and configure topics for OEE Recovery, Quality Loss, Order Fulfilment, Lean Actions. Publish it to Teams with instructions that it should answer in a concise, evidence-based way and surface a clear escalation path when users ask high-risk questions.',
        'You are the Operations Director at Maju Teknika Industries Berhad. Demo the Maju Teknika Operations Assistant agent by asking: One customer programme has low OEE, high rejects, and missed deliveries in the same month. What should the plant manager escalate first, which quality-system controls apply, and what evidence from the workbook should be used in the next customer review? Show how the agent responds with the relevant file, the recommended action, and the owner who should take the next step.'
      ], DESC_BUILDER),
    ],
    companyID='PT Maju Teknika Industri Tbk',
    taglineID='Pelanggan utama menekan saat OEE 68% dan reject rate naik ke 4.9%.'),

]

print(f"Batch 4 written: {len(INDUSTRIES_4)} entries")
