
import sys; sys.path.insert(0,'.')
from util import *

# Based on Contoso Tobacco & Wellness Copilot Immersion
# https://steffiyappy.github.io/contoso-tobacco-wellness-demo/
# Persona: Pak Hendra Susanto, GM Indonesia
# Scenario: Quarterly Country Review for Regional Office — stick volumes by
# brand, MT/GT coverage, CHT excise compliance, FY26 ginseng-line launch.
INDUSTRIES_14 = []

INDUSTRIES_14.append(ind(
    'tobacco-wellness', 'sec-tobacco-wellness', 'Tobacco & Wellness', '🍃', '#B91C1C', '#7F1D1D',
    'Contoso Tobacco & Wellness',
    'Quarterly Country Review in 48 hours — stick volumes by brand, MT/GT coverage, CHT compliance, ginseng-line launch readiness.',
    "Contoso Tobacco & Wellness (CTW) is a multi-brand Indonesian tobacco manufacturer and health-functional-foods operator (Korean Red Ginseng line in launch). The local OpCo runs 1 manufacturing plant at Karawang, six active cigarette brands across Premium/Mid-tier/Mass, and a new ginseng SKU portfolio in BPOM filing for Q4 FY26 launch. Volume YTD ~1.85 billion sticks; Premium Brand Share 6.4% (+0.6pt YoY); Active Outlet Coverage 78% vs 82% target; CHT (excise) compliance 99.4%; Karawang plant yield slipping in 2 lines. The Regional Office Country Review is in 48 hours and the GM needs a defensible briefing pack, FY27 CHT (excise) tariff-step response, brand-by-brand price ladder, distributor communications, and a ginseng-launch readiness review. Real-world reference frame: peers include KTNG Indonesia, HM Sampoerna (PMI), Gudang Garam, Djarum, Bentoel (BAT Indonesia), Wismilak, Nojorono. Regulators in scope: Bea Cukai (Customs/Excise — CHT, pita-cukai), BPOM (food/health products), MoH (PP 109/2012 packaging & advertising), LPPOM-MUI (halal certification for the wellness line).",
    ['01 Contoso_Market_Brief.xlsx',
     '02 Contoso_KPI_Dashboard.xlsx',
     '03 Contoso_Mail_Merge_Recipients.xlsx',
     '04 Contoso_Brand_Guidelines.docx',
     '05 Contoso_Strategic_Memo.docx',
     '06 Contoso_Merger_Discussion_Transcript.docx',
     'samples/CVs/ (12 candidate CVs — Trade Marketing & Distribution Manager)'],
    [
      # ── Researcher · Daily Briefing + Market Intelligence (Critique + Model Council) ─
      tool(T_RESEARCHER, M365_LIC, M365_ACCT, [
        {'instr':'Open `m365.cloud.microsoft/chat` > **Researcher** (Auto = Critique). Paste the prompt below — Researcher draws on inbox, calendar, Teams chats, and recent files to produce a one-screen GM briefing.',
         'prompt':"Create a daily briefing for the GM Indonesia at Contoso Tobacco & Wellness, from emails, messages, documents and meetings. Use your understanding of brand performance, MT/GT coverage, CHT compliance, and the FY26 ginseng-line launch to decide what is relevant. Sections: (1) short intro paragraph — what a chief of staff would say to greet me; (2) Key updates since yesterday (info that impacts my day); (3) Suggested tasks for today (cross-check none already done); (4) Unread email threads from the past week that likely need my reply — prioritise where I am on To/CC, @mentioned, or where requests/deadlines/leadership/customers are at stake; exclude automated mail; draft replies for the urgent ones; if none, say so; (5) Meeting prep for today as a table — Meeting (time, title, organiser), Topic Overview, Suggested Preparations. Header: 'Daily briefing — <Day, Date>'. Sub-header: timestamp of generation. Use only explicitly stated facts; no speculation. If a section has no data, state that."},
        {'instr':'Stay in the same Researcher Critique session. Paste the prompt below to scan the Indonesia tobacco manufacturing & health-functional-foods landscape.',
         'prompt':"Research the Tobacco Manufacturing & Health Functional Foods sector in Indonesia. Benchmark these companies: KTNG Indonesia, HM Sampoerna (Philip Morris), Gudang Garam, Djarum, Bentoel (BAT Indonesia), Wismilak, Nojorono. For each one, compare market share, FY25 revenue growth, EBITDA margin, strategic focus, digital maturity, and recent material moves (M&A, capex, new contracts, regulation). Include 2024–2028 market sizing with the three main growth drivers. Cite every source. Flag any section where the evidence is thin."},
        {'instr':'Switch the Researcher model picker to **Model Council** (GPT and Claude reason in parallel). Paste the prompt below to stress-test the strategic question.',
         'prompt':"Model Council — for GM Indonesia at Contoso Tobacco & Wellness: what are the three highest-impact strategic moves we should make in the next 12 months in the Indonesian tobacco manufacturing & health-functional-foods sector, given the peer benchmark above? For each move: rationale, evidence (cited), main risk, and a 90-day starter action. Show me where the models agree, where they disagree, and which one I should trust on each move."}
      ], DESC_RESEARCHER,
      promptsID=[
        {'instr':'Buka `m365.cloud.microsoft/chat` > **Researcher** (Auto = Critique). Tempelkan prompt di bawah — Researcher menarik dari inbox, kalender, chat Teams, dan berkas terbaru untuk menyajikan briefing satu-layar Direktur Utama.',
         'prompt':"Susun briefing harian untuk Direktur Utama Indonesia di Contoso Tobacco & Wellness, dari email, pesan, dokumen dan rapat. Gunakan pemahaman tentang kinerja merek, cakupan MT/GT, kepatuhan CHT, dan peluncuran lini ginseng FY26 untuk menentukan yang relevan. Bagian: (1) paragraf pembuka singkat — seperti yang akan disampaikan kepala staf di pagi hari; (2) Update penting sejak kemarin (info yang memengaruhi hari saya); (3) Tugas yang disarankan untuk hari ini (cek silang belum ada yang selesai); (4) Thread email belum dibaca minggu lalu yang kemungkinan perlu balasan — prioritaskan saat saya berada di To/CC, @mention, atau ketika ada permintaan/tenggat/pimpinan/pelanggan; kecualikan email otomatis; siapkan draf balasan untuk yang mendesak; jika tidak ada, sebutkan; (5) Persiapan rapat hari ini dalam tabel — Rapat (jam, judul, penyelenggara), Ringkasan Topik, Persiapan yang Disarankan. Header: 'Briefing harian — <Hari, Tanggal>'. Sub-header: timestamp pembuatan. Gunakan hanya fakta yang dinyatakan eksplisit; tanpa spekulasi. Jika ada bagian tanpa data, sebutkan."},
        {'instr':'Tetap di sesi Researcher Critique yang sama. Tempelkan prompt di bawah untuk memindai lanskap manufaktur tembakau & pangan fungsional kesehatan Indonesia.',
         'prompt':"Teliti sektor Manufaktur Tembakau & Pangan Fungsional Kesehatan di Indonesia. Benchmark perusahaan-perusahaan ini: KTNG Indonesia, HM Sampoerna (Philip Morris), Gudang Garam, Djarum, Bentoel (BAT Indonesia), Wismilak, Nojorono. Untuk masing-masing, bandingkan pangsa pasar, pertumbuhan pendapatan FY25, margin EBITDA, fokus strategis, kematangan digital, dan langkah material terkini (M&A, capex, kontrak baru, regulasi). Sertakan ukuran pasar 2024–2028 dengan tiga pendorong pertumbuhan utama. Sertakan kutipan setiap sumber. Tandai bagian yang buktinya tipis."},
        {'instr':'Ubah pemilih model Researcher menjadi **Model Council** (GPT dan Claude bernalar paralel). Tempelkan prompt di bawah untuk stress-test pertanyaan strategis.',
         'prompt':"Model Council — untuk Direktur Utama Indonesia di Contoso Tobacco & Wellness: apa tiga langkah strategis berdampak terbesar yang harus kami ambil dalam 12 bulan ke depan di sektor manufaktur tembakau & pangan fungsional kesehatan Indonesia, mengingat benchmark peer di atas? Untuk setiap langkah: alasan, bukti (terkutip), risiko utama, dan tindakan awal 90 hari. Tunjukkan di mana model sepakat, di mana berbeda, dan mana yang harus saya percaya untuk setiap langkah."}
      ],
      persona=['Pak Hendra Susanto','Pak Hendra Susanto','Pak Hendra Susanto'],
      personaID=['Pak Hendra Susanto','Pak Hendra Susanto','Pak Hendra Susanto']),

      # ── Analyst · Multi-perspective on the KPI workbook (GM / CFO / COO) ─
      tool(T_ANALYST, M365_LIC, M365_ACCT, [
        {'instr':'Open `m365.cloud.microsoft/chat` > **Agents** > **Analyst**. Upload `/02 Contoso_KPI_Dashboard.xlsx`. Paste the GM-lens prompt.',
         'prompt':"You are a data analyst for the GM Indonesia at Contoso Tobacco & Wellness. Based on the Monthly_KPIs sheet, model this scenario: what would full-year performance look like if the bottom-quartile locations on each KPI rose to the median in Q4? Show the end-of-year position vs FY26 target for each KPI (Stick Volume — All Brands M sticks, Premium Brand Share %, Active Outlet Coverage %, Plant Yield % at Karawang), before and after the uplift. Then identify the 3 highest-impact actions — where the smallest move lifts the group most."},
        {'instr':'Same workbook. Paste the CFO financial-risk prompt.',
         'prompt':"Same workbook. Now act as a CFO analyst. Run a correlation analysis across all KPIs over the 12 months. Which KPIs move together? Which KPIs lead vs lag? Identify the single early-warning KPI we should be tracking weekly. Then build a simple 3-month forecast for the top 2 financial KPIs, with a confidence band, and highlight the months where we are likely to breach the FY26 budget envelope."},
        {'instr':'Same workbook. Paste the COO operations prompt.',
         'prompt':"Same workbook. Now act as a COO analyst. For each location, compute a simple operational health score combining the KPIs into one number (0–100). Cluster locations into three groups: thriving, stable, at-risk. For each at-risk location, identify the two KPIs dragging the score down most. Recommend the single operational intervention with the highest expected score uplift, and the cost band (low/medium/high) to implement it."}
      ], DESC_ANALYST,
      promptsID=[
        {'instr':'Buka `m365.cloud.microsoft/chat` > **Agents** > **Analyst**. Unggah `/02 Contoso_KPI_Dashboard.xlsx`. Tempelkan prompt sudut pandang Direktur Utama.',
         'prompt':"Anda adalah data analyst untuk Direktur Utama Indonesia di Contoso Tobacco & Wellness. Berdasarkan sheet Monthly_KPIs, modelkan skenario ini: bagaimana kinerja setahun penuh jika lokasi kuartil terbawah pada tiap KPI naik ke median di Q4? Tunjukkan posisi akhir tahun vs target FY26 untuk tiap KPI (Volume Batang — Semua Merek M batang, Pangsa Merek Premium %, Cakupan Outlet Aktif %, Yield Pabrik % Karawang), sebelum dan sesudah uplift. Lalu identifikasi 3 tindakan paling berdampak — di mana langkah terkecil mengangkat grup paling banyak."},
        {'instr':'Workbook yang sama. Tempelkan prompt sudut pandang Direktur Keuangan.',
         'prompt':"Workbook yang sama. Sekarang bertindak sebagai analis Direktur Keuangan. Jalankan analisis korelasi lintas semua KPI selama 12 bulan. KPI mana yang bergerak bersama? KPI mana yang menjadi indikator awal vs tertinggal? Identifikasi satu KPI peringatan dini yang harus dipantau mingguan. Lalu bangun perkiraan 3 bulan sederhana untuk 2 KPI keuangan teratas, dengan rentang keyakinan, dan tandai bulan-bulan yang kemungkinan menembus amplop anggaran FY26."},
        {'instr':'Workbook yang sama. Tempelkan prompt sudut pandang Direktur Operasional.',
         'prompt':"Workbook yang sama. Sekarang bertindak sebagai analis Direktur Operasional. Untuk tiap lokasi, hitung skor kesehatan operasional sederhana yang menggabungkan KPI menjadi satu angka (0–100). Kelompokkan lokasi menjadi tiga grup: thriving, stable, at-risk. Untuk setiap lokasi at-risk, identifikasi dua KPI yang paling menarik skor turun. Rekomendasikan satu intervensi operasional dengan uplift skor terbesar yang diharapkan, dan rentang biaya (rendah/sedang/tinggi) untuk implementasi."}
      ],
      persona=['Hadar Caspit','Hadar Caspit','Hadar Caspit'],
      personaID=['Hadar Caspit','Hadar Caspit','Hadar Caspit']),

      # ── Excel · Power Hour (Chat / Edit / Plan) ─
      tool(T_EXCEL, M365_LIC, M365_ACCT, [
        {'instr':'Open `/02 Contoso_KPI_Dashboard.xlsx` in Excel for the Web. Open the **Copilot pane**. On the `Monthly_KPIs` tab, paste the Chat-mode prompt.',
         'prompt':"Analyse the Monthly_KPIs tab. For each KPI (Stick Volume — All Brands M sticks, Premium Brand Share %, Active Outlet Coverage %, Plant Yield % Karawang): identify the best and worst locations; detect any sustained declining trend (2+ months); flag the one-month outliers worth a phone call. Then compare against Targets_vs_Actual. Which KPI has the biggest gap to FY26 target, and which location is dragging it down the most? Show the result as a 2-line executive summary, then a RAG status table by location."},
        {'instr':'Switch the Copilot pane to **Edit** mode. Highlight the Status column on the `Targets_vs_Actual` tab. Paste the prompt below.',
         'prompt':"In this column, replace the emoji status with a one-word plain-text status (Green / Amber / Red) and apply conditional formatting with the matching colour. Do not change any other cells. Show me the diff first, before applying."},
        {'instr':'Switch the Copilot pane to **Plan** mode. Paste the prompt below — Copilot proposes a multi-step plan that you approve before any cell changes.',
         'prompt':"Plan: in a new sheet called 'Exec_View', build a pivot summary — one row per location, one column per KPI — showing the FY26 H2 average. Add a 'Trend' column showing up/flat/down vs FY26 H1 average. Highlight the worst quartile per KPI in red. Add a 2-sentence executive read-out at the very top. Show me the plan first. I will approve. Then execute."}
      ], DESC_EXCEL,
      promptsID=[
        {'instr':'Buka `/02 Contoso_KPI_Dashboard.xlsx` di Excel for the Web. Buka **panel Copilot**. Pada tab `Monthly_KPIs`, tempelkan prompt mode Chat.',
         'prompt':"Analisis tab Monthly_KPIs. Untuk tiap KPI (Volume Batang — Semua Merek M batang, Pangsa Merek Premium %, Cakupan Outlet Aktif %, Yield Pabrik % Karawang): identifikasi lokasi terbaik dan terburuk; deteksi tren penurunan berkelanjutan (2+ bulan); tandai outlier satu-bulan yang layak ditelepon. Lalu bandingkan dengan Targets_vs_Actual. KPI mana yang gap-nya terbesar ke target FY26, dan lokasi mana yang paling menariknya turun? Sajikan hasil sebagai ringkasan eksekutif 2 baris, lalu tabel status RAG per lokasi."},
        {'instr':'Ubah panel Copilot ke mode **Edit**. Sorot kolom Status pada tab `Targets_vs_Actual`. Tempelkan prompt di bawah.',
         'prompt':"Di kolom ini, ganti status emoji dengan status teks satu kata (Hijau / Kuning / Merah) dan terapkan conditional formatting dengan warna yang cocok. Jangan ubah sel lain. Tunjukkan diff dulu, sebelum diterapkan."},
        {'instr':'Ubah panel Copilot ke mode **Plan**. Tempelkan prompt di bawah — Copilot mengusulkan rencana multi-langkah yang Anda setujui sebelum perubahan sel apa pun.',
         'prompt':"Plan: di sheet baru bernama 'Exec_View', bangun ringkasan pivot — satu baris per lokasi, satu kolom per KPI — menunjukkan rata-rata H2 FY26. Tambahkan kolom 'Tren' menunjukkan naik/datar/turun vs rata-rata H1 FY26. Sorot kuartil terburuk per KPI dengan merah. Tambahkan baca-singkat eksekutif 2 kalimat di paling atas. Tunjukkan rencananya dulu. Saya akan menyetujui. Lalu eksekusi."}
      ],
      persona=['Pak Hendra Susanto','Pak Hendra Susanto','Pak Hendra Susanto'],
      personaID=['Pak Hendra Susanto','Pak Hendra Susanto','Pak Hendra Susanto']),

      # ── Word · 1-page GM brief + meeting minutes template + auto-fill from transcript ─
      tool(T_WORD, M365_LIC, M365_ACCT, [
        {'instr':'In the Researcher market-intel report, click **Export** > **Convert to Word**. Open from OneDrive. In the Word Copilot pane, paste the prompt below.',
         'prompt':"Based on the content of this document, draft a 1-page brief for the GM Indonesia at Contoso Tobacco & Wellness. Structure: (1) Market headline — 2 sentences, 1 number; (2) 3 competitor moves we must track; (3) 3 implications for Contoso Tobacco & Wellness in the next 90 days; (4) 1 question to put to the Executive Committee. Tone: direct, board-ready, no jargon. Max 350 words. Use [PLACEHOLDER] for anything not confirmed in the research. End with assumptions made and one open question."},
        {'instr':'Open a blank Word doc. Click the Copilot icon > **Draft with Copilot**. Paste the prompt below to create the corporate minutes template.',
         'prompt':"Create a professional, reusable meeting-minutes template for Contoso Tobacco & Wellness. The template should be clean, executive-ready, and easy to fill in after any internal meeting. Include: (1) Header block — Meeting title, Date & time, Location / Teams link, Meeting owner, Minute-taker; (2) Attendees (table: Name, Role, Present / Apologies); (3) Agenda items discussed (numbered list); (4) Key decisions taken (table: Decision, Decision owner, Effective date); (5) Action items (table: Action, Owner, Due date, Status); (6) Open questions / parked items (bullet list); (7) Risks & escalations raised (bullet list); (8) Next meeting (date, focus topics); (9) Distribution list. Use Contoso Tobacco & Wellness brand tone — direct, professional, no jargon. Add a 1-line footer: 'Confidential — internal use only.' Format it so it looks like a proper corporate template, not a chat reply."},
        {'instr':'Stay in the same Word doc. Reference the merger transcript with /, then paste the auto-fill prompt below.',
         'prompt':"Using the meeting-minutes template above, fill it in completely using the content of /06 Contoso_Merger_Discussion_Transcript.docx (or the Teams recap just generated for the Potential Merger meeting). Rules: use only facts explicitly stated in the source — no speculation, no invented attendees, no invented decisions; for every action item, name the owner and the due date exactly as agreed; if not stated, write [VERIFY] in that field; keep the executive tone — short, factual, neutral; at the very top, add a 3-line executive summary above the template; flag any sensitive merger-related items as 'CONFIDENTIAL — restricted distribution' in red at the section header."}
      ], DESC_WORD,
      promptsID=[
        {'instr':'Pada laporan riset pasar Researcher, klik **Export** > **Convert to Word**. Buka dari OneDrive. Di panel Copilot Word, tempelkan prompt di bawah.',
         'prompt':"Berdasarkan isi dokumen ini, susun ringkasan 1 halaman untuk Direktur Utama Indonesia di Contoso Tobacco & Wellness. Struktur: (1) Headline pasar — 2 kalimat, 1 angka; (2) 3 langkah kompetitor yang harus dilacak; (3) 3 implikasi untuk Contoso Tobacco & Wellness dalam 90 hari ke depan; (4) 1 pertanyaan yang akan diajukan ke Komite Eksekutif. Nada: lugas, siap-direksi, tanpa jargon. Maksimum 350 kata. Gunakan [PLACEHOLDER] untuk apa pun yang belum dikonfirmasi dalam riset. Akhiri dengan asumsi yang dibuat dan satu pertanyaan terbuka."},
        {'instr':'Buka dokumen Word kosong. Klik ikon Copilot > **Draft with Copilot**. Tempelkan prompt di bawah untuk membuat template notulensi korporat.',
         'prompt':"Buat template notulensi rapat profesional yang dapat dipakai ulang untuk Contoso Tobacco & Wellness. Template harus bersih, siap-eksekutif, dan mudah diisi setelah rapat internal mana pun. Sertakan: (1) Blok header — Judul Rapat, Tanggal & jam, Lokasi / tautan Teams, Pemilik rapat, Pencatat notulen; (2) Peserta (tabel: Nama, Peran, Hadir / Berhalangan); (3) Agenda yang dibahas (daftar bernomor); (4) Keputusan utama yang diambil (tabel: Keputusan, Pemilik keputusan, Tanggal berlaku); (5) Action items (tabel: Aksi, Pemilik, Tenggat, Status); (6) Pertanyaan terbuka / item ditahan (daftar bullet); (7) Risiko & eskalasi yang muncul (daftar bullet); (8) Rapat berikutnya (tanggal, topik fokus); (9) Daftar distribusi. Gunakan nada merek Contoso Tobacco & Wellness — lugas, profesional, tanpa jargon. Tambahkan footer 1 baris: 'Rahasia — penggunaan internal saja.' Format agar terlihat sebagai template korporat yang layak, bukan balasan chat."},
        {'instr':'Tetap di dokumen Word yang sama. Referensikan transcript merger dengan /, lalu tempelkan prompt auto-fill di bawah.',
         'prompt':"Menggunakan template notulensi di atas, isi sepenuhnya menggunakan isi /06 Contoso_Merger_Discussion_Transcript.docx (atau recap Teams yang baru dibuat untuk rapat Potential Merger). Aturan: hanya gunakan fakta yang dinyatakan eksplisit di sumber — tanpa spekulasi, tanpa peserta atau keputusan rekaan; untuk setiap action item, sebutkan pemilik dan tenggat persis seperti disepakati; jika tidak dinyatakan, tulis [VERIFIKASI] di field tersebut; pertahankan nada eksekutif — pendek, faktual, netral; di paling atas, tambahkan ringkasan eksekutif 3 baris di atas template; tandai item sensitif terkait merger sebagai 'RAHASIA — distribusi terbatas' merah pada header bagian."}
      ],
      persona=['Pak Hendra Susanto','Pak Hendra Susanto','Pak Hendra Susanto'],
      personaID=['Pak Hendra Susanto','Pak Hendra Susanto','Pak Hendra Susanto']),

      # ── PowerPoint · BCG/McKinsey style + digest incoming deck ─
      tool(T_PPT, M365_LIC, M365_ACCT, [
        {'instr':'Open a blank PowerPoint (start from your corporate template .potx if you have one). Open the Copilot pane. Type / to reference both source files. Paste the 8-slide brief.',
         'prompt':"Create an 8-slide FY26 Indonesia Country Strategy — Brand, Channel, Excise & Ginseng Launch deck for Contoso Tobacco & Wellness. Audience: GM Indonesia and the Operating Committee. Ground every slide on /05 Contoso_Strategic_Memo.docx and the KPI tables in /02 Contoso_KPI_Dashboard.xlsx. Use the corporate template that is currently applied — do not change fonts, colours, or master layouts. Apply the strict 'one message per slide' consulting style: (a) every slide title is an ACTION TITLE — a full sentence that IS the conclusion; (b) the body proves the title with exactly 3 supporting bullets OR one small evidence table — nothing else; (c) every slide has a source caption in 8pt grey at the bottom referencing the file and tab/page used; (d) max 30 words of body per slide, no decorative imagery. Slide structure: 1 Title — Contoso T&W · FY26 Indonesia Country Strategy · date; 2 Executive snapshot — single headline + 3-number callout + RAG; 3 Where we stand today — KPI scoreboard; 4 What is changing — top 3 market forces; 5 Our three FY26 H2 priorities — one priority per bullet, named owner; 6 Where we invest first — 90-day moves with cost & expected benefit; 7 Risks & mitigations — table risk, owner, status; 8 The ask — 1-page decision summary for the Operating Committee. Use [PLACEHOLDER] for any number not in the source files."},
        {'instr':'Run a self-critique pass on the deck. Paste the prompt below.',
         'prompt':"Act as a McKinsey engagement manager reviewing this deck against consulting best practice. For each slide: (1) score the action title 1–5 — if less than 5, rewrite it so it IS the conclusion (full sentence); (2) check that the body proves the title — flag any slide where title and body don't match; (3) check the 'so-what' — if the slide doesn't change a decision, mark it for deletion. Return a 1-page review note: slide-by-slide table, plus the single slide to cut, plus the single missing slide we should add. Then apply all the edits."},
        {'instr':'Open any deck recently sent to the GM. In the Copilot pane, paste the prompt below.',
         'prompt':"Summarise this presentation in 5 bullets. What is the single decision being asked of the audience? What are the 3 numbers I must remember? List the action items with owners and dates. Then list the top 3 questions the GM Indonesia should ask in the room."}
      ], DESC_PPT,
      promptsID=[
        {'instr':'Buka PowerPoint kosong (mulai dari template korporat .potx jika ada). Buka panel Copilot. Ketik / untuk mereferensikan kedua berkas sumber. Tempelkan brief 8-slide.',
         'prompt':"Buat deck 8-slide Strategi Negara Indonesia FY26 — Merek, Channel, Cukai & Peluncuran Ginseng untuk Contoso Tobacco & Wellness. Audiens: Direktur Utama Indonesia dan Komite Operasi. Grounding setiap slide pada /05 Contoso_Strategic_Memo.docx dan tabel KPI di /02 Contoso_KPI_Dashboard.xlsx. Gunakan template korporat yang aktif — jangan mengubah font, warna, atau master layout. Terapkan gaya konsultasi 'satu pesan per slide' yang ketat: (a) setiap judul slide adalah ACTION TITLE — satu kalimat penuh yang ADALAH kesimpulan; (b) body membuktikan judul dengan tepat 3 bullet pendukung ATAU satu tabel bukti kecil — tidak ada yang lain; (c) setiap slide memiliki caption sumber 8pt abu-abu di bawah merujuk berkas dan tab/halaman yang digunakan; (d) maks 30 kata body per slide, tanpa imageri dekoratif. Struktur slide: 1 Judul — Contoso T&W · Strategi Negara Indonesia FY26 · tanggal; 2 Snapshot eksekutif — satu headline + callout 3 angka + RAG; 3 Posisi saat ini — scoreboard KPI; 4 Apa yang berubah — 3 kekuatan pasar utama; 5 Tiga prioritas H2 FY26 — satu prioritas per bullet, pemilik bernama; 6 Di mana investasi pertama — langkah 90 hari dengan biaya & manfaat yang diharapkan; 7 Risiko & mitigasi — tabel risiko, pemilik, status; 8 The ask — ringkasan keputusan 1 halaman untuk Komite Operasi. Gunakan [PLACEHOLDER] untuk angka apa pun yang tidak ada di berkas sumber."},
        {'instr':'Jalankan pass kritik-diri pada deck. Tempelkan prompt di bawah.',
         'prompt':"Bertindak sebagai engagement manager McKinsey yang meninjau deck ini terhadap praktik terbaik konsultansi. Untuk setiap slide: (1) skor action title 1–5 — jika kurang dari 5, tulis ulang agar IA-NYA kesimpulan (kalimat penuh); (2) cek bahwa body membuktikan judul — tandai slide mana pun di mana judul dan body tidak cocok; (3) cek 'so-what' — jika slide tidak mengubah keputusan, tandai untuk dihapus. Kembalikan catatan tinjauan 1 halaman: tabel per-slide, ditambah satu slide untuk dipotong, ditambah satu slide hilang yang harus ditambahkan. Lalu terapkan semua edit."},
        {'instr':'Buka deck mana pun yang baru dikirim ke Direktur Utama. Di panel Copilot, tempelkan prompt di bawah.',
         'prompt':"Ringkas presentasi ini dalam 5 bullet. Apa satu keputusan yang diminta dari audiens? Apa 3 angka yang harus saya ingat? Daftarkan action items dengan pemilik dan tanggal. Lalu daftarkan 3 pertanyaan teratas yang harus diajukan Direktur Utama Indonesia di ruangan."}
      ],
      persona=['Pak Hendra Susanto','Pak Hendra Susanto','Pak Hendra Susanto'],
      personaID=['Pak Hendra Susanto','Pak Hendra Susanto','Pak Hendra Susanto']),

      # ── Teams · Recap of the Potential Merger meeting ─
      tool(T_TEAMS, M365_LIC, M365_ACCT, [
        {'instr':'Open Teams > Calendar > pick the past Potential Merger meeting (or use /06 Contoso_Merger_Discussion_Transcript.docx). Click the Recap tab. In the Copilot box at the top of the recap, paste the prompt below.',
         'prompt':"Recap this Potential Merger meeting for the GM Indonesia who could not stay for the whole session. Produce: (1) a 5-bullet executive summary of what was discussed; (2) the 3 decisions taken and who took them; (3) the 5 open action items with owner and due date; (4) the 3 topics that took the most time and why; (5) anyone who pushed back strongly and on what; (6) anything that was committed directly to me; (7) the 3 key unanswered questions we still need to resolve before the next meeting. Tone: factual, neutral, no speculation."}
      ], DESC_TEAMS,
      promptsID=[
        {'instr':'Buka Teams > Kalender > pilih rapat Potential Merger yang lalu (atau gunakan /06 Contoso_Merger_Discussion_Transcript.docx). Klik tab Recap. Di kotak Copilot di atas recap, tempelkan prompt di bawah.',
         'prompt':"Recap rapat Potential Merger ini untuk Direktur Utama Indonesia yang tidak dapat hadir penuh. Hasilkan: (1) ringkasan eksekutif 5 bullet tentang yang dibahas; (2) 3 keputusan yang diambil dan siapa yang mengambilnya; (3) 5 action items terbuka dengan pemilik dan tenggat; (4) 3 topik yang paling memakan waktu dan mengapa; (5) siapa yang menyangkal dengan kuat dan tentang apa; (6) apa pun yang dijanjikan langsung kepada saya; (7) 3 pertanyaan kunci yang belum terjawab yang masih perlu diselesaikan sebelum rapat berikutnya. Nada: faktual, netral, tanpa spekulasi."}
      ],
      persona=['Pak Hendra Susanto'],
      personaID=['Pak Hendra Susanto']),

      # ── Copilot Create · Indonesia Country Snapshot infographic ─
      tool(T_CREATE, M365_LIC, M365_ACCT, [
        {'instr':'Open `m365.cloud.microsoft/chat` > **Create** in the left sidebar (or type /create). Paste the prompt below.',
         'prompt':"Make a clean, premium one-page infographic poster called 'Indonesia Country Snapshot — Brand, Channel & Compliance, Q3 FY26'. Use our brand colours deep red and warm amber/gold on white, with small dark-grey for headings — a serious, regulator-friendly look (no playful illustrations of cigarettes; we are deliberately understated). Vertical, fits one A4 page, fill the entire page top to bottom. At the top, a big bold title 'INDONESIA COUNTRY SNAPSHOT — Q3 FY26', sub-line 'Brand · Channel · Compliance · Ginseng readiness · For the Regional Office Country Review'. Row of 4 big-number boxes: '1.85 billion sticks' Volume YTD all brands; '6.4%' Premium Brand Share (+0.6 pt YoY); '78%' Active Outlet Coverage (target 82%); '99.4%' CHT (Excise) Compliance Score. Section 'THE THREE COUNTRY PRIORITIES' with 3 cards side by side — Defend the premium tier; Close the coverage gap; Launch the ginseng line — each with 3-4 bullets. Small table 'Tier Compare' with rows Volume YoY, Share %, Average Price/pack, Distribution %, Recommended Action and columns Premium, Mid-tier, Mass-market, using coloured indicators (green/amber/red). Row of 3 icons with labels for 'Top regulatory & market risks': FY27 CHT step-up, PP 109/2012 packaging rules, plain-packaging discussion at MoH. Deep-red ribbon footer 'RECOMMENDATION: hold premium share, close the coverage gap, ship the ginseng line by Q4 — Country GM reviews weekly' with today's date on the right. Clean modern sans-serif, thin outline icons only, no clip-art, no images of products or people. Important: every section sized to fill the full A4 page, no large empty area at the bottom."}
      ], DESC_CREATE,
      promptsID=[
        {'instr':'Buka `m365.cloud.microsoft/chat` > **Create** di sidebar kiri (atau ketik /create). Tempelkan prompt di bawah.',
         'prompt':"Buat poster infografis satu-halaman premium yang bersih berjudul 'Snapshot Negara Indonesia — Merek, Channel & Kepatuhan, Q3 FY26'. Gunakan warna merek merah tua dan amber/emas hangat di atas putih, dengan abu-abu tua kecil untuk heading — tampilan serius, ramah regulator (tanpa ilustrasi rokok yang playful; kami sengaja understated). Vertikal, muat satu halaman A4, isi seluruh halaman dari atas ke bawah. Di atas, judul tebal besar 'SNAPSHOT NEGARA INDONESIA — Q3 FY26', sub-baris 'Merek · Channel · Kepatuhan · Kesiapan Ginseng · Untuk Country Review Kantor Regional'. Baris 4 kotak angka besar: '1,85 miliar batang' Volume YTD semua merek; '6,4%' Pangsa Merek Premium (+0,6 pt YoY); '78%' Cakupan Outlet Aktif (target 82%); '99,4%' Skor Kepatuhan CHT. Bagian 'TIGA PRIORITAS NEGARA' dengan 3 kartu bersebelahan — Pertahankan tier premium; Tutup gap cakupan; Luncurkan lini ginseng — masing-masing dengan 3-4 bullet. Tabel kecil 'Bandingkan Tier' dengan baris Volume YoY, Pangsa %, Harga Rata-rata/pak, Distribusi %, Tindakan Direkomendasikan dan kolom Premium, Mid-tier, Mass-market, menggunakan indikator berwarna (hijau/kuning/merah). Baris 3 ikon dengan label 'Risiko regulasi & pasar teratas': step-up CHT FY27, aturan kemasan PP 109/2012, diskusi plain-packaging di Kemenkes. Footer pita merah-tua 'REKOMENDASI: tahan pangsa premium, tutup gap cakupan, kirim lini ginseng pada Q4 — Country GM review mingguan' dengan tanggal hari ini di kanan. Sans-serif modern bersih, ikon outline tipis saja, tanpa clip-art, tanpa gambar produk atau orang. Penting: setiap bagian disesuaikan untuk mengisi seluruh halaman A4, tanpa area kosong besar di bawah."}
      ],
      persona=['Pak Hendra Susanto'],
      personaID=['Pak Hendra Susanto']),

      # ── Cowork · Quarter-end pack + personalised mail merge + CV screening ─
      tool(T_COWORK, FRONTIER_LIC, M365_ACCT, [
        {'instr':'Open Microsoft 365 Copilot Chat > switch to **Cowork**. Reference /02 Contoso_KPI_Dashboard.xlsx with /. Paste the quarter-close prompt.',
         'prompt':"Cowork — close the quarter for the GM Indonesia at Contoso Tobacco & Wellness. Use /02 Contoso_KPI_Dashboard.xlsx as the source of truth. Do all of the following, in order: (1) analyse Monthly_KPIs and Targets_vs_Actual — for each KPI identify best/worst locations and variance vs FY26 target; flag any Red locations; (2) draft a 1-page Word doc 'Contoso T&W Q-End GM Summary' — top 3 wins, top 3 issues, 90-day action plan with owners; save to OneDrive; (3) draft an executive email from the GM to the Operating Committee with headline + link to the Word doc; (4) schedule a 30-min Operating Committee review Wed next week 10:00 AM; (5) generate a self-contained HTML KPI dashboard 'Brand · Distribution · Excise Compliance Dashboard' — brand-coloured header band, 5 KPI scorecards with RAG icons, inline mini-table per location showing last 3 months' trend, 'Top issue' and 'Top action' callouts at the bottom, all CSS inline, no JS, mobile-friendly; save as Dashboard.html to OneDrive. Stop and confirm before sending the email or scheduling the meeting."},
        {'instr':'Stay in Cowork. Reference /03 Contoso_Mail_Merge_Recipients.xlsx and /04 Contoso_Brand_Guidelines.docx with /. Paste the cascade prompt.',
         'prompt':"Cowork — run a quarterly country-team cascade to 14 regional sales managers, plant and compliance leads for GM Indonesia at Contoso Tobacco & Wellness. Sources: /03 Contoso_Mail_Merge_Recipients.xlsx (14 rows: First Name, Full Name, Location, Role, Email, Performance Band, Key Highlight), /04 Contoso_Brand_Guidelines.docx (use the 'Approved GM Communications Template' exactly). For each row: (1) write a personal 180-word letter using the approved template — premium share, outlet coverage, CHT compliance, and one specific 30-day ask per region; tailor body to the Performance Band — Top Quartile: appreciative, ask them to mentor a neighbouring site; On Track: acknowledge progress + one specific stretch goal; Watch: direct, supportive, one specific 30-day improvement; (2) quote the recipient's Key Highlight verbatim in para 2; (3) sign off as Pak Hendra Susanto, GM Indonesia, Contoso Tobacco & Wellness; (4) create an Outlook DRAFT (do not send) to the address in Email column; subject '[First Name], a quick note on this quarter at [Location]'. When all 14 drafts are ready, give me a summary table: Recipient · Location · Band · Subject preview · Draft link. Stop and confirm before sending anything."},
        {'instr':'Stay in Cowork. Upload samples/CVs/ to a SharePoint library first (HR / Recruitment / Trade Marketing & Distribution Manager). Wait 2 min for Microsoft Graph indexing. Paste the CV-screening prompt.',
         'prompt':"Cowork — handle CV screening for the Trade Marketing & Distribution Manager role at Contoso Tobacco & Wellness. Source: SharePoint folder /HR/Recruitment/Contoso T&W Trade Marketing & Distribution Manager (12 CVs). Do all of the following: (1) review every CV; score each candidate 1–5 against FMCG distribution, outlet coverage growth, trade marketing; (2) build a ranked shortlist (top 5) with name · current company · 3 quoted evidence bullets · risks/gaps to test in interview; (3) build a 'second look' list (next 3) and a rejected list (one line of reasoning each); (4) for each top-5 candidate, draft a personalised interview-prep brief for the hiring manager — 3 questions to ask and what kind of answer opens a 'yes'; (5) draft (DO NOT send) an introductory email to candidate #1 inviting them to a screening call; save as Outlook draft. Flag anything unclear with [VERIFY]. Do not fabricate qualifications. Stop and confirm before sending any email."}
      ], DESC_COWORK,
      promptsID=[
        {'instr':'Buka Microsoft 365 Copilot Chat > beralih ke **Cowork**. Referensikan /02 Contoso_KPI_Dashboard.xlsx dengan /. Tempelkan prompt quarter-close.',
         'prompt':"Cowork — tutup kuartal untuk Direktur Utama Indonesia di Contoso Tobacco & Wellness. Gunakan /02 Contoso_KPI_Dashboard.xlsx sebagai sumber kebenaran. Lakukan semua hal berikut, berurutan: (1) analisis Monthly_KPIs dan Targets_vs_Actual — untuk tiap KPI identifikasi lokasi terbaik/terburuk dan selisih vs target FY26; tandai lokasi Merah; (2) buat doc Word 1 halaman 'Ringkasan Tutup Kuartal GM Contoso T&W' — 3 kemenangan teratas, 3 isu teratas, rencana aksi 90-hari dengan pemilik; simpan ke OneDrive; (3) susun email eksekutif dari Direktur Utama ke Komite Operasi dengan headline + tautan ke doc Word; (4) jadwalkan review Komite Operasi 30 menit Rabu minggu depan jam 10:00; (5) buat dashboard HTML KPI mandiri 'Dashboard Merek · Distribusi · Kepatuhan Cukai' — pita header berwarna merek, 5 KPI scorecard dengan ikon RAG, mini-tabel inline per lokasi menunjukkan tren 3 bulan terakhir, callout 'Isu Teratas' dan 'Aksi Teratas' di bawah, semua CSS inline, tanpa JS, ramah seluler; simpan sebagai Dashboard.html ke OneDrive. Berhenti dan konfirmasi sebelum mengirim email atau menjadwalkan rapat."},
        {'instr':'Tetap di Cowork. Referensikan /03 Contoso_Mail_Merge_Recipients.xlsx dan /04 Contoso_Brand_Guidelines.docx dengan /. Tempelkan prompt cascade.',
         'prompt':"Cowork — jalankan cascade tim negara kuartalan ke 14 sales manager regional, lead pabrik dan kepatuhan untuk Direktur Utama Indonesia di Contoso Tobacco & Wellness. Sumber: /03 Contoso_Mail_Merge_Recipients.xlsx (14 baris: Nama Depan, Nama Lengkap, Lokasi, Peran, Email, Performance Band, Highlight Utama), /04 Contoso_Brand_Guidelines.docx (gunakan 'Template Komunikasi GM Disetujui' persis). Untuk tiap baris: (1) tulis surat personal 180 kata dengan template disetujui — pangsa premium, cakupan outlet, kepatuhan CHT, dan satu permintaan spesifik 30-hari per region; sesuaikan body dengan Performance Band — Top Quartile: apresiatif, minta mereka mentor situs tetangga; On Track: akui progres + satu stretch goal spesifik; Watch: lugas, suportif, satu peningkatan spesifik 30-hari; (2) kutip Highlight Utama penerima verbatim di paragraf 2; (3) tanda tangani sebagai Pak Hendra Susanto, Direktur Utama Indonesia, Contoso Tobacco & Wellness; (4) buat DRAF Outlook (jangan kirim) ke alamat di kolom Email; subjek '[Nama Depan], catatan singkat tentang kuartal ini di [Lokasi]'. Saat 14 draf siap, beri saya tabel ringkasan: Penerima · Lokasi · Band · Pratinjau Subjek · Tautan Draf. Berhenti dan konfirmasi sebelum mengirim apa pun."},
        {'instr':'Tetap di Cowork. Unggah samples/CVs/ ke library SharePoint dulu (HR / Recruitment / Trade Marketing & Distribution Manager). Tunggu 2 menit untuk indexing Microsoft Graph. Tempelkan prompt screening CV.',
         'prompt':"Cowork — tangani screening CV untuk peran Trade Marketing & Distribution Manager di Contoso Tobacco & Wellness. Sumber: folder SharePoint /HR/Recruitment/Contoso T&W Trade Marketing & Distribution Manager (12 CV). Lakukan semua berikut: (1) tinjau setiap CV; skor tiap kandidat 1–5 terhadap distribusi FMCG, pertumbuhan cakupan outlet, trade marketing; (2) bangun shortlist berperingkat (top 5) dengan nama · perusahaan saat ini · 3 bullet bukti terkutip · risiko/gap untuk diuji di wawancara; (3) bangun daftar 'second look' (3 berikutnya) dan daftar ditolak (satu baris alasan masing-masing); (4) untuk tiap kandidat top-5, susun brief persiapan wawancara personal untuk hiring manager — 3 pertanyaan untuk diajukan dan jenis jawaban yang membuka 'ya'; (5) susun (JANGAN kirim) email pengantar ke kandidat #1 mengundang ke panggilan screening; simpan sebagai draf Outlook. Tandai apa pun yang tidak jelas dengan [VERIFIKASI]. Jangan fabrikasi kualifikasi. Berhenti dan konfirmasi sebelum mengirim email apa pun."}
      ],
      persona=['Pak Hendra Susanto','Pak Hendra Susanto','Pak Hendra Susanto'],
      personaID=['Pak Hendra Susanto','Pak Hendra Susanto','Pak Hendra Susanto']),

      # ── Outlook · Catch up + executive reply ─
      tool(T_OUTLOOK, M365_LIC, M365_ACCT, [
        {'instr':'Open Outlook (web or desktop). Find the longest email thread in your inbox from this week. Click **Summary by Copilot** at the top of the thread. In the Copilot pane, paste the catch-up prompt.',
         'prompt':"Summarise this email thread in 5 bullets. Who is asking what of whom? What decision is being narrowed in this thread? List the open action items with owner and due date. Flag the parts where I am specifically mentioned and what is being asked of me."},
        {'instr':'In the same thread, click Reply > Copilot icon > **Draft with Copilot**. Paste the executive-reply prompt.',
         'prompt':"Draft a reply to this thread on behalf of the GM Indonesia at Contoso Tobacco & Wellness. Confirm we are on track on the main request, politely push back on the unrealistic deadline, and propose a 30-minute call this week. Tone: warm, direct, respectful. Maximum 4 short paragraphs, no jargon. Sign off as Pak Hendra Susanto."}
      ], DESC_OUTLOOK,
      promptsID=[
        {'instr':'Buka Outlook (web atau desktop). Temukan thread email terpanjang di inbox minggu ini. Klik **Summary by Copilot** di atas thread. Di panel Copilot, tempelkan prompt catch-up.',
         'prompt':"Ringkas thread email ini dalam 5 bullet. Siapa meminta apa kepada siapa? Keputusan apa yang dipersempit di thread ini? Daftarkan action items terbuka dengan pemilik dan tenggat. Tandai bagian di mana saya secara spesifik disebut dan apa yang diminta dari saya."},
        {'instr':'Pada thread yang sama, klik Reply > ikon Copilot > **Draft with Copilot**. Tempelkan prompt balasan eksekutif.',
         'prompt':"Susun balasan thread ini atas nama Direktur Utama Indonesia di Contoso Tobacco & Wellness. Konfirmasi kami on-track untuk permintaan utama, sopan menolak tenggat yang tidak realistis, dan tawarkan panggilan 30 menit minggu ini. Nada: hangat, lugas, hormat. Maksimum 4 paragraf pendek, tanpa jargon. Tanda tangani sebagai Pak Hendra Susanto."}
      ],
      persona=['Pak Hendra Susanto','Pak Hendra Susanto'],
      personaID=['Pak Hendra Susanto','Pak Hendra Susanto']),

      # ── Power Move · FY27 CHT (excise) tariff-step response pack ─
      tool(T_CHAT, M365_LIC, M365_ACCT, [
        {'instr':'Open Microsoft 365 Copilot Chat. Reference the relevant sample files with /. Paste the FY27 CHT response prompt.',
         'prompt':"Act as Country Strategy lead supporting the GM Indonesia at Contoso Tobacco & Wellness. The FY27 CHT (excise) tariff bands have just been signalled — assume Premium SKM-class +12%, Mid-tier SKM +9%, Mass SKT +6%. Use /02 Contoso_KPI_Dashboard.xlsx (volumes, share, current price ladder by brand and region) and /05 Contoso_Strategic_Memo.docx (premium-defence stance). Produce four artefacts: (1) PRICING SCENARIOS Excel-style table — three scenarios (Hold price / Partial pass-through / Full pass-through) with modelled volume sensitivity, share impact, and gross-profit impact for each brand; (2) BRAND-BY-BRAND PRICE LADDER Word 1 page — recommended new price points effective FY27 cut-over date, rationale per tier; (3) DISTRIBUTOR LETTER Word 0.5 page — clear, respectful, signed by GM Indonesia, explaining new price ladder, pita-cukai cut-over logistics, credit-note treatment for in-trade stock; (4) BOARD PRE-READ Word 1 page — what we are doing, why, expected P&L impact, the 3 risks we are watching, 2 open questions for the Regional Office. Use precise tobacco / FMCG / Indonesian regulatory language (CHT, pita-cukai, Bea Cukai, PP 109/2012). Flag every assumption with [ASSUMPTION:...]. Do not invent KPI numbers — pull from source files or mark [VERIFY]."}
      ], DESC_CHAT,
      promptsID=[
        {'instr':'Buka Microsoft 365 Copilot Chat. Referensikan berkas sampel yang relevan dengan /. Tempelkan prompt respons CHT FY27.',
         'prompt':"Bertindak sebagai lead Strategi Negara yang mendukung Direktur Utama Indonesia di Contoso Tobacco & Wellness. Pita tarif CHT FY27 baru saja disinyalkan — asumsikan kelas SKM Premium +12%, SKM Mid-tier +9%, SKT Mass +6%. Gunakan /02 Contoso_KPI_Dashboard.xlsx (volume, pangsa, ladder harga saat ini per merek dan region) dan /05 Contoso_Strategic_Memo.docx (sikap pertahanan premium). Hasilkan empat artefak: (1) SKENARIO HARGA tabel gaya Excel — tiga skenario (Tahan harga / Pass-through parsial / Pass-through penuh) dengan sensitivitas volume termodel, dampak pangsa, dan dampak laba kotor untuk tiap merek; (2) PRICE LADDER PER MEREK Word 1 halaman — titik harga baru yang direkomendasikan efektif tanggal cut-over FY27, alasan per tier; (3) SURAT DISTRIBUTOR Word 0,5 halaman — jelas, hormat, ditandatangani Direktur Utama Indonesia, menjelaskan price ladder baru, logistik cut-over pita-cukai, perlakuan credit-note untuk stok in-trade; (4) PRE-READ DIREKSI Word 1 halaman — apa yang kami lakukan, mengapa, dampak P&L yang diharapkan, 3 risiko yang dipantau, 2 pertanyaan terbuka untuk Kantor Regional. Gunakan bahasa tembakau / FMCG / regulasi Indonesia yang presisi (CHT, pita-cukai, Bea Cukai, PP 109/2012). Tandai setiap asumsi dengan [ASUMSI:...]. Jangan fabrikasi angka KPI — tarik dari berkas sumber atau tandai [VERIFIKASI]."}
      ],
      persona=['Pak Hendra Susanto'],
      personaID=['Pak Hendra Susanto']),

    ],
    companyID='Contoso Tobacco & Wellness',
    taglineID='Country Review Kantor Regional dalam 48 jam — volume batang per merek, cakupan MT/GT, kepatuhan CHT, kesiapan peluncuran lini ginseng.',
    scenarioID="Contoso Tobacco & Wellness (CTW) adalah produsen rokok multi-merek Indonesia dan operator pangan fungsional kesehatan (lini Korean Red Ginseng dalam peluncuran). OpCo lokal menjalankan 1 pabrik di Karawang, enam merek rokok aktif di Premium/Mid-tier/Mass, dan portofolio SKU ginseng baru dalam filing BPOM untuk peluncuran Q4 FY26. Volume YTD ~1,85 miliar batang; Pangsa Merek Premium 6,4% (+0,6pt YoY); Cakupan Outlet Aktif 78% vs target 82%; kepatuhan CHT 99,4%; yield pabrik Karawang menurun di 2 lini. Country Review Kantor Regional dalam 48 jam dan Direktur Utama membutuhkan paket briefing defensible, respons step tarif CHT FY27, price ladder per merek, komunikasi distributor, dan review kesiapan peluncuran ginseng. Frame referensi dunia nyata: peer termasuk KTNG Indonesia, HM Sampoerna (PMI), Gudang Garam, Djarum, Bentoel (BAT Indonesia), Wismilak, Nojorono. Regulator dalam scope: Bea Cukai (CHT, pita-cukai), BPOM (produk pangan/kesehatan), Kemenkes (kemasan & periklanan PP 109/2012), LPPOM-MUI (sertifikasi halal untuk lini wellness).",
    geo='ID',
))
