
import sys; sys.path.insert(0,'.')
from util import *

# ────────────────────────────────────────────────────────────────────────
#  Batch 15  —  Cosmetics & Personal Care industry (Contoso Beauty Innovation flavour)
#
#  Real customer reference frame: Contoso Beauty Innovation — the Indonesian cosmetics
#  and personal-care group behind Wardah, Make Over, Emina, Kahf, Instaperfect,
#  Wardah Perfect Bright, and OMG!. Group also inspired by Mandom Indonesia
#  (Gatsby, Pixy), Mustika Ratu, Martina Berto (Sariayu), Kao Indonesia (Biore),
#  L\u2019Oréal Indonesia, Unilever Indonesia Personal Care and Cosmax Indonesia.
#
#  Cloned from the food-fmcg block (ind_batch10.py) with targeted substitutions
#  so structure (14 tools · storyboard · personas · Agent Builder set) is intact
#  while scenario, prompts, regulators, channels, ingredients and recall triggers
#  are all cosmetics-industry appropriate.
# ────────────────────────────────────────────────────────────────────────

INDUSTRIES_15 = []

INDUSTRIES_15.append(ind(
    'cosmetics', 'sec-cosmetics', 'Cosmetics & Personal Care', '💄', '#EC4899', '#BE185D',
    'Contoso Beauty Innovation',
    'Q4 FY2025 live-shopping live-shopping trade-spend overrun Rp 60B; hydroquinone-contamination recall on 2 SKUs across 3 markets — Board pack in 5 days.',
    "Contoso Beauty Innovation is an Indonesia-based cosmetics and personal-care group with 4 manufacturing plants across Jababeka and Cikande, producing colour cosmetics, skincare, haircare, personal wash and fragrance for over 300 SKUs across the Wardah, Make Over, Emina, Kahf, Instaperfect, Wardah Perfect Bright and OMG! brand houses. Live-shopping trade-spend in Q4 FY2025 overran budget by Rp 60B (+22%) driven by aggressive TikTok Shop and Shopee Live incentives and weaker Sociolla / Watsons / Guardian modern-beauty sell-through. A hydroquinone-above-limit finding on two Wardah Perfect Bright brightening SKUs triggered a precautionary recall in Malaysia and Singapore — BPOM Indonesia (Notifikasi Kosmetik), NPRA / KKM Malaysia and HSA Singapore have all opened files, and US MoCRA compliance for the export line is under fresh scrutiny. Titanium dioxide (TiO2) and palm-derived surfactant costs jumped 18% on global specialty-chemicals volatility, squeezing margins on the 4 highest-volume colour-cosmetics and personal-wash SKUs. The Group CFO needs a Board pack in 5 days covering live-shopping trade-spend control, the ingredient-recall remediation programme, gross-margin recovery on colour-cosmetics + personal-wash, and FY2026 live-shopping + creator-affiliate guardrails. Real customer reference frame: the group operates similarly to Contoso Beauty Innovation (Wardah / Make Over / Emina / Kahf), Mandom Indonesia (Gatsby, Pixy), Mustika Ratu, Martina Berto (Sariayu), Kao Indonesia (Biore), L\u2019Oréal Indonesia, Unilever Indonesia (Personal Care) and Cosmax Indonesia.",
    ['COSMETICS_01_BPOM_Notifikasi_Tracker.xlsx','COSMETICS_02_SKU_Margin_Tracker.xlsx','COSMETICS_03_Ingredient_Recall_Programme.docx','COSMETICS_04_TiO2_Surfactant_Hedge_Book.xlsx','COSMETICS_05_FY2026_Live_Shopping_Guardrails.docx'],
    [
      tool(T_CHAT, FREE_LIC, FREE_ACCT, [
        {'instr':'', 'prompt':'Trade-spend in Q4 FY2025 overran budget by Rp 60 miliar (~MYR 17 million) (+22%) driven mainly by TikTok Shop and Shopee Live incentive aggression on the colour-cosmetics and personal-wash SKUs. Draft a 1-page note for the Group CFO that frames the overrun in plain language, lists the 5 questions the Board will ask first, and identifies the 3 decisions the CFO must take before the Audit Committee opens. Present as a structured table with columns for Issue, Why It Matters, Board Question, and Recommended Answer.'},
        {'instr':'', 'prompt':'Write a 90-second verbal opening for the Board meeting in 5 days that acknowledges the Rp 60B live-shopping trade-spend overrun and the precautionary hydroquinone-contamination recall in Malaysia and Singapore directly, explains the role of TiO2 + palm-surfactant volatility and modern-trade promo intensity without sounding defensive, and signals a credible 2-quarter margin restoration path. End with 3 talking points the CFO can use if the Board challenges promo discipline or QA controls.'},
        {'instr':'', 'prompt':'Build a stakeholder communication map for the Q4 FY2025 live-shopping trade-spend overrun and the active hydroquinone-contamination recall ahead of the Board meeting. Identify the priority audiences (BPOM Indonesia, MOH Malaysia, SFA Singapore, top-3 modern-trade chains, the recall-affected consumers via the 24h hotline, the 3 outsourced OEM fillers (Cosmax Indonesia, Kolmar Indonesia, Sinar Wisesa), and the FY2026 live-shopping working-capital banks), the message each audience requires, the timing, and the main communication risk if the message is mishandled. Present as a RAG table with Red for same-day, Amber for 24-hour, and Green for monitor-only audiences.'}
      ], DESC_CHAT,
      promptsID=[
        {'instr':'', 'prompt':'Trade-spend kuartal 4 FY2025 melebihi anggaran sebesar Rp 60 miliar (+22%) terutama karena agresivitas insentif TikTok Shop dan Shopee Live pada SKU colour cosmetics dan personal wash. Susun nota tajam 1 halaman untuk Direktur Keuangan Grup yang membingkai pembengkakan dalam bahasa sederhana, mendaftar 5 pertanyaan yang akan ditanyakan Direksi pertama-tama, dan mengidentifikasi 3 keputusan yang harus diambil Direktur Keuangan sebelum Komite Audit dibuka. Sajikan sebagai tabel terstruktur dengan kolom Isu, Mengapa Penting, Pertanyaan Direksi, dan Jawaban yang Direkomendasikan.'},
        {'instr':'', 'prompt':'Tulis pembukaan lisan 90 detik untuk Rapat Direksi dalam 5 hari yang mengakui pembengkakan trade-spend Rp 60 miliar dan recall pencegahan kontaminasi hidrokuinon di Malaysia dan Singapura secara langsung, menjelaskan peran volatilitas TiO2 + surfaktan sawit dan intensitas promo modern-trade tanpa terdengar defensif, dan memberikan sinyal jalur pemulihan margin 2-kuartal yang kredibel. Akhiri dengan 3 talking points untuk dipakai Direktur Keuangan bila Direksi menantang disiplin promo atau pengendalian QA.'},
        {'instr':'', 'prompt':'Bangun peta komunikasi pemangku kepentingan untuk pembengkakan trade-spend kuartal 4 FY2025 dan recall kontaminasi hidrokuinon aktif menjelang Rapat Direksi. Identifikasi audiens prioritas (BPOM Indonesia, KKM Malaysia, SFA Singapura, 3 chain beauty teratas (Sociolla, Watsons, Guardian), konsumen terdampak recall via hotline 24 jam, 3 OEM filler eksternal (Cosmax Indonesia, Kolmar Indonesia, Sinar Wisesa), dan bank modal kerja live-shopping FY2026), pesan inti tiap audiens, timing, dan risiko komunikasi utama bila pesan keliru. Sajikan sebagai tabel RAG dengan Merah untuk hari ini juga, Kuning untuk 24 jam, dan Hijau untuk audiens monitor saja.'}
      ],
      persona=['Sasha Ouellet','Mod Admin','Hadar Caspit'],
      personaID=['Sasha Ouellet','Mod Admin','Hadar Caspit']),

      tool(T_RESEARCHER, M365_LIC, M365_ACCT, [
        {'instr':'Open `m365.cloud.microsoft/chat` > Agents > **Researcher** > select **Critique Mode**. Paste the prompt below — Researcher will draft a deep market study and a second model peer-reviews every claim and citation before it lands.', 'prompt':'I am working under a tight deadline and the work product needs to be airtight, so please be thorough rather than terse. Contoso Beauty Innovation is preparing a Board pack in 5 days. We need credible peer cases including but not limited to Contoso Beauty Innovation, Mandom Indonesia, Mustika Ratu, Martina Berto, Kao Indonesia, L\u2019Oréal Indonesia, Unilever Indonesia Personal Care and Cosmax Indonesia. Here is exactly what I need from you. I need a defensible benchmark of how listed ASEAN cosmetics and personal-care groups have managed Q4 live-shopping trade-spend overruns of more than 15 percent and concurrent product-recall events between 2020 and 2025. Ground every part of your answer in the inputs that follow, and walk through them methodically rather than skimming. For each peer, identify the trigger event, the trade-spend control programme adopted within 90 days, the recall-handling decisions, and the gross-margin trajectory 12 to 24 months later. When you reply, organise the output as described below so I can lift it straight into my deliverable without reformatting. Cite every source with publication date. Critically, instruct Researcher to peer-review each claim against the original publication, flag any claim it cannot independently verify, and present as a structured comparison table with columns for Peer, Trigger, 90-Day Programme, Recall Handling, Margin Outcome, Citation. Be specific, attach a citation or sheet/tab/cell reference to every quantitative claim, and if anything is missing or contradictory call it out explicitly with the question I should ask next so nothing slips before the deadline.'},
        {'instr':'Open `m365.cloud.microsoft/chat` > Agents > **Researcher** > select **Model Council**. Paste the prompt below — Researcher runs the question through GPT and Claude in parallel, then a synthesis cover letter highlights agreements, disagreements and unique findings.', 'prompt':'I am working under a tight deadline and the work product needs to be airtight, so please be thorough rather than terse. Contoso Beauty Innovation operates across 4 export markets (Malaysia, Singapore, Philippines, UAE) with regulators (BPOM (Notifikasi Kosmetik), NPRA / KKM, HSA, US FDA (MoCRA)) all on alert. Here is exactly what I need from you. Identify the 3 most defensible playbooks for an cosmetics group dealing with simultaneous live-shopping trade-spend overrun and product-recall pressure. Ground every part of your answer in the inputs that follow, and walk through them methodically rather than skimming. Use Researcher with Model Council enabled — convene parallel reports from GPT and Claude on live-shopping + creator-affiliate rationalisation, SKU portfolio pruning (long-tail shade + finish), ingredient-recall + halal recertification communication, and TiO2 + palm-surfactant hedge restructuring. When you reply, organise the output as described below so I can lift it straight into my deliverable without reformatting. Surface dissent across the panel, summarise the majority position, mark the minority view, and present as a comparison table with columns for Playbook, Council Verdict, Dissenting View, ASEAN Precedent, and Implementation Risk for a CFO-led 90-day plan. Be specific, attach a citation or sheet/tab/cell reference to every quantitative claim, and if anything is missing or contradictory call it out explicitly with the question I should ask next so nothing slips before the deadline.'}
      ], DESC_RESEARCHER,
      promptsID=[
        {'instr':'Buka `m365.cloud.microsoft/chat` > Agents > **Researcher** > pilih **Critique Mode**. Tempel prompt — Researcher menyusun draf riset mendalam lalu model kedua mengkritisi tiap klaim dan kutipan sebelum hasilnya diterima.', 'prompt':'Saya sedang mengerjakan ini dengan tenggat yang ketat dan hasil akhirnya harus rapi, jadi mohon jawab dengan tuntas, jangan ringkas. Contoso Beauty Innovation menyiapkan paket Direksi dalam 5 hari. Kami butuh studi kasus peer yang kredibel termasuk Indofood, Mayora, Wings Group, Japfa, Nippon Indosari, F&N Holdings, Mamee Double Decker dan Nestlé Malaysia. Berikut yang saya butuhkan dari Anda secara persis. Saya butuh benchmark yang dapat dipertahankan tentang bagaimana grup kosmetik dan personal care ASEAN yang tercatat di bursa menangani pembengkakan trade-spend Q4 di atas 15 persen dan kejadian recall produk antara 2020 hingga 2025. Grounding setiap bagian jawaban Anda pada masukan berikut, telaah satu per satu, jangan dilewati. Untuk tiap peer identifikasi peristiwa pemicu, program kendali trade-spend dalam 90 hari, keputusan penanganan recall, dan lintasan gross margin 12 sampai 24 bulan kemudian. Saat menjawab, susun keluaran sesuai format di bawah ini agar dapat langsung saya gunakan di deliverable tanpa perlu format ulang. Sertakan kutipan lengkap dengan tanggal publikasi. Yang kritikal, minta Researcher peer-review tiap klaim terhadap publikasi aslinya, tandai klaim yang tidak dapat diverifikasi independen, dan sajikan sebagai tabel perbandingan terstruktur dengan kolom Peer, Pemicu, Program 90-Hari, Penanganan Recall, Hasil Margin, Kutipan. Tegas, cantumkan kutipan atau referensi sheet/tab/cell untuk setiap angka, dan bila ada yang kurang atau bertentangan, sebutkan secara eksplisit beserta pertanyaan tindak lanjut yang harus saya ajukan agar tidak ada yang terlewat sebelum tenggat.'},
        {'instr':'Buka `m365.cloud.microsoft/chat` > Agents > **Researcher** > pilih **Model Council**. Tempel prompt — Researcher menggelar laporan parallel GPT dan Claude, lalu cover letter sintesa menyorot kesepakatan dan perbedaan.', 'prompt':'Saya sedang mengerjakan ini dengan tenggat yang ketat dan hasil akhirnya harus rapi, jadi mohon jawab dengan tuntas, jangan ringkas. Contoso Beauty Innovation beroperasi di 4 pasar ekspor (Malaysia, Singapura, Filipina, UEA) dengan regulator (BPOM (Notifikasi Kosmetik), NPRA / KKM, HSA, US FDA (MoCRA)) semuanya waspada. Berikut yang saya butuhkan dari Anda secara persis. Identifikasi 3 strategi paling defensible untuk grup kosmetik yang menghadapi pembengkakan trade-spend dan tekanan recall produk secara bersamaan. Grounding setiap bagian jawaban Anda pada masukan berikut, telaah satu per satu, jangan dilewati. Gunakan Researcher dengan Model Council aktif — gelar laporan paralel dari GPT dan Claude atas rasionalisasi trade-spend live-shopping + creator affiliate, pemangkasan portfolio SKU (long-tail shade + finish), komunikasi recall bahan aktif + rekertifikasi halal, dan restrukturisasi hedge TiO2 + surfaktan sawit. Saat menjawab, susun keluaran sesuai format di bawah ini agar dapat langsung saya gunakan di deliverable tanpa perlu format ulang. Sorot perbedaan pendapat, rangkum posisi mayoritas, tandai pandangan minoritas, dan sajikan tabel perbandingan dengan kolom Strategi, Putusan Council, Pandangan Minoritas, Preseden ASEAN, dan Risiko Implementasi untuk rencana 90 hari yang dipimpin Direktur Keuangan. Tegas, cantumkan kutipan atau referensi sheet/tab/cell untuk setiap angka, dan bila ada yang kurang atau bertentangan, sebutkan secara eksplisit beserta pertanyaan tindak lanjut yang harus saya ajukan agar tidak ada yang terlewat sebelum tenggat.'}
      ],
      persona=['Mod Admin','Mod Admin'],
      personaID=['Mod Admin','Mod Admin']),

      tool(T_ANALYST, M365_LIC, M365_ACCT, [
        {'instr':'Open `m365.cloud.microsoft/chat` > Agents > **Analyst**. Upload `/COSMETICS_01_BPOM_Notifikasi_Tracker.xlsx`. Paste the prompt below.', 'prompt':'I am working under a tight deadline and the work product needs to be airtight, so please be thorough rather than terse. We are Rp 60 miliar (~MYR 17 million) over budget on trade-spend; the Group CFO presents to the Board in 5 days. Here is exactly what I need from you. Quantify and visualise the Q4 FY2025 live-shopping trade-spend overrun. Ground every part of your answer in the inputs that follow, and walk through them methodically rather than skimming. Use the uploaded /COSMETICS_01_BPOM_Notifikasi_Tracker.xlsx — cross-reference the Channel Spend, SKU Promo Activity AND Sell-Through tabs. When you reply, organise the output as described below so I can lift it straight into my deliverable without reformatting. Calculate absolute and percentage variance vs budget by channel (modern-beauty retail, general trade, marketplace, live shopping) and by category (colour cosmetics, skincare, haircare, personal wash, fragrance). Build (1) a horizontal bar chart of live-shopping trade-spend variance ranked worst to best, and (2) a 100% stacked column showing each category contribution to the gap. Flag overrun worse than 25% as Red, 10–25% as Amber, under 10% as Green. Output a RAG dashboard with both charts embedded and one recommended corrective lever per Red row. Be specific, attach a citation or sheet/tab/cell reference to every quantitative claim, and if anything is missing or contradictory call it out explicitly with the question I should ask next so nothing slips before the deadline.'},
        {'instr':'Open `m365.cloud.microsoft/chat` > Agents > **Analyst**. Upload `/COSMETICS_02_SKU_Margin_Tracker.xlsx` AND `/COSMETICS_04_TiO2_Surfactant_Hedge_Book.xlsx`. Paste the prompt below.', 'prompt':'I am working under a tight deadline and the work product needs to be airtight, so please be thorough rather than terse. Edible-oil costs jumped 18% in Q4. Here is exactly what I need from you. Identify which SKUs have lost the most gross-margin in Q4 FY2025 and how much of that is CPO-driven. Ground every part of your answer in the inputs that follow, and walk through them methodically rather than skimming. From /COSMETICS_02_SKU_Margin_Tracker.xlsx pull Q3 vs Q4 GM by SKU; from /COSMETICS_04_TiO2_Surfactant_Hedge_Book.xlsx pull hedge coverage and realised vs spot CPO prices. When you reply, organise the output as described below so I can lift it straight into my deliverable without reformatting. Build a margin-bridge waterfall (Q3 GM → Volume → Mix → Trade-spend → CPO Cost → FX → Q4 GM) with the 10 worst-impacted SKUs labelled. Output a RAG dashboard with the waterfall, a hedge-coverage donut chart, and a one-paragraph CFO note on whether to extend the hedge book through FY2026 H1. Be specific, attach a citation or sheet/tab/cell reference to every quantitative claim, and if anything is missing or contradictory call it out explicitly with the question I should ask next so nothing slips before the deadline.'}
      ], DESC_ANALYST,
      promptsID=[
        {'instr':'Buka `m365.cloud.microsoft/chat` > Agents > **Analyst**. Unggah `/COSMETICS_01_BPOM_Notifikasi_Tracker.xlsx`. Tempel prompt.', 'prompt':'Saya sedang mengerjakan ini dengan tenggat yang ketat dan hasil akhirnya harus rapi, jadi mohon jawab dengan tuntas, jangan ringkas. Kami over budget Rp 60 miliar pada trade-spend; Direktur Keuangan Grup mempresentasikan ke Direksi dalam 5 hari. Berikut yang saya butuhkan dari Anda secara persis. Kuantifikasi dan visualisasikan pembengkakan trade-spend Q4 FY2025. Grounding setiap bagian jawaban Anda pada masukan berikut, telaah satu per satu, jangan dilewati. Gunakan /COSMETICS_01_BPOM_Notifikasi_Tracker.xlsx — analisis silang antar tab Channel Spend, SKU Promo Activity DAN Sell-Through. Saat menjawab, susun keluaran sesuai format di bawah ini agar dapat langsung saya gunakan di deliverable tanpa perlu format ulang. Hitung selisih absolut dan persentase vs anggaran per channel (modern-beauty retail, general trade, marketplace, live shopping) dan per kategori (colour cosmetics, skincare, haircare, personal wash, fragrance). Bangun (1) bar chart horizontal selisih trade-spend diurutkan dari terburuk ke terbaik, dan (2) stacked column 100% kontribusi tiap kategori. Tandai pembengkakan >25% Merah, 10–25% Kuning, <10% Hijau. Hasilkan dashboard RAG dengan kedua chart tertanam dan satu rekomendasi perbaikan per baris Merah. Tegas, cantumkan kutipan atau referensi sheet/tab/cell untuk setiap angka, dan bila ada yang kurang atau bertentangan, sebutkan secara eksplisit beserta pertanyaan tindak lanjut yang harus saya ajukan agar tidak ada yang terlewat sebelum tenggat.'},
        {'instr':'Buka `m365.cloud.microsoft/chat` > Agents > **Analyst**. Unggah `/COSMETICS_02_SKU_Margin_Tracker.xlsx` DAN `/COSMETICS_04_TiO2_Surfactant_Hedge_Book.xlsx`. Tempel prompt.', 'prompt':'Saya sedang mengerjakan ini dengan tenggat yang ketat dan hasil akhirnya harus rapi, jadi mohon jawab dengan tuntas, jangan ringkas. Biaya edible-oil melonjak 18% di Q4. Berikut yang saya butuhkan dari Anda secara persis. Identifikasi SKU mana yang kehilangan margin kotor terbanyak di Q4 FY2025 dan berapa banyak yang didorong CPO. Grounding setiap bagian jawaban Anda pada masukan berikut, telaah satu per satu, jangan dilewati. Dari /COSMETICS_02_SKU_Margin_Tracker.xlsx tarik GM per SKU Q3 vs Q4; dari /COSMETICS_04_TiO2_Surfactant_Hedge_Book.xlsx tarik cover hedge dan harga CPO realisasi vs spot. Saat menjawab, susun keluaran sesuai format di bawah ini agar dapat langsung saya gunakan di deliverable tanpa perlu format ulang. Bangun margin-bridge waterfall (GM Q3 → Volume → Mix → Trade-spend → Biaya CPO → Valas → GM Q4) dengan 10 SKU paling terdampak diberi label. Sajikan dashboard RAG dengan waterfall, donut chart cover hedge, dan paragraf catatan Direktur Keuangan apakah memperpanjang hedge book hingga H1 FY2026. Tegas, cantumkan kutipan atau referensi sheet/tab/cell untuk setiap angka, dan bila ada yang kurang atau bertentangan, sebutkan secara eksplisit beserta pertanyaan tindak lanjut yang harus saya ajukan agar tidak ada yang terlewat sebelum tenggat.'}
      ],
      persona=['Hadar Caspit','Hadar Caspit'],
      personaID=['Hadar Caspit','Hadar Caspit']),

      tool(T_EXCEL, M365_LIC, M365_ACCT, [
        {'instr':'Open `/COSMETICS_01_BPOM_Notifikasi_Tracker.xlsx` in Excel for the Web. Open the **Copilot pane**. Paste the prompt below.', 'prompt':'I am working under a tight deadline and the work product needs to be airtight, so please be thorough rather than terse. The CFO presents in 5 days. Here is exactly what I need from you. Build a Board-ready trade-spend dashboard. Ground every part of your answer in the inputs that follow, and walk through them methodically rather than skimming. Pull from the Channel Spend, SKU Promo Activity AND Sell-Through tabs. When you reply, organise the output as described below so I can lift it straight into my deliverable without reformatting. On a new sheet "Board Trade-Spend Dashboard": (1) KPI tiles for Total Variance MYR M, Variance %, Worst Channel, Worst Category; (2) horizontal bar of variance by channel; (3) clustered column of monthly run-rate; (4) sparklines per channel; (5) RAG conditional formatting >25% red, 10–25% amber, <10% green. Insert all charts on the new sheet, do not modify the source tabs. Be specific, attach a citation or sheet/tab/cell reference to every quantitative claim, and if anything is missing or contradictory call it out explicitly with the question I should ask next so nothing slips before the deadline.'}
      ,
        {'instr':"Stay in the same workbook (or open a fresh Excel-for-the-Web file with one of the data files attached). Open the **Copilot pane** > click the **menu above the prompt box** and pick **Plan** (May 2026). Copilot will outline a step-by-step approach BEFORE making any edits — review and approve before changes land. For the second half, add **use Python** to the prompt and Copilot will run advanced analysis directly inside the workbook.", 'prompt':"Plan mode: outline the step-by-step approach you will take to surface the 3 most material risks in the attached workbook for this scenario — list each step as a numbered plan I can review/approve before any edit. After I approve, execute the plan and create one new sheet called 'Risk Triage' with the result. Then on a second sheet 'Advanced', **use Python** to run a 12-month rolling-trend forecast on the most material risk metric and plot it as a chart with confidence bands. Cite which input columns drive the forecast and flag any data-quality gaps that would invalidate the result."}], '',
      promptsID=[
        {'instr':'Buka `/COSMETICS_01_BPOM_Notifikasi_Tracker.xlsx` di Excel for the Web. Buka **Copilot pane**. Tempel prompt.', 'prompt':'Saya sedang mengerjakan ini dengan tenggat yang ketat dan hasil akhirnya harus rapi, jadi mohon jawab dengan tuntas, jangan ringkas. Direktur Keuangan presentasi dalam 5 hari. Berikut yang saya butuhkan dari Anda secara persis. Bangun dashboard trade-spend siap-Direksi. Grounding setiap bagian jawaban Anda pada masukan berikut, telaah satu per satu, jangan dilewati. Tarik dari tab Channel Spend, SKU Promo Activity DAN Sell-Through. Saat menjawab, susun keluaran sesuai format di bawah ini agar dapat langsung saya gunakan di deliverable tanpa perlu format ulang. Pada sheet baru "Dashboard Trade-Spend Direksi": (1) KPI tile Total Selisih Rp Miliar, Selisih %, Channel Terburuk, Kategori Terburuk; (2) bar horizontal selisih per channel; (3) clustered column run-rate bulanan; (4) sparkline per channel; (5) format kondisional RAG >25% merah, 10–25% kuning, <10% hijau. Sisipkan semua chart pada sheet baru, jangan modifikasi tab sumber. Tegas, cantumkan kutipan atau referensi sheet/tab/cell untuk setiap angka, dan bila ada yang kurang atau bertentangan, sebutkan secara eksplisit beserta pertanyaan tindak lanjut yang harus saya ajukan agar tidak ada yang terlewat sebelum tenggat.'}
      ,
        {'instr':"Tetap di workbook yang sama (atau buka file Excel-for-the-Web baru dengan salah satu file data terlampir). Buka **Copilot pane** > klik **menu di atas kotak prompt** dan pilih **Plan** (Mei 2026). Copilot akan menguraikan pendekatan langkah-demi-langkah SEBELUM melakukan edit — tinjau dan setujui sebelum perubahan diterapkan. Pada bagian kedua, tambahkan **use Python** ke prompt dan Copilot akan menjalankan analisis lanjutan langsung di dalam workbook.", 'prompt':"Mode Plan: uraikan pendekatan langkah-demi-langkah yang akan Anda ambil untuk memunculkan 3 risiko paling material pada workbook terlampir untuk skenario ini — daftarkan setiap langkah sebagai plan bernomor yang dapat saya tinjau/setujui sebelum edit apa pun. Setelah saya setujui, eksekusi plan dan buat satu sheet baru bernama 'Risk Triage' dengan hasilnya. Kemudian pada sheet kedua 'Advanced', **gunakan Python** untuk menjalankan rolling-trend forecast 12 bulan terhadap metrik risiko paling material dan plot sebagai chart dengan confidence bands. Sebutkan kolom input mana yang mendorong forecast dan tandai kesenjangan kualitas data yang akan membatalkan hasilnya."}],
      persona=['Hadar Caspit'],
      personaID=['Hadar Caspit']),

      tool(T_WORD, M365_LIC, M365_ACCT, [
        {'instr':'Open a new blank Word doc in Word for the Web. Open the **Copilot pane**. Reference `/COSMETICS_03_Ingredient_Recall_Programme.docx` and `/COSMETICS_05_FY2026_Live_Shopping_Guardrails.docx` using `/`. Paste the prompt below.', 'prompt':'I am working under a tight deadline and the work product needs to be airtight, so please be thorough rather than terse. Board meets in 5 days. Here is exactly what I need from you. Draft the 4-page Board paper "Q4 FY2025 Trade-Spend & Recall Update — Board Discussion Pack". Ground every part of your answer in the inputs that follow, and walk through them methodically rather than skimming. /COSMETICS_03_Ingredient_Recall_Programme.docx and /COSMETICS_05_FY2026_Live_Shopping_Guardrails.docx, plus the live-shopping trade-spend variance numbers I will paste. When you reply, organise the output as described below so I can lift it straight into my deliverable without reformatting. Sections — (1) Executive summary in 5 bullets, (2) Trade-spend overrun bridge in plain language, (3) Salmonella recall status across MY/SG/ID, (4) Gross-margin recovery levers and their MYR impact, (5) FY2026 promo guardrail policy proposal, (6) Decisions requested from the Board. Tone: precise, Board-ready, no speculative language. Cite the source files at the end of every section. Be specific, attach a citation or sheet/tab/cell reference to every quantitative claim, and if anything is missing or contradictory call it out explicitly with the question I should ask next so nothing slips before the deadline.'}
      ,
        {'instr':"Open the Word doc > **Copilot pane**. Click the **🧠 model picker** at the top of the pane and switch to **Claude Opus 4.7** for nuanced legal/policy/board-grade rewriting. Paste the prompt below. After Copilot drafts, click **Edit with Copilot** (agent mode) for inline restructuring across the whole document in one instruction.", 'prompt':"Using Claude Opus 4.7, rewrite the most consequential section of this document for an external audience (regulator, lender, Board-level reader) — preserve every fact, but tighten the language for clarity and remove any internal jargon. Then switch the model picker back to **GPT** and ask Copilot to produce a same-length GPT version of the SAME section so I can compare nuance side-by-side. Finally, click **Edit with Copilot** (agent mode) and ask Copilot to restructure the whole document so the executive summary lands on page 1 and the appendix moves to the end — one instruction, applied across all sections."}], DESC_WORD,
      promptsID=[
        {'instr':'Buka dokumen Word baru kosong di Word for the Web. Buka **Copilot pane**. Referensikan `/COSMETICS_03_Ingredient_Recall_Programme.docx` dan `/COSMETICS_05_FY2026_Live_Shopping_Guardrails.docx` menggunakan `/`. Tempel prompt.', 'prompt':'Saya sedang mengerjakan ini dengan tenggat yang ketat dan hasil akhirnya harus rapi, jadi mohon jawab dengan tuntas, jangan ringkas. Direksi rapat dalam 5 hari. Berikut yang saya butuhkan dari Anda secara persis. Susun paper Direksi 4 halaman "Update Trade-Spend & Recall Q4 FY2025 — Pack Diskusi Direksi". Grounding setiap bagian jawaban Anda pada masukan berikut, telaah satu per satu, jangan dilewati. /COSMETICS_03_Ingredient_Recall_Programme.docx dan /COSMETICS_05_FY2026_Live_Shopping_Guardrails.docx, plus angka selisih trade-spend yang akan saya tempelkan. Saat menjawab, susun keluaran sesuai format di bawah ini agar dapat langsung saya gunakan di deliverable tanpa perlu format ulang. Bagian — (1) Ringkasan eksekutif 5 bullet, (2) Bridge pembengkakan trade-spend bahasa sederhana, (3) Status recall Salmonella di MY/SG/ID, (4) Lever pemulihan gross margin dan dampak Rp Miliar, (5) Proposal policy guardrail promo FY2026, (6) Keputusan yang diminta dari Direksi. Nada: presisi, siap-Direksi, tidak spekulatif. Kutip file sumber di akhir tiap bagian. Tegas, cantumkan kutipan atau referensi sheet/tab/cell untuk setiap angka, dan bila ada yang kurang atau bertentangan, sebutkan secara eksplisit beserta pertanyaan tindak lanjut yang harus saya ajukan agar tidak ada yang terlewat sebelum tenggat.'}
      ,
        {'instr':"Buka dokumen Word > **Copilot pane**. Klik **🧠 model picker** di atas panel dan beralih ke **Claude Opus 4.7** untuk penulisan ulang yang bernuansa (legal/kebijakan/grade-Direksi). Tempelkan prompt di bawah ini. Setelah Copilot membuat draft, klik **Edit with Copilot** (mode agent) untuk restrukturisasi inline pada seluruh dokumen dalam satu instruksi.", 'prompt':"Menggunakan Claude Opus 4.7, tulis ulang bagian paling penting dari dokumen ini untuk audiens eksternal (regulator, kreditor, pembaca tingkat Direksi) — pertahankan setiap fakta, tetapi rapikan bahasanya agar jelas dan hilangkan jargon internal. Lalu kembalikan model picker ke **GPT** dan minta Copilot membuat versi GPT dengan panjang yang sama dari bagian YANG SAMA sehingga saya bisa membandingkan nuansa berdampingan. Terakhir, klik **Edit with Copilot** (mode agent) dan minta Copilot merestrukturisasi seluruh dokumen sehingga ringkasan eksekutif berada di halaman 1 dan lampiran berpindah ke akhir — satu instruksi, diterapkan pada semua bagian."}],
      persona=['Hadar Caspit'],
      personaID=['Hadar Caspit']),

      tool(T_PPT, M365_LIC, M365_ACCT, [
        {'instr':'Open a new PowerPoint deck in PowerPoint for the Web. Open the **Copilot pane**. Paste the prompt below.', 'prompt':'I am working under a tight deadline and the work product needs to be airtight, so please be thorough rather than terse. The Board sees this on Friday. Here is exactly what I need from you. Build a 10-slide investor-grade deck on the Q4 FY2025 live-shopping trade-spend overrun and recall response. Ground every part of your answer in the inputs that follow, and walk through them methodically rather than skimming. Reference my Word draft `/Q4_Board_Paper.docx` and the trade-spend dashboard numbers I will paste. When you reply, organise the output as described below so I can lift it straight into my deliverable without reformatting. Cover slide; situation in 1 slide; trade-spend bridge waterfall (2 slides); recall status by market (1 slide); margin levers (2 slides); FY2026 promo guardrails (1 slide); decisions requested (1 slide); appendix (1 slide). Use Zava brand colours #F59E0B and #0F1C3F, 18pt minimum body text, 1 chart per slide, no walls of text. Be specific, attach a citation or sheet/tab/cell reference to every quantitative claim, and if anything is missing or contradictory call it out explicitly with the question I should ask next so nothing slips before the deadline.'}
      ,
        {'instr':"Stay in the same deck (or open a fresh PowerPoint for the Web file). Open the **Copilot pane** > click the **🌐 web reference** chip and paste ONE relevant public web URL (e.g. a regulator microsite, a Bursa Malaysia announcement page, a peer's investor-relations page, or a recent industry research page) as a deck-wide reference. Then click the **image-model gear** above the image prompt and select **GPT-Image** for photoreal hero artwork (or **Flux** for stylised). Paste the prompt below.", 'prompt':"Refresh the cover slide and one mid-deck slide using the public-web reference I just attached — pull in the 2 most relevant facts/headlines from that page and surface them as concise, dated bullets with a citation footer ('Source: <publisher>, <date>'). On the cover slide, generate ONE photoreal hero image with **GPT-Image** that captures the strategic theme of this deck in an executive style — no text-on-image, 16:9, neutral palette. Add a footer disclaimer that the web-grounding facts are point-in-time and must be re-verified before final external use."},
        {'instr':'', 'prompt': 'Act as a Marketing & Ops planner for the General Manager · Operations & Marketing of Zava Food (QSR Pizza line).\n\nLebaran 2026 is 4 weeks away. Use /COSMETICS_02_SKU_Margin_Tracker.xlsx (AOV per outlet, food cost %, delivery mix %, CSAT) and /COSMETICS_05_FY2026_Live_Shopping_Guardrails.docx for context.\n\nProduce a launch-ready promo pack:\n\n1. PROMO DESIGN\n - 3 promo bundles (family / duo / solo) with menu, target AOV, food-cost %, gross margin\n - Price ladder vs current menu — call out cannibalisation risk\n - Duration & wave roll-out (Jakarta first, then secondary cities)\n\n2. CHANNEL COPY\n - GoFood listing title + description (max 90 char title, 220 char desc)\n - GrabFood listing title + description\n - Instagram caption × 3 variants (warm / playful / respectful Hari Raya tone)\n - Push notification copy for app\n\n3. OUTLET BRIEFING PACK\n - 1-page operational checklist (prep · staffing · POS · ingredient stock-up)\n - Talking points for outlet team briefing\n - Quality-control sampling plan\n\n4. CANNIBALISATION FORECAST TABLE\n - Outlet by outlet: expected lift vs cannibalisation of regular menu, net AOV impact\n\n5. LAUNCH SCORECARD\n - 5 KPIs to monitor for the first 7 days, with red/amber/green thresholds\n\nTag every assumption [ASSUMPTION:...]. Tone: confident, food-first, never racist or tone-deaf to the Indonesian Muslim audience.'}
      ], DESC_PPT,
      promptsID=[
        {'instr':'Buka deck PowerPoint baru di PowerPoint for the Web. Buka **Copilot pane**. Tempel prompt.', 'prompt':'Saya sedang mengerjakan ini dengan tenggat yang ketat dan hasil akhirnya harus rapi, jadi mohon jawab dengan tuntas, jangan ringkas. Direksi melihat ini Jumat. Berikut yang saya butuhkan dari Anda secara persis. Bangun deck 10 slide kelas investor tentang pembengkakan trade-spend dan respons recall Q4 FY2025. Grounding setiap bagian jawaban Anda pada masukan berikut, telaah satu per satu, jangan dilewati. Referensikan draf Word saya `/Paper_Direksi_Q4.docx` dan angka dashboard trade-spend yang akan saya tempel. Saat menjawab, susun keluaran sesuai format di bawah ini agar dapat langsung saya gunakan di deliverable tanpa perlu format ulang. Slide cover; situasi 1 slide; waterfall bridge trade-spend (2 slide); status recall per pasar (1 slide); lever margin (2 slide); guardrail promo FY2026 (1 slide); keputusan yang diminta (1 slide); appendix (1 slide). Gunakan warna brand Zava #F59E0B dan #0F1C3F, font tubuh minimum 18pt, 1 chart per slide, hindari dinding teks. Tegas, cantumkan kutipan atau referensi sheet/tab/cell untuk setiap angka, dan bila ada yang kurang atau bertentangan, sebutkan secara eksplisit beserta pertanyaan tindak lanjut yang harus saya ajukan agar tidak ada yang terlewat sebelum tenggat.'}
      ,
        {'instr':"Tetap di deck yang sama (atau buka file PowerPoint for the Web baru). Buka **Copilot pane** > klik chip **🌐 referensi web** dan tempelkan SATU URL publik yang relevan (misalnya microsite regulator, halaman pengumuman BEI, halaman investor-relations peer, atau halaman riset industri terbaru) sebagai referensi seluruh deck. Kemudian klik **roda gigi model gambar** di atas prompt gambar dan pilih **GPT-Image** untuk hero photoreal (atau **Flux** untuk stilisasi). Tempelkan prompt di bawah ini.", 'prompt':"Segarkan slide cover dan satu slide tengah deck menggunakan referensi web publik yang baru saja dilampirkan — tarik 2 fakta/headline paling relevan dari halaman tersebut dan munculkan sebagai bullet ringkas bertanggal dengan footer kutipan ('Sumber: <penerbit>, <tanggal>'). Pada slide cover, hasilkan SATU hero image photoreal dengan **GPT-Image** yang menangkap tema strategis deck dalam gaya eksekutif — tanpa teks di gambar, 16:9, palet netral. Tambahkan disclaimer footer bahwa fakta web-grounding bersifat point-in-time dan harus diverifikasi ulang sebelum penggunaan eksternal final."},
        {'instr':'', 'prompt': 'Berperan sebagai Marketing & Ops planner untuk General Manager · Operations & Marketing dari Zava Food (lini QSR Pizza).\n\nLebaran 2026 tinggal 4 minggu lagi. Gunakan /COSMETICS_02_SKU_Margin_Tracker.xlsx (AOV per outlet, food cost %, delivery mix %, CSAT) dan /COSMETICS_05_FY2026_Live_Shopping_Guardrails.docx untuk konteks.\n\nHasilkan promo pack siap launch:\n\n1. DESAIN PROMO\n - 3 bundle promo (keluarga / berdua / solo) dengan menu, target AOV, food-cost %, marjin kotor\n - Price ladder vs menu saat ini — sebutkan risiko cannibalisation\n - Durasi & wave roll-out (Jakarta dulu, lalu kota sekunder)\n\n2. CHANNEL COPY\n - GoFood listing title + description (maks 90 karakter title, 220 karakter desc)\n - GrabFood listing title + description\n - Caption Instagram × 3 varian (hangat/jenaka/Hari-Raya yang santun)\n - Copy push notification untuk app\n\n3. PAKET BRIEFING OUTLET\n - Checklist operasional 1 halaman (prep · staffing · POS · stock-up bahan)\n - Talking points untuk briefing tim outlet\n - Rencana sampling quality-control\n\n4. TABEL FORECAST CANNIBALISATION\n - Outlet per outlet: ekspektasi lift vs cannibalisation menu reguler, dampak AOV bersih\n\n5. SCORECARD LAUNCH\n - 5 KPI untuk dipantau 7 hari pertama, dengan threshold merah/amber/hijau\n\nTandai setiap asumsi [ASSUMPTION:...]. Tone: percaya diri, food-first, tidak boleh rasis atau tone-deaf terhadap audiens Muslim Indonesia.'}
      ],
      persona=['Sasha Ouellet', 'Bu Lisa Hartono'],
      personaID=['Sasha Ouellet', 'Bu Lisa Hartono']),

      tool(T_OUTLOOK, M365_LIC, M365_ACCT, [
        {'instr':'Open Outlook on the Web. Open the email thread titled "Q4 FY2025 Trade-Spend Variance — Group CFO follow-up". Click the **Copilot icon** in the message ribbon. Paste the prompt below.', 'prompt':'I am working under a tight deadline and the work product needs to be airtight, so please be thorough rather than terse. Q4 trade-spend overran budget by Rp 60 miliar (~MYR 17 million); Board on Friday. Here is exactly what I need from you. Draft a single, calm, board-ready email to the 6 Brand-House GMs and the Group Trade-Marketing Director. Ground every part of your answer in the inputs that follow, and walk through them methodically rather than skimming. Summarise the latest figures from the email thread above and the attached dashboard. When you reply, organise the output as described below so I can lift it straight into my deliverable without reformatting. Subject line, 4 short paragraphs covering (1) the headline number, (2) the 3 corrective levers I expect each Division to commit to in 48 hours, (3) the FY2026 promo guardrails coming, (4) the meeting time on Wednesday for alignment. End with a one-line note that the Board will see this on Friday. Tone: firm but collegial, not blaming. Be specific, attach a citation or sheet/tab/cell reference to every quantitative claim, and if anything is missing or contradictory call it out explicitly with the question I should ask next so nothing slips before the deadline.'}
      ,
        {'instr':"Open Outlook on the Web > **New email**. In the new **first-draft-in-canvas** experience (March 2026), Copilot drafts directly in the email body (not the small Copilot pane) and asks clarifying questions on goal, audience, and tone. Paste the prompt below and answer Copilot's follow-ups in canvas — no copy-paste.", 'prompt':"Draft a clear stakeholder email about the most pressing issue in this scenario. Copilot, in canvas, ask me 3 clarifying questions before finalising: (1) which decision the recipient must make and by when, (2) which tone fits (firm vs. collaborative vs. supervisory), and (3) audience seniority. After I answer, refine in place — no copy-paste. End with a recommended subject line and a 1-sentence preview tuned for inbox triage."}], DESC_OUTLOOK,
      promptsID=[
        {'instr':'Buka Outlook on the Web. Buka thread email "Selisih Trade-Spend Q4 FY2025 — tindak lanjut Direktur Keuangan". Klik **ikon Copilot** di ribbon pesan. Tempel prompt.', 'prompt':'Saya sedang mengerjakan ini dengan tenggat yang ketat dan hasil akhirnya harus rapi, jadi mohon jawab dengan tuntas, jangan ringkas. Trade-spend Q4 over budget Rp 60 miliar; Direksi Jumat. Berikut yang saya butuhkan dari Anda secara persis. Susun satu email tenang dan siap-Direksi kepada 6 GM Brand House dan Direktur Trade-Marketing Grup. Grounding setiap bagian jawaban Anda pada masukan berikut, telaah satu per satu, jangan dilewati. Ringkas angka terbaru dari thread di atas dan dashboard terlampir. Saat menjawab, susun keluaran sesuai format di bawah ini agar dapat langsung saya gunakan di deliverable tanpa perlu format ulang. Baris subjek, 4 paragraf pendek mencakup (1) angka headline, (2) 3 lever perbaikan yang saya harapkan tiap Divisi komit dalam 48 jam, (3) guardrail promo FY2026 yang akan datang, (4) waktu rapat Rabu untuk penyelarasan. Akhiri dengan satu baris bahwa Direksi melihat ini Jumat. Nada: tegas tapi kolegial, tidak menyalahkan. Tegas, cantumkan kutipan atau referensi sheet/tab/cell untuk setiap angka, dan bila ada yang kurang atau bertentangan, sebutkan secara eksplisit beserta pertanyaan tindak lanjut yang harus saya ajukan agar tidak ada yang terlewat sebelum tenggat.'}
      ,
        {'instr':"Buka Outlook on the Web > **Email Baru**. Pada pengalaman **first-draft-in-canvas** baru (Maret 2026), Copilot mengetik draft langsung di badan email (bukan di panel Copilot kecil) dan mengajukan pertanyaan klarifikasi terkait tujuan, audiens, dan nada. Tempelkan prompt di bawah dan jawab pertanyaan Copilot di kanvas — tanpa copy-paste.", 'prompt':"Susun email pemangku kepentingan yang jelas mengenai isu paling mendesak dalam skenario ini. Copilot, di kanvas, ajukan 3 pertanyaan klarifikasi sebelum finalisasi: (1) keputusan apa yang harus diambil penerima dan kapan, (2) nada mana yang sesuai (tegas vs. kolaboratif vs. supervisori), (3) seniority audiens. Setelah saya menjawab, sempurnakan langsung di kanvas — tanpa copy-paste. Akhiri dengan rekomendasi subject line dan preview 1 kalimat yang disetel untuk triage inbox."}],
      persona=['Hadar Caspit'],
      personaID=['Hadar Caspit']),

      tool(T_TEAMS, M365_LIC, M365_ACCT, 
        [
          {'instr':"**(1) In Teams**, open **Calendar** → click the past meeting **\"New Software Implementation\"**. On the Recap page, walk the audience through the **AI Notes** (auto-summary), the **Custom summary** (Copilot's per-attendee view), and the **Audio recap** (chapter markers with speaker timings). **(2) In Word for the Web**, open a **new blank document**. Type a minutes template at the top — five empty headings: Date and Attendees · Agenda Items · Decisions Taken · Action Items · Risks and Open Questions. **(3) Click the Copilot icon** in the Word ribbon and paste the prompt below — Copilot in Word will reference the meeting recap by name with `/` and fill the template.", 'prompt':"Create meeting minutes for the Teams meeting /New Software Implementation. Use the empty template already on this page and fill each heading from the meeting recap. Sections: (1) Date and Attendees; (2) Agenda Items; (3) Decisions Taken; (4) Action Items with Owner and Due Date; (5) Risks and Open Questions. Quote attendee statements verbatim where the wording matters. Tag any decision that is on the critical path as Critical Path."},
          {'instr':'**(1) In Teams**, open **Calendar** → click the past meeting **"Marketing Campaign Performance Review"**. On the Recap page, walk through the **AI Notes**, the **Custom summary**, and the **Audio recap** chapters. **(2) In Word for the Web**, open a **new blank document**. Type a campaign-review minutes template at the top — six empty headings: Date and Attendees · Campaign KPIs Reviewed · Decisions Taken · Action Items · Budget Reallocations · Next Review Date. **(3) Click the Copilot icon** in the Word ribbon and paste the prompt below.', 'prompt':"Create meeting minutes for the Teams meeting /Marketing Campaign Performance Review. Use the empty campaign-review template already on this page. Sections: (1) Date and Attendees; (2) Campaign KPIs Reviewed; (3) Decisions Taken; (4) Action Items with Owner and Due Date; (5) Budget Reallocations Approved; (6) Next Review Date. Quote attendee statements verbatim where the wording matters. Highlight any KPI that missed target by more than 10% in amber."},
          {'instr':'**(1) In Teams**, open **Calendar** → click the past meeting **"Negotiating Marketing Contract"**. On the Recap page, walk through the **AI Notes**, the **Custom summary**, and the **Audio recap**. **(2) In Word for the Web**, open a **new blank document**. Type a vendor-negotiation minutes template at the top — seven empty headings: Vendor and Owner · Commercial Terms Discussed · Concessions Offered · Concessions Accepted · Open Items · Approval Thresholds · Next Steps. **(3) Click the Copilot icon** in the Word ribbon and paste the prompt below — then forward the result to Procurement, Legal, and the Group CFO.', 'prompt':"Create meeting minutes for the Teams meeting /Negotiating Marketing Contract. Use the empty vendor-negotiation template already on this page. Sections: (1) Vendor and Owner; (2) Commercial Terms Discussed; (3) Concessions Offered; (4) Concessions Accepted; (5) Open Items; (6) Approval Thresholds (CFO / Board); (7) Next Steps with Owner and Due Date. Highlight any term requiring CFO sign-off in amber and any term requiring Board sign-off in red.. Email the link to Procurement, Legal, and the Group CFO."}
        ], DESC_TEAMS,
        promptsID=[
          {'instr':'**(1) Di Teams**, buka **Calendar** → klik rapat **"New Software Implementation"**. Di halaman Recap, jelaskan ke peserta tentang **AI Notes** (ringkasan otomatis), **Custom summary** (tampilan per-peserta dari Copilot), dan **Audio recap** (penanda bab dengan timing pembicara). **(2) Di Word for the Web**, buka **dokumen kosong baru**. Ketik kerangka notulen di bagian atas — lima heading kosong: Tanggal dan Peserta · Agenda · Keputusan · Action Items · Risiko dan Pertanyaan Terbuka. **(3) Klik ikon Copilot** di ribbon Word lalu tempelkan prompt di bawah — Copilot in Word akan merujuk recap rapat dengan `/` dan mengisi template.', 'prompt':"Susun notulen rapat untuk rapat Teams /New Software Implementation. Gunakan template kosong yang sudah ada di halaman ini dan isi tiap heading dari recap rapat. Bagian: (1) Tanggal dan Peserta; (2) Agenda; (3) Keputusan; (4) Action Items dengan Owner dan Due Date; (5) Risiko dan Pertanyaan Terbuka. Kutip pernyataan peserta apa adanya bila kata-katanya penting. Tandai keputusan di jalur kritis sebagai Critical Path."},
          {'instr':'**(1) Di Teams**, buka **Calendar** → klik rapat **"Marketing Campaign Performance Review"**. Di halaman Recap, jelaskan **AI Notes**, **Custom summary**, dan **Audio recap**. **(2) Di Word for the Web**, buka dokumen kosong baru. Ketik kerangka notulen tinjauan kampanye — enam heading kosong: Tanggal dan Peserta · KPI Kampanye yang Dikaji · Keputusan · Action Items · Realokasi Anggaran · Jadwal Tinjauan Berikutnya. **(3) Klik ikon Copilot** di ribbon Word lalu tempelkan prompt di bawah.', 'prompt':"Susun notulen rapat untuk rapat Teams /Marketing Campaign Performance Review. Gunakan template kosong tinjauan kampanye yang sudah ada. Bagian: (1) Tanggal dan Peserta; (2) KPI Kampanye yang Dikaji; (3) Keputusan; (4) Action Items dengan Owner dan Due Date; (5) Realokasi Anggaran yang Disetujui; (6) Jadwal Tinjauan Berikutnya. Kutip pernyataan peserta apa adanya. Tandai KPI yang meleset >10% dengan amber."},
          {'instr':'**(1) Di Teams**, buka **Calendar** → klik rapat **"Negotiating Marketing Contract"**. Di halaman Recap, jelaskan **AI Notes**, **Custom summary**, dan **Audio recap**. **(2) Di Word for the Web**, buka dokumen kosong baru. Ketik kerangka notulen negosiasi vendor — tujuh heading kosong: Vendor dan Owner · Term Komersial · Konsesi yang Ditawarkan · Konsesi yang Diterima · Item Terbuka · Threshold Persetujuan · Langkah Berikutnya. **(3) Klik ikon Copilot** di ribbon Word lalu tempelkan prompt di bawah — kemudian teruskan hasilnya ke Procurement, Legal, dan Direktur Keuangan Grup.', 'prompt':"Susun notulen rapat untuk rapat Teams /Negotiating Marketing Contract. Gunakan template kosong negosiasi vendor yang sudah ada. Bagian: (1) Vendor dan Owner; (2) Term Komersial; (3) Konsesi yang Ditawarkan; (4) Konsesi yang Diterima; (5) Item Terbuka; (6) Threshold Persetujuan (CFO / Direksi); (7) Langkah Berikutnya dengan Owner dan Due Date. Tandai term yang memerlukan persetujuan CFO dengan amber dan persetujuan Direksi dengan merah.. Lalu email link-nya ke Procurement, Legal, dan Direktur Keuangan Grup."}
        ],
        promptsBM=[
          {'instr':'**(1) Di Teams**, buka **Calendar** → klik mesyuarat **"New Software Implementation"**. Pada halaman Recap, terangkan kepada hadirin tentang **AI Notes** (ringkasan automatik), **Custom summary** (paparan per-hadirin dari Copilot), dan **Audio recap** (penanda bab dengan masa pembicara). **(2) Di Word for the Web**, buka **dokumen kosong baharu**. Taip rangka minit di bahagian atas — lima tajuk kosong: Tarikh dan Hadirin · Agenda · Keputusan · Tindakan · Risiko dan Soalan Terbuka. **(3) Klik ikon Copilot** di ribbon Word dan tampal prompt di bawah — Copilot in Word akan merujuk recap mesyuarat dengan `/` dan mengisi templat.', 'prompt':"Hasilkan minit mesyuarat untuk mesyuarat Teams /New Software Implementation. Gunakan templat kosong yang sudah ada di halaman ini dan isi setiap tajuk daripada recap mesyuarat. Bahagian: (1) Tarikh dan Hadirin; (2) Agenda; (3) Keputusan; (4) Tindakan dengan Pemilik dan Tarikh; (5) Risiko dan Soalan Terbuka. Petik kenyataan hadirin sebagaimana asal di mana perkataannya penting. Tandakan sebarang keputusan di laluan kritikal sebagai Critical Path."},
          {'instr':'**(1) Di Teams**, buka **Calendar** → klik mesyuarat **"Marketing Campaign Performance Review"**. Pada halaman Recap, terangkan **AI Notes**, **Custom summary**, dan **Audio recap**. **(2) Di Word for the Web**, buka dokumen kosong baharu. Taip rangka minit ulasan kempen — enam tajuk kosong: Tarikh dan Hadirin · KPI Kempen yang Diulas · Keputusan · Tindakan · Pelarasan Bajet · Tarikh Ulasan Berikutnya. **(3) Klik ikon Copilot** di ribbon Word dan tampal prompt di bawah.', 'prompt':"Hasilkan minit mesyuarat untuk mesyuarat Teams /Marketing Campaign Performance Review. Gunakan templat kosong ulasan kempen yang sudah ada. Bahagian: (1) Tarikh dan Hadirin; (2) KPI Kempen yang Diulas; (3) Keputusan; (4) Tindakan dengan Pemilik dan Tarikh; (5) Pelarasan Bajet yang Diluluskan; (6) Tarikh Ulasan Berikutnya. Petik kenyataan hadirin sebagaimana asal. Tandakan KPI yang tersasar >10% dengan amber."},
          {'instr':'**(1) Di Teams**, buka **Calendar** → klik mesyuarat **"Negotiating Marketing Contract"**. Pada halaman Recap, terangkan **AI Notes**, **Custom summary**, dan **Audio recap**. **(2) Di Word for the Web**, buka dokumen kosong baharu. Taip rangka minit perundingan vendor — tujuh tajuk kosong: Vendor dan Pemilik · Terma Komersial · Konsesi Ditawarkan · Konsesi Diterima · Item Terbuka · Ambang Kelulusan · Langkah Seterusnya. **(3) Klik ikon Copilot** di ribbon Word dan tampal prompt di bawah — kemudian majukan hasilnya kepada Procurement, Legal dan Pengarah Kewangan Kumpulan.', 'prompt':"Hasilkan minit mesyuarat untuk mesyuarat Teams /Negotiating Marketing Contract. Gunakan templat kosong perundingan vendor yang sudah ada. Bahagian: (1) Vendor dan Pemilik; (2) Terma Komersial; (3) Konsesi Ditawarkan; (4) Konsesi Diterima; (5) Item Terbuka; (6) Ambang Kelulusan (CFO / Lembaga); (7) Langkah Seterusnya dengan Pemilik dan Tarikh. Tandakan terma yang memerlukan kelulusan CFO dengan amber dan Lembaga dengan merah.. Kemudian e-mel pautan kepada Procurement, Legal dan Pengarah Kewangan Kumpulan."}
        ],
        persona=['Sasha Ouellet', 'Sasha Ouellet', 'Sasha Ouellet'],
        personaID=['Sasha Ouellet', 'Sasha Ouellet', 'Sasha Ouellet']
      ),

      tool(T_NOTEBOOK, M365_LIC, M365_ACCT, [
        {'instr':'All sources are loaded in the notebook (see Notebook setup above). The Instructions field is set. Type the prompt below in the notebook chat.',
         'prompt':'Synthesise across all 5 sources to produce a 10-bullet Board narrative for Friday. Cover: the Rp 60B live-shopping trade-spend overrun in plain language, the worst 5 SKUs by margin loss, the recall status by market, the 3 levers we will pull in 90 days, and the FY2026 promo guardrails we will table for approval. Cite the source file (and tab/section where applicable) at the end of every bullet.'},
        {'instr':'In the same notebook, click **Quick Create** > **Audio Overview** to generate a 6-minute podcast-style summary; OR click **Quick Create** > **Page** to generate a collaborative Page the leadership team can comment on.',
         'prompt':'Quick Create: Audio Overview, 6 minutes, formal narration tone, focused on the Board narrative above. Listeners are the 6 Brand-House GMs who will be on a flight on Thursday and need to walk into the Friday Board meeting prepared.'}
      ], DESC_NOTEBOOK,
      promptsID=[
        {'instr':'Semua sumber sudah dimuat di notebook (lihat setup Notebook di atas). Field Instructions sudah diset. Ketik prompt di bawah pada chat notebook.',
         'prompt':'Sintesakan dari kelima sumber untuk menghasilkan narasi Direksi 10-bullet untuk Jumat. Mencakup: pembengkakan trade-spend Rp 60 miliar dengan bahasa sederhana, 5 SKU terburuk dari sisi kehilangan margin, status recall per pasar, 3 lever yang akan kami tarik dalam 90 hari, dan guardrail promo FY2026 yang akan diajukan untuk disetujui. Kutip file sumber (dan tab/bagian bila relevan) di akhir tiap bullet.'},
        {'instr':'Pada notebook yang sama, klik **Quick Create** > **Audio Overview** untuk menghasilkan ringkasan podcast 6 menit; ATAU klik **Quick Create** > **Page** untuk menghasilkan Page kolaboratif yang bisa dikomentari tim leadership.',
         'prompt':'Quick Create: Audio Overview, 6 menit, gaya narasi formal, fokus pada narasi Direksi di atas. Pendengar adalah 6 GM Brand House yang akan terbang Kamis dan butuh siap hadir Rapat Direksi Jumat.'}
      ],
      persona=['Mod Admin','Mod Admin'],
      personaID=['Mod Admin','Mod Admin'],
      notebookMeta={
        'sources':['/COSMETICS_01_BPOM_Notifikasi_Tracker.xlsx','/COSMETICS_02_SKU_Margin_Tracker.xlsx','/COSMETICS_03_Ingredient_Recall_Programme.docx','/COSMETICS_04_TiO2_Surfactant_Hedge_Book.xlsx','/COSMETICS_05_FY2026_Live_Shopping_Guardrails.docx'],
        'instructions':'You are the Group CFO of Contoso Beauty Innovation preparing a Friday Board pack. Cover trade-spend control, the active hydroquinone-contamination recall in MY/SG/ID, gross-margin recovery, and FY2026 promo guardrails. Always cite the source file and tab/section. Tone: precise, Board-ready, no speculation. Convert IDR to MYR at 1 MYR = 3,580 IDR when reporting Group totals.',
        'instructionsID':'Anda adalah Direktur Keuangan Grup Contoso Beauty Innovation yang menyiapkan paket Direksi Jumat. Cakup kendali trade-spend, recall kontaminasi hidrokuinon aktif di MY/SG/ID, pemulihan gross margin, dan guardrail promo FY2026. Selalu kutip file sumber dan tab/bagian. Nada: presisi, siap-Direksi, tanpa spekulasi. Konversi IDR ke MYR pada 1 MYR = 3.580 IDR saat melaporkan total Grup.'
      }),

      tool(T_COWORK, FRONTIER_LIC, M365_ACCT, [
        {'instr':'Open `m365.cloud.microsoft` > left nav > **Agents** > **Cowork**. Paste the single prompt below — Cowork delegates 5 parallel sub-tasks and reports back with one consolidated status panel. Frontier program required.',
         'prompt':'Cowork — Trade-Spend Sprint. Run these 5 tasks in parallel and report back: (1) 📝 Draft a Word doc — Q4 Trade-Spend Variance Brief, 4 pages, audience Group ExCo, sources /COSMETICS_01_BPOM_Notifikasi_Tracker.xlsx and /COSMETICS_05_FY2026_Live_Shopping_Guardrails.docx. (2) 📝 Draft a Word doc — Recall Holding Lines for BPOM/MOH/SFA, 1 page each, source /COSMETICS_03_Ingredient_Recall_Programme.docx. (3) ✉️ Send an email to the 6 Brand-House GMs and the Group Trade-Marketing Director summarising the variance and asking for 3 corrective levers each, due in 48 hours. (4) 📅 Schedule a 60-minute Group ExCo meeting tomorrow 9am MYT titled "Trade-Spend Crisis Alignment — Pre-Board". (5) 💬 Post a Teams message to the #group-exco channel with a one-line headline of the variance and a link to the dashboard. Use these named recipients consistently across the email task and the Teams meeting task — Hadar (Group CFO), Sasha (Group Chief of Staff), Daichi (Head of Investor Relations), Sonia (Head of Strategy), Will (Head of Risk) and Omar (Head of Procurement) — and adapt the precise distribution per sub-task to keep each communication focused on the right audience.'}
      ], DESC_COWORK,
      promptsID=[
        {'instr':'Buka `m365.cloud.microsoft` > nav kiri > **Agents** > **Cowork**. Tempel prompt tunggal di bawah — Cowork mendelegasikan 5 sub-tugas paralel dan melaporkan kembali dengan satu panel status terkonsolidasi. Membutuhkan program Frontier.',
         'prompt':'Cowork — Sprint Trade-Spend. Jalankan 5 tugas berikut paralel dan laporkan kembali: (1) 📝 Susun dokumen Word — Brief Selisih Trade-Spend Q4, 4 halaman, audiens Group ExCo, sumber /COSMETICS_01_BPOM_Notifikasi_Tracker.xlsx dan /COSMETICS_05_FY2026_Live_Shopping_Guardrails.docx. (2) 📝 Susun dokumen Word — Holding Line Recall untuk BPOM/KKM/SFA, 1 halaman per regulator, sumber /COSMETICS_03_Ingredient_Recall_Programme.docx. (3) ✉️ Kirim email ke 6 GM Brand House dan Direktur Trade-Marketing Grup yang merangkum selisih dan meminta 3 lever perbaikan dari masing-masing dalam 48 jam. (4) 📅 Jadwalkan rapat Group ExCo 60 menit besok pukul 09:00 WIB berjudul "Penyelarasan Krisis Trade-Spend — Pre-Direksi". (5) 💬 Posting pesan Teams di channel #group-exco dengan headline satu baris selisih dan tautan ke dashboard. Use these named recipients consistently across the email task and the Teams meeting task — Hadar (Group CFO), Sasha (Group Chief of Staff), Daichi (Head of Investor Relations), Sonia (Head of Strategy), Will (Head of Risk) and Omar (Head of Procurement) — and adapt the precise distribution per sub-task to keep each communication focused on the right audience.'}
      ],
      persona=['Mod Admin'],
      personaID=['Mod Admin']),

      tool(T_WORD_AGT, ANY_LIC, ANY_ACCT, [
        {'instr':'Open `m365.cloud.microsoft/chat` and sign in. In the prompt box click the **Tools** menu (or **Agents** menu) and choose **Word**. Paste the prompt below — Copilot generates a complete `.docx` preview in chat, asks any clarifying questions on tone/length/audience, then saves the finished file to OneDrive. Open it in Word to review and polish. Works **with or without** a Microsoft 365 Copilot license — with a Copilot license, Copilot can ground in tenant files/emails/chats/meetings; without a license, Copilot uses the public web plus any file you reference inline.',
         'prompt':'I am working under a tight deadline and the work product needs to be airtight, so please be thorough rather than terse. Q4 FY2025 trade-spend overran by Rp 60B, Salmonella recall active in MY/SG/ID, Board on Friday. Here is exactly what I need from you. Generate a 4-page Group CFO Trade-Spend & Recall Brief in Word. Ground every part of your answer in the inputs that follow, and walk through them methodically rather than skimming. Reference /COSMETICS_01_BPOM_Notifikasi_Tracker.xlsx (Channel Spend tab) and /COSMETICS_03_Ingredient_Recall_Programme.docx. When you reply, organise the output as described below so I can lift it straight into my deliverable without reformatting. Sections — Executive Summary 5 bullets, Trade-Spend Bridge plain English, Recall Status by Market, Margin Recovery Levers with MYR impact, FY2026 Promo Guardrails proposal, Decisions Requested. Tone: precise, Board-ready, no speculation. Save as CFO_TradeSpend_Recall_Brief.docx. Be specific, attach a citation or sheet/tab/cell reference to every quantitative claim, and if anything is missing or contradictory call it out explicitly with the question I should ask next so nothing slips before the deadline.'}
      ], DESC_WORD_AGT,
      promptsID=[
        {'instr':'Buka `m365.cloud.microsoft/chat` dan login. Pada kotak prompt klik menu **Tools** (atau menu **Agents**) lalu pilih **Word**. Tempel prompt di bawah — Copilot menghasilkan preview `.docx` lengkap di chat, bertanya jika ada hal perlu diklarifikasi (nada/panjang/audiens), kemudian menyimpan file ke OneDrive. Buka di Word untuk review dan polishing akhir. Berfungsi **dengan maupun tanpa** lisensi Microsoft 365 Copilot — dengan lisensi Copilot grounding ke file/email/chat/meeting tenant; tanpa lisensi Copilot pakai web publik + file apapun yang Anda referensikan dalam prompt.',
         'prompt':'Saya sedang mengerjakan ini dengan tenggat yang ketat dan hasil akhirnya harus rapi, jadi mohon jawab dengan tuntas, jangan ringkas. Trade-spend Q4 FY2025 over Rp 60 miliar, recall kontaminasi hidrokuinon aktif di MY/SG/ID, Direksi Jumat. Berikut yang saya butuhkan dari Anda secara persis. Hasilkan Brief Trade-Spend & Recall Direktur Keuangan Grup 4 halaman dalam Word. Grounding setiap bagian jawaban Anda pada masukan berikut, telaah satu per satu, jangan dilewati. Referensikan /COSMETICS_01_BPOM_Notifikasi_Tracker.xlsx (tab Channel Spend) dan /COSMETICS_03_Ingredient_Recall_Programme.docx. Saat menjawab, susun keluaran sesuai format di bawah ini agar dapat langsung saya gunakan di deliverable tanpa perlu format ulang. Bagian — Ringkasan Eksekutif 5 bullet, Bridge Trade-Spend bahasa sederhana, Status Recall per Pasar, Lever Pemulihan Margin dengan dampak Rp Miliar, Proposal Guardrail Promo FY2026, Keputusan yang Diminta. Nada: presisi, siap-Direksi, tanpa spekulasi. Simpan sebagai Brief_TradeSpend_Recall_Direktur_Keuangan.docx. Tegas, cantumkan kutipan atau referensi sheet/tab/cell untuk setiap angka, dan bila ada yang kurang atau bertentangan, sebutkan secara eksplisit beserta pertanyaan tindak lanjut yang harus saya ajukan agar tidak ada yang terlewat sebelum tenggat.'}
      ],
      persona=['Sasha Ouellet'],
      personaID=['Sasha Ouellet']),

      tool(T_PPT_AGT, ANY_LIC, ANY_ACCT, [
        {'instr':'Open `m365.cloud.microsoft/chat` and sign in. In the prompt box click the **Tools** menu (or **Agents** menu) and choose **PowerPoint**. Paste the prompt below — Copilot generates a complete `.pptx` preview in chat, asks any clarifying questions on theme/audience/slide count, then saves the finished file to OneDrive. Open it in PowerPoint to review and polish. Works **with or without** a Microsoft 365 Copilot license — with a Copilot license, Copilot can ground in tenant content; without a license, Copilot uses the public web plus any file you reference inline.',
         'prompt':'I am working under a tight deadline and the work product needs to be airtight, so please be thorough rather than terse. Friday Board. Here is exactly what I need from you. Build a 10-slide Board deck on Q4 FY2025 live-shopping trade-spend overrun and recall. Ground every part of your answer in the inputs that follow, and walk through them methodically rather than skimming. Reference my Word brief /CFO_TradeSpend_Recall_Brief.docx and trade-spend dashboard /COSMETICS_01_BPOM_Notifikasi_Tracker.xlsx. When you reply, organise the output as described below so I can lift it straight into my deliverable without reformatting. Cover, Situation, Bridge waterfall (2 slides), Recall by market, Levers (2 slides), FY2026 Guardrails, Decisions, Appendix. Brand colours #F59E0B + #0F1C3F, 18pt minimum body text, 1 chart per slide. Save as Q4_TradeSpend_Recall_BoardDeck.pptx. Be specific, attach a citation or sheet/tab/cell reference to every quantitative claim, and if anything is missing or contradictory call it out explicitly with the question I should ask next so nothing slips before the deadline.'}
      ], DESC_PPT_AGT,
      promptsID=[
        {'instr':'Buka `m365.cloud.microsoft/chat` dan login. Pada kotak prompt klik menu **Tools** (atau menu **Agents**) lalu pilih **PowerPoint**. Tempel prompt di bawah — Copilot menghasilkan preview `.pptx` lengkap di chat, bertanya jika ada hal perlu diklarifikasi (tema/audiens/jumlah slide), kemudian menyimpan file ke OneDrive. Buka di PowerPoint untuk review dan polishing akhir. Berfungsi **dengan maupun tanpa** lisensi Microsoft 365 Copilot — dengan lisensi grounding ke konten tenant; tanpa lisensi pakai web publik + file referensi inline.',
         'prompt':'Saya sedang mengerjakan ini dengan tenggat yang ketat dan hasil akhirnya harus rapi, jadi mohon jawab dengan tuntas, jangan ringkas. Direksi Jumat. Berikut yang saya butuhkan dari Anda secara persis. Bangun deck Direksi 10 slide tentang pembengkakan trade-spend dan recall Q4 FY2025. Grounding setiap bagian jawaban Anda pada masukan berikut, telaah satu per satu, jangan dilewati. Referensikan brief Word saya /Brief_TradeSpend_Recall_Direktur_Keuangan.docx dan dashboard trade-spend /COSMETICS_01_BPOM_Notifikasi_Tracker.xlsx. Saat menjawab, susun keluaran sesuai format di bawah ini agar dapat langsung saya gunakan di deliverable tanpa perlu format ulang. Cover, Situasi, Waterfall Bridge (2 slide), Recall per Pasar, Lever (2 slide), Guardrail FY2026, Keputusan, Appendix. Warna brand #F59E0B + #0F1C3F, font tubuh minimum 18pt, 1 chart per slide. Simpan sebagai Deck_Direksi_TradeSpend_Recall_Q4.pptx. Tegas, cantumkan kutipan atau referensi sheet/tab/cell untuk setiap angka, dan bila ada yang kurang atau bertentangan, sebutkan secara eksplisit beserta pertanyaan tindak lanjut yang harus saya ajukan agar tidak ada yang terlewat sebelum tenggat.'}
      ],
      persona=['Sasha Ouellet'],
      personaID=['Sasha Ouellet']),

      tool(T_XL_AGT, ANY_LIC, ANY_ACCT, [
        {'instr':'Open `m365.cloud.microsoft/chat` and sign in. In the prompt box click the **Tools** menu (or **Agents** menu) and choose **Excel**. Paste the prompt below — Copilot generates a complete `.xlsx` preview in chat, asks any clarifying questions on sheets/columns/charts/formatting, then saves the finished file to OneDrive. Open it in Excel to review and polish. Works **with or without** a Microsoft 365 Copilot license — with a Copilot license, Copilot can ground in tenant data; without a license, Copilot uses the public web plus any file you reference inline.',
         'prompt':'I am working under a tight deadline and the work product needs to be airtight, so please be thorough rather than terse. 30-day rolling control workbook for the Group CFO. Here is exactly what I need from you. Build a BPOM Notifikasi + Margin Tracker workbook from scratch. Ground every part of your answer in the inputs that follow, and walk through them methodically rather than skimming. schema only — channels (modern-beauty retail, general trade, marketplace, live shopping), categories (colour cosmetics, skincare, haircare, personal wash, fragrance), 4 export markets (Malaysia, Singapore, Philippines, UAE). When you reply, organise the output as described below so I can lift it straight into my deliverable without reformatting. Sheet 1 Channel Spend (budget vs actual by month), Sheet 2 SKU Margin (top 50 SKUs Q3 vs Q4 GM), Sheet 3 Recall Cost Tracker (legal, logistics, replacement, halal recert, comms), Sheet 4 Dashboard with KPI tiles + RAG conditional formatting. Save as Cosmetics_BPOM_Notif_Margin_Tracker.xlsx. Be specific, attach a citation or sheet/tab/cell reference to every quantitative claim, and if anything is missing or contradictory call it out explicitly with the question I should ask next so nothing slips before the deadline.'}
      ], DESC_XL_AGT,
      promptsID=[
        {'instr':'Buka `m365.cloud.microsoft/chat` dan login. Pada kotak prompt klik menu **Tools** (atau menu **Agents**) lalu pilih **Excel**. Tempel prompt di bawah — Copilot menghasilkan preview `.xlsx` lengkap di chat, bertanya jika ada hal perlu diklarifikasi (sheet/kolom/chart/formatting), kemudian menyimpan file ke OneDrive. Buka di Excel untuk review dan polishing akhir. Berfungsi **dengan maupun tanpa** lisensi Microsoft 365 Copilot — dengan lisensi grounding ke data tenant; tanpa lisensi pakai web publik + file referensi inline.',
         'prompt':'Saya sedang mengerjakan ini dengan tenggat yang ketat dan hasil akhirnya harus rapi, jadi mohon jawab dengan tuntas, jangan ringkas. Workbook kontrol rolling 30-hari untuk Direktur Keuangan Grup. Berikut yang saya butuhkan dari Anda secara persis. Bangun workbook Tracker BPOM Notifikasi + Margin dari nol. Grounding setiap bagian jawaban Anda pada masukan berikut, telaah satu per satu, jangan dilewati. hanya skema — channel (modern-beauty retail, general trade, marketplace, live shopping), kategori (colour cosmetics, skincare, haircare, personal wash, fragrance), 4 pasar ekspor (Malaysia, Singapura, Filipina, UEA). Saat menjawab, susun keluaran sesuai format di bawah ini agar dapat langsung saya gunakan di deliverable tanpa perlu format ulang. Sheet 1 Channel Spend (anggaran vs aktual per bulan), Sheet 2 SKU Margin (50 SKU teratas GM Q3 vs Q4), Sheet 3 Recall Cost Tracker (legal, logistik, replacement, recert halal, komunikasi), Sheet 4 Dashboard dengan KPI tile + format kondisional RAG. Simpan sebagai Tracker_BPOM_Notif_Margin_Kosmetik.xlsx. Tegas, cantumkan kutipan atau referensi sheet/tab/cell untuk setiap angka, dan bila ada yang kurang atau bertentangan, sebutkan secara eksplisit beserta pertanyaan tindak lanjut yang harus saya ajukan agar tidak ada yang terlewat sebelum tenggat.'}
      ],
      persona=['Hadar Caspit'],
      personaID=['Hadar Caspit']),

      tool_builder(M365_LIC, M365_ACCT,
        agents=[
        {
          'icon': '🥫',
          'label': 'Brand & Beauty Velocity Coach',
          'name': 'Contoso Beauty Cosmetics — Brand & Beauty SKU Velocity Coach',
          'desc': 'Tracks Food & FMCG brand share (Wardah, Make Over, Emina, Kahf, Instaperfect, OMG!), SKU velocity, and live-shopping ROI by channel.',
          'instructions': 'You are the Contoso Beauty Cosmetics Brand & Beauty SKU Velocity Coach. You support Brand Marketing. Monitor velocity (COSMETICS_01_BPOM_Notifikasi_Tracker.xlsx), trade-spend (COSMETICS_03_Ingredient_Recall_Programme.docx), and channel mix (COSMETICS_05_FY2026_Live_Shopping_Guardrails.docx). Recommend trade-spend reallocation, range-edit, or campaign actions.',
          'knowledge': [
            {'file':'COSMETICS_01_BPOM_Notifikasi_Tracker.xlsx', 'note':'SKU velocity by channel.'},
            {'file':'COSMETICS_03_Ingredient_Recall_Programme.docx', 'note':'Trade-spend ROI tracker.'},
            {'file':'COSMETICS_05_FY2026_Live_Shopping_Guardrails.docx', 'note':'Channel-mix data.'}
          ],
          'knowledgeNote': 'Test: "Which 3 brand houses at Contoso Beauty are losing beauty-shelf share this quarter?"',
          'queries': [
            'Top 10 SKUs by velocity drop — recommended action per SKU.',
            'Which trade-spend programmes are ROI-negative? Recommend cancel.',
            'Draft the quarterly Brand Steering Committee paper.'
          ],
        },
        {
          'icon': '🏭',
          'label': 'Plant & R&D Coach',
          'name': 'Contoso Beauty Cosmetics — Plant & R&D Coach',
          'desc': 'Optimises Food & FMCG plant OEE, active-ingredient yield, PIF (Product Information File) currency, and supply-chain reliability.',
          'instructions': 'You are the Contoso Beauty Cosmetics Plant & R&D Coach. You support Manufacturing and Supply Chain. Monitor plant OEE (COSMETICS_02_SKU_Margin_Tracker.xlsx), raw-material yield, and OTIF (COSMETICS_04_TiO2_Surfactant_Hedge_Book.xlsx). Recommend maintenance, recipe, or supply-base actions.',
          'knowledge': [
            {'file':'COSMETICS_02_SKU_Margin_Tracker.xlsx', 'note':'Plant OEE & yield.'},
            {'file':'COSMETICS_04_TiO2_Surfactant_Hedge_Book.xlsx', 'note':'OTIF tracker.'}
          ],
          'knowledgeNote': 'Test: "Which 2 plants at Contoso Beauty have the worst OEE drag on the colour-cosmetics filling lines?"',
          'queries': [
            'Top 10 plant lines by OEE drag — recommended action.',
            'Which suppliers have OTIF deterioration? Tabulate and recommend escalation.',
            'Draft the monthly Manufacturing & Supply review paper.'
          ],
        },
        {
          'icon': '🏛️',
          'label': 'BPOM Notifikasi + LPPOM MUI Halal Liaison',
          'name': 'Contoso Beauty Cosmetics — Cosmetic Regulator Liaison',
          'desc': 'Prepares MOH / JAKIM (MY) / BPOM (ID) halal, ingredient-safety, and labelling filings for Contoso Beauty Cosmetics.',
          'instructions': 'You are the Contoso Beauty Cosmetics Cosmetic Regulator Liaison. Prepare halal, ingredient-safety, labelling, and recall filings grounded on the regulatory file (COSMETICS_05_FY2026_Live_Shopping_Guardrails.docx).',
          'knowledge': [],
          'knowledgeNote': 'Test: "Draft the response to BPOM\'s latest ingredient-safety circular for Contoso Beauty Cosmetics."',
          'queries': [
            "Prepare a cover letter for this quarter's LPPOM MUI + BPOM Notifikasi return.",
            'Which open recalls remain unclosed? Build closure plan.',
            "Draft the response letter to the regulator's latest notice."
          ],
        }
      ],
        agentsID=[
        {
          'icon': '🥫',
          'label': 'Brand & Beauty Velocity Pelatih',
          'name': 'Contoso Beauty Cosmetics — Brand & Beauty SKU Velocity Pelatih',
          'desc': 'Memantau Food & FMCG brand share (Wardah, Make Over, Emina, Kahf, Instaperfect, OMG!), SKU velocity, and live-shopping ROI by channel.',
          'instructions': 'Anda adalah Contoso Beauty Cosmetics Brand & Beauty SKU Velocity Pelatih. Anda mendukung Brand Marketing. Pantau velocity (COSMETICS_01_BPOM_Notifikasi_Tracker.xlsx), trade-spend (COSMETICS_03_Ingredient_Recall_Programme.docx), and channel mix (COSMETICS_05_FY2026_Live_Shopping_Guardrails.docx). Rekomendasikan trade-spend reallocation, range-edit, or campaign actions.',
          'knowledge': [
            {'file':'COSMETICS_01_BPOM_Notifikasi_Tracker.xlsx', 'note':'SKU velocity by channel.'},
            {'file':'COSMETICS_03_Ingredient_Recall_Programme.docx', 'note':'Trade-spend ROI tracker.'},
            {'file':'COSMETICS_05_FY2026_Live_Shopping_Guardrails.docx', 'note':'Channel-mix data.'}
          ],
          'knowledgeNote': 'Test: "Yang mana 3 brand house di Contoso Beauty losing beauty-shelf share kuartal ini?"',
          'queries': [
            '10 teratas SKUs by velocity drop — recommended tindakan per SKU.',
            'Yang mana trade-spend programmes are ROI-negative? Rekomendasikan cancel.',
            'Susun the kuartalan Brand Komite Pengarah paper.'
          ],
        },
        {
          'icon': '🏭',
          'label': 'Plant & R&D Pelatih',
          'name': 'Contoso Beauty Cosmetics — Plant & R&D Pelatih',
          'desc': 'Optimises Food & FMCG plant OEE, active-ingredient yield, PIF (Product Information File) currency, and supply-chain reliability.',
          'instructions': 'Anda adalah Contoso Beauty Cosmetics Plant & R&D Pelatih. Anda mendukung Manufacturing and Supply Chain. Pantau plant OEE (COSMETICS_02_SKU_Margin_Tracker.xlsx), raw-material yield, and OTIF (COSMETICS_04_TiO2_Surfactant_Hedge_Book.xlsx). Rekomendasikan maintenance, recipe, or supply-base actions.',
          'knowledge': [
            {'file':'COSMETICS_02_SKU_Margin_Tracker.xlsx', 'note':'Plant OEE & yield.'},
            {'file':'COSMETICS_04_TiO2_Surfactant_Hedge_Book.xlsx', 'note':'OTIF tracker.'}
          ],
          'knowledgeNote': 'Test: "Yang mana 2 plants Contoso Beauty have OEE drag terburuk di lini pengisian colour cosmetics?"',
          'queries': [
            '10 teratas plant lines by OEE drag — recommended tindakan.',
            'Yang mana suppliers have OTIF deterioration? Tabulasikan and rekomendasikan escalation.',
            'Susun the bulanan Manufacturing & Supply review paper.'
          ],
        },
        {
          'icon': '🏛️',
          'label': 'BPOM Notifikasi + LPPOM MUI Halal Penghubung',
          'name': 'Contoso Beauty Cosmetics — Cosmetic Regulator Penghubung',
          'desc': 'Prepares MOH / JAKIM (MY) / BPOM (ID) halal, ingredient-safety, and labelling filings for Contoso Beauty Cosmetics.',
          'instructions': 'Anda adalah Contoso Beauty Cosmetics Cosmetic Regulator Penghubung. Prepare halal, ingredient-safety, labelling, and recall filings grounded on the regulatory file (COSMETICS_05_FY2026_Live_Shopping_Guardrails.docx).',
          'knowledge': [],
          'knowledgeNote': 'Test: "Susun the response to BPOM\'s latest ingredient-safety circular for Contoso Beauty Cosmetics."',
          'queries': [
            "Prepare cover letter untuk LPPOM MUI + BPOM Notifikasi return kuartal ini.",
            'Yang mana open recalls remain unclosed? Bangun closure plan.',
            "Susun the response letter to the regulator's latest notice."
          ],
        }
      ],
        persona=['Mod Admin', 'Mod Admin', 'Mod Admin'],
        personaID=['Mod Admin', 'Mod Admin', 'Mod Admin']
      ),
    ],
    companyID='Contoso Beauty Innovation',
    taglineID='Trade-spend live-shopping Q4 FY2025 lebih Rp 60 M; recall SKU kontaminasi hidrokuinon di 3 pasar — paket Direksi 5 hari.',
    scenarioID='Contoso Beauty Innovation adalah grup kosmetik dan personal care Indonesia dengan 4 pabrik di Jababeka dan Cikande, memproduksi colour cosmetics, skincare, haircare, personal wash dan fragrance untuk lebih dari 300 SKU di lini Wardah, Make Over, Emina, Kahf, Instaperfect, Wardah Perfect Bright dan OMG!. Trade-spend live-shopping Q4 FY2025 melebihi anggaran Rp 60 miliar (+22%) terutama karena agresivitas insentif TikTok Shop dan Shopee Live serta sell-through beauty modern trade (Sociolla, Watsons, Guardian) yang melemah. Temuan hidrokuinon di atas ambang pada dua SKU Wardah Perfect Bright memicu recall pencegahan di Malaysia dan Singapura — BPOM Indonesia (Notifikasi Kosmetik), NPRA / KKM Malaysia dan HSA Singapura semuanya membuka kasus, dan kepatuhan US MoCRA untuk lini ekspor sedang diteliti ulang. Biaya titanium dioxide (TiO2) dan surfaktan turunan sawit melonjak 18% dari volatilitas specialty chemicals global, menekan margin pada 4 SKU colour cosmetics dan personal wash terlaris. Direktur Keuangan Grup butuh paket Direksi dalam 5 hari yang mencakup pengendalian trade-spend live-shopping, program remediasi recall bahan aktif, pemulihan gross margin colour cosmetics + personal wash, dan guardrail live-shopping + creator-affiliate FY2026. Frame customer riil: grup ini beroperasi serupa dengan Contoso Beauty Innovation (Wardah, Make Over, Emina, Kahf), Mandom Indonesia (Gatsby, Pixy), Mustika Ratu, Martina Berto (Sariayu), Kao Indonesia (Biore), L\u2019Oréal Indonesia, Unilever Indonesia (Personal Care) dan Cosmax Indonesia.',
    relevantDepts=['dept-finance','dept-strategy','dept-legal','dept-risk','dept-operations','dept-marketing','dept-it-digital'],
    personas=[
      {'name':'Hadar Caspit','role':'Group CFO','roleID':'Direktur Keuangan Grup','acct':'admin@ABSx62256373.onmicrosoft.com','lic':'Microsoft 365 Copilot','color':'#1E40AF'},
      {'name':'Sasha Ouellet','role':'Group Chief of Staff','roleID':'Kepala Staf Grup','acct':'SashaO@ABSx62256373.OnMicrosoft.com','lic':'Free — no Microsoft 365 Copilot license needed','color':'#7C3AED'},
      {'name':'Mod Admin','role':'Group Strategy Director','roleID':'Direktur Strategi Grup','acct':'admin@ABSx62256373.onmicrosoft.com','lic':'Microsoft 365 Copilot','color':'#059669'},
      {'name':'Daichi Maruyama','role':'Group Head of Regulatory & Halal Compliance','roleID':'Direktur Regulatory & Halal Compliance Grup','acct':'admin@ABSx62256373.onmicrosoft.com','lic':'Microsoft 365 Copilot','color':'#DC2626'}
    ],
    storyboard=[
      {'ex':1,'title':'Research & Brief','titleID':'Riset & Pengarahan','minutes':18,'mode':'Show & Tell + Hands-on',
       'summary':'Frame the Rp 60B live-shopping trade-spend overrun and the active recall; pull deep ASEAN peer benchmarks before the Group CFO walks into the Board on Friday.',
       'summaryID':'Bingkai pembengkakan trade-spend Rp 60 M dan recall aktif; tarik benchmark peer ASEAN mendalam sebelum Direktur Keuangan Grup masuk Rapat Direksi Jumat.',
       'tasks':[
         {'verb':'Frame the morning question and lock the day priorities','verbID':'Susun pertanyaan pagi dan kunci prioritas hari ini','toolId':T_CHAT,'mode':'Show & Tell'},
         {'verb':'Run an outside-in peer scan and pull proven plays','verbID':'Lakukan pemindaian peer dari luar dan tarik praktik terbaik','toolId':T_RESEARCHER,'mode':'Show & Tell'},
         {'verb':'Generate a board-ready brief straight from chat','verbID':'Hasilkan brief siap-Direksi langsung dari chat','toolId':T_WORD_AGT,'mode':'Hands-on'}]},
      {'ex':2,'title':'Analyse & Decide','titleID':'Analisis & Putuskan','minutes':18,'mode':'Hands-on',
       'summary':'Quantify the live-shopping trade-spend variance and SKU-level margin drag; build a Board-ready dashboard.',
       'summaryID':'Kuantifikasi selisih trade-spend live-shopping dan drag margin per SKU; bangun dashboard siap-Direksi.',
       'tasks':[
         {'verb':'Crunch the numbers and surface the biggest gaps','verbID':'Olah angka dan ungkap celah terbesar','toolId':T_ANALYST,'mode':'Hands-on'},
         {'verb':'Build a single-pane operating dashboard','verbID':'Bangun dashboard operasi satu-halaman','toolId':T_EXCEL,'mode':'Hands-on'},
         {'verb':'Spin up a recurring tracker workbook from chat','verbID':'Buat workbook tracker berulang dari chat','toolId':T_XL_AGT,'mode':'Hands-on'}]},
      {'ex':3,'title':'Communicate & Coordinate','titleID':'Komunikasi & Koordinasi','minutes':18,'mode':'Hands-on',
       'summary':'Brief the 6 Brand-House GMs, capture the Live-Shopping & Recall Crisis Review meeting, and assemble the Board deck.',
       'summaryID':'Brief 6 GM Brand House, capture rapat Live-Shopping & Recall Crisis Review, dan rakit deck Direksi.',
       'tasks':[
         {'verb':'Draft the stakeholder alignment email','verbID':'Draf email penyelarasan stakeholder','toolId':T_OUTLOOK,'mode':'Hands-on'},
         {'verb':'Recap the meeting and turn it into minutes','verbID':'Recap rapat dan ubah ke notulen','toolId':T_TEAMS,'mode':'Hands-on'},
         {'verb':'Generate a board-ready deck from chat','verbID':'Hasilkan deck siap-Direksi dari chat','toolId':T_PPT_AGT,'mode':'Hands-on'},
         {'verb':'Delegate a 5-task parallel sprint','verbID':'Delegasikan 5-tugas paralel ke Cowork','toolId':T_COWORK,'mode':'Show & Tell'}]},
      {'ex':4,'title':'Build & Scale','titleID':'Bangun & Skala','minutes':15,'mode':'Show & Tell',
       'summary':'Wrap the live-shopping + regulatory playbook into a reusable agent so the 6 Brand-House GMs can self-serve.',
       'summaryID':'Bungkus playbook live-shopping + regulatory ke dalam agent reusable agar 6 GM Brand House dapat self-service.',
       'tasks':[
         {'verb':'Pull every source into one synthesis notebook','verbID':'Tarik semua sumber ke satu notebook sintesis','toolId':T_NOTEBOOK,'mode':'Show & Tell'},
         {'verb':'Wrap the daily workflow into a reusable agent','verbID':'Bungkus alur kerja harian jadi agen yang dapat dipakai ulang','toolId':T_BUILDER,'mode':'Show & Tell'}]}
    ],
    geo='ID'
))
