
import sys; sys.path.insert(0,'.')
from util import *

INDUSTRIES_2 = [

# ── INVESTMENT BANKING ─────────────────────────────────────────────────────
ind('investment-banking','banking-fs','Investment Banking','💹','#0D47A1','#1565C0',
    'Aruna Capital Markets Berhad',
    'Three Bursa mandates are slipping, SC queries are rising, and fee concentration is threatening FY2026 earnings.',
    "Aruna Capital Markets Berhad is a Malaysian investment bank with equity capital markets, advisory, and fund management licences. Three Bursa Malaysia IPO mandates in the current pipeline account for a disproportionate share of the next two quarters' fee plan, but two issuers are now facing valuation pushback from cornerstone investors, slower legal diligence, and fresh disclosure questions from the Securities Commission Malaysia. At the same time, the proposed ESG fund launch has to clear tighter sustainability-labelling scrutiny, with management worried about greenwashing exposure if the methodology in the regulatory pack is not tightened before distribution. Treasury has also flagged settlement and FX timing pressure if one cross-border transaction closes while Bank Negara Malaysia keeps liquidity conditions tight. The Indonesian affiliate, PT Aruna Kapital Sekuritas Tbk, is managing similar execution risk as OJK review comments slow an IDX pipeline and Bank Indonesia volatility changes client funding assumptions. Senior management has ten days to decide which mandates to defend, which clients need partner-level intervention, and whether the ESG launch should proceed on time.",
    ['IB_01_Deal_Pipeline.xlsx', 'IB_02_Client_Relationship_Map.docx', 'IB_03_Regulatory_Compliance_Pack.docx'],
    [
      tool(T_CHAT, FREE_LIC, FREE_ACCT, [
        'You are the Head of Equity Capital Markets at Aruna Capital Markets Berhad. Using IB_01_Deal_Pipeline.xlsx, especially the Live Mandates and Deal Metrics tabs, assess which of the three IPO mandates is most likely to miss quarter-end close, what evidence supports that view, and what question the deal committee should ask first for each mandate. Flag mandates likely to slip this quarter as Red, mandates recoverable with immediate senior intervention as Amber, and mandates still on plan as Green. Present as a RAG table.',
        'You are the Head of Client Coverage at Aruna Capital Markets Berhad. Using the Fee Revenue Tracker tab in IB_01_Deal_Pipeline.xlsx and IB_02_Client_Relationship_Map.docx, identify which client relationships are over-concentrated, where we have weak sponsor access, and which cross-sell angle is most credible if an IPO is delayed. Rank the top five coverage priorities for the next ten days and explain the commercial downside if each is ignored. Present as a table with columns for Client, Revenue Exposure, Relationship Gap, Immediate Action, and Escalation Owner.',
        'You are the Chief Compliance Officer at Aruna Capital Markets Berhad. Using IB_03_Regulatory_Compliance_Pack.docx and the Pitch Calendar tab in IB_01_Deal_Pipeline.xlsx, identify the near-term SC Malaysia, Bursa Malaysia, and BNM touchpoints that could become problematic if two mandates slip while the ESG fund launch stays on its current timetable. Distinguish disclosure risk, conduct risk, and market-timing risk, then state what management should settle this week. Flag issues needing same-day escalation as Red, next-week action as Amber, and monitor-only matters as Green. Present as a RAG table.',
      ]),
      tool(T_RESEARCHER, FREE_LIC, FREE_ACCT, [
        'You are the Head of Equity Capital Markets at Aruna Capital Markets Berhad. Research Malaysian and Indonesian IPO transactions from 2023 to 2026 where listing timetables slipped because of valuation tension, regulatory comments, or weak bookbuilding, with emphasis on Bursa Malaysia and IDX. For each relevant case, identify the trigger, the sponsor or adviser response, the revised timetable, and the eventual outcome for proceeds and aftermarket performance. Flag any claim that could not be independently verified.',
        'You are the Head of Asset Management at Aruna Capital Markets Berhad. Research the current ESG fund disclosure and anti-greenwashing expectations that apply to Malaysian and Indonesian fund launches, focusing on SC Malaysia, OJK, and at least one comparable regional regime such as MAS or SFC. Compare what is mandatory, what is emerging market practice, and which disclosure failures have already attracted public scrutiny or enforcement attention. Flag any claim that could not be independently verified.',
        'You are the CFO of Aruna Capital Markets Berhad. Research how ASEAN investment banks and securities houses have managed fee concentration risk when two or three transactions dominate the revenue plan, especially during volatile equity issuance windows from 2022 to 2026. Summarise the mitigation levers used, how firms communicated internally about forecast reliability, and what indicators management watched most closely before re-basing guidance. Flag any claim that could not be independently verified.',
      ], DESC_RESEARCHER),
      tool(T_ANALYST, M365_LIC, M365_ACCT, [
        'You are the Head of Equity Capital Markets at Aruna Capital Markets Berhad. Upload IB_01_Deal_Pipeline.xlsx to Analyst and use the Live Mandates and Deal Metrics tabs to estimate probability-weighted fee revenue, close timing, and execution risk for each IPO mandate. Identify which milestone slippages matter most to quarter-end recognition and which mandate has the sharpest downside if valuation expectations are not reset this week. Flag mandates with a low probability of closing this quarter as Red, mandates with mixed signals as Amber, and mandates still broadly on schedule as Green. Present as a RAG table.',
        'You are the CFO of Aruna Capital Markets Berhad. Upload IB_01_Deal_Pipeline.xlsx to Analyst and compare the Fee Revenue Tracker and Tombstone Log tabs to assess revenue concentration, historical conversion rates by sector, and how much of FY2026 advisory income depends on the current top three deals. Show whether our live pipeline is stronger or weaker than the historical base rate and quantify the sensitivity if one mandate slips by one quarter. Present as a structured table with columns for Mandate, Forecast Fee, Historical Close Rate Proxy, Sensitivity, and Management Implication.',
        'You are the COO of Aruna Capital Markets Berhad. Upload IB_01_Deal_Pipeline.xlsx to Analyst and analyse the Pitch Calendar and Live Mandates tabs to determine whether banker capacity is being stretched across pitching, execution, and regulatory workstreams. Identify any clients that are receiving too little senior attention relative to revenue importance and whether the current calendar creates hidden bottlenecks before the SC filing deadline. Flag capacity gaps that could compromise a live deal as Red, overloaded but manageable situations as Amber, and balanced coverage as Green. Present as a RAG table.',
      ], DESC_ANALYST),
      tool(T_EXCEL, M365_LIC, M365_ACCT, [
        'Using the Live Mandates tab in this workbook, analyse sponsor readiness, diligence completeness, valuation tension, and regulatory dependency across the three IPO mandates in IB_01_Deal_Pipeline.xlsx. Create a new sheet called Deal Triage that ranks each mandate by probability-weighted close this quarter and summarises the two biggest blockers beside each issuer. Flag mandates likely to slip this quarter as Red, mandates needing immediate partner intervention as Amber, and mandates still executable as Green. Present as a RAG table.',
        'Using the Fee Revenue Tracker tab in this workbook, compare current quarter fee expectations with the historical close patterns in the Tombstone Log tab of IB_01_Deal_Pipeline.xlsx. Create a new sheet called Revenue Vulnerability that shows deal concentration, downside if one mandate slips, and whether replacement fees exist elsewhere in the pipeline. Flag exposures that could materially miss plan as Red, exposures that need active monitoring as Amber, and diversified fee streams as Green. Present as a RAG table.',
        'Using the Pitch Calendar tab in this workbook, assess whether senior banker time is aligned to the highest-value opportunities in IB_01_Deal_Pipeline.xlsx. Create a new sheet called Coverage Priorities that links the calendar to Deal Metrics, highlights where live mandates are under-covered, and shows which meetings can be deferred without harming conversion. Flag client situations that need same-week senior outreach as Red, next-week action as Amber, and lower-priority coverage as Green. Present as a RAG table.',
      ]),
      tool(T_WORD, M365_LIC, M365_ACCT, [
        'You are the Head of Equity Capital Markets at Aruna Capital Markets Berhad. Using IB_01_Deal_Pipeline.xlsx together with IB_03_Regulatory_Compliance_Pack.docx, draft a deal committee briefing that explains the status of the three live mandates, the revenue exposure if any slip, and the regulatory questions that could still derail execution. Separate facts, judgement calls, and decisions required from the committee. Flag mandates needing immediate committee direction as Red, heightened watchlist matters as Amber, and stable workstreams as Green. Present as a RAG table followed by a concise narrative.',
        'You are the Head of Client Coverage at Aruna Capital Markets Berhad. Using IB_02_Client_Relationship_Map.docx and the Fee Revenue Tracker insights from IB_01_Deal_Pipeline.xlsx, draft a relationship defence memo for management on the top five clients exposed to timetable slippage or reduced wallet share. Explain what each client values most, where our current sponsor access is weak, and which senior executive should intervene first. Present as a table followed by a short recommendation section.',
        'You are the Head of Product Governance at Aruna Capital Markets Berhad. Using IB_03_Regulatory_Compliance_Pack.docx, draft a readiness note for the proposed ESG fund launch that explains the methodology, the most material greenwashing vulnerabilities, and the approvals still needed before marketing can begin. Contrast what can proceed now versus what should wait until the policy wording is strengthened. Flag launch blockers as Red, remediation items as Amber, and completed requirements as Green. Present as a RAG table.',
      ]),
      tool(T_PPT, M365_LIC, M365_ACCT, [
        'You are the Head of Investment Banking at Aruna Capital Markets Berhad. Using IB_01_Deal_Pipeline.xlsx and IB_03_Regulatory_Compliance_Pack.docx, create a five-slide deal committee deck covering live mandate status, probability-weighted fee outcomes, the main execution blockers, and the decisions management must take in the next ten days. Keep each slide focused on one headline message and make the revenue risk explicit. Flag the most urgent issue on each slide as Red, Amber, or Green.',
        'You are the COO of Aruna Capital Markets Berhad. Using IB_01_Deal_Pipeline.xlsx and IB_02_Client_Relationship_Map.docx, create a five-slide management deck on client concentration and banker capacity risk. Show which relationships drive the fee plan, where calendar overload is hurting coverage quality, and what resource trade-offs management should make before quarter-end. End with a slide that prioritises interventions in Red, Amber, and Green order.',
        'You are the Head of Asset Management at Aruna Capital Markets Berhad. Using IB_03_Regulatory_Compliance_Pack.docx and the Deal Metrics tab in IB_01_Deal_Pipeline.xlsx, create a five-slide go or no-go deck for the ESG fund launch. Explain market opportunity, the strongest compliance arguments for proceeding, the main greenwashing exposures, and what a delayed launch would mean for FY2026 revenue mix. Present the risk summary as a RAG table.',
      ]),
      tool(T_OUTLOOK, M365_LIC, M365_ACCT, [
        'You are the Head of Equity Capital Markets at Aruna Capital Markets Berhad. Draft an email to the CEO and deal committee summarising the latest position on the three live mandates using the Live Mandates and Deal Metrics tabs in IB_01_Deal_Pipeline.xlsx as context. Explain what changed, where the biggest quarter-end fee risk now sits, and what decision you need from the committee before tomorrow. Keep the tone crisp, factual, and escalation-ready.',
        'You are the Chief Compliance Officer at Aruna Capital Markets Berhad. Draft a formal email to internal legal and the regulatory affairs team using IB_03_Regulatory_Compliance_Pack.docx as context, asking for immediate review of the outstanding SC Malaysia and Bursa Malaysia points on one live mandate and the ESG fund launch. Make clear which questions are interpretive, which are deadline-critical, and what management cannot approve until advice is received. Keep the tone controlled and precise.',
        'You are the Managing Director for Corporate Finance at Aruna Capital Markets Berhad. Draft a client email to a sponsor whose IPO timetable may move, using the status in the Live Mandates tab of IB_01_Deal_Pipeline.xlsx as context. Acknowledge market conditions and remaining diligence items, explain that we are protecting execution quality rather than forcing timing, and propose the next discussion. Keep the tone commercially sensitive and confidence-preserving.',
      ]),
      tool(T_TEAMS, M365_LIC, M365_ACCT, [
        'You are the Head of Investment Banking at Aruna Capital Markets Berhad. Using this recorded Teams meeting recap together with the Live Mandates and Fee Revenue Tracker tabs in IB_01_Deal_Pipeline.xlsx, identify every decision, unresolved issue, and action item affecting quarter-end fee recognition. Note which comments change the risk view on each live mandate and who owns the next step. Flag actions that must close before quarter-end as Red, actions due next week as Amber, and monitor-only items as Green. Present as a RAG table.',
        'You are the COO of Aruna Capital Markets Berhad. Using this recorded Teams meeting recap and IB_02_Client_Relationship_Map.docx as context, extract all client commitments, senior banker follow-ups, and any sign that relationship coverage is weakening on key accounts. Explain which commitments are still credible, which are at risk of being missed, and what escalation is needed. Present as a table with columns for Client, Commitment, Owner, Deadline, and Risk Level.',
        'You are the Chief Compliance Officer at Aruna Capital Markets Berhad. Using this recorded Teams meeting recap and IB_03_Regulatory_Compliance_Pack.docx as context, identify statements that could create conduct, disclosure, or greenwashing risk if repeated externally. Distinguish between acceptable internal judgement, problematic wording, and items requiring legal or compliance clarification before reuse. Flag same-day remediation items as Red, items to tighten before the next meeting as Amber, and acceptable wording as Green. Present as a RAG table.',
      ], DESC_TEAMS),
      tool(T_NOTEBOOK, M365_LIC, M365_ACCT, [
        'You are the CEO of Aruna Capital Markets Berhad. Upload IB_01_Deal_Pipeline.xlsx, IB_02_Client_Relationship_Map.docx, and IB_03_Regulatory_Compliance_Pack.docx to Copilot Notebook, and set the instruction to focus on mandate triage, revenue protection, and regulatory readiness. Ask Notebook to synthesise the ten-day management agenda, the biggest commercial and compliance contradictions across the files, and the three decisions that cannot be deferred. Flag priorities requiring immediate executive action as Red, next-week work as Amber, and monitor-only issues as Green. Present as a RAG table.',
        'You are the CFO of Aruna Capital Markets Berhad. Upload IB_01_Deal_Pipeline.xlsx and IB_03_Regulatory_Compliance_Pack.docx to Copilot Notebook. Ask Notebook to assess how much quarter-end fee recognition, capital planning, and regulatory workload change under three scenarios: all mandates close on time, one slips, or two slip while the ESG launch stays on schedule. Require the answer to cite the source file for every major conclusion and to present the summary as a RAG table.',
        'You are the Head of Client Coverage at Aruna Capital Markets Berhad. Upload IB_01_Deal_Pipeline.xlsx and IB_02_Client_Relationship_Map.docx to Copilot Notebook. Ask Notebook to identify which clients most need partner-level intervention, what evidence suggests wallet-share leakage, and where cross-sell into fund management or advisory is realistic if an IPO slips. Present the answer as a ranked table with a Red, Amber, or Green priority for each relationship.',
      ], DESC_NOTEBOOK),
      tool(T_COWORK, M365_LIC, M365_ACCT, [
        'You are the Head of Investment Banking at Aruna Capital Markets Berhad. Using IB_01_Deal_Pipeline.xlsx, IB_02_Client_Relationship_Map.docx, and IB_03_Regulatory_Compliance_Pack.docx as the source context, research comparable ASEAN IPO delays, draft a two-page mandate triage brief, save it to OneDrive, email it to the CEO and CFO, and schedule a 30-minute deal committee prep call for tomorrow morning. Keep the brief focused on revenue exposure, client rescue priorities, and regulatory blockers. End with a short RAG summary of the three live mandates.',
        'You are the COO of Aruna Capital Markets Berhad. Using IB_01_Deal_Pipeline.xlsx and IB_02_Client_Relationship_Map.docx as context, prepare a client coverage rescue pack, create a task list for the senior bankers who own the top five revenue relationships, email each owner their actions, and schedule check-in meetings before quarter-end. Make the deliverables explicit, prioritise the clients by fee dependence, and keep the tone urgent but controlled. Present the action summary as Red, Amber, and Green priorities.',
      ], DESC_COWORK),
      tool(T_EDIT_COPILOT, M365_LIC, M365_ACCT, [
        'You are the Chief Compliance Officer at Aruna Capital Markets Berhad. Using IB_03_Regulatory_Compliance_Pack.docx in Word for the web, add an appendix titled Mandate Escalation and ESG Launch Decision Rules that clarifies approval owners, escalation triggers, disclosure checkpoints, and what evidence is needed before marketing can proceed. Keep the language consistent with the current pack and highlight where SC Malaysia or Bursa Malaysia interpretation is still required. End with a short RAG summary table.',
        'Using the Live Mandates and Fee Revenue Tracker tabs in IB_01_Deal_Pipeline.xlsx, create a new worksheet called Quarter-End Revenue Watch in Excel for the web. Reorganise the information so management can see mandate stage, probability-weighted fee, key blocker, owner, and next milestone on one page, with the highest-risk items at the top. Flag high-slip-risk mandates as Red, active watchlist items as Amber, and stable mandates as Green. Present as a RAG table.',
      ], DESC_EDIT_COPILOT),
      tool(T_WORD_AGT, M365_LIC, M365_ACCT, [
        'You are the Chief Compliance Officer at Aruna Capital Markets Berhad. Using IB_03_Regulatory_Compliance_Pack.docx in Word for Web, create a declarative agent called Aruna Regulatory Guide that answers questions on IPO disclosure controls, ESG marketing safeguards, and approval authorities. Set the document as the knowledge source and share it with the investment banking, compliance, and product governance teams. Explain in the description that the agent should help staff distinguish policy requirements from judgement calls.',
        'You are the Head of Product Governance at Aruna Capital Markets Berhad. Demo the Aruna Regulatory Guide agent by asking how the ESG fund launch should be handled if two SC clarification points remain open while marketing materials are due next week, using IB_03_Regulatory_Compliance_Pack.docx as the source context. Then ask which approvals are required before a live IPO timetable can be revised externally. Present the demo outcome as a short table showing question, answer, and cited source section.',
      ], DESC_WORD_AGT),
      tool(T_PPT_AGT, M365_LIC, M365_ACCT, [
        'You are the Head of Investment Banking at Aruna Capital Markets Berhad. Using a PowerPoint summary of IB_01_Deal_Pipeline.xlsx and IB_03_Regulatory_Compliance_Pack.docx, create a declarative agent called Deal Committee Navigator that helps executives find the right slide, fee assumption, and regulatory point quickly. Share it with the CEO office and the deal committee only. Describe it as a guide for mandate triage and quarter-end decision support.',
        'You are the CFO of Aruna Capital Markets Berhad. Demo the Deal Committee Navigator agent by asking which live mandate has the largest probability-weighted fee gap, what blocker is driving that result, and which slide to open if the committee asks about ESG launch timing risk. Then ask for a summary of the two decisions management cannot defer this week. Present the demo as a short answer log with cited slide references.',
      ], DESC_PPT_AGT),
      tool(T_XL_AGT, M365_LIC, M365_ACCT, [
        'You are the COO of Aruna Capital Markets Berhad. Using IB_01_Deal_Pipeline.xlsx in Excel for Web, create a declarative agent called Pipeline Analytics Q and A that answers questions on live mandates, fee concentration, client exposure, and banker capacity. Share it with the ECM, advisory, and finance leadership teams. Make the description clear that answers should stay grounded in the workbook rather than unsupported assumptions.',
        'You are the Head of Equity Capital Markets at Aruna Capital Markets Berhad. Demo the Pipeline Analytics Q and A agent by asking which mandate has the lowest probability of closing this quarter based on the Live Mandates and Deal Metrics tabs, and what share of forecast fees the top two mandates represent using the Fee Revenue Tracker tab. Then ask whether the Pitch Calendar suggests any resourcing bottleneck before filing. Present the result as a concise table with the source tab named for each answer.',
      ], DESC_XL_AGT),
      tool(T_BUILDER, M365_LIC, M365_ACCT, [
        'You are the COO of Aruna Capital Markets Berhad. In Copilot Studio, create an agent called Aruna Deal Intelligence using IB_01_Deal_Pipeline.xlsx, IB_02_Client_Relationship_Map.docx, and IB_03_Regulatory_Compliance_Pack.docx as knowledge sources. Describe it as an assistant for senior bankers who need consistent answers on live mandate status, client priorities, ESG launch readiness, and regulatory checkpoints. Add a starter topic for Which mandate needs intervention first and publish it to Teams for the investment banking leadership group.',
        'You are the Head of Equity Capital Markets at Aruna Capital Markets Berhad. Demo Aruna Deal Intelligence by asking which of the three live mandates should be escalated first, what evidence supports that priority, and what management should tell the client this week, using the Live Mandates and Fee Revenue Tracker tabs plus IB_02_Client_Relationship_Map.docx as context. Then ask whether the ESG launch should proceed on schedule if the compliance pack still has open wording issues. Present the demo output as a RAG table.',
      ], DESC_BUILDER),
    ],
    companyID='PT Aruna Kapital Sekuritas Tbk',
    taglineID='Tiga mandat IDX tertahan, pertanyaan OJK meningkat, dan volatilitas rupiah menekan fee advisory kuartal depan.'
),

# ── GENERAL INSURANCE ─────────────────────────────────────────────────────
ind('general-insurance','insurance','General Insurance','🛡','#1A237E','#283593',
    'Prisma General Insurance Berhad',
    'Motor severity and claims leakage are lifting the combined ratio above plan, with reserve scrutiny looming.',
    'Prisma General Insurance Berhad is a Malaysian general insurer with a large motor and commercial property book. Claims frequency stayed elevated after a severe weather season, but the sharper problem is claims severity, where repair inflation, leakage, and questionable workshop behaviour are pushing the motor portfolio beyond target while the reserve margin has started to narrow. Management is also worried that detariffed pricing actions taken to defend market share are not fully compensating for the changing risk mix, especially in segments where underwriting discipline has weakened. BNM has asked for sharper explanations of reserve adequacy, reinsurance dependency, and the path back to a sustainable combined ratio before the next supervisory dialogue, while Bursa Malaysia investors are focused on whether earnings guidance still holds. The Indonesian listed affiliate, PT Asuransi Prisma Proteksi Tbk, is facing similar pressure as OJK reviews reserve assumptions, IDX investors question underwriting quality, and Bank Indonesia inflation keeps spare-parts costs high. The executive committee has two weeks to decide how hard to reprice, where to tighten claims controls, and whether reinsurance protection is still adequate for the current risk profile.',
    ['GI_01_Claims_Portfolio.xlsx', 'GI_02_Product_Manual.docx', 'GI_03_Risk_Management_Framework.docx'],
    [
      tool(T_CHAT, FREE_LIC, FREE_ACCT, [
        'You are the Chief Claims Officer at Prisma General Insurance Berhad. Using GI_01_Claims_Portfolio.xlsx, especially the Claims Register and Loss Ratio Tracker tabs, explain what is driving the deterioration in the motor book and where leakage looks most plausible. Separate pricing issues, operational issues, and potential fraud indicators, then state which management question should be answered first. Flag immediate intervention areas as Red, urgent follow-up items as Amber, and lower-priority issues as Green. Present as a RAG table.',
        'You are the Chief Underwriting Officer at Prisma General Insurance Berhad. Using the Underwriting Performance and Reinsurance Summary tabs in GI_01_Claims_Portfolio.xlsx, assess whether pricing, risk selection, or programme structure is the bigger reason the combined ratio is off plan. Explain which segment should be repriced first, which segment may need tighter underwriting rules instead, and what trade-off management is making between market share and margin. Present as a table with columns for Segment, Main Problem, Evidence, and Recommended Action.',
        'You are the CRO of Prisma General Insurance Berhad. Using GI_03_Risk_Management_Framework.docx and the Solvency II Dashboard tab in GI_01_Claims_Portfolio.xlsx, identify the risk themes that BNM, the Board Risk Committee, and investors are most likely to challenge over the next two weeks. Distinguish reserve adequacy risk, conduct risk, and capital volatility, and explain which issue would damage credibility most if management underestimates it. Flag matters needing immediate escalation as Red, matters for the next committee cycle as Amber, and stable areas as Green. Present as a RAG table.',
      ]),
      tool(T_RESEARCHER, FREE_LIC, FREE_ACCT, [
        'You are the Chief Claims Officer at Prisma General Insurance Berhad. Research how general insurers in Malaysia and Indonesia have responded from 2022 to 2026 when motor claims inflation, leakage, or workshop concentration pushed the combined ratio materially above plan. Focus on published examples that discuss reserve actions, anti-fraud measures, pricing moves, or reinsurance changes, and compare the supervisory stance taken by BNM and OJK where available. Flag any claim that could not be independently verified.',
        'You are the Chief Underwriting Officer at Prisma General Insurance Berhad. Research current market practice on motor repricing, portfolio pruning, and detariffication discipline among Malaysian general insurers, with any useful comparator evidence from Indonesia. Summarise where leading carriers accepted volume loss to repair margin, where they relied on tighter underwriting instead, and what market signals suggested the pricing correction was working. Flag any claim that could not be independently verified.',
        'You are the CRO of Prisma General Insurance Berhad. Research how regulators and listed insurers have discussed reserve adequacy, reinsurance dependence, and solvency pressure in public filings or supervisory commentary from 2023 to 2026, focusing on BNM, OJK, and listed insurance names on Bursa Malaysia or IDX. Distinguish mandatory regulatory expectations from management practice, and highlight any cases where weak communication amplified market concern. Flag any claim that could not be independently verified.',
      ], DESC_RESEARCHER),
      tool(T_ANALYST, M365_LIC, M365_ACCT, [
        'You are the Chief Claims Officer at Prisma General Insurance Berhad. Upload GI_01_Claims_Portfolio.xlsx to Analyst and use the Claims Register and Loss Ratio Tracker tabs to determine which products, geographies, or workshop clusters are driving the worst claims deterioration. Quantify whether frequency or severity is contributing more, identify where repeat patterns look abnormal, and show what proportion of the gap is concentrated in the top problem areas. Flag severe leakage or fraud risk areas as Red, ambiguous watchlist areas as Amber, and stable segments as Green. Present as a RAG table.',
        'You are the Chief Underwriting Officer at Prisma General Insurance Berhad. Upload GI_01_Claims_Portfolio.xlsx to Analyst and compare the Underwriting Performance and Reinsurance Summary tabs to assess whether pricing, acceptance standards, or reinsurance structure is doing the most damage to profitability. Show which segments could return to target through repricing alone and which need a deeper underwriting reset. Present as a table with columns for Segment, Loss Ratio Gap, Reinsurance Support, Recovery Lever, and Management Implication.',
        'You are the CFO of Prisma General Insurance Berhad. Upload GI_01_Claims_Portfolio.xlsx to Analyst and use the Solvency II Dashboard, Loss Ratio Tracker, and Reinsurance Summary tabs to assess the likely capital and earnings effect if current claims trends persist for two more quarters. Quantify the downside under base, adverse, and severe scenarios and identify the metrics management should watch weekly. Flag capital or reserve indicators at immediate risk as Red, elevated watch items as Amber, and stable measures as Green. Present as a RAG table.',
      ], DESC_ANALYST),
      tool(T_EXCEL, M365_LIC, M365_ACCT, [
        'Using the Claims Register tab in this workbook, analyse which claim types, workshops, and adjuster patterns are contributing most to the loss deterioration in GI_01_Claims_Portfolio.xlsx. Create a new sheet called Claims Leakage Watch that groups the strongest abnormal patterns, highlights concentration, and explains where a manual review queue should start. Flag likely leakage hotspots as Red, possible hotspots as Amber, and normal patterns as Green. Present as a RAG table.',
        'Using the Underwriting Performance tab in this workbook, assess where current pricing and risk selection no longer support the target combined ratio in GI_01_Claims_Portfolio.xlsx. Create a new sheet called Portfolio Reset that shows the segments needing repricing, tighter underwriting, or reduced line size, with a short rationale beside each segment. Flag segments needing immediate action as Red, medium-priority actions as Amber, and segments still acceptable as Green. Present as a RAG table.',
        'Using the Solvency II Dashboard and Reinsurance Summary tabs in this workbook, evaluate how claims deterioration and reinsurance dependence interact in GI_01_Claims_Portfolio.xlsx. Create a new sheet called Capital and Protection View that shows which solvency or retention indicators are moving out of tolerance and which treaty renewals matter most. Flag urgent pressure points as Red, emerging pressure points as Amber, and stable indicators as Green. Present as a RAG table.',
      ]),
      tool(T_WORD, M365_LIC, M365_ACCT, [
        'You are the Chief Claims Officer at Prisma General Insurance Berhad. Using GI_01_Claims_Portfolio.xlsx and GI_03_Risk_Management_Framework.docx, draft a board paper on why the motor portfolio has moved off plan and what management should do in the next ninety days. Separate the analysis into claims leakage, pricing adequacy, reserve sensitivity, and operational controls. Flag the biggest decision areas as Red, the next layer of management actions as Amber, and monitor-only issues as Green. Present as a RAG table followed by a concise narrative.',
        'You are the Chief Underwriting Officer at Prisma General Insurance Berhad. Using GI_02_Product_Manual.docx and the Underwriting Performance tab in GI_01_Claims_Portfolio.xlsx, draft a portfolio reset memo that explains which product or segment rules are no longer fit for current loss behaviour. Show where wording, exclusions, pricing assumptions, or underwriting authority should be tightened first. Present as a structured table followed by a short recommendation section.',
        'You are the CRO of Prisma General Insurance Berhad. Using GI_03_Risk_Management_Framework.docx and the Solvency II Dashboard tab in GI_01_Claims_Portfolio.xlsx, draft a supervisory readiness note for the next BNM discussion. Explain the main solvency and reserve questions management should expect, how reinsurance mitigates or fails to mitigate them, and what evidence is strongest in our favour. Flag key risk topics as Red, Amber, and Green in a RAG table.',
      ]),
      tool(T_PPT, M365_LIC, M365_ACCT, [
        'You are the CEO of Prisma General Insurance Berhad. Using GI_01_Claims_Portfolio.xlsx and GI_03_Risk_Management_Framework.docx, create a five-slide executive deck on the current combined ratio problem, the drivers of claims deterioration, the solvency implications, and the decisions management needs this month. Keep the storyline factual and recovery-focused, with one clear headline per slide. Present the risk summary as a RAG table.',
        'You are the Chief Claims Officer at Prisma General Insurance Berhad. Using the Claims Register and Loss Ratio Tracker tabs in GI_01_Claims_Portfolio.xlsx, create a five-slide investigation deck on leakage and abnormal claims patterns. Show where the data supports deeper review, what immediate operational controls are needed, and what financial benefit management could expect if the worst patterns are addressed. Flag the priority focus areas on each slide as Red, Amber, or Green.',
        'You are the Chief Underwriting Officer at Prisma General Insurance Berhad. Using the Underwriting Performance and Reinsurance Summary tabs in GI_01_Claims_Portfolio.xlsx plus GI_02_Product_Manual.docx, create a five-slide pricing and protection deck for the executive committee. Explain which segments require repricing, where underwriting rules should change, and whether current reinsurance structure still matches the risk profile. End with a RAG table showing priority actions.',
      ]),
      tool(T_OUTLOOK, M365_LIC, M365_ACCT, [
        'You are the Chief Claims Officer at Prisma General Insurance Berhad. Draft an internal email to the CEO and CFO using the Claims Register and Loss Ratio Tracker tabs in GI_01_Claims_Portfolio.xlsx as context, explaining where the biggest claims deterioration now sits and what immediate controls you recommend. Make clear what is known, what is still hypothesis, and what support you need from underwriting and finance this week. Keep the tone factual and escalation-ready.',
        "You are the CRO of Prisma General Insurance Berhad. Draft a formal email to the regulatory affairs team and internal stakeholders using GI_03_Risk_Management_Framework.docx and the Solvency II Dashboard tab in GI_01_Claims_Portfolio.xlsx as context, asking for final review before the next BNM discussion. Highlight reserve adequacy, reinsurance dependency, and management's proposed remediation path. Keep the tone measured and precise.",
        'You are the Chief Underwriting Officer at Prisma General Insurance Berhad. Draft an email to product and distribution leaders using GI_02_Product_Manual.docx and the Underwriting Performance tab in GI_01_Claims_Portfolio.xlsx as context, explaining that pricing and acceptance standards need review in selected segments. Ask for input on commercial impact, state the turnaround timeline, and make clear that profitability discipline now comes first. Keep the tone direct but collaborative.',
      ]),
      tool(T_TEAMS, M365_LIC, M365_ACCT, [
        'You are the Chief Claims Officer at Prisma General Insurance Berhad. Using this recorded Teams meeting recap together with the Claims Register and Loss Ratio Tracker tabs in GI_01_Claims_Portfolio.xlsx, identify every decision, unresolved issue, and action item linked to worsening claims performance. Note where the meeting changed the view on leakage, reserve risk, or operational control effectiveness. Flag same-week actions as Red, next-stage follow-ups as Amber, and monitor-only items as Green. Present as a RAG table.',
        'You are the Chief Underwriting Officer at Prisma General Insurance Berhad. Using this recorded Teams meeting recap and the Underwriting Performance tab in GI_01_Claims_Portfolio.xlsx as context, extract every statement that affects repricing, segment appetite, or distribution behaviour. Explain which ideas are supported by the data, which are commercially risky, and which need more analysis before a decision is made. Present as a table with columns for Issue, Comment, Data Support, Owner, and Next Step.',
        'You are the CRO of Prisma General Insurance Berhad. Using this recorded Teams meeting recap and GI_03_Risk_Management_Framework.docx as context, identify any comments that could weaken our external narrative on reserves, solvency, or claims governance if repeated outside the room. Distinguish between acceptable internal challenge, problematic wording, and items that need policy clarification before reuse. Flag urgent wording fixes as Red, medium-priority fixes as Amber, and acceptable content as Green. Present as a RAG table.',
      ], DESC_TEAMS),
      tool(T_NOTEBOOK, M365_LIC, M365_ACCT, [
        'You are the CEO of Prisma General Insurance Berhad. Upload GI_01_Claims_Portfolio.xlsx, GI_02_Product_Manual.docx, and GI_03_Risk_Management_Framework.docx to Copilot Notebook, and set the instruction to focus on combined ratio recovery, reserve credibility, and supervisory readiness. Ask Notebook to identify the three highest-conviction drivers of current underperformance, the biggest contradictions across claims, underwriting, and risk documents, and the decisions management cannot delay. Present the answer as a RAG table with citations to the source files.',
        'You are the CFO of Prisma General Insurance Berhad. Upload GI_01_Claims_Portfolio.xlsx and GI_03_Risk_Management_Framework.docx to Copilot Notebook. Ask Notebook to assess what happens to earnings, reserve confidence, and solvency if claims severity stays elevated for two more quarters and whether reinsurance materially changes that answer. Require citations for each conclusion and present the summary as Red, Amber, and Green priorities.',
        'You are the Chief Underwriting Officer at Prisma General Insurance Berhad. Upload GI_01_Claims_Portfolio.xlsx and GI_02_Product_Manual.docx to Copilot Notebook. Ask Notebook to identify which product or segment rules now appear misaligned with actual loss experience, where pricing needs a reset, and which customer or broker conversations management should prepare for first. Present the answer as a ranked table with a Red, Amber, or Green priority for each segment.',
      ], DESC_NOTEBOOK),
      tool(T_COWORK, M365_LIC, M365_ACCT, [
        'You are the Chief Claims Officer at Prisma General Insurance Berhad. Using GI_01_Claims_Portfolio.xlsx and GI_03_Risk_Management_Framework.docx as context, prepare a claims leakage action brief, save it to OneDrive, email it to the CEO, CFO, and CRO, and schedule a 30-minute review call for tomorrow morning. Keep the brief focused on abnormal claim patterns, reserve sensitivity, and the first controls to tighten. End with a short RAG summary of the focus areas.',
        'You are the Chief Underwriting Officer at Prisma General Insurance Berhad. Using GI_01_Claims_Portfolio.xlsx and GI_02_Product_Manual.docx as context, create a portfolio repricing and underwriting action tracker, assign the segment owners, email each owner their top two tasks, and schedule a checkpoint meeting before the next executive committee. Prioritise the actions by combined ratio repair potential and make the rationale visible. Present the action summary as Red, Amber, and Green priorities.',
      ], DESC_COWORK),
      tool(T_EDIT_COPILOT, M365_LIC, M365_ACCT, [
        'You are the CRO of Prisma General Insurance Berhad. Using GI_03_Risk_Management_Framework.docx in Word for the web, add an appendix titled Combined Ratio Deterioration Response Protocol that clarifies reserve governance, pricing escalation, claims leakage triggers, and decision rights before a BNM discussion. Keep the language aligned to the existing framework and highlight where management judgement must be documented. End with a short RAG summary table.',
        'Using the Loss Ratio Tracker and Reinsurance Summary tabs in GI_01_Claims_Portfolio.xlsx, create a new worksheet called Recovery Control Tower in Excel for the web. Reorganise the information so management can view segment loss pressure, reinsurance support, key owner, and next decision on one page with the worst problems first. Flag severe deterioration as Red, emerging pressure as Amber, and stable areas as Green. Present as a RAG table.',
      ], DESC_EDIT_COPILOT),
      tool(T_WORD_AGT, M365_LIC, M365_ACCT, [
        'You are the CRO of Prisma General Insurance Berhad. Using GI_03_Risk_Management_Framework.docx in Word for Web, create a declarative agent called Prisma Risk Governance Guide that answers questions on reserve oversight, combined ratio escalation, claims governance, and supervisory preparation. Set the document as the knowledge source and share it with the claims, underwriting, and finance leadership teams. Make the description clear that the agent should distinguish policy requirements from management judgement.',
        'You are the Chief Claims Officer at Prisma General Insurance Berhad. Demo the Prisma Risk Governance Guide agent by asking what governance steps are required when the motor portfolio loss ratio worsens but the root cause is still partly uncertain, using GI_03_Risk_Management_Framework.docx as the source context. Then ask which approvals are needed before management changes claims controls or reserve assumptions. Present the demo outcome as a short table showing question, answer, and cited source section.',
      ], DESC_WORD_AGT),
      tool(T_PPT_AGT, M365_LIC, M365_ACCT, [
        'You are the CEO of Prisma General Insurance Berhad. Using a PowerPoint summary of GI_01_Claims_Portfolio.xlsx and GI_03_Risk_Management_Framework.docx, create a declarative agent called Combined Ratio Briefing Navigator that helps executives find the right slide, chart, and risk message quickly. Share it with the executive committee and Board Risk Committee support team. Describe it as a guide for claims deterioration, pricing response, and solvency discussion points.',
        'You are the CFO of Prisma General Insurance Berhad. Demo the Combined Ratio Briefing Navigator agent by asking which segment is driving the largest gap versus plan, how much reinsurance is offsetting the pressure, and which slide to open if the Board asks about reserve credibility. Then ask it to summarise the two decisions management cannot defer before the BNM meeting. Present the demo as a short answer log with cited slide references.',
      ], DESC_PPT_AGT),
      tool(T_XL_AGT, M365_LIC, M365_ACCT, [
        'You are the Chief Underwriting Officer at Prisma General Insurance Berhad. Using GI_01_Claims_Portfolio.xlsx in Excel for Web, create a declarative agent called Claims and Pricing Analytics Q and A that answers questions on loss ratio movement, claims leakage, reinsurance support, and solvency indicators. Share it with claims, underwriting, and finance leadership. Make the description clear that answers must stay grounded in the workbook tabs.',
        'You are the CRO of Prisma General Insurance Berhad. Demo the Claims and Pricing Analytics Q and A agent by asking which segment shows the sharpest deterioration in the Loss Ratio Tracker tab, how the Reinsurance Summary tab changes the net exposure view, and whether the Solvency II Dashboard indicates immediate capital pressure. Present the result as a concise table with the source tab named for each answer.',
      ], DESC_XL_AGT),
      tool(T_BUILDER, M365_LIC, M365_ACCT, [
        'You are the COO of Prisma General Insurance Berhad. In Copilot Studio, create an agent called Prisma Claims and Underwriting Intelligence using GI_01_Claims_Portfolio.xlsx, GI_02_Product_Manual.docx, and GI_03_Risk_Management_Framework.docx as knowledge sources. Describe it as an assistant for claims, underwriting, and risk teams that answers questions on claims leakage, pricing discipline, product wording, reserve governance, and solvency readiness. Add a starter topic for Which segment needs intervention first and publish it to Teams for the executive insurance leadership group.',
        'You are the Chief Claims Officer at Prisma General Insurance Berhad. Demo Prisma Claims and Underwriting Intelligence by asking which motor claim patterns should be escalated first, what evidence supports that priority, and what control should be tightened immediately, using the Claims Register and Loss Ratio Tracker tabs plus GI_03_Risk_Management_Framework.docx as context. Then ask whether current reinsurance support materially changes the urgency of the response. Present the demo output as a RAG table.',
      ], DESC_BUILDER),
    ],
    companyID='PT Asuransi Prisma Proteksi Tbk',
    taglineID='Loss ratio kendaraan melonjak, cadangan klaim dipertanyakan OJK, dan tekanan harga pasar mengganggu profitabilitas.'
),

# ── LIFE INSURANCE ────────────────────────────────────────────────────────
ind('life-insurance','insurance','Life Insurance','💗','#283593','#3949AB',
    'Sentosa Life Assurance Berhad',
    'Early-duration lapses and softer bancassurance sales are eroding new business value ahead of stress testing.',
    'Sentosa Life Assurance Berhad is a Malaysian life insurer with a sizeable savings, protection, and bancassurance franchise. The in-force book is still profitable, but early-duration lapses have risen across several cohorts, first-year strain is staying elevated, and new business value is weakening because bancassurance momentum has cooled just as digital-first competitors are offering simpler onboarding and lower acquisition friction. Actuarial management is comfortable that the current capital position still exceeds minimum requirements, yet the trend in reserve strain, surrender behaviour, and channel productivity is moving in the wrong direction ahead of a BNM stress-testing cycle. Board members are also questioning whether the product mix is drifting toward lower-quality growth and whether management is being too optimistic about the recovery speed of the bank channel. The Indonesian affiliate, PT Asuransi Jiwa Sentosa Nusantara Tbk, is under similar pressure as OJK monitors persistency and capital resilience, IDX investors focus on margin quality, and Bank Indonesia rate conditions affect savings product competitiveness. Management has three weeks to decide whether to reset targets, reprice selected products, and accelerate a digitally enabled retention strategy.',
    ['LI_01_Policy_Portfolio.xlsx', 'LI_02_Product_Framework.docx', 'LI_03_Actuarial_Policy.docx'],
    [
      tool(T_CHAT, FREE_LIC, FREE_ACCT, [
        'You are the Chief Distribution Officer at Sentosa Life Assurance Berhad. Using LI_01_Policy_Portfolio.xlsx, especially the New Business Tracker and Bancassurance Performance tabs, explain why new business momentum is weakening and whether the bigger issue is channel productivity, product fit, or customer selection. Distinguish what management can influence quickly from what needs a structural response, and state which question the executive committee should answer first. Flag immediate priorities as Red, urgent watchlist items as Amber, and lower-priority items as Green. Present as a RAG table.',
        'You are the Chief Customer Officer at Sentosa Life Assurance Berhad. Using the In-Force Book and Lapse Analysis tabs in LI_01_Policy_Portfolio.xlsx, assess what the lapse pattern says about customer value, onboarding quality, and servicing pain points in the first three policy years. Explain which cohorts are most vulnerable, what behaviour appears reversible, and where management may be mistaking temporary noise for a deeper persistency problem. Present as a table with columns for Cohort, Main Issue, Evidence, and Recommended Action.',
        'You are the Appointed Actuary at Sentosa Life Assurance Berhad. Using LI_03_Actuarial_Policy.docx and the Actuarial Reserve Summary tab in LI_01_Policy_Portfolio.xlsx, identify the capital and reserve questions that BNM and the Board are most likely to ask if current lapse and sales trends persist. Distinguish between earnings strain, reserve adequacy, and business mix risk, then explain which issue would most undermine management credibility if ignored. Flag immediate escalation topics as Red, important follow-ups as Amber, and stable areas as Green. Present as a RAG table.',
      ]),
      tool(T_RESEARCHER, FREE_LIC, FREE_ACCT, [
        'You are the Chief Distribution Officer at Sentosa Life Assurance Berhad. Research how life insurers in Malaysia and Indonesia have responded from 2022 to 2026 when bancassurance productivity softened while digital entrants won younger customers. Focus on published examples that discuss channel redesign, digital enablement, product simplification, or target resetting, and compare the outcomes where possible. Flag any claim that could not be independently verified.',
        'You are the Appointed Actuary at Sentosa Life Assurance Berhad. Research how regulators, actuarial bodies, and listed life insurers have discussed persistency deterioration, early-duration lapse assumptions, and reserve stress from 2023 to 2026, with emphasis on BNM, OJK, and public disclosures on Bursa Malaysia or IDX. Distinguish mandatory expectations from management practice and highlight any cases where lapse assumptions became a governance issue. Flag any claim that could not be independently verified.',
        'You are the Chief Product Officer at Sentosa Life Assurance Berhad. Research product and distribution trends in Southeast Asian life insurance from 2023 to 2026, especially where insurers improved persistency or new business value by changing proposition design, bancassurance economics, or digital onboarding. Summarise the product features or operating changes that appear most linked to better retention and economics. Flag any claim that could not be independently verified.',
      ], DESC_RESEARCHER),
      tool(T_ANALYST, M365_LIC, M365_ACCT, [
        'You are the Chief Distribution Officer at Sentosa Life Assurance Berhad. Upload LI_01_Policy_Portfolio.xlsx to Analyst and use the New Business Tracker and Bancassurance Performance tabs to determine where channel productivity is weakening, whether the issue is concentrated by partner, product, or period, and what that implies for the next two quarters. Quantify the mix shift and show what share of the shortfall is explainable by bancassurance alone. Flag severe channel pressure as Red, mixed-signal areas as Amber, and resilient areas as Green. Present as a RAG table.',
        'You are the Chief Customer Officer at Sentosa Life Assurance Berhad. Upload LI_01_Policy_Portfolio.xlsx to Analyst and analyse the In-Force Book and Lapse Analysis tabs to identify the cohorts with the highest early-duration lapse risk, the products or channels associated with that risk, and the likely economic consequence if behaviour does not improve. Show which lapse patterns look structural versus temporary and which interventions are most likely to matter. Present as a table with columns for Cohort, Lapse Signal, Economic Impact, Likely Driver, and Management Action.',
        'You are the Appointed Actuary at Sentosa Life Assurance Berhad. Upload LI_01_Policy_Portfolio.xlsx to Analyst and use the Actuarial Reserve Summary, Lapse Analysis, and New Business Tracker tabs to test how current lapse and sales trends affect reserve strain, capital resilience, and business value over the next year. Quantify the downside under base, adverse, and severe scenarios and identify the metrics management should review weekly. Flag immediate pressure points as Red, elevated watch items as Amber, and stable indicators as Green. Present as a RAG table.',
      ], DESC_ANALYST),
      tool(T_EXCEL, M365_LIC, M365_ACCT, [
        'Using the Lapse Analysis tab in this workbook, analyse which cohorts, products, and channels are contributing most to persistency deterioration in LI_01_Policy_Portfolio.xlsx. Create a new sheet called Persistency Recovery View that groups the strongest risk signals, highlights concentration, and states where retention action should start first. Flag the worst lapse hotspots as Red, emerging hotspots as Amber, and stable cohorts as Green. Present as a RAG table.',
        'Using the New Business Tracker and Bancassurance Performance tabs in this workbook, assess where channel productivity is falling short in LI_01_Policy_Portfolio.xlsx and whether the problem is partner-specific or proposition-specific. Create a new sheet called Distribution Reset that ranks channels by quality of growth, shows where the shortfall is largest, and summarises the most credible recovery lever beside each channel. Flag priority channels as Red, Amber, and Green in a RAG table.',
        'Using the Actuarial Reserve Summary tab in this workbook, evaluate how current lapse and sales trends affect reserve strain and capital resilience in LI_01_Policy_Portfolio.xlsx. Create a new sheet called Reserve and Value Watch that shows the products or cohorts putting the most pressure on economics and which indicators need weekly monitoring. Flag immediate pressure points as Red, watchlist areas as Amber, and stable areas as Green. Present as a RAG table.',
      ]),
      tool(T_WORD, M365_LIC, M365_ACCT, [
        'You are the Chief Distribution Officer at Sentosa Life Assurance Berhad. Using LI_01_Policy_Portfolio.xlsx and LI_02_Product_Framework.docx, draft a board paper explaining why new business value is weakening and what management should do across bancassurance, agency, and digital channels. Separate the analysis into channel productivity, proposition fit, and target-setting realism. Flag the main decisions as Red, the supporting management actions as Amber, and monitor-only items as Green. Present as a RAG table followed by a concise narrative.',
        'You are the Chief Customer Officer at Sentosa Life Assurance Berhad. Using LI_01_Policy_Portfolio.xlsx and LI_02_Product_Framework.docx, draft a persistency recovery memo that explains which customer cohorts are most at risk, what in the proposition or servicing journey may be causing that behaviour, and where intervention is most likely to change the outcome. Present as a structured table followed by a short recommendation section.',
        'You are the Appointed Actuary at Sentosa Life Assurance Berhad. Using LI_03_Actuarial_Policy.docx and the Actuarial Reserve Summary tab in LI_01_Policy_Portfolio.xlsx, draft a management note for the Board Risk Committee on reserve and capital implications if lapse and sales trends do not improve. Explain what assumptions matter most, how much management headroom remains, and which questions BNM is likely to ask. Present the risk summary as a RAG table.',
      ]),
      tool(T_PPT, M365_LIC, M365_ACCT, [
        'You are the CEO of Sentosa Life Assurance Berhad. Using LI_01_Policy_Portfolio.xlsx and LI_03_Actuarial_Policy.docx, create a five-slide executive deck on weakening new business value, rising lapses, and the capital implications if trends persist. Keep the narrative focused on what changed, why it matters, and what the executive committee must decide in the next three weeks. Present the risk summary as a RAG table.',
        'You are the Chief Distribution Officer at Sentosa Life Assurance Berhad. Using the New Business Tracker and Bancassurance Performance tabs in LI_01_Policy_Portfolio.xlsx plus LI_02_Product_Framework.docx, create a five-slide deck on channel productivity and proposition fit. Show where growth quality is weakening, what can be recovered quickly, and which channel assumptions should be reset. Flag the priority actions on each slide as Red, Amber, or Green.',
        'You are the Appointed Actuary at Sentosa Life Assurance Berhad. Using the Actuarial Reserve Summary and Lapse Analysis tabs in LI_01_Policy_Portfolio.xlsx plus LI_03_Actuarial_Policy.docx, create a five-slide board briefing on reserve sensitivity and persistency risk. Explain the downside under current trends, what management can still control, and which indicators should be watched most closely. End with a RAG table of the most important risk areas.',
      ]),
      tool(T_OUTLOOK, M365_LIC, M365_ACCT, [
        'You are the Chief Distribution Officer at Sentosa Life Assurance Berhad. Draft an internal email to the CEO and CFO using the New Business Tracker and Bancassurance Performance tabs in LI_01_Policy_Portfolio.xlsx as context, explaining where channel productivity is now weakest and what decisions you need this week. Make clear what is data-backed, what is still hypothesis, and which targets may no longer be realistic. Keep the tone factual and action-oriented.',
        'You are the Appointed Actuary at Sentosa Life Assurance Berhad. Draft a formal email to finance, risk, and regulatory affairs using LI_03_Actuarial_Policy.docx and the Actuarial Reserve Summary tab in LI_01_Policy_Portfolio.xlsx as context, asking for coordinated review before the next BNM stress discussion. Highlight the assumptions under pressure, the evidence we should lead with, and what management should not overstate. Keep the tone precise and controlled.',
        'You are the Chief Customer Officer at Sentosa Life Assurance Berhad. Draft an email to product, operations, and distribution leaders using the Lapse Analysis tab in LI_01_Policy_Portfolio.xlsx and LI_02_Product_Framework.docx as context, explaining that persistency recovery must now be prioritised. Ask each team for one intervention with the strongest evidence behind it and state the turnaround deadline. Keep the tone direct but collaborative.',
      ]),
      tool(T_TEAMS, M365_LIC, M365_ACCT, [
        'You are the Chief Distribution Officer at Sentosa Life Assurance Berhad. Using this recorded Teams meeting recap together with the New Business Tracker and Bancassurance Performance tabs in LI_01_Policy_Portfolio.xlsx, identify every decision, unresolved issue, and action item affecting growth quality and channel productivity. Note where the discussion changed the view on partner performance, product fit, or target realism. Flag same-week actions as Red, next-stage follow-ups as Amber, and monitor-only items as Green. Present as a RAG table.',
        'You are the Chief Customer Officer at Sentosa Life Assurance Berhad. Using this recorded Teams meeting recap and the In-Force Book and Lapse Analysis tabs in LI_01_Policy_Portfolio.xlsx as context, extract every comment that affects persistency, servicing pain points, or customer communication quality. Explain which comments are supported by the portfolio data, which are intuitive but unproven, and which need immediate action. Present as a table with columns for Issue, Comment, Data Support, Owner, and Next Step.',
        'You are the Appointed Actuary at Sentosa Life Assurance Berhad. Using this recorded Teams meeting recap and LI_03_Actuarial_Policy.docx as context, identify any comments that could weaken our reserve, capital, or stress-testing narrative if repeated externally. Distinguish between acceptable internal debate, problematic wording, and items requiring policy clarification before reuse. Flag urgent wording fixes as Red, medium-priority fixes as Amber, and acceptable content as Green. Present as a RAG table.',
      ], DESC_TEAMS),
      tool(T_NOTEBOOK, M365_LIC, M365_ACCT, [
        'You are the CEO of Sentosa Life Assurance Berhad. Upload LI_01_Policy_Portfolio.xlsx, LI_02_Product_Framework.docx, and LI_03_Actuarial_Policy.docx to Copilot Notebook, and set the instruction to focus on new business value, persistency, and reserve resilience. Ask Notebook to identify the three strongest drivers of current deterioration, the contradictions across distribution, product, and actuarial documents, and the executive decisions that cannot be delayed. Present the answer as a RAG table with citations to the source files.',
        'You are the Appointed Actuary at Sentosa Life Assurance Berhad. Upload LI_01_Policy_Portfolio.xlsx and LI_03_Actuarial_Policy.docx to Copilot Notebook. Ask Notebook to assess what happens to reserve strain, capital resilience, and growth quality if current lapse and sales trends continue for another two quarters and whether management still has credible room to hold the existing target. Require citations for each conclusion and present the summary as Red, Amber, and Green priorities.',
        'You are the Chief Distribution Officer at Sentosa Life Assurance Berhad. Upload LI_01_Policy_Portfolio.xlsx and LI_02_Product_Framework.docx to Copilot Notebook. Ask Notebook to identify which channels and propositions deserve more management support, which should be reset, and what the evidence says about a digitally enabled retention strategy for the most at-risk cohorts. Present the answer as a ranked table with a Red, Amber, or Green priority for each recommendation.',
      ], DESC_NOTEBOOK),
      tool(T_COWORK, M365_LIC, M365_ACCT, [
        'You are the Chief Distribution Officer at Sentosa Life Assurance Berhad. Using LI_01_Policy_Portfolio.xlsx and LI_02_Product_Framework.docx as context, prepare a channel productivity action brief, save it to OneDrive, email it to the CEO, CFO, and Head of Bancassurance, and schedule a 30-minute review call for tomorrow morning. Keep the brief focused on weakening growth quality, partner-level priorities, and the most credible recovery levers. End with a short RAG summary of the key channels.',
        'You are the Appointed Actuary at Sentosa Life Assurance Berhad. Using LI_01_Policy_Portfolio.xlsx and LI_03_Actuarial_Policy.docx as context, create a reserve and persistency watchlist, assign the relevant owners, email each owner their top actions, and schedule a checkpoint meeting before the next Board Risk Committee pack is finalised. Prioritise the watchlist by downside to earnings and credibility. Present the action summary as Red, Amber, and Green priorities.',
      ], DESC_COWORK),
      tool(T_EDIT_COPILOT, M365_LIC, M365_ACCT, [
        'You are the Appointed Actuary at Sentosa Life Assurance Berhad. Using LI_03_Actuarial_Policy.docx in Word for the web, add an appendix titled Persistency Deterioration and Reserve Escalation Protocol that clarifies assumption governance, trigger thresholds, management sign-offs, and what evidence is needed before changing the narrative to BNM or the Board. Keep the language consistent with the current policy and make judgement-based areas explicit. End with a short RAG summary table.',
        'Using the Lapse Analysis and Actuarial Reserve Summary tabs in LI_01_Policy_Portfolio.xlsx, create a new worksheet called Value and Persistency Control Tower in Excel for the web. Reorganise the information so management can see cohort risk, reserve pressure, owner, and next intervention on one page with the most urgent items at the top. Flag severe deterioration as Red, emerging pressure as Amber, and stable cohorts as Green. Present as a RAG table.',
      ], DESC_EDIT_COPILOT),
      tool(T_WORD_AGT, M365_LIC, M365_ACCT, [
        'You are the Appointed Actuary at Sentosa Life Assurance Berhad. Using LI_03_Actuarial_Policy.docx in Word for Web, create a declarative agent called Sentosa Actuarial Governance Guide that answers questions on reserve assumptions, lapse escalation, and board-level capital narratives. Set the document as the knowledge source and share it with actuarial, finance, and risk leadership. Make the description clear that the agent should separate policy rules from management judgement.',
        'You are the Chief Distribution Officer at Sentosa Life Assurance Berhad. Demo the Sentosa Actuarial Governance Guide agent by asking what governance steps are required if early-duration lapse assumptions worsen again before the next BNM discussion, using LI_03_Actuarial_Policy.docx as the source context. Then ask which approvals are needed before management changes the reserve narrative in a board paper. Present the demo outcome as a short table showing question, answer, and cited source section.',
      ], DESC_WORD_AGT),
      tool(T_PPT_AGT, M365_LIC, M365_ACCT, [
        'You are the CEO of Sentosa Life Assurance Berhad. Using a PowerPoint summary of LI_01_Policy_Portfolio.xlsx and LI_03_Actuarial_Policy.docx, create a declarative agent called Growth and Persistency Briefing Navigator that helps executives find the right slide, chart, and capital message quickly. Share it with the executive committee and Board Risk Committee support team. Describe it as a guide for growth quality, lapse trends, and reserve discussion points.',
        'You are the CFO of Sentosa Life Assurance Berhad. Demo the Growth and Persistency Briefing Navigator agent by asking which cohort is creating the largest economic drag, how much the bancassurance slowdown contributes to the shortfall, and which slide to open if the Board asks about reserve sensitivity. Then ask it to summarise the two decisions management cannot defer this month. Present the demo as a short answer log with cited slide references.',
      ], DESC_PPT_AGT),
      tool(T_XL_AGT, M365_LIC, M365_ACCT, [
        'You are the Chief Distribution Officer at Sentosa Life Assurance Berhad. Using LI_01_Policy_Portfolio.xlsx in Excel for Web, create a declarative agent called Life Portfolio Analytics Q and A that answers questions on new business, lapse behaviour, reserve signals, and bancassurance performance. Share it with distribution, actuarial, and finance leadership. Make the description clear that answers must stay grounded in the workbook tabs.',
        'You are the Chief Customer Officer at Sentosa Life Assurance Berhad. Demo the Life Portfolio Analytics Q and A agent by asking which cohort has the highest early-duration lapse signal in the Lapse Analysis tab, what the Bancassurance Performance tab suggests about partner weakness, and whether the Actuarial Reserve Summary tab shows immediate economic strain. Present the result as a concise table with the source tab named for each answer.',
      ], DESC_XL_AGT),
      tool(T_BUILDER, M365_LIC, M365_ACCT, [
        'You are the COO of Sentosa Life Assurance Berhad. In Copilot Studio, create an agent called Sentosa Growth and Persistency Intelligence using LI_01_Policy_Portfolio.xlsx, LI_02_Product_Framework.docx, and LI_03_Actuarial_Policy.docx as knowledge sources. Describe it as an assistant for distribution, product, and actuarial teams that answers questions on new business quality, lapse drivers, proposition fit, reserve governance, and board readiness. Add a starter topic for Which cohort needs intervention first and publish it to Teams for the life insurance leadership group.',
        'You are the Chief Distribution Officer at Sentosa Life Assurance Berhad. Demo Sentosa Growth and Persistency Intelligence by asking which cohort or channel should be escalated first, what evidence supports that priority, and what management should do this week, using the New Business Tracker, Lapse Analysis, and Bancassurance Performance tabs plus LI_02_Product_Framework.docx as context. Then ask whether current reserve pressures change the urgency of the distribution response. Present the demo output as a RAG table.',
      ], DESC_BUILDER),
    ],
    companyID='PT Asuransi Jiwa Sentosa Nusantara Tbk',
    taglineID='Persistensi polis melemah, penjualan bancassurance turun, dan tekanan RBC menjadi fokus OJK serta investor IDX.'
),

# ── TAKAFUL ────────────────────────────────────────────────────────────────
ind('takaful','insurance','Takaful','☪','#1A237E','#1976D2',
    'Barakah Takaful Berhad',
    'Participant fund surplus is tightening as lapse pressure, wakalah fee competition, and Shariah exceptions converge before review.',
    'Barakah Takaful Berhad is a Malaysian takaful operator with family and general takaful lines, but the immediate pressure sits in the participant fund and the competitiveness of the wakalah model. Claims outgo has risen faster than expected in selected family takaful portfolios, lapse behaviour has worsened in the early years, and the current wakalah fee position now looks uncomfortably high against newer digital competitors that are winning price-sensitive customers. Management is also working through a small number of Shariah process exceptions that are not yet systemic but could become reputationally damaging if they are still open when BNM reviews governance, participant disclosure, and surplus treatment. The re-takaful programme is due for renewal at a time when counterparties are pushing for less generous terms, creating further uncertainty over protection and net fund resilience. The Indonesian affiliate, PT Asuransi Syariah Barakah Nusantara Tbk, is facing similar scrutiny as OJK sharpens supervision of syariah fund governance, IDX investors question margin quality, and Bank Indonesia conditions influence participant affordability. The management committee has six weeks to decide whether to adjust fee strategy, tighten retention measures, and accelerate remediation of Shariah control gaps.',
    ['TAK_01_Takaful_Portfolio.xlsx', 'TAK_02_Takaful_Governance_Manual.docx', 'TAK_03_Shariah_Compliance_Policy.docx'],
    [
      tool(T_CHAT, FREE_LIC, FREE_ACCT, [
        'You are the CEO of Barakah Takaful Berhad. Using TAK_01_Takaful_Portfolio.xlsx, especially the Participant Fund and Wakalah Fee Tracker tabs, explain whether the bigger threat is worsening fund sustainability, uncompetitive fee positioning, or customer retention. Distinguish what can be fixed quickly from what requires a broader operating model change, and state which management question should be answered first. Flag immediate priorities as Red, urgent watchlist items as Amber, and lower-priority items as Green. Present as a RAG table.',
        'You are the Chief Operations Officer at Barakah Takaful Berhad. Using the Claim Payment Register and Shariah Compliance Log tabs in TAK_01_Takaful_Portfolio.xlsx, assess whether current operational exceptions look isolated or symptomatic of a wider control weakness. Explain what the pattern suggests about root cause, where participant impact could become material, and which control break would worry BNM or the Shariah Committee most. Present as a table with columns for Issue, Evidence, Impact, and Recommended Action.',
        'You are the Head of Shariah Compliance at Barakah Takaful Berhad. Using TAK_03_Shariah_Compliance_Policy.docx and the Surplus Distribution tab in TAK_01_Takaful_Portfolio.xlsx, identify the governance and disclosure questions that BNM and the Board are most likely to ask if surplus pressure continues while fee competitiveness worsens. Distinguish participant fairness, operational compliance, and commercial strategy risk, then explain which issue would most damage trust if underestimated. Flag immediate escalation topics as Red, important follow-ups as Amber, and stable areas as Green. Present as a RAG table.',
      ]),
      tool(T_RESEARCHER, FREE_LIC, FREE_ACCT, [
        'You are the CEO of Barakah Takaful Berhad. Research how takaful operators in Malaysia and Indonesia have responded from 2022 to 2026 when participant fund pressure, wakalah fee competition, or lapse deterioration threatened profitability and growth at the same time. Focus on published examples that discuss pricing strategy, retention programmes, surplus treatment, or re-takaful changes, and compare the supervisory posture of BNM and OJK where possible. Flag any claim that could not be independently verified.',
        'You are the Head of Shariah Compliance at Barakah Takaful Berhad. Research current expectations on participant disclosure, surplus distribution, and governance of Shariah exceptions in Malaysia and Indonesia, with emphasis on BNM, OJK, and any useful guidance from regional Shariah standard setters between 2023 and 2026. Distinguish what is clearly mandatory from what is emerging good practice, and highlight any public cases where weak communication damaged trust. Flag any claim that could not be independently verified.',
        'You are the CFO of Barakah Takaful Berhad. Research how takaful operators and reinsurers have discussed re-takaful pricing, retention, and treaty structure from 2023 to 2026 when claims pressure or participant fund strain increased. Summarise what negotiation levers appear most effective, what trade-offs operators accepted, and what management indicators were watched most closely before renewal. Flag any claim that could not be independently verified.',
      ], DESC_RESEARCHER),
      tool(T_ANALYST, M365_LIC, M365_ACCT, [
        'You are the CFO of Barakah Takaful Berhad. Upload TAK_01_Takaful_Portfolio.xlsx to Analyst and use the Participant Fund, Wakalah Fee Tracker, and Surplus Distribution tabs to determine whether current pressure is primarily coming from claims, lapse behaviour, fee competitiveness, or all three together. Quantify where the largest strain sits and how concentrated the downside is by product or cohort. Flag severe sustainability pressure as Red, mixed-signal areas as Amber, and stable areas as Green. Present as a RAG table.',
        'You are the Chief Operations Officer at Barakah Takaful Berhad. Upload TAK_01_Takaful_Portfolio.xlsx to Analyst and analyse the Claim Payment Register and Shariah Compliance Log tabs to identify patterns in operational exceptions, processing delays, and potential participant harm. Show whether the exceptions cluster by process, product, or team and which issues should be escalated first. Present as a table with columns for Issue, Frequency, Participant Impact, Likely Driver, and Management Action.',
        'You are the Head of Shariah Compliance at Barakah Takaful Berhad. Upload TAK_01_Takaful_Portfolio.xlsx to Analyst and use the Surplus Distribution, Participant Fund, and Wakalah Fee Tracker tabs to test how current trends affect participant fairness, fund resilience, and the credibility of the current fee model over the next year. Quantify the downside under base, adverse, and severe scenarios and identify the indicators management should review weekly. Flag immediate pressure points as Red, elevated watch items as Amber, and stable indicators as Green. Present as a RAG table.',
      ], DESC_ANALYST),
      tool(T_EXCEL, M365_LIC, M365_ACCT, [
        'Using the Participant Fund tab in this workbook, analyse which products, cohorts, or claims patterns are contributing most to fund pressure in TAK_01_Takaful_Portfolio.xlsx. Create a new sheet called Fund Sustainability View that groups the strongest risk signals, highlights concentration, and states where management intervention should start first. Flag severe pressure points as Red, emerging pressure points as Amber, and stable areas as Green. Present as a RAG table.',
        "Using the Wakalah Fee Tracker tab in this workbook, assess where Barakah Takaful's current fee position may be undermining competitiveness in TAK_01_Takaful_Portfolio.xlsx. Create a new sheet called Fee Competitiveness Reset that shows where fee pressure aligns with lapse behaviour, which segments need a strategy review, and what the likely commercial implication is beside each segment. Flag the most urgent issues as Red, developing issues as Amber, and stable areas as Green. Present as a RAG table.",
        'Using the Surplus Distribution and Shariah Compliance Log tabs in this workbook, evaluate how participant fairness and governance risk interact in TAK_01_Takaful_Portfolio.xlsx. Create a new sheet called Surplus and Compliance Watch that shows where operational exceptions, disclosure sensitivity, or surplus strain are converging. Flag immediate escalation items as Red, elevated watch items as Amber, and stable areas as Green. Present as a RAG table.',
      ]),
      tool(T_WORD, M365_LIC, M365_ACCT, [
        'You are the CEO of Barakah Takaful Berhad. Using TAK_01_Takaful_Portfolio.xlsx and TAK_02_Takaful_Governance_Manual.docx, draft a board paper explaining why participant fund pressure, fee competitiveness, and lapse behaviour now require a strategic response. Separate the analysis into fund sustainability, participant value, and operating model implications. Flag the main decisions as Red, the supporting management actions as Amber, and monitor-only matters as Green. Present as a RAG table followed by a concise narrative.',
        'You are the Chief Operations Officer at Barakah Takaful Berhad. Using TAK_02_Takaful_Governance_Manual.docx and the Claim Payment Register tab in TAK_01_Takaful_Portfolio.xlsx, draft an operations memo on the most important process breakdowns, participant impacts, and control actions required before the BNM review. Show where the problems are procedural, where they are resourcing-related, and where governance escalation is needed. Present as a structured table followed by a short recommendation section.',
        'You are the Head of Shariah Compliance at Barakah Takaful Berhad. Using TAK_03_Shariah_Compliance_Policy.docx and the Surplus Distribution tab in TAK_01_Takaful_Portfolio.xlsx, draft a management note for the Shariah Committee on participant disclosure, surplus pressure, and the credibility of the current wakalah model. Explain which issues are clearly policy matters, which are strategic choices, and which need remediation evidence before review. Present the risk summary as a RAG table.',
      ]),
      tool(T_PPT, M365_LIC, M365_ACCT, [
        'You are the CEO of Barakah Takaful Berhad. Using TAK_01_Takaful_Portfolio.xlsx and TAK_03_Shariah_Compliance_Policy.docx, create a five-slide executive deck on participant fund pressure, wakalah fee competitiveness, Shariah governance risk, and the decisions management needs within six weeks. Keep the storyline clear, participant-focused, and decision-oriented. Present the risk summary as a RAG table.',
        'You are the CFO of Barakah Takaful Berhad. Using the Participant Fund, Wakalah Fee Tracker, and Surplus Distribution tabs in TAK_01_Takaful_Portfolio.xlsx, create a five-slide deck on fund resilience and fee strategy. Show where pressure is concentrated, what current trends imply for surplus distribution, and what trade-offs management faces if fees are reduced or benefits are changed. Flag the priority issues on each slide as Red, Amber, or Green.',
        'You are the Head of Shariah Compliance at Barakah Takaful Berhad. Using the Shariah Compliance Log tab in TAK_01_Takaful_Portfolio.xlsx plus TAK_02_Takaful_Governance_Manual.docx and TAK_03_Shariah_Compliance_Policy.docx, create a five-slide board briefing on operational exceptions and governance readiness. Explain which issues are most sensitive from a participant trust perspective and what remediation evidence the committee should demand. End with a RAG table of the most important risk areas.',
      ]),
      tool(T_OUTLOOK, M365_LIC, M365_ACCT, [
        'You are the CFO of Barakah Takaful Berhad. Draft an internal email to the CEO and Head of Shariah Compliance using the Participant Fund and Wakalah Fee Tracker tabs in TAK_01_Takaful_Portfolio.xlsx as context, explaining where the biggest sustainability pressure now sits and what strategic decisions you need this week. Make clear what is data-backed, what remains uncertain, and where the current fee model may no longer be defensible. Keep the tone factual and action-oriented.',
        'You are the Head of Shariah Compliance at Barakah Takaful Berhad. Draft a formal email to governance, legal, and operations stakeholders using TAK_03_Shariah_Compliance_Policy.docx and the Surplus Distribution tab in TAK_01_Takaful_Portfolio.xlsx as context, asking for coordinated review before the next BNM and Shariah Committee discussions. Highlight participant disclosure, surplus treatment, and any open process exceptions. Keep the tone precise and controlled.',
        'You are the Chief Operations Officer at Barakah Takaful Berhad. Draft an email to product, distribution, and customer service leaders using the Claim Payment Register and Shariah Compliance Log tabs in TAK_01_Takaful_Portfolio.xlsx plus TAK_02_Takaful_Governance_Manual.docx as context, explaining that operational remediation must now be accelerated. Ask each team for one evidence-based intervention and state the turnaround deadline. Keep the tone direct but collaborative.',
      ]),
      tool(T_TEAMS, M365_LIC, M365_ACCT, [
        'You are the CFO of Barakah Takaful Berhad. Using this recorded Teams meeting recap together with the Participant Fund and Wakalah Fee Tracker tabs in TAK_01_Takaful_Portfolio.xlsx, identify every decision, unresolved issue, and action item affecting fund resilience and fee competitiveness. Note where the discussion changed the view on lapse pressure, participant value, or re-takaful reliance. Flag same-week actions as Red, next-stage follow-ups as Amber, and monitor-only items as Green. Present as a RAG table.',
        'You are the Chief Operations Officer at Barakah Takaful Berhad. Using this recorded Teams meeting recap and the Claim Payment Register and Shariah Compliance Log tabs in TAK_01_Takaful_Portfolio.xlsx as context, extract every comment that affects processing quality, participant impact, or control weakness. Explain which points are supported by the operational data, which are intuitive but unproven, and which need immediate action. Present as a table with columns for Issue, Comment, Data Support, Owner, and Next Step.',
        'You are the Head of Shariah Compliance at Barakah Takaful Berhad. Using this recorded Teams meeting recap and TAK_03_Shariah_Compliance_Policy.docx as context, identify any comments that could weaken our participant fairness or Shariah governance narrative if repeated externally. Distinguish between acceptable internal challenge, problematic wording, and items requiring policy clarification before reuse. Flag urgent wording fixes as Red, medium-priority fixes as Amber, and acceptable content as Green. Present as a RAG table.',
      ], DESC_TEAMS),
      tool(T_NOTEBOOK, M365_LIC, M365_ACCT, [
        'You are the CEO of Barakah Takaful Berhad. Upload TAK_01_Takaful_Portfolio.xlsx, TAK_02_Takaful_Governance_Manual.docx, and TAK_03_Shariah_Compliance_Policy.docx to Copilot Notebook, and set the instruction to focus on participant fund resilience, fee competitiveness, and governance readiness. Ask Notebook to identify the three strongest drivers of current pressure, the contradictions across commercial, operational, and Shariah documents, and the decisions management cannot delay. Present the answer as a RAG table with citations to the source files.',
        'You are the Head of Shariah Compliance at Barakah Takaful Berhad. Upload TAK_01_Takaful_Portfolio.xlsx and TAK_03_Shariah_Compliance_Policy.docx to Copilot Notebook. Ask Notebook to assess what happens to participant fairness, surplus credibility, and governance risk if current lapse and fee trends continue for another two quarters and whether management still has a credible basis to defend the current model. Require citations for each conclusion and present the summary as Red, Amber, and Green priorities.',
        'You are the CFO of Barakah Takaful Berhad. Upload TAK_01_Takaful_Portfolio.xlsx and TAK_02_Takaful_Governance_Manual.docx to Copilot Notebook. Ask Notebook to identify which products, cohorts, or operating processes deserve immediate intervention, which should be reset, and how re-takaful considerations affect the urgency of those choices. Present the answer as a ranked table with a Red, Amber, or Green priority for each recommendation.',
      ], DESC_NOTEBOOK),
      tool(T_COWORK, M365_LIC, M365_ACCT, [
        'You are the CFO of Barakah Takaful Berhad. Using TAK_01_Takaful_Portfolio.xlsx and TAK_03_Shariah_Compliance_Policy.docx as context, prepare a participant fund and fee strategy brief, save it to OneDrive, email it to the CEO and Head of Shariah Compliance, and schedule a 30-minute review call for tomorrow morning. Keep the brief focused on fund resilience, fee competitiveness, and the highest-stakes governance questions. End with a short RAG summary of the key pressure points.',
        'You are the Chief Operations Officer at Barakah Takaful Berhad. Using TAK_01_Takaful_Portfolio.xlsx and TAK_02_Takaful_Governance_Manual.docx as context, create an operational remediation tracker, assign the relevant owners, email each owner their top actions, and schedule a checkpoint meeting before the next BNM readiness review. Prioritise the tracker by participant impact and governance sensitivity. Present the action summary as Red, Amber, and Green priorities.',
      ], DESC_COWORK),
      tool(T_EDIT_COPILOT, M365_LIC, M365_ACCT, [
        'You are the Head of Shariah Compliance at Barakah Takaful Berhad. Using TAK_03_Shariah_Compliance_Policy.docx in Word for the web, add an appendix titled Participant Fund Pressure and Shariah Escalation Protocol that clarifies trigger thresholds, governance steps, participant disclosure requirements, and management sign-offs before the narrative goes to BNM or the Board. Keep the language aligned to the current policy and make judgement-based areas explicit. End with a short RAG summary table.',
        'Using the Participant Fund and Surplus Distribution tabs in TAK_01_Takaful_Portfolio.xlsx, create a new worksheet called Fund and Fairness Control Tower in Excel for the web. Reorganise the information so management can see fund strain, participant impact, owner, and next intervention on one page with the most urgent items at the top. Flag severe deterioration as Red, emerging pressure as Amber, and stable areas as Green. Present as a RAG table.',
      ], DESC_EDIT_COPILOT),
      tool(T_WORD_AGT, M365_LIC, M365_ACCT, [
        'You are the Head of Shariah Compliance at Barakah Takaful Berhad. Using TAK_03_Shariah_Compliance_Policy.docx in Word for Web, create a declarative agent called Barakah Shariah Governance Guide that answers questions on participant disclosure, surplus treatment, operational exceptions, and approval authorities. Set the document as the knowledge source and share it with Shariah, operations, and finance leadership. Make the description clear that the agent should separate policy rules from management judgement.',
        'You are the CFO of Barakah Takaful Berhad. Demo the Barakah Shariah Governance Guide agent by asking what governance steps are required if surplus pressure persists while the wakalah fee stays above newer competitors, using TAK_03_Shariah_Compliance_Policy.docx as the source context. Then ask which approvals are needed before management changes the participant communication on surplus treatment. Present the demo outcome as a short table showing question, answer, and cited source section.',
      ], DESC_WORD_AGT),
      tool(T_PPT_AGT, M365_LIC, M365_ACCT, [
        'You are the CEO of Barakah Takaful Berhad. Using a PowerPoint summary of TAK_01_Takaful_Portfolio.xlsx and TAK_03_Shariah_Compliance_Policy.docx, create a declarative agent called Fund and Governance Briefing Navigator that helps executives find the right slide, chart, and participant-risk message quickly. Share it with the management committee and Shariah Committee support team. Describe it as a guide for fund resilience, fee strategy, and governance discussion points.',
        'You are the CFO of Barakah Takaful Berhad. Demo the Fund and Governance Briefing Navigator agent by asking which product or cohort is creating the largest strain on the participant fund, how much the current fee stance contributes to the pressure, and which slide to open if the Board asks about participant fairness. Then ask it to summarise the two decisions management cannot defer this month. Present the demo as a short answer log with cited slide references.',
      ], DESC_PPT_AGT),
      tool(T_XL_AGT, M365_LIC, M365_ACCT, [
        'You are the CFO of Barakah Takaful Berhad. Using TAK_01_Takaful_Portfolio.xlsx in Excel for Web, create a declarative agent called Takaful Portfolio Analytics Q and A that answers questions on participant fund performance, wakalah fee competitiveness, surplus pressure, and operational exceptions. Share it with finance, operations, and Shariah leadership. Make the description clear that answers must stay grounded in the workbook tabs.',
        'You are the Chief Operations Officer at Barakah Takaful Berhad. Demo the Takaful Portfolio Analytics Q and A agent by asking which area shows the strongest pressure in the Participant Fund tab, what the Wakalah Fee Tracker tab suggests about competitiveness, and whether the Surplus Distribution tab indicates immediate participant fairness pressure. Present the result as a concise table with the source tab named for each answer.',
      ], DESC_XL_AGT),
      tool(T_BUILDER, M365_LIC, M365_ACCT, [
        'You are the COO of Barakah Takaful Berhad. In Copilot Studio, create an agent called Barakah Fund and Shariah Intelligence using TAK_01_Takaful_Portfolio.xlsx, TAK_02_Takaful_Governance_Manual.docx, and TAK_03_Shariah_Compliance_Policy.docx as knowledge sources. Describe it as an assistant for finance, operations, and Shariah teams that answers questions on participant fund pressure, fee competitiveness, surplus treatment, governance steps, and review readiness. Add a starter topic for Which issue needs intervention first and publish it to Teams for the takaful leadership group.',
        'You are the CFO of Barakah Takaful Berhad. Demo Barakah Fund and Shariah Intelligence by asking which issue should be escalated first, what evidence supports that priority, and what management should do this week, using the Participant Fund, Wakalah Fee Tracker, and Surplus Distribution tabs plus TAK_03_Shariah_Compliance_Policy.docx as context. Then ask whether current Shariah exceptions materially change the urgency of the commercial response. Present the demo output as a RAG table.',
      ], DESC_BUILDER),
    ],
    companyID='PT Asuransi Syariah Barakah Nusantara Tbk',
    taglineID='Surplus dana peserta menyempit, fee wakalah kurang kompetitif, dan temuan kepatuhan syariah menarik perhatian OJK.'
),
]

print(f"Batch 2 written: {len(INDUSTRIES_2)} entries")
