
import sys; sys.path.insert(0,'.')
from util import *

INDUSTRIES_1 = [

# ── GENERAL ───────────────────────────────────────────────────────────────
ind('general','general','⭐ General (Any Role)','⭐','#FF6B35','#FF8C42',
    'Your Organisation',
    'A universal demo set — works for any industry, any role.',
    'These scenarios work for any organisation and any seniority level. No prior context needed — just open Copilot and follow the prompts. Perfect as a warm-up before industry-specific demos.',
    ['01_Zava_Group_Financial_Performance.xlsx','02_Zava_Group_Policy_Handbook.docx','03_Zava_Group_Strategy_Framework.docx'],
    [
      tool(T_CHAT, FREE_LIC, FREE_ACCT, [
        'I have a performance review meeting in two days and I need to articulate the impact of my last six months of work clearly. My key achievements include leading a cross-functional project that cut procurement cycle time by 22%, coaching two junior team members who both received "exceeds expectations" ratings, and resolving a long-standing vendor dispute that had been escalating for months. Draft a concise self-assessment narrative of around 300 words that connects these achievements to the team\'s broader goals, uses active language, and ends with a forward-looking statement about my priorities for the next half-year. Avoid generic phrases like "team player" — keep it specific and confident.',
        'My manager just asked me to prepare a 5-minute briefing for the leadership team on why our department should pilot Microsoft 365 Copilot before the company-wide rollout. I need to make a compelling, evidence-based case without it sounding like a vendor pitch. Draft talking points covering: what Copilot does in plain language, two concrete use cases relevant to a finance or operations team, estimated time savings based on published Microsoft research, and how we would measure success in a 30-day pilot. Keep each talking point under 40 words so I can deliver it naturally without reading from a script.',
        'Explain the difference between Copilot Chat, Microsoft 365 Copilot, and Copilot Studio in plain language — as if you were explaining to a department head who has heard the terms but is confused about what each one does and which licence they need. Use a simple analogy and end with a one-sentence recommendation on which to start with for a team of 50 knowledge workers who primarily use Outlook, Word, and Excel.'
      ]),
      tool(T_RESEARCHER, M365_LIC, M365_ACCT, [
        'Research how Fortune 500 companies are measuring the ROI of Microsoft 365 Copilot deployments in 2025 and 2026. I need specific data points: average hours saved per user per week, cost-per-seat payback periods, and which job functions report the highest productivity gains. Summarise findings in a structured format with source citations so I can use this in an executive briefing next week.',
        'What are the top five AI governance and responsible AI frameworks that enterprises in Southeast Asia are adopting in 2025? For each framework, identify who publishes it, what its core principles are, and whether it has any regulatory backing in Malaysia or Indonesia. Present as a comparison table.'
      ], DESC_RESEARCHER),
      tool(T_ANALYST, M365_LIC, M365_ACCT, [
        'Analyse the revenue and EBITDA trends across all 11 divisions from FY2022 to FY2025. Which three divisions have shown the steepest decline in EBITDA margin? Calculate the year-on-year change in margin for each and rank them from worst to best. Create a bar chart showing EBITDA margin by division for FY2024 vs FY2025, and flag any division where margin has dropped more than 5 percentage points in a single year.',
        'Perform a variance analysis between the FY2025 budget and actuals for each division. Calculate both the absolute variance in MYR millions and the percentage variance. Identify the top three divisions with the largest unfavourable variances and suggest two plausible business reasons for each based on the data patterns visible in the file. Output as a table ranked by absolute variance, largest first.'
      ], DESC_ANALYST),
      tool(T_EXCEL, M365_LIC, M365_ACCT, [
        'Using the Group Summary tab in this workbook, Create a formula that calculates the compound annual growth rate (CAGR) of total group revenue from FY2022 to FY2025, then apply the same formula across each division row. Add a conditional formatting rule that highlights any division with a CAGR below 3% in red and above 8% in green.',
        'Using this workbook, Add a new sheet called "FY2026 Forecast" that projects each division\'s revenue using linear trend extrapolation from the FY2022–FY2025 data. Include a column showing the assumed growth rate and a column showing the 90% confidence interval range. Format all currency cells in MYR millions with 1 decimal place.',
        'Identify any cells in this workbook that contain hard-coded numbers where a formula would be more appropriate, and list them with the sheet name and cell reference. Also flag any formula inconsistencies where a formula in a row differs from the pattern used in adjacent rows.',
      ]),
      tool(T_WORD, M365_LIC, M365_ACCT, [
        'Summarise this policy handbook into a one-page executive briefing covering the five most critical compliance obligations, the three highest-risk policy areas, and the escalation path for a potential breach. Format as a briefing memo addressed to the Group CEO, with a "Key Actions Required" section at the end.',
        'Using this document, Identify all sections that reference regulatory bodies or government agencies. List each reference with the section number, the regulatory body named, and the specific obligation it relates to. Present as a structured table with three columns: Section | Regulatory Body | Obligation Summary.',
        'Ask Copilot to draft a new section for the policy handbook titled "Artificial Intelligence Acceptable Use Policy" covering: permitted uses of AI tools in the workplace, data classification rules (what can and cannot be uploaded to AI tools), employee responsibilities, and the approval process for deploying AI in a business process. Keep it under 600 words, use the same formal tone as the existing document, and flag where legal review is recommended.'
      ]),
      tool(T_PPT, M365_LIC, M365_ACCT, [
        'Create a 10-slide presentation titled "Microsoft 365 Copilot — Productivity Unlocked" for a C-suite audience. Include: an executive summary of what Copilot does, a slide on business impact with three metrics (time saved, cost avoidance, employee satisfaction), a demo flow slide showing which tools to show first, a change management slide, and a recommended 90-day rollout roadmap. Use a professional blue and white colour scheme.',
        'Open any existing strategy presentation. Redesign this presentation so each slide follows a "Situation — Complication — Resolution" narrative structure. Rewrite the speaker notes for each slide to be a 30-second verbal script. Flag any slide that is currently text-heavy and suggest a chart or visual to replace it.',
        'Add a new slide titled "AI Governance Principles" to this presentation. The slide should show five principles as icons with one-line descriptions: Responsible, Secure, Transparent, Inclusive, and Accountable. Use the existing slide template and colour palette.'
      ]),
      tool(T_OUTLOOK, M365_LIC, M365_ACCT, [
        'Open Outlook and find the most recent email thread about a project update or budget review. Summarise this thread, identify all open action items with the name of the person responsible, and draft a follow-up email to all participants listing the actions, owners, and a proposed deadline of end of this week. Keep the tone professional but direct.',
        'Draft a meeting request email to three senior stakeholders requesting a 45-minute strategy alignment session. The email should explain the purpose (reviewing Q2 performance against FY2026 targets), the proposed agenda in three bullet points, and ask them to confirm availability for one of three time slots next week. Keep it concise — under 150 words.',
        'Coach me on this email before I send it. Check the tone, identify anything that could be misinterpreted, suggest a stronger subject line, and recommend whether I should copy or blind-copy anyone based on the content. Show your suggestions as tracked changes.'
      ]),
      tool(T_TEAMS, M365_LIC, M365_ACCT, [
        'Generate a full meeting summary with four sections: Key Decisions Made, Open Action Items (with owner and due date), Topics That Need Follow-Up, and a one-paragraph executive summary I can paste into an email to stakeholders who did not attend.',
        'Draft a follow-up email to all meeting participants. The email should thank them for attending, list all action items with owners and deadlines, note any decisions that require sign-off from absent stakeholders, and propose a date for the next check-in in two weeks.',
        'Ask Copilot in the Teams recap: Which discussion points from this meeting are still unresolved? For each unresolved item, identify who raised it, what the proposed next step was, and whether a decision was reached or deferred. Present as a table: Topic | Raised By | Status | Next Step.'
      ], DESC_TEAMS),
      tool(T_NOTEBOOK, M365_LIC, M365_ACCT, [
        'Upload 02_Zava_Group_Policy_Handbook.docx and 03_Zava_Group_Strategy_Framework.docx to Copilot Notebook. Set this system instruction: "You are a senior strategy advisor. Answer questions by synthesising insights from both documents — always cite which document your answer draws from." Then ask: Where do the strategic priorities in the strategy framework conflict with or create compliance obligations under the policy handbook? List the top three tensions and suggest how leadership might resolve each.',
        'Upload 01_Zava_Group_Financial_Performance.xlsx and 03_Zava_Group_Strategy_Framework.docx to Notebook. Ask: Based on the actual financial performance data and the stated strategic objectives, which strategic priorities appear to be underfunded given current revenue allocation? Rank by gap size and suggest which two should be accelerated and which one should be deferred.'
      ], DESC_NOTEBOOK),
      tool(T_COWORK, FRONTIER_LIC, M365_ACCT, [
        'Do all of the following autonomously: (1) Research the latest Microsoft 365 Copilot adoption statistics and productivity benchmarks published in 2025 or 2026. (2) Draft a two-page Word document titled "Copilot Business Case — Internal Briefing" summarising the research with three key data points, two customer case studies, and a recommended adoption approach. (3) Save the document to my OneDrive. (4) Send an email to my manager with the document attached, subject line "Copilot Business Case — Ready for Review", asking for feedback by end of week. (5) Schedule a 30-minute Teams meeting with my manager for next Tuesday at 10am titled "Copilot Business Case Review".',
        'Do all of the following: (1) Check my calendar for any meetings this week that do not have an agenda attached. (2) For each such meeting, draft a short agenda based on the meeting title and attendees. (3) Send each agenda as a reply to the original meeting invitation. (4) Create a recurring Teams meeting every Monday at 9am titled "Weekly Copilot Adoption Check-In" for the next 8 weeks and invite my manager.'
      ], DESC_COWORK),
      tool(T_WORD_AGT, M365_LIC, M365_ACCT, [
        'Open 02_Zava_Group_Policy_Handbook.docx in Word for Web. In the Copilot pane, click + New Agent. Name it "Group Policy Assistant". Description: "Answers employee questions about Zava Group\'s internal policies, compliance obligations, and escalation procedures based on the official policy handbook." Set the document as the knowledge source. Copy the share link and send it to your HR team so employees can chat with it from Teams.',
        'Demo the agent: Open a new Teams chat or M365 Copilot session and ask the Policy Assistant: "What is the escalation process if I suspect a colleague is violating our anti-bribery policy? Who do I contact and what documentation do I need to prepare?" Show how the agent answers with specific references to the policy sections.'
      ], DESC_WORD_AGT),
      tool(T_PPT_AGT, M365_LIC, M365_ACCT, [
        'Open 03_Zava_Group_Strategy_Framework.docx or a strategy presentation in PowerPoint for Web. Create a new agent called "Strategy Deck Assistant". Description: "Helps leadership and strategy teams quickly find information from the group strategy framework, including KPIs, initiative owners, and investment priorities." Set the file as knowledge source and share with the strategy team.',
        'Demo query: Ask the Strategy Deck Assistant in Teams: "Which strategic initiative has the highest investment priority for FY2026, and who is the executive sponsor?" Then ask: "What are the three key risks flagged for the ASEAN expansion workstream?" Show how it pulls answers directly from the deck without requiring anyone to open the file.'
      ], DESC_PPT_AGT),
      tool(T_XL_AGT, M365_LIC, M365_ACCT, [
        'Open 01_Zava_Group_Financial_Performance.xlsx in Excel for Web. In the Copilot pane, click + New Agent. Name it "Group Financials Q&A". Description: "Answers questions about Zava Group\'s divisional revenue, EBITDA, and budget performance using the latest financial data workbook." Set the workbook as knowledge source and share with finance leaders.',
        'Demo query: Ask the Group Financials Q&A agent: "Which three divisions missed their FY2025 EBITDA target and by how much in MYR millions?" Then ask: "What was the group-level revenue growth rate from FY2024 to FY2025?" Show how non-finance colleagues get instant answers without needing to navigate the workbook.'
      ], DESC_XL_AGT),
      tool(T_BUILDER, M365_LIC, M365_ACCT, [
        'Go to copilotstudio.microsoft.com > Create > New Agent. Name the agent "Zava Knowledge Hub". Description: "A company-wide AI assistant that answers questions about group policies, strategy, and financial performance, drawing from official Zava Group documents." Under Knowledge, upload 01_Zava_Group_Financial_Performance.xlsx, 02_Zava_Group_Policy_Handbook.docx, and 03_Zava_Group_Strategy_Framework.docx. Under Topics, add a welcome topic that greets users and explains what the agent can help with. Click Publish > Microsoft Teams. Within 10 minutes the agent appears in Teams for all authorised users.',
        'Demo the published agent in Teams: Open the Zava Knowledge Hub bot and ask: "What is the group\'s FY2026 revenue target and which divisions are expected to contribute the most growth?" Then ask: "Is there a policy covering the use of AI tools in client-facing communications?" Show how the agent synthesises answers from multiple source documents and cites them.'
      ], DESC_BUILDER),
    ]),

# ── COMMERCIAL BANKING ─────────────────────────────────────────────────────
ind('commercial-banking','banking-fs','Commercial Banking','🏦','#0D47A1','#1976D2',
    'Meridian Bank Berhad',
    'NPL at 14.2% — 4x BNM\'s supervisory threshold. Bilateral review in 3 days.',
    'Meridian Bank Berhad is Malaysia\'s fifth-largest commercial bank by assets (MYR 68.4B). Personal Financing NPL has climbed for 6 consecutive quarters, reaching 14.2% — four times BNM\'s 3.5% supervisory threshold. The CFO goes into a BNM bilateral review on Tuesday. Provision coverage sits at 68%, well below the internal 80% target.',
    ['BNK_01_Meridian_Bank.xlsx','BNK_02_Meridian_Bank_Strategy.docx','Email_01_Zava_Bank_NPL_Thread.docx','Email_06_BNM_Regulatory_Correspondence.docx'],
    [
      tool(T_CHAT, FREE_LIC, FREE_ACCT, [
        'I am the CFO of a Malaysian commercial bank. Our Personal Financing NPL ratio has climbed from 8.2% to 14.2% over six quarters and I have a BNM bilateral review in three days. Draft a one-page internal briefing note for my Board Risk Committee explaining the NPL situation in plain language: what drove the deterioration, what remediation actions we have taken so far, and what we expect BNM to ask. Keep the tone calm and factual — this is not a crisis communication, it is a preparatory briefing.',
        'Explain the difference between gross NPL ratio, net NPL ratio, and provision coverage ratio in the context of Malaysian banking regulation. Use simple language suitable for a Board director who has a finance background but is not a banking specialist. Include a worked numerical example using approximate figures.',
        'What are BNM\'s standard remediation requirements when a bank\'s NPL ratio exceeds its supervisory threshold? List the typical regulatory actions BNM may impose, from supervisory letters through to more formal interventions, and indicate the approximate timelines involved.'
      ]),
      tool(T_RESEARCHER, M365_LIC, M365_ACCT, [
        'Research how Malaysian commercial banks have managed NPL surges in the past five years, particularly post-moratorium periods. I need: (1) Industry-average NPL ratios for Malaysian banks in 2023–2025, (2) The three most common remediation strategies banks used successfully, (3) Any BNM guidance circulars on NPL management issued since 2023. Cite all sources so I can share this with our credit risk team.',
        'Research global best practices for bank NPL resolution programmes, particularly in markets with similar profile to Malaysia — emerging markets with retail-heavy loan books. Identify two or three banks that successfully reduced NPL ratios by more than 4 percentage points within 18 months and summarise their approach. Present findings as a structured brief with source links.'
      ], DESC_RESEARCHER),
      tool(T_ANALYST, M365_LIC, M365_ACCT, [
        'Analyse the NPL trend across all loan product segments from Q1 FY2023 to Q4 FY2025. Which three product segments are driving the highest NPL increase in absolute MYR terms? Calculate the required provision top-up to reach 80% provision coverage for each segment and show the cumulative impact on pre-tax profit. Present as a ranked table: Segment | Current NPL (MYR M) | Coverage Gap | Provision Top-Up Required | Pre-Tax Profit Impact.',
        'Build a scatter plot showing the relationship between loan vintage (year of origination) and default rate across all Personal Financing accounts. Identify whether there is a specific origination cohort that is disproportionately contributing to the NPL problem. If a pattern exists, calculate what percentage of total NPL would be resolved by writing off or restructuring that cohort alone.'
      ], DESC_ANALYST),
      tool(T_EXCEL, M365_LIC, M365_ACCT, [
        'Using the Loan Portfolio tab in this workbook, Our Personal Financing NPL ratio has climbed from 8.2% in Q1 FY2023 to 14.2% in Q4 FY2025, now 4x BNM\'s supervisory threshold of 3.5%. Analyse the quarterly deterioration trend across all product segments, identify the three sub-segments contributing most to the NPL increase, calculate the additional loan loss provision required to reach 80% provision coverage, and show the resulting impact on pre-tax profit. Present as a 4-column table: Segment | NPL Rate | Provision Shortfall (MYR M) | Recommended Action.',
        'Create a dynamic NPL stress-test model on a new sheet called "Stress Test". Assume three scenarios — Base (NPL stays at 14.2%), Moderate (NPL rises to 18%), Severe (NPL rises to 22%). For each scenario, calculate the required provision, the impact on Tier 1 capital ratio, and the regulatory capital buffer remaining above BNM\'s 10.5% minimum. Flag in red any scenario where the buffer falls below 1%.',
        'Add a rolling 4-quarter average NPL ratio column next to each product segment row. Then add conditional formatting to flag any segment where the most recent quarter\'s NPL exceeds the 4Q average by more than 2 percentage points — these are the fast-deteriorating segments that need immediate escalation.',
        'Summarise the key risk metrics on the Risk Dashboard sheet into a plain-language paragraph I can paste into the Board pack. Highlight the three metrics that are outside tolerance thresholds and suggest a one-sentence action for each.'
      ]),
      tool(T_WORD, M365_LIC, M365_ACCT, [
        'Draft a 2-page credit risk remediation plan for BNM submission. Structure it as: (1) Executive Summary — current NPL position and root causes, (2) Remediation Actions — three concrete steps with timelines, (3) Governance — who owns each action and how progress will be reported, (4) Milestones — what BNM should expect to see at 30, 60, and 90 days. Use a formal regulatory tone throughout.',
        'Identify all sections in this strategy document that reference credit risk or lending standards. For each section, summarise in one sentence whether the current strategy is consistent with remediation of the NPL problem or whether it may be contributing to it. Present as a gap analysis table.',
        'Rewrite the Executive Summary of this document to reflect the current NPL crisis. The new summary should open with the most critical issue, acknowledge the BNM bilateral review, and end with a clear statement of the bank\'s commitment to reaching 80% provision coverage within 6 months. Keep it under 200 words.',
      ]),
      tool(T_PPT, M365_LIC, M365_ACCT, [
        'Create a 12-slide Board presentation titled "NPL Remediation Programme — Q4 FY2025 Update" for Meridian Bank. Slides should cover: (1) NPL dashboard — current vs threshold, (2) Root cause analysis, (3) Segment breakdown — top 3 contributors, (4) Provision coverage gap analysis, (5) Remediation plan — 3 initiatives, (6) Timeline and milestones, (7) Capital adequacy impact, (8) BNM engagement strategy, (9) Risk appetite reset, (10) Next steps. Use a professional dark-blue colour scheme.',
        'For each slide in this presentation, generate speaker notes that are a 45-second verbal script. The CFO delivering this has 20 years of banking experience, so avoid over-explaining basics — focus the notes on pre-empting the questions Board members are most likely to ask.',
        'Add a "Key Risks" slide after slide 8 that shows five risks to the remediation plan in a 2×2 risk matrix (likelihood vs impact), with one-line mitigants for each risk.'
      ]),
      tool(T_OUTLOOK, M365_LIC, M365_ACCT, [
        'Draft a formal response to BNM\'s latest query. Acknowledge their concerns about the NPL trajectory, outline the three immediate remediation steps we have initiated, confirm the timeline for our next progress report, and request a 30-minute call with the BNM supervision team to discuss the bilateral review agenda. Use the formal salutation style appropriate for BNM correspondence.',
        'Open Email_01_Zava_Bank_NPL_Thread.docx. Summarise this internal email thread, identify all commitments made by the credit risk team, and draft a follow-up email to the Chief Credit Officer asking for a status update on each commitment before the BNM meeting on Tuesday. List the commitments as numbered bullet points in the email body.',
        'Draft an all-staff email from the CEO to branch managers and relationship managers explaining the NPL situation without causing alarm. The email should acknowledge the challenge, explain what the bank is doing about it, and give clear guidance on what relationship managers should and should not say to customers who ask about loan restructuring options. Keep it under 300 words.'
      ]),
      tool(T_TEAMS, M365_LIC, M365_ACCT, [
        'Open an existing recorded Teams meeting recap from a credit or risk committee meeting. Generate a structured recap covering: (1) Key credit risk metrics reviewed, (2) Decisions made on provisioning or remediation, (3) Action items with owners and due dates, (4) Any escalation items that need Board or BNM notification. Format for distribution to the Risk Committee.',
        'Draft a follow-up email to all Risk Committee members. The email should list all action items with owner names and deadlines, note any decisions that require CFO or Board sign-off, and propose the next Risk Committee meeting date.',
        'Based on this meeting transcript, identify any statements made about NPL targets or remediation timelines that could be interpreted as commitments to BNM. List each statement with the speaker name and timestamp so the legal team can review before the bilateral meeting.'
      ], DESC_TEAMS),
      tool(T_NOTEBOOK, M365_LIC, M365_ACCT, [
        'Upload BNK_01_Meridian_Bank.xlsx, BNK_02_Meridian_Bank_Strategy.docx, and Email_06_BNM_Regulatory_Correspondence.docx to Copilot Notebook. Set this instruction: "You are a senior banking regulator advisor preparing the CFO for a BNM bilateral review." Ask: Based on the NPL data, our strategy document, and the BNM correspondence, what are the five most likely questions BNM will ask on Tuesday? For each question, draft a concise, factually grounded answer the CFO can use.',
        'Upload BNK_01_Meridian_Bank.xlsx and Email_01_Zava_Bank_NPL_Thread.docx. Ask: Cross-reference the NPL figures in the data file against the commitments made in the internal email thread. Are there any discrepancies between what was promised internally and what the data shows has actually happened? List any gaps the CFO should be aware of before the BNM meeting.'
      ], DESC_NOTEBOOK),
      tool(T_COWORK, FRONTIER_LIC, M365_ACCT, [
        'Do all of the following: (1) Research the latest BNM guidelines on NPL classification and provisioning requirements published in 2024 or 2025. (2) Draft a 3-page internal compliance brief summarising the key requirements and how Meridian Bank\'s current provisioning compares. (3) Save it as "BNM NPL Compliance Brief - [Today\'s Date]" in OneDrive. (4) Email it to the Chief Risk Officer and Chief Credit Officer with subject "BNM NPL Compliance Brief — Please review before Tuesday" asking for feedback by Monday 5pm. (5) Schedule a 1-hour prep meeting titled "BNM Bilateral Review Prep" for Monday 2pm and invite the CFO, CRO, and CCO.',
        'Do all of the following: (1) Check the calendar for any outstanding action items from the last Risk Committee meeting. (2) For each action item that is overdue, send a polite follow-up email to the owner asking for a status update by end of day. (3) Create a Word document listing all overdue items with owner names and original due dates. (4) Post a summary in the #risk-committee Teams channel: "Reminder: 3 action items from our last meeting are overdue — please update by COB today." (5) Set a recurring weekly reminder in my calendar titled "Risk Action Item Review" every Friday at 4pm for 12 weeks.'
      ], DESC_COWORK),
      tool(T_WORD_AGT, M365_LIC, M365_ACCT, [
        'Open BNK_02_Meridian_Bank_Strategy.docx in Word for Web. Create a new agent called "Credit Strategy Assistant" with description: "Answers questions from credit and risk officers about Meridian Bank\'s credit risk strategy, NPL remediation plan, and lending standards." Set the document as knowledge source. Share with the credit risk team and branch network compliance officers.',
        'Demo query: Ask the Credit Strategy Assistant in Teams: "What is the approved remediation approach for Personal Financing accounts that have been in arrears for more than 90 days? What restructuring options am I authorised to offer before escalating to the Credit Committee?" Show how the agent pulls the answer directly from the strategy document.'
      ], DESC_WORD_AGT),
      tool(T_PPT_AGT, M365_LIC, M365_ACCT, [
        'Create a PowerPoint presentation summarising the NPL remediation programme slides, then open it in PowerPoint for Web. Create an agent called "NPL Remediation Briefing Bot". Description: "Provides instant answers about Meridian Bank\'s NPL remediation programme, targets, and milestones for board members and senior management." Share with Board members so they can review without needing to open the full deck.',
        'Demo: Ask the agent "What is our target NPL ratio at the end of Q2 FY2026 and what are the three key actions driving that target?" Then ask: "What happens to our Tier 1 capital ratio in the severe stress scenario?" Show how Board members get precise answers without navigating through slides.'
      ], DESC_PPT_AGT),
      tool(T_XL_AGT, M365_LIC, M365_ACCT, [
        'Open BNK_01_Meridian_Bank.xlsx in Excel for Web. Create an agent called "Meridian Loan Portfolio Q&A". Description: "Answers questions about Meridian Bank\'s loan portfolio, NPL ratios, provision coverage, and segment breakdowns using live workbook data." Share with senior credit officers who need quick data access without navigating the full workbook.',
        'Demo: Ask the agent "What is the current NPL ratio for the SME segment and how does it compare to the industry average?" Then ask: "Which loan product has the highest rate of deterioration over the last four quarters?" Show how credit managers get instant, data-grounded answers.'
      ], DESC_XL_AGT),
      tool(T_BUILDER, M365_LIC, M365_ACCT, [
        'Go to copilotstudio.microsoft.com > Create > New Agent. Name it "Meridian Credit Risk Assistant". Description: "A regulatory-ready AI assistant for Meridian Bank\'s credit and risk teams — answers questions about NPL positions, remediation plans, BNM requirements, and lending policies using official bank documents." Upload BNK_01_Meridian_Bank.xlsx, BNK_02_Meridian_Bank_Strategy.docx, and Email_06_BNM_Regulatory_Correspondence.docx as knowledge sources. Add a starter topic: "Explain our current NPL situation and remediation plan." Publish to Teams for the Risk and Credit divisions.',
        'Demo the agent in Teams. Ask it: "We have a customer requesting a third loan restructuring on their Personal Financing account. What is our policy and what approval level is required?" Then ask: "What NPL ratio target has the Board approved for end of FY2026 and what are the consequences if we miss it?" Show how the agent gives consistent, document-grounded answers that reduce compliance risk from inconsistent verbal guidance.'
      ], DESC_BUILDER),
    ]),

# ── ISLAMIC BANKING ────────────────────────────────────────────────────────
ind('islamic-banking','banking-fs','Islamic Banking','🕌','#1A237E','#283593',
    'Al-Amanah Islamic Bank Malaysia',
    'MYR 3.5B Sukuk issuance pending — BNM IFSA compliance review in 4 weeks.',
    'Al-Amanah Islamic Bank Malaysia (AIBM) has MYR 22.1B in total financing assets. A landmark MYR 3.5B Sukuk Wakalah issuance is pending regulatory approval. The BNM IFSA compliance review is scheduled in 4 weeks and the Shariah Committee has flagged two products for re-structuring. Profit rate risk is rising as OPR hovers at 3.0%.',
    ['BNK_01_Meridian_Bank.xlsx','BNK_02_Meridian_Bank_Strategy.docx'],
    [
      tool(T_CHAT, FREE_LIC, FREE_ACCT, [
        'Explain the key differences between a conventional bank loan and Islamic financing products such as Murabahah, Ijarah, and Musharakah Mutanaqisah — in plain language suitable for a retail customer who has only ever had a conventional mortgage. Focus on how the profit rate is determined, who owns the asset, and what happens in the event of default.',
        'What are the key disclosure requirements under BNM\'s IFSA 2013 (Islamic Financial Services Act) for a Sukuk Wakalah issuance? List the five most critical compliance obligations and the approval timeline from application to issuance. Include the role of the Shariah Advisory Council in the approval process.',
        'Draft a one-paragraph explanation of profit rate risk in Islamic banking that I can use in our annual report. The paragraph should explain the concept, why it differs from interest rate risk in conventional banking, and how we manage it through our Asset and Liability Management framework. Keep it under 150 words and avoid overly technical language.'
      ]),
      tool(T_RESEARCHER, M365_LIC, M365_ACCT, [
        'Research the global Sukuk market outlook for 2025 and 2026 — specifically for Malaysia. I need: (1) Total Sukuk issuance volumes in Malaysia for 2024 and the forecast for 2025, (2) Demand trends from Middle Eastern and Southeast Asian investors, (3) Any new BNM or SC guidelines affecting Sukuk Wakalah structures issued in the past 12 months. Provide source citations for each data point.',
        'Research how Islamic banks in Malaysia are managing profit rate risk in a rising OPR environment. Identify the top three strategies used by leading Islamic banks (Maybank Islamic, CIMB Islamic, Bank Islam) and compare their approaches. Summarise in a briefing note format suitable for the ALCO (Asset and Liability Committee).'
      ], DESC_RESEARCHER),
      tool(T_ANALYST, M365_LIC, M365_ACCT, [
        'Analyse the financing asset breakdown by product type (Murabahah, Ijarah, Musharakah, etc.) and calculate the concentration risk — what percentage of total financing is in the top 3 product categories. Create a pie chart showing product mix and a trend chart showing how the mix has shifted over the past 8 quarters. Flag any product category where growth has exceeded 15% quarter-on-quarter.',
        'Perform a sensitivity analysis on profit income assuming OPR changes of -50bps, flat, +50bps, and +100bps. For each scenario, calculate the impact on Net Financing Income (NFI) in MYR millions and the resulting NFI margin. Present as a 4-scenario sensitivity table with a colour-coded heat map — red for scenarios where NFI margin falls below 2.5%.'
      ], DESC_ANALYST),
      tool(T_EXCEL, M365_LIC, M365_ACCT, [
        'Using the Financing Portfolio tab in this workbook, Create a Shariah compliance monitoring dashboard on a new sheet called "Shariah Dashboard". It should show: (1) Each product type and its Shariah contract structure, (2) The profit rate benchmark used (COF + spread), (3) Any product where the actual rate charged deviates from the approved structure by more than 10bps — flag these in red.',
        'Build a Sukuk issuance impact model on a new sheet. Assume a MYR 3.5B Sukuk Wakalah at 4.2% profit rate for 5 years. Calculate: (1) Annual profit distribution to Sukukholders, (2) Impact on the bank\'s liquidity coverage ratio (LCR), (3) Impact on the net stable funding ratio (NSFR), (4) Breakeven period assuming proceeds are deployed into Murabahah financing at 6.8% profit rate.',
        'In the financing data, identify all accounts where the financing-to-value (FTV) ratio has exceeded 90% and the account is classified as Stage 2 under MFRS 9. List them by product type and calculate the expected credit loss (ECL) for each assuming a 35% loss given default (LGD). Present as a table sorted by ECL amount, largest first.',
      ]),
      tool(T_WORD, M365_LIC, M365_ACCT, [
        'Draft a Shariah compliance remediation memo for the two flagged products. For each product, the memo should include: (1) the Shariah issue identified, (2) the proposed re-structuring to comply with IFSA requirements, (3) the customer impact and communication plan, (4) the timeline for remediation and sign-off by the Shariah Committee. Use a formal regulatory tone.',
        'Summarise the BNM IFSA compliance requirements referenced in this strategy document into a checklist format. For each requirement, add a status column (Compliant / Partial / Gap) and a responsible officer column. This checklist will be used by the compliance team to prepare for the upcoming BNM review.',
        'Draft a Sukuk Wakalah investor briefing document of approximately 500 words. Cover: the structure of the instrument, profit rate and payment schedule, the underlying Wakalah assets, the risk factors, and the use of proceeds. The audience is institutional investors from the GCC who are familiar with Islamic finance but unfamiliar with Malaysian regulatory requirements.'
      ]),
      tool(T_PPT, M365_LIC, M365_ACCT, [
        'Create a 10-slide Sukuk Wakalah roadshow presentation for institutional investors. Include slides on: AIBM overview and credit rating, the Sukuk structure diagram, profit rate and tenure, use of proceeds, the Shariah compliance framework, key financial metrics (CAR, NPF ratio, ROAE), risk factors, and a Q&A summary. Use a professional green and gold colour scheme appropriate for an Islamic finance presentation.',
        'Add speaker notes to each slide of this investor presentation. The notes should anticipate the three most likely questions from a GCC sovereign wealth fund and provide brief scripted answers the presenter can deliver naturally.',
        'Create a 2-slide summary of the BNM IFSA compliance status for use in the Board Shariah Committee meeting. Slide 1: Current compliance status (RAG table by requirement). Slide 2: Remediation plan for the two flagged products with a Gantt-style timeline.'
      ]),
      tool(T_OUTLOOK, M365_LIC, M365_ACCT, [
        'Open Email_06_BNM_Regulatory_Correspondence.docx. Draft a formal response to the BNM IFSA review notice. The letter should: acknowledge receipt of the review schedule, confirm our readiness and the documents we will provide, request clarification on two specific requirements relating to Musharakah profit-sharing ratios, and propose a pre-review meeting with the BNM supervision officer to align on expectations.',
        'Draft an email to our Shariah Committee members calling an emergency meeting to address the two flagged products. The email should explain the nature of the Shariah issue without using overly technical language, attach the relevant product term sheets for review, and ask for written confirmation of availability for a 2-hour session this week. Subject line: "Urgent: Shariah Committee Review — Two Product Compliance Issues".',
        'Coach me on the tone of the draft email to BNM. Is it too defensive? Too casual? Does it inadvertently admit any non-compliance? Suggest three edits that would make the letter more confident and regulatory-appropriate without being evasive.'
      ]),
      tool(T_TEAMS, M365_LIC, M365_ACCT, [
        'Open an existing recorded Teams meeting recap from a Shariah Committee or ALCO meeting. Identify all Shariah compliance decisions made in this meeting, the rationale provided, and any conditions attached to the approval. Format as a formal Shariah Committee resolution summary suitable for inclusion in the minute book.',
        'Ask Copilot in the recap: Draft follow-up action items for the ALCO based on this meeting. Each action should have a clear owner, a deliverable, and a deadline. Group actions by theme: Profit Rate Risk, Liquidity, Sukuk Issuance, and Shariah Compliance.',
        'Were any profit rate assumptions discussed in this meeting that differ from the assumptions in our Board-approved ALCO policy? If so, flag them with the exact quote from the transcript and the page number of the policy they may conflict with.'
      ], DESC_TEAMS),
      tool(T_NOTEBOOK, M365_LIC, M365_ACCT, [
        'Upload BNK_02_Meridian_Bank_Strategy.docx and Email_06_BNM_Regulatory_Correspondence.docx to Copilot Notebook. Set instruction: "You are a Shariah compliance officer preparing for a BNM IFSA review." Ask: What are the five most critical gaps between our strategy document and the BNM IFSA requirements referenced in the regulatory correspondence? For each gap, propose a remediation step and estimate the time required to close it.',
        'Upload BNK_01_Meridian_Bank.xlsx and BNK_02_Meridian_Bank_Strategy.docx. Ask: Based on the financing portfolio data and our stated strategy, which business segments are growing fastest and are they consistent with our Shariah-compliant product strategy? Flag any segment where growth is driven by a product type that the Shariah Committee has flagged for review.'
      ], DESC_NOTEBOOK),
      tool(T_COWORK, FRONTIER_LIC, M365_ACCT, [
        'Do all of the following: (1) Research BNM\'s latest IFSA guidelines on Sukuk Wakalah issuance requirements and any updates from the Securities Commission published in 2025. (2) Draft a 2-page compliance readiness checklist for our Sukuk issuance, mapping each requirement to our current status. (3) Save it to OneDrive as "Sukuk IFSA Compliance Checklist - [Today\'s Date]". (4) Email it to the Head of Islamic Finance and the Chief Compliance Officer asking for review and sign-off by Thursday. (5) Schedule a 90-minute "Sukuk Issuance Pre-Approval Review" meeting for Friday morning and invite the CFO, Head of Islamic Finance, and Shariah Committee Chairman.',
        'Do all of the following: (1) Set up a recurring weekly 30-minute Teams meeting titled "Shariah Compliance Monitoring Check-In" every Wednesday at 3pm for the next 12 weeks and invite the Shariah Compliance team. (2) Draft an agenda template for these meetings covering: open issues review, new product pipeline, BNM correspondence updates, and any other business. (3) Post the agenda template in the #shariah-compliance Teams channel with a message: "Agenda template for our weekly check-ins — please use this format going forward." (4) Send each invitee a welcome email explaining the purpose of the check-in series.'
      ], DESC_COWORK),
      tool(T_WORD_AGT, M365_LIC, M365_ACCT, [
        'Open BNK_02_Meridian_Bank_Strategy.docx in Word for Web. Create an agent called "AIBM Shariah Policy Bot". Description: "Answers questions from product managers and relationship managers about Al-Amanah Islamic Bank\'s Shariah compliance requirements, approved product structures, and profit rate policies." Set the document as knowledge source and share with the Islamic Banking product team.',
        'Demo: Ask the Shariah Policy Bot: "Is it permissible under our current Shariah framework to offer a hybrid Murabahah-Ijarah product for commercial property financing? What are the structural requirements and who needs to approve it?" Show how the agent gives a policy-grounded answer rather than requiring the team to search through documentation.'
      ], DESC_WORD_AGT),
      tool(T_PPT_AGT, M365_LIC, M365_ACCT, [
        'Convert the Sukuk investor presentation into a PowerPoint file and open it in PowerPoint for Web. Create an agent called "Sukuk Investor Q&A Bot". Description: "Answers investor questions about Al-Amanah\'s MYR 3.5B Sukuk Wakalah issuance — structure, profit rate, Shariah compliance, and use of proceeds." Share the agent with the IR team and external investor contacts.',
        'Demo: Ask the agent "What is the profit rate and payment frequency for this Sukuk?" Then ask: "Who is the Shariah advisor for this issuance and what is the fatwa basis for the Wakalah structure?" Show how investor queries are answered instantly without requiring the IR team to dig through the prospectus.'
      ], DESC_PPT_AGT),
      tool(T_XL_AGT, M365_LIC, M365_ACCT, [
        'Open BNK_01_Meridian_Bank.xlsx in Excel for Web. Create an agent called "AIBM Portfolio Analytics Q&A". Description: "Instant answers on Al-Amanah Islamic Bank\'s financing portfolio — product mix, NPF ratios, profit rate sensitivity, and concentration risk — for ALCO and senior management." Share with ALCO members.',
        'Demo: Ask the agent "What is the current non-performing financing ratio for the Home Financing (Musharakah Mutanaqisah) segment?" Then ask: "If OPR rises by 50bps, what is the projected impact on our Net Financing Income?" Show how ALCO members get data-grounded answers in seconds.'
      ], DESC_XL_AGT),
      tool(T_BUILDER, M365_LIC, M365_ACCT, [
        'Go to copilotstudio.microsoft.com > Create > New Agent. Name it "AIBM Compliance & Product Assistant". Description: "Helps Islamic banking staff answer Shariah compliance questions, understand approved product structures, and navigate BNM IFSA requirements — grounded in official bank strategy and compliance documents." Upload BNK_02_Meridian_Bank_Strategy.docx and Email_06_BNM_Regulatory_Correspondence.docx. Add topics: "Shariah Product Query", "BNM Requirement Lookup", "Sukuk Issuance FAQ". Publish to Teams for all Islamic Banking staff.',
        'Demo the agent: Ask it "A corporate client wants Islamic financing for a toll road concession. What Shariah-compliant structures can we offer and what is the maximum tenure allowed under our current policy?" Then ask: "What are the BNM disclosure requirements for this type of infrastructure financing?" Show how front-line bankers get consistent, compliant guidance without calling the Shariah department.'
      ], DESC_BUILDER),
    ]),
]

print(f"Industries batch 1 written: {len(INDUSTRIES_1)} entries")
