import sys; sys.path.insert(0,'.')
from util import *

INDUSTRIES_3 = [

# ── HOSPITAL NETWORK ───────────────────────────────────────────────────────
ind('hospital-network', 'healthcare', 'Hospital Network', '🏥', '#1B5E20', '#2E7D32',
    'Saujana Health Systems Berhad',
    'MOH readiness at risk as bed occupancy hits 92% and JCI score slips to 78%.',
    'Saujana Health Systems Berhad runs nine tertiary and secondary hospitals across Klang Valley, Penang, Johor, and East Malaysia, with linked referral pathways into Indonesia. Group revenue is tracking MYR 1.92 billion, but average bed occupancy has surged to 92% while OT utilisation has become uneven, ranging from 54% to 88% across sites. The Department P&L sheet shows oncology and emergency medicine protecting top-line growth while two legacy medical wards are now EBITDA-negative. Patient volumes are rising 11% year on year, yet the JCI Compliance Score sheet shows medication safety, discharge turnaround, and hand-hygiene audit performance all below internal threshold. A Ministry of Health Malaysia review is due in nine weeks, and the Board wants assurance that clinical governance controls in HC_02_Clinical_Governance_Policy.docx are being translated into daily operating discipline. Management is also weighing whether to defer one ward refurbishment after MedTech procurement delays. The Indonesian affiliate is facing similar referral pressure and is watching the group response for Kemenkes reporting alignment.',
    [
        'HC_01_Hospital_Operations.xlsx',
        'HC_02_Clinical_Governance_Policy.docx',
        'HC_03_Hospital_Strategy_Plan.docx'
    ],
    [
      tool(T_CHAT, FREE_LIC, FREE_ACCT, [
        'You are the COO at Saujana Health Systems Berhad. Using the Bed Occupancy, OT Utilisation, Department P&L, and JCI Compliance Score sheets in HC_01_Hospital_Operations.xlsx, prepare a one-page operating diagnostic that explains why occupancy pressure and clinical quality drift are worsening at the same time. Present the answer as a RAG table with columns for Issue, Evidence from Sheet, Likely Root Cause, and 30-Day Action.',
        'You are the Chief Strategy Officer at Saujana Health Systems Berhad. Using HC_02_Clinical_Governance_Policy.docx, HC_03_Hospital_Strategy_Plan.docx, and the Patient Volume Tracker sheet in HC_01_Hospital_Operations.xlsx, identify the 5 decisions management must make before the next executive review so that growth ambitions do not outpace control discipline. Present the answer as a prioritised table with columns for Decision, Why Now, Evidence Source, and Consequence if Deferred.',
        'You are the Head of Corporate Affairs at Saujana Health Systems Berhad. Using the trends implied by the Bed Occupancy, Department P&L, and JCI Compliance Score sheets in HC_01_Hospital_Operations.xlsx, draft a stakeholder communication map covering the Board, regulators, frontline teams, and external partners. Present the answer as a RAG table with columns for Audience, Key Message, Timing, and Communication Risk.'
      ]),
      tool(T_RESEARCHER, FREE_LIC, FREE_ACCT, [
        'You are the Strategy Director at Saujana Health Systems Berhad. Research how comparable organisations in this sector responded when occupancy pressure became visible in operating data like the Bed Occupancy and Department P&L sheets in HC_01_Hospital_Operations.xlsx. Present the answer as a table with columns for Organisation, Trigger, Intervention, Measured Outcome, and Relevance to Saujana Health Systems Berhad. Flag any claim that could not be independently verified.',
        'You are the Compliance Director at Saujana Health Systems Berhad. Research the latest guidance, enforcement themes, and supervisory expectations relevant to MOH Malaysia and the affiliated Indonesian context of Kemenkes, then link them to the control areas implied by HC_02_Clinical_Governance_Policy.docx and the JCI Compliance Score sheet in HC_01_Hospital_Operations.xlsx. Present the answer as a RAG table with columns for Requirement, Malaysia Context, Indonesia Context, Practical Impact, and Immediate Management Action. Flag any claim that could not be independently verified.',
        'You are the CEO at Saujana Health Systems Berhad. Research three recent sector benchmarks on how peers balanced short-term recovery with longer-term priorities when facing clinical quality drift, using the tension visible between the OT Utilisation and Patient Volume Tracker sheets in HC_01_Hospital_Operations.xlsx as the framing context. Present the answer as a table with columns for Peer, What They Changed, Time to Impact, Reported Result, and Lesson for Saujana Health Systems Berhad. Flag any claim that could not be independently verified.'
      ], DESC_RESEARCHER),
      tool(T_ANALYST, M365_LIC, M365_ACCT, [
        'You are the Head of FP&A at Saujana Health Systems Berhad. Upload HC_01_Hospital_Operations.xlsx to Analyst and use the Bed Occupancy, OT Utilisation, Department P&L, and JCI Compliance Score sheets to identify which hospitals are driving the largest share of occupancy pressure and clinical quality drift. Present the output as a RAG table with columns for Hospital, Performance Signal, Financial Impact, Control Risk, and Recommended Owner.',
        'You are the CFO at Saujana Health Systems Berhad. Upload HC_01_Hospital_Operations.xlsx to Analyst and quantify the revenue, margin, or cash exposure linked to the patterns in the Department P&L, Patient Volume Tracker, and JCI Compliance Score sheets, then show where management should intervene first. Present the answer as a ranked table and include one chart that makes the biggest pressure point obvious.',
        'You are the Operations Director at Saujana Health Systems Berhad. Upload HC_01_Hospital_Operations.xlsx to Analyst and build a 3-scenario view for the next two quarters using the Bed Occupancy, OT Utilisation, Department P&L, and Patient Volume Tracker sheets: recover quickly, stabilise slowly, or deteriorate further. Present the result as a RAG table with threshold assumptions, earliest warning sign, and the action that should be triggered in each scenario.'
      ], DESC_ANALYST),
      tool(T_EXCEL, M365_LIC, M365_ACCT, [
        'You are the Business Planning Manager at Saujana Health Systems Berhad. Using the Bed Occupancy, OT Utilisation, Department P&L, and JCI Compliance Score sheets in this workbook, create a new worksheet called Executive RAG Dashboard that summarises the top operating and control risks by hospital. Add conditional formatting so leaders can instantly see Red, Amber, and Green status plus the numeric driver behind each status.',
        'You are the Performance Manager at Saujana Health Systems Berhad. Using the Patient Volume Tracker, Department P&L, and JCI Compliance Score sheets in HC_01_Hospital_Operations.xlsx, create a new worksheet called Intervention Tracker that logs the top 10 corrective actions, the accountable owner, the due date, the expected benefit, and the latest status. Include formulas that highlight overdue actions in red and roll up the count of open Reds at the top of the sheet.',
        "You are the Finance Transformation Lead at Saujana Health Systems Berhad. Using the Bed Occupancy, OT Utilisation, and Department P&L sheets in HC_01_Hospital_Operations.xlsx, build a sensitivity model on a new worksheet that shows how small changes in operating throughput, quality or compliance performance, and unit economics would change the overall outcome. Present the result as an easy-to-read decision table that management can use in tomorrow's review."
      ]),
      tool(T_WORD, M365_LIC, M365_ACCT, [
        'You are the Company Secretary at Saujana Health Systems Berhad. Using HC_02_Clinical_Governance_Policy.docx, HC_03_Hospital_Strategy_Plan.docx, and the evidence implied by the Bed Occupancy, Department P&L, and JCI Compliance Score sheets in HC_01_Hospital_Operations.xlsx, draft a 2-page Board paper on the current situation, the main risks, and the governance actions required in the next 30 days. Start with a short RAG summary and then move into decisions, owners, and timing.',
        'You are the Head of Internal Audit at Saujana Health Systems Berhad. Using HC_02_Clinical_Governance_Policy.docx and the pressure points visible in the JCI Compliance Score and Department P&L sheets in HC_01_Hospital_Operations.xlsx, draft a control-gap memorandum that identifies where process design and frontline execution are drifting apart. Present the core findings as a table with columns for Control Area, Current Gap, Risk if Unresolved, and Proposed Remediation.',
        'You are the CEO at Saujana Health Systems Berhad. Using HC_03_Hospital_Strategy_Plan.docx, the Bed Occupancy sheet, and the Patient Volume Tracker sheet in HC_01_Hospital_Operations.xlsx, draft a one-page management note that explains what can still be delivered this year, what must be reset, and how leadership should talk about the change in priorities. Keep the tone candid, steady, and evidence-based.'
      ]),
      tool(T_PPT, M365_LIC, M365_ACCT, [
        'You are the Chief of Staff at Saujana Health Systems Berhad. Create a 6-slide executive deck using HC_01_Hospital_Operations.xlsx, HC_02_Clinical_Governance_Policy.docx, and HC_03_Hospital_Strategy_Plan.docx as the source context, covering current performance, the root causes behind occupancy pressure and clinical quality drift, the top Red risks, the first 90-day actions, and the decisions required from leadership. Give each slide a headline that states the message, not just the topic.',
        'You are the CFO at Saujana Health Systems Berhad. Create a 5-slide update deck for leadership that uses the Department P&L, Patient Volume Tracker, and JCI Compliance Score sheets in HC_01_Hospital_Operations.xlsx to show where financial exposure is concentrated and how quickly it can be reduced. Include speaker notes that explain the Red issues in plain language for a non-technical audience.',
        'You are the Strategy Director at Saujana Health Systems Berhad. Create a single summary slide that links the signals in the Bed Occupancy, OT Utilisation, and JCI Compliance Score sheets in HC_01_Hospital_Operations.xlsx to the priorities in HC_03_Hospital_Strategy_Plan.docx. Present it as a RAG matrix with one sentence of management action beside each Red item.'
      ]),
      tool(T_OUTLOOK, M365_LIC, M365_ACCT, [
        'You are the Regulatory Affairs Lead at Saujana Health Systems Berhad. Draft an email to the relevant authorities and senior internal stakeholders that acknowledges the current pressure areas indicated by the JCI Compliance Score sheet in HC_01_Hospital_Operations.xlsx, outlines the corrective steps already under way, and requests alignment on the next review checkpoint. Keep the tone factual, controlled, and suitable for scrutiny by MOH Malaysia and Kemenkes counterparts.',
        'You are the COO at Saujana Health Systems Berhad. Draft an internal email to Hospital Directors and clinical leaders summarising the top three risks shown in the Bed Occupancy, Department P&L, and JCI Compliance Score sheets in HC_01_Hospital_Operations.xlsx, the required actions this week, and the consequences of delay. End with a bullet list titled What I need from you by Friday.',
        'You are the Head of Stakeholder Management at Saujana Health Systems Berhad. Draft an external-facing update that explains the current operating situation using plain language consistent with HC_02_Clinical_Governance_Policy.docx and HC_03_Hospital_Strategy_Plan.docx, without overpromising outcomes or admitting fault. Use the evidence implied by the Patient Volume Tracker and Department P&L sheets in HC_01_Hospital_Operations.xlsx to keep the message disciplined.'
      ]),
      tool(T_TEAMS, M365_LIC, M365_ACCT, [
        'You are the Chief of Staff at Saujana Health Systems Berhad. Using this recorded Teams meeting recap, identify the decisions, unresolved issues, and action items that connect directly to the Bed Occupancy, Department P&L, and JCI Compliance Score sheets in HC_01_Hospital_Operations.xlsx. Present the output as a RAG table with columns for Topic, What Was Said, Owner, Due Date, and Escalation Level.',
        'You are the Operations Director at Saujana Health Systems Berhad. Using this Teams recap, draft follow-up actions for the teams responsible for the areas covered in HC_02_Clinical_Governance_Policy.docx and the OT Utilisation sheet in HC_01_Hospital_Operations.xlsx. Group the actions by workstream and include a success measure for each one.',
        'You are the CFO at Saujana Health Systems Berhad. Using this Teams recap, extract every financial, compliance, or customer-impact figure that would help explain the trends in the Department P&L, Patient Volume Tracker, and JCI Compliance Score sheets in HC_01_Hospital_Operations.xlsx. Present the result as a structured note with sections for Facts, Risks, Commitments, and Missing Information.'
      ], DESC_TEAMS),
      tool(T_NOTEBOOK, M365_LIC, M365_ACCT, [
        'You are the CEO at Saujana Health Systems Berhad. Upload HC_01_Hospital_Operations.xlsx, HC_02_Clinical_Governance_Policy.docx, HC_03_Hospital_Strategy_Plan.docx to Copilot Notebook, set the instruction to synthesise across all files with citations, and ask for the 10-slide-equivalent story leadership needs right now. Require Notebook to reconcile the signals from the Bed Occupancy, Department P&L, and JCI Compliance Score sheets in HC_01_Hospital_Operations.xlsx with the commitments in HC_02_Clinical_Governance_Policy.docx and HC_03_Hospital_Strategy_Plan.docx.',
        'You are the COO at Saujana Health Systems Berhad. Upload HC_01_Hospital_Operations.xlsx, HC_02_Clinical_Governance_Policy.docx, HC_03_Hospital_Strategy_Plan.docx to Copilot Notebook and ask whether the priorities implied by the OT Utilisation and Patient Volume Tracker sheets in HC_01_Hospital_Operations.xlsx are still realistic given the risk picture in the JCI Compliance Score sheet. Require a RAG table with columns for Priority, Evidence, Risk to Delivery, and Recommendation, all with citations.',
        'You are the Board Liaison at Saujana Health Systems Berhad. Upload HC_01_Hospital_Operations.xlsx, HC_02_Clinical_Governance_Policy.docx, HC_03_Hospital_Strategy_Plan.docx to Copilot Notebook and ask for the contradictions management must resolve before the next review, especially where operational ambition, control capability, and financial reality do not line up. Request a concise answer with sections for Contradictions, Questions Directors Will Ask, and Pre-Reads to Send.'
      ], DESC_NOTEBOOK),
      tool(T_COWORK, M365_LIC, M365_ACCT, [
        'You are the COO at Saujana Health Systems Berhad. Do all of the following autonomously: create a recovery action plan grounded in the Bed Occupancy, Department P&L, and JCI Compliance Score sheets in HC_01_Hospital_Operations.xlsx; save it to OneDrive; email it to Hospital Directors and clinical leaders; and schedule a 45-minute review meeting for next week. Make the plan easy to track with RAG status and owner-by-owner accountability.',
        'You are the Chief of Staff at Saujana Health Systems Berhad. Do all of the following autonomously: turn the main obligations from HC_02_Clinical_Governance_Policy.docx and the priorities from HC_03_Hospital_Strategy_Plan.docx into a working checklist, save it in OneDrive, email the checklist to the accountable leaders, and create calendar reminders for each major milestone. Keep the wording clear enough that teams can act without a second briefing.'
      ], DESC_COWORK),
      tool(T_EDIT_COPILOT, M365_LIC, M365_ACCT, [
        'You are the Company Secretary at Saujana Health Systems Berhad. Using HC_02_Clinical_Governance_Policy.docx in Word for the web, add an appendix titled Operating Escalation and RAG Governance Protocol and populate it with decision rights, escalation thresholds, evidence requirements, and sign-off owners that mirror the issues visible in the JCI Compliance Score and Department P&L sheets in HC_01_Hospital_Operations.xlsx. Keep the style consistent with the existing document.',
        'You are the Performance Manager at Saujana Health Systems Berhad. Using HC_01_Hospital_Operations.xlsx in Excel for the web, create a new worksheet called Leadership Recovery Tracker that combines the Bed Occupancy, Department P&L, Patient Volume Tracker, and JCI Compliance Score sheets into a single view with owner, due date, expected impact, and live RAG status. Reorder the layout so the Red issues appear first and add formulas that refresh the summary automatically.'
      ], DESC_EDIT_COPILOT),
      tool(T_WORD_AGT, M365_LIC, M365_ACCT, [
        'You are the Knowledge Manager at Saujana Health Systems Berhad. Open HC_02_Clinical_Governance_Policy.docx in Word for Web and create an agent called Clinical Governance Navigator. Describe it as an assistant that answers questions about the policies, thresholds, and escalation rules that matter when the JCI Compliance Score sheet and the Department P&L sheet in HC_01_Hospital_Operations.xlsx start to move against plan, then share it with the core leadership team.',
        'You are the COO at Saujana Health Systems Berhad. Demo the Clinical Governance Navigator agent by asking: Our oncology waitlist has crossed the internal threshold and the JCI compliance score for medication reconciliation is Amber. What is the escalation pathway, who owns the corrective action, and what evidence should we prepare before the MOH review? Show how the answer cites the source document and gives a clear next step.'
      ], DESC_WORD_AGT),
      tool(T_PPT_AGT, M365_LIC, M365_ACCT, [
        'You are the Chief of Staff at Saujana Health Systems Berhad. Create the leadership deck in PowerPoint for Web, then create an agent called Hospital Network Board Bot that helps executives find the right slide, chart, and message quickly. Make sure it can answer questions grounded in the Bed Occupancy, Department P&L, and JCI Compliance Score sheets in HC_01_Hospital_Operations.xlsx.',
        'You are the CFO at Saujana Health Systems Berhad. Demo the Hospital Network Board Bot agent by asking which Red issue needs leadership attention first, what slide supports that answer, and what decision should be taken this week. Keep the response short enough to use in a live meeting.'
      ], DESC_PPT_AGT),
      tool(T_XL_AGT, M365_LIC, M365_ACCT, [
        'You are the Data Product Owner at Saujana Health Systems Berhad. Open HC_01_Hospital_Operations.xlsx in Excel for Web and create an agent called Hospital Operations Q&A. Describe it as an assistant that answers plain-English questions about the Bed Occupancy, OT Utilisation, Department P&L, Patient Volume Tracker, and JCI Compliance Score sheets and share it with the teams that need faster insight.',
        'You are the COO at Saujana Health Systems Berhad. Demo the Hospital Operations Q&A agent by asking which hospital is currently Red, what is driving the status, and what leading indicator should be watched next. Then ask for the one figure from the workbook that leadership should remember before the next review.'
      ], DESC_XL_AGT),
      tool(T_BUILDER, M365_LIC, M365_ACCT, [
        'You are the Digital Transformation Lead at Saujana Health Systems Berhad. Go to copilotstudio.microsoft.com, create a new agent called Saujana Care Operations Assistant, use HC_01_Hospital_Operations.xlsx, HC_02_Clinical_Governance_Policy.docx, HC_03_Hospital_Strategy_Plan.docx as the knowledge sources, and configure topics for Bed Management, Clinical Governance, MOH Readiness, Oncology Access. Publish it to Teams with instructions that it should answer in a concise, evidence-based way and surface a clear escalation path when users ask high-risk questions.',
        'You are the Operations Director at Saujana Health Systems Berhad. Demo the Saujana Care Operations Assistant agent by asking: Our oncology waitlist has crossed the internal threshold and the JCI compliance score for medication reconciliation is Amber. What is the escalation pathway, who owns the corrective action, and what evidence should we prepare before the MOH review? Show how the agent responds with the relevant file, the recommended action, and the owner who should take the next step.'
      ], DESC_BUILDER),
    ],
    companyID='PT Saujana Jaringan Medika Tbk',
    taglineID='Audit Kemenkes makin dekat ketika BOR 92% dan skor mutu turun ke 78%.'),

# ── PHARMACEUTICAL ───────────────────────────────────────────────────────
ind('pharmaceutical', 'healthcare', 'Pharmaceutical', '💊', '#2E7D32', '#388E3C',
    'Cendana BioPharma Berhad',
    'MOH launch window tightens as approval queries rise and supply KPIs weaken.',
    'Cendana BioPharma Berhad manufactures branded generics and specialty therapies from Johor and distributes across Malaysia and Indonesia through a BPOM-registered affiliate. The Product Revenue sheet shows the top five molecules still driving 63% of sales, but margin pressure is emerging as tender pricing softens and freight inflation pushes landed cost higher. In the R&D Pipeline Tracker sheet, three late-stage assets are clustered into a 14-month window, creating portfolio concentration risk if any filing slips. The Regulatory Approval Log shows multiple agency questions outstanding, including two Malaysian MOH-related label clarifications and one BPOM chemistry query that is delaying the Indonesian launch bridge. Supply Chain KPIs indicate fill rate has fallen to 93% against a 97% target, with service failures concentrated in two temperature-sensitive SKUs. Leadership needs to align HC-style quality language in PH_02_Regulatory_Affairs_Manual.docx with the execution cadence in PH_03_Clinical_Trials_Protocol.docx before the next Audit Committee review. The Indonesian team is also preparing Kemenkes and BPOM stakeholder messaging should the flagship diabetes launch move by another quarter.',
    [
        'PH_01_Drug_Portfolio.xlsx',
        'PH_02_Regulatory_Affairs_Manual.docx',
        'PH_03_Clinical_Trials_Protocol.docx'
    ],
    [
      tool(T_CHAT, FREE_LIC, FREE_ACCT, [
        'You are the COO at Cendana BioPharma Berhad. Using the Product Revenue, R&D Pipeline Tracker, Supply Chain KPIs, and Regulatory Approval Log sheets in PH_01_Drug_Portfolio.xlsx, prepare a one-page operating diagnostic that explains why regulatory approval slippage and portfolio and supply-chain concentration risk are worsening at the same time. Present the answer as a RAG table with columns for Issue, Evidence from Sheet, Likely Root Cause, and 30-Day Action.',
        'You are the Chief Strategy Officer at Cendana BioPharma Berhad. Using PH_02_Regulatory_Affairs_Manual.docx, PH_03_Clinical_Trials_Protocol.docx, and the Market Share Analysis sheet in PH_01_Drug_Portfolio.xlsx, identify the 5 decisions management must make before the next executive review so that growth ambitions do not outpace control discipline. Present the answer as a prioritised table with columns for Decision, Why Now, Evidence Source, and Consequence if Deferred.',
        'You are the Head of Corporate Affairs at Cendana BioPharma Berhad. Using the trends implied by the Product Revenue, Supply Chain KPIs, and Regulatory Approval Log sheets in PH_01_Drug_Portfolio.xlsx, draft a stakeholder communication map covering the Board, regulators, frontline teams, and external partners. Present the answer as a RAG table with columns for Audience, Key Message, Timing, and Communication Risk.'
      ]),
      tool(T_RESEARCHER, FREE_LIC, FREE_ACCT, [
        'You are the Strategy Director at Cendana BioPharma Berhad. Research how comparable organisations in this sector responded when regulatory approval slippage became visible in operating data like the Product Revenue and Supply Chain KPIs sheets in PH_01_Drug_Portfolio.xlsx. Present the answer as a table with columns for Organisation, Trigger, Intervention, Measured Outcome, and Relevance to Cendana BioPharma Berhad. Flag any claim that could not be independently verified.',
        'You are the Compliance Director at Cendana BioPharma Berhad. Research the latest guidance, enforcement themes, and supervisory expectations relevant to MOH Malaysia and the affiliated Indonesian context of BPOM and Kemenkes, then link them to the control areas implied by PH_02_Regulatory_Affairs_Manual.docx and the Regulatory Approval Log sheet in PH_01_Drug_Portfolio.xlsx. Present the answer as a RAG table with columns for Requirement, Malaysia Context, Indonesia Context, Practical Impact, and Immediate Management Action. Flag any claim that could not be independently verified.',
        'You are the CEO at Cendana BioPharma Berhad. Research three recent sector benchmarks on how peers balanced short-term recovery with longer-term priorities when facing portfolio and supply-chain concentration risk, using the tension visible between the R&D Pipeline Tracker and Market Share Analysis sheets in PH_01_Drug_Portfolio.xlsx as the framing context. Present the answer as a table with columns for Peer, What They Changed, Time to Impact, Reported Result, and Lesson for Cendana BioPharma Berhad. Flag any claim that could not be independently verified.'
      ], DESC_RESEARCHER),
      tool(T_ANALYST, M365_LIC, M365_ACCT, [
        'You are the Head of FP&A at Cendana BioPharma Berhad. Upload PH_01_Drug_Portfolio.xlsx to Analyst and use the Product Revenue, R&D Pipeline Tracker, Supply Chain KPIs, and Regulatory Approval Log sheets to identify which product or markets are driving the largest share of regulatory approval slippage and portfolio and supply-chain concentration risk. Present the output as a RAG table with columns for Product Or Market, Performance Signal, Financial Impact, Control Risk, and Recommended Owner.',
        'You are the CFO at Cendana BioPharma Berhad. Upload PH_01_Drug_Portfolio.xlsx to Analyst and quantify the revenue, margin, or cash exposure linked to the patterns in the Supply Chain KPIs, Market Share Analysis, and Regulatory Approval Log sheets, then show where management should intervene first. Present the answer as a ranked table and include one chart that makes the biggest pressure point obvious.',
        'You are the Operations Director at Cendana BioPharma Berhad. Upload PH_01_Drug_Portfolio.xlsx to Analyst and build a 3-scenario view for the next two quarters using the Product Revenue, R&D Pipeline Tracker, Supply Chain KPIs, and Market Share Analysis sheets: recover quickly, stabilise slowly, or deteriorate further. Present the result as a RAG table with threshold assumptions, earliest warning sign, and the action that should be triggered in each scenario.'
      ], DESC_ANALYST),
      tool(T_EXCEL, M365_LIC, M365_ACCT, [
        'You are the Business Planning Manager at Cendana BioPharma Berhad. Using the Product Revenue, R&D Pipeline Tracker, Supply Chain KPIs, and Regulatory Approval Log sheets in this workbook, create a new worksheet called Executive RAG Dashboard that summarises the top operating and control risks by product or market. Add conditional formatting so leaders can instantly see Red, Amber, and Green status plus the numeric driver behind each status.',
        'You are the Performance Manager at Cendana BioPharma Berhad. Using the Market Share Analysis, Supply Chain KPIs, and Regulatory Approval Log sheets in PH_01_Drug_Portfolio.xlsx, create a new worksheet called Intervention Tracker that logs the top 10 corrective actions, the accountable owner, the due date, the expected benefit, and the latest status. Include formulas that highlight overdue actions in red and roll up the count of open Reds at the top of the sheet.',
        "You are the Finance Transformation Lead at Cendana BioPharma Berhad. Using the Product Revenue, R&D Pipeline Tracker, and Supply Chain KPIs sheets in PH_01_Drug_Portfolio.xlsx, build a sensitivity model on a new worksheet that shows how small changes in operating throughput, quality or compliance performance, and unit economics would change the overall outcome. Present the result as an easy-to-read decision table that management can use in tomorrow's review."
      ]),
      tool(T_WORD, M365_LIC, M365_ACCT, [
        'You are the Company Secretary at Cendana BioPharma Berhad. Using PH_02_Regulatory_Affairs_Manual.docx, PH_03_Clinical_Trials_Protocol.docx, and the evidence implied by the Product Revenue, Supply Chain KPIs, and Regulatory Approval Log sheets in PH_01_Drug_Portfolio.xlsx, draft a 2-page Board paper on the current situation, the main risks, and the governance actions required in the next 30 days. Start with a short RAG summary and then move into decisions, owners, and timing.',
        'You are the Head of Internal Audit at Cendana BioPharma Berhad. Using PH_02_Regulatory_Affairs_Manual.docx and the pressure points visible in the Regulatory Approval Log and Supply Chain KPIs sheets in PH_01_Drug_Portfolio.xlsx, draft a control-gap memorandum that identifies where process design and frontline execution are drifting apart. Present the core findings as a table with columns for Control Area, Current Gap, Risk if Unresolved, and Proposed Remediation.',
        'You are the CEO at Cendana BioPharma Berhad. Using PH_03_Clinical_Trials_Protocol.docx, the Product Revenue sheet, and the Market Share Analysis sheet in PH_01_Drug_Portfolio.xlsx, draft a one-page management note that explains what can still be delivered this year, what must be reset, and how leadership should talk about the change in priorities. Keep the tone candid, steady, and evidence-based.'
      ]),
      tool(T_PPT, M365_LIC, M365_ACCT, [
        'You are the Chief of Staff at Cendana BioPharma Berhad. Create a 6-slide executive deck using PH_01_Drug_Portfolio.xlsx, PH_02_Regulatory_Affairs_Manual.docx, and PH_03_Clinical_Trials_Protocol.docx as the source context, covering current performance, the root causes behind regulatory approval slippage and portfolio and supply-chain concentration risk, the top Red risks, the first 90-day actions, and the decisions required from leadership. Give each slide a headline that states the message, not just the topic.',
        'You are the CFO at Cendana BioPharma Berhad. Create a 5-slide update deck for leadership that uses the Supply Chain KPIs, Market Share Analysis, and Regulatory Approval Log sheets in PH_01_Drug_Portfolio.xlsx to show where financial exposure is concentrated and how quickly it can be reduced. Include speaker notes that explain the Red issues in plain language for a non-technical audience.',
        'You are the Strategy Director at Cendana BioPharma Berhad. Create a single summary slide that links the signals in the Product Revenue, R&D Pipeline Tracker, and Regulatory Approval Log sheets in PH_01_Drug_Portfolio.xlsx to the priorities in PH_03_Clinical_Trials_Protocol.docx. Present it as a RAG matrix with one sentence of management action beside each Red item.'
      ]),
      tool(T_OUTLOOK, M365_LIC, M365_ACCT, [
        'You are the Regulatory Affairs Lead at Cendana BioPharma Berhad. Draft an email to the relevant authorities and senior internal stakeholders that acknowledges the current pressure areas indicated by the Regulatory Approval Log sheet in PH_01_Drug_Portfolio.xlsx, outlines the corrective steps already under way, and requests alignment on the next review checkpoint. Keep the tone factual, controlled, and suitable for scrutiny by MOH Malaysia and BPOM and Kemenkes counterparts.',
        'You are the COO at Cendana BioPharma Berhad. Draft an internal email to Regulatory, medical, and commercial leaders summarising the top three risks shown in the Product Revenue, Supply Chain KPIs, and Regulatory Approval Log sheets in PH_01_Drug_Portfolio.xlsx, the required actions this week, and the consequences of delay. End with a bullet list titled What I need from you by Friday.',
        'You are the Head of Stakeholder Management at Cendana BioPharma Berhad. Draft an external-facing update that explains the current operating situation using plain language consistent with PH_02_Regulatory_Affairs_Manual.docx and PH_03_Clinical_Trials_Protocol.docx, without overpromising outcomes or admitting fault. Use the evidence implied by the Market Share Analysis and Supply Chain KPIs sheets in PH_01_Drug_Portfolio.xlsx to keep the message disciplined.'
      ]),
      tool(T_TEAMS, M365_LIC, M365_ACCT, [
        'You are the Chief of Staff at Cendana BioPharma Berhad. Using this recorded Teams meeting recap, identify the decisions, unresolved issues, and action items that connect directly to the Product Revenue, Supply Chain KPIs, and Regulatory Approval Log sheets in PH_01_Drug_Portfolio.xlsx. Present the output as a RAG table with columns for Topic, What Was Said, Owner, Due Date, and Escalation Level.',
        'You are the Operations Director at Cendana BioPharma Berhad. Using this Teams recap, draft follow-up actions for the teams responsible for the areas covered in PH_02_Regulatory_Affairs_Manual.docx and the R&D Pipeline Tracker sheet in PH_01_Drug_Portfolio.xlsx. Group the actions by workstream and include a success measure for each one.',
        'You are the CFO at Cendana BioPharma Berhad. Using this Teams recap, extract every financial, compliance, or customer-impact figure that would help explain the trends in the Supply Chain KPIs, Market Share Analysis, and Regulatory Approval Log sheets in PH_01_Drug_Portfolio.xlsx. Present the result as a structured note with sections for Facts, Risks, Commitments, and Missing Information.'
      ], DESC_TEAMS),
      tool(T_NOTEBOOK, M365_LIC, M365_ACCT, [
        'You are the CEO at Cendana BioPharma Berhad. Upload PH_01_Drug_Portfolio.xlsx, PH_02_Regulatory_Affairs_Manual.docx, PH_03_Clinical_Trials_Protocol.docx to Copilot Notebook, set the instruction to synthesise across all files with citations, and ask for the 10-slide-equivalent story leadership needs right now. Require Notebook to reconcile the signals from the Product Revenue, Supply Chain KPIs, and Regulatory Approval Log sheets in PH_01_Drug_Portfolio.xlsx with the commitments in PH_02_Regulatory_Affairs_Manual.docx and PH_03_Clinical_Trials_Protocol.docx.',
        'You are the COO at Cendana BioPharma Berhad. Upload PH_01_Drug_Portfolio.xlsx, PH_02_Regulatory_Affairs_Manual.docx, PH_03_Clinical_Trials_Protocol.docx to Copilot Notebook and ask whether the priorities implied by the R&D Pipeline Tracker and Market Share Analysis sheets in PH_01_Drug_Portfolio.xlsx are still realistic given the risk picture in the Regulatory Approval Log sheet. Require a RAG table with columns for Priority, Evidence, Risk to Delivery, and Recommendation, all with citations.',
        'You are the Board Liaison at Cendana BioPharma Berhad. Upload PH_01_Drug_Portfolio.xlsx, PH_02_Regulatory_Affairs_Manual.docx, PH_03_Clinical_Trials_Protocol.docx to Copilot Notebook and ask for the contradictions management must resolve before the next review, especially where operational ambition, control capability, and financial reality do not line up. Request a concise answer with sections for Contradictions, Questions Directors Will Ask, and Pre-Reads to Send.'
      ], DESC_NOTEBOOK),
      tool(T_COWORK, M365_LIC, M365_ACCT, [
        'You are the COO at Cendana BioPharma Berhad. Do all of the following autonomously: create a recovery action plan grounded in the Product Revenue, Supply Chain KPIs, and Regulatory Approval Log sheets in PH_01_Drug_Portfolio.xlsx; save it to OneDrive; email it to Regulatory, medical, and commercial leaders; and schedule a 45-minute review meeting for next week. Make the plan easy to track with RAG status and owner-by-owner accountability.',
        'You are the Chief of Staff at Cendana BioPharma Berhad. Do all of the following autonomously: turn the main obligations from PH_02_Regulatory_Affairs_Manual.docx and the priorities from PH_03_Clinical_Trials_Protocol.docx into a working checklist, save it in OneDrive, email the checklist to the accountable leaders, and create calendar reminders for each major milestone. Keep the wording clear enough that teams can act without a second briefing.'
      ], DESC_COWORK),
      tool(T_EDIT_COPILOT, M365_LIC, M365_ACCT, [
        'You are the Company Secretary at Cendana BioPharma Berhad. Using PH_02_Regulatory_Affairs_Manual.docx in Word for the web, add an appendix titled Operating Escalation and RAG Governance Protocol and populate it with decision rights, escalation thresholds, evidence requirements, and sign-off owners that mirror the issues visible in the Regulatory Approval Log and Supply Chain KPIs sheets in PH_01_Drug_Portfolio.xlsx. Keep the style consistent with the existing document.',
        'You are the Performance Manager at Cendana BioPharma Berhad. Using PH_01_Drug_Portfolio.xlsx in Excel for the web, create a new worksheet called Leadership Recovery Tracker that combines the Product Revenue, Supply Chain KPIs, Market Share Analysis, and Regulatory Approval Log sheets into a single view with owner, due date, expected impact, and live RAG status. Reorder the layout so the Red issues appear first and add formulas that refresh the summary automatically.'
      ], DESC_EDIT_COPILOT),
      tool(T_WORD_AGT, M365_LIC, M365_ACCT, [
        'You are the Knowledge Manager at Cendana BioPharma Berhad. Open PH_02_Regulatory_Affairs_Manual.docx in Word for Web and create an agent called Regulatory Affairs Navigator. Describe it as an assistant that answers questions about the policies, thresholds, and escalation rules that matter when the Regulatory Approval Log sheet and the Supply Chain KPIs sheet in PH_01_Drug_Portfolio.xlsx start to move against plan, then share it with the core leadership team.',
        'You are the COO at Cendana BioPharma Berhad. Demo the Regulatory Affairs Navigator agent by asking: BPOM has issued another CMC clarification on our lead diabetes product and the fill rate is below target. What is the likely launch impact, what escalation steps are required under our manual, and which evidence from the Regulatory Approval Log and Supply Chain KPIs should management review first? Show how the answer cites the source document and gives a clear next step.'
      ], DESC_WORD_AGT),
      tool(T_PPT_AGT, M365_LIC, M365_ACCT, [
        'You are the Chief of Staff at Cendana BioPharma Berhad. Create the leadership deck in PowerPoint for Web, then create an agent called Portfolio Review Board Bot that helps executives find the right slide, chart, and message quickly. Make sure it can answer questions grounded in the Product Revenue, Supply Chain KPIs, and Regulatory Approval Log sheets in PH_01_Drug_Portfolio.xlsx.',
        'You are the CFO at Cendana BioPharma Berhad. Demo the Portfolio Review Board Bot agent by asking which Red issue needs leadership attention first, what slide supports that answer, and what decision should be taken this week. Keep the response short enough to use in a live meeting.'
      ], DESC_PPT_AGT),
      tool(T_XL_AGT, M365_LIC, M365_ACCT, [
        'You are the Data Product Owner at Cendana BioPharma Berhad. Open PH_01_Drug_Portfolio.xlsx in Excel for Web and create an agent called Pharma Portfolio Q&A. Describe it as an assistant that answers plain-English questions about the Product Revenue, R&D Pipeline Tracker, Supply Chain KPIs, Market Share Analysis, and Regulatory Approval Log sheets and share it with the teams that need faster insight.',
        'You are the COO at Cendana BioPharma Berhad. Demo the Pharma Portfolio Q&A agent by asking which product or market is currently Red, what is driving the status, and what leading indicator should be watched next. Then ask for the one figure from the workbook that leadership should remember before the next review.'
      ], DESC_XL_AGT),
      tool(T_BUILDER, M365_LIC, M365_ACCT, [
        'You are the Digital Transformation Lead at Cendana BioPharma Berhad. Go to copilotstudio.microsoft.com, create a new agent called Cendana Launch Readiness Assistant, use PH_01_Drug_Portfolio.xlsx, PH_02_Regulatory_Affairs_Manual.docx, PH_03_Clinical_Trials_Protocol.docx as the knowledge sources, and configure topics for Registration Readiness, Pipeline Priorities, Supply Chain Risk, Market Share. Publish it to Teams with instructions that it should answer in a concise, evidence-based way and surface a clear escalation path when users ask high-risk questions.',
        'You are the Operations Director at Cendana BioPharma Berhad. Demo the Cendana Launch Readiness Assistant agent by asking: BPOM has issued another CMC clarification on our lead diabetes product and the fill rate is below target. What is the likely launch impact, what escalation steps are required under our manual, and which evidence from the Regulatory Approval Log and Supply Chain KPIs should management review first? Show how the agent responds with the relevant file, the recommended action, and the owner who should take the next step.'
      ], DESC_BUILDER),
    ],
    companyID='PT Cendana Biofarma Nusantara Tbk',
    taglineID='BPOM menekan jadwal peluncuran saat query registrasi naik dan KPI suplai melemah.'),

# ── OG UPSTREAM ───────────────────────────────────────────────────────
ind('og-upstream', 'og-energy', 'Oil & Gas Upstream', '🛢️', '#E65100', '#F57C00',
    'Lautan Merdeka Energy Berhad',
    'PETRONAS scrutiny rises as lifting cost climbs to USD19.8/bbl and HSSE incidents trend upward.',
    'Lautan Merdeka Energy Berhad operates mature offshore assets in Peninsular Malaysia and a participating interest in an Indonesian block through PT Lautan Merdeka Energi Tbk. The Daily Production Log shows average output at 41.6 mboepd, 7% below plan after unplanned deferment on two wells and longer compressor downtime. Reservoir Performance indicates water cut is rising faster than the FDP assumptions for one brownfield cluster, while the Lifting Cost Tracker has moved to USD19.8 per barrel versus a budget of USD16.2. The HSSE Incident Register shows three recordable events in five months, including one hydrocarbon release that triggered PETRONAS follow-up questions. Capex vs Budget also shows subsea integrity spending running 14% ahead of plan, putting pressure on cash generation just as the Board is reviewing the next phase of OGU_03_Field_Development_Plan.docx. DOSH expectations, PETRONAS operational assurance, and Indonesian SKK Migas production commitments all matter in the next quarter. Management needs a tighter read-through between OGU_02_HSE_Policy.docx and field execution before the next asset review committee.',
    [
        'OGU_01_Production_Operations.xlsx',
        'OGU_02_HSE_Policy.docx',
        'OGU_03_Field_Development_Plan.docx'
    ],
    [
      tool(T_CHAT, FREE_LIC, FREE_ACCT, [
        'You are the COO at Lautan Merdeka Energy Berhad. Using the Daily Production Log, Reservoir Performance, Lifting Cost Tracker, and HSSE Incident Register sheets in OGU_01_Production_Operations.xlsx, prepare a one-page operating diagnostic that explains why production under-delivery and cost and HSSE pressure are worsening at the same time. Present the answer as a RAG table with columns for Issue, Evidence from Sheet, Likely Root Cause, and 30-Day Action.',
        'You are the Chief Strategy Officer at Lautan Merdeka Energy Berhad. Using OGU_02_HSE_Policy.docx, OGU_03_Field_Development_Plan.docx, and the Capex vs Budget sheet in OGU_01_Production_Operations.xlsx, identify the 5 decisions management must make before the next executive review so that growth ambitions do not outpace control discipline. Present the answer as a prioritised table with columns for Decision, Why Now, Evidence Source, and Consequence if Deferred.',
        'You are the Head of Corporate Affairs at Lautan Merdeka Energy Berhad. Using the trends implied by the Daily Production Log, Lifting Cost Tracker, and HSSE Incident Register sheets in OGU_01_Production_Operations.xlsx, draft a stakeholder communication map covering the Board, regulators, frontline teams, and external partners. Present the answer as a RAG table with columns for Audience, Key Message, Timing, and Communication Risk.'
      ]),
      tool(T_RESEARCHER, FREE_LIC, FREE_ACCT, [
        'You are the Strategy Director at Lautan Merdeka Energy Berhad. Research how comparable organisations in this sector responded when production under-delivery became visible in operating data like the Daily Production Log and Lifting Cost Tracker sheets in OGU_01_Production_Operations.xlsx. Present the answer as a table with columns for Organisation, Trigger, Intervention, Measured Outcome, and Relevance to Lautan Merdeka Energy Berhad. Flag any claim that could not be independently verified.',
        'You are the Compliance Director at Lautan Merdeka Energy Berhad. Research the latest guidance, enforcement themes, and supervisory expectations relevant to PETRONAS and DOSH and the affiliated Indonesian context of SKK Migas, then link them to the control areas implied by OGU_02_HSE_Policy.docx and the HSSE Incident Register sheet in OGU_01_Production_Operations.xlsx. Present the answer as a RAG table with columns for Requirement, Malaysia Context, Indonesia Context, Practical Impact, and Immediate Management Action. Flag any claim that could not be independently verified.',
        'You are the CEO at Lautan Merdeka Energy Berhad. Research three recent sector benchmarks on how peers balanced short-term recovery with longer-term priorities when facing cost and HSSE pressure, using the tension visible between the Reservoir Performance and Capex vs Budget sheets in OGU_01_Production_Operations.xlsx as the framing context. Present the answer as a table with columns for Peer, What They Changed, Time to Impact, Reported Result, and Lesson for Lautan Merdeka Energy Berhad. Flag any claim that could not be independently verified.'
      ], DESC_RESEARCHER),
      tool(T_ANALYST, M365_LIC, M365_ACCT, [
        'You are the Head of FP&A at Lautan Merdeka Energy Berhad. Upload OGU_01_Production_Operations.xlsx to Analyst and use the Daily Production Log, Reservoir Performance, Lifting Cost Tracker, and HSSE Incident Register sheets to identify which asset or fields are driving the largest share of production under-delivery and cost and HSSE pressure. Present the output as a RAG table with columns for Asset Or Field, Performance Signal, Financial Impact, Control Risk, and Recommended Owner.',
        'You are the CFO at Lautan Merdeka Energy Berhad. Upload OGU_01_Production_Operations.xlsx to Analyst and quantify the revenue, margin, or cash exposure linked to the patterns in the Lifting Cost Tracker, Capex vs Budget, and HSSE Incident Register sheets, then show where management should intervene first. Present the answer as a ranked table and include one chart that makes the biggest pressure point obvious.',
        'You are the Operations Director at Lautan Merdeka Energy Berhad. Upload OGU_01_Production_Operations.xlsx to Analyst and build a 3-scenario view for the next two quarters using the Daily Production Log, Reservoir Performance, Lifting Cost Tracker, and Capex vs Budget sheets: recover quickly, stabilise slowly, or deteriorate further. Present the result as a RAG table with threshold assumptions, earliest warning sign, and the action that should be triggered in each scenario.'
      ], DESC_ANALYST),
      tool(T_EXCEL, M365_LIC, M365_ACCT, [
        'You are the Business Planning Manager at Lautan Merdeka Energy Berhad. Using the Daily Production Log, Reservoir Performance, Lifting Cost Tracker, and HSSE Incident Register sheets in this workbook, create a new worksheet called Executive RAG Dashboard that summarises the top operating and control risks by asset or field. Add conditional formatting so leaders can instantly see Red, Amber, and Green status plus the numeric driver behind each status.',
        'You are the Performance Manager at Lautan Merdeka Energy Berhad. Using the Capex vs Budget, Lifting Cost Tracker, and HSSE Incident Register sheets in OGU_01_Production_Operations.xlsx, create a new worksheet called Intervention Tracker that logs the top 10 corrective actions, the accountable owner, the due date, the expected benefit, and the latest status. Include formulas that highlight overdue actions in red and roll up the count of open Reds at the top of the sheet.',
        "You are the Finance Transformation Lead at Lautan Merdeka Energy Berhad. Using the Daily Production Log, Reservoir Performance, and Lifting Cost Tracker sheets in OGU_01_Production_Operations.xlsx, build a sensitivity model on a new worksheet that shows how small changes in operating throughput, quality or compliance performance, and unit economics would change the overall outcome. Present the result as an easy-to-read decision table that management can use in tomorrow's review."
      ]),
      tool(T_WORD, M365_LIC, M365_ACCT, [
        'You are the Company Secretary at Lautan Merdeka Energy Berhad. Using OGU_02_HSE_Policy.docx, OGU_03_Field_Development_Plan.docx, and the evidence implied by the Daily Production Log, Lifting Cost Tracker, and HSSE Incident Register sheets in OGU_01_Production_Operations.xlsx, draft a 2-page Board paper on the current situation, the main risks, and the governance actions required in the next 30 days. Start with a short RAG summary and then move into decisions, owners, and timing.',
        'You are the Head of Internal Audit at Lautan Merdeka Energy Berhad. Using OGU_02_HSE_Policy.docx and the pressure points visible in the HSSE Incident Register and Lifting Cost Tracker sheets in OGU_01_Production_Operations.xlsx, draft a control-gap memorandum that identifies where process design and frontline execution are drifting apart. Present the core findings as a table with columns for Control Area, Current Gap, Risk if Unresolved, and Proposed Remediation.',
        'You are the CEO at Lautan Merdeka Energy Berhad. Using OGU_03_Field_Development_Plan.docx, the Daily Production Log sheet, and the Capex vs Budget sheet in OGU_01_Production_Operations.xlsx, draft a one-page management note that explains what can still be delivered this year, what must be reset, and how leadership should talk about the change in priorities. Keep the tone candid, steady, and evidence-based.'
      ]),
      tool(T_PPT, M365_LIC, M365_ACCT, [
        'You are the Chief of Staff at Lautan Merdeka Energy Berhad. Create a 6-slide executive deck using OGU_01_Production_Operations.xlsx, OGU_02_HSE_Policy.docx, and OGU_03_Field_Development_Plan.docx as the source context, covering current performance, the root causes behind production under-delivery and cost and HSSE pressure, the top Red risks, the first 90-day actions, and the decisions required from leadership. Give each slide a headline that states the message, not just the topic.',
        'You are the CFO at Lautan Merdeka Energy Berhad. Create a 5-slide update deck for leadership that uses the Lifting Cost Tracker, Capex vs Budget, and HSSE Incident Register sheets in OGU_01_Production_Operations.xlsx to show where financial exposure is concentrated and how quickly it can be reduced. Include speaker notes that explain the Red issues in plain language for a non-technical audience.',
        'You are the Strategy Director at Lautan Merdeka Energy Berhad. Create a single summary slide that links the signals in the Daily Production Log, Reservoir Performance, and HSSE Incident Register sheets in OGU_01_Production_Operations.xlsx to the priorities in OGU_03_Field_Development_Plan.docx. Present it as a RAG matrix with one sentence of management action beside each Red item.'
      ]),
      tool(T_OUTLOOK, M365_LIC, M365_ACCT, [
        'You are the Regulatory Affairs Lead at Lautan Merdeka Energy Berhad. Draft an email to the relevant authorities and senior internal stakeholders that acknowledges the current pressure areas indicated by the HSSE Incident Register sheet in OGU_01_Production_Operations.xlsx, outlines the corrective steps already under way, and requests alignment on the next review checkpoint. Keep the tone factual, controlled, and suitable for scrutiny by PETRONAS and DOSH and SKK Migas counterparts.',
        'You are the COO at Lautan Merdeka Energy Berhad. Draft an internal email to Asset managers and HSSE leaders summarising the top three risks shown in the Daily Production Log, Lifting Cost Tracker, and HSSE Incident Register sheets in OGU_01_Production_Operations.xlsx, the required actions this week, and the consequences of delay. End with a bullet list titled What I need from you by Friday.',
        'You are the Head of Stakeholder Management at Lautan Merdeka Energy Berhad. Draft an external-facing update that explains the current operating situation using plain language consistent with OGU_02_HSE_Policy.docx and OGU_03_Field_Development_Plan.docx, without overpromising outcomes or admitting fault. Use the evidence implied by the Capex vs Budget and Lifting Cost Tracker sheets in OGU_01_Production_Operations.xlsx to keep the message disciplined.'
      ]),
      tool(T_TEAMS, M365_LIC, M365_ACCT, [
        'You are the Chief of Staff at Lautan Merdeka Energy Berhad. Using this recorded Teams meeting recap, identify the decisions, unresolved issues, and action items that connect directly to the Daily Production Log, Lifting Cost Tracker, and HSSE Incident Register sheets in OGU_01_Production_Operations.xlsx. Present the output as a RAG table with columns for Topic, What Was Said, Owner, Due Date, and Escalation Level.',
        'You are the Operations Director at Lautan Merdeka Energy Berhad. Using this Teams recap, draft follow-up actions for the teams responsible for the areas covered in OGU_02_HSE_Policy.docx and the Reservoir Performance sheet in OGU_01_Production_Operations.xlsx. Group the actions by workstream and include a success measure for each one.',
        'You are the CFO at Lautan Merdeka Energy Berhad. Using this Teams recap, extract every financial, compliance, or customer-impact figure that would help explain the trends in the Lifting Cost Tracker, Capex vs Budget, and HSSE Incident Register sheets in OGU_01_Production_Operations.xlsx. Present the result as a structured note with sections for Facts, Risks, Commitments, and Missing Information.'
      ], DESC_TEAMS),
      tool(T_NOTEBOOK, M365_LIC, M365_ACCT, [
        'You are the CEO at Lautan Merdeka Energy Berhad. Upload OGU_01_Production_Operations.xlsx, OGU_02_HSE_Policy.docx, OGU_03_Field_Development_Plan.docx to Copilot Notebook, set the instruction to synthesise across all files with citations, and ask for the 10-slide-equivalent story leadership needs right now. Require Notebook to reconcile the signals from the Daily Production Log, Lifting Cost Tracker, and HSSE Incident Register sheets in OGU_01_Production_Operations.xlsx with the commitments in OGU_02_HSE_Policy.docx and OGU_03_Field_Development_Plan.docx.',
        'You are the COO at Lautan Merdeka Energy Berhad. Upload OGU_01_Production_Operations.xlsx, OGU_02_HSE_Policy.docx, OGU_03_Field_Development_Plan.docx to Copilot Notebook and ask whether the priorities implied by the Reservoir Performance and Capex vs Budget sheets in OGU_01_Production_Operations.xlsx are still realistic given the risk picture in the HSSE Incident Register sheet. Require a RAG table with columns for Priority, Evidence, Risk to Delivery, and Recommendation, all with citations.',
        'You are the Board Liaison at Lautan Merdeka Energy Berhad. Upload OGU_01_Production_Operations.xlsx, OGU_02_HSE_Policy.docx, OGU_03_Field_Development_Plan.docx to Copilot Notebook and ask for the contradictions management must resolve before the next review, especially where operational ambition, control capability, and financial reality do not line up. Request a concise answer with sections for Contradictions, Questions Directors Will Ask, and Pre-Reads to Send.'
      ], DESC_NOTEBOOK),
      tool(T_COWORK, M365_LIC, M365_ACCT, [
        'You are the COO at Lautan Merdeka Energy Berhad. Do all of the following autonomously: create a recovery action plan grounded in the Daily Production Log, Lifting Cost Tracker, and HSSE Incident Register sheets in OGU_01_Production_Operations.xlsx; save it to OneDrive; email it to Asset managers and HSSE leaders; and schedule a 45-minute review meeting for next week. Make the plan easy to track with RAG status and owner-by-owner accountability.',
        'You are the Chief of Staff at Lautan Merdeka Energy Berhad. Do all of the following autonomously: turn the main obligations from OGU_02_HSE_Policy.docx and the priorities from OGU_03_Field_Development_Plan.docx into a working checklist, save it in OneDrive, email the checklist to the accountable leaders, and create calendar reminders for each major milestone. Keep the wording clear enough that teams can act without a second briefing.'
      ], DESC_COWORK),
      tool(T_EDIT_COPILOT, M365_LIC, M365_ACCT, [
        'You are the Company Secretary at Lautan Merdeka Energy Berhad. Using OGU_02_HSE_Policy.docx in Word for the web, add an appendix titled Operating Escalation and RAG Governance Protocol and populate it with decision rights, escalation thresholds, evidence requirements, and sign-off owners that mirror the issues visible in the HSSE Incident Register and Lifting Cost Tracker sheets in OGU_01_Production_Operations.xlsx. Keep the style consistent with the existing document.',
        'You are the Performance Manager at Lautan Merdeka Energy Berhad. Using OGU_01_Production_Operations.xlsx in Excel for the web, create a new worksheet called Leadership Recovery Tracker that combines the Daily Production Log, Lifting Cost Tracker, Capex vs Budget, and HSSE Incident Register sheets into a single view with owner, due date, expected impact, and live RAG status. Reorder the layout so the Red issues appear first and add formulas that refresh the summary automatically.'
      ], DESC_EDIT_COPILOT),
      tool(T_WORD_AGT, M365_LIC, M365_ACCT, [
        'You are the Knowledge Manager at Lautan Merdeka Energy Berhad. Open OGU_02_HSE_Policy.docx in Word for Web and create an agent called Upstream HSE Navigator. Describe it as an assistant that answers questions about the policies, thresholds, and escalation rules that matter when the HSSE Incident Register sheet and the Lifting Cost Tracker sheet in OGU_01_Production_Operations.xlsx start to move against plan, then share it with the core leadership team.',
        'You are the COO at Lautan Merdeka Energy Berhad. Demo the Upstream HSE Navigator agent by asking: One offshore field is below plan, water cut is rising, and a hydrocarbon release remains open in the HSSE register. What immediate escalation is required, which workover or integrity actions should be prioritised, and what evidence should we show PETRONAS and SKK Migas this month? Show how the answer cites the source document and gives a clear next step.'
      ], DESC_WORD_AGT),
      tool(T_PPT_AGT, M365_LIC, M365_ACCT, [
        'You are the Chief of Staff at Lautan Merdeka Energy Berhad. Create the leadership deck in PowerPoint for Web, then create an agent called Asset Review Board Bot that helps executives find the right slide, chart, and message quickly. Make sure it can answer questions grounded in the Daily Production Log, Lifting Cost Tracker, and HSSE Incident Register sheets in OGU_01_Production_Operations.xlsx.',
        'You are the CFO at Lautan Merdeka Energy Berhad. Demo the Asset Review Board Bot agent by asking which Red issue needs leadership attention first, what slide supports that answer, and what decision should be taken this week. Keep the response short enough to use in a live meeting.'
      ], DESC_PPT_AGT),
      tool(T_XL_AGT, M365_LIC, M365_ACCT, [
        'You are the Data Product Owner at Lautan Merdeka Energy Berhad. Open OGU_01_Production_Operations.xlsx in Excel for Web and create an agent called Upstream Operations Q&A. Describe it as an assistant that answers plain-English questions about the Daily Production Log, Reservoir Performance, Lifting Cost Tracker, Capex vs Budget, and HSSE Incident Register sheets and share it with the teams that need faster insight.',
        'You are the COO at Lautan Merdeka Energy Berhad. Demo the Upstream Operations Q&A agent by asking which asset or field is currently Red, what is driving the status, and what leading indicator should be watched next. Then ask for the one figure from the workbook that leadership should remember before the next review.'
      ], DESC_XL_AGT),
      tool(T_BUILDER, M365_LIC, M365_ACCT, [
        'You are the Digital Transformation Lead at Lautan Merdeka Energy Berhad. Go to copilotstudio.microsoft.com, create a new agent called Lautan Field Decision Assistant, use OGU_01_Production_Operations.xlsx, OGU_02_HSE_Policy.docx, OGU_03_Field_Development_Plan.docx as the knowledge sources, and configure topics for Production Recovery, Reservoir Risk, HSSE Escalation, Capex Control. Publish it to Teams with instructions that it should answer in a concise, evidence-based way and surface a clear escalation path when users ask high-risk questions.',
        'You are the Operations Director at Lautan Merdeka Energy Berhad. Demo the Lautan Field Decision Assistant agent by asking: One offshore field is below plan, water cut is rising, and a hydrocarbon release remains open in the HSSE register. What immediate escalation is required, which workover or integrity actions should be prioritised, and what evidence should we show PETRONAS and SKK Migas this month? Show how the agent responds with the relevant file, the recommended action, and the owner who should take the next step.'
      ], DESC_BUILDER),
    ],
    companyID='PT Lautan Merdeka Energi Tbk',
    taglineID='SKK Migas menyorot biaya angkat USD19.8/bbl saat insiden HSSE meningkat.'),

]

print(f"Batch 3 written: {len(INDUSTRIES_3)} entries")
