
import sys; sys.path.insert(0,'.')
from util import *

INDUSTRIES_5 = [

# ── PLANTATION ─────────────────────────────────────────────────────────────
ind('plantation','plantation','Plantation & Agribusiness','🌿','#388E3C','#43A047',
    'Zava Agribusiness (Perkebunan Lestari)',
    'RSPO suspended 2 mills — EUDR deadline Jan 2026 with 184,200 ha at risk.',
    'Zava Agribusiness operates 184,200 hectares of oil palm in Kalimantan and Sabah. Two mills have had RSPO certification suspended following a third-party audit. The EU Deforestation Regulation (EUDR) deadline is January 2026 — all palm oil exported to the EU must be deforestation-free with full geolocation traceability. OER has declined to 19.4% vs the 21.2% industry benchmark.',
    ['11_Zava_Agribusiness_Plantations.xlsx','22_Zava_Plantation_RSPO_Audit.docx','20_Zava_ESG_Sustainability_Framework.docx','Email_03_Cilegon_EHS_Enforcement.docx'],
    [
      tool(T_CHAT, FREE_LIC, FREE_ACCT, [
        'I am the Sustainability Director of a Malaysian-Indonesian palm oil plantation group. Two of our mills have had RSPO certification suspended and the EU Deforestation Regulation takes effect in January 2026, putting our EU-bound export volumes at risk. Draft a 300-word crisis communications brief for our investors. The brief should: acknowledge the RSPO suspension transparently, explain the remediation steps underway, describe our EUDR compliance programme, and reaffirm our commitment to sustainable palm oil. Tone: honest, accountable, and forward-looking.',
        'Explain the EU Deforestation Regulation (EUDR) requirements for palm oil exporters — specifically what traceability documentation is required, what the "no deforestation after December 31, 2020" cutoff date means in practice, and what the penalties are for non-compliance. Focus on the implications for a plantation with operations in Kalimantan.',
        'What is the RSPO remediation and complaints process? If two mills have had certification suspended, what specific steps must the company take to reinstate certification? What is the typical timeline and what evidence does RSPO require to lift a suspension?'
      ]),
      tool(T_RESEARCHER, M365_LIC, M365_ACCT, [
        'Research the latest EUDR implementation updates — specifically for Indonesian and Malaysian palm oil exporters. I need: (1) The current implementation timeline (is the January 2026 deadline confirmed?), (2) Which EU member states are most actively enforcing, (3) The specific geolocation and due diligence documentation required, (4) Any industry body guidance from MPOB, RSPO, or MSPO on EUDR compliance. Provide citations.',
        'Research oil extraction rate (OER) improvement strategies for tropical oil palm in Southeast Asia. What are the key factors that drive the gap between 19.4% (our current OER) and the 21.2% industry benchmark? What mill process improvements and estate best practices have shown the highest OER improvement impact? Cite recent research or industry case studies.'
      ], DESC_RESEARCHER),
      tool(T_ANALYST, M365_LIC, M365_ACCT, [
        'Upload 11_Zava_Agribusiness_Plantations.xlsx to Analyst. Ask: Analyse OER trends by mill over the past 8 quarters. Which mills have the lowest OER and what is the variance from the 21.2% industry benchmark? Calculate the revenue impact of the OER gap — if all mills operated at the industry benchmark OER, how much additional CPO would we have produced at current FFB tonnage and what is the MYR revenue impact at MYR 3,800/tonne? Show as a ranked table and a bar chart.',
        'Upload 11_Zava_Agribusiness_Plantations.xlsx and 22_Zava_Plantation_RSPO_Audit.docx. Ask: Cross-reference the EUDR compliance status of each estate block against the December 31, 2020 deforestation cutoff. Which estate blocks show land conversion activity after this date? Calculate the total hectarage at risk and the corresponding export volume that cannot be sold to EU buyers until remediation is complete. Present as a heat map.'
      ], DESC_ANALYST),
      tool(T_EXCEL, M365_LIC, M365_ACCT, [
        'Open 11_Zava_Agribusiness_Plantations.xlsx. Navigate to the Mill Performance sheet. Ask Copilot: Create an EUDR traceability compliance tracker on a new sheet. For each estate block, show: (1) Block ID and hectarage, (2) Geolocation coordinates (latitude/longitude), (3) Land conversion history pre/post December 2020, (4) RSPO certification status, (5) EUDR compliance status (Compliant/At Risk/Non-Compliant). Colour code: green = Compliant, red = Non-Compliant.',
        'Ask Copilot: In the Financial Performance sheet, model the revenue impact of losing EU market access for 12 months. Assume: 35% of CPO exports go to the EU, average EU premium of MYR 180/tonne over non-EU markets, total CPO production of 280,000 tonnes per year. Calculate: (1) Annual EU premium revenue at risk, (2) Revenue loss if EU volumes are diverted to non-EU markets at lower prices, (3) The cost to implement full EUDR compliance (estimate MYR 12M for satellite monitoring and traceability system). Show as a cost-benefit table.',
        'Ask Copilot: Create an OER improvement action plan on a new sheet. For the 5 mills with the lowest OER, identify the 3 most impactful improvement actions for each (based on the audit findings in the strategy data). Calculate the projected OER improvement if all actions are implemented and the resulting additional CPO revenue per mill.'
      ]),
      tool(T_WORD, M365_LIC, M365_ACCT, [
        'Open 22_Zava_Plantation_RSPO_Audit.docx. Ask Copilot: Draft a 3-page RSPO remediation plan for the two suspended mills. Structure: (1) Summary of audit findings that led to the suspension, (2) Corrective actions for each finding — with responsible person, action description, and completion date, (3) Evidence to be provided to RSPO verifier — list by finding, (4) Stakeholder grievance resolution plan — addressing any community or worker complaints raised in the audit, (5) Timeline to reinstatement — target 4 months. Use formal RSPO reporting language.',
        'Ask Copilot: Draft an EUDR due diligence statement template for use with our EU customers. The statement should: assert that the palm oil in the specified shipment was produced on land not deforested after December 31, 2020, reference the geolocation data supporting this assertion, confirm RSPO or MSPO certification (where applicable), and provide the name and contact of the responsible officer. Format to meet EU regulatory requirements.',
        'Ask Copilot: Draft a letter to our top 3 EU customers (who together represent 28% of our CPO sales) explaining our EUDR compliance programme. The letter should: confirm our commitment to full EUDR compliance by January 2026, describe our traceability system implementation, acknowledge the RSPO suspension and the remediation timeline, and assure them that their supply volumes will not be affected. Keep it professional and confidence-building.'
      ]),
      tool(T_PPT, M365_LIC, M365_ACCT, [
        'Ask Copilot in PowerPoint: Create a 12-slide sustainability investor briefing presentation. Include: (1) Portfolio overview — 184,200 ha, (2) RSPO suspension — cause, remediation, timeline, (3) EUDR compliance programme — progress dashboard, (4) Traceability system implementation, (5) OER improvement roadmap, (6) ESG rating trajectory, (7) Community and social commitments, (8) Financial impact of EUDR compliance investment, (9) Competitive positioning — sustainability as a market differentiator, (10) Key milestones FY2026, (11) Risks and mitigants, (12) Our Net Zero pathway. Use green and earthy tones.',
        'Ask Copilot: Create a 2-slide RSPO suspension update for the Board. Slide 1: What happened — the audit findings and suspension notice. Slide 2: What we are doing — remediation plan, timeline, and expected reinstatement date. Keep it factual, accountable, and concise.',
        'Ask Copilot: Add a geolocation compliance map slide showing our estate blocks colour-coded by EUDR compliance status (green/amber/red). Include statistics: total compliant hectarage, at-risk hectarage, and non-compliant hectarage.'
      ]),
      tool(T_OUTLOOK, M365_LIC, M365_ACCT, [
        'Ask Copilot in Outlook: Draft a formal response to the RSPO complaints panel regarding the two suspended mills. The letter should: acknowledge the suspension, provide a timeline for remediation, note the corrective actions already completed, and request a re-audit within 4 months. Use formal RSPO correspondence language.',
        'Ask Copilot: Draft an email to the EU customer relations team providing an EUDR compliance update. The email should confirm our traceability system is on track for full deployment by October 2025, attach our current compliance certificate for unaffected estate blocks, and outline the due diligence documentation we will provide with each shipment from November 2025.',
        'Ask Copilot: Summarise the email thread in Email_03_Cilegon_EHS_Enforcement.docx and identify any findings from the enforcement action that also affect our plantation operations. List each relevant finding with the corrective action required and the deadline.'
      ]),
      tool(T_TEAMS, M365_LIC, M365_ACCT, [
        'Open an existing recorded Teams meeting recap from a sustainability or RSPO compliance meeting. Ask Copilot: Identify all RSPO remediation commitments made, the responsible mill manager for each, and the evidence submission deadline. Format as a formal RSPO remediation action register.',
        'Ask Copilot: Draft a follow-up communication to all mill managers and estate supervisors covering the EUDR traceability requirements. Include a simple checklist of what data each manager must collect and submit monthly to the central traceability system.',
        'Ask Copilot: Were any community or worker grievances mentioned in this meeting? List each with the nature of the grievance, the mill or estate it relates to, and whether it has been formally logged in the RSPO grievance mechanism.'
      ], DESC_TEAMS),
      tool(T_NOTEBOOK, M365_LIC, M365_ACCT, [
        'Upload 11_Zava_Agribusiness_Plantations.xlsx, 22_Zava_Plantation_RSPO_Audit.docx, and 20_Zava_ESG_Sustainability_Framework.docx to Copilot Notebook. Set instruction: "You are an ESG advisor helping the Sustainability Director navigate RSPO and EUDR simultaneously." Ask: Given that we must reinstate RSPO certification for 2 mills AND achieve EUDR compliance by January 2026, what is the optimal sequencing of activities over the next 6 months? Where do the requirements overlap and where do they conflict?',
        'Upload 11_Zava_Agribusiness_Plantations.xlsx and 20_Zava_ESG_Sustainability_Framework.docx. Ask: Our sustainability framework commits to zero deforestation across all new development. The EUDR requires proof of no deforestation after December 2020. Based on the estate data, are there any estates where our current commitments may not meet the EUDR standard? Identify any gaps and recommend how to address them.'
      ], DESC_NOTEBOOK),
      tool(T_COWORK, FRONTIER_LIC, M365_ACCT, [
        'Do all of the following for RSPO reinstatement: (1) Research the RSPO remediation process and the typical evidence required to lift a mill certification suspension. (2) Draft a month-by-month remediation plan for both suspended mills covering the next 4 months. (3) Save to OneDrive as "RSPO Reinstatement Plan - [Date]". (4) Email to the VP Sustainability and both Mill Managers asking for review and commitment by Friday. (5) Schedule a bi-weekly RSPO Remediation Check-In via Teams every other Monday starting next week.',
        'Do all of the following for EUDR compliance: (1) Research satellite-based deforestation monitoring solutions suitable for palm oil operations — identify 3 vendors operating in Indonesia/Malaysia with EUDR-compliant outputs. (2) Draft an RFP (Request for Proposal) for a traceability system covering satellite monitoring + supply chain geolocation. (3) Save the RFP to OneDrive. (4) Email the RFP to the 3 vendors and to our Head of IT and Head of Sustainability asking for proposals within 3 weeks. (5) Schedule a Vendor Evaluation Workshop for 4 weeks from today.'
      ], DESC_COWORK),
      tool(T_WORD_AGT, M365_LIC, M365_ACCT, [
        'Open 22_Zava_Plantation_RSPO_Audit.docx in Word for Web. Create an agent called "RSPO Compliance Agent". Description: "Answers questions from mill managers and sustainability officers about RSPO certification requirements, audit findings, remediation procedures, and grievance handling — grounded in our official RSPO audit documents." Share with all mill and estate managers.',
        'Demo: A mill manager asks "The RSPO auditor flagged that we do not have documented evidence of our riparian buffer zone maintenance for the past 12 months. What evidence do I need to provide, in what format, and by when to close this non-conformance?" Show how the agent gives a precise, audit-grounded remediation guide.'
      ], DESC_WORD_AGT),
      tool(T_PPT_AGT, M365_LIC, M365_ACCT, [
        'Create a PowerPoint from the sustainability investor briefing. Create an agent called "Sustainability Briefing Bot". Share with ESG-focused investors and rating agencies such as MSCI and Sustainalytics.',
        'Demo: An ESG analyst asks "What percentage of your total hectarage is currently EUDR-compliant with full geolocation data submitted, and what is your projected compliance rate by October 2025?" Show how the agent provides a precise, data-grounded answer for ESG due diligence.'
      ], DESC_PPT_AGT),
      tool(T_XL_AGT, M365_LIC, M365_ACCT, [
        'Open 11_Zava_Agribusiness_Plantations.xlsx in Excel for Web. Create an agent called "Plantation Operations & ESG Q&A". Description: "Instant answers on OER by mill, RSPO certification status, EUDR compliance by estate block, and CPO production for the sustainability and operations teams." Share with senior management and external ESG auditors.',
        'Demo: Ask "What is the total hectarage currently non-compliant with EUDR and what CPO volume does that represent?" Then: "Which mill has the lowest OER this quarter and by how much does it fall short of the industry benchmark?" Show how the sustainability team gets instant data-grounded answers.'
      ], DESC_XL_AGT),
      tool(T_BUILDER, M365_LIC, M365_ACCT, [
        'Go to copilotstudio.microsoft.com > Create > New Agent. Name it "Perkebunan Lestari Compliance & Ops Agent". Description: "Supports Zava Agribusiness mill managers and sustainability teams with answers on RSPO certification, EUDR traceability requirements, OER improvement, and ESG reporting — ensuring consistent, document-grounded guidance across all 184,200 hectares of operations." Upload 11_Zava_Agribusiness_Plantations.xlsx, 22_Zava_Plantation_RSPO_Audit.docx, and 20_Zava_ESG_Sustainability_Framework.docx. Add topics: "RSPO Compliance", "EUDR Traceability", "OER Improvement", "ESG Reporting". Publish to Teams for all mill and estate managers.',
        'Demo the agent: An estate manager in Kalimantan asks: "A community representative has just filed a land rights grievance claiming that 120 hectares of our Block K-14 was traditionally used for community farming and was converted without free, prior and informed consent (FPIC). What is our RSPO FPIC obligation in this situation, what is the grievance response process, and do I need to immediately suspend operations in that block?" Show how the agent provides a comprehensive, policy-grounded response.'
      ], DESC_BUILDER),
    ]),

# ── BPO SERVICES ───────────────────────────────────────────────────────────
ind('bpo-services','technology','BPO Services','🖥','#01579B','#0277BD',
    'Zava BPO (Bengaluru Centre)',
    'Attrition 31.2% — Bank Mandiri renewal MYR 84M at risk. DOCUAI at 99.8% accuracy.',
    'Zava BPO\'s Bengaluru Centre houses 3,200 FTE across banking, insurance, and healthcare process outsourcing. Staff attrition has surged to 31.2% (industry benchmark: 22%). The Bank Mandiri BPO contract worth MYR 84M is up for renewal — client satisfaction score is 6.8/10, below the 7.5 renewal threshold. DOCUAI (document processing AI) is performing at 99.8% accuracy.',
    ['15_Zava_BPO_Operations.xlsx','18_Zava_HR_Analytics.xlsx','Email_13_Bengaluru_Attrition_Crisis.docx','Email_12_BPO_Contract_Pipeline.docx'],
    [
      tool(T_CHAT, FREE_LIC, FREE_ACCT, [
        'I am the MD of a BPO centre in Bengaluru with 3,200 FTE. Attrition has hit 31.2% against an industry benchmark of 22%, and my largest client — Bank Mandiri — has given us a satisfaction score of 6.8/10 against a 7.5 renewal threshold. The MYR 84M contract is up for renewal in 4 months. Draft a 300-word account recovery brief covering: the 3 most likely drivers of the low satisfaction score, the immediate actions I should take to demonstrate commitment to Mandiri before the renewal meeting, and the retention risk if we lose this contract.',
        'What are the most effective strategies to reduce BPO attrition in the Indian IT-BPO sector? Focus on approaches that have been proven to work for 3,000+ FTE operations. Rank the top 5 strategies by speed of impact — I need results within 90 days not 12 months.',
        'Explain how AI-powered document processing (such as OCR + NLP) is changing BPO service delivery. What is a realistic accuracy target for a well-trained model on structured financial documents? How should a BPO operator position AI as a productivity enhancer rather than a threat to its workforce in client conversations?'
      ]),
      tool(T_RESEARCHER, M365_LIC, M365_ACCT, [
        'Research BPO industry attrition benchmarks in Bengaluru specifically for banking and insurance process outsourcing. I need: (1) Average and top-quartile attrition rates for 2024 and 2025, (2) The top 5 reasons BPO employees cite for leaving, (3) The most effective retention bonuses and non-monetary benefits used by leading BPO operators in India. Provide citations.',
        'Research the competitive landscape for banking BPO services in Southeast Asia — specifically for Indonesian bank clients. Who are the top BPO providers competing for Bank Mandiri-scale contracts? What differentiators are most valued by Indonesian banking clients — cost, accuracy, turnaround time, or regulatory compliance expertise? Cite industry sources.'
      ], DESC_RESEARCHER),
      tool(T_ANALYST, M365_LIC, M365_ACCT, [
        'Upload 18_Zava_HR_Analytics.xlsx to Analyst. Ask: Analyse attrition data for Zava BPO Bengaluru by department, tenure band, and job level. Which department has the highest attrition? Are employees leaving most within the first 6 months (early attrition) or after 12–24 months (mid-tenure)? Calculate the fully-loaded replacement cost per FTE (assume USD 2,800 per hire including training) and the total annual attrition cost. Show as a heat map and cost waterfall.',
        'Upload 15_Zava_BPO_Operations.xlsx to Analyst. Ask: Analyse the Bank Mandiri contract SLA performance over the last 12 months. Which SLA metrics — turnaround time, accuracy, escalation rate, CSAT — are below the contract threshold? Calculate the weighted satisfaction score and identify the 3 metrics most correlated with the low CSAT score of 6.8. Show as a correlation matrix and a trend chart.'
      ], DESC_ANALYST),
      tool(T_EXCEL, M365_LIC, M365_ACCT, [
        'Open 15_Zava_BPO_Operations.xlsx. Navigate to the SLA Performance sheet. Ask Copilot: Build a Bank Mandiri account recovery dashboard on a new sheet. For each of the 8 SLA metrics in the contract, show: (1) Contract threshold, (2) Last 3 months actual performance, (3) Status vs threshold (RAG), (4) Trend (Improving/Stable/Declining). Highlight in red any metric that is below threshold AND declining.',
        'Ask Copilot: Create an attrition cost model on a new sheet. Calculate: (1) Total FTE lost to attrition last 12 months (31.2% of 3,200), (2) Replacement cost per FTE at USD 2,800, (3) Total attrition cost, (4) Productivity loss during new hire ramp-up (assume 60% productivity for first 3 months), (5) Total cost including productivity loss. Compare against the cost of a MYR 2M retention programme. Show the ROI of the retention programme.',
        'Ask Copilot: In the Contract Pipeline sheet, calculate the total contract renewal value at risk in the next 12 months. For each contract marked "At Risk", show the contract value, the renewal probability (based on current CSAT), and the expected value. Rank by expected value at risk and flag any contract where the CSAT score is below the renewal threshold.'
      ]),
      tool(T_WORD, M365_LIC, M365_ACCT, [
        'Open Email_13_Bengaluru_Attrition_Crisis.docx. Ask Copilot: Draft a comprehensive attrition reduction action plan of 2 pages. Cover: (1) Root cause analysis — 3 key drivers based on exit interview data, (2) Five retention initiatives — retention bonus structure, career pathing programme, flexible work policy, wellness benefits, and manager excellence training, (3) KPIs: target attrition rate of 24% within 6 months, (4) Investment required: MYR 2M, projected ROI through reduced replacement cost and improved client CSAT, (5) Governance: who owns each initiative. Use a business case format.',
        'Open Email_12_BPO_Contract_Pipeline.docx. Ask Copilot: Draft a Bank Mandiri account recovery plan in the format of a client executive briefing. Cover: (1) Current SLA performance — transparent acknowledgement of the 3 metrics below threshold, (2) Root cause — the attrition impact on experienced staff levels, (3) Recovery plan — 6 specific commitments with measurable targets, (4) DOCUAI deployment — how AI will improve accuracy and turnaround for Mandiri processes, (5) Our investment commitment — dedicated Mandiri team ring-fenced from attrition impact. Keep it confident and specific.',
        'Ask Copilot: Write a DOCUAI capability one-pager for the Bank Mandiri renewal meeting. The document should explain in client-friendly language: what DOCUAI does (OCR + NLP for financial document processing), the 99.8% accuracy achievement vs the 98.5% industry benchmark, the turnaround time improvement (from 4 hours to 45 minutes for standard forms), and the integration with Mandiri\'s existing document management system.'
      ]),
      tool(T_PPT, M365_LIC, M365_ACCT, [
        'Ask Copilot in PowerPoint: Create a 12-slide Bank Mandiri contract renewal presentation. Include: (1) Partnership overview — 5 years, 850 FTE dedicated, (2) Service delivery scorecard — 12-month trend, (3) Transparent acknowledgement of 3 below-threshold metrics, (4) Root cause — attrition impact and what we have done, (5) Recovery plan — 6 commitments with targets, (6) DOCUAI — live demo results for Mandiri process types, (7) New value-add proposition — 3 additional services we can offer, (8) Dedicated Mandiri team structure — ring-fenced, (9) Proposed renewal terms, (10) Investment in Mandiri\'s success — our commitments, (11) Testimonials from other banking BPO clients, (12) Recommended next steps. Use navy blue and white.',
        'Ask Copilot: Create a 2-slide attrition update for the Zava Group Board. Slide 1: The Bengaluru attrition crisis — root causes and financial impact. Slide 2: The retention action plan — 5 initiatives, MYR 2M investment, and projected CSAT recovery impact.',
        'Ask Copilot: Add a DOCUAI impact slide showing a before/after process flow diagram — how Bank Mandiri\'s loan documentation process worked before DOCUAI (4 hours, 3 manual steps, 2.1% error rate) vs after DOCUAI (45 minutes, 1 review step, 0.2% error rate).'
      ]),
      tool(T_OUTLOOK, M365_LIC, M365_ACCT, [
        'Open Email_12_BPO_Contract_Pipeline.docx. Ask Copilot in Outlook: Draft a proactive email to Bank Mandiri\'s procurement lead requesting a contract renewal review meeting. The email should: acknowledge that we are aware the CSAT score fell below threshold in Q3, take accountability and briefly describe what we have done to address it, and request a 90-minute business review meeting 6 weeks before the contract expiry. Tone: confident and relationship-focused, not defensive.',
        'Ask Copilot: Draft an internal email to the Bengaluru Centre leadership team briefing them on the Bank Mandiri renewal risk and the recovery plan. Be direct about the stakes: losing this contract will result in 850 role reductions. Ask each department head to submit their specific commitments for the account recovery plan within 3 days.',
        'Open Email_13_Bengaluru_Attrition_Crisis.docx. Ask Copilot: Summarise the key facts and decisions from this email thread. What commitments were made by the Bengaluru HR Director to the Group CEO? List each commitment with the deadline. Draft a status update email from the HR Director to the CEO confirming progress on each commitment.'
      ]),
      tool(T_TEAMS, M365_LIC, M365_ACCT, [
        'Open an existing recorded Teams meeting recap from an account review or operations meeting. Ask Copilot: Identify all client commitments discussed — specific SLA improvements, process changes, or escalation resolutions. List each with owner and deadline. Flag any commitment made to Bank Mandiri that has a deadline within the next 30 days.',
        'Ask Copilot: Draft follow-up actions for the attrition reduction taskforce based on this meeting. Group by initiative: Retention Bonus | Career Pathing | Manager Training | Wellness | Flexible Work. Include the HR business partner responsible and the target completion date.',
        'Ask Copilot: Based on this meeting, what is the overall tone regarding the Bank Mandiri renewal — confident, uncertain, or at risk? Identify the 3 most important statements made about the renewal and what they imply about the likelihood of securing it.'
      ], DESC_TEAMS),
      tool(T_NOTEBOOK, M365_LIC, M365_ACCT, [
        'Upload 15_Zava_BPO_Operations.xlsx, 18_Zava_HR_Analytics.xlsx, and Email_12_BPO_Contract_Pipeline.docx to Copilot Notebook. Set instruction: "You are a BPO turnaround specialist. The MD needs to retain the Bank Mandiri contract and reduce attrition simultaneously." Ask: Based on all three documents, what is the single most important action the MD should take in the next 2 weeks that will have the greatest positive impact on BOTH the Bank Mandiri renewal AND the attrition crisis?',
        'Upload 15_Zava_BPO_Operations.xlsx and Email_13_Bengaluru_Attrition_Crisis.docx. Ask: The attrition data and the contract pipeline show a direct link — high attrition is leading to experienced staff losses which is driving down CSAT. Quantify this connection: for each 1 percentage point increase in attrition, estimate the impact on the Bank Mandiri CSAT score based on the data patterns. At what attrition rate does CSAT drop below the 7.5 renewal threshold?'
      ], DESC_NOTEBOOK),
      tool(T_COWORK, FRONTIER_LIC, M365_ACCT, [
        'Do all of the following: (1) Research Bank Mandiri\'s latest annual report and public statements about their BPO and digital transformation strategy to understand what they value most in a BPO partner. (2) Draft a 2-page Bank Mandiri-specific value proposition document showing how Zava BPO aligns with their strategic priorities. (3) Save to OneDrive as "Bank Mandiri Renewal Value Prop". (4) Email to the Account Director and MD asking for review before the renewal meeting. (5) Schedule a 2-hour "Mandiri Renewal Prep" session for next week with the Account Director, Head of Operations, and DOCUAI Product Lead.',
        'Do all of the following for attrition: (1) Analyse the exit interview data from the past 6 months (from the HR Analytics data) and identify the top 3 reasons for resignation. (2) Draft 3 targeted retention initiatives — one addressing each root cause. (3) Create a retention programme proposal document in Word. (4) Email to the Group HR Director and Bengaluru Centre HR Head for approval. (5) Schedule a town hall meeting for all Bengaluru staff next Friday to announce the retention programme.'
      ], DESC_COWORK),
      tool(T_WORD_AGT, M365_LIC, M365_ACCT, [
        'Open Email_12_BPO_Contract_Pipeline.docx in Word for Web. Create an agent called "BPO Contract Intelligence Bot". Description: "Answers questions about Zava BPO\'s contract pipeline, SLA performance, account renewal status, and recovery plans — for the MD and account management team." Share with the account management and commercial teams.',
        'Demo: An account manager asks "What is the current CSAT score for Bank Mandiri and what specific SLA metrics are below the renewal threshold? What commitments have we made in the account recovery plan?" Show how the team gets instant, document-grounded account intelligence.'
      ], DESC_WORD_AGT),
      tool(T_PPT_AGT, M365_LIC, M365_ACCT, [
        'Create a PowerPoint from the Bank Mandiri renewal presentation. Create an agent called "Mandiri Renewal Deck Bot". Share with the Bank Mandiri procurement team as a pre-meeting resource and with internal leadership.',
        'Demo: A Mandiri procurement officer asks "What specific accuracy improvement has Zava BPO achieved on our loan documentation process since DOCUAI was deployed, and what is the new turnaround time SLA you are proposing for Year 2?" Show how the agent handles client due diligence questions with specific, documented answers.'
      ], DESC_PPT_AGT),
      tool(T_XL_AGT, M365_LIC, M365_ACCT, [
        'Open 15_Zava_BPO_Operations.xlsx in Excel for Web. Create an agent called "BPO Operations Analytics Q&A". Description: "Instant answers on SLA performance by client, attrition by department, contract renewal status, and DOCUAI accuracy — for the MD and operations leadership." Share with operations and commercial leadership.',
        'Demo: Ask "What is the current turnaround time SLA performance for Bank Mandiri\'s loan document processing and how does it compare to the contract threshold?" Then: "Which department in the Bengaluru Centre has the highest attrition rate this quarter?" Show how management gets rapid operational intelligence.'
      ], DESC_XL_AGT),
      tool(T_BUILDER, M365_LIC, M365_ACCT, [
        'Go to copilotstudio.microsoft.com > Create > New Agent. Name it "Zava BPO Client Success Bot". Description: "Supports Zava BPO\'s account management and operations teams with instant answers on SLA commitments, contract terms, DOCUAI capabilities, attrition impact on service delivery, and account recovery plans — helping retain key clients and win renewals." Upload 15_Zava_BPO_Operations.xlsx, 18_Zava_HR_Analytics.xlsx, and Email_12_BPO_Contract_Pipeline.docx. Add topics: "SLA Performance", "Contract Renewal", "DOCUAI Capabilities", "Attrition Impact". Publish to Teams for the account management and operations leadership.',
        'Demo the agent: During the Bank Mandiri renewal negotiation, the client asks: "If your attrition is at 31%, how can you guarantee that the 850-person team we have been working with will remain intact for Year 2 of the contract? What contractual commitment can you give us on staff retention for our account?" Show how the account director uses the agent to pull the specific retention commitment and ring-fencing proposal from the recovery plan in real-time during the negotiation.'
      ], DESC_BUILDER),
    ]),

# ── TELCO ──────────────────────────────────────────────────────────────────
ind('telco','media-telco','Telecommunications','📡','#4A148C','#6A1B9A',
    'ClearWave Communications Berhad',
    '5G at 12.4% vs 20% target — MCMC penalty risk + Nexus Home FMC bundle launch.',
    'ClearWave Communications Berhad is Malaysia\'s third-largest telco with 14.8 million subscribers. 5G coverage has reached only 12.4% of the population against MCMC\'s 20% year-end target. An MCMC penalty notice has been issued. The Nexus Home fixed-mobile convergence (FMC) bundle is launching in Q2 FY2026. Postpaid ARPU has declined 8.4% year-on-year.',
    ['TC_01_ClearWave_Communications.xlsx','TC_02_ClearWave_Strategy.docx'],
    [
      tool(T_CHAT, FREE_LIC, FREE_ACCT, [
        'I am the CTO of a Malaysian telecommunications company. Our 5G rollout is at 12.4% population coverage against MCMC\'s 20% year-end target and we have received a penalty notice. Draft a 300-word 5G acceleration plan brief for my CEO and MCMC that covers: the 3 main obstacles to our rollout (site acquisition, backhaul capacity, power supply to rural sites), the acceleration actions we have taken since the penalty notice, and the revised coverage milestone commitments we can credibly commit to for Q3 and Q4. Tone: transparent, committed, and technically credible.',
        'Explain what a fixed-mobile convergence (FMC) bundle is and why it is strategically important for a telco in 2025–2026. What are the key customer value propositions, the typical bundling models (ARPU lift, churn reduction, net promoter score impact), and the technical infrastructure requirements? Keep the answer under 200 words.',
        'What are the most effective strategies for reversing postpaid ARPU decline in a competitive telco market? Focus on Malaysia specifically — what are the pricing and bundling approaches that have worked for Maxis and Celcom? What role does 5G play in ARPU recovery?'
      ]),
      tool(T_RESEARCHER, M365_LIC, M365_ACCT, [
        'Research MCMC\'s 5G rollout requirements and enforcement framework for Malaysian telecommunications operators. I need: (1) The specific coverage and population penetration milestones MCMC requires, (2) The penalty structure for missing milestones, (3) Any recent MCMC statements about enforcement flexibility or remediation pathways for operators missing targets. Provide citations.',
        'Research global FMC bundle performance data — specifically how bundles of fixed broadband + mobile postpaid + OTT content have affected ARPU, churn rate, and NPS for telcos in comparable markets (Singapore, Australia, UK). What are the 3 most important success factors for a successful FMC launch? Cite industry reports.'
      ], DESC_RESEARCHER),
      tool(T_ANALYST, M365_LIC, M365_ACCT, [
        'Upload TC_01_ClearWave_Communications.xlsx to Analyst. Ask: Analyse 5G rollout progress by region and state. Which states have the largest gap between actual and target coverage? What is the correlation between 5G coverage and postpaid subscriber growth in those states? Create a map-style table showing: State | 5G Coverage % | Target % | Gap | Postpaid Growth Rate. Highlight in red any state where coverage gap exceeds 10 percentage points.',
        'Upload TC_01_ClearWave_Communications.xlsx. Ask: Analyse ARPU trends for postpaid, prepaid, and home broadband segments over the last 8 quarters. Which segment is declining fastest? Calculate the total ARPU decline impact on annual revenue. Build a churn rate cohort analysis — for the Nexus Home FMC bundle pilot (500 subscribers), what is the 3-month churn rate compared to non-bundle postpaid subscribers? Show as trend charts.'
      ], DESC_ANALYST),
      tool(T_EXCEL, M365_LIC, M365_ACCT, [
        'Open TC_01_ClearWave_Communications.xlsx. Navigate to the 5G Rollout Tracker sheet. Ask Copilot: Build a 5G acceleration model showing the monthly site activation required to reach 20% population coverage by December 31, 2026. Current pace is 80 sites/month. Calculate: (1) Sites needed to close the gap, (2) Monthly activation rate required to reach target by December, (3) Additional capex required vs current budget at MYR 1.8M per site. Flag if the required activation rate exceeds our current deployment team capacity.',
        'Ask Copilot: Create a Nexus Home FMC bundle revenue model on a new sheet. Assume: (1) Target of 180,000 bundle subscribers in Year 1, (2) Bundle ARPU of MYR 158/month vs current postpaid ARPU of MYR 82 and fixed broadband ARPU of MYR 110 separately, (3) Churn rate improvement from 2.1% to 1.4% for bundle subscribers. Calculate: Year 1 incremental revenue, Year 1 churn avoidance revenue, and 3-year NPV of the bundle at 10% discount rate.',
        'Ask Copilot: In the Network Quality sheet, calculate the average 5G download speed (Mbps) and latency (ms) per region. How do our 5G KPIs compare to our stated commitments to MCMC (100 Mbps download, <20ms latency)? Flag any region where we are below commitment and calculate the impact on the MCMC penalty calculation.'
      ]),
      tool(T_WORD, M365_LIC, M365_ACCT, [
        'Open TC_02_ClearWave_Strategy.docx. Ask Copilot: Draft a formal response to the MCMC penalty notice. The response should: acknowledge the coverage shortfall factually, explain the root causes (site acquisition delays, backhaul supply constraints), present a credible revised milestone commitment for 16% coverage by Q3 and 20% by Q4, note the acceleration investments already committed (MYR 280M additional capex), and request a bilateral meeting to discuss the penalty mitigation framework. Use formal regulatory correspondence tone.',
        'Ask Copilot: Draft the Nexus Home FMC bundle launch go-to-market brief of 2 pages. Cover: (1) Bundle proposition — what is included (postpaid line, home fibre, and 3 OTT subscriptions), (2) Target customer segment — multi-person households currently on separate contracts, (3) Pricing — MYR 158/month vs MYR 192 for equivalent standalone products, (4) Sales channel strategy — direct digital, retail, and retention saves, (5) Key success metrics — 180,000 subscribers Year 1, churn reduction to 1.4%.',
        'Ask Copilot: Summarise the competitive intelligence section of this strategy document. Who are our top 3 competitors, what are their 5G coverage levels and ARPU positions, and where are we competitively advantaged or disadvantaged? Create a simple competitive matrix.'
      ]),
      tool(T_PPT, M365_LIC, M365_ACCT, [
        'Ask Copilot in PowerPoint: Create a 12-slide Board presentation titled "5G Recovery & FMC Growth Strategy". Include: (1) Current situation — 5G at 12.4%, MCMC penalty, ARPU decline, (2) Root cause analysis — 5G rollout blockers, (3) 5G acceleration plan — monthly milestones and capex, (4) MCMC engagement strategy, (5) FMC bundle — product overview and pricing, (6) FMC revenue model — 3-year projection, (7) Subscriber growth outlook — 5G and FMC impact, (8) Competitive positioning, (9) Network quality dashboard, (10) Financial outlook — ARPU recovery, (11) Risk register, (12) Board decisions required. Purple and white colour scheme.',
        'Ask Copilot: Create a one-slide Nexus Home FMC customer value proposition visual. Show the bundle components as overlapping circles (Venn diagram style): Mobile | Home Broadband | OTT Content. In the overlap area, show the bundle benefits: MYR 34 monthly saving, one bill, shared data pool, priority 5G access.',
        'Ask Copilot: Add a 5G coverage heat map slide showing coverage by state against MCMC target. Use green (at target), amber (within 5%), red (below by more than 5%). Add a timeline showing the monthly activation plan to reach 20% by December.'
      ]),
      tool(T_OUTLOOK, M365_LIC, M365_ACCT, [
        'Ask Copilot in Outlook: Draft a formal response letter to the MCMC penalty notice. Reference the notice number, acknowledge the coverage shortfall, present our revised milestone commitments (16% by Q3, 20% by Q4), outline the MYR 280M acceleration investment, and request a bilateral meeting. Attach the 5G acceleration plan as an annex (note: attach separately). Use the formal regulatory correspondence format.',
        'Ask Copilot: Draft an internal brief email to the 5G Rollout Taskforce with 3 action items: (1) prioritise site acquisition in the 5 most under-covered states, (2) escalate backhaul supply chain constraints to the CEO for resolution, (3) submit revised rollout milestone report to MCMC by Friday. Include the urgency context: penalty risk if we do not demonstrate credible progress.',
        'Ask Copilot: Draft a launch announcement email to our top 500 high-value postpaid customers introducing the Nexus Home FMC bundle. The email should explain the bundle, highlight the MYR 34 monthly saving, include a limited early adopter offer (first 3 months at 50% off), and provide a direct link to upgrade online. Subject line should be compelling and under 10 words.'
      ]),
      tool(T_TEAMS, M365_LIC, M365_ACCT, [
        'Open an existing recorded Teams meeting recap from a network or commercial operations meeting. Ask Copilot: Identify all 5G rollout milestones discussed, the current completion status of each, and any blockers mentioned. Format as a 5G programme status report.',
        'Ask Copilot: Draft follow-up actions for the Nexus Home FMC launch team. Group by workstream: Product | Marketing | Sales | Network | IT Systems | Customer Care. Include owner and deadline for each action.',
        'Ask Copilot: Based on this meeting, what are the top 3 risks to our MCMC milestone recovery? For each risk, identify who raised it, what mitigation was proposed, and whether a decision was made.'
      ], DESC_TEAMS),
      tool(T_NOTEBOOK, M365_LIC, M365_ACCT, [
        'Upload TC_01_ClearWave_Communications.xlsx, TC_02_ClearWave_Strategy.docx to Copilot Notebook. Set instruction: "You are a telecoms strategy advisor helping the CEO navigate the MCMC penalty and FMC launch simultaneously." Ask: Given constrained management bandwidth and capital, should ClearWave prioritise 5G rollout (to avoid further MCMC penalties) or FMC bundle launch (to arrest ARPU decline)? Make a recommendation with financial reasoning.',
        'Upload TC_01_ClearWave_Communications.xlsx and TC_02_ClearWave_Strategy.docx. Ask: The strategy commits to 20% 5G coverage by year-end and 180,000 FMC subscribers in Year 1. Given the current pace of 80 site activations per month and the FMC marketing investment required, does our current capex budget support both objectives simultaneously? If not, which should we fund first and what is the opportunity cost of delaying the other?'
      ], DESC_NOTEBOOK),
      tool(T_COWORK, FRONTIER_LIC, M365_ACCT, [
        'Do all of the following: (1) Research MCMC\'s penalty mitigation framework and any precedents where Malaysian telcos successfully negotiated penalty reductions by presenting credible remediation plans. (2) Draft a penalty mitigation submission to MCMC — 3 pages — presenting our 5G acceleration plan and requesting a 50% penalty reduction. (3) Save to OneDrive as "MCMC Penalty Mitigation Submission". (4) Email to our General Counsel and CEO for sign-off before the MCMC deadline. (5) Schedule a preparation meeting for the bilateral MCMC session.',
        'Do all of the following for the Nexus Home FMC launch: (1) Research competitor FMC bundle pricing in Malaysia — Maxis, Celcom, U Mobile — and compile a pricing comparison. (2) Draft a competitive pricing analysis brief for the CCO. (3) Create a launch countdown tracker in SharePoint with 30-day pre-launch milestones and owners. (4) Email the tracker and pricing brief to the CCO and Head of Products. (5) Schedule a daily FMC Launch War Room call for the 2 weeks before launch.'
      ], DESC_COWORK),
      tool(T_WORD_AGT, M365_LIC, M365_ACCT, [
        'Open TC_02_ClearWave_Strategy.docx in Word for Web. Create an agent called "ClearWave Strategy & Regulatory Bot". Description: "Answers questions from the commercial and regulatory teams about ClearWave\'s 5G commitments, MCMC obligations, FMC bundle strategy, and competitive positioning." Share with the strategy, regulatory, and commercial leadership.',
        'Demo: A regulatory affairs manager asks "What is our specific MCMC coverage commitment for Sabah and Sarawak by Q3, and what are the penalty rates if we miss it by 2 percentage points?" Show how the agent provides a precise, strategy-grounded regulatory answer.'
      ], DESC_WORD_AGT),
      tool(T_PPT_AGT, M365_LIC, M365_ACCT, [
        'Create a PowerPoint from the Board presentation. Create an agent called "5G & FMC Strategy Board Bot". Share with Board members and institutional investors.',
        'Demo: A Board member asks "If we achieve 20% 5G coverage by December but our FMC bundle only reaches 120,000 subscribers in Year 1, what is the net ARPU impact and do we still meet our FY2026 revenue guidance?" Show how the agent handles complex financial scenario questions.'
      ], DESC_PPT_AGT),
      tool(T_XL_AGT, M365_LIC, M365_ACCT, [
        'Open TC_01_ClearWave_Communications.xlsx in Excel for Web. Create an agent called "ClearWave Network & Commercial Q&A". Description: "Instant answers on 5G coverage by state, ARPU trends, FMC bundle performance, churn rates, and MCMC compliance status for the CTO, CFO, and CCO." Share with senior leadership.',
        'Demo: Ask "What is the current 5G coverage percentage in Selangor and what is the gap to the MCMC state-level target?" Then: "What is the current postpaid ARPU trend and what is the projected ARPU at Year 1 with full FMC bundle adoption?" Show how leadership gets rapid operational intelligence.'
      ], DESC_XL_AGT),
      tool(T_BUILDER, M365_LIC, M365_ACCT, [
        'Go to copilotstudio.microsoft.com > Create > New Agent. Name it "ClearWave Commercial Intelligence Agent". Description: "Supports ClearWave\'s commercial, regulatory, and network teams with answers on 5G rollout commitments, MCMC obligations, FMC bundle details, ARPU trends, and competitive intelligence — ensuring consistent, strategy-grounded responses across the organisation." Upload TC_01_ClearWave_Communications.xlsx and TC_02_ClearWave_Strategy.docx. Add topics: "5G & MCMC", "FMC Bundle", "ARPU & Revenue", "Competitive Intelligence". Publish to Teams.',
        'Demo the agent: A retail channel manager asks: "A Maxis customer is in our store comparing the Nexus Home FMC bundle against Maxis ONE. What is our price advantage, what is included in our bundle that Maxis does not offer, and if they mention they get a free upgrade phone with Maxis, what is our counter-offer?" Show how the agent equips frontline staff with the right competitive response in real time.'
      ], DESC_BUILDER),
    ]),
]

print(f"Batch 5 written: {len(INDUSTRIES_5)} entries")
