
import sys; sys.path.insert(0,'.')
from util import *

INDUSTRIES_1 = [

# ── GENERAL ───────────────────────────────────────────────────────────────
ind('general','general','⭐ General (Any Role)','⭐','#FF6B35','#FF8C42',
    'Zava Group Berhad',
    'FY2025 EBITDA misses budget by 18% — Board emergency review in 48 hours.',
    'Zava Group Berhad is a Malaysian diversified conglomerate with 11 divisions and about 8,400 employees. FY2025 EBITDA has missed budget by 18%, with 3 divisions now in negative EBITDA and investor confidence starting to wobble. The Group CEO has 48 hours to walk into an emergency Board review with a sharp briefing pack, a defensible variance analysis, and regulatory communications ready to go.',
    ['01_Zava_Group_Financial_Performance.xlsx','02_Zava_Group_Policy_Handbook.docx','03_Zava_Group_Strategy_Framework.docx'],
    [
      tool(T_CHAT, FREE_LIC, FREE_ACCT, [
        'You are the Group Chief of Staff at Zava Group Berhad. FY2025 EBITDA is 18% below budget, 3 divisions are in negative EBITDA, and the Board has called an emergency review in 48 hours. Draft a crisp 1-page CEO briefing that explains the situation in plain language, the likely questions directors will ask first, and the 5 decisions that must be ready before the meeting opens. Present as a structured table with columns for Issue, Why It Matters, Board Question, and Recommended Answer.',
        'You are the Group CFO at Zava Group Berhad. The CEO needs a verbal opening script for a high-pressure Board session after an 18% EBITDA miss across an 11-division conglomerate with 8,400 employees. Write a 90-second opening statement that acknowledges the underperformance directly, explains why 3 divisions have fallen into negative EBITDA, and signals immediate corrective action without sounding defensive. End with 3 talking points the CEO can use if directors challenge management credibility.',
        'You are the Head of Corporate Affairs at Zava Group Berhad. Prepare a stakeholder communication map for an 18% FY2025 EBITDA miss, 3 negative-EBITDA divisions, and an emergency Board review in 48 hours. Identify the priority audiences, the message each audience needs, the timing, and the main communication risk if the message is mishandled. Present as a RAG table with Red for immediate same-day communication needs, Amber for 24-hour needs, and Green for monitor-only audiences.'
      ]),
      tool(T_RESEARCHER, M365_LIC, M365_ACCT, [
        'You are the Group Strategy Director at Zava Group Berhad. Research how large diversified conglomerates in Malaysia and Indonesia have responded to EBITDA shortfalls of more than 15% against budget from 2022 to 2025. For at least 3 published case studies, identify the trigger event, the Board response within 30 days, and the financial outcome 12 months later. Cite all sources including publication dates and flag any claim that could not be independently verified against an original source.',
        'You are the Group Company Secretary at Zava Group Berhad. Research the disclosure, governance, and investor communication expectations that listed Malaysian and Indonesian conglomerates typically face after a material earnings miss and emergency Board review. Focus on Bursa Malaysia, OJK, IDX, and comparable listed-company guidance from 2022 to 2025, then distinguish mandatory obligations from market practice. Present as a table with columns for Requirement, Malaysia, Indonesia, Timing, and Practical Implication for Management.',
        'You are the Group CEO at Zava Group Berhad. Research turnaround actions used by ASEAN conglomerates when multiple divisions move into negative EBITDA at the same time, especially cost reset programmes, capital allocation changes, portfolio exits, and leadership interventions. Find examples published between 2022 and 2025 and note what happened in the first 100 days after the trigger event. Present as a RAG table with Red for actions usually required within 30 days, Amber for 31 to 90 days, and Green for longer-horizon actions, with citations for every case.'
      ], DESC_RESEARCHER),
      tool(T_ANALYST, M365_LIC, M365_ACCT, [
        'You are the Group CFO of Zava Group Berhad preparing for tomorrow\'s emergency Board review. Upload 01_Zava_Group_Financial_Performance.xlsx to Analyst. Using the Group P&L Summary tab, calculate the absolute and percentage revenue and EBITDA variance against FY2025 budget for each of the 11 divisions, identify the 3 divisions with the largest unfavourable EBITDA variance in MYR millions, and quantify the group-level gap behind the 18% miss. Flag divisions where EBITDA variance is worse than -20% as Red, -10% to -20% as Amber, and above -10% as Green. Present as a RAG summary table with one recommended corrective action per Red-status division.',
        'You are the Head of FP&A at Zava Group Berhad. Upload 01_Zava_Group_Financial_Performance.xlsx to Analyst. Using the Division Revenue Bridge tab and the Quarterly Earnings Tracker tab, identify which revenue and margin drivers explain why 3 divisions have fallen into negative EBITDA and whether the deterioration accelerated in Q4. Quantify the contribution of volume, pricing, mix, and cost movements where visible in the data, then show which divisions are stabilising versus worsening. Present as a structured RAG table with columns for Division, Main Driver, Q4 Change, Negative EBITDA Risk, and Recommended Action.',
        'You are the Group Treasurer at Zava Group Berhad. Upload 01_Zava_Group_Financial_Performance.xlsx to Analyst. Using the Balance Sheet Summary tab and the Key Financial Ratios tab, assess whether the FY2025 18% EBITDA miss creates pressure on leverage, interest cover, liquidity, or covenant headroom at group level, and identify which 3 metrics the Board should monitor weekly over the next 8 weeks. Flag metrics with immediate escalation risk as Red, heightened watchlist risk as Amber, and stable metrics as Green. Present as a RAG dashboard table with a short note on the likely implication for lenders and regulators.'
      ], DESC_ANALYST),
      tool(T_EXCEL, M365_LIC, M365_ACCT, [
        'Using the Group P&L Summary tab in this workbook, build a variance analysis dashboard on a new sheet called "Board Variance Dashboard". For each of the 11 divisions, calculate absolute revenue variance versus FY2025 budget in MYR M, percentage EBITDA variance, and year-on-year EBITDA margin change, then add a group-level summary row at the top. Apply conditional formatting so EBITDA variance worse than -20% is red, -10% to -20% is amber, and above -10% is green. The CFO is presenting this to the Board in 2 hours.',
        'Using the Division Revenue Bridge tab in this workbook, create a new sheet called "Recovery Bridge" that shows for each division the movement from FY2025 budget EBITDA to actual EBITDA using the major bridge drivers available in the data. Sort the divisions from worst to best by EBITDA gap, highlight the 3 divisions already in negative EBITDA, and add a short text box beside each Red division summarising the likely driver in one sentence. Present the result so it can be pasted directly into a Board pack.',
        'Using the Quarterly Earnings Tracker tab and the Key Financial Ratios tab in this workbook, create an early-warning tracker on a new sheet called "8-Week Watchlist". Show quarterly EBITDA trend, revenue trend, net debt to EBITDA, and interest cover for the group, then calculate whether each trend is improving, flat, or deteriorating. Flag metrics deteriorating for 2 or more consecutive periods as Red, 1 period as Amber, and stable or improving as Green. Present as a compact RAG table with sparklines that the CEO can review weekly.'
      ]),
      tool(T_WORD, M365_LIC, M365_ACCT, [
        'You are the Group Company Secretary at Zava Group Berhad. Using 02_Zava_Group_Policy_Handbook.docx, draft a 2-page Board paper for the emergency review covering governance obligations, escalation triggers, disclosure controls, and management accountabilities after an 18% EBITDA miss. Include sections for Immediate Facts, Governance Obligations, Decisions Required, and Next 30-Day Actions. Present in formal Board paper style with a short RAG summary at the top.',
        'You are the Group Strategy Director at Zava Group Berhad. Using 03_Zava_Group_Strategy_Framework.docx, draft a 2-page CEO briefing that explains which strategic priorities remain valid despite the FY2025 EBITDA miss and which priorities should be paused, reset, or accelerated across the 11 divisions. Specifically address the 3 divisions now in negative EBITDA and the implications for capital allocation over the next 2 quarters. Present as a Board-ready paper with a RAG table for Continue, Reset, and Pause decisions.',
        'You are the Head of Corporate Affairs at Zava Group Berhad. Using 02_Zava_Group_Policy_Handbook.docx and the tone of 03_Zava_Group_Strategy_Framework.docx, draft a stakeholder communication annex for the Board pack covering regulators, lenders, employees, and investors. For each audience, state the core message, approval owner, timing window, and the main risk if the wording is wrong. Present as a structured table followed by a 200-word holding statement the CEO can adapt quickly.'
      ]),
      tool(T_PPT, M365_LIC, M365_ACCT, [
        'You are the Group Chief of Staff at Zava Group Berhad. Create a 5-slide emergency Board deck on the FY2025 EBITDA miss using 01_Zava_Group_Financial_Performance.xlsx and 03_Zava_Group_Strategy_Framework.docx as the source context. Cover: group performance versus budget, the 3 negative-EBITDA divisions, the likely root causes, immediate management actions, and the decisions required in the next 48 hours. Use a serious executive design and present the output as a 5-slide deck with one headline message per slide.',
        'You are the Group CFO at Zava Group Berhad. Create a 5-slide briefing deck for the CEO to use in lender and regulator conversations after the Board review. Show the 18% EBITDA miss, balance sheet resilience, corrective actions, and the expected timeline for recovery across the 11 divisions. Flag the most material risk on each slide as Red, Amber, or Green and include speaker notes that keep the tone factual and controlled.',
        'You are the Head of Investor Relations at Zava Group Berhad. Build a 5-slide analyst call deck that explains the FY2025 variance without sounding defensive, focusing on what happened, what management is changing, and what investors should monitor next quarter. Include one slide that separates structural issues from one-off issues and one slide that summarises the 3 negative-EBITDA divisions. Format as a 5-slide deck with concise headlines, minimal text, and a closing slide titled "Management Commitments for the Next 90 Days".'
      ]),
      tool(T_OUTLOOK, M365_LIC, M365_ACCT, [
        'You are the Group Company Secretary at Zava Group Berhad. Draft the Board emergency meeting email for a session taking place in 48 hours on the FY2025 EBITDA miss. The email should explain the purpose, list the 3 agenda items, mention that 3 divisions are in negative EBITDA, and instruct directors to review the briefing pack before the meeting. Keep it under 180 words and professional, urgent, and discreet.',
        'You are the Group CFO at Zava Group Berhad. Draft an email to the lead relationship banks explaining that FY2025 EBITDA missed budget by 18% but that management is already preparing an emergency Board review and liquidity actions. Reassure lenders that balance sheet monitoring is active, note that a fuller update will follow after the Board meeting, and avoid making promises not yet approved. Present as a polished external email with a strong subject line.',
        'You are the Head of Corporate Affairs at Zava Group Berhad. Draft an internal email to all division CEOs immediately after the emergency Board review summarising the key decisions, the expectations for Red-status divisions, and the rules for external communications until approved messaging is issued. Keep the tone firm and aligned, and end with 3 bullet points titled "What you must do today".'
      ]),
      tool(T_TEAMS, M365_LIC, M365_ACCT, [
        'You are the Group Chief of Staff at Zava Group Berhad. Using this recorded Teams meeting recap from the executive committee, identify the decisions, unresolved issues, and action items related to the FY2025 EBITDA miss and the 3 divisions in negative EBITDA. Note who owns each item and whether it must be resolved before the Board emergency review in 48 hours. Present as a RAG table with Red for must-close before the Board, Amber for can close this week, and Green for monitor only.',
        'You are the Group CFO at Zava Group Berhad. Using this Teams meeting recap, extract every statement relevant to variance drivers, liquidity, covenant pressure, or regulatory communication readiness. Summarise the discussion in 4 sections: Key Facts, Risks Raised, Decisions Taken, and Follow-Up Actions with owners and due dates. End with a one-paragraph executive summary the CEO can paste into the Board pack.',
        'You are the Head of Investor Relations at Zava Group Berhad. Using this Teams meeting recap, identify which discussion points would worry investors most if they leaked before the Board review and which points demonstrate that management has control of the situation. Flag high-leak-risk items as Red, sensitive-but-manageable items as Amber, and safe factual items as Green. Present as a RAG table with suggested holding lines for each Red item.'
      ], DESC_TEAMS),
      tool(T_NOTEBOOK, M365_LIC, M365_ACCT, [
        'You are the Group CEO at Zava Group Berhad. Upload 01_Zava_Group_Financial_Performance.xlsx, 02_Zava_Group_Policy_Handbook.docx, and 03_Zava_Group_Strategy_Framework.docx to Copilot Notebook. Set the instruction: "You are my executive war-room analyst. Synthesize across all files, cite the source file for every major point, and focus on actions needed in the next 48 hours." Then ask for the 10-slide-equivalent story the Board needs, including the 18% EBITDA miss, the 3 negative-EBITDA divisions, the main governance obligations, and the top 5 decisions management must bring forward.',
        'You are the Group CFO at Zava Group Berhad. Upload 01_Zava_Group_Financial_Performance.xlsx and 03_Zava_Group_Strategy_Framework.docx to Copilot Notebook. Ask which strategic priorities appear underfunded or mis-sequenced given the FY2025 results, and which priorities should be accelerated, deferred, or stopped across the 11 divisions. Require Notebook to cite the exact source document for every recommendation and to present the answer as a RAG table with financial rationale.',
        'You are the Group Company Secretary at Zava Group Berhad. Upload 01_Zava_Group_Financial_Performance.xlsx, 02_Zava_Group_Policy_Handbook.docx, and 03_Zava_Group_Strategy_Framework.docx to Copilot Notebook. Ask Notebook to identify where the strategy narrative, the financial reality, and the policy obligations are misaligned ahead of the emergency Board review. Request a concise answer with 3 sections: Contradictions to Resolve, Questions Directors Will Ask, and Recommended Pre-Reads, all with citations to the source files.'
      ], DESC_NOTEBOOK),
      tool(T_COWORK, FRONTIER_LIC, M365_ACCT, [
        'You are the Group Chief of Staff at Zava Group Berhad. Do all of the following autonomously: research comparable Malaysian and Indonesian conglomerate responses to EBITDA misses above 15%, draft a 2-page Word document titled "Emergency Board Review Brief", save it to OneDrive, email it to the Group CEO and CFO for review, and schedule a 30-minute Teams prep meeting for tomorrow morning. Keep the brief focused on Board actions, disclosure risk, and the first 30 days of recovery.',
        'You are the Group Company Secretary at Zava Group Berhad. Do all of the following autonomously: create the emergency Board review meeting invite for 48 hours from now, attach a placeholder agenda, set a reminder 12 hours before the meeting, create a OneDrive folder called "Board Emergency Review - FY2025 EBITDA", and email all directors asking them to expect the final pack within 24 hours. Keep the wording discreet and clearly marked confidential.',
        'You are the Group CFO at Zava Group Berhad. Do all of the following autonomously: draft a lender update email, draft a regulator holding note, create a task list for the finance leadership team covering variance analysis, liquidity review, and divisional recovery plans, then send the task list to the relevant owners and schedule a 20-minute checkpoint meeting for this afternoon. The context is an 18% FY2025 EBITDA miss with 3 divisions in negative EBITDA and an emergency Board review in 48 hours.'
      ], DESC_COWORK),
      tool(T_EDIT_COPILOT, M365_LIC, M365_ACCT, [
        'You are the Group Company Secretary at Zava Group Berhad. Using 02_Zava_Group_Policy_Handbook.docx in Word for the web, add an appendix titled "Emergency Earnings Review Governance Protocol" and populate it with a decision-rights table, escalation timeline, and approval matrix for regulator, lender, investor, and employee communications. Keep the language consistent with the existing handbook and add a short note wherever legal review is required before external release.',
        'Using the Group P&L Summary tab and the Key Financial Ratios tab in 01_Zava_Group_Financial_Performance.xlsx, create a new worksheet called "Board Recovery Tracker" that combines divisional EBITDA variance, RAG status, leverage metrics, and an owner column for each corrective action. Reorder the columns so Board readers see the Red issues first, apply consistent styling, and add formulas that automatically refresh the group summary at the top when divisional values change.',
        'You are the Group Chief of Staff at Zava Group Berhad. Using the current Board presentation in PowerPoint for the web, restructure the deck so the first 5 slides tell a tighter crisis narrative on the FY2025 EBITDA miss. Consolidate duplicative slides, rewrite slide titles into action-oriented headlines, move detailed backup charts to an appendix, and add a final decisions slide that clearly separates approve today, review next week, and monitor monthly.'
      ], DESC_EDIT_COPILOT),
      tool(T_WORD_AGT, M365_LIC, M365_ACCT, [
        'You are the Group Company Secretary at Zava Group Berhad. Open 02_Zava_Group_Policy_Handbook.docx in Word for Web and create a new agent called "Zava Governance Guide". Describe it as an assistant that answers questions on governance obligations, escalation rules, disclosure controls, and approval authorities during performance or crisis situations. Set the document as the knowledge source and share it with the CEO office, finance, and corporate affairs teams.',
        'You are the Head of Corporate Affairs at Zava Group Berhad. Demo the Zava Governance Guide agent by asking: "An 18% EBITDA miss has triggered an emergency Board review. What approvals do I need before sending a regulator update, a lender email, and an employee note, and who owns each approval?" Show how the agent responds with policy-grounded guidance that cites the source document.'
      ], DESC_WORD_AGT),
      tool(T_PPT_AGT, M365_LIC, M365_ACCT, [
        'You are the Group Chief of Staff at Zava Group Berhad. Build the emergency Board review deck in PowerPoint for Web, then create a new agent called "Board Pack Navigator". Describe it as an assistant that helps directors and executives find the right slide, chart, or message on group performance, divisional issues, and next-step decisions. Share it with the Board office and senior leadership team only.',
        'You are the Group CFO at Zava Group Berhad. Demo the Board Pack Navigator agent by asking: "Which 3 divisions are in negative EBITDA, what is the size of each gap versus budget, and which slide should I open if a director asks about leverage impact?" Then ask it to summarise the 3 most important decisions on the final slide in under 80 words.'
      ], DESC_PPT_AGT),
      tool(T_XL_AGT, M365_LIC, M365_ACCT, [
        'You are the Group CFO at Zava Group Berhad. Open 01_Zava_Group_Financial_Performance.xlsx in Excel for Web and create a new agent called "Zava Performance Q&A". Describe it as an assistant that answers questions on the Group P&L Summary, Division Revenue Bridge, Balance Sheet Summary, Quarterly Earnings Tracker, and Key Financial Ratios tabs for the emergency Board review. Share it with the Group CEO, finance leadership team, and strategy office.',
        'You are the Group CEO at Zava Group Berhad. Demo the Zava Performance Q&A agent by asking: "Which 3 divisions have the largest unfavourable EBITDA variance in FY2025, what is the group-level miss versus budget, and has liquidity or leverage materially worsened?" Then ask it to classify each answer as Red, Amber, or Green so the CEO gets an instant decision-oriented summary.'
      ], DESC_XL_AGT),
      tool(T_BUILDER, M365_LIC, M365_ACCT, [
        'You are the Group Chief of Staff at Zava Group Berhad. Go to copilotstudio.microsoft.com and create a new agent called "Zava Executive War Room". Describe it as an assistant for Board, CEO, CFO, and corporate affairs teams managing the FY2025 EBITDA miss, and upload 01_Zava_Group_Financial_Performance.xlsx, 02_Zava_Group_Policy_Handbook.docx, and 03_Zava_Group_Strategy_Framework.docx as knowledge sources. Add starter topics for Board Review, Divisional Recovery, Stakeholder Communications, and Governance Approvals, then publish it to Teams for authorised executives only.',
        'You are the Group CEO at Zava Group Berhad. Demo the published Zava Executive War Room agent in Teams by asking: "Give me the 60-second version of the FY2025 EBITDA problem, the 3 divisions in negative EBITDA, the top governance obligations, and the decisions I must take to the Board in 48 hours." Then ask a second question: "Draft my first message to division CEOs after the Board meeting."'
      ], DESC_BUILDER),
    ],
    'PT Wahana Makmur Nusantara Tbk',
    'EBITDA FY2025 meleset 18% — review darurat direksi dalam 48 jam.'),

# ── COMMERCIAL BANKING ─────────────────────────────────────────────────────
ind('commercial-banking','banking-fs','Commercial Banking','🏦','#0D47A1','#1976D2',
    'Meridian Bank Berhad',
    'NPL at 14.2% — 4x BNM\'s supervisory threshold. Bilateral review in 3 days.',
    'Meridian Bank Berhad is Malaysia\'s fifth-largest commercial bank by assets (MYR 68.4B). Personal Financing NPL has climbed for 6 consecutive quarters, reaching 14.2% — four times BNM\'s 3.5% supervisory threshold. The CFO goes into a BNM bilateral review on Tuesday. Provision coverage sits at 68%, well below the internal 80% target.',
    ['BNK_01_Meridian_Bank.xlsx','BNK_02_Meridian_Bank_Strategy.docx','Email_01_Zava_Bank_NPL_Thread.docx','Email_06_BNM_Regulatory_Correspondence.docx'],
    [
      tool(T_CHAT, FREE_LIC, FREE_ACCT, [
        'I am the CFO of a Malaysian commercial bank. Our Personal Financing NPL ratio has climbed from 8.2% to 14.2% over six quarters and I have a BNM bilateral review in three days. Draft a one-page internal briefing note for my Board Risk Committee explaining the NPL situation in plain language: what drove the deterioration, what remediation actions we have taken so far, and what we expect BNM to ask. Keep the tone calm and factual — this is not a crisis communication, it is a preparatory briefing.',
        'Explain the difference between gross NPL ratio, net NPL ratio, and provision coverage ratio in the context of Malaysian banking regulation. Use simple language suitable for a Board director who has a finance background but is not a banking specialist. Include a worked numerical example using approximate figures.',
        'What are BNM\'s standard remediation requirements when a bank\'s NPL ratio exceeds its supervisory threshold? List the typical regulatory actions BNM may impose, from supervisory letters through to more formal interventions, and indicate the approximate timelines involved.'
      ]),
      tool(T_RESEARCHER, M365_LIC, M365_ACCT, [
        'Research how Malaysian commercial banks have managed NPL surges in the past five years, particularly post-moratorium periods. I need: (1) Industry-average NPL ratios for Malaysian banks in 2023–2025, (2) The three most common remediation strategies banks used successfully, (3) Any BNM guidance circulars on NPL management issued since 2023. Cite all sources so I can share this with our credit risk team.',
        'Research global best practices for bank NPL resolution programmes, particularly in markets with similar profile to Malaysia — emerging markets with retail-heavy loan books. Identify two or three banks that successfully reduced NPL ratios by more than 4 percentage points within 18 months and summarise their approach. Present findings as a structured brief with source links.'
      ], DESC_RESEARCHER),
      tool(T_ANALYST, M365_LIC, M365_ACCT, [
        'Analyse the NPL trend across all loan product segments from Q1 FY2023 to Q4 FY2025. Which three product segments are driving the highest NPL increase in absolute MYR terms? Calculate the required provision top-up to reach 80% provision coverage for each segment and show the cumulative impact on pre-tax profit. Present as a ranked table: Segment | Current NPL (MYR M) | Coverage Gap | Provision Top-Up Required | Pre-Tax Profit Impact.',
        'Build a scatter plot showing the relationship between loan vintage (year of origination) and default rate across all Personal Financing accounts. Identify whether there is a specific origination cohort that is disproportionately contributing to the NPL problem. If a pattern exists, calculate what percentage of total NPL would be resolved by writing off or restructuring that cohort alone.'
      ], DESC_ANALYST),
      tool(T_EXCEL, M365_LIC, M365_ACCT, [
        'Using the Loan Portfolio tab in this workbook, Our Personal Financing NPL ratio has climbed from 8.2% in Q1 FY2023 to 14.2% in Q4 FY2025, now 4x BNM\'s supervisory threshold of 3.5%. Analyse the quarterly deterioration trend across all product segments, identify the three sub-segments contributing most to the NPL increase, calculate the additional loan loss provision required to reach 80% provision coverage, and show the resulting impact on pre-tax profit. Present as a 4-column table: Segment | NPL Rate | Provision Shortfall (MYR M) | Recommended Action.',
        'Create a dynamic NPL stress-test model on a new sheet called "Stress Test". Assume three scenarios — Base (NPL stays at 14.2%), Moderate (NPL rises to 18%), Severe (NPL rises to 22%). For each scenario, calculate the required provision, the impact on Tier 1 capital ratio, and the regulatory capital buffer remaining above BNM\'s 10.5% minimum. Flag in red any scenario where the buffer falls below 1%.',
        'Add a rolling 4-quarter average NPL ratio column next to each product segment row. Then add conditional formatting to flag any segment where the most recent quarter\'s NPL exceeds the 4Q average by more than 2 percentage points — these are the fast-deteriorating segments that need immediate escalation.',
        'Summarise the key risk metrics on the Risk Dashboard sheet into a plain-language paragraph I can paste into the Board pack. Highlight the three metrics that are outside tolerance thresholds and suggest a one-sentence action for each.'
      ]),
      tool(T_WORD, M365_LIC, M365_ACCT, [
        'Draft a 2-page credit risk remediation plan for BNM submission. Structure it as: (1) Executive Summary — current NPL position and root causes, (2) Remediation Actions — three concrete steps with timelines, (3) Governance — who owns each action and how progress will be reported, (4) Milestones — what BNM should expect to see at 30, 60, and 90 days. Use a formal regulatory tone throughout.',
        'Identify all sections in this strategy document that reference credit risk or lending standards. For each section, summarise in one sentence whether the current strategy is consistent with remediation of the NPL problem or whether it may be contributing to it. Present as a gap analysis table.',
        'Rewrite the Executive Summary of this document to reflect the current NPL crisis. The new summary should open with the most critical issue, acknowledge the BNM bilateral review, and end with a clear statement of the bank\'s commitment to reaching 80% provision coverage within 6 months. Keep it under 200 words.',
      ]),
      tool(T_PPT, M365_LIC, M365_ACCT, [
        'Create a 12-slide Board presentation titled "NPL Remediation Programme — Q4 FY2025 Update" for Meridian Bank. Slides should cover: (1) NPL dashboard — current vs threshold, (2) Root cause analysis, (3) Segment breakdown — top 3 contributors, (4) Provision coverage gap analysis, (5) Remediation plan — 3 initiatives, (6) Timeline and milestones, (7) Capital adequacy impact, (8) BNM engagement strategy, (9) Risk appetite reset, (10) Next steps. Use a professional dark-blue colour scheme.',
        'For each slide in this presentation, generate speaker notes that are a 45-second verbal script. The CFO delivering this has 20 years of banking experience, so avoid over-explaining basics — focus the notes on pre-empting the questions Board members are most likely to ask.',
        'Add a "Key Risks" slide after slide 8 that shows five risks to the remediation plan in a 2×2 risk matrix (likelihood vs impact), with one-line mitigants for each risk.'
      ]),
      tool(T_OUTLOOK, M365_LIC, M365_ACCT, [
        'Draft a formal response to BNM\'s latest query. Acknowledge their concerns about the NPL trajectory, outline the three immediate remediation steps we have initiated, confirm the timeline for our next progress report, and request a 30-minute call with the BNM supervision team to discuss the bilateral review agenda. Use the formal salutation style appropriate for BNM correspondence.',
        'Open Email_01_Zava_Bank_NPL_Thread.docx. Summarise this internal email thread, identify all commitments made by the credit risk team, and draft a follow-up email to the Chief Credit Officer asking for a status update on each commitment before the BNM meeting on Tuesday. List the commitments as numbered bullet points in the email body.',
        'Draft an all-staff email from the CEO to branch managers and relationship managers explaining the NPL situation without causing alarm. The email should acknowledge the challenge, explain what the bank is doing about it, and give clear guidance on what relationship managers should and should not say to customers who ask about loan restructuring options. Keep it under 300 words.'
      ]),
      tool(T_TEAMS, M365_LIC, M365_ACCT, [
        'Open an existing recorded Teams meeting recap from a credit or risk committee meeting. Generate a structured recap covering: (1) Key credit risk metrics reviewed, (2) Decisions made on provisioning or remediation, (3) Action items with owners and due dates, (4) Any escalation items that need Board or BNM notification. Format for distribution to the Risk Committee.',
        'Draft a follow-up email to all Risk Committee members. The email should list all action items with owner names and deadlines, note any decisions that require CFO or Board sign-off, and propose the next Risk Committee meeting date.',
        'Based on this meeting transcript, identify any statements made about NPL targets or remediation timelines that could be interpreted as commitments to BNM. List each statement with the speaker name and timestamp so the legal team can review before the bilateral meeting.'
      ], DESC_TEAMS),
      tool(T_NOTEBOOK, M365_LIC, M365_ACCT, [
        'Upload BNK_01_Meridian_Bank.xlsx, BNK_02_Meridian_Bank_Strategy.docx, and Email_06_BNM_Regulatory_Correspondence.docx to Copilot Notebook. Set this instruction: "You are a senior banking regulator advisor preparing the CFO for a BNM bilateral review." Ask: Based on the NPL data, our strategy document, and the BNM correspondence, what are the five most likely questions BNM will ask on Tuesday? For each question, draft a concise, factually grounded answer the CFO can use.',
        'Upload BNK_01_Meridian_Bank.xlsx and Email_01_Zava_Bank_NPL_Thread.docx. Ask: Cross-reference the NPL figures in the data file against the commitments made in the internal email thread. Are there any discrepancies between what was promised internally and what the data shows has actually happened? List any gaps the CFO should be aware of before the BNM meeting.'
      ], DESC_NOTEBOOK),
      tool(T_COWORK, FRONTIER_LIC, M365_ACCT, [
        'Do all of the following: (1) Research the latest BNM guidelines on NPL classification and provisioning requirements published in 2024 or 2025. (2) Draft a 3-page internal compliance brief summarising the key requirements and how Meridian Bank\'s current provisioning compares. (3) Save it as "BNM NPL Compliance Brief - [Today\'s Date]" in OneDrive. (4) Email it to the Chief Risk Officer and Chief Credit Officer with subject "BNM NPL Compliance Brief — Please review before Tuesday" asking for feedback by Monday 5pm. (5) Schedule a 1-hour prep meeting titled "BNM Bilateral Review Prep" for Monday 2pm and invite the CFO, CRO, and CCO.',
        'Do all of the following: (1) Check the calendar for any outstanding action items from the last Risk Committee meeting. (2) For each action item that is overdue, send a polite follow-up email to the owner asking for a status update by end of day. (3) Create a Word document listing all overdue items with owner names and original due dates. (4) Post a summary in the #risk-committee Teams channel: "Reminder: 3 action items from our last meeting are overdue — please update by COB today." (5) Set a recurring weekly reminder in my calendar titled "Risk Action Item Review" every Friday at 4pm for 12 weeks.'
      ], DESC_COWORK),
      tool(T_WORD_AGT, M365_LIC, M365_ACCT, [
        'Open BNK_02_Meridian_Bank_Strategy.docx in Word for Web. Create a new agent called "Credit Strategy Assistant" with description: "Answers questions from credit and risk officers about Meridian Bank\'s credit risk strategy, NPL remediation plan, and lending standards." Set the document as knowledge source. Share with the credit risk team and branch network compliance officers.',
        'Demo query: Ask the Credit Strategy Assistant in Teams: "What is the approved remediation approach for Personal Financing accounts that have been in arrears for more than 90 days? What restructuring options am I authorised to offer before escalating to the Credit Committee?" Show how the agent pulls the answer directly from the strategy document.'
      ], DESC_WORD_AGT),
      tool(T_PPT_AGT, M365_LIC, M365_ACCT, [
        'Create a PowerPoint presentation summarising the NPL remediation programme slides, then open it in PowerPoint for Web. Create an agent called "NPL Remediation Briefing Bot". Description: "Provides instant answers about Meridian Bank\'s NPL remediation programme, targets, and milestones for board members and senior management." Share with Board members so they can review without needing to open the full deck.',
        'Demo: Ask the agent "What is our target NPL ratio at the end of Q2 FY2026 and what are the three key actions driving that target?" Then ask: "What happens to our Tier 1 capital ratio in the severe stress scenario?" Show how Board members get precise answers without navigating through slides.'
      ], DESC_PPT_AGT),
      tool(T_XL_AGT, M365_LIC, M365_ACCT, [
        'Open BNK_01_Meridian_Bank.xlsx in Excel for Web. Create an agent called "Meridian Loan Portfolio Q&A". Description: "Answers questions about Meridian Bank\'s loan portfolio, NPL ratios, provision coverage, and segment breakdowns using live workbook data." Share with senior credit officers who need quick data access without navigating the full workbook.',
        'Demo: Ask the agent "What is the current NPL ratio for the SME segment and how does it compare to the industry average?" Then ask: "Which loan product has the highest rate of deterioration over the last four quarters?" Show how credit managers get instant, data-grounded answers.'
      ], DESC_XL_AGT),
      tool(T_BUILDER, M365_LIC, M365_ACCT, [
        'Go to copilotstudio.microsoft.com > Create > New Agent. Name it "Meridian Credit Risk Assistant". Description: "A regulatory-ready AI assistant for Meridian Bank\'s credit and risk teams — answers questions about NPL positions, remediation plans, BNM requirements, and lending policies using official bank documents." Upload BNK_01_Meridian_Bank.xlsx, BNK_02_Meridian_Bank_Strategy.docx, and Email_06_BNM_Regulatory_Correspondence.docx as knowledge sources. Add a starter topic: "Explain our current NPL situation and remediation plan." Publish to Teams for the Risk and Credit divisions.',
        'Demo the agent in Teams. Ask it: "We have a customer requesting a third loan restructuring on their Personal Financing account. What is our policy and what approval level is required?" Then ask: "What NPL ratio target has the Board approved for end of FY2026 and what are the consequences if we miss it?" Show how the agent gives consistent, document-grounded answers that reduce compliance risk from inconsistent verbal guidance.'
      ], DESC_BUILDER),
    ]),

# ── ISLAMIC BANKING ────────────────────────────────────────────────────────
ind('islamic-banking','banking-fs','Islamic Banking','🕌','#1A237E','#283593',
    'Al-Amanah Islamic Bank Malaysia',
    'MYR 3.5B Sukuk issuance pending — BNM IFSA compliance review in 4 weeks.',
    'Al-Amanah Islamic Bank Malaysia (AIBM) has MYR 22.1B in total financing assets. A landmark MYR 3.5B Sukuk Wakalah issuance is pending regulatory approval. The BNM IFSA compliance review is scheduled in 4 weeks and the Shariah Committee has flagged two products for re-structuring. Profit rate risk is rising as OPR hovers at 3.0%.',
    ['BNK_01_Meridian_Bank.xlsx','BNK_02_Meridian_Bank_Strategy.docx'],
    [
      tool(T_CHAT, FREE_LIC, FREE_ACCT, [
        'Explain the key differences between a conventional bank loan and Islamic financing products such as Murabahah, Ijarah, and Musharakah Mutanaqisah — in plain language suitable for a retail customer who has only ever had a conventional mortgage. Focus on how the profit rate is determined, who owns the asset, and what happens in the event of default.',
        'What are the key disclosure requirements under BNM\'s IFSA 2013 (Islamic Financial Services Act) for a Sukuk Wakalah issuance? List the five most critical compliance obligations and the approval timeline from application to issuance. Include the role of the Shariah Advisory Council in the approval process.',
        'Draft a one-paragraph explanation of profit rate risk in Islamic banking that I can use in our annual report. The paragraph should explain the concept, why it differs from interest rate risk in conventional banking, and how we manage it through our Asset and Liability Management framework. Keep it under 150 words and avoid overly technical language.'
      ]),
      tool(T_RESEARCHER, M365_LIC, M365_ACCT, [
        'Research the global Sukuk market outlook for 2025 and 2026 — specifically for Malaysia. I need: (1) Total Sukuk issuance volumes in Malaysia for 2024 and the forecast for 2025, (2) Demand trends from Middle Eastern and Southeast Asian investors, (3) Any new BNM or SC guidelines affecting Sukuk Wakalah structures issued in the past 12 months. Provide source citations for each data point.',
        'Research how Islamic banks in Malaysia are managing profit rate risk in a rising OPR environment. Identify the top three strategies used by leading Islamic banks (Maybank Islamic, CIMB Islamic, Bank Islam) and compare their approaches. Summarise in a briefing note format suitable for the ALCO (Asset and Liability Committee).'
      ], DESC_RESEARCHER),
      tool(T_ANALYST, M365_LIC, M365_ACCT, [
        'Analyse the financing asset breakdown by product type (Murabahah, Ijarah, Musharakah, etc.) and calculate the concentration risk — what percentage of total financing is in the top 3 product categories. Create a pie chart showing product mix and a trend chart showing how the mix has shifted over the past 8 quarters. Flag any product category where growth has exceeded 15% quarter-on-quarter.',
        'Perform a sensitivity analysis on profit income assuming OPR changes of -50bps, flat, +50bps, and +100bps. For each scenario, calculate the impact on Net Financing Income (NFI) in MYR millions and the resulting NFI margin. Present as a 4-scenario sensitivity table with a colour-coded heat map — red for scenarios where NFI margin falls below 2.5%.'
      ], DESC_ANALYST),
      tool(T_EXCEL, M365_LIC, M365_ACCT, [
        'Using the Financing Portfolio tab in this workbook, Create a Shariah compliance monitoring dashboard on a new sheet called "Shariah Dashboard". It should show: (1) Each product type and its Shariah contract structure, (2) The profit rate benchmark used (COF + spread), (3) Any product where the actual rate charged deviates from the approved structure by more than 10bps — flag these in red.',
        'Build a Sukuk issuance impact model on a new sheet. Assume a MYR 3.5B Sukuk Wakalah at 4.2% profit rate for 5 years. Calculate: (1) Annual profit distribution to Sukukholders, (2) Impact on the bank\'s liquidity coverage ratio (LCR), (3) Impact on the net stable funding ratio (NSFR), (4) Breakeven period assuming proceeds are deployed into Murabahah financing at 6.8% profit rate.',
        'In the financing data, identify all accounts where the financing-to-value (FTV) ratio has exceeded 90% and the account is classified as Stage 2 under MFRS 9. List them by product type and calculate the expected credit loss (ECL) for each assuming a 35% loss given default (LGD). Present as a table sorted by ECL amount, largest first.',
      ]),
      tool(T_WORD, M365_LIC, M365_ACCT, [
        'Draft a Shariah compliance remediation memo for the two flagged products. For each product, the memo should include: (1) the Shariah issue identified, (2) the proposed re-structuring to comply with IFSA requirements, (3) the customer impact and communication plan, (4) the timeline for remediation and sign-off by the Shariah Committee. Use a formal regulatory tone.',
        'Summarise the BNM IFSA compliance requirements referenced in this strategy document into a checklist format. For each requirement, add a status column (Compliant / Partial / Gap) and a responsible officer column. This checklist will be used by the compliance team to prepare for the upcoming BNM review.',
        'Draft a Sukuk Wakalah investor briefing document of approximately 500 words. Cover: the structure of the instrument, profit rate and payment schedule, the underlying Wakalah assets, the risk factors, and the use of proceeds. The audience is institutional investors from the GCC who are familiar with Islamic finance but unfamiliar with Malaysian regulatory requirements.'
      ]),
      tool(T_PPT, M365_LIC, M365_ACCT, [
        'Create a 10-slide Sukuk Wakalah roadshow presentation for institutional investors. Include slides on: AIBM overview and credit rating, the Sukuk structure diagram, profit rate and tenure, use of proceeds, the Shariah compliance framework, key financial metrics (CAR, NPF ratio, ROAE), risk factors, and a Q&A summary. Use a professional green and gold colour scheme appropriate for an Islamic finance presentation.',
        'Add speaker notes to each slide of this investor presentation. The notes should anticipate the three most likely questions from a GCC sovereign wealth fund and provide brief scripted answers the presenter can deliver naturally.',
        'Create a 2-slide summary of the BNM IFSA compliance status for use in the Board Shariah Committee meeting. Slide 1: Current compliance status (RAG table by requirement). Slide 2: Remediation plan for the two flagged products with a Gantt-style timeline.'
      ]),
      tool(T_OUTLOOK, M365_LIC, M365_ACCT, [
        'Open Email_06_BNM_Regulatory_Correspondence.docx. Draft a formal response to the BNM IFSA review notice. The letter should: acknowledge receipt of the review schedule, confirm our readiness and the documents we will provide, request clarification on two specific requirements relating to Musharakah profit-sharing ratios, and propose a pre-review meeting with the BNM supervision officer to align on expectations.',
        'Draft an email to our Shariah Committee members calling an emergency meeting to address the two flagged products. The email should explain the nature of the Shariah issue without using overly technical language, attach the relevant product term sheets for review, and ask for written confirmation of availability for a 2-hour session this week. Subject line: "Urgent: Shariah Committee Review — Two Product Compliance Issues".',
        'Coach me on the tone of the draft email to BNM. Is it too defensive? Too casual? Does it inadvertently admit any non-compliance? Suggest three edits that would make the letter more confident and regulatory-appropriate without being evasive.'
      ]),
      tool(T_TEAMS, M365_LIC, M365_ACCT, [
        'Open an existing recorded Teams meeting recap from a Shariah Committee or ALCO meeting. Identify all Shariah compliance decisions made in this meeting, the rationale provided, and any conditions attached to the approval. Format as a formal Shariah Committee resolution summary suitable for inclusion in the minute book.',
        'Ask Copilot in the recap: Draft follow-up action items for the ALCO based on this meeting. Each action should have a clear owner, a deliverable, and a deadline. Group actions by theme: Profit Rate Risk, Liquidity, Sukuk Issuance, and Shariah Compliance.',
        'Were any profit rate assumptions discussed in this meeting that differ from the assumptions in our Board-approved ALCO policy? If so, flag them with the exact quote from the transcript and the page number of the policy they may conflict with.'
      ], DESC_TEAMS),
      tool(T_NOTEBOOK, M365_LIC, M365_ACCT, [
        'Upload BNK_02_Meridian_Bank_Strategy.docx and Email_06_BNM_Regulatory_Correspondence.docx to Copilot Notebook. Set instruction: "You are a Shariah compliance officer preparing for a BNM IFSA review." Ask: What are the five most critical gaps between our strategy document and the BNM IFSA requirements referenced in the regulatory correspondence? For each gap, propose a remediation step and estimate the time required to close it.',
        'Upload BNK_01_Meridian_Bank.xlsx and BNK_02_Meridian_Bank_Strategy.docx. Ask: Based on the financing portfolio data and our stated strategy, which business segments are growing fastest and are they consistent with our Shariah-compliant product strategy? Flag any segment where growth is driven by a product type that the Shariah Committee has flagged for review.'
      ], DESC_NOTEBOOK),
      tool(T_COWORK, FRONTIER_LIC, M365_ACCT, [
        'Do all of the following: (1) Research BNM\'s latest IFSA guidelines on Sukuk Wakalah issuance requirements and any updates from the Securities Commission published in 2025. (2) Draft a 2-page compliance readiness checklist for our Sukuk issuance, mapping each requirement to our current status. (3) Save it to OneDrive as "Sukuk IFSA Compliance Checklist - [Today\'s Date]". (4) Email it to the Head of Islamic Finance and the Chief Compliance Officer asking for review and sign-off by Thursday. (5) Schedule a 90-minute "Sukuk Issuance Pre-Approval Review" meeting for Friday morning and invite the CFO, Head of Islamic Finance, and Shariah Committee Chairman.',
        'Do all of the following: (1) Set up a recurring weekly 30-minute Teams meeting titled "Shariah Compliance Monitoring Check-In" every Wednesday at 3pm for the next 12 weeks and invite the Shariah Compliance team. (2) Draft an agenda template for these meetings covering: open issues review, new product pipeline, BNM correspondence updates, and any other business. (3) Post the agenda template in the #shariah-compliance Teams channel with a message: "Agenda template for our weekly check-ins — please use this format going forward." (4) Send each invitee a welcome email explaining the purpose of the check-in series.'
      ], DESC_COWORK),
      tool(T_WORD_AGT, M365_LIC, M365_ACCT, [
        'Open BNK_02_Meridian_Bank_Strategy.docx in Word for Web. Create an agent called "AIBM Shariah Policy Bot". Description: "Answers questions from product managers and relationship managers about Al-Amanah Islamic Bank\'s Shariah compliance requirements, approved product structures, and profit rate policies." Set the document as knowledge source and share with the Islamic Banking product team.',
        'Demo: Ask the Shariah Policy Bot: "Is it permissible under our current Shariah framework to offer a hybrid Murabahah-Ijarah product for commercial property financing? What are the structural requirements and who needs to approve it?" Show how the agent gives a policy-grounded answer rather than requiring the team to search through documentation.'
      ], DESC_WORD_AGT),
      tool(T_PPT_AGT, M365_LIC, M365_ACCT, [
        'Convert the Sukuk investor presentation into a PowerPoint file and open it in PowerPoint for Web. Create an agent called "Sukuk Investor Q&A Bot". Description: "Answers investor questions about Al-Amanah\'s MYR 3.5B Sukuk Wakalah issuance — structure, profit rate, Shariah compliance, and use of proceeds." Share the agent with the IR team and external investor contacts.',
        'Demo: Ask the agent "What is the profit rate and payment frequency for this Sukuk?" Then ask: "Who is the Shariah advisor for this issuance and what is the fatwa basis for the Wakalah structure?" Show how investor queries are answered instantly without requiring the IR team to dig through the prospectus.'
      ], DESC_PPT_AGT),
      tool(T_XL_AGT, M365_LIC, M365_ACCT, [
        'Open BNK_01_Meridian_Bank.xlsx in Excel for Web. Create an agent called "AIBM Portfolio Analytics Q&A". Description: "Instant answers on Al-Amanah Islamic Bank\'s financing portfolio — product mix, NPF ratios, profit rate sensitivity, and concentration risk — for ALCO and senior management." Share with ALCO members.',
        'Demo: Ask the agent "What is the current non-performing financing ratio for the Home Financing (Musharakah Mutanaqisah) segment?" Then ask: "If OPR rises by 50bps, what is the projected impact on our Net Financing Income?" Show how ALCO members get data-grounded answers in seconds.'
      ], DESC_XL_AGT),
      tool(T_BUILDER, M365_LIC, M365_ACCT, [
        'Go to copilotstudio.microsoft.com > Create > New Agent. Name it "AIBM Compliance & Product Assistant". Description: "Helps Islamic banking staff answer Shariah compliance questions, understand approved product structures, and navigate BNM IFSA requirements — grounded in official bank strategy and compliance documents." Upload BNK_02_Meridian_Bank_Strategy.docx and Email_06_BNM_Regulatory_Correspondence.docx. Add topics: "Shariah Product Query", "BNM Requirement Lookup", "Sukuk Issuance FAQ". Publish to Teams for all Islamic Banking staff.',
        'Demo the agent: Ask it "A corporate client wants Islamic financing for a toll road concession. What Shariah-compliant structures can we offer and what is the maximum tenure allowed under our current policy?" Then ask: "What are the BNM disclosure requirements for this type of infrastructure financing?" Show how front-line bankers get consistent, compliant guidance without calling the Shariah department.'
      ], DESC_BUILDER),
    ]),
]

print(f"Industries batch 1 written: {len(INDUSTRIES_1)} entries")
