
import sys; sys.path.insert(0,'.')
from util import *

INDUSTRIES_5 = [

# ── PLANTATION & AGRIBUSINESS ──────────────────────────────────────────────
ind('plantation', 'plantation', 'Plantation & Agribusiness', '🌿', '#388E3C', '#43A047',
    'Seri Sawit Nusantara Berhad',
    'Yield softness and certification exposure threaten premium export contracts.',
    'Seri Sawit Nusantara Berhad operates palm estates across Sabah and Kalimantan. Management is balancing estate yield softness, rising labour pressure, and sustainability assurance demands from export buyers at the same time. The Board wants one integrated view of operating performance, control gaps, and buyer exposure before the next quarterly review.',
    ['PLT_01_Estate_Operations.xlsx', 'PLT_02_MSPO_Certification_Manual.docx', 'PLT_03_Estate_Operations_SOP.docx'],
    [
      tool(T_CHAT, FREE_LIC, FREE_ACCT, [
        'You are the Chief Sustainability Officer at Seri Sawit Nusantara Berhad. Use the Yield by Estate, FFB Production Log, and MSPO Compliance Log sheets in PLT_01_Estate_Operations.xlsx together with PLT_02_MSPO_Certification_Manual.docx and PLT_03_Estate_Operations_SOP.docx. Brief the leadership team on plantation performance, certification readiness, and market-access risk, and separate the immediate operating gaps, control gaps, and stakeholder exposure that could escalate with MPOB and BPDPKS or premium export buyers. Present the answer as a RAG table with columns Risk, Evidence, 30-Day Action, and Owner.',
        'You are the Head of Estate Operations at Seri Sawit Nusantara Berhad. Use the FFB Production Log, Labour Productivity, and Yield by Estate sheets in PLT_01_Estate_Operations.xlsx together with PLT_03_Estate_Operations_SOP.docx. Diagnose which areas are recoverable within one quarter, which need management intervention now, and which should be paused until controls in the operating documents are tightened. Present the answer as a RAG heat map with the unit or workstream, the leading indicator, the root cause, and the next action.',
        'You are the Commercial Director at Seri Sawit Nusantara Berhad. Use the CPO Price Tracker, MSPO Compliance Log, and Labour Productivity sheets in PLT_01_Estate_Operations.xlsx together with PLT_02_MSPO_Certification_Manual.docx and PLT_03_Estate_Operations_SOP.docx. Prepare decision-quality talking points for the Board, EU buyers, and estate managers that distinguish what management can commit today, what depends on milestones, and what should be disclosed carefully. Present the answer as a RAG message matrix with audience, key message, evidence source, and approval owner.'
      ]),
      tool(T_RESEARCHER, FREE_LIC, FREE_ACCT, [
        'You are the Chief Sustainability Officer at Seri Sawit Nusantara Berhad. Research how organisations in Malaysia and Indonesia have handled plantation performance, certification readiness, and market-access risk since 2023, with explicit attention to guidance from MPOB and BPDPKS that would affect the Yield by Estate and MSPO Compliance Log sheets and PLT_02_MSPO_Certification_Manual.docx. Distinguish mandatory expectations, market practice, and peer tactics that management could apply to sustainability recovery and yield restoration. Present the findings as a RAG benchmark table with columns Theme, Malaysia, Indonesia, Evidence Source, and Management Implication. Flag any claim that could not be independently verified.',
        'You are the Head of Estate Operations at Seri Sawit Nusantara Berhad. Research the highest-impact operational levers that comparable teams have used to improve the indicators tracked in the FFB Production Log, Labour Productivity, and CPO Price Tracker sheets. Prioritise published case studies, association guidance, or regulator commentary that would be credible in front of the Board, EU buyers, and estate managers. Present the findings as a RAG table with Intervention, Expected Benefit, Time to Impact, and Evidence Strength. Flag any claim that could not be independently verified.',
        'You are the Commercial Director at Seri Sawit Nusantara Berhad. Research what investors, customers, sponsors, or regulators typically expect to see when management is trying to stabilise plantation performance, certification readiness, and market-access risk, using examples that align with PLT_02_MSPO_Certification_Manual.docx and PLT_03_Estate_Operations_SOP.docx. Highlight what leading teams communicate in the first 30 days, 60 days, and 90 days so the messaging is defensible with premium export buyers. Present the findings as a RAG roadmap with Time Horizon, Expected Action, External Signal, and Practical Implication. Flag any claim that could not be independently verified.'
      ], DESC_RESEARCHER),
      tool(T_ANALYST, M365_LIC, M365_ACCT, [
        'You are the Chief Sustainability Officer at Seri Sawit Nusantara Berhad. Upload PLT_01_Estate_Operations.xlsx to Analyst and use the Yield by Estate, FFB Production Log, and CPO Price Tracker sheets to quantify where current performance is deviating from plan. Estimate the financial, service, or programme impact of each gap and highlight which areas are most material to sustainability recovery and yield restoration. Present the output as a RAG table with Metric, Current Position, Gap, Impact Estimate, and Recommended Action.',
        'You are the Head of Estate Operations at Seri Sawit Nusantara Berhad. Upload PLT_01_Estate_Operations.xlsx and PLT_02_MSPO_Certification_Manual.docx to Analyst, then cross-reference the FFB Production Log, Labour Productivity, and MSPO Compliance Log sheets against the control expectations in the document. Identify the hotspots where weak execution and weak governance are reinforcing each other and rank them by urgency. Present the answer as a RAG heat map with Area, Root Cause, Evidence, Escalation Risk, and Owner.',
        'You are the Commercial Director at Seri Sawit Nusantara Berhad. Upload PLT_01_Estate_Operations.xlsx to Analyst and build a forward look from the CPO Price Tracker, Labour Productivity, and MSPO Compliance Log sheets for the next two quarters. Show the upside case, base case, and downside case for management if current trends continue versus if the highest-priority actions land on time. Present the result as a RAG scenario table with Scenario, Key Assumption, Expected Outcome, and Trigger for Escalation.'
      ], DESC_ANALYST),
      tool(T_EXCEL, M365_LIC, M365_ACCT, [
        "You are the Chief Sustainability Officer at Seri Sawit Nusantara Berhad. Using the Yield by Estate, CPO Price Tracker, and MSPO Compliance Log sheets in PLT_01_Estate_Operations.xlsx, create a new worksheet called 'Executive RAG Dashboard'. Show the core metrics that matter most to sustainability recovery and yield restoration, a short variance note, and a Red, Amber, or Green status for each metric. Design it so the first view is board-ready and the formulas refresh automatically when source values change.",
        "You are the Head of Estate Operations at Seri Sawit Nusantara Berhad. Using the FFB Production Log, Labour Productivity, and CPO Price Tracker sheets in PLT_01_Estate_Operations.xlsx, create a new worksheet called 'Recovery Scenarios'. Model what happens if management closes half the current gap within one quarter versus if the trend deteriorates by another 10 percent. Present the result as a RAG scenario model with assumptions, impact, and recommended management response.",
        "You are the Commercial Director at Seri Sawit Nusantara Berhad. Using the MSPO Compliance Log, Yield by Estate, and Labour Productivity sheets in PLT_01_Estate_Operations.xlsx, create a new worksheet called 'Action Tracker'. List the highest-priority actions, the metric each action should move, the target date, and the owner that estate and mill managers should hold accountable. Make the tracker a RAG control sheet with overdue items highlighted automatically."
      ]),
      tool(T_WORD, M365_LIC, M365_ACCT, [
        'You are the Chief Sustainability Officer at Seri Sawit Nusantara Berhad. Use PLT_02_MSPO_Certification_Manual.docx together with the Yield by Estate and MSPO Compliance Log sheets in PLT_01_Estate_Operations.xlsx to draft a 2-page Board memo. Explain the current position, the governance or policy implications, and the decisions required to stabilise plantation performance, certification readiness, and market-access risk. Start with a short RAG summary and end with a 30-day action table.',
        'You are the Head of Estate Operations at Seri Sawit Nusantara Berhad. Use PLT_03_Estate_Operations_SOP.docx together with the FFB Production Log and Labour Productivity sheets in PLT_01_Estate_Operations.xlsx to draft a stakeholder-ready note for premium export buyers. Make the narrative analytical rather than promotional, and distinguish what is already evidenced in the files from what is still being validated. Present the note with a RAG section on commitments, dependencies, and unresolved risks.',
        'You are the Commercial Director at Seri Sawit Nusantara Berhad. Use PLT_02_MSPO_Certification_Manual.docx and PLT_03_Estate_Operations_SOP.docx together with the CPO Price Tracker and MSPO Compliance Log sheets in PLT_01_Estate_Operations.xlsx to draft a 90-day operating action plan for estate and mill managers. Show how management should sequence the work so quick wins support the longer-control fixes needed for sustainability recovery and yield restoration. Present the plan as a RAG table with Week, Action, Dependency, and Success Measure.'
      ]),
      tool(T_PPT, M365_LIC, M365_ACCT, [
        'You are the Chief Sustainability Officer at Seri Sawit Nusantara Berhad. Create a 6-slide executive deck using PLT_01_Estate_Operations.xlsx, PLT_02_MSPO_Certification_Manual.docx, and PLT_03_Estate_Operations_SOP.docx as the source context. Cover the current position, the most material gaps, the implications for the Board, EU buyers, and estate managers, the stabilisation plan, the financial or delivery outlook, and the decisions required this month. Give each slide a headline with a RAG status and keep the layout tight enough for a board review.',
        'You are the Head of Estate Operations at Seri Sawit Nusantara Berhad. Create a 3-slide update pack for premium export buyers using the Yield by Estate, CPO Price Tracker, and MSPO Compliance Log sheets and PLT_02_MSPO_Certification_Manual.docx. Slide 1 should summarise the issue, slide 2 should show evidence-backed progress, and slide 3 should state the next milestone commitments. Add a RAG ribbon to each slide so the risk posture is obvious at a glance.',
        'You are the Commercial Director at Seri Sawit Nusantara Berhad. Create a single heat-map slide from the FFB Production Log, Labour Productivity, and MSPO Compliance Log sheets in PLT_01_Estate_Operations.xlsx. Show which business units, processes, regions, or workstreams are Red, Amber, or Green and note the one action that would most likely move each Red area back to Amber. Use an executive style and include a short legend that ties the colours to management action.'
      ]),
      tool(T_OUTLOOK, M365_LIC, M365_ACCT, [
        'You are the Chief Sustainability Officer at Seri Sawit Nusantara Berhad. Draft an external email to premium export buyers using the evidence in PLT_02_MSPO_Certification_Manual.docx and the Yield by Estate and MSPO Compliance Log sheets in PLT_01_Estate_Operations.xlsx. Acknowledge the issue directly, explain what is already under way, and avoid promising outcomes that depend on unresolved milestones or approvals. Keep the message concise and end with a RAG summary of what is confirmed, in progress, and still under review.',
        'You are the Head of Estate Operations at Seri Sawit Nusantara Berhad. Draft an internal war-room email for estate and mill managers that references the FFB Production Log, Labour Productivity, and MSPO Compliance Log sheets in PLT_01_Estate_Operations.xlsx and the responsibilities in PLT_03_Estate_Operations_SOP.docx. State the three priorities for the next seven days, who owns each one, and what evidence must be ready for the leadership review. Present the bottom section as a RAG checklist so owners can act immediately.',
        'You are the Commercial Director at Seri Sawit Nusantara Berhad. Draft a steering-committee email that summarises the latest position using the CPO Price Tracker and Yield by Estate sheets in PLT_01_Estate_Operations.xlsx. Highlight the decision required, the dependency that could block it, and the single biggest risk if the meeting slips by two weeks. Close with a RAG decision box showing approve now, approve with conditions, or hold.'
      ]),
      tool(T_TEAMS, M365_LIC, M365_ACCT, [
        'You are the Chief Sustainability Officer at Seri Sawit Nusantara Berhad. Use this recorded Teams meeting recap and cross-check it against the Yield by Estate and MSPO Compliance Log sheets in PLT_01_Estate_Operations.xlsx and PLT_02_MSPO_Certification_Manual.docx. Extract every action item, owner, and deadline that matters to sustainability recovery and yield restoration, and identify where the conversation is not supported by the latest file evidence. Present the result as a RAG action register with columns Action, Owner, Due Date, Evidence Check, and Escalation Risk.',
        'You are the Head of Estate Operations at Seri Sawit Nusantara Berhad. Use this recorded Teams meeting recap and compare the discussion with the FFB Production Log, Labour Productivity, and MSPO Compliance Log sheets in PLT_01_Estate_Operations.xlsx. Identify the top risks raised, what mitigation was proposed, and whether the control expectations in PLT_03_Estate_Operations_SOP.docx were fully addressed. Present the result as a RAG risk log with Risk, Evidence, Proposed Mitigation, and Decision Owner.',
        'You are the Commercial Director at Seri Sawit Nusantara Berhad. Use this recorded Teams meeting recap and reconcile it with the CPO Price Tracker and Yield by Estate sheets in PLT_01_Estate_Operations.xlsx. Separate decisions already taken, decisions that are still open, and assumptions that need independent validation before management can communicate externally. Present the result as a RAG decisions table with Decision, Current Status, Dependency, and Recommended Next Step.'
      ], DESC_TEAMS),
      tool(T_NOTEBOOK, M365_LIC, M365_ACCT, [
        "You are the Chief Sustainability Officer at Seri Sawit Nusantara Berhad. Upload PLT_01_Estate_Operations.xlsx, PLT_02_MSPO_Certification_Manual.docx, and PLT_03_Estate_Operations_SOP.docx to Copilot Notebook. Set the notebook instruction to: 'Synthesize evidence across all files, cite the exact file and sheet name for every major claim, and focus on sustainability recovery and yield restoration.' Ask for a RAG executive synthesis with the current position, the root causes, the key dependencies, and the next three decisions management should take.",
        'You are the Head of Estate Operations at Seri Sawit Nusantara Berhad. Upload PLT_01_Estate_Operations.xlsx, PLT_02_MSPO_Certification_Manual.docx, and PLT_03_Estate_Operations_SOP.docx to Copilot Notebook. Ask Notebook to reconcile what the workbook signals in the Yield by Estate, Labour Productivity, and MSPO Compliance Log sheets with the operating expectations in PLT_02_MSPO_Certification_Manual.docx and PLT_03_Estate_Operations_SOP.docx. Request a RAG table that shows where the documents and the live metrics align, conflict, or leave unanswered questions.',
        'You are the Commercial Director at Seri Sawit Nusantara Berhad. Upload PLT_01_Estate_Operations.xlsx, PLT_02_MSPO_Certification_Manual.docx, and PLT_03_Estate_Operations_SOP.docx to Copilot Notebook. Ask Notebook for a 30-60-90 day plan that balances quick wins with durable control fixes for plantation performance, certification readiness, and market-access risk, and make it explicit which actions depend on premium export buyers or regulator feedback. Request the answer as a RAG roadmap with citations to the exact source file and sheet name for every recommendation.'
      ], DESC_NOTEBOOK),
      tool(T_COWORK, M365_LIC, M365_ACCT, [
        'You are the Chief Sustainability Officer at Seri Sawit Nusantara Berhad. Research external benchmarks relevant to plantation performance, certification readiness, and market-access risk, then draft a 2-page brief grounded in PLT_02_MSPO_Certification_Manual.docx and the Yield by Estate and MSPO Compliance Log sheets in PLT_01_Estate_Operations.xlsx. Save the brief to OneDrive, email it to the leadership sponsors, and schedule a 30-minute review meeting with the owners who need to move sustainability recovery and yield restoration this week. Make the brief a RAG action pack with a one-line decision ask on the first page.',
        'You are the Head of Estate Operations at Seri Sawit Nusantara Berhad. Create a shared execution tracker from the FFB Production Log, Labour Productivity, and MSPO Compliance Log sheets in PLT_01_Estate_Operations.xlsx and the responsibilities described in PLT_03_Estate_Operations_SOP.docx. Email the tracker to estate and mill managers, ask each owner to confirm status by end of day, and schedule a recurring weekly checkpoint until the Red items are reduced. Make the tracker RAG-driven so overdue Red items are easy to escalate.'
      ], DESC_COWORK),
      tool(T_EDIT_COPILOT, M365_LIC, M365_ACCT, [
        "You are the Chief Sustainability Officer at Seri Sawit Nusantara Berhad. Using PLT_02_MSPO_Certification_Manual.docx in Word for the web, add a new section called 'Executive Recovery Controls' that aligns with the risks visible in the Yield by Estate and MSPO Compliance Log sheets in PLT_01_Estate_Operations.xlsx. Restructure the document so the most urgent controls appear first, tighten repetitive language, and add a RAG summary table for leadership at the top. Keep the tone consistent with the existing document and make every new control action specific enough to assign an owner.",
        "You are the Head of Estate Operations at Seri Sawit Nusantara Berhad. Using PLT_01_Estate_Operations.xlsx in Excel for the web, create or refine a sheet called 'Leadership Tracker' using the FFB Production Log, Labour Productivity, and MSPO Compliance Log sheets as source data. Reorder the columns so Red items appear first, standardise the formulas, and add a compact RAG summary block that updates automatically. Make the finished layout readable enough to paste into a leadership pack without manual cleanup."
      ], DESC_EDIT_COPILOT),
      tool(T_WORD_AGT, M365_LIC, M365_ACCT, [
        "You are the Chief Sustainability Officer at Seri Sawit Nusantara Berhad. In Word for the web, use PLT_02_MSPO_Certification_Manual.docx to create a new agent called 'Estate Governance Guide'. Describe it as an assistant that answers questions on plantation performance, certification readiness, and market-access risk, the control expectations in the document, and the decisions leaders need for sustainability recovery and yield restoration. Share it with estate and mill managers and make sure the welcome message explains the RAG logic it uses for prioritisation.",
        "You are the Head of Estate Operations at Seri Sawit Nusantara Berhad. Demo the 'Estate Governance Guide' agent with a question that references PLT_02_MSPO_Certification_Manual.docx and the Yield by Estate and MSPO Compliance Log sheets in PLT_01_Estate_Operations.xlsx. Ask the agent to explain the top Red issue, the control the document expects, and the owner who should respond first. Show the response as a concise RAG answer with a source citation."
      ], DESC_WORD_AGT),
      tool(T_PPT_AGT, M365_LIC, M365_ACCT, [
        "You are the Chief Sustainability Officer at Seri Sawit Nusantara Berhad. Create a PowerPoint briefing from PLT_01_Estate_Operations.xlsx, PLT_02_MSPO_Certification_Manual.docx, and PLT_03_Estate_Operations_SOP.docx, then create a new agent called 'Plantation Recovery Deck Guide'. Describe it as a deck navigator that helps leaders answer questions about plantation performance, certification readiness, and market-access risk, the major Red items, and the decisions required this month. Share it with the Board, EU buyers, and estate managers and configure the opening prompt to point users to the highest-risk slide first.",
        "You are the Commercial Director at Seri Sawit Nusantara Berhad. Demo the 'Plantation Recovery Deck Guide' agent by asking which slide best explains the current Red items from the Yield by Estate, CPO Price Tracker, and MSPO Compliance Log sheets in PLT_01_Estate_Operations.xlsx. Then ask for a 60-second RAG summary of the story the presenter should tell to premium export buyers. Require the answer to cite the slide topic it is drawing from."
      ], DESC_PPT_AGT),
      tool(T_XL_AGT, M365_LIC, M365_ACCT, [
        "You are the Chief Sustainability Officer at Seri Sawit Nusantara Berhad. In Excel for the web, use PLT_01_Estate_Operations.xlsx to create a new agent called 'Estate Performance Q&A'. Describe it as an assistant that answers questions on the Yield by Estate, FFB Production Log, CPO Price Tracker, Labour Productivity, and MSPO Compliance Log sheets and translates workbook signals into RAG-ready management insight for sustainability recovery and yield restoration. Share it with estate and mill managers and set the starter prompt to surface the top Red metrics automatically.",
        "You are the Head of Estate Operations at Seri Sawit Nusantara Berhad. Demo the 'Estate Performance Q&A' agent by asking which indicators in the Yield by Estate, Labour Productivity, and MSPO Compliance Log sheets are currently Red and what action would most likely move each one to Amber. Then ask for the single metric management should watch weekly if it can only track one item. Require the reply to be a RAG summary that names the exact sheet for every answer."
      ], DESC_XL_AGT),
      tool(T_BUILDER, M365_LIC, M365_ACCT, [
        "You are the Chief Sustainability Officer at Seri Sawit Nusantara Berhad. Go to Copilot Studio and create a new agent called 'Seri Sawit Ops Copilot' using PLT_01_Estate_Operations.xlsx, PLT_02_MSPO_Certification_Manual.docx, and PLT_03_Estate_Operations_SOP.docx as knowledge sources. Describe it as an assistant for the Board, EU buyers, and estate managers that supports sustainability recovery and yield restoration, add the topics Estate Yield, MSPO Readiness, Traceability Controls, and Buyer Messaging, and publish it to Teams for the right audience. Make the starter prompts explicitly return Red, Amber, or Green recommendations when users ask for priorities.",
        "You are the Commercial Director at Seri Sawit Nusantara Berhad. Demo the 'Seri Sawit Ops Copilot' agent with a question that combines the Yield by Estate, CPO Price Tracker, and MSPO Compliance Log sheets in PLT_01_Estate_Operations.xlsx with the policy direction in PLT_02_MSPO_Certification_Manual.docx. Ask for the top Red issue, the fastest Amber recovery action, and the Green area management should preserve while sustainability recovery and yield restoration is under way. Require the answer to cite the file evidence it used for each RAG judgement."
      ], DESC_BUILDER),
    ],
    companyID='PT Sawit Lestari Kalimantan Tbk',
    taglineID='Produktivitas melemah dan temuan sertifikasi mengancam kontrak ekspor premium.'),

# ── BPO SERVICES ───────────────────────────────────────────────────────────
ind('bpo-services', 'technology', 'BPO Services', '🖥', '#01579B', '#0277BD',
    'Pacific Axis Services Berhad',
    'Attrition and SLA drift are threatening anchor-client renewals.',
    'Pacific Axis Services Berhad runs multilingual delivery centres serving banking, insurance, and consumer clients across Southeast Asia. Leadership is trying to stabilise service levels while attrition, uneven utilisation, and margin pressure are pushing client renewals into a higher-risk category. The executive committee needs a sharper recovery plan that links workforce actions to measurable client outcomes.',
    ['BPO_01_Service_Delivery.xlsx', 'BPO_02_Client_Service_Agreement.docx', 'BPO_03_Quality_Management_Framework.docx'],
    [
      tool(T_CHAT, FREE_LIC, FREE_ACCT, [
        'You are the Managing Director at Pacific Axis Services Berhad. Use the SLA Dashboard, Headcount Utilisation, and Attrition Monitor sheets in BPO_01_Service_Delivery.xlsx together with BPO_02_Client_Service_Agreement.docx and BPO_03_Quality_Management_Framework.docx. Brief the leadership team on service delivery stability, workforce retention, and client revenue protection, and separate the immediate operating gaps, control gaps, and stakeholder exposure that could escalate with MDEC and Komdigi or anchor clients. Present the answer as a RAG table with columns Risk, Evidence, 30-Day Action, and Owner.',
        'You are the Head of Service Delivery at Pacific Axis Services Berhad. Use the Headcount Utilisation, Process KPIs, and SLA Dashboard sheets in BPO_01_Service_Delivery.xlsx together with BPO_03_Quality_Management_Framework.docx. Diagnose which areas are recoverable within one quarter, which need management intervention now, and which should be paused until controls in the operating documents are tightened. Present the answer as a RAG heat map with the unit or workstream, the leading indicator, the root cause, and the next action.',
        'You are the Client Success Director at Pacific Axis Services Berhad. Use the Client Revenue Tracker, Attrition Monitor, and Process KPIs sheets in BPO_01_Service_Delivery.xlsx together with BPO_02_Client_Service_Agreement.docx and BPO_03_Quality_Management_Framework.docx. Prepare decision-quality talking points for the executive committee, anchor clients, and delivery managers that distinguish what management can commit today, what depends on milestones, and what should be disclosed carefully. Present the answer as a RAG message matrix with audience, key message, evidence source, and approval owner.'
      ]),
      tool(T_RESEARCHER, FREE_LIC, FREE_ACCT, [
        'You are the Managing Director at Pacific Axis Services Berhad. Research how organisations in Malaysia and Indonesia have handled service delivery stability, workforce retention, and client revenue protection since 2023, with explicit attention to guidance from MDEC and Komdigi that would affect the SLA Dashboard and Attrition Monitor sheets and BPO_02_Client_Service_Agreement.docx. Distinguish mandatory expectations, market practice, and peer tactics that management could apply to service recovery and workforce stability. Present the findings as a RAG benchmark table with columns Theme, Malaysia, Indonesia, Evidence Source, and Management Implication. Flag any claim that could not be independently verified.',
        'You are the Head of Service Delivery at Pacific Axis Services Berhad. Research the highest-impact operational levers that comparable teams have used to improve the indicators tracked in the Headcount Utilisation, Process KPIs, and Client Revenue Tracker sheets. Prioritise published case studies, association guidance, or regulator commentary that would be credible in front of the executive committee, anchor clients, and delivery managers. Present the findings as a RAG table with Intervention, Expected Benefit, Time to Impact, and Evidence Strength. Flag any claim that could not be independently verified.',
        'You are the Client Success Director at Pacific Axis Services Berhad. Research what investors, customers, sponsors, or regulators typically expect to see when management is trying to stabilise service delivery stability, workforce retention, and client revenue protection, using examples that align with BPO_02_Client_Service_Agreement.docx and BPO_03_Quality_Management_Framework.docx. Highlight what leading teams communicate in the first 30 days, 60 days, and 90 days so the messaging is defensible with anchor clients. Present the findings as a RAG roadmap with Time Horizon, Expected Action, External Signal, and Practical Implication. Flag any claim that could not be independently verified.'
      ], DESC_RESEARCHER),
      tool(T_ANALYST, M365_LIC, M365_ACCT, [
        'You are the Managing Director at Pacific Axis Services Berhad. Upload BPO_01_Service_Delivery.xlsx to Analyst and use the SLA Dashboard, Headcount Utilisation, and Client Revenue Tracker sheets to quantify where current performance is deviating from plan. Estimate the financial, service, or programme impact of each gap and highlight which areas are most material to service recovery and workforce stability. Present the output as a RAG table with Metric, Current Position, Gap, Impact Estimate, and Recommended Action.',
        'You are the Head of Service Delivery at Pacific Axis Services Berhad. Upload BPO_01_Service_Delivery.xlsx and BPO_02_Client_Service_Agreement.docx to Analyst, then cross-reference the Headcount Utilisation, Process KPIs, and Attrition Monitor sheets against the control expectations in the document. Identify the hotspots where weak execution and weak governance are reinforcing each other and rank them by urgency. Present the answer as a RAG heat map with Area, Root Cause, Evidence, Escalation Risk, and Owner.',
        'You are the Client Success Director at Pacific Axis Services Berhad. Upload BPO_01_Service_Delivery.xlsx to Analyst and build a forward look from the Client Revenue Tracker, Process KPIs, and Attrition Monitor sheets for the next two quarters. Show the upside case, base case, and downside case for management if current trends continue versus if the highest-priority actions land on time. Present the result as a RAG scenario table with Scenario, Key Assumption, Expected Outcome, and Trigger for Escalation.'
      ], DESC_ANALYST),
      tool(T_EXCEL, M365_LIC, M365_ACCT, [
        "You are the Managing Director at Pacific Axis Services Berhad. Using the SLA Dashboard, Client Revenue Tracker, and Attrition Monitor sheets in BPO_01_Service_Delivery.xlsx, create a new worksheet called 'Executive RAG Dashboard'. Show the core metrics that matter most to service recovery and workforce stability, a short variance note, and a Red, Amber, or Green status for each metric. Design it so the first view is board-ready and the formulas refresh automatically when source values change.",
        "You are the Head of Service Delivery at Pacific Axis Services Berhad. Using the Headcount Utilisation, Process KPIs, and Client Revenue Tracker sheets in BPO_01_Service_Delivery.xlsx, create a new worksheet called 'Recovery Scenarios'. Model what happens if management closes half the current gap within one quarter versus if the trend deteriorates by another 10 percent. Present the result as a RAG scenario model with assumptions, impact, and recommended management response.",
        "You are the Client Success Director at Pacific Axis Services Berhad. Using the Attrition Monitor, SLA Dashboard, and Process KPIs sheets in BPO_01_Service_Delivery.xlsx, create a new worksheet called 'Action Tracker'. List the highest-priority actions, the metric each action should move, the target date, and the owner that delivery and HR leads should hold accountable. Make the tracker a RAG control sheet with overdue items highlighted automatically."
      ]),
      tool(T_WORD, M365_LIC, M365_ACCT, [
        'You are the Managing Director at Pacific Axis Services Berhad. Use BPO_02_Client_Service_Agreement.docx together with the SLA Dashboard and Attrition Monitor sheets in BPO_01_Service_Delivery.xlsx to draft a 2-page Executive committee memo. Explain the current position, the governance or policy implications, and the decisions required to stabilise service delivery stability, workforce retention, and client revenue protection. Start with a short RAG summary and end with a 30-day action table.',
        'You are the Head of Service Delivery at Pacific Axis Services Berhad. Use BPO_03_Quality_Management_Framework.docx together with the Headcount Utilisation and Process KPIs sheets in BPO_01_Service_Delivery.xlsx to draft a stakeholder-ready note for anchor clients. Make the narrative analytical rather than promotional, and distinguish what is already evidenced in the files from what is still being validated. Present the note with a RAG section on commitments, dependencies, and unresolved risks.',
        'You are the Client Success Director at Pacific Axis Services Berhad. Use BPO_02_Client_Service_Agreement.docx and BPO_03_Quality_Management_Framework.docx together with the Client Revenue Tracker and Attrition Monitor sheets in BPO_01_Service_Delivery.xlsx to draft a 90-day operating action plan for delivery and HR leads. Show how management should sequence the work so quick wins support the longer-control fixes needed for service recovery and workforce stability. Present the plan as a RAG table with Week, Action, Dependency, and Success Measure.'
      ]),
      tool(T_PPT, M365_LIC, M365_ACCT, [
        'You are the Managing Director at Pacific Axis Services Berhad. Create a 6-slide executive deck using BPO_01_Service_Delivery.xlsx, BPO_02_Client_Service_Agreement.docx, and BPO_03_Quality_Management_Framework.docx as the source context. Cover the current position, the most material gaps, the implications for the executive committee, anchor clients, and delivery managers, the stabilisation plan, the financial or delivery outlook, and the decisions required this month. Give each slide a headline with a RAG status and keep the layout tight enough for a board review.',
        'You are the Head of Service Delivery at Pacific Axis Services Berhad. Create a 3-slide update pack for anchor clients using the SLA Dashboard, Client Revenue Tracker, and Attrition Monitor sheets and BPO_02_Client_Service_Agreement.docx. Slide 1 should summarise the issue, slide 2 should show evidence-backed progress, and slide 3 should state the next milestone commitments. Add a RAG ribbon to each slide so the risk posture is obvious at a glance.',
        'You are the Client Success Director at Pacific Axis Services Berhad. Create a single heat-map slide from the Headcount Utilisation, Process KPIs, and Attrition Monitor sheets in BPO_01_Service_Delivery.xlsx. Show which business units, processes, regions, or workstreams are Red, Amber, or Green and note the one action that would most likely move each Red area back to Amber. Use an executive style and include a short legend that ties the colours to management action.'
      ]),
      tool(T_OUTLOOK, M365_LIC, M365_ACCT, [
        'You are the Managing Director at Pacific Axis Services Berhad. Draft an external email to anchor clients using the evidence in BPO_02_Client_Service_Agreement.docx and the SLA Dashboard and Attrition Monitor sheets in BPO_01_Service_Delivery.xlsx. Acknowledge the issue directly, explain what is already under way, and avoid promising outcomes that depend on unresolved milestones or approvals. Keep the message concise and end with a RAG summary of what is confirmed, in progress, and still under review.',
        'You are the Head of Service Delivery at Pacific Axis Services Berhad. Draft an internal war-room email for delivery and HR leads that references the Headcount Utilisation, Process KPIs, and Attrition Monitor sheets in BPO_01_Service_Delivery.xlsx and the responsibilities in BPO_03_Quality_Management_Framework.docx. State the three priorities for the next seven days, who owns each one, and what evidence must be ready for the leadership review. Present the bottom section as a RAG checklist so owners can act immediately.',
        'You are the Client Success Director at Pacific Axis Services Berhad. Draft a steering-committee email that summarises the latest position using the Client Revenue Tracker and SLA Dashboard sheets in BPO_01_Service_Delivery.xlsx. Highlight the decision required, the dependency that could block it, and the single biggest risk if the meeting slips by two weeks. Close with a RAG decision box showing approve now, approve with conditions, or hold.'
      ]),
      tool(T_TEAMS, M365_LIC, M365_ACCT, [
        'You are the Managing Director at Pacific Axis Services Berhad. Use this recorded Teams meeting recap and cross-check it against the SLA Dashboard and Attrition Monitor sheets in BPO_01_Service_Delivery.xlsx and BPO_02_Client_Service_Agreement.docx. Extract every action item, owner, and deadline that matters to service recovery and workforce stability, and identify where the conversation is not supported by the latest file evidence. Present the result as a RAG action register with columns Action, Owner, Due Date, Evidence Check, and Escalation Risk.',
        'You are the Head of Service Delivery at Pacific Axis Services Berhad. Use this recorded Teams meeting recap and compare the discussion with the Headcount Utilisation, Process KPIs, and Attrition Monitor sheets in BPO_01_Service_Delivery.xlsx. Identify the top risks raised, what mitigation was proposed, and whether the control expectations in BPO_03_Quality_Management_Framework.docx were fully addressed. Present the result as a RAG risk log with Risk, Evidence, Proposed Mitigation, and Decision Owner.',
        'You are the Client Success Director at Pacific Axis Services Berhad. Use this recorded Teams meeting recap and reconcile it with the Client Revenue Tracker and SLA Dashboard sheets in BPO_01_Service_Delivery.xlsx. Separate decisions already taken, decisions that are still open, and assumptions that need independent validation before management can communicate externally. Present the result as a RAG decisions table with Decision, Current Status, Dependency, and Recommended Next Step.'
      ], DESC_TEAMS),
      tool(T_NOTEBOOK, M365_LIC, M365_ACCT, [
        "You are the Managing Director at Pacific Axis Services Berhad. Upload BPO_01_Service_Delivery.xlsx, BPO_02_Client_Service_Agreement.docx, and BPO_03_Quality_Management_Framework.docx to Copilot Notebook. Set the notebook instruction to: 'Synthesize evidence across all files, cite the exact file and sheet name for every major claim, and focus on service recovery and workforce stability.' Ask for a RAG executive synthesis with the current position, the root causes, the key dependencies, and the next three decisions management should take.",
        'You are the Head of Service Delivery at Pacific Axis Services Berhad. Upload BPO_01_Service_Delivery.xlsx, BPO_02_Client_Service_Agreement.docx, and BPO_03_Quality_Management_Framework.docx to Copilot Notebook. Ask Notebook to reconcile what the workbook signals in the SLA Dashboard, Process KPIs, and Attrition Monitor sheets with the operating expectations in BPO_02_Client_Service_Agreement.docx and BPO_03_Quality_Management_Framework.docx. Request a RAG table that shows where the documents and the live metrics align, conflict, or leave unanswered questions.',
        'You are the Client Success Director at Pacific Axis Services Berhad. Upload BPO_01_Service_Delivery.xlsx, BPO_02_Client_Service_Agreement.docx, and BPO_03_Quality_Management_Framework.docx to Copilot Notebook. Ask Notebook for a 30-60-90 day plan that balances quick wins with durable control fixes for service delivery stability, workforce retention, and client revenue protection, and make it explicit which actions depend on anchor clients or regulator feedback. Request the answer as a RAG roadmap with citations to the exact source file and sheet name for every recommendation.'
      ], DESC_NOTEBOOK),
      tool(T_COWORK, M365_LIC, M365_ACCT, [
        'You are the Managing Director at Pacific Axis Services Berhad. Research external benchmarks relevant to service delivery stability, workforce retention, and client revenue protection, then draft a 2-page brief grounded in BPO_02_Client_Service_Agreement.docx and the SLA Dashboard and Attrition Monitor sheets in BPO_01_Service_Delivery.xlsx. Save the brief to OneDrive, email it to the leadership sponsors, and schedule a 30-minute review meeting with the owners who need to move service recovery and workforce stability this week. Make the brief a RAG action pack with a one-line decision ask on the first page.',
        'You are the Head of Service Delivery at Pacific Axis Services Berhad. Create a shared execution tracker from the Headcount Utilisation, Process KPIs, and Attrition Monitor sheets in BPO_01_Service_Delivery.xlsx and the responsibilities described in BPO_03_Quality_Management_Framework.docx. Email the tracker to delivery and HR leads, ask each owner to confirm status by end of day, and schedule a recurring weekly checkpoint until the Red items are reduced. Make the tracker RAG-driven so overdue Red items are easy to escalate.'
      ], DESC_COWORK),
      tool(T_EDIT_COPILOT, M365_LIC, M365_ACCT, [
        "You are the Managing Director at Pacific Axis Services Berhad. Using BPO_02_Client_Service_Agreement.docx in Word for the web, add a new section called 'Executive Recovery Controls' that aligns with the risks visible in the SLA Dashboard and Attrition Monitor sheets in BPO_01_Service_Delivery.xlsx. Restructure the document so the most urgent controls appear first, tighten repetitive language, and add a RAG summary table for leadership at the top. Keep the tone consistent with the existing document and make every new control action specific enough to assign an owner.",
        "You are the Head of Service Delivery at Pacific Axis Services Berhad. Using BPO_01_Service_Delivery.xlsx in Excel for the web, create or refine a sheet called 'Leadership Tracker' using the Headcount Utilisation, Process KPIs, and Attrition Monitor sheets as source data. Reorder the columns so Red items appear first, standardise the formulas, and add a compact RAG summary block that updates automatically. Make the finished layout readable enough to paste into a leadership pack without manual cleanup."
      ], DESC_EDIT_COPILOT),
      tool(T_WORD_AGT, M365_LIC, M365_ACCT, [
        "You are the Managing Director at Pacific Axis Services Berhad. In Word for the web, use BPO_02_Client_Service_Agreement.docx to create a new agent called 'Service Governance Guide'. Describe it as an assistant that answers questions on service delivery stability, workforce retention, and client revenue protection, the control expectations in the document, and the decisions leaders need for service recovery and workforce stability. Share it with delivery and HR leads and make sure the welcome message explains the RAG logic it uses for prioritisation.",
        "You are the Head of Service Delivery at Pacific Axis Services Berhad. Demo the 'Service Governance Guide' agent with a question that references BPO_02_Client_Service_Agreement.docx and the SLA Dashboard and Attrition Monitor sheets in BPO_01_Service_Delivery.xlsx. Ask the agent to explain the top Red issue, the control the document expects, and the owner who should respond first. Show the response as a concise RAG answer with a source citation."
      ], DESC_WORD_AGT),
      tool(T_PPT_AGT, M365_LIC, M365_ACCT, [
        "You are the Managing Director at Pacific Axis Services Berhad. Create a PowerPoint briefing from BPO_01_Service_Delivery.xlsx, BPO_02_Client_Service_Agreement.docx, and BPO_03_Quality_Management_Framework.docx, then create a new agent called 'Client Recovery Deck Guide'. Describe it as a deck navigator that helps leaders answer questions about service delivery stability, workforce retention, and client revenue protection, the major Red items, and the decisions required this month. Share it with the executive committee, anchor clients, and delivery managers and configure the opening prompt to point users to the highest-risk slide first.",
        "You are the Client Success Director at Pacific Axis Services Berhad. Demo the 'Client Recovery Deck Guide' agent by asking which slide best explains the current Red items from the SLA Dashboard, Client Revenue Tracker, and Attrition Monitor sheets in BPO_01_Service_Delivery.xlsx. Then ask for a 60-second RAG summary of the story the presenter should tell to anchor clients. Require the answer to cite the slide topic it is drawing from."
      ], DESC_PPT_AGT),
      tool(T_XL_AGT, M365_LIC, M365_ACCT, [
        "You are the Managing Director at Pacific Axis Services Berhad. In Excel for the web, use BPO_01_Service_Delivery.xlsx to create a new agent called 'Delivery Performance Q&A'. Describe it as an assistant that answers questions on the SLA Dashboard, Headcount Utilisation, Client Revenue Tracker, Process KPIs, and Attrition Monitor sheets and translates workbook signals into RAG-ready management insight for service recovery and workforce stability. Share it with delivery and HR leads and set the starter prompt to surface the top Red metrics automatically.",
        "You are the Head of Service Delivery at Pacific Axis Services Berhad. Demo the 'Delivery Performance Q&A' agent by asking which indicators in the SLA Dashboard, Process KPIs, and Attrition Monitor sheets are currently Red and what action would most likely move each one to Amber. Then ask for the single metric management should watch weekly if it can only track one item. Require the reply to be a RAG summary that names the exact sheet for every answer."
      ], DESC_XL_AGT),
      tool(T_BUILDER, M365_LIC, M365_ACCT, [
        "You are the Managing Director at Pacific Axis Services Berhad. Go to Copilot Studio and create a new agent called 'Pacific Axis Delivery Copilot' using BPO_01_Service_Delivery.xlsx, BPO_02_Client_Service_Agreement.docx, and BPO_03_Quality_Management_Framework.docx as knowledge sources. Describe it as an assistant for the executive committee, anchor clients, and delivery managers that supports service recovery and workforce stability, add the topics SLA Recovery, Attrition Control, Client Profitability, and Quality Assurance, and publish it to Teams for the right audience. Make the starter prompts explicitly return Red, Amber, or Green recommendations when users ask for priorities.",
        "You are the Client Success Director at Pacific Axis Services Berhad. Demo the 'Pacific Axis Delivery Copilot' agent with a question that combines the SLA Dashboard, Client Revenue Tracker, and Attrition Monitor sheets in BPO_01_Service_Delivery.xlsx with the policy direction in BPO_02_Client_Service_Agreement.docx. Ask for the top Red issue, the fastest Amber recovery action, and the Green area management should preserve while service recovery and workforce stability is under way. Require the answer to cite the file evidence it used for each RAG judgement."
      ], DESC_BUILDER),
    ],
    companyID='PT Layanan Proses Andalan',
    taglineID='Attrisi dan penurunan SLA mengancam perpanjangan klien utama.'),

# ── TELECOMMUNICATIONS ─────────────────────────────────────────────────────
ind('telco', 'media-telco', 'Telecommunications', '📡', '#4A148C', '#6A1B9A',
    'Satria Jaringan Digital Berhad',
    'Coverage, churn, and capex discipline are off track before spectrum review.',
    'Satria Jaringan Digital Berhad is balancing network expansion, subscriber retention, and spectrum obligations in a highly competitive market. Coverage targets are slipping in several priority clusters while churn and ARPU pressure are eroding confidence in the current rollout plan. Management needs one fact-based narrative that ties network, commercial, and regulatory actions together before the next review with authorities.',
    ['TC_01_Network_Performance.xlsx', 'TC_02_Spectrum_Compliance_Report.docx', 'TC_03_Network_Rollout_Strategy.docx'],
    [
      tool(T_CHAT, FREE_LIC, FREE_ACCT, [
        'You are the Chief Technology Officer at Satria Jaringan Digital Berhad. Use the Network KPIs, Subscriber Metrics, and Capex Plan vs Actual sheets in TC_01_Network_Performance.xlsx together with TC_02_Spectrum_Compliance_Report.docx and TC_03_Network_Rollout_Strategy.docx. Brief the leadership team on network execution, subscriber retention, and regulatory compliance, and separate the immediate operating gaps, control gaps, and stakeholder exposure that could escalate with MCMC and Komdigi or the MCMC liaison team. Present the answer as a RAG table with columns Risk, Evidence, 30-Day Action, and Owner.',
        'You are the Chief Commercial Officer at Satria Jaringan Digital Berhad. Use the Subscriber Metrics, Churn Analysis, and Network KPIs sheets in TC_01_Network_Performance.xlsx together with TC_03_Network_Rollout_Strategy.docx. Diagnose which areas are recoverable within one quarter, which need management intervention now, and which should be paused until controls in the operating documents are tightened. Present the answer as a RAG heat map with the unit or workstream, the leading indicator, the root cause, and the next action.',
        'You are the Head of Regulatory Affairs at Satria Jaringan Digital Berhad. Use the ARPU Tracker, Capex Plan vs Actual, and Churn Analysis sheets in TC_01_Network_Performance.xlsx together with TC_02_Spectrum_Compliance_Report.docx and TC_03_Network_Rollout_Strategy.docx. Prepare decision-quality talking points for the Board, regulators, and commercial leadership that distinguish what management can commit today, what depends on milestones, and what should be disclosed carefully. Present the answer as a RAG message matrix with audience, key message, evidence source, and approval owner.'
      ]),
      tool(T_RESEARCHER, FREE_LIC, FREE_ACCT, [
        'You are the Chief Technology Officer at Satria Jaringan Digital Berhad. Research how organisations in Malaysia and Indonesia have handled network execution, subscriber retention, and regulatory compliance since 2023, with explicit attention to guidance from MCMC and Komdigi that would affect the Network KPIs and Capex Plan vs Actual sheets and TC_02_Spectrum_Compliance_Report.docx. Distinguish mandatory expectations, market practice, and peer tactics that management could apply to network recovery and churn control. Present the findings as a RAG benchmark table with columns Theme, Malaysia, Indonesia, Evidence Source, and Management Implication. Flag any claim that could not be independently verified.',
        'You are the Chief Commercial Officer at Satria Jaringan Digital Berhad. Research the highest-impact operational levers that comparable teams have used to improve the indicators tracked in the Subscriber Metrics, Churn Analysis, and ARPU Tracker sheets. Prioritise published case studies, association guidance, or regulator commentary that would be credible in front of the Board, regulators, and commercial leadership. Present the findings as a RAG table with Intervention, Expected Benefit, Time to Impact, and Evidence Strength. Flag any claim that could not be independently verified.',
        'You are the Head of Regulatory Affairs at Satria Jaringan Digital Berhad. Research what investors, customers, sponsors, or regulators typically expect to see when management is trying to stabilise network execution, subscriber retention, and regulatory compliance, using examples that align with TC_02_Spectrum_Compliance_Report.docx and TC_03_Network_Rollout_Strategy.docx. Highlight what leading teams communicate in the first 30 days, 60 days, and 90 days so the messaging is defensible with the MCMC liaison team. Present the findings as a RAG roadmap with Time Horizon, Expected Action, External Signal, and Practical Implication. Flag any claim that could not be independently verified.'
      ], DESC_RESEARCHER),
      tool(T_ANALYST, M365_LIC, M365_ACCT, [
        'You are the Chief Technology Officer at Satria Jaringan Digital Berhad. Upload TC_01_Network_Performance.xlsx to Analyst and use the Network KPIs, Subscriber Metrics, and ARPU Tracker sheets to quantify where current performance is deviating from plan. Estimate the financial, service, or programme impact of each gap and highlight which areas are most material to network recovery and churn control. Present the output as a RAG table with Metric, Current Position, Gap, Impact Estimate, and Recommended Action.',
        'You are the Chief Commercial Officer at Satria Jaringan Digital Berhad. Upload TC_01_Network_Performance.xlsx and TC_02_Spectrum_Compliance_Report.docx to Analyst, then cross-reference the Subscriber Metrics, Churn Analysis, and Capex Plan vs Actual sheets against the control expectations in the document. Identify the hotspots where weak execution and weak governance are reinforcing each other and rank them by urgency. Present the answer as a RAG heat map with Area, Root Cause, Evidence, Escalation Risk, and Owner.',
        'You are the Head of Regulatory Affairs at Satria Jaringan Digital Berhad. Upload TC_01_Network_Performance.xlsx to Analyst and build a forward look from the ARPU Tracker, Churn Analysis, and Capex Plan vs Actual sheets for the next two quarters. Show the upside case, base case, and downside case for management if current trends continue versus if the highest-priority actions land on time. Present the result as a RAG scenario table with Scenario, Key Assumption, Expected Outcome, and Trigger for Escalation.'
      ], DESC_ANALYST),
      tool(T_EXCEL, M365_LIC, M365_ACCT, [
        "You are the Chief Technology Officer at Satria Jaringan Digital Berhad. Using the Network KPIs, ARPU Tracker, and Capex Plan vs Actual sheets in TC_01_Network_Performance.xlsx, create a new worksheet called 'Executive RAG Dashboard'. Show the core metrics that matter most to network recovery and churn control, a short variance note, and a Red, Amber, or Green status for each metric. Design it so the first view is board-ready and the formulas refresh automatically when source values change.",
        "You are the Chief Commercial Officer at Satria Jaringan Digital Berhad. Using the Subscriber Metrics, Churn Analysis, and ARPU Tracker sheets in TC_01_Network_Performance.xlsx, create a new worksheet called 'Recovery Scenarios'. Model what happens if management closes half the current gap within one quarter versus if the trend deteriorates by another 10 percent. Present the result as a RAG scenario model with assumptions, impact, and recommended management response.",
        "You are the Head of Regulatory Affairs at Satria Jaringan Digital Berhad. Using the Capex Plan vs Actual, Network KPIs, and Churn Analysis sheets in TC_01_Network_Performance.xlsx, create a new worksheet called 'Action Tracker'. List the highest-priority actions, the metric each action should move, the target date, and the owner that network and commercial leads should hold accountable. Make the tracker a RAG control sheet with overdue items highlighted automatically."
      ]),
      tool(T_WORD, M365_LIC, M365_ACCT, [
        'You are the Chief Technology Officer at Satria Jaringan Digital Berhad. Use TC_02_Spectrum_Compliance_Report.docx together with the Network KPIs and Capex Plan vs Actual sheets in TC_01_Network_Performance.xlsx to draft a 2-page Board memo. Explain the current position, the governance or policy implications, and the decisions required to stabilise network execution, subscriber retention, and regulatory compliance. Start with a short RAG summary and end with a 30-day action table.',
        'You are the Chief Commercial Officer at Satria Jaringan Digital Berhad. Use TC_03_Network_Rollout_Strategy.docx together with the Subscriber Metrics and Churn Analysis sheets in TC_01_Network_Performance.xlsx to draft a stakeholder-ready note for the MCMC liaison team. Make the narrative analytical rather than promotional, and distinguish what is already evidenced in the files from what is still being validated. Present the note with a RAG section on commitments, dependencies, and unresolved risks.',
        'You are the Head of Regulatory Affairs at Satria Jaringan Digital Berhad. Use TC_02_Spectrum_Compliance_Report.docx and TC_03_Network_Rollout_Strategy.docx together with the ARPU Tracker and Capex Plan vs Actual sheets in TC_01_Network_Performance.xlsx to draft a 90-day operating action plan for network and commercial leads. Show how management should sequence the work so quick wins support the longer-control fixes needed for network recovery and churn control. Present the plan as a RAG table with Week, Action, Dependency, and Success Measure.'
      ]),
      tool(T_PPT, M365_LIC, M365_ACCT, [
        'You are the Chief Technology Officer at Satria Jaringan Digital Berhad. Create a 6-slide executive deck using TC_01_Network_Performance.xlsx, TC_02_Spectrum_Compliance_Report.docx, and TC_03_Network_Rollout_Strategy.docx as the source context. Cover the current position, the most material gaps, the implications for the Board, regulators, and commercial leadership, the stabilisation plan, the financial or delivery outlook, and the decisions required this month. Give each slide a headline with a RAG status and keep the layout tight enough for a board review.',
        'You are the Chief Commercial Officer at Satria Jaringan Digital Berhad. Create a 3-slide update pack for the MCMC liaison team using the Network KPIs, ARPU Tracker, and Capex Plan vs Actual sheets and TC_02_Spectrum_Compliance_Report.docx. Slide 1 should summarise the issue, slide 2 should show evidence-backed progress, and slide 3 should state the next milestone commitments. Add a RAG ribbon to each slide so the risk posture is obvious at a glance.',
        'You are the Head of Regulatory Affairs at Satria Jaringan Digital Berhad. Create a single heat-map slide from the Subscriber Metrics, Churn Analysis, and Capex Plan vs Actual sheets in TC_01_Network_Performance.xlsx. Show which business units, processes, regions, or workstreams are Red, Amber, or Green and note the one action that would most likely move each Red area back to Amber. Use an executive style and include a short legend that ties the colours to management action.'
      ]),
      tool(T_OUTLOOK, M365_LIC, M365_ACCT, [
        'You are the Chief Technology Officer at Satria Jaringan Digital Berhad. Draft an external email to the MCMC liaison team using the evidence in TC_02_Spectrum_Compliance_Report.docx and the Network KPIs and Capex Plan vs Actual sheets in TC_01_Network_Performance.xlsx. Acknowledge the issue directly, explain what is already under way, and avoid promising outcomes that depend on unresolved milestones or approvals. Keep the message concise and end with a RAG summary of what is confirmed, in progress, and still under review.',
        'You are the Chief Commercial Officer at Satria Jaringan Digital Berhad. Draft an internal war-room email for network and commercial leads that references the Subscriber Metrics, Churn Analysis, and Capex Plan vs Actual sheets in TC_01_Network_Performance.xlsx and the responsibilities in TC_03_Network_Rollout_Strategy.docx. State the three priorities for the next seven days, who owns each one, and what evidence must be ready for the leadership review. Present the bottom section as a RAG checklist so owners can act immediately.',
        'You are the Head of Regulatory Affairs at Satria Jaringan Digital Berhad. Draft a steering-committee email that summarises the latest position using the ARPU Tracker and Network KPIs sheets in TC_01_Network_Performance.xlsx. Highlight the decision required, the dependency that could block it, and the single biggest risk if the meeting slips by two weeks. Close with a RAG decision box showing approve now, approve with conditions, or hold.'
      ]),
      tool(T_TEAMS, M365_LIC, M365_ACCT, [
        'You are the Chief Technology Officer at Satria Jaringan Digital Berhad. Use this recorded Teams meeting recap and cross-check it against the Network KPIs and Capex Plan vs Actual sheets in TC_01_Network_Performance.xlsx and TC_02_Spectrum_Compliance_Report.docx. Extract every action item, owner, and deadline that matters to network recovery and churn control, and identify where the conversation is not supported by the latest file evidence. Present the result as a RAG action register with columns Action, Owner, Due Date, Evidence Check, and Escalation Risk.',
        'You are the Chief Commercial Officer at Satria Jaringan Digital Berhad. Use this recorded Teams meeting recap and compare the discussion with the Subscriber Metrics, Churn Analysis, and Capex Plan vs Actual sheets in TC_01_Network_Performance.xlsx. Identify the top risks raised, what mitigation was proposed, and whether the control expectations in TC_03_Network_Rollout_Strategy.docx were fully addressed. Present the result as a RAG risk log with Risk, Evidence, Proposed Mitigation, and Decision Owner.',
        'You are the Head of Regulatory Affairs at Satria Jaringan Digital Berhad. Use this recorded Teams meeting recap and reconcile it with the ARPU Tracker and Network KPIs sheets in TC_01_Network_Performance.xlsx. Separate decisions already taken, decisions that are still open, and assumptions that need independent validation before management can communicate externally. Present the result as a RAG decisions table with Decision, Current Status, Dependency, and Recommended Next Step.'
      ], DESC_TEAMS),
      tool(T_NOTEBOOK, M365_LIC, M365_ACCT, [
        "You are the Chief Technology Officer at Satria Jaringan Digital Berhad. Upload TC_01_Network_Performance.xlsx, TC_02_Spectrum_Compliance_Report.docx, and TC_03_Network_Rollout_Strategy.docx to Copilot Notebook. Set the notebook instruction to: 'Synthesize evidence across all files, cite the exact file and sheet name for every major claim, and focus on network recovery and churn control.' Ask for a RAG executive synthesis with the current position, the root causes, the key dependencies, and the next three decisions management should take.",
        'You are the Chief Commercial Officer at Satria Jaringan Digital Berhad. Upload TC_01_Network_Performance.xlsx, TC_02_Spectrum_Compliance_Report.docx, and TC_03_Network_Rollout_Strategy.docx to Copilot Notebook. Ask Notebook to reconcile what the workbook signals in the Network KPIs, Churn Analysis, and Capex Plan vs Actual sheets with the operating expectations in TC_02_Spectrum_Compliance_Report.docx and TC_03_Network_Rollout_Strategy.docx. Request a RAG table that shows where the documents and the live metrics align, conflict, or leave unanswered questions.',
        'You are the Head of Regulatory Affairs at Satria Jaringan Digital Berhad. Upload TC_01_Network_Performance.xlsx, TC_02_Spectrum_Compliance_Report.docx, and TC_03_Network_Rollout_Strategy.docx to Copilot Notebook. Ask Notebook for a 30-60-90 day plan that balances quick wins with durable control fixes for network execution, subscriber retention, and regulatory compliance, and make it explicit which actions depend on the MCMC liaison team or regulator feedback. Request the answer as a RAG roadmap with citations to the exact source file and sheet name for every recommendation.'
      ], DESC_NOTEBOOK),
      tool(T_COWORK, M365_LIC, M365_ACCT, [
        'You are the Chief Technology Officer at Satria Jaringan Digital Berhad. Research external benchmarks relevant to network execution, subscriber retention, and regulatory compliance, then draft a 2-page brief grounded in TC_02_Spectrum_Compliance_Report.docx and the Network KPIs and Capex Plan vs Actual sheets in TC_01_Network_Performance.xlsx. Save the brief to OneDrive, email it to the leadership sponsors, and schedule a 30-minute review meeting with the owners who need to move network recovery and churn control this week. Make the brief a RAG action pack with a one-line decision ask on the first page.',
        'You are the Chief Commercial Officer at Satria Jaringan Digital Berhad. Create a shared execution tracker from the Subscriber Metrics, Churn Analysis, and Capex Plan vs Actual sheets in TC_01_Network_Performance.xlsx and the responsibilities described in TC_03_Network_Rollout_Strategy.docx. Email the tracker to network and commercial leads, ask each owner to confirm status by end of day, and schedule a recurring weekly checkpoint until the Red items are reduced. Make the tracker RAG-driven so overdue Red items are easy to escalate.'
      ], DESC_COWORK),
      tool(T_EDIT_COPILOT, M365_LIC, M365_ACCT, [
        "You are the Chief Technology Officer at Satria Jaringan Digital Berhad. Using TC_02_Spectrum_Compliance_Report.docx in Word for the web, add a new section called 'Executive Recovery Controls' that aligns with the risks visible in the Network KPIs and Capex Plan vs Actual sheets in TC_01_Network_Performance.xlsx. Restructure the document so the most urgent controls appear first, tighten repetitive language, and add a RAG summary table for leadership at the top. Keep the tone consistent with the existing document and make every new control action specific enough to assign an owner.",
        "You are the Chief Commercial Officer at Satria Jaringan Digital Berhad. Using TC_01_Network_Performance.xlsx in Excel for the web, create or refine a sheet called 'Leadership Tracker' using the Subscriber Metrics, Churn Analysis, and Capex Plan vs Actual sheets as source data. Reorder the columns so Red items appear first, standardise the formulas, and add a compact RAG summary block that updates automatically. Make the finished layout readable enough to paste into a leadership pack without manual cleanup."
      ], DESC_EDIT_COPILOT),
      tool(T_WORD_AGT, M365_LIC, M365_ACCT, [
        "You are the Chief Technology Officer at Satria Jaringan Digital Berhad. In Word for the web, use TC_02_Spectrum_Compliance_Report.docx to create a new agent called 'Rollout Governance Guide'. Describe it as an assistant that answers questions on network execution, subscriber retention, and regulatory compliance, the control expectations in the document, and the decisions leaders need for network recovery and churn control. Share it with network and commercial leads and make sure the welcome message explains the RAG logic it uses for prioritisation.",
        "You are the Chief Commercial Officer at Satria Jaringan Digital Berhad. Demo the 'Rollout Governance Guide' agent with a question that references TC_02_Spectrum_Compliance_Report.docx and the Network KPIs and Capex Plan vs Actual sheets in TC_01_Network_Performance.xlsx. Ask the agent to explain the top Red issue, the control the document expects, and the owner who should respond first. Show the response as a concise RAG answer with a source citation."
      ], DESC_WORD_AGT),
      tool(T_PPT_AGT, M365_LIC, M365_ACCT, [
        "You are the Chief Technology Officer at Satria Jaringan Digital Berhad. Create a PowerPoint briefing from TC_01_Network_Performance.xlsx, TC_02_Spectrum_Compliance_Report.docx, and TC_03_Network_Rollout_Strategy.docx, then create a new agent called 'Network Recovery Deck Guide'. Describe it as a deck navigator that helps leaders answer questions about network execution, subscriber retention, and regulatory compliance, the major Red items, and the decisions required this month. Share it with the Board, regulators, and commercial leadership and configure the opening prompt to point users to the highest-risk slide first.",
        "You are the Head of Regulatory Affairs at Satria Jaringan Digital Berhad. Demo the 'Network Recovery Deck Guide' agent by asking which slide best explains the current Red items from the Network KPIs, ARPU Tracker, and Capex Plan vs Actual sheets in TC_01_Network_Performance.xlsx. Then ask for a 60-second RAG summary of the story the presenter should tell to the MCMC liaison team. Require the answer to cite the slide topic it is drawing from."
      ], DESC_PPT_AGT),
      tool(T_XL_AGT, M365_LIC, M365_ACCT, [
        "You are the Chief Technology Officer at Satria Jaringan Digital Berhad. In Excel for the web, use TC_01_Network_Performance.xlsx to create a new agent called 'Network Performance Q&A'. Describe it as an assistant that answers questions on the Network KPIs, Subscriber Metrics, ARPU Tracker, Churn Analysis, and Capex Plan vs Actual sheets and translates workbook signals into RAG-ready management insight for network recovery and churn control. Share it with network and commercial leads and set the starter prompt to surface the top Red metrics automatically.",
        "You are the Chief Commercial Officer at Satria Jaringan Digital Berhad. Demo the 'Network Performance Q&A' agent by asking which indicators in the Network KPIs, Churn Analysis, and Capex Plan vs Actual sheets are currently Red and what action would most likely move each one to Amber. Then ask for the single metric management should watch weekly if it can only track one item. Require the reply to be a RAG summary that names the exact sheet for every answer."
      ], DESC_XL_AGT),
      tool(T_BUILDER, M365_LIC, M365_ACCT, [
        "You are the Chief Technology Officer at Satria Jaringan Digital Berhad. Go to Copilot Studio and create a new agent called 'Satria Network Copilot' using TC_01_Network_Performance.xlsx, TC_02_Spectrum_Compliance_Report.docx, and TC_03_Network_Rollout_Strategy.docx as knowledge sources. Describe it as an assistant for the Board, regulators, and commercial leadership that supports network recovery and churn control, add the topics Network KPIs, Subscriber Growth, Spectrum Compliance, and Capex Discipline, and publish it to Teams for the right audience. Make the starter prompts explicitly return Red, Amber, or Green recommendations when users ask for priorities.",
        "You are the Head of Regulatory Affairs at Satria Jaringan Digital Berhad. Demo the 'Satria Network Copilot' agent with a question that combines the Network KPIs, ARPU Tracker, and Capex Plan vs Actual sheets in TC_01_Network_Performance.xlsx with the policy direction in TC_02_Spectrum_Compliance_Report.docx. Ask for the top Red issue, the fastest Amber recovery action, and the Green area management should preserve while network recovery and churn control is under way. Require the answer to cite the file evidence it used for each RAG judgement."
      ], DESC_BUILDER),
    ],
    companyID='PT Satria Jaringan Digital Tbk',
    taglineID='Cakupan, churn, dan disiplin capex menyimpang menjelang review spektrum.'),
]

print(f"Batch 5 written: {len(INDUSTRIES_5)} entries")
