
import sys; sys.path.insert(0,'.')
from util import *

INDUSTRIES_6 = [

# ── DIVERSIFIED CONGLOMERATE ───────────────────────────────────────────────
ind('diversified-conglomerate','conglomerate','Diversified Conglomerate','🏛','#37474F','#455A64',
    'Zava Group Holdings Berhad',
    'Coal trading breach USD 22.4M — Board emergency meeting + dual HQ MY+ID restructure.',
    'Zava Group Holdings Berhad is a dual-HQ (Kuala Lumpur / Jakarta) ASEAN conglomerate with 11 divisions and MYR 44.8B revenue. A coal trading desk has breached its USD 20M single-counterparty exposure limit by USD 2.4M. An emergency Board meeting has been called. Three divisions are underperforming vs FY2026 targets. Group CFO Hadar Caspit must present to the Board on Monday.',
    ['01_Zava_Group_Financial_Performance.xlsx','03_Zava_Group_Strategy_Framework.docx','Email_07_Emergency_Board_Meeting.docx','Email_08_Coal_Trading_Breach.docx'],
    [
      tool(T_CHAT, FREE_LIC, FREE_ACCT, [
        'I am the Group CFO of a diversified ASEAN conglomerate. Our coal trading desk has breached its USD 20M single-counterparty exposure limit by USD 2.4M and I have an emergency Board meeting on Monday. Draft a 300-word Board briefing note covering: (1) the nature and scale of the breach, (2) how it occurred — control failure, (3) the immediate remediation steps taken, (4) the financial exposure if the counterparty defaults, (5) the proposed governance enhancement to prevent recurrence. Tone: accountable, factual, and forward-looking. Do not minimise the breach.',
        'Explain what a single-counterparty exposure limit is, why it exists in commodity trading operations, and what the typical regulatory and internal governance consequences are when such a limit is breached. Include what a Board Risk Committee would normally expect in terms of escalation and reporting within the first 48 hours.',
        'What are the 5 most important things a conglomerate Group CEO should do in the first week after discovering a significant internal control breach? Focus on governance, stakeholder communication, and operational actions. Be practical and specific.'
      ]),
      tool(T_RESEARCHER, M365_LIC, M365_ACCT, [
        'Research governance best practices for commodity trading risk management in diversified Asian conglomerates. I need: (1) Typical exposure limit frameworks used by conglomerates with commodity trading arms, (2) How boards of comparable conglomerates (Sime Darby, IOI, IJM) structure their risk oversight, (3) Any regulatory guidance from Bursa Malaysia or the Securities Commission on trading risk governance for listed conglomerates. Provide citations.',
        'Research the current Asian coal market — specifically Indonesian thermal coal pricing, demand trends from China and India, and any regulatory restrictions affecting Malaysian-listed companies\' coal trading activities. I need to brief the Board on whether our coal trading exposure represents a strategic risk beyond the immediate limit breach. Cite sources.'
      ], DESC_RESEARCHER),
      tool(T_ANALYST, M365_LIC, M365_ACCT, [
        'Analyse the performance of all 11 divisions against their FY2026 targets. Identify the 3 underperforming divisions — calculate the revenue variance vs target and the EBITDA margin variance. For each underperformer, show the trend over the past 4 quarters and calculate the full-year impact if the current trend continues. Present as a ranked table and a waterfall chart.',
        'Perform a conglomerate portfolio health assessment. For each division, calculate: (1) Revenue growth rate year-on-year, (2) EBITDA margin trend, (3) Working capital days (if data available), (4) Return on capital employed (ROCE). Rank all 11 divisions from highest to lowest portfolio value contribution. Create a 2x2 matrix: Revenue Growth vs EBITDA Margin — place each division in the appropriate quadrant (Star, Cash Cow, Question Mark, Dog).'
      ], DESC_ANALYST),
      tool(T_EXCEL, M365_LIC, M365_ACCT, [
        'Using the Trading Risk tab in this workbook, Build an exposure limit monitoring dashboard on a new sheet. For each trading counterparty, show: (1) Current exposure in USD M, (2) Approved limit in USD M, (3) Utilisation % (exposure/limit), (4) Breach status (OK / Warning >80% / BREACH >100%). Highlight breaches in red, warnings in amber. Add a total group exposure row at the bottom.',
        'Create a division performance dashboard on a new sheet. For each of the 11 divisions, show the current FY2026 revenue vs target, EBITDA vs target, and a traffic light status (Green: within 5% of target, Amber: 5–15% below, Red: >15% below). Add a group total row. Sort by largest revenue variance, unfavourable first.',
        'In the Group Cashflow sheet, calculate the group-level free cash flow for FY2025 and project FY2026 assuming the 3 underperforming divisions recover to 90% of target. Calculate the impact on group gearing (net debt/EBITDA) under two scenarios: divisions recover vs divisions continue declining. Show side-by-side.'
      ]),
      tool(T_WORD, M365_LIC, M365_ACCT, [
        'Draft a 2-page Board paper on the coal trading exposure breach. Structure: (1) Executive Summary — breach description, scale, and immediate status, (2) Background — how the breach occurred, (3) Immediate Actions Taken — exposure reduction steps, counterparty engagement, internal escalation, (4) Financial Exposure — worst-case scenario if counterparty defaults, (5) Governance Enhancement Plan — revised limit structure, daily reporting, real-time monitoring system, (6) Decisions Required from Board. Use formal board paper format.',
        'Draft the emergency Board meeting agenda. The meeting is Monday at 9am. Agenda items: (1) Apologies and quorum, (2) Coal Trading Breach — CFO presentation and Board deliberation, (3) FY2026 Performance Review — 3 underperforming divisions, (4) Group Strategy — any adjustments required, (5) Actions and decisions. Allocate time to each item — total meeting is 3 hours. Include a note on what pre-reading documents should be circulated 24 hours before the meeting.',
        'Identify the sections in this strategy document related to risk management and trading. Does the current strategy adequately address commodity trading risk? Highlight any gaps and suggest additions to the risk governance framework that would prevent a recurrence of this type of breach. Create a gap analysis table: Current Policy | Gap | Proposed Enhancement.'
      ]),
      tool(T_PPT, M365_LIC, M365_ACCT, [
        'Create a 14-slide emergency Board presentation for the Group CFO. Include: (1) Opening — purpose of the emergency meeting, (2) Coal trading breach — facts, scale, and timeline, (3) Root cause — control failure analysis, (4) Immediate actions taken, (5) Financial exposure scenario analysis, (6) Counterparty risk assessment, (7) Governance enhancement plan, (8) FY2026 group performance — 11 divisions dashboard, (9) Top 3 underperforming divisions — root cause and recovery plan, (10) Group cashflow and gearing outlook, (11) Strategic implications — should we divest coal trading?, (12) Regulatory and disclosure obligations, (13) Key risks, (14) Board decisions required. Use a serious dark grey and white colour scheme.',
        'For slides 2 through 5 (the breach narrative), generate detailed speaker notes. The CFO presenting is under significant Board pressure. Notes should be factual, accountable, and help the CFO maintain composure when challenged by Board members who may have already heard about the breach from media.',
        'Create a risk heat map slide showing the top 10 group-level risks, each positioned on a 5x5 likelihood-impact matrix. Flag the coal trading breach as a new risk. Compare this to the risk register from the previous quarter to show which risks have increased.'
      ]),
      tool(T_OUTLOOK, M365_LIC, M365_ACCT, [
        'Open Email_07_Emergency_Board_Meeting.docx. Draft the emergency Board meeting notice to all 9 Board members. The notice should: confirm Monday 9am (specify location and Teams link), attach the meeting agenda, note that pre-reading documents will be circulated by Sunday 6pm, stress the confidentiality of the breach information, and ask for immediate confirmation of attendance. Subject line: "URGENT: Emergency Board Meeting — Monday 9am".',
        'Draft an internal escalation email from the Group CFO to the Group CEO and Chairman informing them of the breach before the Board meeting. The email should: state the facts of the breach clearly, confirm the immediate containment actions taken, note the regulatory disclosure considerations, and recommend that no external communications be made until after the Board meeting on Monday. Mark as CONFIDENTIAL.',
        'Draft the Bursa Malaysia stock exchange announcement regarding the coal trading breach, to be released after the Board meeting. The announcement should: disclose the nature and financial magnitude of the breach, confirm that internal investigations are underway, state that no material impact on group financials is expected, and note the governance enhancements being implemented. Follow the Bursa Main Market disclosure guidelines.'
      ]),
      tool(T_TEAMS, M365_LIC, M365_ACCT, [
        'Open an existing recorded Teams meeting recap from a group management committee or risk committee meeting. Identify all risk-related discussions — any early warning signals about the coal trading exposure, any risk limit updates discussed, and any governance concerns raised. Format as a risk committee minute and flag any discussion point that may be relevant to the current breach investigation.',
        'Draft a post-breach communication for all Division MDs via Teams. The message should: acknowledge that they may have heard about the Board emergency meeting, reassure them that this is isolated to the trading desk, provide clear guidance on what they should and should not say to their teams and external stakeholders, and ask them to continue normal operations.',
        'Based on this meeting transcript, were there any previous discussions about commodity trading risk that should have prompted earlier escalation of the exposure limit? Extract any relevant statements with timestamps that the risk investigation team should review.'
      ], DESC_TEAMS),
      tool(T_NOTEBOOK, M365_LIC, M365_ACCT, [
        'Upload 01_Zava_Group_Financial_Performance.xlsx, 03_Zava_Group_Strategy_Framework.docx, Email_07_Emergency_Board_Meeting.docx, and Email_08_Coal_Trading_Breach.docx to Copilot Notebook. Set instruction: "You are the Group General Counsel advising the CFO on managing the Board emergency meeting." Ask: Based on all four documents, what are the top 3 legal and regulatory obligations the Board must be advised of at Monday\'s meeting? What decisions must the Board make and what cannot be delegated?',
        'Upload 01_Zava_Group_Financial_Performance.xlsx and 03_Zava_Group_Strategy_Framework.docx. Ask: The group strategy prioritises growing the commodity trading division as a high-margin business. The breach has called this into question. Based on the financial data, is the commodity trading division actually delivering the returns that justify the governance risk? Should the Board consider divesting or scaling back the trading operation? Present a data-based recommendation.'
      ], DESC_NOTEBOOK),
      tool(T_COWORK, FRONTIER_LIC, M365_ACCT, [
        'Do all of the following immediately: (1) Research Bursa Malaysia\'s disclosure requirements for material events at listed conglomerates — specifically trading losses and exposure limit breaches. (2) Draft a Bursa announcement for review by the Board — 2 paragraphs, factual and measured. (3) Save to OneDrive as "Bursa Disclosure Draft - CONFIDENTIAL". (4) Email to the General Counsel and CFO marked CONFIDENTIAL asking for review before Monday\'s Board meeting. (5) Schedule a 1-hour pre-Board legal and compliance briefing for Sunday 3pm with the General Counsel, CFO, and Company Secretary.',
        'Do all of the following for the Board meeting: (1) Confirm all 9 Board members\' attendance for Monday 9am and send calendar invites with the Teams link and a reminder. (2) Create a Board pre-reading pack in OneDrive with the 3 documents the CFO has drafted. (3) Set an access permission so only Board members and the Company Secretary can open the folder. (4) Send each Board member a link to the pre-reading pack via email with the instruction to review before Sunday 8pm. (5) Schedule a 15-minute pre-brief call for the Chairman and CEO for Sunday 8pm.'
      ], DESC_COWORK),
      tool(T_WORD_AGT, M365_LIC, M365_ACCT, [
        'Open 03_Zava_Group_Strategy_Framework.docx in Word for Web. Create an agent called "Group Strategy & Governance Bot". Description: "Answers questions from Group executives and Division MDs about Zava Group\'s strategic priorities, risk governance framework, performance targets, and corporate governance policies." Share with all Division MDs and the Group management team.',
        'Demo: A Division MD asks "Our EBITDA is tracking 18% below target. The Group strategy says underperforming divisions should submit a turnaround plan by end of Q2. What is the required format of the turnaround plan and who do I submit it to?" Show how the agent provides a governance-grounded, consistent answer to a high-stakes operational question.'
      ], DESC_WORD_AGT),
      tool(T_PPT_AGT, M365_LIC, M365_ACCT, [
        'Create a PowerPoint from the Board presentation. Create an agent called "Group Board Pack Bot". Share ONLY with Board members and the Company Secretary.',
        'Demo: A Board member reviewing the pack at 11pm Sunday asks the agent "In the coal trading breach scenario analysis, what is the worst-case financial impact on group EBITDA and does it trigger any debt covenant breaches on our existing revolving credit facility?" Show how the agent gives a precise, scenario-specific answer that prepares the Board member for Monday\'s discussion.'
      ], DESC_PPT_AGT),
      tool(T_XL_AGT, M365_LIC, M365_ACCT, [
        'Open 01_Zava_Group_Financial_Performance.xlsx in Excel for Web. Create an agent called "Group Financial Performance Q&A". Description: "Answers questions from the Group CFO, CEO, and Board on divisional performance, trading exposure, cashflow, and gearing — providing instant data-grounded intelligence for executive decision-making." Share with the Group C-suite and Board.',
        'Demo: Ask "Which 3 divisions are most below their FY2026 EBITDA target and by how much in absolute MYR terms?" Then: "If the coal trading counterparty defaults on their full exposure, what would be the impact on our group net debt/EBITDA ratio and do we breach the 3.5x covenant?" Show how the CFO gets instant scenario intelligence.'
      ], DESC_XL_AGT),
      tool(T_BUILDER, M365_LIC, M365_ACCT, [
        'Go to copilotstudio.microsoft.com > Create > New Agent. Name it "Zava Group Executive Intelligence Bot". Description: "Supports Zava Group\'s Board, C-suite, and Division MDs with instant answers on group financial performance, divisional KPIs, risk governance requirements, trading exposure limits, and strategic priorities — grounded in official group financial and strategy documents." Upload 01_Zava_Group_Financial_Performance.xlsx, 03_Zava_Group_Strategy_Framework.docx. Add topics: "Group Performance", "Risk Governance", "Trading Limits", "Strategic Priorities". Publish to Teams for Group executives only (restricted access).',
        'Demo the agent: The Group CEO asks at 7am Monday before the Board meeting: "Give me a 60-second summary of the coal trading situation, the 3 worst-performing divisions, and the key decision the Board needs to make today. Also — are there any regulatory disclosure obligations that must be acted on immediately after the meeting?" Show how the CEO gets an instant, comprehensive executive intelligence briefing before walking into the boardroom.'
      ], DESC_BUILDER),
    ]),

# ── FINTECH & PAYMENTS ─────────────────────────────────────────────────────
ind('fintech-payments','fintech','Fintech & Payments','💳','#6A1B9A','#7B1FA2',
    'Tranglo Payments Group',
    '120+ corridor remittance — BNM e-money licence renewal + fraud detection ML upgrade.',
    'Tranglo Payments Group operates cross-border remittance across 120+ corridors serving 8 million active digital wallets. The BNM e-money licence is up for renewal in 3 months. A fraud detection ML model upgrade is underway — current model flags 94% of fraud with a 12% false positive rate. ASEAN Payment Network (APN) integration is in progress.',
    ['13_Zava_Financial_Services.xlsx','BNK_01_Meridian_Bank.xlsx'],
    [
      tool(T_CHAT, FREE_LIC, FREE_ACCT, [
        'I am the Chief Risk Officer of a Malaysian fintech specialising in cross-border remittance. Our fraud detection model has a 94% detection rate but a 12% false positive rate — meaning 1 in 8 legitimate transactions is incorrectly flagged as fraud, causing customer friction. Draft a 250-word brief for my Board explaining the trade-off between detection rate and false positive rate, why both matter for our business, and the approach we will take to improve both simultaneously in our ML model upgrade.',
        'What are BNM\'s key requirements for e-money licence renewal in Malaysia? What financial, operational, and technical conditions must the licensee meet, and what documentation is typically required 90 days before renewal? Focus on requirements relevant to a cross-border remittance operator with 8 million active wallets.',
        'Explain how the ASEAN Payment Network (APN) initiative works and what it means for cross-border remittance operators in the region. What are the key technical and regulatory requirements for integration? Which corridors will benefit most from APN connectivity in Malaysia, Indonesia, Thailand, and Singapore?'
      ]),
      tool(T_RESEARCHER, M365_LIC, M365_ACCT, [
        'Research the competitive landscape for digital cross-border remittance in Southeast Asia. I need: (1) Market size and growth rate for intra-ASEAN and ASEAN-GCC remittance in 2024–2025, (2) The top 5 competitors (Wise, Western Union, GrabPay, Sea Money, local players) and their key differentiators, (3) The impact of APN on incumbent remittance operators. Provide citations.',
        'Research best practices for fraud detection in digital payments — specifically for cross-border remittance. What ML model architectures are most effective for remittance fraud? How do leading fintechs balance detection rate and false positive rate? Are there regulatory expectations from BNM on fraud detection performance? Cite industry sources.'
      ], DESC_RESEARCHER),
      tool(T_ANALYST, M365_LIC, M365_ACCT, [
        'Analyse transaction data by remittance corridor. Which 10 corridors have the highest transaction volume? Which have the highest fraud rate? Is there a correlation between high-volume corridors and high fraud rates? Create a bubble chart: X-axis = transaction volume, Y-axis = fraud rate, bubble size = average transaction value. Identify corridors that are high-volume AND high-fraud (top-right quadrant).',
        'Analyse the false positive rate by customer segment (first-time senders, regular senders, high-value senders). Which segment has the highest false positive rate? Calculate the customer dropout rate for transactions incorrectly flagged — if 8% of customers abandon a transaction after a false positive flag, calculate the annual revenue loss from false positives at current transaction volumes and average fee of MYR 18 per transaction.'
      ], DESC_ANALYST),
      tool(T_EXCEL, M365_LIC, M365_ACCT, [
        'Using the Compliance tab in this workbook, Build a BNM e-money licence renewal readiness checklist on a new sheet. List the 15 key BNM renewal criteria. For each, show: Current Status (Met/Partial/Not Met) | Evidence on File (Yes/No) | Responsible Team | Action Required | Deadline. Apply conditional formatting: green = Met, amber = Partial, red = Not Met.',
        'Create a fraud model performance dashboard on a new sheet. Show monthly data for the past 12 months: (1) Detection rate (%), (2) False positive rate (%), (3) Fraud losses prevented (MYR M), (4) Customer complaints due to false positives (count). Add trend lines and flag months where false positive rate exceeded 15%. Calculate the estimated revenue saved by fraud prevention vs the estimated revenue lost due to false positives — show the net benefit.',
        'In the Corridor Performance sheet, build a corridor priority matrix. For each of the top 20 corridors, calculate: (1) Annual fee revenue (MYR M), (2) Transaction volume growth rate, (3) Current fraud rate, (4) APN integration status. Rank corridors by a composite score (revenue × growth ÷ fraud rate) to identify which corridors should receive the most investment in fraud detection improvement.'
      ]),
      tool(T_WORD, M365_LIC, M365_ACCT, [
        'Open BNK_01_Meridian_Bank.xlsx (use as a financial services reference). Draft the BNM e-money licence renewal application cover letter. The letter should: reference our existing licence number and expiry date, confirm our continued compliance with the BNM e-money framework, highlight our key operational metrics (8M active wallets, 120+ corridors, 99.97% system uptime), note the ML fraud model upgrade underway, and request a pre-renewal meeting with BNM Supervision. Use formal BNM correspondence format.',
        'Draft a fraud risk management policy document of 3 pages. Cover: (1) Fraud risk appetite statement — acceptable detection rate and false positive rate targets, (2) ML model governance — how the model is trained, validated, and monitored, (3) Manual review process for flagged transactions, (4) Customer dispute resolution process for false positives, (5) Regulatory reporting of fraud incidents to BNM. Format as a formal policy document with version control header.',
        'Draft an APN integration business case for the CFO. Cover: (1) What APN connectivity means for our corridor economics — expected fee compression and volume increase, (2) Technical integration requirements and estimated cost (MYR 8.5M), (3) Revenue impact — net of fee compression, volume uplift, and new corridors unlocked, (4) Risk: if we do not integrate, we lose access to APN-connected corridors to competitors who do. Recommend: proceed vs defer.'
      ]),
      tool(T_PPT, M365_LIC, M365_ACCT, [
        'Create a 10-slide investor presentation for Tranglo Payments Group. Include: (1) Business overview — 120+ corridors, 8M wallets, (2) Market opportunity — intra-ASEAN remittance growth, (3) Competitive positioning, (4) Fraud detection — current model and ML upgrade roadmap, (5) BNM licence renewal — compliance status, (6) APN integration — timeline and revenue impact, (7) Financial performance — revenue growth and margin, (8) Technology roadmap, (9) ESG — financial inclusion and migrant worker impact, (10) Investment thesis. Purple and white colour scheme.',
        'Create a 2-slide fraud model explainer for a non-technical Board audience. Slide 1: How our ML fraud model works — simple visual with 3 steps (transaction comes in → model scores risk → action taken). Slide 2: Current performance vs target — detection rate and false positive rate shown as gauges, with the improvement target for the upgraded model.',
        'Add a corridor map slide showing our 10 highest-revenue corridors as a world map with connecting lines. Label each corridor with the annual transaction volume and the fraud rate. Use different colours to indicate APN-integrated vs non-APN corridors.'
      ]),
      tool(T_OUTLOOK, M365_LIC, M365_ACCT, [
        'Draft a letter to BNM\'s Payment Systems Policy Department requesting a pre-renewal consultation meeting for our e-money licence renewal. The letter should: introduce the purpose of the meeting, summarise our compliance status, highlight the ML fraud model upgrade as a key enhancement since the last renewal, and request a 45-minute meeting within the next 4 weeks.',
        'Draft a customer apology and resolution email for the top 50 customers who were most affected by false positive fraud flags in the past quarter. The email should: acknowledge the inconvenience, explain briefly that our fraud detection system has flagged their transaction incorrectly, confirm the transaction has been approved, and offer a waived fee on their next transaction as a goodwill gesture.',
        'Draft an email to our APN integration technology partner requesting a project status update. The integration is now 6 weeks behind the original schedule. The email should ask for: the root cause of the delay, a revised project timeline, and confirmation of the resources assigned to the integration sprint.'
      ]),
      tool(T_TEAMS, M365_LIC, M365_ACCT, [
        'Open an existing recorded Teams meeting recap from a product or compliance meeting. Identify all BNM compliance actions discussed — their status, deadline, and responsible team. Flag any action that is overdue or at risk of missing its deadline before the licence renewal in 3 months.',
        'Draft follow-up actions from this meeting for the fraud model upgrade team. Group by workstream: Data Science | Engineering | Compliance | Customer Experience. Include owner and deadline.',
        'Based on this meeting, what is the team\'s confidence level that the ML model upgrade will be completed before the BNM renewal inspection? Identify the top 2 technical or resource risks that could delay the upgrade.'
      ], DESC_TEAMS),
      tool(T_NOTEBOOK, M365_LIC, M365_ACCT, [
        'Upload 13_Zava_Financial_Services.xlsx and BNK_01_Meridian_Bank.xlsx to Copilot Notebook. Set instruction: "You are a fintech regulatory advisor preparing Tranglo for BNM e-money licence renewal." Ask: Based on the transaction data and the financial services framework, what are the 3 areas where our current performance is most likely to draw BNM scrutiny during the renewal assessment? For each area, what specific evidence should we prepare?',
        'Our current false positive rate of 12% is significantly above the industry best practice of 5–7%. If we reduce it to 7% through the ML upgrade, what is the projected impact on: (1) customer retention rate, (2) annual transaction volume, (3) annual fee revenue? Quantify the business case for the ML upgrade investment.'
      ], DESC_NOTEBOOK),
      tool(T_COWORK, FRONTIER_LIC, M365_ACCT, [
        'Do all of the following: (1) Research BNM\'s e-money licence renewal requirements and any updates published in 2024 or 2025. (2) Draft a 90-day countdown renewal action plan with weekly milestones covering all documentation, compliance, and technical requirements. (3) Save to OneDrive as "BNM e-Money Licence Renewal Plan". (4) Email to the Chief Compliance Officer and CTO asking for review and sign-off within 2 days. (5) Schedule a weekly 30-minute "BNM Renewal Check-In" every Monday at 9am for 12 weeks.',
        'Do all of the following for APN integration: (1) Research the technical specification for APN integration published by BNM or the ASEAN payment network. (2) Draft an accelerated integration timeline to make up the 6-week delay. (3) Email to our CTO and the technology partner project manager asking for a recovery plan call this week. (4) Create an integration milestone tracker in SharePoint with weekly check-points. (5) Post in the #product-engineering Teams channel: "APN integration is 6 weeks behind — recovery plan discussion on [date]. All corridor and API team members please attend."'
      ], DESC_COWORK),
      tool(T_WORD_AGT, M365_LIC, M365_ACCT, [
        'Open BNK_01_Meridian_Bank.xlsx in Excel for Web. Create a Word document summarising the key BNM compliance requirements for e-money operators and open it in Word for Web. Create an agent called "Tranglo Compliance Policy Bot". Description: "Answers questions from compliance and product teams about BNM e-money framework requirements, fraud reporting obligations, AML/CFT rules for remittance, and licence renewal criteria." Share with the compliance team.',
        'Demo: A compliance analyst asks "A customer has sent 15 transactions over MYR 5,000 to the same overseas beneficiary in one week. Does this trigger our STR (Suspicious Transaction Report) obligation to BNM and what is the 24-hour reporting deadline?" Show how the agent provides a precise, regulatory-grounded AML compliance answer.'
      ], DESC_WORD_AGT),
      tool(T_PPT_AGT, M365_LIC, M365_ACCT, [
        'Create a PowerPoint from the investor presentation and open in PowerPoint for Web. Create an agent called "Tranglo Investor Q&A Bot". Share with institutional investors and analyst research teams.',
        'Demo: An analyst asks "What is Tranglo\'s current market share in the Malaysia-Indonesia remittance corridor and what is the projected impact of APN integration on corridor fees?" Show how the agent handles investor research questions with specific data-grounded answers.'
      ], DESC_PPT_AGT),
      tool(T_XL_AGT, M365_LIC, M365_ACCT, [
        'Open 13_Zava_Financial_Services.xlsx in Excel for Web. Create an agent called "Tranglo Payments Analytics Q&A". Description: "Instant answers on corridor performance, fraud rates, false positive rates, wallet metrics, and BNM compliance status for the CRO, CEO, and product leadership." Share with senior leadership.',
        'Demo: Ask "What is the fraud rate on the Malaysia-Philippines corridor and how does it compare to the group average?" Then: "How many customer transactions were incorrectly flagged as fraud last month and what was the estimated revenue impact?" Show how the CRO gets rapid fraud intelligence.'
      ], DESC_XL_AGT),
      tool(T_BUILDER, M365_LIC, M365_ACCT, [
        'Go to copilotstudio.microsoft.com > Create > New Agent. Name it "Tranglo Payments Intelligence Agent". Description: "Supports Tranglo\'s compliance, product, and commercial teams with answers on BNM e-money requirements, fraud detection policies, APN integration status, corridor performance, and customer dispute procedures — ensuring regulatory-compliant, consistent responses across the fintech operation." Upload 13_Zava_Financial_Services.xlsx. Add topics: "BNM Compliance", "Fraud Detection", "APN Integration", "Corridor Performance". Publish to Teams.',
        'Demo the agent: A customer success manager gets a call from an angry corporate customer whose payroll remittance to 120 employees in Indonesia was blocked by the fraud model. The manager asks the agent: "A USD 340,000 payroll transfer to Indonesia was flagged and blocked. What is our SLA to resolve a blocked corporate payroll transfer, what information do I need from the customer to manually approve it, and can I override the ML flag?" Show how the agent provides an instant, policy-grounded resolution path.'
      ], DESC_BUILDER),
    ]),

# ── GOVERNMENT AGENCY ─────────────────────────────────────────────────────
ind('government-agency','government','Government Agency','🏛','#4E342E','#5D4037',
    'Jabatan Perkhidmatan Awam (JPA) / State Digital Office',
    'MyGovID rollout — 2.4M constituent digital interactions, e-service transformation.',
    'The Selangor State Digital Office is leading the digital government transformation agenda — migrating 48 government services online, integrating with MyGovID (national digital identity), and reducing counter-based transactions by 60% within 18 months. 2.4 million constituent interactions per year are being transformed through digital channels.',
    ['03_Zava_Group_Strategy_Framework.docx','02_Zava_Group_Policy_Handbook.docx'],
    [
      tool(T_CHAT, FREE_LIC, FREE_ACCT, [
        'I am leading the digital transformation programme for a Malaysian state government. We are migrating 48 services online and integrating with MyGovID. Constituents are resistant to digital channels — only 34% adoption after 6 months. Draft a 300-word constituent adoption acceleration strategy brief. Cover: the 3 most common barriers to adoption for Malaysian government digital services, three specific interventions that have worked in comparable GovTech programmes (cite examples from Singapore, Estonia, or other advanced digital governments), and the key success metric we should target at the 12-month mark.',
        'Explain how MyGovID works as a national digital identity for Malaysia — what it enables for government service delivery, how it differs from SingPass, and what the key privacy and data security considerations are for state government agencies integrating with it.',
        'What are the 5 most important change management principles for a successful government digital transformation? Focus on the specific challenges of driving change in a public sector environment where civil servants may fear that digitalisation will reduce headcount.'
      ]),
      tool(T_RESEARCHER, M365_LIC, M365_ACCT, [
        'Research successful government digital transformation case studies in Southeast Asia and comparable markets. I need: (1) The top 3 governments that have achieved the highest e-service adoption rates, (2) The specific interventions that drove adoption beyond 60%, (3) How they handled data privacy and cybersecurity concerns with constituents. Provide citations from GovTech publications or government reports.',
        'Research the Malaysia Government digital transformation roadmap — specifically MAMPU\'s guidelines, the MyDigital blueprint, and any Selangor-specific digital government initiatives. What are the performance benchmarks the federal government expects from state agencies? Are there any grant funding programmes for digital government projects? Cite official sources.'
      ], DESC_RESEARCHER),
      tool(T_ANALYST, M365_LIC, M365_ACCT, [
        'Upload 03_Zava_Group_Strategy_Framework.docx (use as strategy proxy). Ask Analyst: Assume we have a dataset of 2.4 million constituent interactions — 34% digital, 66% counter-based. Analyse the digital adoption rate by service type (business licence, property assessment, civil complaints, permit applications). Which service types have the highest digital adoption? Which have the lowest? Create a bar chart ranked by adoption rate and calculate the revenue/cost saving for each 1% shift from counter to digital (assume MYR 12 cost per counter transaction vs MYR 2 per digital transaction).',
        'Ask Analyst: Build a digital transformation ROI model. Inputs: 2.4M annual interactions, current 34% digital adoption (816,000 digital, 1,584,000 counter), target 80% digital by Month 18. Calculate: (1) Annual cost saving at 80% adoption vs current, (2) Investment required — portal development MYR 4.2M, MyGovID integration MYR 1.8M, digital outreach MYR 0.8M, (3) Payback period in months. Show as a cost-benefit table.'
      ], DESC_ANALYST),
      tool(T_EXCEL, M365_LIC, M365_ACCT, [
        'Open 03_Zava_Group_Strategy_Framework.docx. In Excel, create a new workbook called "Digital Services Migration Tracker.xlsx". Ask Copilot to help structure: Create a sheet with columns: Service Name | Department | Current Mode (Counter/Hybrid/Digital) | MyGovID Integration Required (Y/N) | Development Status | Go-Live Date | Adoption Rate (%) | Monthly Transactions. Populate with 10 sample services. Add conditional formatting: red = not started, amber = in progress, green = live.',
        'Build a constituent adoption dashboard. For each of the 10 sample services, create a chart showing: (1) Monthly transaction volume by channel (digital vs counter) for the past 6 months, (2) Digital adoption trend line, (3) Target adoption rate line at 80%. Flag any service where digital adoption is declining despite being live.',
        'Create an efficiency savings model. For each service, calculate: (1) Annual counter transactions saved if digital adoption reaches 80%, (2) Cost saving at MYR 10 per counter transaction, (3) Officer hours freed for higher-value work. Sum across all 48 services and show the total annual productivity dividend in MYR and officer hours.'
      ]),
      tool(T_WORD, M365_LIC, M365_ACCT, [
        'Draft a digital government transformation policy for the Selangor State Government. Cover: (1) Vision and mandate — 80% digital adoption within 18 months, (2) Scope — 48 services, (3) MyGovID integration requirements, (4) Data privacy and cybersecurity standards for digital services, (5) Civil servant role in supporting constituent adoption, (6) Performance measurement framework. Keep it to 5 pages, use formal government policy language.',
        'Draft a constituent communication guide for the digital migration of 5 high-volume services. For each service, the guide should: explain the new online process in plain language (Bahasa Malaysia and English), list the documents to prepare before logging in, provide the MyGovID registration link, and note the helpline for constituents who need assistance. Format as a simple infographic script.',
        'Write a Board paper for the State Exco Committee recommending the approval of MYR 6.8M for the digital services migration programme. Cover: strategic rationale, scope, investment breakdown, ROI and payback period, risks and mitigants, and the decision required. Format as a formal Exco submission paper.'
      ]),
      tool(T_PPT, M365_LIC, M365_ACCT, [
        'Create a 10-slide presentation for the State Exco Committee on the digital transformation programme. Include: (1) Vision — transforming 2.4M annual constituent interactions, (2) Current state — 34% digital adoption, (3) Target state — 80% digital, 60% counter reduction, (4) Service migration roadmap — 48 services, phased over 18 months, (5) MyGovID integration plan, (6) Cost savings — MYR 18M annual by Year 3, (7) Technology architecture — simple diagram, (8) Change management plan — civil servant and constituent engagement, (9) Budget request — MYR 6.8M, (10) Decision required. Use dark blue and gold Malaysian government colour scheme.',
        'Create a one-slide "Before and After" digital journey map showing how a constituent currently obtains a business licence at a counter (7 steps, 45-minute wait, MYR 12 cost) vs the new digital process (4 steps, 10 minutes online, MYR 2 cost). Use a simple flowchart format.',
        'Add a constituent testimonial slide with 3 fictional but realistic quotes from different constituent segments — a millennial entrepreneur, a 55-year-old smallholder farmer, and a SME owner — showing their positive experience with the new digital service.'
      ]),
      tool(T_OUTLOOK, M365_LIC, M365_ACCT, [
        'Draft a letter from the State Digital Director to all 48 department heads whose services are being migrated. The letter should: explain the digital migration mandate, the MyGovID integration requirement, the department\'s responsibilities in the migration project, and the go-live timeline. Ask each department head to nominate a digital champion within 2 weeks. Use formal government correspondence language in Bahasa Malaysia (or bilingual format).',
        'Draft a press release announcing the launch of the Selangor Digital Government Portal. The release should: announce the availability of the first 10 digital services, explain the MyGovID login process, note the constituent support channels, and include a quote from the State Exco member for Digital Affairs. Target audience: Malay and English-language media.',
        'Draft an email to MAMPU (Malaysia Administrative Modernisation and Management Planning Unit) requesting technical support for the MyGovID API integration. The email should specify our integration requirements, the development timeline, and the number of services being integrated. Request a technical onboarding meeting within 2 weeks.'
      ]),
      tool(T_TEAMS, M365_LIC, M365_ACCT, [
        'Open an existing recorded Teams meeting recap from a project or digital transformation steering committee. Identify all digital service migration milestones discussed, their current status, and any blockers. Format as a programme status update for the Exco Digital Transformation Committee.',
        'Draft follow-up actions for the digital transformation team. Group by workstream: Technology | Change Management | Constituent Communications | MyGovID Integration | Training. Include department owner and deadline.',
        'Were any constituent complaints or feedback about the digital services discussed? List each with the service type, the nature of the feedback, and whether a resolution was proposed.'
      ], DESC_TEAMS),
      tool(T_NOTEBOOK, M365_LIC, M365_ACCT, [
        'Upload 03_Zava_Group_Strategy_Framework.docx and 02_Zava_Group_Policy_Handbook.docx to Copilot Notebook. Set instruction: "You are a GovTech transformation advisor helping the State Digital Director drive constituent adoption." Ask: Based on the strategic framework and policy requirements, what is the single biggest barrier to digital adoption in a Malaysian state government context and what is the most effective intervention backed by international evidence?',
        'Upload 02_Zava_Group_Policy_Handbook.docx and 03_Zava_Group_Strategy_Framework.docx. Ask: A civil servant has raised concerns that the digital migration will lead to job losses in the counter service teams. Is this concern valid based on comparable government digital transformations? How should the State Digital Director address this concern in a way that is honest, compassionate, and motivating for the civil service?'
      ], DESC_NOTEBOOK),
      tool(T_COWORK, FRONTIER_LIC, M365_ACCT, [
        'Do all of the following: (1) Research the top 3 GovTech vendors in Malaysia who have successfully implemented MyGovID integration for state government portals — identify their references and pricing models. (2) Draft a vendor RFP for the digital portal development covering our 10 priority services. (3) Save to OneDrive as "Digital Portal RFP - Selangor SDO". (4) Email the RFP to the 3 shortlisted vendors asking for proposals within 3 weeks. (5) Schedule an RFP briefing session for all 3 vendors for next Thursday.',
        'Do all of the following for the digital adoption campaign: (1) Draft a constituent digital awareness campaign concept for social media, WhatsApp, and community halls targeting 3 segments: youth (18–35), working age (36–54), and senior (55+). (2) Create a campaign calendar showing the 12-week rollout. (3) Draft sample social media posts in Bahasa Malaysia and English for weeks 1 and 2. (4) Email the concept and calendar to the State Communications team for review. (5) Schedule a campaign kickoff meeting for next week.'
      ], DESC_COWORK),
      tool(T_WORD_AGT, M365_LIC, M365_ACCT, [
        'Open 02_Zava_Group_Policy_Handbook.docx in Word for Web. Create an agent called "Digital Government Policy Bot". Description: "Answers questions from civil servants and department heads about the digital transformation policy, MyGovID integration requirements, data privacy obligations, and constituent service standards." Share with all 48 department heads.',
        'Demo: A department head asks "My team handles physical land title searches. The new digital portal requires us to process results within 3 working days. Our current process takes 7 days. What process changes are we required to make and is there any budget available for system upgrades to meet the 3-day SLA?" Show how the agent provides a policy-grounded answer that empowers the department head to act.'
      ], DESC_WORD_AGT),
      tool(T_PPT_AGT, M365_LIC, M365_ACCT, [
        'Create a PowerPoint from the Exco presentation. Create an agent called "Selangor Digital Transformation Q&A". Share with Exco members and the State Secretary.',
        'Demo: An Exco member asks "If we achieve 80% digital adoption within 18 months, what is the total headcount saving across all 48 services and how will those officers be redeployed rather than retrenched?" Show how the agent gives a data-grounded, politically-sensitive answer.'
      ], DESC_PPT_AGT),
      tool(T_XL_AGT, M365_LIC, M365_ACCT, [
        'Create a Digital Services Tracker workbook and open in Excel for Web. Create an agent called "Digital Services Programme Q&A". Description: "Answers questions about the Selangor digital government programme — service migration status, adoption rates, cost savings, and MyGovID integration progress — for the State Digital Director and Exco." Share with the State Digital Office.',
        'Demo: Ask "How many of the 48 services are currently live on the digital portal and what is the average adoption rate across live services?" Then: "Which 3 services have the lowest digital adoption and what might be causing it?" Show how the Digital Director gets instant programme intelligence.'
      ], DESC_XL_AGT),
      tool(T_BUILDER, M365_LIC, M365_ACCT, [
        'Go to copilotstudio.microsoft.com > Create > New Agent. Name it "Selangor Digital Government Assistant". Description: "Helps civil servants, department heads, and the State Digital Office team with answers on digital service requirements, MyGovID integration, constituent FAQ, data privacy obligations, and transformation programme milestones — supporting Malaysia\'s digital government agenda." Upload 02_Zava_Group_Policy_Handbook.docx and 03_Zava_Group_Strategy_Framework.docx. Add topics: "MyGovID Integration", "Digital Service Standards", "Constituent FAQ", "Privacy & Data". Publish to Teams for all state government staff.',
        'Demo the agent: A counter officer who has been redeployed to a digital support role asks: "A constituent is trying to renew their business licence online but keeps getting an error at the payment step after connecting their MyGovID. What are the 3 most common causes of this error and what is the step-by-step resolution I should guide them through over the phone?" Show how the agent empowers redeployed staff to provide excellent digital support.'
      ], DESC_BUILDER),
    ]),
]

print(f"Batch 6 written: {len(INDUSTRIES_6)} entries")
