import sys
sys.path.insert(0, '.')
from util import *

INDUSTRIES_13 = []

# ─────────────────────────────────────────────────────────────────────────────
# Zava Electrical — Industrial & Electrical Distribution
# Follows Zava canonical tool order: Chat, Researcher, Analyst, Excel, Word,
# PPT, Outlook, Teams, Notebook, Cowork, Word Agent, PPT Agent, Excel Agent
# ─────────────────────────────────────────────────────────────────────────────

PRE = ("I am working under a tight deadline and the work product needs to be airtight, "
       "so please be thorough rather than terse. ")
POST = (" Be specific, attach a citation or sheet/tab/cell reference to every "
        "quantitative claim, and if anything is missing or contradictory call it out "
        "explicitly with the question I should ask next so nothing slips before the deadline.")

SCENARIO = (
    "Zava Electrical is the local OpCo of Zava Group (the world's largest B2B distributor of "
    "electrical products, €33.6B 2025 group revenue, 170 OpCos, 45,000 associates). The MY business "
    "runs RM 800M annual revenue, 6 distribution centres (Shah Alam HQ, Penang, Johor Bahru, Kuching, "
    "Kota Kinabalu, Ipoh), 7,000+ B2B customers across industrial, commercial, datacenter, EV, and "
    "Petronas-supply-chain segments, and represents ABB, Schneider Electric, Siemens, Legrand, "
    "Eaton, Phoenix Contact and Mersen. It is 21 May 2026. Mod Admin, Group Strategy Director, has "
    "30 minutes before tomorrow's MD board review. May closed at RM 44.86M actual vs RM 43.30M "
    "budget — a 3.6% miss driven by FX + ABB 4.2% price increase eating RM 1.18M of margin, three "
    "ABB ACS580 VFD backorders for Petronas Melaka, Top Glove and UMW Toyota worth RM 2.4M, "
    "last-mile logistics 20% over budget, and Tan Brothers bad debt of RM 190k. Offsetting: "
    "Commercial sales +10.4% (datacenter and semicon strong — TM, YTL, Bridge DC, Princeton Digital, "
    "Penang semicon fabs). Aishah must walk in tomorrow with a variance memo, a risk-ranked order "
    "list, a market brief on ABB pricing and MY datacenter demand, a 6-slide board deck, all three "
    "backorder customer comms aligned with what her buyers actually promised, and a Monday morning "
    "follow-up plan with the war-room invite already scheduled."
)

INDUSTRIES_13.append(ind(
    'electrical-distribution',
    'sec-distribution',
    'Industrial & Electrical Distribution',
    '⚡',
    '#005EB8',
    '#0F1C3F',
    'Zava Electrical',
    'World #1 B2B electrical distributor — RM 800M MY revenue, 6 DCs, 7,000+ customers, ABB / Schneider / Siemens / Legrand / Eaton lines, datacenter + semicon + Petronas + EV demand all hitting at once.',
    SCENARIO,
    [
        'zava-electrical-ops-workbook.xlsx',
        'variance-memo.docx',
        'exec-brief-template.pptx',
        'customer-rfq.docx',
        'product-catalog.xlsx',
        'customer-feedback.xlsx',
        'purchase-orders.xlsx',
        'month-end-variance.docx',
        'roi-summary.xlsx',
    ],
    [
        # ── 1. CHAT ─────────────────────────────────────────────────────────
        tool(T_CHAT, FREE_LIC, FREE_ACCT, [
            {'instr':'Open `m365.cloud.microsoft/chat` > toggle **Work** ON > leave model = GPT default. Paste the prompt below.',
             'prompt': PRE + "I am Mod Admin, Group Strategy Director at Zava Electrical. I need a single grounded answer pulled across Outlook, Teams, SharePoint, the workbook and the live web — and at the end I want it turned into a Copilot Page my Procurement and Sales leads can co-edit. Here is exactly what I need from you. Search across my Outlook, Teams chats and SharePoint for everything in the last 14 days about ABB 2026 price increases, the three ABB ACS580 VFD backorders, Petronas Melaka Refinery SO-44218, Top Glove SO-44219, and UMW Toyota SO-44226. Cross-reference with zava-electrical-ops-workbook.xlsx (Orders + Inventory sheets) and variance-memo.docx. When you reply, organise as (1) summary of what the buyer and customer have said about each backorder with email dates and Teams timestamps, (2) commitments my team has made quoted verbatim with citation, (3) mismatches between team commitments and NetSuite Orders status, (4) ABB price discussion grounded in three public sources from the last 30 days, (5) three follow-up questions for Daichi Maruyama this afternoon. Show inline citations 📎 Outlook 📎 Teams 📎 SharePoint 📊 workbook 🌐 web. When done, click Create Page, title it 'Backorder situation 21-May', share to #zava-electrical-ops-leads." + POST},
            {'instr':'Stay in Copilot Chat. Paste the account-coverage prompt.',
             'prompt': PRE + "Tomorrow morning before the MD review I want to walk in already knowing what every account manager has been saying to their largest customer this week, so the MD's first question — 'are our top accounts at risk?' — has a confident answer. Here is exactly what I need from you. Search Outlook + Teams + SharePoint over the last 7 days for every conversation between Zava Electrical account managers (Sasha Ouellet, Sasha Ouellet, Sasha Ouellet, Sasha Ouellet, Sasha Ouellet) and our top 10 customers by YTD revenue (Petronas, MMHE, Lotte Chemical, TM, YTL, Bridge DC, Princeton Digital, Inari, Vitrox, UMW Toyota). Output a table — Customer, Account Manager, Last Touchpoint Date, Topic, Sentiment (Green/Amber/Red), Open Commitment, Next Step. Add a 3-bullet 'so what' on the biggest churn risk, the biggest upsell opportunity, and the account manager needing MD-level air-cover in 48h." + POST},
            {'instr':'Stay in Copilot Chat. Paste the meeting-prep prompt.',
             'prompt': PRE + "I have 12 minutes between meetings and I need to walk into the 4pm backorder war-room fully briefed. Here is exactly what I need from you. Search Outlook + Teams for the war-room invite and any prior thread tagged 'backorder' over the last 21 days. Ground in the invite, the Orders sheet, and the variance-memo. Give me (1) the 5 specific decisions the war-room needs to make in 30 minutes, (2) the pre-read each attendee should have already opened (deck slide, sheet tab, email thread — name them), (3) three contentious points where Procurement and Sales are likely to disagree with the data to settle each, (4) a 60-second opening to set the frame." + POST},
        ], DESC_CHAT, persona=['Mod Admin','Mod Admin','Mod Admin']),

        # ── 2. RESEARCHER ───────────────────────────────────────────────────
        tool(T_RESEARCHER, M365_LIC, M365_ACCT, [
            {'instr':'Open `m365.cloud.microsoft/chat` > **Agents** > **Researcher** > **Critique Mode**. Paste the prompt below.',
             'prompt': PRE + "I am the Head of Operations briefing the MD tomorrow for the board review. I need a credible market brief the board cannot poke holes in. Here is exactly what I need from you. Produce a comprehensive, fully cited market brief dated 21 May 2026 from public sources within the last 90 days, with each source critiqued for credibility and freshness. Cover (1) ABB AG 2026 H1 price actions on low-voltage products globally and any APAC surcharges with named products and percentages, (2) Malaysia electrical equipment demand outlook H2 2026 — datacenter pipeline (TM Iskandar Puteri, YTL Kulai DC2, Bridge DC Cyberjaya, Princeton Digital JB1, NTT Cyberjaya 6), semicon expansions in Penang (Inari, Vitrox, Greatech, Pentamaster) and Batu Kawan (Intel, Lam Research, AT&S), EV charging roll-out (TNB Electron, Gentari, ChargeSini), effect on MV/LV switchgear and VFD demand, (3) FX outlook USD/MYR and EUR/MYR consensus for next 90 days with Maybank IB, CIMB IB, RHB views, (4) competitor moves — Rexel APAC, WESCO, Zava Group itself, plus Yee Lee Electrical, Caleffi/Frasers MY, Chip Lee, (5) one contrarian insight the market is NOT pricing in. Format: Executive Summary (3 bullets), 5 numbered sections, 'What this means' call-out box. Go as deep as the public source base supports — do not cap the length." + POST},
            {'instr':'Stay in Researcher > switch the mode pill to **Model Council**. Paste the prompt below.',
             'prompt': PRE + "I want a defensible answer to one strategic question for the MD: should Zava Electrical absorb the ABB 4.2% price increase to defend industrial customer share, fully pass it through at the risk of losing share to Rexel and WESCO, or pass through selectively by sector. Here is exactly what I need from you. Convene Researcher Model Council — get GPT and Claude to produce parallel independent assessments grounded in public ABB pricing communications, Rexel/WESCO investor commentary, and MY distributor channel commentary over the last 90 days. Surface dissent, mark majority and minority positions. Output a comparison table — Option, Council Verdict, Dissenting View, ASEAN Precedent (cite peer transaction year), 12-month margin impact estimate (RM), customer-share risk, recommended hedges. Then write a 60-word recommendation for the board deck speaker notes." + POST},
            {'instr':'Stay in Researcher > **Critique Mode**. Paste the regulatory scan prompt.',
             'prompt': PRE + "Tomorrow's board pack must not be surprised by a regulatory or policy shift. Here is exactly what I need from you. Scan public sources from the last 60 days and produce a 1-page regulatory radar for an MY electrical distributor — MIDA / MITI investment-incentive changes affecting datacenter and EV-charging customers, Bank Negara FX intervention signals and EUR/MYR / USD/MYR positioning, KPDN price-control gazettes touching electrical products, ESG-procurement gating in GLC tenders (TNB, Petronas, MMHE, Khazanah-linked datacenter operators), JKR / SIRIM standards updates on MV / LV switchgear, cross-border supply-chain controls affecting ABB / Schneider import flow through Singapore IBC. Critique each source. Output a RAG-coded table — Red same-week impact, Amber 30-90 days, Green monitor — with Owner, Counter-action, Earliest Trigger Date." + POST},
        ], DESC_RESEARCHER, persona=['Mod Admin','Mod Admin','Mod Admin']),

        # ── 3. ANALYST ──────────────────────────────────────────────────────
        tool(T_ANALYST, M365_LIC, M365_ACCT, [
            {'instr':'Open `m365.cloud.microsoft/chat` > **Agents** > **Analyst**. Attach `zava-electrical-ops-workbook.xlsx`. Paste the prompt below.',
             'prompt': PRE + "I am attaching zava-electrical-ops-workbook.xlsx (Sheets: Inventory, Orders, Variance_May2026, ROI_Summary). Run a full Python risk analysis end-to-end — code, charts and a defensible RM exposure number to put in front of the MD tomorrow. Here is exactly what I need from you. (a) Compute SKU-level inventory cover assuming demand = avg daily order quantity over the last 15 orders; for SKUs with 0 history use Reorder/30 and flag them. (b) Build a Risk Score 0–100 per order = 40×(1 if Status=BACKORDER else 0.5 if RISK else 0) + 30×clip(1−OnHand/Qty,0,1) + 30×clip(LeadTime_Days/60,0,1); output the top 10 with Customer, Brand, SKU, RM, score, dominant driver. (c) KMeans cluster customers into Strategic / Standard / At-Risk on Value_RM cumulative and avg lateness, name the customers per cluster. (d) Two charts — horizontal bar of top-10 Risk Score; scatter OnHand vs Reorder coloured by Brand (ABB, Schneider, Siemens, Legrand, Eaton). (e) 5-bullet executive summary — escalate-to-ABB-today list, At-Risk customers to call this afternoon, the single consolidated RM exposure number, two biggest data-quality issues in NetSuite, recommended next analysis." + POST},
            {'instr':'Stay in Analyst. Paste the Monte Carlo prompt.',
             'prompt': PRE + "Stress-test what happens if the ABB Helsinki backorder situation worsens. Run a Monte Carlo simulation in Python (10,000 trials) where ABB direct-fulfilment ETA on SO-44218, SO-44219, SO-44226 is drawn from a triangular distribution (min 35, mode 60, max 110 days), customer-cancellation probability rises linearly from 0% at 30 days lateness to 80% at 90 days, Singapore IBC cross-ship is available with 92% probability at 18 days lead time and RM 38k incremental freight. Here is exactly what I need from you. Output expected RM loss with and without cross-ship, P5 / P50 / P95 of total exposure, the breakeven incremental freight at which cross-ship is no longer NPV-positive, and a histogram of net P&L impact. Add a 3-bullet 'so what' for the variance-memo appendix." + POST},
            {'instr':'Stay in Analyst. Paste the network optimisation prompt.',
             'prompt': PRE + "I have 6 DCs (Shah Alam HQ, Penang, Johor Bahru, Kuching, Kota Kinabalu, Ipoh) and 7,000+ B2B customers. Last-mile cost is 20% over budget. Here is exactly what I need from you. Using the Orders sheet, model a simple network re-balance — current delivery cost as a function of straight-line distance from current Warehouse to customer site (look up MY town centroids) vs the same fulfilled from the nearest DC. Quantify the RM saving on May 2026 alone if every order had been routed from its nearest DC, identify the top 10 customer-route pairs with the worst mismatch, recommend three specific operational changes (which DC to re-stock with which SKU set, which customers to re-home, which last-mile carrier contract to renegotiate first). Output saving estimate with stated assumptions, a Lon/Lat scatter of mis-routed orders, and a one-paragraph implementation plan." + POST},
        ], DESC_ANALYST, persona=['Mod Admin','Mod Admin','Mod Admin']),

        # ── 4. EXCEL ────────────────────────────────────────────────────────
        tool(T_EXCEL, M365_LIC, M365_ACCT, [
            {'instr':'Open `zava-electrical-ops-workbook.xlsx` in Excel for the web (Sheets: Inventory · Orders · Variance_May2026 · ROI_Summary). **Copilot** (right rail) > paste the prompt below.',
             'prompt': PRE + "I have zava-electrical-ops-workbook.xlsx open with four sheets — Inventory, Orders, Variance_May2026 and ROI_Summary. I am the Zava Electrical Head of Ops and I need this turned into a working ops dashboard in 5 minutes. Apply formulas / formatting / charts to the sheets and explain in chat what you found. Ground every claim in a sheet/tab/cell reference. (1) On Inventory add DaysOfCover = OnHand / 4, conditionally format OnHand=0 red and OnHand<Reorder amber. (2) List every SKU where OnHand < Reorder AND LeadTime_Days > 30, flag 'Critical Exposure'. (3) On Orders summarise total RM at risk by Status (BACKORDER, RISK, ON-TIME) and Sector (Industrial, Commercial, Datacenter, Semicon, EV, Petronas), insert a clustered bar chart 'Risk value by Sector'. (4) Cross-check every BACKORDER/RISK against Inventory — return Order#, Warehouse, SKU, Qty, OnHand, Shortfall, ETA-from-DC. (5) On Variance_May2026 identify the 3 line items contributing most to the −RM 1.56M total, give % contribution." + POST},
            {'instr':'Stay in the workbook on the Orders sheet. **Copilot** > paste the second prompt.',
             'prompt': PRE + "I have Zava Electrical Orders open (~200 rows) with Customer, SO#, Sector, Brand, SKU, Qty, Value_RM, Status, PromiseDate, ActualDate, Warehouse, Buyer. The Procurement Steering Committee meets in 90 minutes. Here is exactly what I need from you. (1) PivotTable summarising Value_RM at risk by Buyer × Status — which of Daichi Maruyama / Hadar Caspit / Sasha Ouellet carries the most BACKORDER+RISK exposure. (2) Compute lateness in days where ActualDate > PromiseDate, add sparkline of 30-day lateness trend per buyer. (3) Top 5 customers by total RM at risk, flag any with > RM 500k cumulative across orders. (4) Add a 'Recovery Action' column on every BACKORDER suggesting 'Cross-ship from Singapore IBC' / 'Substitute Schneider equivalent' / 'Negotiate later promise date' / 'Escalate to ABB Helsinki' based on Brand and LeadTime. Apply to the sheet, summarise top 3 escalations in chat." + POST},
            {'instr':'In the same workbook switch to the ROI_Summary sheet. **Copilot** > paste the forecast prompt.',
             'prompt': PRE + "I have ROI_Summary with 12 months of revenue, gross margin %, ops KPI scores. Here is exactly what I need from you. (1) Forecast Zava Electrical monthly revenue for June, July, August 2026 with a 90% confidence interval, accounting for seasonality and the June pull-forward of the 3 slipped industrial projects (Petronas Melaka, MMHE, Lotte Chemical) worth ~RM 1.8M. (2) Compute implied gross margin trajectory under Scenario A (ABB 4.2% increase fully passed through to industrial customers from July) vs Scenario B (60% pass-through); chart both. (3) Quantify productivity uplift on Procurement + Ops + Sales + CS + HR if 220 knowledge-worker FTEs adopt Copilot at 2 hours saved per FTE per week at RM 25/hr loaded — annualised RM and headcount-equivalent. Apply formulas, build charts, write a 4-bullet summary." + POST},
        ], DESC_EXCEL, persona=['Mod Admin','Mod Admin','Mod Admin']),

        # ── 5. WORD ─────────────────────────────────────────────────────────
        tool(T_WORD, M365_LIC, M365_ACCT, [
            {'instr':'Open a blank Word document > **Copilot** (right rail) > **Draft with Copilot**. Paste the prompt below. After Copilot drafts, click **Keep it** then save to SharePoint > Zava Electrical > Board.',
             'prompt': PRE + "I am Mod Admin, Group Strategy Director at Zava Electrical. The MD wants a one-page month-end variance memo on his desk for tomorrow's board review. Here is exactly what I need from you. Draft a one-page memo titled 'May 2026 Variance Memo — Zava Electrical' for the MD. Closed numbers: Revenue actual RM 44.86M vs budget RM 43.30M (−3.6%); Industrial sales −RM 680k (three projects slipped to June — Petronas Melaka MV switchgear, MMHE topside cabling, Lotte Chemical PLC panels); Commercial sales +RM 645k (datacenter + Penang semicon strong — TM Iskandar Puteri, YTL Kulai DC2, Bridge DC Cyberjaya, Princeton Digital JB1, Inari, Vitrox); Inventory purchases over budget by RM 1.18M (EUR/MYR −3.8%, ABB low-voltage +4.2% from 1 May); last-mile logistics +RM 190k (20% over) from diesel surcharge + driver shortage; bad debt RM 190k (Tan Brothers Engineering default, 75-day overdue PO 44182). Organise as Executive Summary (3 sentences), Key Variances (bulleted RM impact + driver), Recommended Actions (5 specific owned dated bullets — EUR FX cover, last-mile carrier renegotiation, credit tightening for >60-day distributors, June pipeline pull-forward, ABB surcharge pass-through), Appendix on the three ABB ACS580 VFD backorders (Petronas Melaka SO-44218 RM 920k, Top Glove SO-44219 RM 680k, UMW Toyota SO-44226 RM 800k) with Singapore IBC cross-ship mitigation. Max 350 words, board-ready, no marketing language." + POST},
            {'instr':'Stay in the same Word doc. Highlight the **Recommended Actions** block. **Copilot** > paste the rewrite prompt.',
             'prompt': PRE + "I have the May variance memo open and the MD just messaged me to say the recommendations 'sound too soft — make them sound like decisions the board has already taken'. Here is exactly what I need from you. Rewrite the Recommended Actions so each bullet starts with an imperative active verb, names the accountable owner (Aishah for Ops, Daichi Maruyama for Procurement, Lee Wai Mun for Credit, Sasha Ouellet for Sales), gives a specific date in May or June 2026, and quantifies the expected RM benefit on a 90-day horizon. Return only the rewritten bullets in the same numbered-list format, no preamble." + POST},
            {'instr':'In the Word doc place cursor at the end. **Copilot** > paste the appendix prompt.',
             'prompt': PRE + "I need a technical appendix at the back of the May variance memo on the three ABB ACS580 VFD backorders so the MD Procurement Steering Committee tomorrow can take the cross-ship decision in 5 minutes. Here is exactly what I need from you. Build a 1-page appendix table — Customer (Petronas Melaka, Top Glove Klang, UMW Toyota Bukit Raja), SO# (44218 / 44219 / 44226), Line item (ABB ACS580-01-145A-4, 110kW VFD ×2 / 75kW VFD ×3 / 90kW VFD ×4), RM exposure (920k / 680k / 800k = 2.4M), Customer promise date, ABB Helsinki direct ETA, Singapore IBC cross-ship ETA, incremental freight, NPS/SLA risk if we miss. Add a 3-line decision recommendation — cross-ship all three from Singapore IBC, absorb the RM 38k incremental freight against May P&L, lock customer commitments in writing within 24 hours." + POST},
        ], DESC_WORD, persona=['Mod Admin','Mod Admin','Mod Admin']),

        # ── 6. POWERPOINT ───────────────────────────────────────────────────
        tool(T_PPT, M365_LIC, M365_ACCT, [
            {'instr':'Open `exec-brief-template.pptx` in PowerPoint for the web. **Copilot** (right rail) > **Create presentation from file** > attach `variance-memo.docx`. Paste the prompt below.',
             'prompt': PRE + "I have a Zava Electrical brand template open (exec-brief-template.pptx) and have attached variance-memo.docx. The Researcher market brief and the Analyst risk output are also in this chat session. The MD board review is at 9am tomorrow and the deck must look board-ready. Here is exactly what I need from you. Build a 6-slide presentation titled 'May 2026 Board Update — Variance, Risk, and the Path to RM 45M' for the Zava Electrical MD. Source from variance-memo.docx and the Researcher/Analyst outputs in this thread — do NOT invent numbers. Slides: (1) Title — 'Zava Electrical · May 2026 Board Update', 21 May 2026, Zava Electrical blue #005EB8 background, white 60pt headline, MD name and presenter. (2) May closed — RM 44.86M actual vs RM 43.30M budget waterfall, 3 negative drivers (FX+ABB, last-mile, bad debt), 1 upside (Commercial +10.4%); chart left, 5-bullet narrative right. (3) Three ABB VFD backorders — customers, RM at risk per line (920k/680k/800k=2.4M), mitigation (Singapore IBC cross-ship, RM 38k freight). (4) Market context — three bullets from Researcher (ABB H1 price action, MY datacenter outlook, FX) with footnoted citations. (5) Recommended actions — 5 bullets in active voice with owner and date. (6) The RM 45M opportunity — six-up tile across Finance / Supply Chain / Ops / Sales / CS / HR-IT with annualised RM productivity from ROI_Summary. Brand: navy #0F1C3F + Zava Electrical blue #005EB8 + accent red #C8102E + Inter/Calibri. Speaker notes 2–3 sentences per slide, MD-pitched." + POST},
            {'instr':'Stay in the deck. Highlight slide 6. **Copilot** > paste the speaker-notes prompt.',
             'prompt': PRE + "I have the 6-slide board deck open. Slide 6 is the RM 45M Copilot opportunity. The MD is a former PwC partner who will ask hard questions. Here is exactly what I need from you. Rewrite the speaker notes for slide 6 so a 90-second spoken delivery (a) anchors the productivity claim in 220 knowledge-worker FTEs, 2 hours saved per FTE per week, RM 25/hr loaded, (b) names two specific named Zava Electrical workflows per department where Copilot is already saving time (Finance — month-end variance + AR follow-up; Supply Chain — PO triage + backorder comms; Ops — DC re-stock planning + last-mile routing; Sales — quote generation + call prep; CS — ticket triage + RFQ response; HR/IT — JD drafting + helpdesk macro), (c) closes with the explicit 12-month payback and the one risk (data-classification readiness in NetSuite and SharePoint). Return only the speaker notes paragraph." + POST},
            {'instr':'Stay in the deck. **Copilot** > paste the design-pass prompt.',
             'prompt': PRE + "Aesthetic matters — the MD has seen the Zava Group HQ Paris board template and will compare. Here is exactly what I need from you. Design pass on all 6 slides — verify navy #0F1C3F primary text, Zava Electrical blue #005EB8 accent fills, accent red #C8102E only on negative variance / risk callouts, 40% whitespace, body 18-20pt, headlines 32-40pt, charts have unit suffix and a one-sentence takeaway upper-right, every slide footer 'Zava Electrical · Confidential · 21-May-2026 · MD Board Pack'. Fix any slide that breaks the rules, return a checklist of changes." + POST},
        ], DESC_PPT, persona=['Mod Admin','Mod Admin','Mod Admin']),

        # ── 7. OUTLOOK ──────────────────────────────────────────────────────
        tool(T_OUTLOOK, M365_LIC, M365_ACCT, [
            {'instr':'Open Outlook on the Web. Open the email thread "ABB Helsinki — ACS580 VFD backorder cross-ship request". Click the **Copilot icon**. Paste the prompt below.',
             'prompt': PRE + "I have an active email thread with ABB Helsinki Account Manager on the cross-ship request for SO-44218 Petronas Melaka, SO-44219 Top Glove, SO-44226 UMW Toyota. Here is exactly what I need from you. Draft a single reply email to ABB Helsinki, copying Daichi Maruyama (Procurement Lead) and the Zava Electrical Singapore IBC Account Manager. Ground in the email thread above and the Zava Electrical Orders sheet. Cover (1) restate the three SO numbers, line items (ABB ACS580-01-145A-4, 110kW ×2 / 75kW ×3 / 90kW ×4), customer promise dates, and the RM 2.4M exposure, (2) formal request to release stock from Singapore IBC for cross-ship within 18 days, (3) commit to absorbing the RM 38k incremental freight against May P&L, (4) ask ABB for a written confirmation on the Q3 ACS580 allocation to Zava Electrical so we can re-anchor the rolling forecast. Tone: firm, partnership, no margin-claim language. End with subject line and a 1-line inbox preview tuned for ABB Helsinki triage." + POST},
            {'instr':'Open Outlook > **New email**. In the new **first-draft-in-canvas** experience, Copilot drafts directly in the email body and asks clarifying questions on goal/audience/tone. Paste the prompt below and answer Copilot in canvas — no copy-paste.',
             'prompt': PRE + "Draft a customer-facing email to the Petronas Melaka Refinery Procurement Manager on the SO-44218 cross-ship plan. Copilot, in canvas, ask me 3 clarifying questions before finalising: (1) the exact revised promise date I can commit to, (2) tone (apologetic vs partnership vs supplier-of-record), (3) whether to disclose the Singapore IBC cross-ship arrangement to Petronas explicitly. After I answer, refine in place. End with a subject line and a 1-line inbox preview tuned for a Petronas Procurement Manager." + POST},
            {'instr':'Open Outlook > the high-volume distribution-team folder. Click **Copilot icon** > paste the inbox-triage prompt.',
             'prompt': PRE + "I have ~180 unread emails after a 3-hour back-to-back meeting block. I need to walk into the 4pm war-room knowing only what is genuinely urgent. Here is exactly what I need from you. Triage the inbox over the last 24 hours — surface only mail where (a) a customer named in the top-10 list (Petronas, MMHE, Lotte Chemical, TM, YTL, Bridge DC, Princeton Digital, Inari, Vitrox, UMW Toyota) is the sender or in the To line, OR (b) a brand principal (ABB, Schneider, Siemens, Legrand, Eaton, Phoenix Contact, Mersen) is the sender, OR (c) an internal escalation tag — variance, backorder, credit, FX, ESG. Output a triage table — Priority (Red/Amber/Green), Sender, Subject, Why it matters, Response window (now / today / this week), Suggested 1-line reply or 'no action'. Group by priority." + POST},
        ], DESC_OUTLOOK, persona=['Mod Admin','Mod Admin','Mod Admin']),

        # ── 8. TEAMS — meeting recap → Word minutes ─────────────────────────
        tool(T_TEAMS, M365_LIC, M365_ACCT, [
            {'instr':'**(1) In Teams**, open **Calendar** > click the past meeting **"Zava Electrical · Backorder War-Room — ABB VFDs"**. On the Recap page walk through the **AI Notes**, the **Custom summary**, and the **Audio recap** (chapter markers). **(2) In Word for the Web** open a new blank document. Type a war-room minutes template — six headings: Date and Attendees · Backorder Status by SO · Decisions Taken · Action Items · Risks and Open Questions · Customer Comms Plan. **(3) Click the Copilot icon** in the Word ribbon and paste the prompt below.',
             'prompt': "Create meeting minutes for the Teams meeting /Zava Electrical · Backorder War-Room — ABB VFDs. Use the empty war-room template already on this page and fill each heading from the meeting recap. Sections: (1) Date and Attendees (Mod Admin, Daichi Maruyama, Sasha Ouellet, Hadar Caspit, Sasha Ouellet — and any ABB Helsinki dial-in); (2) Backorder Status by SO (SO-44218 Petronas Melaka, SO-44219 Top Glove, SO-44226 UMW Toyota — with current ETA and commitment from ABB); (3) Decisions Taken; (4) Action Items with Owner and Due Date; (5) Risks and Open Questions; (6) Customer Comms Plan (who calls whom by when). Quote attendee statements verbatim where the wording matters. Tag any decision on the critical path as Critical Path."},
            {'instr':'**(1) In Teams**, open **Calendar** > click the past meeting **"Zava Electrical · May Month-End Variance Review"**. Walk the Recap page (AI Notes, Custom summary, Audio recap). **(2) In Word for the Web** open a new blank document. Type a variance-review minutes template — six headings: Date and Attendees · Variance Drivers Reviewed · Decisions Taken · Action Items · Recoveries Approved · Next Review Date. **(3) Click the Copilot icon** in the Word ribbon and paste the prompt below.',
             'prompt': "Create meeting minutes for the Teams meeting /Zava Electrical · May Month-End Variance Review. Use the empty variance-review template already on this page. Sections: (1) Date and Attendees (Mod Admin, Lee Wai Mun, Daichi Maruyama, Sasha Ouellet, MD); (2) Variance Drivers Reviewed (FX + ABB price increase, last-mile logistics, bad debt, Industrial slippage, Commercial upside); (3) Decisions Taken; (4) Action Items with Owner and Due Date; (5) Recoveries Approved (June pull-forward list, FX cover ratio, surcharge framework); (6) Next Review Date. Quote attendee statements verbatim. Highlight any variance > RM 250k in amber and any P&L decision requiring MD sign-off in red."},
            {'instr':'**(1) In Teams**, open **Calendar** > click the past meeting **"Zava Electrical · ABB Helsinki Quarterly Business Review"**. Walk the Recap page. **(2) In Word for the Web** open a new blank document. Type a vendor-QBR minutes template — seven headings: Vendor and Owner · Commercial Terms Discussed · Concessions Offered · Concessions Accepted · Open Items · Approval Thresholds · Next Steps. **(3) Click the Copilot icon** in the Word ribbon and paste the prompt below — then forward the result to Procurement, Finance, and the MD.',
             'prompt': "Create meeting minutes for the Teams meeting /Zava Electrical · ABB Helsinki Quarterly Business Review. Use the empty vendor-QBR template already on this page. Sections: (1) Vendor (ABB Helsinki) and Owner (Daichi Maruyama); (2) Commercial Terms Discussed (4.2% LV price increase, ACS580 allocation, Singapore IBC stock split, surcharge structure); (3) Concessions Offered by ABB; (4) Concessions Accepted by Zava Electrical; (5) Open Items; (6) Approval Thresholds (MD / Group Procurement Paris); (7) Next Steps with Owner and Due Date. Highlight any term requiring MD sign-off in amber and any term requiring Zava Group Paris sign-off in red. Email the link to Daichi Maruyama (Procurement), Lee Wai Mun (Finance), and the MD."}
        ], DESC_TEAMS, persona=['Mod Admin','Mod Admin','Mod Admin']),

        # ── 9. NOTEBOOK ─────────────────────────────────────────────────────
        tool(T_NOTEBOOK, M365_LIC, M365_ACCT, [
            {'instr':'All sources are loaded. Type the prompt below in the notebook chat.',
             'prompt':'Synthesise across all sources to produce a 12-bullet MD Board Pre-Read. Cover (1) May revenue close vs budget + top three variance drivers with RM impact; (2) three ABB ACS580 VFD backorders — customer / SO# / RM exposure / customer promise date / ABB Helsinki ETA / Singapore IBC cross-ship ETA; (3) datacenter + semicon upside signal with named customers and RM contribution; (4) last-mile cost over-run + proposed carrier renegotiation timeline; (5) Tan Brothers bad-debt status + credit-tightening trigger; (6) FX + ABB price-increase pass-through framework for July onwards; (7) the five Recommended Actions restated with owner / due date / RM benefit; (8) the single consolidated RM exposure number for tomorrow; (9) two questions the MD will ask + the data-grounded answer for each; (10) one contrarian risk the board is not focused on; (11) the decision the board must take in 48 hours; (12) the follow-up war-room owner and time. Cite the source file at the end of every bullet.'},
            {'instr':'Click **Quick Create** > **Audio Overview** to generate a 7-minute briefing podcast.',
             'prompt':'Quick Create: Audio Overview, 7 minutes, formal narration tone, focused on the 12-bullet MD Board Pre-Read above. Listeners are the Zava Electrical ExCo (MD, Head of Ops Aishah, Head of Sales Razif, Procurement Lead Suresh, Finance Director Lee Wai Mun) on their commute to tomorrow 9am board review. Open with the headline RM exposure number, walk the three ABB VFD backorders, the May variance close, the datacenter+semicon upside, the recommended actions with owners and due dates, close with the contrarian risk and the 48-hour board decision.'},
            {'instr':'Click **Quick Create** > **Page** to spin off a shareable artefact for the war-room.',
             'prompt':"Quick Create: Page titled 'Zava Electrical · Board Pre-Read 22-May-2026'. Lift the 12-bullet synthesis above, format as a clean shareable page — sections Headlines, Variance, Backorders, Upside, Recommendations, Decisions Requested. Add an inline RAG-coded table for the three ABB VFD backorders. Footer cites every source file used. Share to the #zava-electrical-ops-leads Teams channel so Razif, Suresh, Mei Ling and Lee Wai Mun can co-edit before 9am."}
        ], DESC_NOTEBOOK,
        persona=['Mod Admin','Mod Admin','Mod Admin'],
        notebookMeta={
            'sources':['/variance-memo.docx', '/zava-electrical-ops-workbook.xlsx', '/exec-brief-template.pptx', '/customer-rfq.docx', '/month-end-variance.md'],
            'instructions':'You are Mod Admin, Group Strategy Director at Zava Electrical, building the MD board pre-read for tomorrow 9am. Always cite the source file and the specific sheet/tab/section. Tone: principal-grade, factual, board-ready, no marketing language and no speculation about ABB, Schneider, Siemens, Legrand, Eaton or competitor intent beyond what is in writing in the sources. Use RM (Ringgit Malaysia) for all figures. Reference named Zava Electrical people (Daichi Maruyama — Procurement, Sasha Ouellet — Sales, Lee Wai Mun — Finance, Hadar Caspit — buyer, Sasha Ouellet — IT), real Malaysian customers (Petronas Melaka Refinery, MMHE, Lotte Chemical, Top Glove Klang, UMW Toyota Bukit Raja, TM Iskandar Puteri, YTL Kulai DC2, Bridge DC Cyberjaya, Princeton Digital JB1, Inari Penang, Vitrox Batu Kawan, Tan Brothers Engineering) and real brand principals (ABB AG Helsinki + Singapore IBC, Schneider Electric, Siemens, Legrand, Eaton, Phoenix Contact, Mersen). Cross-reference the variance memo against the workbook on every quantitative claim. If a number cannot be tied back to a source, flag it explicitly with the follow-up question Aishah should ask before the board.',
        }),

        # ── 10. COWORK ──────────────────────────────────────────────────────
        tool(T_COWORK, FRONTIER_LIC, M365_ACCT, [
            {'instr':'Open `m365.cloud.microsoft` > Agents > **Cowork** (Frontier program — Claude). Attach `variance-memo.docx`, `zava-electrical-ops-workbook.xlsx`, `exec-brief-template.pptx`. Paste the goal below. Watch the dashboard stream each step; approve sensitive sends.',
             'prompt': PRE + "Goal — get me ready for the MD's Monday review by 9am tomorrow. Context: I am Mod Admin, Group Strategy Director at Zava Electrical. The MD Monday review is at 9am 22-May-2026. You have access to my variance-memo.docx, zava-electrical-ops-workbook.xlsx, exec-brief-template.pptx, Outlook, Teams, SharePoint, OneDrive. Plan and execute the following as an autonomous workflow — show each step in the task dashboard and PAUSE for my approval before any external send. (1) Read variance-memo.docx and the Orders + Variance_May2026 sheets. Produce a 5-bullet 'What the MD needs to know'. (2) Identify the three ABB ACS580 VFD backorders (SO-44218 Petronas Melaka, SO-44219 Top Glove, SO-44226 UMW Toyota), look up the responsible buyer (Daichi Maruyama) in Outlook, prepare a draft email to ABB Helsinki Account Manager requesting Singapore IBC cross-ship — hold for my approval. (3) Build the MD board deck from exec-brief-template.pptx using the variance numbers and the Researcher market brief in this chat. Save to SharePoint > Zava Electrical > Board > 'MD Board Update 22-May-2026.pptx'. (4) Schedule a 30-minute 'Backorder war-room' in Teams for today 4pm KL with @Procurement (Daichi Maruyama), @Sales (Sasha Ouellet), @Aishah — hold the invite for approval. (5) Draft a SharePoint List 'May variance follow-ups' on the Zava Electrical Ops site with 5 items (EUR FX-cover review — Hadar Caspit 23 May; last-mile carrier renegotiation — Sasha Ouellet 30 May; credit-limit tightening — Hadar Caspit 28 May; June pull-forward kickoff — Mod Admin 24 May; ABB surcharge pass-through — Daichi Maruyama 27 May) each assigned with a due date. (6) Draft a Teams message to the MD linking the SharePoint deck, the SharePoint List, and including the single consolidated RM exposure number from Analyst — hold for approval. Use Frontier Claude model. Stop and ask me if any step needs a judgement call." + POST},
            {'instr':'Same Cowork session after step 6 completes. Paste the overnight-monitoring goal.',
             'prompt': PRE + "Second goal — between now (9pm 21-May) and 7:30am tomorrow (22-May), watch my inbox + Teams for any ABB Helsinki reply, any Petronas / Top Glove / UMW Toyota escalation, and any MD message. Here is exactly what I need from you. (a) If ABB Helsinki replies on the cross-ship request, summarise in plain English, post to #zava-electrical-ops-leads tagging Suresh — DO NOT auto-reply to ABB without approval. (b) If any of the three backorder customers sends a follow-up, prioritise Red, draft a holding reply that does not over-promise, hold for approval at 7:30am. (c) If the MD messages, send a phone-friendly summary to my Teams mobile, do not respond. (d) At 7:30am sharp post a 'Monday Morning Briefing' Copilot Page to #zava-electrical-ops-leads with overnight events, the war-room outcome, the consolidated risk position, the deck link, and my top 3 priorities for the day. Stream every step in the dashboard." + POST},
            {'instr':'Same Cowork session. Paste the RM 45M rollout goal.',
             'prompt': PRE + "Third goal — the MD will ask 'how do we get the RM 45M Copilot productivity story moving in the next 60 days'. Plan and propose (do NOT execute external sends without approval). (1) Draft a 60-day Copilot adoption plan across Finance, Supply Chain, Operations, Sales, CS, HR/IT — 220 knowledge-worker FTEs, target 2 hours saved per FTE per week, anchor on ROI_Summary. (2) Identify a named workstream owner per function (Lee Wai Mun — Finance, Daichi Maruyama — Supply Chain, Mod Admin — Operations, Sasha Ouellet — Sales, Sasha Ouellet — CS, Sasha Ouellet — HR/IT). (3) Schedule six 30-minute kickoff meetings across this week and next, hold each invite for approval. (4) Create a SharePoint site section 'Zava Electrical Copilot — RM 45M' with one page per function, each with 3 starter use cases, the named owner, the success metric, the 30/60/90-day milestones. (5) Draft a one-page MD memo summarising the plan, save to SharePoint > Zava Electrical > Strategy. Stream every step, pause for approval on invites and the MD memo." + POST},
        ], DESC_COWORK, persona=['Mod Admin','Mod Admin','Mod Admin']),

        # ── 11. WORD AGENT ──────────────────────────────────────────────────
        tool(T_WORD_AGT, ANY_LIC, ANY_ACCT, [
            {'instr':'Open `m365.cloud.microsoft/chat` and sign in. In the prompt box click the **Tools** menu (or **Agents** menu) and choose **Word**. Paste the prompt below — Copilot generates a complete `.docx` preview in chat, asks any clarifying questions, then saves to OneDrive. Works **with or without** a Microsoft 365 Copilot license.',
             'prompt': PRE + "Zava Electrical MD Board Pack for the 22-May 9am review. Here is exactly what I need from you. Generate a 4-page MD Board Brief in Word covering Toyota-style sectional structure — Executive Summary 5 bullets; Current Status (May variance close + the three ABB ACS580 VFD backorders + datacenter/semicon upside); Programme; Financial Impact bridge; Stakeholder Map (ABB Helsinki / Schneider / Siemens / Legrand / Eaton / Petronas / Top Glove / UMW Toyota / TM / YTL / Bridge DC / Princeton Digital); Decisions requested. Ground every section in /variance-memo.docx AND /zava-electrical-ops-workbook.xlsx. Tone: principal-grade, board-ready, no marketing language. Save as ZavaElectrical_MD_Board_Brief.docx." + POST},
            {'instr':'Stay in chat and paste the second prompt.',
             'prompt': PRE + "Zava Electrical customer-facing response on the ABB VFD backorders. Here is exactly what I need from you. Generate a 1-page customer letter in Word addressed to the Petronas Melaka Refinery Procurement Manager on SO-44218. Ground in /zava-electrical-ops-workbook.xlsx (Orders sheet). Cover the SO details (line item, qty, original promise date), the cross-ship plan from Singapore IBC with the revised committed date, the Zava Electrical accountable contact (Daichi Maruyama, Procurement Lead), and an unequivocal commitment statement. Tone: accountable, partnership, no excuses. Save as ZavaElectrical_Petronas_SO44218_Cross-Ship_Commitment.docx." + POST}
        ], DESC_WORD_AGT, persona=['Mod Admin','Mod Admin']),

        # ── 12. POWERPOINT AGENT ────────────────────────────────────────────
        tool(T_PPT_AGT, ANY_LIC, ANY_ACCT, [
            {'instr':'Open `m365.cloud.microsoft/chat` and sign in. In the prompt box click the **Tools** menu (or **Agents** menu) and choose **PowerPoint**. Paste the prompt below — Copilot generates a complete `.pptx` preview in chat, asks any clarifying questions on theme/audience/slide count, then saves to OneDrive. Works **with or without** a Microsoft 365 Copilot license.',
             'prompt': PRE + "Zava Electrical MD board review tomorrow 9am. Here is exactly what I need from you. 9-slide MD Board Update deck — Cover; May Variance Close (waterfall); ABB VFD Backorder Situation; Datacenter + Semicon Upside; Market Context (ABB H1 price / FX / competitor); Recommended Actions; RM 45M Copilot Opportunity; Risks and Mitigations; Decisions Requested. Ground every slide in /ZavaElectrical_MD_Board_Brief.docx and /zava-electrical-ops-workbook.xlsx. Brand navy #0F1C3F + Zava Electrical blue #005EB8 + accent red #C8102E. One chart per slide. Speaker notes 2-3 sentences per slide. Save as ZavaElectrical_MD_Board_Update_Deck.pptx." + POST},
            {'instr':'Stay in chat and paste the second prompt.',
             'prompt': PRE + "Zava Electrical ExCo internal cascade deck. Here is exactly what I need from you. 6-slide ExCo Cascade Deck after the MD board review, audience is the function heads (Finance, Supply Chain, Operations, Sales, CS, HR/IT). Cover; Headline Outcomes from Board; Owner-by-Owner Action Tracker (Aishah / Suresh / Razif / Lee Wai Mun / Sasha / Hairul); RM 45M Copilot 60-Day Plan; Risk and Escalation Path; Next Two Weeks. Brand same Zava Electrical palette. Save as ZavaElectrical_ExCo_Cascade_Deck.pptx." + POST}
        ], DESC_PPT_AGT, persona=['Mod Admin','Mod Admin']),

        # ── 13. EXCEL AGENT ─────────────────────────────────────────────────
        tool(T_XL_AGT, ANY_LIC, ANY_ACCT, [
            {'instr':'Open `m365.cloud.microsoft/chat` and sign in. In the prompt box click the **Tools** menu (or **Agents** menu) and choose **Excel**. Paste the prompt below — Copilot generates a complete `.xlsx` preview in chat, asks any clarifying questions on sheets/columns/charts, then saves to OneDrive. Works **with or without** a Microsoft 365 Copilot license.',
             'prompt': PRE + "Zava Electrical MD operating tracker. Here is exactly what I need from you. Build a Zava Electrical Board Action Tracker workbook. Sheet 1 — Recommended Actions Tracker (5 rows from the variance memo, columns Owner, Action, Due Date, RM Benefit 90-day, Status, Last Update). Sheet 2 — ABB VFD Backorder Tracker (3 rows for SO-44218 / SO-44219 / SO-44226 with Customer, Line Item, RM Exposure, ABB Helsinki ETA, Singapore IBC Cross-ship ETA, Committed Customer Date, Status). Sheet 3 — Top 10 Customer Watchlist (Petronas / MMHE / Lotte / TM / YTL / Bridge DC / Princeton Digital / Inari / Vitrox / UMW Toyota with Account Manager, YTD revenue, Open Exposure, Sentiment RAG, Next Touchpoint). Sheet 4 — Dashboard with KPI tiles + RAG conditional formatting. Save as ZavaElectrical_Board_Action_Tracker.xlsx." + POST},
            {'instr':'Stay in chat and paste the second prompt.',
             'prompt': PRE + "Zava Electrical 60-day Copilot rollout model. Here is exactly what I need from you. Build a Zava Electrical Copilot RM 45M Rollout Model workbook. Sheet 1 — FTE Inventory (220 knowledge-worker FTEs by function — Finance / Supply Chain / Operations / Sales / CS / HR-IT — with hours saved per week assumption and RM 25/hr loaded). Sheet 2 — Use Case Backlog (3 starter use cases per function, each with effort score, ROI score, named owner). Sheet 3 — 30/60/90-day Milestone Tracker (6 rows — one per function, with kickoff / pilot / scale / measure milestones). Sheet 4 — Dashboard tile — Annualised RM saving, FTE-equivalent, % adoption. RAG conditional formatting. Save as ZavaElectrical_Copilot_RM45M_Rollout_Model.xlsx." + POST}
        ], DESC_XL_AGT, persona=['Mod Admin','Mod Admin']),

        # ── 14. AGENT BUILDER (paid — file knowledge) ───────────────────────
        tool(T_BUILDER, M365_LIC, M365_ACCT, [
            {'instr':'Open `m365.cloud.microsoft/chat` > **Agents** > **+ Create an agent**. Describe the agent below, then in Configure add the knowledge files listed, set the instructions and 4 starter prompts, Test in the right pane, then **Create + share** to the #zava-electrical-ops-leads Teams channel. Submit for admin approval to publish into the Agent Store "Built by your org" catalog.',
             'prompt':"Describe — Build an 'MD Board Briefing Bot' that answers any executive question on the May 2026 month-end close, the three ABB ACS580 VFD backorders (Petronas Melaka SO-44218, Top Glove SO-44219, UMW Toyota SO-44226), the datacenter + semicon upside pipeline, and the recommended actions from the variance memo. Grounded ONLY on internal documents — not the public web. Configure — Knowledge: /variance-memo.docx, /zava-electrical-ops-workbook.xlsx, /month-end-variance.docx, /roi-summary.xlsx, /customer-rfq.docx. Instructions: 'You are the MD Board Briefing Bot for the Head of Operations. Always cite the source file and the specific sheet/tab/section. Tone: principal-grade, factual, board-ready, no marketing language. Use RM for all figures. Reference named buyers (Daichi Maruyama, Hadar Caspit, Sasha Ouellet), named customers (Petronas Melaka, MMHE, Lotte Chemical, Top Glove Klang, UMW Toyota Bukit Raja, TM Iskandar Puteri, YTL Kulai DC2, Bridge DC Cyberjaya, Princeton Digital JB1, Inari Penang, Vitrox Batu Kawan), and named principals (ABB Helsinki + Singapore IBC, Schneider, Siemens, Legrand, Eaton). If a number cannot be tied back to a source, say so explicitly and propose the follow-up question. Never speculate about ABB or competitor intent beyond what is in writing in the sources.' Starter prompts: (1) 'What are the top 3 variance drivers in May 2026 and the RM impact of each?' (2) 'For each of the three ABB VFD backorders, give SO#, customer, RM exposure, customer promise date, ABB Helsinki ETA, Singapore IBC cross-ship ETA.' (3) 'Which 5 customers carry the biggest open RM exposure right now and which Account Manager owns each?' (4) 'Restate the 5 Recommended Actions with owner, due date, and 90-day RM benefit.'"},
            {'instr':'Open `m365.cloud.microsoft/chat` > **Agents** > **+ Create an agent**. Same 4-step flow. Build a second, sales-facing agent.',
             'prompt':"Describe — Build a 'Sales Quote Coach' agent that helps Zava Electrical account managers draft customer quotes faster. Grounded on the product catalogue, prior RFQs, and the active price book — never speculative. Configure — Knowledge: /product-catalog.xlsx, /customer-rfq.docx, /zava-electrical-ops-workbook.xlsx (Orders sheet for prior comparable transactions). Instructions: 'You are the Sales Quote Coach for Zava Electrical account managers. For any customer + product request, return — recommended SKU(s) with brand, list price RM, last comparable transaction (customer, RM, date, margin), the three substitutes if the primary brand is on backorder (Schneider for ABB, ABB for Schneider, etc.), suggested discount band by customer tier (Strategic / Standard / At-Risk), the three risks to flag in the quote footer, and the standard payment terms by sector. Tone: confident, helpful, never over-promise on availability. Always cite the source file and row.' Starter prompts: (1) 'Customer Petronas Melaka, need ABB ACS580 VFD 110kW, qty 2 — give me a draft quote.' (2) 'Top Glove Klang asks for an MV switchgear alternative to ABB — what should I propose?' (3) 'YTL Kulai DC2 datacenter — give me the standard quote bundle for a 6MW IT-room build.' (4) 'What was the last margin we got on a Siemens 1500kVA transformer to TM?'"}
        ], DESC_BUILDER, persona=['Mod Admin','Sasha Ouellet']),

        # ── 15. AGENT BUILDER FREE (free tier — URL knowledge) ──────────────
        tool(T_BUILDER_FREE, FREE_LIC, FREE_ACCT, [
            {'instr':'Open `m365.cloud.microsoft/chat` on a **Free Copilot Chat** account (no paid Copilot license) > **Agents** > **+ Create an agent**. Describe the agent, in Configure add only public URLs as knowledge sources, set instructions and starter prompts, Test, then Create + share.',
             'prompt':"Describe — Build a 'Brand Principal Pulse' agent that tracks public news on Zava Electrical's brand principals (ABB, Schneider Electric, Siemens, Legrand, Eaton, Phoenix Contact, Mersen). Citizen-developer style, zero IT involvement, zero cost. Configure — Knowledge URLs only (no file uploads): https://new.abb.com/news, https://www.se.com/ww/en/about-us/newsroom/news/, https://press.siemens.com/global/en, https://www.legrand.com/en/news, https://www.eaton.com/us/en-us/company/news-insights.html, https://www.phoenixcontact.com/en-id/about-us/newsroom, https://www.mersen.com/news. Instructions: 'You are the Brand Principal Pulse for Zava Electrical. For any user query, scan the public press-release pages of the brand principals listed in your knowledge URLs and return — release date, principal, headline, the one-line takeaway for an MY distributor (price action / allocation / new product / management change / sustainability claim / partnership), and the link. Cite every claim with the source URL. Only include items published in the last 30 days unless the user asks for a longer window.' Starter prompts: (1) 'Any ABB price-action announcements in the last 30 days affecting APAC distributors?' (2) 'What has Schneider published on datacenter products in the last 60 days?' (3) 'Has Siemens announced any new SEA partnership or DC investment recently?' (4) 'Aggregate sustainability / ESG announcements across all 7 principals in the last 90 days.'"},
            {'instr':'Open `m365.cloud.microsoft/chat` on a **Free Copilot Chat** account > **Agents** > **+ Create an agent**. Build a second, customer-pulse agent.',
             'prompt':"Describe — Build a 'Top-10 Customer Pulse' agent that tracks public news on Zava Electrical's top customers and the MY datacenter / semicon build-out. Configure — Knowledge URLs only: https://www.petronas.com/media, https://www.mmhe.com.my/news, https://www.lottechem.my/en/Media-Centre, https://www.topglove.com/media, https://www.umw.com.my/news, https://www.tm.com.my/about/newsroom, https://www.ytl.com/news, https://www.bridgedc.com/news, https://www.princetondigital.com/news, https://www.inari-amertron.com/news, https://www.vitrox.com/news, https://www.mida.gov.my/news. Instructions: 'You are the Top-10 Customer Pulse for Zava Electrical. For any user query, scan the public newsrooms in your knowledge URLs and return — release date, customer, headline, the one-line takeaway for an electrical distributor (capex announcement / new site / management change / financing round / supplier programme), and the source link. Cite every claim. Only include items published in the last 30 days unless the user asks for a longer window.' Starter prompts: (1) 'Has Petronas Melaka announced any new turnaround or shutdown maintenance window?' (2) 'What is the latest Bridge DC or Princeton Digital capex / new-site news?' (3) 'Penang semicon — any new fab or expansion announcement from Inari, Vitrox, or AT&S?' (4) 'Aggregate MIDA + MITI announcements affecting datacenter and EV charging in the last 60 days.'"}
        ], DESC_BUILDER_FREE, persona=['Mod Admin','Sasha Ouellet']),
    ],

    # ── Storyboard — 30-minute live demo arc (unchanged) ────────────────────
    storyboard=[
        {
            'ex': 1,
            'title': '0–10 min · Set the Scene — Variance Memo + Market Brief',
            'titleID': '0–10 menit · Set the Scene — Memo Varian + Market Brief',
            'minutes': 10,
            'mode': 'Show & Tell',
            'summary': 'Aishah opens a blank Word doc, drafts the May variance memo with Copilot in 90 seconds. Then she flips to Copilot Researcher in Critique + Model Council mode to pull a fully cited market brief on ABB H1 pricing, MY datacenter demand and FX outlook. Two deliverables, two minutes of Copilot time.',
            'summaryID': 'Aishah membuka dokumen Word kosong, draft memo varian Mei dengan Copilot dalam 90 detik. Kemudian beralih ke Copilot Researcher mode Critique + Model Council untuk market brief bersitasi penuh tentang harga ABB H1, demand datacenter MY dan outlook FX.',
            'tasks': [
                {'verb':'Draft the May variance memo from closed numbers + ABB backorder appendix','verbID':'Draft memo varian Mei dari angka tertutup + lampiran backorder ABB','toolId':T_WORD,'mode':'Show & Tell'},
                {'verb':'Run Researcher Critique + Model Council for the MD market brief','verbID':'Jalankan Researcher Critique + Model Council untuk market brief MD','toolId':T_RESEARCHER,'mode':'Show & Tell'},
            ],
        },
        {
            'ex': 2,
            'title': '10–20 min · Analyse & Decide — Workbook + Python Risk',
            'titleID': '10–20 menit · Analisis & Keputusan — Workbook + Python Risk',
            'minutes': 10,
            'mode': 'Hands-on',
            'summary': 'Switch to zava-electrical-ops-workbook.xlsx — Excel Copilot adds DaysOfCover, applies conditional formatting, builds the risk-by-sector chart, and cross-checks every BACKORDER against on-hand. Then hand off to Analyst — a full Python Monte Carlo on the three ABB VFD backorders gives the MD a defensible single RM exposure number with P5 / P50 / P95.',
            'summaryID': 'Beralih ke zava-electrical-ops-workbook.xlsx — Excel Copilot menambahkan DaysOfCover, conditional formatting, chart risk-by-sector, dan cross-check setiap BACKORDER. Lalu serahkan ke Analyst — Monte Carlo Python pada 3 backorder ABB VFD memberi MD angka exposure tunggal P5/P50/P95.',
            'tasks': [
                {'verb':'Apply DaysOfCover, conditional formatting, risk-by-sector chart, backorder cross-check','verbID':'Terapkan DaysOfCover, conditional formatting, chart risk-by-sector, cross-check backorder','toolId':T_EXCEL,'mode':'Hands-on'},
                {'verb':'Run the Python risk-score model + Monte Carlo on the three ABB VFD backorders','verbID':'Jalankan Python risk-score + Monte Carlo pada 3 backorder ABB VFD','toolId':T_ANALYST,'mode':'Hands-on'},
            ],
        },
        {
            'ex': 3,
            'title': '20–25 min · Communicate & Coordinate — Deck + Grounded Copilot Page',
            'titleID': '20–25 menit · Komunikasi & Koordinasi — Deck + Grounded Copilot Page',
            'minutes': 5,
            'mode': 'Hands-on',
            'summary': 'PowerPoint Copilot builds the 6-slide MD board deck from the variance memo, the market brief, and the brand template in under 60 seconds. Aishah switches to Copilot Chat, runs ONE grounded query across Outlook, Teams, SharePoint, the workbook and the live web on the three backorders, then turns the answer into a Copilot Page co-edited live by Procurement and Sales.',
            'summaryID': 'PowerPoint Copilot membangun deck 6-slide untuk MD dari memo varian, market brief, dan brand template dalam <60 detik. Aishah beralih ke Copilot Chat, satu query grounded di Outlook/Teams/SharePoint/workbook/web — diubah jadi Copilot Page yang di-co-edit Procurement & Sales.',
            'tasks': [
                {'verb':'Generate the 6-slide board deck from template + variance memo + Researcher brief','verbID':'Generate deck 6-slide dari template + memo varian + Researcher brief','toolId':T_PPT,'mode':'Hands-on'},
                {'verb':'Run grounded multi-source query and promote it to a shared Copilot Page','verbID':'Jalankan query grounded multi-source dan promote ke Copilot Page bersama','toolId':T_CHAT,'mode':'Hands-on'},
            ],
        },
        {
            'ex': 4,
            'title': '25–30 min · Cowork — The Autonomous AI Coworker',
            'titleID': '25–30 menit · Cowork — Rekan Kerja AI Otonom',
            'minutes': 5,
            'mode': 'Show & Tell',
            'summary': 'One goal statement — "Get me ready for the MD review by 9am tomorrow" — and Cowork (Frontier program, Claude) plans the workflow itself, streams every step on the task dashboard, and pauses for approval on the ABB Helsinki email, the war-room Teams invite, and the MD message. End the demo with the dashboard live — six tasks in flight, three queued for approval, and Aishah closing her laptop.',
            'summaryID': 'Satu pernyataan tujuan — "Siapkan saya untuk review MD jam 9 pagi besok" — dan Cowork (Frontier, Claude) merencanakan workflow sendiri, streaming setiap langkah di dashboard, dan menjeda untuk persetujuan email ABB Helsinki, invite Teams war-room, dan pesan MD.',
            'tasks': [
                {'verb':'Issue one autonomous goal to Cowork (Frontier, Claude) — watch dashboard + approval pauses','verbID':'Berikan satu tujuan otonom ke Cowork (Frontier, Claude) — pantau dashboard + jeda persetujuan','toolId':T_COWORK,'mode':'Show & Tell'},
            ],
        },
    ],

    personas=[
        {'name':'Mod Admin','role':'Head of Operations · Zava Electrical','roleID':'Kepala Operasi · Zava Electrical','acct':'admin@ABSx62256373.onmicrosoft.com','lic':'Microsoft 365 Copilot','color':'#005EB8'},
        {'name':'Daichi Maruyama','role':'Procurement Lead · Zava Electrical','roleID':'Kepala Pengadaan · Zava Electrical','acct':'admin@ABSx62256373.onmicrosoft.com','lic':'Microsoft 365 Copilot','color':'#0F1C3F'},
        {'name':'Sasha Ouellet','role':'Head of Sales · Zava Electrical','roleID':'Kepala Penjualan · Zava Electrical','acct':'admin@ABSx62256373.onmicrosoft.com','lic':'Microsoft 365 Copilot','color':'#C8102E'},
        {'name':'Lee Wai Mun','role':'Finance Director · Zava Electrical','roleID':'Direktur Keuangan · Zava Electrical','acct':'admin@ABSx62256373.onmicrosoft.com','lic':'Microsoft 365 Copilot','color':'#059669'}
    ],
    geo='MY'
))

print(f"Industries batch 13 written: {len(INDUSTRIES_13)} entries")
