
import sys; sys.path.insert(0,'.')
from util import *

INDUSTRIES_4 = [

# ── OG DOWNSTREAM ──────────────────────────────────────────────────────────
ind('og-downstream','og-energy','Oil & Gas — Downstream','🏭','#BF360C','#D84315',
    'HengYuan Refining Sdn Bhd',
    'Refinery margin at USD 4.2/bbl — DOSH CIMAH audit in 8 weeks.',
    'HengYuan Refining operates Malaysia\'s second-largest crude oil refinery with 156,000 bbl/day capacity. Refinery margins have compressed to USD 4.2/bbl (breakeven at USD 5.8/bbl) driven by MOPS crack spread compression. A DOSH CIMAH (Control of Industrial Major Accident Hazards) audit is scheduled in 8 weeks. A major maintenance turnaround is being planned for Q3.',
    ['OG_01_Nusantara_Energy.xlsx','OG_02_Nusantara_HSE_Report.docx'],
    [
      tool(T_CHAT, FREE_LIC, FREE_ACCT, [
        'I am the CFO of a Malaysian crude oil refinery. Our refinery margin has compressed to USD 4.2 per barrel — below our breakeven of USD 5.8/bbl — driven by MOPS crack spread compression and rising crude differentials. Draft a 300-word margin recovery briefing for our Board. Cover: the key drivers of margin compression, three operational levers we can pull to improve margin within 90 days (without capital investment), and the crude slate optimisation opportunity given current Middle East vs North African crude price differentials.',
        'Explain the DOSH CIMAH (Control of Industrial Major Accident Hazards) Regulations 1996 for a petroleum refinery in Malaysia. What are the key obligations, the documentation required, and the consequences of a failed CIMAH audit? Keep it under 200 words for a non-technical Board member.',
        'What are the main components of a refinery maintenance turnaround (T/A) and what are the typical cost and production loss risks? Describe the best practices for turnaround planning that minimise production downtime and cost overrun, specifically for a complex refinery in Southeast Asia.'
      ]),
      tool(T_RESEARCHER, M365_LIC, M365_ACCT, [
        'Research the current MOPS (Mean of Platts Singapore) crack spread trends for Asian refineries and the outlook for the next 6 months. What is driving the compression? Which product slates (gasoline, diesel, jet fuel) are most and least affected? Cite recent energy market reports or commodity trading publications.',
        'Research DOSH Malaysia\'s CIMAH enforcement trends for petroleum refineries in 2023–2025. What are the most common audit findings? Have any refineries received improvement orders or stop-work orders? What documentation do DOSH auditors typically request on the first day of inspection? Provide citations.'
      ], DESC_RESEARCHER),
      tool(T_ANALYST, M365_LIC, M365_ACCT, [
        'Upload OG_01_Nusantara_Energy.xlsx (use as refinery operations proxy). Ask Analyst: Analyse refinery margin data over the past 8 quarters. Decompose the margin into: crude differential, product realisation (by product slate), variable operating cost, and fixed cost per barrel. Which component has deteriorated most? Show as a waterfall chart from peak margin to current margin.',
        'Upload OG_01_Nusantara_Energy.xlsx. Ask: Build a crude slate optimisation analysis. Compare three crude blends available to us — Arab Light, Murban, and Basrah Heavy — showing for each: (1) current spot price vs our long-term contract price, (2) API gravity and sulphur content, (3) estimated product yield by category, (4) net margin contribution per barrel. Recommend the optimal crude slate mix for the next quarter.'
      ], DESC_ANALYST),
      tool(T_EXCEL, M365_LIC, M365_ACCT, [
        'Open OG_01_Nusantara_Energy.xlsx. Navigate to the Refinery Operations sheet. Ask Copilot: Build a margin sensitivity model on a new sheet. Show how the refinery margin changes for every USD 1/bbl move in the MOPS crack spread and every USD 0.50/bbl change in crude differential. Create a 6x6 sensitivity table (crack spread vs crude differential) showing the resulting margin and highlight in green cells above breakeven (USD 5.8/bbl) and red cells below.',
        'Ask Copilot: Create a turnaround planning model on a new sheet. The planned Q3 turnaround will take 28 days and shut down Units 3 and 5. Calculate: (1) Total production loss in barrels assuming 80,000 bbl/day from those units, (2) Revenue loss at current margin of USD 4.2/bbl, (3) Fixed cost absorption loss, (4) Net P&L impact of the turnaround. Compare against the cost of deferring the turnaround by 6 months.',
        'Ask Copilot: In the CIMAH Compliance sheet, identify all major hazard installations (MHIs) that are due for re-inspection within the next 12 months. For each, show the last inspection date, the next due date, the responsible engineer, and whether the pre-inspection documentation is complete. Flag in red any MHI where documentation is incomplete and the inspection is less than 60 days away.'
      ]),
      tool(T_WORD, M365_LIC, M365_ACCT, [
        'Open OG_02_Nusantara_HSE_Report.docx. Ask Copilot: Draft a DOSH CIMAH pre-audit submission letter. The letter should: confirm our readiness for the scheduled audit, provide a summary of our major hazard risk assessment updates since the last audit, list the key safety-critical equipment that has been tested and certified in the past 12 months, and request 20 minutes for a management presentation at the start of the audit.',
        'Ask Copilot: Create a CIMAH Safety Report executive summary of 500 words. Cover: (1) description of the hazardous substances on site and quantities relative to CIMAH thresholds, (2) the major accident scenarios identified in our HAZOP/QRA, (3) the safety systems in place to prevent and mitigate each scenario, (4) the emergency response plan and last drill date. Use formal regulatory language.',
        'Ask Copilot: Draft the turnaround scope-of-work document for Units 3 and 5. Structure: (1) objective of the turnaround, (2) equipment list for inspection and maintenance, (3) critical path activities, (4) contractor safety requirements, (5) permit-to-work framework during T/A, (6) restoration and recommissioning criteria. Keep it to 3 pages.'
      ]),
      tool(T_PPT, M365_LIC, M365_ACCT, [
        'Ask Copilot in PowerPoint: Create a 10-slide Board presentation on Refinery Performance and Margin Recovery. Include: (1) Current margin position vs breakeven, (2) Margin decomposition waterfall, (3) MOPS market outlook — 6-month view, (4) Three margin recovery levers with estimated impact, (5) Crude slate optimisation — recommended blend, (6) Q3 turnaround — scope, cost, and margin impact, (7) CIMAH audit readiness — RAG status, (8) Safety performance dashboard, (9) Financial outlook — 12-month margin projection, (10) Board decisions required. Dark red and white colour scheme.',
        'Ask Copilot: Add a one-slide crude slate decision matrix showing the trade-off between three crude options. Display as a spider chart with 5 axes: Margin Contribution | Sulphur Content | Availability Risk | Price Volatility | Refinery Compatibility.',
        'Ask Copilot: Create speaker notes for the CFO for slides 1 through 4. The CFO needs to be able to explain the margin compression to non-technical Board members in under 3 minutes using plain language and one analogy.'
      ]),
      tool(T_OUTLOOK, M365_LIC, M365_ACCT, [
        'Ask Copilot in Outlook: Draft an email to our crude oil trading desk requesting a revised crude supply proposal for Q3. The email should specify: (1) our preferred crude API gravity range (32-38 API), (2) maximum sulphur content (0.5%), (3) required delivery window for the turnaround period, (4) target price differential vs Brent, and (5) request for optionality on volumes given the turnaround timing uncertainty.',
        'Ask Copilot: Draft an internal memo to the operations leadership team briefing them on the DOSH CIMAH audit in 8 weeks. List the 5 areas DOSH will focus on, assign a responsible manager for each area, and set a document readiness deadline of 4 weeks before the audit. Emphasise that DOSH auditors will conduct physical plant walk-rounds and interview operators directly.',
        'Ask Copilot: Draft a letter to DOSH Malaysia confirming our CIMAH Safety Report has been updated and requesting confirmation that the latest version is on file with DOSH. Reference the relevant CIMAH regulation schedule and our establishment registration number.'
      ]),
      tool(T_TEAMS, M365_LIC, M365_ACCT, [
        'Open an existing recorded Teams meeting recap from a refinery operations or HSE meeting. Ask Copilot: Identify all CIMAH or process safety topics discussed. List each topic with the key point made, any decision taken, and the follow-up action assigned. Format as a process safety meeting minute.',
        'Ask Copilot: Draft follow-up actions from this meeting for the turnaround planning team. Group by workstream: Engineering | HSE | Procurement | Contractor Management | Operations Readiness. Include owner and deadline for each action.',
        'Ask Copilot: Were any near-miss incidents or process deviations mentioned in this meeting? Extract each one with: the unit or equipment involved, the nature of the deviation, and whether a formal incident report was raised.'
      ], DESC_TEAMS),
      tool(T_NOTEBOOK, M365_LIC, M365_ACCT, [
        'Upload OG_01_Nusantara_Energy.xlsx and OG_02_Nusantara_HSE_Report.docx to Copilot Notebook. Set instruction: "You are a refinery CFO preparing a margin recovery and CIMAH audit strategy." Ask: Based on the operations data and the HSE report, what are the top 3 actions that will simultaneously improve refinery margin AND reduce CIMAH compliance risk before the audit in 8 weeks? Show the financial impact and the risk reduction benefit of each.',
        'Upload OG_01_Nusantara_Energy.xlsx and OG_02_Nusantara_HSE_Report.docx. Ask: If we defer the Q3 turnaround to Q1 FY2027 to avoid the production loss during a period of already-compressed margins, what is the increased safety and regulatory risk? What criteria should the Board use to make this deferral decision responsibly?'
      ], DESC_NOTEBOOK),
      tool(T_COWORK, FRONTIER_LIC, M365_ACCT, [
        'Do all of the following: (1) Research the latest DOSH CIMAH audit requirements and any guidance notes published since 2023. (2) Draft a CIMAH audit readiness action plan covering the 8 weeks to the audit — with specific weekly milestones. (3) Save to OneDrive as "CIMAH Audit Readiness Plan". (4) Email to the Plant Manager, Process Safety Manager, and Head of HSE asking them to review and confirm ownership of each milestone by Friday. (5) Schedule a weekly "CIMAH Audit Prep" 30-minute check-in every Monday morning for 8 weeks starting next Monday.',
        'Do all of the following for margin recovery: (1) Pull the latest MOPS pricing data from available sources. (2) Calculate the current crack spread for gasoline, diesel, and jet fuel based on available data. (3) Draft a 1-page crude slate recommendation memo for the trading desk showing the recommended crude blend for Q3. (4) Email to the Crude Procurement Manager and CFO. (5) Schedule a Crude Slate Review meeting for this Thursday.'
      ], DESC_COWORK),
      tool(T_WORD_AGT, M365_LIC, M365_ACCT, [
        'Open OG_02_Nusantara_HSE_Report.docx in Word for Web. Create an agent called "CIMAH Compliance Assistant". Description: "Answers questions from process engineers, HSE officers, and plant managers about CIMAH obligations, major hazard risk assessments, safety-critical equipment inspection requirements, and audit documentation." Share with all plant HSE and engineering teams.',
        'Demo: A process engineer asks "Unit 3 has a relief valve that was last tested 14 months ago. CIMAH requires annual testing. Is this non-compliant and what is the procedure to bring it into compliance before the DOSH audit in 8 weeks?" Show how the agent provides a precise, policy-grounded compliance answer.'
      ], DESC_WORD_AGT),
      tool(T_PPT_AGT, M365_LIC, M365_ACCT, [
        'Create a PowerPoint from the Board presentation and open in PowerPoint for Web. Create an agent called "Refinery Performance Board Bot". Share with Board members.',
        'Demo: A Board member asks "If the MOPS crack spread remains at current levels for the full year, what is our projected full-year EBITDA and do we remain above our debt covenant requirements?" Show how the agent provides a scenario-specific financial answer.'
      ], DESC_PPT_AGT),
      tool(T_XL_AGT, M365_LIC, M365_ACCT, [
        'Open OG_01_Nusantara_Energy.xlsx in Excel for Web. Create an agent called "Refinery Operations Analytics Q&A". Description: "Answers questions on refinery margin, crude slate, CIMAH compliance status, and turnaround planning for the operations and finance teams." Share with refinery management.',
        'Demo: Ask "What is the current refinery margin and how does it compare to our 3-year average?" Then: "How many safety-critical inspections are overdue across all major hazard installations?" Show how management gets instant operational intelligence.'
      ], DESC_XL_AGT),
      tool(T_BUILDER, M365_LIC, M365_ACCT, [
        'Go to copilotstudio.microsoft.com > Create > New Agent. Name it "HengYuan Operations Intelligence Bot". Description: "Supports HengYuan\'s plant operations and HSE teams with answers on CIMAH compliance, margin analysis, crude slate decisions, turnaround planning, and DOSH requirements — grounded in official operations and HSE documents." Upload OG_01_Nusantara_Energy.xlsx and OG_02_Nusantara_HSE_Report.docx. Add topics: "CIMAH Compliance", "Margin Analysis", "Turnaround Planning". Publish to Teams for operations and HSE staff.',
        'Demo the agent: A shift supervisor asks "We have detected a gas leak in the Unit 3 heat exchanger area. Concentration is at 15% LEL. What is our emergency response Level 1 procedure, do we isolate the unit, and who do I call first?" Show how the agent provides an immediate, structured emergency response for a high-stakes situation.'
      ], DESC_BUILDER),
    ]),

# ── RENEWABLE ENERGY ───────────────────────────────────────────────────────
ind('renewable-energy','og-energy','Renewable Energy','☀','#F9A825','#F57F17',
    'GreenPower Division (Sarawak Energy)',
    '480MW solar pipeline + PPA renegotiation with Tenaga — EUETS carbon credit filing due.',
    'GreenPower Division manages Sarawak Energy\'s 2.4GW hydro portfolio and a 480MW solar pipeline under development. The power purchase agreement (PPA) with Tenaga Nasional Berhad (TNB) for 800MW is up for renegotiation. Carbon credit generation under Verra VCS is being certified. The Energy Commission (ST) large-scale solar (LSS) bid is due in 6 weeks.',
    ['OG_01_Nusantara_Energy.xlsx','20_Zava_ESG_Sustainability_Framework.docx'],
    [
      tool(T_CHAT, FREE_LIC, FREE_ACCT, [
        'I lead the commercial team for a renewable energy developer in Malaysia. We have an 800MW hydro PPA with Tenaga that is up for renegotiation. The current tariff is MYR 0.214/kWh on a 25-year contract. Market tariffs for new hydro have risen to MYR 0.26/kWh. Draft a negotiation strategy brief of 250 words covering: our target tariff, our walk-away position, our three strongest negotiating arguments, and the key concessions we should be prepared to offer Tenaga in exchange for a tariff increase.',
        'Explain the Verra VCS (Verified Carbon Standard) certification process for a large hydro project. What are the key steps, the typical timeline from initial project design document (PDD) to first carbon credits issued, and the verification requirements? Focus on Sarawak hydro projects specifically.',
        'What is the Energy Commission Malaysia\'s Large Scale Solar (LSS) bidding framework? What are the eligibility criteria, the maximum capacity per bid, the tariff determination mechanism, and the typical timeline from bid submission to financial close? How competitive has the LSS bidding been in recent rounds?'
      ]),
      tool(T_RESEARCHER, M365_LIC, M365_ACCT, [
        'Research the carbon credit market for renewable energy in Southeast Asia in 2025 and 2026. I need: (1) Current voluntary carbon credit price range for hydro and solar projects, (2) Demand trends from corporate buyers in Malaysia and Singapore, (3) The Bursa Carbon Exchange (BCX) performance since launch. Provide citations.',
        'Research global solar PV cost trends and the competitive landscape for LSS solar bids in Malaysia. What levelised cost of energy (LCOE) are developers achieving? Who are the main EPC contractors active in Malaysian LSS projects and what are typical project timelines? Cite recent energy reports.'
      ], DESC_RESEARCHER),
      tool(T_ANALYST, M365_LIC, M365_ACCT, [
        'Upload OG_01_Nusantara_Energy.xlsx (use as energy portfolio proxy). Ask Analyst: Analyse the hydro portfolio generation data for the past 4 years. What is the capacity factor trend for each dam? Which dams have the highest variability in generation due to rainfall patterns? Calculate the average annual generation in GWh and the revenue sensitivity to a 10% drop in generation. Show as a trend chart and a sensitivity table.',
        'Upload 20_Zava_ESG_Sustainability_Framework.xlsx. Ask: Build a carbon credit revenue projection for the hydro portfolio. Assume 2.4GW capacity, 45% average capacity factor, grid emission factor of 0.62 tCO2e/MWh. Calculate: (1) Annual carbon credits generated in tCO2e, (2) Revenue at USD 8/tCO2e (current VCS price), (3) Revenue at USD 15/tCO2e (if carbon price rises). Show as a 5-year projection table.'
      ], DESC_ANALYST),
      tool(T_EXCEL, M365_LIC, M365_ACCT, [
        'Open OG_01_Nusantara_Energy.xlsx. Navigate to the Renewable Portfolio sheet. Ask Copilot: Build a PPA renegotiation model on a new sheet. Current PPA: 800MW at MYR 0.214/kWh, 25-year remaining term, 2% annual escalation. Proposed new tariff: MYR 0.248/kWh. Calculate: (1) Annual revenue difference, (2) NPV of the tariff increase over the remaining 25 years at an 8% discount rate, (3) The impact on our DSCR (Debt Service Coverage Ratio). Show as a comparison table: Current PPA vs Proposed PPA.',
        'Ask Copilot: Create a 480MW solar pipeline development tracker on a new sheet. List each solar project with: Project Name | Capacity (MW) | Development Stage | Land Status | Grid Connection Application Status | Expected COD | Estimated Capex (MYR M) | LSS Bid Round. Apply conditional formatting: projects at Financial Close stage in green, at Grid Application stage in yellow, at Land Acquisition stage in orange.',
        'Ask Copilot: Build a carbon credit generation tracker. For each hydro asset in the portfolio, calculate the estimated annual carbon credits based on generation data and the grid emission factor. Show the cumulative carbon credits generated to date and the estimated revenue at current market prices. Add a chart showing annual carbon credit revenue at three price scenarios: USD 8, USD 12, and USD 18/tCO2e.'
      ]),
      tool(T_WORD, M365_LIC, M365_ACCT, [
        'Open 20_Zava_ESG_Sustainability_Framework.docx. Ask Copilot: Draft a 400-word renewable energy section for our annual sustainability report. Cover: (1) Our renewable energy generation capacity and portfolio overview, (2) Carbon emission avoidance in tCO2e from our hydro and solar assets, (3) Progress on the 480MW solar pipeline, (4) Carbon credit certification update, (5) PPA contribution to Malaysia\'s renewable energy targets under the National Energy Transition Roadmap (NETR). Use an optimistic but factually grounded tone.',
        'Ask Copilot: Draft the PPA renegotiation position paper for the TNB negotiation. Cover: (1) Market context — new hydro tariffs have risen to MYR 0.26/kWh, (2) Our cost structure justification — OPEX has increased 18% since the original PPA, (3) The long-term supply security value we provide TNB, (4) Our proposal — MYR 0.248/kWh with 2.5% escalation, (5) What we can offer TNB in return — extended term optionality, demand response capability. Keep it to 2 pages.',
        'Ask Copilot: Write the LSS bid submission executive summary for our 150MW solar project in Sarawak. Cover: project overview, site location, technology (single-axis tracking monofacial), expected capacity factor 19.2%, proposed tariff MYR 0.198/kWh, EPC contractor, connection point, and environmental impact summary. Format to match the Energy Commission LSS bid template structure.'
      ]),
      tool(T_PPT, M365_LIC, M365_ACCT, [
        'Ask Copilot in PowerPoint: Create a 10-slide renewable energy investor day presentation. Include: (1) Portfolio overview — 2.4GW hydro + 480MW solar pipeline, (2) Hydro generation performance and revenue, (3) PPA renegotiation — rationale and impact, (4) Solar pipeline — project map and development status, (5) Carbon credit programme — certification update and revenue potential, (6) LSS Round 5 bid — project details, (7) NETR alignment — how our portfolio supports Malaysia\'s 70% renewable target, (8) Financial projections — 5-year revenue and EBITDA, (9) ESG commitment, (10) Investment thesis. Use a green and yellow colour scheme.',
        'Ask Copilot: Create a 2-slide carbon credit explainer for our Board who are unfamiliar with voluntary carbon markets. Slide 1: How carbon credits are generated, verified (Verra VCS), and sold. Slide 2: Our portfolio\'s carbon credit potential — annual tCO2e generated and revenue at three price scenarios. Use simple visuals, no jargon.',
        'Ask Copilot: Add a risk matrix slide showing the top 4 risks to our renewable energy business: hydrology risk (rainfall variability), tariff renegotiation risk, LSS bid failure, and carbon price volatility. Position each on a 3x3 likelihood-impact matrix.'
      ]),
      tool(T_OUTLOOK, M365_LIC, M365_ACCT, [
        'Ask Copilot in Outlook: Draft a formal letter to TNB\'s Power Procurement team requesting a PPA renegotiation meeting. The letter should: reference the existing PPA and its key terms, note that the PPA review clause allows renegotiation at the 10-year mark, outline our position at a high level (seeking a tariff revision to reflect current market rates), and propose a negotiation timeline of 3 months. Use formal utility sector correspondence tone.',
        'Ask Copilot: Draft an email to the Energy Commission Malaysia submitting our intention to bid in the LSS Round 5 tender. The email should confirm our company eligibility, specify the project name and capacity (150MW), attach the pre-qualification documents checklist (note: attach separately), and request confirmation of the submission portal access.',
        'Ask Copilot: Draft an update email to our Verra VCS verifier requesting the status of our carbon credit certification for the Bakun Hydro project. The verification has been pending for 5 months. Ask for an estimated completion date and a list of any outstanding documentation required from our side.'
      ]),
      tool(T_TEAMS, M365_LIC, M365_ACCT, [
        'Open an existing recorded Teams meeting recap from a project development or commercial meeting. Ask Copilot: Identify all commercial milestones discussed — PPA, LSS bid, carbon credits, and land acquisition. For each, note the current status, the next key milestone, and who is responsible.',
        'Ask Copilot: Draft follow-up actions for the LSS bid preparation team. Assign each action to a workstream: Technical | Commercial | Legal | Environmental | Grid Connection. Include deadline and the person responsible.',
        'Ask Copilot: Were any regulatory risks or delays discussed in this meeting? List each risk with the project it affects, the nature of the risk, and the mitigation discussed.'
      ], DESC_TEAMS),
      tool(T_NOTEBOOK, M365_LIC, M365_ACCT, [
        'Upload OG_01_Nusantara_Energy.xlsx and 20_Zava_ESG_Sustainability_Framework.docx to Copilot Notebook. Set instruction: "You are a renewable energy commercial director." Ask: Based on the portfolio data and our sustainability framework, what is the optimal sequencing of our three commercial priorities — PPA renegotiation, LSS bid, and carbon credit certification — given that we have limited management bandwidth? Which should we focus on first and why?',
        'Upload OG_01_Nusantara_Energy.xlsx and 20_Zava_ESG_Sustainability_Framework.docx. Ask: Our sustainability framework commits to being carbon neutral by 2035. Our current operations generate 480,000 tCO2e/year. Our renewable portfolio avoids an estimated 4.2M tCO2e/year. Does this mean we are already carbon neutral on a portfolio basis? What is the correct way to report this under GHG Protocol accounting standards?'
      ], DESC_NOTEBOOK),
      tool(T_COWORK, FRONTIER_LIC, M365_ACCT, [
        'Do all of the following for the LSS bid: (1) Research the Energy Commission Malaysia LSS Round 5 requirements and submission deadline. (2) Draft a bid preparation checklist covering all required documents. (3) Save to OneDrive as "LSS Round 5 Bid Checklist". (4) Email to the Project Director and Head of Business Development asking them to assign responsibility for each checklist item and confirm readiness in 2 weeks. (5) Schedule a weekly LSS Bid Preparation meeting every Tuesday at 9am for 6 weeks.',
        'Do all of the following for the PPA renegotiation: (1) Research recent PPA tariff benchmarks for hydro power in Malaysia and comparable markets. (2) Compile a negotiation brief showing our tariff request (MYR 0.248/kWh) against market benchmarks. (3) Draft a letter to TNB\'s Power Procurement team requesting a renegotiation meeting. (4) Save the letter and brief to OneDrive. (5) Email both documents to our General Counsel and CFO for review before sending to TNB.'
      ], DESC_COWORK),
      tool(T_WORD_AGT, M365_LIC, M365_ACCT, [
        'Open 20_Zava_ESG_Sustainability_Framework.docx in Word for Web. Create an agent called "GreenPower ESG Policy Bot". Description: "Answers questions from the project development team about GreenPower\'s sustainability commitments, carbon credit methodology, ESG reporting requirements, and renewable energy targets." Share with the development and sustainability teams.',
        'Demo: A project developer asks "Does our 150MW Sarawak solar project qualify for Verra VCS carbon credit certification? What additionality criteria do we need to meet and what is the typical documentation required for the Project Design Document?" Show how the agent provides a precise, policy-grounded answer.'
      ], DESC_WORD_AGT),
      tool(T_PPT_AGT, M365_LIC, M365_ACCT, [
        'Create a PowerPoint from the investor day presentation. Create an agent called "GreenPower Investor Q&A Bot". Share with institutional investors and the IR team.',
        'Demo: An investor asks "What is GreenPower\'s projected EBITDA from the 480MW solar pipeline at full buildout, and what assumptions does that use for tariff and capacity factor?" Show how the agent handles complex investor questions during a roadshow.'
      ], DESC_PPT_AGT),
      tool(T_XL_AGT, M365_LIC, M365_ACCT, [
        'Open OG_01_Nusantara_Energy.xlsx in Excel for Web. Create an agent called "Renewable Portfolio Analytics Q&A". Description: "Instant answers on GreenPower\'s hydro and solar portfolio — generation, PPA revenue, carbon credits, and project pipeline — for the commercial and finance teams." Share with senior management.',
        'Demo: Ask "What is the capacity factor for our top-performing hydro asset in FY2025?" Then: "At USD 12/tCO2e, what is the annual carbon credit revenue from our full hydro portfolio?" Show how the commercial team gets rapid portfolio intelligence.'
      ], DESC_XL_AGT),
      tool(T_BUILDER, M365_LIC, M365_ACCT, [
        'Go to copilotstudio.microsoft.com > Create > New Agent. Name it "GreenPower Commercial Intelligence Bot". Description: "Supports GreenPower\'s commercial, project development, and sustainability teams with answers on PPA terms, LSS bid requirements, carbon credit methodology, ESG reporting, and portfolio performance — grounded in official portfolio and sustainability documents." Upload OG_01_Nusantara_Energy.xlsx and 20_Zava_ESG_Sustainability_Framework.docx. Add topics: "PPA & Tariff", "LSS Bid", "Carbon Credits", "ESG Reporting". Publish to Teams.',
        'Demo the agent: A business development manager asks: "We are evaluating a 50MW rooftop solar project for a large industrial client in Penang. Can we structure this as a corporate PPA and how does it interact with our existing LSS licences? Are there any Energy Commission approval requirements?" Show how the agent gives a comprehensive commercial answer that helps the team make the right decision.'
      ], DESC_BUILDER),
    ]),

# ── INDUSTRIAL MANUFACTURING ───────────────────────────────────────────────
ind('industrial-manufacturing','manufacturing','Industrial Manufacturing','⚙','#263238','#37474F',
    'Zava Manufacturing (Nilai Plant)',
    'OEE 62% — spindle motor failures, 2,800-unit backlog MYR 14.2M. SIRIM audit in 8 weeks.',
    'Zava Manufacturing\'s Nilai plant produces precision industrial components for the automotive and electronics sectors. Overall Equipment Effectiveness (OEE) has dropped from 76% to 62% over 3 quarters, driven by recurring spindle motor failures on 3 of 12 CNC machines. A 2,800-unit production backlog worth MYR 14.2M has accumulated. SIRIM ISO 9001:2015 audit is scheduled in 8 weeks.',
    ['12_Zava_Manufacturing_KPIs.xlsx','21_Zava_Chemical_Safety_HIRARC.docx'],
    [
      tool(T_CHAT, FREE_LIC, FREE_ACCT, [
        'I am the Plant Manager of a precision manufacturing facility. Three of my 12 CNC machines have recurring spindle motor failures, dragging OEE from 76% to 62% over the past 3 quarters. I have a 2,800-unit backlog worth MYR 14.2M and a SIRIM ISO 9001 audit in 8 weeks. Draft a 300-word operational recovery brief for my Managing Director. Cover: root cause hypothesis for the spindle motor failures, the three immediate actions I am taking to reduce the backlog, and how I will ensure the audit readiness is not compromised by the operational recovery effort.',
        'Explain Overall Equipment Effectiveness (OEE) — how it is calculated, what the three components are (availability, performance, quality), and what a world-class OEE target looks like for a precision manufacturing facility producing automotive and electronics components. Include an example calculation.',
        'What are the most common root causes of CNC spindle motor failures in precision machining environments, and what predictive maintenance approaches are most effective for preventing them? Focus on approaches that can be implemented without replacing the machines entirely.'
      ]),
      tool(T_RESEARCHER, M365_LIC, M365_ACCT, [
        'Research best practices for rapid OEE recovery in precision manufacturing — specifically for facilities producing automotive and electronics components in Southeast Asia. I need: (1) The most effective maintenance strategies (TPM, predictive maintenance, RCM) and their typical OEE improvement impact, (2) Any case studies of Malaysian manufacturers who recovered OEE from below 65% to above 80% within 6 months, (3) SIRIM\'s expectations during an ISO 9001 audit for a facility with known equipment issues. Cite sources.',
        'Research the current state of predictive maintenance technology for CNC machining — specifically spindle health monitoring using vibration analysis and IoT sensors. What are the leading solutions available in Malaysia, typical implementation cost for a 12-machine facility, and the expected reduction in unplanned downtime? Provide citations.'
      ], DESC_RESEARCHER),
      tool(T_ANALYST, M365_LIC, M365_ACCT, [
        'Upload 12_Zava_Manufacturing_KPIs.xlsx to Analyst. Ask: Analyse OEE data for all 12 CNC machines over the past 12 months. Break down OEE into availability, performance, and quality for each machine. Which 3 machines have the lowest OEE? Is the OEE decline driven primarily by availability loss (breakdowns) or performance loss (speed reduction)? Create a machine-level OEE heat map and a trend chart showing the group OEE from 76% to 62%.',
        'Upload 12_Zava_Manufacturing_KPIs.xlsx. Ask: Analyse the production backlog by customer and product type. Which customer has the largest backlog in units and MYR value? Calculate the financial penalty risk — assume our top 3 automotive customers have SLA penalties of 0.5% of order value per week of delay. Show total penalty exposure at current backlog clearance rate.'
      ], DESC_ANALYST),
      tool(T_EXCEL, M365_LIC, M365_ACCT, [
        'Open 12_Zava_Manufacturing_KPIs.xlsx. Navigate to the Machine Performance sheet. Ask Copilot: Create an OEE recovery simulation model on a new sheet. Show what happens to overall plant OEE if we: (1) Fix the 3 failing spindle motors (assume restores those machines to 82% OEE), (2) Implement 2-shift vs 3-shift production for the backlog clearance, (3) Temporarily defer non-urgent preventive maintenance. Calculate the projected backlog clearance date under each scenario.',
        'Ask Copilot: Build a SIRIM ISO 9001 audit readiness tracker on a new sheet. List the 10 key ISO 9001 clauses most commonly reviewed in a manufacturing audit. For each clause, add: Current Status (Compliant/Partial/Gap) | Evidence on File (Yes/No) | Responsible Person | Action Required Before Audit. Apply colour coding: green = Compliant with evidence, amber = Partial, red = Gap.',
        'Ask Copilot: In the Quality Control sheet, calculate the First Pass Yield (FPY) and scrap rate for each product family over the past 6 months. Has the scrap rate increased since the OEE decline began? If scrap has increased, estimate the additional material cost in MYR. Show as a trend chart with a correlation line.'
      ]),
      tool(T_WORD, M365_LIC, M365_ACCT, [
        'Open 21_Zava_Chemical_Safety_HIRARC.docx. Ask Copilot: Draft a CNC spindle motor failure root cause analysis report using the 5-Why methodology. The failures occur predominantly after 8–10 hours of continuous operation and are linked to 3 specific machines (CNC-04, CNC-07, CNC-11). Suspected causes include: insufficient coolant flow to the spindle bearing, inadequate preventive maintenance intervals, and substandard replacement parts. Structure the report: Problem Statement | 5-Why Analysis | Root Cause | Corrective Actions | Preventive Actions | Effectiveness Review Date.',
        'Ask Copilot: Write a backlog recovery plan of 2 pages for the Managing Director. Cover: (1) Current backlog — 2,800 units, MYR 14.2M value, (2) Customer impact and penalty risk, (3) Recovery plan — 3-shift production, contract machining outsource for 400 units, spindle motor repair timeline, (4) Expected clearance date — 6 weeks, (5) Communication plan for affected customers. Include a week-by-week recovery milestone table.',
        'Ask Copilot: Draft an ISO 9001 internal audit non-conformance response report. The internal audit found 3 minor non-conformances: (1) calibration records not updated for 2 measurement instruments, (2) operator training records incomplete for 4 new employees, (3) customer complaint response log not updated for 3 complaints. For each non-conformance, write the corrective action and the preventive action in the format required by SIRIM.'
      ]),
      tool(T_PPT, M365_LIC, M365_ACCT, [
        'Ask Copilot in PowerPoint: Create a 10-slide operations recovery presentation for the Managing Director and key customers. Include: (1) Situation — OEE decline from 76% to 62%, (2) Root cause — spindle motor analysis, (3) Financial impact — backlog value and penalty risk, (4) Recovery plan — timeline and milestones, (5) SIRIM audit readiness — status dashboard, (6) Resource plan — 3-shift operation and outsourcing, (7) Customer impact by account, (8) Communication plan, (9) OEE target trajectory — 62% to 78% in 6 months, (10) Decisions required. Use a professional dark grey and orange colour scheme.',
        'Ask Copilot: Create a customer communication slide showing each affected customer, their backlog in units, the expected delivery date under the recovery plan, and whether we are triggering any SLA penalty clauses. Format as a table with a RAG status column.',
        'Ask Copilot: Add a predictive maintenance roadmap slide showing a phased implementation: Phase 1 — vibration sensors on 3 failing machines (Month 1–2), Phase 2 — IoT dashboard and alerting (Month 3–4), Phase 3 — expand to all 12 machines (Month 5–6). Show estimated cost and OEE improvement for each phase.'
      ]),
      tool(T_OUTLOOK, M365_LIC, M365_ACCT, [
        'Ask Copilot in Outlook: Draft a customer communication email to our top 3 automotive customers who are affected by the production backlog. The email should: acknowledge the delay without going into technical detail about the cause, provide the revised delivery schedule for their specific orders, confirm that no quality compromise has occurred, and offer a goodwill gesture (expedited shipping at our cost). Use a professional, accountable but not grovelling tone.',
        'Ask Copilot: Draft an urgent email to our CNC spindle motor supplier requesting emergency delivery of 3 replacement spindle motor units within 5 business days. The email should cite the criticality of the situation (production backlog, customer SLA risk), reference our existing supply agreement and volume commitment, and ask for a price for expedited delivery. Copy our procurement manager.',
        'Ask Copilot: Draft an internal email to all shift supervisors briefing them on the 3-shift recovery operation starting next Monday. Cover: the shift rotation schedule, the backlog clearance target per shift (160 units), the quality checkpoint requirements, and the escalation procedure if a machine goes down during the recovery period.'
      ]),
      tool(T_TEAMS, M365_LIC, M365_ACCT, [
        'Open an existing recorded Teams meeting recap from an operations or production review. Ask Copilot: Extract all KPI figures mentioned — OEE, production output, backlog units, scrap rate, and delivery performance. Create a structured operations scorecard from the meeting data.',
        'Ask Copilot: Draft follow-up actions from this production meeting. Prioritise actions into: Critical (affects backlog clearance this week), High (affects SIRIM audit), Medium (process improvement). Assign owner and deadline to each.',
        'Ask Copilot: Were any customer escalations or SLA breaches discussed? List each customer, the SLA metric at risk, the current performance, and the recovery commitment made in the meeting.'
      ], DESC_TEAMS),
      tool(T_NOTEBOOK, M365_LIC, M365_ACCT, [
        'Upload 12_Zava_Manufacturing_KPIs.xlsx and 21_Zava_Chemical_Safety_HIRARC.docx to Copilot Notebook. Set instruction: "You are a manufacturing excellence consultant helping the Plant Manager prioritise recovery actions." Ask: Based on the KPI data and the operational situation, which 3 actions will have the greatest combined impact on OEE recovery and SIRIM audit readiness in the next 8 weeks? Rank them and explain the trade-offs.',
        'Upload 12_Zava_Manufacturing_KPIs.xlsx and 21_Zava_Chemical_Safety_HIRARC.docx. Ask: The safety document commits to specific machine guarding and chemical handling standards. Given that the plant is operating 3 shifts under backlog recovery pressure, what are the 3 highest safety risks that could materialise and what must the Plant Manager do before the extended shift schedule starts?'
      ], DESC_NOTEBOOK),
      tool(T_COWORK, FRONTIER_LIC, M365_ACCT, [
        'Do all of the following: (1) Research the best spindle motor suppliers in Malaysia and Singapore who can provide emergency delivery of Fanuc or Siemens spindle motors for CNC machines within 5 business days. (2) Draft an emergency procurement request to the top 2 suppliers with our technical specifications. (3) Email to both suppliers and CC our Procurement Manager asking for quotation within 24 hours. (4) Create a spindle motor replacement tracker in OneDrive showing: Machine ID | Motor Spec | Supplier | Order Date | Expected Delivery | Installation Date | Status. (5) Post an update in the #plant-operations Teams channel: "Emergency spindle motor procurement initiated for CNC-04, CNC-07, CNC-11. Quotations expected within 24 hours."',
        'Do all of the following for SIRIM audit prep: (1) Create an ISO 9001 audit readiness checklist based on the standard\'s 10 key clauses. (2) Email to all 5 department heads (Quality, Production, Maintenance, Logistics, HR) asking them to complete their section of the checklist within 1 week. (3) Schedule a pre-audit internal review meeting for 5 weeks before the SIRIM audit date. (4) Set a calendar reminder for yourself 3 weeks before the audit: "Final document readiness check". (5) Post in the #quality-management Teams channel: "SIRIM ISO 9001 audit is in 8 weeks. Please complete the readiness checklist sent via email within 1 week."'
      ], DESC_COWORK),
      tool(T_WORD_AGT, M365_LIC, M365_ACCT, [
        'Open 21_Zava_Chemical_Safety_HIRARC.docx in Word for Web. Create an agent called "Plant Safety & Compliance Bot". Description: "Answers questions from supervisors and operators about Zava Manufacturing\'s safety procedures, chemical handling requirements, machine guarding standards, and ISO 9001 quality requirements." Share with all plant supervisors.',
        'Demo: A production supervisor asks "We need to extend the shift to 12 hours to clear the backlog. What are the HSE requirements for extended shifts — are there additional risk assessment steps required and what welfare facilities must we provide?" Show how the agent provides a policy-grounded answer that protects both productivity and safety.'
      ], DESC_WORD_AGT),
      tool(T_PPT_AGT, M365_LIC, M365_ACCT, [
        'Create a PowerPoint from the operations recovery presentation. Create an agent called "Manufacturing Recovery Board Bot". Share with the MD and key customer account managers.',
        'Demo: A customer account manager asks the agent "My customer Toyota is asking for a firm revised delivery date for their 480-unit order. What does the recovery plan show as the expected delivery date and is there any risk to that date?" Show how account managers get a precise, plan-grounded answer.'
      ], DESC_PPT_AGT),
      tool(T_XL_AGT, M365_LIC, M365_ACCT, [
        'Open 12_Zava_Manufacturing_KPIs.xlsx in Excel for Web. Create an agent called "Nilai Plant Operations Q&A". Description: "Answers questions on OEE by machine, production backlog, scrap rate, delivery performance, and SIRIM audit status for the Plant Manager and operations team." Share with plant leadership.',
        'Demo: Ask "What is the current OEE for CNC-04 and how many units is it producing per shift?" Then: "What is the total backlog for Toyota and when is the expected clearance date at current recovery pace?" Show how the Plant Manager gets instant operational intelligence.'
      ], DESC_XL_AGT),
      tool(T_BUILDER, M365_LIC, M365_ACCT, [
        'Go to copilotstudio.microsoft.com > Create > New Agent. Name it "Nilai Plant Intelligence Agent". Description: "Supports Zava Manufacturing Nilai plant supervisors and managers with instant answers on OEE performance, production backlog, SIRIM ISO 9001 requirements, machine maintenance procedures, and chemical safety — helping drive the OEE recovery from 62% to 78%." Upload 12_Zava_Manufacturing_KPIs.xlsx and 21_Zava_Chemical_Safety_HIRARC.docx. Add topics: "OEE & Production", "SIRIM Audit", "Machine Maintenance", "Safety". Publish to Teams.',
        'Demo the agent: A shift supervisor asks: "CNC-07 has just triggered a spindle overheat alarm for the third time this shift. We are in the middle of an urgent automotive customer run. Should I stop the machine, reduce speed, or can I continue? What does our maintenance protocol say and do I need to raise a maintenance work order immediately?" Show how the agent gives an operationally-grounded, safety-conscious answer that helps the supervisor make the right call.'
      ], DESC_BUILDER),
    ]),
]

print(f"Batch 4 written: {len(INDUSTRIES_4)} entries")
