
import sys; sys.path.insert(0,'.')
from util import *

INDUSTRIES_6 = [

# ── DIVERSIFIED CONGLOMERATE ───────────────────────────────────────────────
ind('diversified-conglomerate', 'conglomerate', 'Diversified Conglomerate', '🏛', '#37474F', '#455A64',
    'Puncak Horizon Holdings Berhad',
    'Capital allocation is under pressure as two portfolio bets underperform.',
    'Puncak Horizon Holdings Berhad manages a multi-industry portfolio spanning manufacturing, consumer, logistics, and services. Two recent investment bets are underperforming, synergy targets are slipping, and the Board wants evidence that management is reallocating capital with discipline. Group leadership needs a single view of business unit returns, governance signals, and strategic trade-offs before the next portfolio committee session.',
    ['DC_01_Portfolio_Performance.xlsx', 'DC_02_Group_Governance_Charter.docx', 'DC_03_Corporate_Strategy_Framework.docx'],
    [
      tool(T_CHAT, FREE_LIC, FREE_ACCT, [
        'You are the Group CFO at Puncak Horizon Holdings Berhad. Use the Business Unit P&L, Capital Allocation Dashboard, and Investment Returns sheets in DC_01_Portfolio_Performance.xlsx together with DC_02_Group_Governance_Charter.docx and DC_03_Corporate_Strategy_Framework.docx. Brief the leadership team on portfolio performance, capital discipline, and governance control, and separate the immediate operating gaps, control gaps, and stakeholder exposure that could escalate with SC and OJK or major shareholders. Present the answer as a RAG table with columns Risk, Evidence, 30-Day Action, and Owner.',
        'You are the Group Strategy Director at Puncak Horizon Holdings Berhad. Use the Capital Allocation Dashboard, Board Scorecard, and Business Unit P&L sheets in DC_01_Portfolio_Performance.xlsx together with DC_03_Corporate_Strategy_Framework.docx. Diagnose which areas are recoverable within one quarter, which need management intervention now, and which should be paused until controls in the operating documents are tightened. Present the answer as a RAG heat map with the unit or workstream, the leading indicator, the root cause, and the next action.',
        'You are the Head of Group Governance at Puncak Horizon Holdings Berhad. Use the Synergy Tracker, Investment Returns, and Board Scorecard sheets in DC_01_Portfolio_Performance.xlsx together with DC_02_Group_Governance_Charter.docx and DC_03_Corporate_Strategy_Framework.docx. Prepare decision-quality talking points for the Board, business unit CEOs, and investors that distinguish what management can commit today, what depends on milestones, and what should be disclosed carefully. Present the answer as a RAG message matrix with audience, key message, evidence source, and approval owner.'
      ]),
      tool(T_RESEARCHER, FREE_LIC, FREE_ACCT, [
        'You are the Group CFO at Puncak Horizon Holdings Berhad. Research how organisations in Malaysia and Indonesia have handled portfolio performance, capital discipline, and governance control since 2023, with explicit attention to guidance from SC and OJK that would affect the Business Unit P&L and Investment Returns sheets and DC_02_Group_Governance_Charter.docx. Distinguish mandatory expectations, market practice, and peer tactics that management could apply to portfolio recovery and capital re-prioritisation. Present the findings as a RAG benchmark table with columns Theme, Malaysia, Indonesia, Evidence Source, and Management Implication. Flag any claim that could not be independently verified.',
        'You are the Group Strategy Director at Puncak Horizon Holdings Berhad. Research the highest-impact operational levers that comparable teams have used to improve the indicators tracked in the Capital Allocation Dashboard, Board Scorecard, and Synergy Tracker sheets. Prioritise published case studies, association guidance, or regulator commentary that would be credible in front of the Board, business unit CEOs, and investors. Present the findings as a RAG table with Intervention, Expected Benefit, Time to Impact, and Evidence Strength. Flag any claim that could not be independently verified.',
        'You are the Head of Group Governance at Puncak Horizon Holdings Berhad. Research what investors, customers, sponsors, or regulators typically expect to see when management is trying to stabilise portfolio performance, capital discipline, and governance control, using examples that align with DC_02_Group_Governance_Charter.docx and DC_03_Corporate_Strategy_Framework.docx. Highlight what leading teams communicate in the first 30 days, 60 days, and 90 days so the messaging is defensible with major shareholders. Present the findings as a RAG roadmap with Time Horizon, Expected Action, External Signal, and Practical Implication. Flag any claim that could not be independently verified.'
      ], DESC_RESEARCHER),
      tool(T_ANALYST, M365_LIC, M365_ACCT, [
        'You are the Group CFO at Puncak Horizon Holdings Berhad. Upload DC_01_Portfolio_Performance.xlsx to Analyst and use the Business Unit P&L, Capital Allocation Dashboard, and Synergy Tracker sheets to quantify where current performance is deviating from plan. Estimate the financial, service, or programme impact of each gap and highlight which areas are most material to portfolio recovery and capital re-prioritisation. Present the output as a RAG table with Metric, Current Position, Gap, Impact Estimate, and Recommended Action.',
        'You are the Group Strategy Director at Puncak Horizon Holdings Berhad. Upload DC_01_Portfolio_Performance.xlsx and DC_02_Group_Governance_Charter.docx to Analyst, then cross-reference the Capital Allocation Dashboard, Board Scorecard, and Investment Returns sheets against the control expectations in the document. Identify the hotspots where weak execution and weak governance are reinforcing each other and rank them by urgency. Present the answer as a RAG heat map with Area, Root Cause, Evidence, Escalation Risk, and Owner.',
        'You are the Head of Group Governance at Puncak Horizon Holdings Berhad. Upload DC_01_Portfolio_Performance.xlsx to Analyst and build a forward look from the Synergy Tracker, Board Scorecard, and Investment Returns sheets for the next two quarters. Show the upside case, base case, and downside case for management if current trends continue versus if the highest-priority actions land on time. Present the result as a RAG scenario table with Scenario, Key Assumption, Expected Outcome, and Trigger for Escalation.'
      ], DESC_ANALYST),
      tool(T_EXCEL, M365_LIC, M365_ACCT, [
        "You are the Group CFO at Puncak Horizon Holdings Berhad. Using the Business Unit P&L, Synergy Tracker, and Investment Returns sheets in DC_01_Portfolio_Performance.xlsx, create a new worksheet called 'Executive RAG Dashboard'. Show the core metrics that matter most to portfolio recovery and capital re-prioritisation, a short variance note, and a Red, Amber, or Green status for each metric. Design it so the first view is board-ready and the formulas refresh automatically when source values change.",
        "You are the Group Strategy Director at Puncak Horizon Holdings Berhad. Using the Capital Allocation Dashboard, Board Scorecard, and Synergy Tracker sheets in DC_01_Portfolio_Performance.xlsx, create a new worksheet called 'Recovery Scenarios'. Model what happens if management closes half the current gap within one quarter versus if the trend deteriorates by another 10 percent. Present the result as a RAG scenario model with assumptions, impact, and recommended management response.",
        "You are the Head of Group Governance at Puncak Horizon Holdings Berhad. Using the Investment Returns, Business Unit P&L, and Board Scorecard sheets in DC_01_Portfolio_Performance.xlsx, create a new worksheet called 'Action Tracker'. List the highest-priority actions, the metric each action should move, the target date, and the owner that group strategy and business unit CFOs should hold accountable. Make the tracker a RAG control sheet with overdue items highlighted automatically."
      ]),
      tool(T_WORD, M365_LIC, M365_ACCT, [
        'You are the Group CFO at Puncak Horizon Holdings Berhad. Use DC_02_Group_Governance_Charter.docx together with the Business Unit P&L and Investment Returns sheets in DC_01_Portfolio_Performance.xlsx to draft a 2-page Portfolio committee memo. Explain the current position, the governance or policy implications, and the decisions required to stabilise portfolio performance, capital discipline, and governance control. Start with a short RAG summary and end with a 30-day action table.',
        'You are the Group Strategy Director at Puncak Horizon Holdings Berhad. Use DC_03_Corporate_Strategy_Framework.docx together with the Capital Allocation Dashboard and Board Scorecard sheets in DC_01_Portfolio_Performance.xlsx to draft a stakeholder-ready note for major shareholders. Make the narrative analytical rather than promotional, and distinguish what is already evidenced in the files from what is still being validated. Present the note with a RAG section on commitments, dependencies, and unresolved risks.',
        'You are the Head of Group Governance at Puncak Horizon Holdings Berhad. Use DC_02_Group_Governance_Charter.docx and DC_03_Corporate_Strategy_Framework.docx together with the Synergy Tracker and Investment Returns sheets in DC_01_Portfolio_Performance.xlsx to draft a 90-day operating action plan for group strategy and business unit CFOs. Show how management should sequence the work so quick wins support the longer-control fixes needed for portfolio recovery and capital re-prioritisation. Present the plan as a RAG table with Week, Action, Dependency, and Success Measure.'
      ]),
      tool(T_PPT, M365_LIC, M365_ACCT, [
        'You are the Group CFO at Puncak Horizon Holdings Berhad. Create a 6-slide executive deck using DC_01_Portfolio_Performance.xlsx, DC_02_Group_Governance_Charter.docx, and DC_03_Corporate_Strategy_Framework.docx as the source context. Cover the current position, the most material gaps, the implications for the Board, business unit CEOs, and investors, the stabilisation plan, the financial or delivery outlook, and the decisions required this month. Give each slide a headline with a RAG status and keep the layout tight enough for a board review.',
        'You are the Group Strategy Director at Puncak Horizon Holdings Berhad. Create a 3-slide update pack for major shareholders using the Business Unit P&L, Synergy Tracker, and Investment Returns sheets and DC_02_Group_Governance_Charter.docx. Slide 1 should summarise the issue, slide 2 should show evidence-backed progress, and slide 3 should state the next milestone commitments. Add a RAG ribbon to each slide so the risk posture is obvious at a glance.',
        'You are the Head of Group Governance at Puncak Horizon Holdings Berhad. Create a single heat-map slide from the Capital Allocation Dashboard, Board Scorecard, and Investment Returns sheets in DC_01_Portfolio_Performance.xlsx. Show which business units, processes, regions, or workstreams are Red, Amber, or Green and note the one action that would most likely move each Red area back to Amber. Use an executive style and include a short legend that ties the colours to management action.'
      ]),
      tool(T_OUTLOOK, M365_LIC, M365_ACCT, [
        'You are the Group CFO at Puncak Horizon Holdings Berhad. Draft an external email to major shareholders using the evidence in DC_02_Group_Governance_Charter.docx and the Business Unit P&L and Investment Returns sheets in DC_01_Portfolio_Performance.xlsx. Acknowledge the issue directly, explain what is already under way, and avoid promising outcomes that depend on unresolved milestones or approvals. Keep the message concise and end with a RAG summary of what is confirmed, in progress, and still under review.',
        'You are the Group Strategy Director at Puncak Horizon Holdings Berhad. Draft an internal war-room email for group strategy and business unit CFOs that references the Capital Allocation Dashboard, Board Scorecard, and Investment Returns sheets in DC_01_Portfolio_Performance.xlsx and the responsibilities in DC_03_Corporate_Strategy_Framework.docx. State the three priorities for the next seven days, who owns each one, and what evidence must be ready for the leadership review. Present the bottom section as a RAG checklist so owners can act immediately.',
        'You are the Head of Group Governance at Puncak Horizon Holdings Berhad. Draft a steering-committee email that summarises the latest position using the Synergy Tracker and Business Unit P&L sheets in DC_01_Portfolio_Performance.xlsx. Highlight the decision required, the dependency that could block it, and the single biggest risk if the meeting slips by two weeks. Close with a RAG decision box showing approve now, approve with conditions, or hold.'
      ]),
      tool(T_TEAMS, M365_LIC, M365_ACCT, [
        'You are the Group CFO at Puncak Horizon Holdings Berhad. Use this recorded Teams meeting recap and cross-check it against the Business Unit P&L and Investment Returns sheets in DC_01_Portfolio_Performance.xlsx and DC_02_Group_Governance_Charter.docx. Extract every action item, owner, and deadline that matters to portfolio recovery and capital re-prioritisation, and identify where the conversation is not supported by the latest file evidence. Present the result as a RAG action register with columns Action, Owner, Due Date, Evidence Check, and Escalation Risk.',
        'You are the Group Strategy Director at Puncak Horizon Holdings Berhad. Use this recorded Teams meeting recap and compare the discussion with the Capital Allocation Dashboard, Board Scorecard, and Investment Returns sheets in DC_01_Portfolio_Performance.xlsx. Identify the top risks raised, what mitigation was proposed, and whether the control expectations in DC_03_Corporate_Strategy_Framework.docx were fully addressed. Present the result as a RAG risk log with Risk, Evidence, Proposed Mitigation, and Decision Owner.',
        'You are the Head of Group Governance at Puncak Horizon Holdings Berhad. Use this recorded Teams meeting recap and reconcile it with the Synergy Tracker and Business Unit P&L sheets in DC_01_Portfolio_Performance.xlsx. Separate decisions already taken, decisions that are still open, and assumptions that need independent validation before management can communicate externally. Present the result as a RAG decisions table with Decision, Current Status, Dependency, and Recommended Next Step.'
      ], DESC_TEAMS),
      tool(T_NOTEBOOK, M365_LIC, M365_ACCT, [
        "You are the Group CFO at Puncak Horizon Holdings Berhad. Upload DC_01_Portfolio_Performance.xlsx, DC_02_Group_Governance_Charter.docx, and DC_03_Corporate_Strategy_Framework.docx to Copilot Notebook. Set the notebook instruction to: 'Synthesize evidence across all files, cite the exact file and sheet name for every major claim, and focus on portfolio recovery and capital re-prioritisation.' Ask for a RAG executive synthesis with the current position, the root causes, the key dependencies, and the next three decisions management should take.",
        'You are the Group Strategy Director at Puncak Horizon Holdings Berhad. Upload DC_01_Portfolio_Performance.xlsx, DC_02_Group_Governance_Charter.docx, and DC_03_Corporate_Strategy_Framework.docx to Copilot Notebook. Ask Notebook to reconcile what the workbook signals in the Business Unit P&L, Board Scorecard, and Investment Returns sheets with the operating expectations in DC_02_Group_Governance_Charter.docx and DC_03_Corporate_Strategy_Framework.docx. Request a RAG table that shows where the documents and the live metrics align, conflict, or leave unanswered questions.',
        'You are the Head of Group Governance at Puncak Horizon Holdings Berhad. Upload DC_01_Portfolio_Performance.xlsx, DC_02_Group_Governance_Charter.docx, and DC_03_Corporate_Strategy_Framework.docx to Copilot Notebook. Ask Notebook for a 30-60-90 day plan that balances quick wins with durable control fixes for portfolio performance, capital discipline, and governance control, and make it explicit which actions depend on major shareholders or regulator feedback. Request the answer as a RAG roadmap with citations to the exact source file and sheet name for every recommendation.'
      ], DESC_NOTEBOOK),
      tool(T_COWORK, M365_LIC, M365_ACCT, [
        'You are the Group CFO at Puncak Horizon Holdings Berhad. Research external benchmarks relevant to portfolio performance, capital discipline, and governance control, then draft a 2-page brief grounded in DC_02_Group_Governance_Charter.docx and the Business Unit P&L and Investment Returns sheets in DC_01_Portfolio_Performance.xlsx. Save the brief to OneDrive, email it to the leadership sponsors, and schedule a 30-minute review meeting with the owners who need to move portfolio recovery and capital re-prioritisation this week. Make the brief a RAG action pack with a one-line decision ask on the first page.',
        'You are the Group Strategy Director at Puncak Horizon Holdings Berhad. Create a shared execution tracker from the Capital Allocation Dashboard, Board Scorecard, and Investment Returns sheets in DC_01_Portfolio_Performance.xlsx and the responsibilities described in DC_03_Corporate_Strategy_Framework.docx. Email the tracker to group strategy and business unit CFOs, ask each owner to confirm status by end of day, and schedule a recurring weekly checkpoint until the Red items are reduced. Make the tracker RAG-driven so overdue Red items are easy to escalate.'
      ], DESC_COWORK),
      tool(T_EDIT_COPILOT, M365_LIC, M365_ACCT, [
        "You are the Group CFO at Puncak Horizon Holdings Berhad. Using DC_02_Group_Governance_Charter.docx in Word for the web, add a new section called 'Executive Recovery Controls' that aligns with the risks visible in the Business Unit P&L and Investment Returns sheets in DC_01_Portfolio_Performance.xlsx. Restructure the document so the most urgent controls appear first, tighten repetitive language, and add a RAG summary table for leadership at the top. Keep the tone consistent with the existing document and make every new control action specific enough to assign an owner.",
        "You are the Group Strategy Director at Puncak Horizon Holdings Berhad. Using DC_01_Portfolio_Performance.xlsx in Excel for the web, create or refine a sheet called 'Leadership Tracker' using the Capital Allocation Dashboard, Board Scorecard, and Investment Returns sheets as source data. Reorder the columns so Red items appear first, standardise the formulas, and add a compact RAG summary block that updates automatically. Make the finished layout readable enough to paste into a leadership pack without manual cleanup."
      ], DESC_EDIT_COPILOT),
      tool(T_WORD_AGT, M365_LIC, M365_ACCT, [
        "You are the Group CFO at Puncak Horizon Holdings Berhad. In Word for the web, use DC_02_Group_Governance_Charter.docx to create a new agent called 'Group Governance Guide'. Describe it as an assistant that answers questions on portfolio performance, capital discipline, and governance control, the control expectations in the document, and the decisions leaders need for portfolio recovery and capital re-prioritisation. Share it with group strategy and business unit CFOs and make sure the welcome message explains the RAG logic it uses for prioritisation.",
        "You are the Group Strategy Director at Puncak Horizon Holdings Berhad. Demo the 'Group Governance Guide' agent with a question that references DC_02_Group_Governance_Charter.docx and the Business Unit P&L and Investment Returns sheets in DC_01_Portfolio_Performance.xlsx. Ask the agent to explain the top Red issue, the control the document expects, and the owner who should respond first. Show the response as a concise RAG answer with a source citation."
      ], DESC_WORD_AGT),
      tool(T_PPT_AGT, M365_LIC, M365_ACCT, [
        "You are the Group CFO at Puncak Horizon Holdings Berhad. Create a PowerPoint briefing from DC_01_Portfolio_Performance.xlsx, DC_02_Group_Governance_Charter.docx, and DC_03_Corporate_Strategy_Framework.docx, then create a new agent called 'Portfolio Review Deck Guide'. Describe it as a deck navigator that helps leaders answer questions about portfolio performance, capital discipline, and governance control, the major Red items, and the decisions required this month. Share it with the Board, business unit CEOs, and investors and configure the opening prompt to point users to the highest-risk slide first.",
        "You are the Head of Group Governance at Puncak Horizon Holdings Berhad. Demo the 'Portfolio Review Deck Guide' agent by asking which slide best explains the current Red items from the Business Unit P&L, Synergy Tracker, and Investment Returns sheets in DC_01_Portfolio_Performance.xlsx. Then ask for a 60-second RAG summary of the story the presenter should tell to major shareholders. Require the answer to cite the slide topic it is drawing from."
      ], DESC_PPT_AGT),
      tool(T_XL_AGT, M365_LIC, M365_ACCT, [
        "You are the Group CFO at Puncak Horizon Holdings Berhad. In Excel for the web, use DC_01_Portfolio_Performance.xlsx to create a new agent called 'Portfolio Performance Q&A'. Describe it as an assistant that answers questions on the Business Unit P&L, Capital Allocation Dashboard, Synergy Tracker, Board Scorecard, and Investment Returns sheets and translates workbook signals into RAG-ready management insight for portfolio recovery and capital re-prioritisation. Share it with group strategy and business unit CFOs and set the starter prompt to surface the top Red metrics automatically.",
        "You are the Group Strategy Director at Puncak Horizon Holdings Berhad. Demo the 'Portfolio Performance Q&A' agent by asking which indicators in the Business Unit P&L, Board Scorecard, and Investment Returns sheets are currently Red and what action would most likely move each one to Amber. Then ask for the single metric management should watch weekly if it can only track one item. Require the reply to be a RAG summary that names the exact sheet for every answer."
      ], DESC_XL_AGT),
      tool(T_BUILDER, M365_LIC, M365_ACCT, [
        "You are the Group CFO at Puncak Horizon Holdings Berhad. Go to Copilot Studio and create a new agent called 'Puncak Horizon Executive Copilot' using DC_01_Portfolio_Performance.xlsx, DC_02_Group_Governance_Charter.docx, and DC_03_Corporate_Strategy_Framework.docx as knowledge sources. Describe it as an assistant for the Board, business unit CEOs, and investors that supports portfolio recovery and capital re-prioritisation, add the topics Unit P&L, Capital Allocation, Synergy Capture, and Board Scorecard, and publish it to Teams for the right audience. Make the starter prompts explicitly return Red, Amber, or Green recommendations when users ask for priorities.",
        "You are the Head of Group Governance at Puncak Horizon Holdings Berhad. Demo the 'Puncak Horizon Executive Copilot' agent with a question that combines the Business Unit P&L, Synergy Tracker, and Investment Returns sheets in DC_01_Portfolio_Performance.xlsx with the policy direction in DC_02_Group_Governance_Charter.docx. Ask for the top Red issue, the fastest Amber recovery action, and the Green area management should preserve while portfolio recovery and capital re-prioritisation is under way. Require the answer to cite the file evidence it used for each RAG judgement."
      ], DESC_BUILDER),
    ],
    companyID='PT Cakrawala Multi Usaha Tbk',
    taglineID='Alokasi modal tertekan saat dua portofolio utama meleset.'),

# ── FINTECH & PAYMENTS ─────────────────────────────────────────────────────
ind('fintech-payments', 'fintech', 'Fintech & Payments', '💳', '#6A1B9A', '#7B1FA2',
    'BayarLintas Digital Berhad',
    'Fraud spikes and licence scrutiny are threatening growth corridors.',
    'BayarLintas Digital Berhad is scaling merchant and consumer payment volumes while regulators are asking harder questions about fraud controls, capital resilience, and licence readiness. Product growth remains attractive, but management sees a widening gap between commercial ambition and control maturity. The executive team needs a joined-up view that can satisfy regulators without slowing the right growth bets.',
    ['FT_01_Payments_Operations.xlsx', 'FT_02_Compliance_Policy.docx', 'FT_03_Product_Roadmap.docx'],
    [
      tool(T_CHAT, FREE_LIC, FREE_ACCT, [
        'You are the Chief Risk Officer at BayarLintas Digital Berhad. Use the Transaction Volume, Fraud Incident Log, and License Compliance sheets in FT_01_Payments_Operations.xlsx together with FT_02_Compliance_Policy.docx and FT_03_Product_Roadmap.docx. Brief the leadership team on payments growth, fraud control, and licence readiness, and separate the immediate operating gaps, control gaps, and stakeholder exposure that could escalate with BNM and OJK and BI or regulators and partner banks. Present the answer as a RAG table with columns Risk, Evidence, 30-Day Action, and Owner.',
        'You are the Chief Compliance Officer at BayarLintas Digital Berhad. Use the Fraud Incident Log, Product Revenue Tracker, and Transaction Volume sheets in FT_01_Payments_Operations.xlsx together with FT_03_Product_Roadmap.docx. Diagnose which areas are recoverable within one quarter, which need management intervention now, and which should be paused until controls in the operating documents are tightened. Present the answer as a RAG heat map with the unit or workstream, the leading indicator, the root cause, and the next action.',
        'You are the Chief Product Officer at BayarLintas Digital Berhad. Use the Regulatory Capital Dashboard, License Compliance, and Product Revenue Tracker sheets in FT_01_Payments_Operations.xlsx together with FT_02_Compliance_Policy.docx and FT_03_Product_Roadmap.docx. Prepare decision-quality talking points for regulators, product leaders, and enterprise merchants that distinguish what management can commit today, what depends on milestones, and what should be disclosed carefully. Present the answer as a RAG message matrix with audience, key message, evidence source, and approval owner.'
      ]),
      tool(T_RESEARCHER, FREE_LIC, FREE_ACCT, [
        'You are the Chief Risk Officer at BayarLintas Digital Berhad. Research how organisations in Malaysia and Indonesia have handled payments growth, fraud control, and licence readiness since 2023, with explicit attention to guidance from BNM and OJK and BI that would affect the Transaction Volume and License Compliance sheets and FT_02_Compliance_Policy.docx. Distinguish mandatory expectations, market practice, and peer tactics that management could apply to licence readiness and payments risk control. Present the findings as a RAG benchmark table with columns Theme, Malaysia, Indonesia, Evidence Source, and Management Implication. Flag any claim that could not be independently verified.',
        'You are the Chief Compliance Officer at BayarLintas Digital Berhad. Research the highest-impact operational levers that comparable teams have used to improve the indicators tracked in the Fraud Incident Log, Product Revenue Tracker, and Regulatory Capital Dashboard sheets. Prioritise published case studies, association guidance, or regulator commentary that would be credible in front of regulators, product leaders, and enterprise merchants. Present the findings as a RAG table with Intervention, Expected Benefit, Time to Impact, and Evidence Strength. Flag any claim that could not be independently verified.',
        'You are the Chief Product Officer at BayarLintas Digital Berhad. Research what investors, customers, sponsors, or regulators typically expect to see when management is trying to stabilise payments growth, fraud control, and licence readiness, using examples that align with FT_02_Compliance_Policy.docx and FT_03_Product_Roadmap.docx. Highlight what leading teams communicate in the first 30 days, 60 days, and 90 days so the messaging is defensible with regulators and partner banks. Present the findings as a RAG roadmap with Time Horizon, Expected Action, External Signal, and Practical Implication. Flag any claim that could not be independently verified.'
      ], DESC_RESEARCHER),
      tool(T_ANALYST, M365_LIC, M365_ACCT, [
        'You are the Chief Risk Officer at BayarLintas Digital Berhad. Upload FT_01_Payments_Operations.xlsx to Analyst and use the Transaction Volume, Fraud Incident Log, and Regulatory Capital Dashboard sheets to quantify where current performance is deviating from plan. Estimate the financial, service, or programme impact of each gap and highlight which areas are most material to licence readiness and payments risk control. Present the output as a RAG table with Metric, Current Position, Gap, Impact Estimate, and Recommended Action.',
        'You are the Chief Compliance Officer at BayarLintas Digital Berhad. Upload FT_01_Payments_Operations.xlsx and FT_02_Compliance_Policy.docx to Analyst, then cross-reference the Fraud Incident Log, Product Revenue Tracker, and License Compliance sheets against the control expectations in the document. Identify the hotspots where weak execution and weak governance are reinforcing each other and rank them by urgency. Present the answer as a RAG heat map with Area, Root Cause, Evidence, Escalation Risk, and Owner.',
        'You are the Chief Product Officer at BayarLintas Digital Berhad. Upload FT_01_Payments_Operations.xlsx to Analyst and build a forward look from the Regulatory Capital Dashboard, Product Revenue Tracker, and License Compliance sheets for the next two quarters. Show the upside case, base case, and downside case for management if current trends continue versus if the highest-priority actions land on time. Present the result as a RAG scenario table with Scenario, Key Assumption, Expected Outcome, and Trigger for Escalation.'
      ], DESC_ANALYST),
      tool(T_EXCEL, M365_LIC, M365_ACCT, [
        "You are the Chief Risk Officer at BayarLintas Digital Berhad. Using the Transaction Volume, Regulatory Capital Dashboard, and License Compliance sheets in FT_01_Payments_Operations.xlsx, create a new worksheet called 'Executive RAG Dashboard'. Show the core metrics that matter most to licence readiness and payments risk control, a short variance note, and a Red, Amber, or Green status for each metric. Design it so the first view is board-ready and the formulas refresh automatically when source values change.",
        "You are the Chief Compliance Officer at BayarLintas Digital Berhad. Using the Fraud Incident Log, Product Revenue Tracker, and Regulatory Capital Dashboard sheets in FT_01_Payments_Operations.xlsx, create a new worksheet called 'Recovery Scenarios'. Model what happens if management closes half the current gap within one quarter versus if the trend deteriorates by another 10 percent. Present the result as a RAG scenario model with assumptions, impact, and recommended management response.",
        "You are the Chief Product Officer at BayarLintas Digital Berhad. Using the License Compliance, Transaction Volume, and Product Revenue Tracker sheets in FT_01_Payments_Operations.xlsx, create a new worksheet called 'Action Tracker'. List the highest-priority actions, the metric each action should move, the target date, and the owner that risk, compliance, and product leads should hold accountable. Make the tracker a RAG control sheet with overdue items highlighted automatically."
      ]),
      tool(T_WORD, M365_LIC, M365_ACCT, [
        'You are the Chief Risk Officer at BayarLintas Digital Berhad. Use FT_02_Compliance_Policy.docx together with the Transaction Volume and License Compliance sheets in FT_01_Payments_Operations.xlsx to draft a 2-page Risk committee memo. Explain the current position, the governance or policy implications, and the decisions required to stabilise payments growth, fraud control, and licence readiness. Start with a short RAG summary and end with a 30-day action table.',
        'You are the Chief Compliance Officer at BayarLintas Digital Berhad. Use FT_03_Product_Roadmap.docx together with the Fraud Incident Log and Product Revenue Tracker sheets in FT_01_Payments_Operations.xlsx to draft a stakeholder-ready note for regulators and partner banks. Make the narrative analytical rather than promotional, and distinguish what is already evidenced in the files from what is still being validated. Present the note with a RAG section on commitments, dependencies, and unresolved risks.',
        'You are the Chief Product Officer at BayarLintas Digital Berhad. Use FT_02_Compliance_Policy.docx and FT_03_Product_Roadmap.docx together with the Regulatory Capital Dashboard and License Compliance sheets in FT_01_Payments_Operations.xlsx to draft a 90-day operating action plan for risk, compliance, and product leads. Show how management should sequence the work so quick wins support the longer-control fixes needed for licence readiness and payments risk control. Present the plan as a RAG table with Week, Action, Dependency, and Success Measure.'
      ]),
      tool(T_PPT, M365_LIC, M365_ACCT, [
        'You are the Chief Risk Officer at BayarLintas Digital Berhad. Create a 6-slide executive deck using FT_01_Payments_Operations.xlsx, FT_02_Compliance_Policy.docx, and FT_03_Product_Roadmap.docx as the source context. Cover the current position, the most material gaps, the implications for regulators, product leaders, and enterprise merchants, the stabilisation plan, the financial or delivery outlook, and the decisions required this month. Give each slide a headline with a RAG status and keep the layout tight enough for a board review.',
        'You are the Chief Compliance Officer at BayarLintas Digital Berhad. Create a 3-slide update pack for regulators and partner banks using the Transaction Volume, Regulatory Capital Dashboard, and License Compliance sheets and FT_02_Compliance_Policy.docx. Slide 1 should summarise the issue, slide 2 should show evidence-backed progress, and slide 3 should state the next milestone commitments. Add a RAG ribbon to each slide so the risk posture is obvious at a glance.',
        'You are the Chief Product Officer at BayarLintas Digital Berhad. Create a single heat-map slide from the Fraud Incident Log, Product Revenue Tracker, and License Compliance sheets in FT_01_Payments_Operations.xlsx. Show which business units, processes, regions, or workstreams are Red, Amber, or Green and note the one action that would most likely move each Red area back to Amber. Use an executive style and include a short legend that ties the colours to management action.'
      ]),
      tool(T_OUTLOOK, M365_LIC, M365_ACCT, [
        'You are the Chief Risk Officer at BayarLintas Digital Berhad. Draft an external email to regulators and partner banks using the evidence in FT_02_Compliance_Policy.docx and the Transaction Volume and License Compliance sheets in FT_01_Payments_Operations.xlsx. Acknowledge the issue directly, explain what is already under way, and avoid promising outcomes that depend on unresolved milestones or approvals. Keep the message concise and end with a RAG summary of what is confirmed, in progress, and still under review.',
        'You are the Chief Compliance Officer at BayarLintas Digital Berhad. Draft an internal war-room email for risk, compliance, and product leads that references the Fraud Incident Log, Product Revenue Tracker, and License Compliance sheets in FT_01_Payments_Operations.xlsx and the responsibilities in FT_03_Product_Roadmap.docx. State the three priorities for the next seven days, who owns each one, and what evidence must be ready for the leadership review. Present the bottom section as a RAG checklist so owners can act immediately.',
        'You are the Chief Product Officer at BayarLintas Digital Berhad. Draft a steering-committee email that summarises the latest position using the Regulatory Capital Dashboard and Transaction Volume sheets in FT_01_Payments_Operations.xlsx. Highlight the decision required, the dependency that could block it, and the single biggest risk if the meeting slips by two weeks. Close with a RAG decision box showing approve now, approve with conditions, or hold.'
      ]),
      tool(T_TEAMS, M365_LIC, M365_ACCT, [
        'You are the Chief Risk Officer at BayarLintas Digital Berhad. Use this recorded Teams meeting recap and cross-check it against the Transaction Volume and License Compliance sheets in FT_01_Payments_Operations.xlsx and FT_02_Compliance_Policy.docx. Extract every action item, owner, and deadline that matters to licence readiness and payments risk control, and identify where the conversation is not supported by the latest file evidence. Present the result as a RAG action register with columns Action, Owner, Due Date, Evidence Check, and Escalation Risk.',
        'You are the Chief Compliance Officer at BayarLintas Digital Berhad. Use this recorded Teams meeting recap and compare the discussion with the Fraud Incident Log, Product Revenue Tracker, and License Compliance sheets in FT_01_Payments_Operations.xlsx. Identify the top risks raised, what mitigation was proposed, and whether the control expectations in FT_03_Product_Roadmap.docx were fully addressed. Present the result as a RAG risk log with Risk, Evidence, Proposed Mitigation, and Decision Owner.',
        'You are the Chief Product Officer at BayarLintas Digital Berhad. Use this recorded Teams meeting recap and reconcile it with the Regulatory Capital Dashboard and Transaction Volume sheets in FT_01_Payments_Operations.xlsx. Separate decisions already taken, decisions that are still open, and assumptions that need independent validation before management can communicate externally. Present the result as a RAG decisions table with Decision, Current Status, Dependency, and Recommended Next Step.'
      ], DESC_TEAMS),
      tool(T_NOTEBOOK, M365_LIC, M365_ACCT, [
        "You are the Chief Risk Officer at BayarLintas Digital Berhad. Upload FT_01_Payments_Operations.xlsx, FT_02_Compliance_Policy.docx, and FT_03_Product_Roadmap.docx to Copilot Notebook. Set the notebook instruction to: 'Synthesize evidence across all files, cite the exact file and sheet name for every major claim, and focus on licence readiness and payments risk control.' Ask for a RAG executive synthesis with the current position, the root causes, the key dependencies, and the next three decisions management should take.",
        'You are the Chief Compliance Officer at BayarLintas Digital Berhad. Upload FT_01_Payments_Operations.xlsx, FT_02_Compliance_Policy.docx, and FT_03_Product_Roadmap.docx to Copilot Notebook. Ask Notebook to reconcile what the workbook signals in the Transaction Volume, Product Revenue Tracker, and License Compliance sheets with the operating expectations in FT_02_Compliance_Policy.docx and FT_03_Product_Roadmap.docx. Request a RAG table that shows where the documents and the live metrics align, conflict, or leave unanswered questions.',
        'You are the Chief Product Officer at BayarLintas Digital Berhad. Upload FT_01_Payments_Operations.xlsx, FT_02_Compliance_Policy.docx, and FT_03_Product_Roadmap.docx to Copilot Notebook. Ask Notebook for a 30-60-90 day plan that balances quick wins with durable control fixes for payments growth, fraud control, and licence readiness, and make it explicit which actions depend on regulators and partner banks or regulator feedback. Request the answer as a RAG roadmap with citations to the exact source file and sheet name for every recommendation.'
      ], DESC_NOTEBOOK),
      tool(T_COWORK, M365_LIC, M365_ACCT, [
        'You are the Chief Risk Officer at BayarLintas Digital Berhad. Research external benchmarks relevant to payments growth, fraud control, and licence readiness, then draft a 2-page brief grounded in FT_02_Compliance_Policy.docx and the Transaction Volume and License Compliance sheets in FT_01_Payments_Operations.xlsx. Save the brief to OneDrive, email it to the leadership sponsors, and schedule a 30-minute review meeting with the owners who need to move licence readiness and payments risk control this week. Make the brief a RAG action pack with a one-line decision ask on the first page.',
        'You are the Chief Compliance Officer at BayarLintas Digital Berhad. Create a shared execution tracker from the Fraud Incident Log, Product Revenue Tracker, and License Compliance sheets in FT_01_Payments_Operations.xlsx and the responsibilities described in FT_03_Product_Roadmap.docx. Email the tracker to risk, compliance, and product leads, ask each owner to confirm status by end of day, and schedule a recurring weekly checkpoint until the Red items are reduced. Make the tracker RAG-driven so overdue Red items are easy to escalate.'
      ], DESC_COWORK),
      tool(T_EDIT_COPILOT, M365_LIC, M365_ACCT, [
        "You are the Chief Risk Officer at BayarLintas Digital Berhad. Using FT_02_Compliance_Policy.docx in Word for the web, add a new section called 'Executive Recovery Controls' that aligns with the risks visible in the Transaction Volume and License Compliance sheets in FT_01_Payments_Operations.xlsx. Restructure the document so the most urgent controls appear first, tighten repetitive language, and add a RAG summary table for leadership at the top. Keep the tone consistent with the existing document and make every new control action specific enough to assign an owner.",
        "You are the Chief Compliance Officer at BayarLintas Digital Berhad. Using FT_01_Payments_Operations.xlsx in Excel for the web, create or refine a sheet called 'Leadership Tracker' using the Fraud Incident Log, Product Revenue Tracker, and License Compliance sheets as source data. Reorder the columns so Red items appear first, standardise the formulas, and add a compact RAG summary block that updates automatically. Make the finished layout readable enough to paste into a leadership pack without manual cleanup."
      ], DESC_EDIT_COPILOT),
      tool(T_WORD_AGT, M365_LIC, M365_ACCT, [
        "You are the Chief Risk Officer at BayarLintas Digital Berhad. In Word for the web, use FT_02_Compliance_Policy.docx to create a new agent called 'Payments Compliance Guide'. Describe it as an assistant that answers questions on payments growth, fraud control, and licence readiness, the control expectations in the document, and the decisions leaders need for licence readiness and payments risk control. Share it with risk, compliance, and product leads and make sure the welcome message explains the RAG logic it uses for prioritisation.",
        "You are the Chief Compliance Officer at BayarLintas Digital Berhad. Demo the 'Payments Compliance Guide' agent with a question that references FT_02_Compliance_Policy.docx and the Transaction Volume and License Compliance sheets in FT_01_Payments_Operations.xlsx. Ask the agent to explain the top Red issue, the control the document expects, and the owner who should respond first. Show the response as a concise RAG answer with a source citation."
      ], DESC_WORD_AGT),
      tool(T_PPT_AGT, M365_LIC, M365_ACCT, [
        "You are the Chief Risk Officer at BayarLintas Digital Berhad. Create a PowerPoint briefing from FT_01_Payments_Operations.xlsx, FT_02_Compliance_Policy.docx, and FT_03_Product_Roadmap.docx, then create a new agent called 'Payments Risk Deck Guide'. Describe it as a deck navigator that helps leaders answer questions about payments growth, fraud control, and licence readiness, the major Red items, and the decisions required this month. Share it with regulators, product leaders, and enterprise merchants and configure the opening prompt to point users to the highest-risk slide first.",
        "You are the Chief Product Officer at BayarLintas Digital Berhad. Demo the 'Payments Risk Deck Guide' agent by asking which slide best explains the current Red items from the Transaction Volume, Regulatory Capital Dashboard, and License Compliance sheets in FT_01_Payments_Operations.xlsx. Then ask for a 60-second RAG summary of the story the presenter should tell to regulators and partner banks. Require the answer to cite the slide topic it is drawing from."
      ], DESC_PPT_AGT),
      tool(T_XL_AGT, M365_LIC, M365_ACCT, [
        "You are the Chief Risk Officer at BayarLintas Digital Berhad. In Excel for the web, use FT_01_Payments_Operations.xlsx to create a new agent called 'Payments Operations Q&A'. Describe it as an assistant that answers questions on the Transaction Volume, Fraud Incident Log, Regulatory Capital Dashboard, Product Revenue Tracker, and License Compliance sheets and translates workbook signals into RAG-ready management insight for licence readiness and payments risk control. Share it with risk, compliance, and product leads and set the starter prompt to surface the top Red metrics automatically.",
        "You are the Chief Compliance Officer at BayarLintas Digital Berhad. Demo the 'Payments Operations Q&A' agent by asking which indicators in the Transaction Volume, Product Revenue Tracker, and License Compliance sheets are currently Red and what action would most likely move each one to Amber. Then ask for the single metric management should watch weekly if it can only track one item. Require the reply to be a RAG summary that names the exact sheet for every answer."
      ], DESC_XL_AGT),
      tool(T_BUILDER, M365_LIC, M365_ACCT, [
        "You are the Chief Risk Officer at BayarLintas Digital Berhad. Go to Copilot Studio and create a new agent called 'BayarLintas Risk Copilot' using FT_01_Payments_Operations.xlsx, FT_02_Compliance_Policy.docx, and FT_03_Product_Roadmap.docx as knowledge sources. Describe it as an assistant for regulators, product leaders, and enterprise merchants that supports licence readiness and payments risk control, add the topics Transaction Growth, Fraud Control, Capital Buffer, and Licence Compliance, and publish it to Teams for the right audience. Make the starter prompts explicitly return Red, Amber, or Green recommendations when users ask for priorities.",
        "You are the Chief Product Officer at BayarLintas Digital Berhad. Demo the 'BayarLintas Risk Copilot' agent with a question that combines the Transaction Volume, Regulatory Capital Dashboard, and License Compliance sheets in FT_01_Payments_Operations.xlsx with the policy direction in FT_02_Compliance_Policy.docx. Ask for the top Red issue, the fastest Amber recovery action, and the Green area management should preserve while licence readiness and payments risk control is under way. Require the answer to cite the file evidence it used for each RAG judgement."
      ], DESC_BUILDER),
    ],
    companyID='PT BayarLintas Digital Indonesia Tbk',
    taglineID='Lonjakan fraud dan sorotan lisensi mengancam koridor pertumbuhan.'),

# ── GOVERNMENT AGENCY ──────────────────────────────────────────────────────
ind('government-agency', 'government', 'Government Agency', '🏛', '#4E342E', '#5D4037',
    'Agensi Pemodenan Perkhidmatan Madani',
    'Budget slippage and open audit findings are delaying flagship programmes.',
    'Agensi Pemodenan Perkhidmatan Madani is coordinating multi-agency delivery programmes with tight public deadlines and high ministerial visibility. Budget utilisation is uneven, several audit findings remain open, and procurement bottlenecks are starting to affect service outcomes. Leadership needs one joined-up view of KPI delivery, governance discipline, and execution risk before the next sponsor review.',
    ['GOV_01_Programme_Performance.xlsx', 'GOV_02_Programme_Governance_Manual.docx', 'GOV_03_Public_Service_Policy.docx'],
    [
      tool(T_CHAT, FREE_LIC, FREE_ACCT, [
        'You are the Programme Director at Agensi Pemodenan Perkhidmatan Madani. Use the KPI Scorecard, Budget Utilisation, and Procurement Dashboard sheets in GOV_01_Programme_Performance.xlsx together with GOV_02_Programme_Governance_Manual.docx and GOV_03_Public_Service_Policy.docx. Brief the leadership team on programme delivery, audit closure, and public-service reform, and separate the immediate operating gaps, control gaps, and stakeholder exposure that could escalate with EPU, JPA, and MAMPU and BAPPENAS and BKN or programme sponsors and implementing agencies. Present the answer as a RAG table with columns Risk, Evidence, 30-Day Action, and Owner.',
        'You are the Head of Policy Delivery at Agensi Pemodenan Perkhidmatan Madani. Use the Budget Utilisation, Audit Findings Tracker, and KPI Scorecard sheets in GOV_01_Programme_Performance.xlsx together with GOV_03_Public_Service_Policy.docx. Diagnose which areas are recoverable within one quarter, which need management intervention now, and which should be paused until controls in the operating documents are tightened. Present the answer as a RAG heat map with the unit or workstream, the leading indicator, the root cause, and the next action.',
        'You are the Chief Digital Officer at Agensi Pemodenan Perkhidmatan Madani. Use the Stakeholder Engagement Log, Procurement Dashboard, and Audit Findings Tracker sheets in GOV_01_Programme_Performance.xlsx together with GOV_02_Programme_Governance_Manual.docx and GOV_03_Public_Service_Policy.docx. Prepare decision-quality talking points for the sponsor ministry, programme directors, and public service leadership that distinguish what management can commit today, what depends on milestones, and what should be disclosed carefully. Present the answer as a RAG message matrix with audience, key message, evidence source, and approval owner.'
      ]),
      tool(T_RESEARCHER, FREE_LIC, FREE_ACCT, [
        'You are the Programme Director at Agensi Pemodenan Perkhidmatan Madani. Research how organisations in Malaysia and Indonesia have handled programme delivery, audit closure, and public-service reform since 2023, with explicit attention to guidance from EPU, JPA, and MAMPU and BAPPENAS and BKN that would affect the KPI Scorecard and Procurement Dashboard sheets and GOV_02_Programme_Governance_Manual.docx. Distinguish mandatory expectations, market practice, and peer tactics that management could apply to programme recovery and service delivery reform. Present the findings as a RAG benchmark table with columns Theme, Malaysia, Indonesia, Evidence Source, and Management Implication. Flag any claim that could not be independently verified.',
        'You are the Head of Policy Delivery at Agensi Pemodenan Perkhidmatan Madani. Research the highest-impact operational levers that comparable teams have used to improve the indicators tracked in the Budget Utilisation, Audit Findings Tracker, and Stakeholder Engagement Log sheets. Prioritise published case studies, association guidance, or regulator commentary that would be credible in front of the sponsor ministry, programme directors, and public service leadership. Present the findings as a RAG table with Intervention, Expected Benefit, Time to Impact, and Evidence Strength. Flag any claim that could not be independently verified.',
        'You are the Chief Digital Officer at Agensi Pemodenan Perkhidmatan Madani. Research what investors, customers, sponsors, or regulators typically expect to see when management is trying to stabilise programme delivery, audit closure, and public-service reform, using examples that align with GOV_02_Programme_Governance_Manual.docx and GOV_03_Public_Service_Policy.docx. Highlight what leading teams communicate in the first 30 days, 60 days, and 90 days so the messaging is defensible with programme sponsors and implementing agencies. Present the findings as a RAG roadmap with Time Horizon, Expected Action, External Signal, and Practical Implication. Flag any claim that could not be independently verified.'
      ], DESC_RESEARCHER),
      tool(T_ANALYST, M365_LIC, M365_ACCT, [
        'You are the Programme Director at Agensi Pemodenan Perkhidmatan Madani. Upload GOV_01_Programme_Performance.xlsx to Analyst and use the KPI Scorecard, Budget Utilisation, and Stakeholder Engagement Log sheets to quantify where current performance is deviating from plan. Estimate the financial, service, or programme impact of each gap and highlight which areas are most material to programme recovery and service delivery reform. Present the output as a RAG table with Metric, Current Position, Gap, Impact Estimate, and Recommended Action.',
        'You are the Head of Policy Delivery at Agensi Pemodenan Perkhidmatan Madani. Upload GOV_01_Programme_Performance.xlsx and GOV_02_Programme_Governance_Manual.docx to Analyst, then cross-reference the Budget Utilisation, Audit Findings Tracker, and Procurement Dashboard sheets against the control expectations in the document. Identify the hotspots where weak execution and weak governance are reinforcing each other and rank them by urgency. Present the answer as a RAG heat map with Area, Root Cause, Evidence, Escalation Risk, and Owner.',
        'You are the Chief Digital Officer at Agensi Pemodenan Perkhidmatan Madani. Upload GOV_01_Programme_Performance.xlsx to Analyst and build a forward look from the Stakeholder Engagement Log, Audit Findings Tracker, and Procurement Dashboard sheets for the next two quarters. Show the upside case, base case, and downside case for management if current trends continue versus if the highest-priority actions land on time. Present the result as a RAG scenario table with Scenario, Key Assumption, Expected Outcome, and Trigger for Escalation.'
      ], DESC_ANALYST),
      tool(T_EXCEL, M365_LIC, M365_ACCT, [
        "You are the Programme Director at Agensi Pemodenan Perkhidmatan Madani. Using the KPI Scorecard, Stakeholder Engagement Log, and Procurement Dashboard sheets in GOV_01_Programme_Performance.xlsx, create a new worksheet called 'Executive RAG Dashboard'. Show the core metrics that matter most to programme recovery and service delivery reform, a short variance note, and a Red, Amber, or Green status for each metric. Design it so the first view is board-ready and the formulas refresh automatically when source values change.",
        "You are the Head of Policy Delivery at Agensi Pemodenan Perkhidmatan Madani. Using the Budget Utilisation, Audit Findings Tracker, and Stakeholder Engagement Log sheets in GOV_01_Programme_Performance.xlsx, create a new worksheet called 'Recovery Scenarios'. Model what happens if management closes half the current gap within one quarter versus if the trend deteriorates by another 10 percent. Present the result as a RAG scenario model with assumptions, impact, and recommended management response.",
        "You are the Chief Digital Officer at Agensi Pemodenan Perkhidmatan Madani. Using the Procurement Dashboard, KPI Scorecard, and Audit Findings Tracker sheets in GOV_01_Programme_Performance.xlsx, create a new worksheet called 'Action Tracker'. List the highest-priority actions, the metric each action should move, the target date, and the owner that programme and procurement leads should hold accountable. Make the tracker a RAG control sheet with overdue items highlighted automatically."
      ]),
      tool(T_WORD, M365_LIC, M365_ACCT, [
        'You are the Programme Director at Agensi Pemodenan Perkhidmatan Madani. Use GOV_02_Programme_Governance_Manual.docx together with the KPI Scorecard and Procurement Dashboard sheets in GOV_01_Programme_Performance.xlsx to draft a 2-page Sponsor review memo. Explain the current position, the governance or policy implications, and the decisions required to stabilise programme delivery, audit closure, and public-service reform. Start with a short RAG summary and end with a 30-day action table.',
        'You are the Head of Policy Delivery at Agensi Pemodenan Perkhidmatan Madani. Use GOV_03_Public_Service_Policy.docx together with the Budget Utilisation and Audit Findings Tracker sheets in GOV_01_Programme_Performance.xlsx to draft a stakeholder-ready note for programme sponsors and implementing agencies. Make the narrative analytical rather than promotional, and distinguish what is already evidenced in the files from what is still being validated. Present the note with a RAG section on commitments, dependencies, and unresolved risks.',
        'You are the Chief Digital Officer at Agensi Pemodenan Perkhidmatan Madani. Use GOV_02_Programme_Governance_Manual.docx and GOV_03_Public_Service_Policy.docx together with the Stakeholder Engagement Log and Procurement Dashboard sheets in GOV_01_Programme_Performance.xlsx to draft a 90-day operating action plan for programme and procurement leads. Show how management should sequence the work so quick wins support the longer-control fixes needed for programme recovery and service delivery reform. Present the plan as a RAG table with Week, Action, Dependency, and Success Measure.'
      ]),
      tool(T_PPT, M365_LIC, M365_ACCT, [
        'You are the Programme Director at Agensi Pemodenan Perkhidmatan Madani. Create a 6-slide executive deck using GOV_01_Programme_Performance.xlsx, GOV_02_Programme_Governance_Manual.docx, and GOV_03_Public_Service_Policy.docx as the source context. Cover the current position, the most material gaps, the implications for the sponsor ministry, programme directors, and public service leadership, the stabilisation plan, the financial or delivery outlook, and the decisions required this month. Give each slide a headline with a RAG status and keep the layout tight enough for a board review.',
        'You are the Head of Policy Delivery at Agensi Pemodenan Perkhidmatan Madani. Create a 3-slide update pack for programme sponsors and implementing agencies using the KPI Scorecard, Stakeholder Engagement Log, and Procurement Dashboard sheets and GOV_02_Programme_Governance_Manual.docx. Slide 1 should summarise the issue, slide 2 should show evidence-backed progress, and slide 3 should state the next milestone commitments. Add a RAG ribbon to each slide so the risk posture is obvious at a glance.',
        'You are the Chief Digital Officer at Agensi Pemodenan Perkhidmatan Madani. Create a single heat-map slide from the Budget Utilisation, Audit Findings Tracker, and Procurement Dashboard sheets in GOV_01_Programme_Performance.xlsx. Show which business units, processes, regions, or workstreams are Red, Amber, or Green and note the one action that would most likely move each Red area back to Amber. Use an executive style and include a short legend that ties the colours to management action.'
      ]),
      tool(T_OUTLOOK, M365_LIC, M365_ACCT, [
        'You are the Programme Director at Agensi Pemodenan Perkhidmatan Madani. Draft an external email to programme sponsors and implementing agencies using the evidence in GOV_02_Programme_Governance_Manual.docx and the KPI Scorecard and Procurement Dashboard sheets in GOV_01_Programme_Performance.xlsx. Acknowledge the issue directly, explain what is already under way, and avoid promising outcomes that depend on unresolved milestones or approvals. Keep the message concise and end with a RAG summary of what is confirmed, in progress, and still under review.',
        'You are the Head of Policy Delivery at Agensi Pemodenan Perkhidmatan Madani. Draft an internal war-room email for programme and procurement leads that references the Budget Utilisation, Audit Findings Tracker, and Procurement Dashboard sheets in GOV_01_Programme_Performance.xlsx and the responsibilities in GOV_03_Public_Service_Policy.docx. State the three priorities for the next seven days, who owns each one, and what evidence must be ready for the leadership review. Present the bottom section as a RAG checklist so owners can act immediately.',
        'You are the Chief Digital Officer at Agensi Pemodenan Perkhidmatan Madani. Draft a steering-committee email that summarises the latest position using the Stakeholder Engagement Log and KPI Scorecard sheets in GOV_01_Programme_Performance.xlsx. Highlight the decision required, the dependency that could block it, and the single biggest risk if the meeting slips by two weeks. Close with a RAG decision box showing approve now, approve with conditions, or hold.'
      ]),
      tool(T_TEAMS, M365_LIC, M365_ACCT, [
        'You are the Programme Director at Agensi Pemodenan Perkhidmatan Madani. Use this recorded Teams meeting recap and cross-check it against the KPI Scorecard and Procurement Dashboard sheets in GOV_01_Programme_Performance.xlsx and GOV_02_Programme_Governance_Manual.docx. Extract every action item, owner, and deadline that matters to programme recovery and service delivery reform, and identify where the conversation is not supported by the latest file evidence. Present the result as a RAG action register with columns Action, Owner, Due Date, Evidence Check, and Escalation Risk.',
        'You are the Head of Policy Delivery at Agensi Pemodenan Perkhidmatan Madani. Use this recorded Teams meeting recap and compare the discussion with the Budget Utilisation, Audit Findings Tracker, and Procurement Dashboard sheets in GOV_01_Programme_Performance.xlsx. Identify the top risks raised, what mitigation was proposed, and whether the control expectations in GOV_03_Public_Service_Policy.docx were fully addressed. Present the result as a RAG risk log with Risk, Evidence, Proposed Mitigation, and Decision Owner.',
        'You are the Chief Digital Officer at Agensi Pemodenan Perkhidmatan Madani. Use this recorded Teams meeting recap and reconcile it with the Stakeholder Engagement Log and KPI Scorecard sheets in GOV_01_Programme_Performance.xlsx. Separate decisions already taken, decisions that are still open, and assumptions that need independent validation before management can communicate externally. Present the result as a RAG decisions table with Decision, Current Status, Dependency, and Recommended Next Step.'
      ], DESC_TEAMS),
      tool(T_NOTEBOOK, M365_LIC, M365_ACCT, [
        "You are the Programme Director at Agensi Pemodenan Perkhidmatan Madani. Upload GOV_01_Programme_Performance.xlsx, GOV_02_Programme_Governance_Manual.docx, and GOV_03_Public_Service_Policy.docx to Copilot Notebook. Set the notebook instruction to: 'Synthesize evidence across all files, cite the exact file and sheet name for every major claim, and focus on programme recovery and service delivery reform.' Ask for a RAG executive synthesis with the current position, the root causes, the key dependencies, and the next three decisions management should take.",
        'You are the Head of Policy Delivery at Agensi Pemodenan Perkhidmatan Madani. Upload GOV_01_Programme_Performance.xlsx, GOV_02_Programme_Governance_Manual.docx, and GOV_03_Public_Service_Policy.docx to Copilot Notebook. Ask Notebook to reconcile what the workbook signals in the KPI Scorecard, Audit Findings Tracker, and Procurement Dashboard sheets with the operating expectations in GOV_02_Programme_Governance_Manual.docx and GOV_03_Public_Service_Policy.docx. Request a RAG table that shows where the documents and the live metrics align, conflict, or leave unanswered questions.',
        'You are the Chief Digital Officer at Agensi Pemodenan Perkhidmatan Madani. Upload GOV_01_Programme_Performance.xlsx, GOV_02_Programme_Governance_Manual.docx, and GOV_03_Public_Service_Policy.docx to Copilot Notebook. Ask Notebook for a 30-60-90 day plan that balances quick wins with durable control fixes for programme delivery, audit closure, and public-service reform, and make it explicit which actions depend on programme sponsors and implementing agencies or regulator feedback. Request the answer as a RAG roadmap with citations to the exact source file and sheet name for every recommendation.'
      ], DESC_NOTEBOOK),
      tool(T_COWORK, M365_LIC, M365_ACCT, [
        'You are the Programme Director at Agensi Pemodenan Perkhidmatan Madani. Research external benchmarks relevant to programme delivery, audit closure, and public-service reform, then draft a 2-page brief grounded in GOV_02_Programme_Governance_Manual.docx and the KPI Scorecard and Procurement Dashboard sheets in GOV_01_Programme_Performance.xlsx. Save the brief to OneDrive, email it to the leadership sponsors, and schedule a 30-minute review meeting with the owners who need to move programme recovery and service delivery reform this week. Make the brief a RAG action pack with a one-line decision ask on the first page.',
        'You are the Head of Policy Delivery at Agensi Pemodenan Perkhidmatan Madani. Create a shared execution tracker from the Budget Utilisation, Audit Findings Tracker, and Procurement Dashboard sheets in GOV_01_Programme_Performance.xlsx and the responsibilities described in GOV_03_Public_Service_Policy.docx. Email the tracker to programme and procurement leads, ask each owner to confirm status by end of day, and schedule a recurring weekly checkpoint until the Red items are reduced. Make the tracker RAG-driven so overdue Red items are easy to escalate.'
      ], DESC_COWORK),
      tool(T_EDIT_COPILOT, M365_LIC, M365_ACCT, [
        "You are the Programme Director at Agensi Pemodenan Perkhidmatan Madani. Using GOV_02_Programme_Governance_Manual.docx in Word for the web, add a new section called 'Executive Recovery Controls' that aligns with the risks visible in the KPI Scorecard and Procurement Dashboard sheets in GOV_01_Programme_Performance.xlsx. Restructure the document so the most urgent controls appear first, tighten repetitive language, and add a RAG summary table for leadership at the top. Keep the tone consistent with the existing document and make every new control action specific enough to assign an owner.",
        "You are the Head of Policy Delivery at Agensi Pemodenan Perkhidmatan Madani. Using GOV_01_Programme_Performance.xlsx in Excel for the web, create or refine a sheet called 'Leadership Tracker' using the Budget Utilisation, Audit Findings Tracker, and Procurement Dashboard sheets as source data. Reorder the columns so Red items appear first, standardise the formulas, and add a compact RAG summary block that updates automatically. Make the finished layout readable enough to paste into a leadership pack without manual cleanup."
      ], DESC_EDIT_COPILOT),
      tool(T_WORD_AGT, M365_LIC, M365_ACCT, [
        "You are the Programme Director at Agensi Pemodenan Perkhidmatan Madani. In Word for the web, use GOV_02_Programme_Governance_Manual.docx to create a new agent called 'Programme Governance Guide'. Describe it as an assistant that answers questions on programme delivery, audit closure, and public-service reform, the control expectations in the document, and the decisions leaders need for programme recovery and service delivery reform. Share it with programme and procurement leads and make sure the welcome message explains the RAG logic it uses for prioritisation.",
        "You are the Head of Policy Delivery at Agensi Pemodenan Perkhidmatan Madani. Demo the 'Programme Governance Guide' agent with a question that references GOV_02_Programme_Governance_Manual.docx and the KPI Scorecard and Procurement Dashboard sheets in GOV_01_Programme_Performance.xlsx. Ask the agent to explain the top Red issue, the control the document expects, and the owner who should respond first. Show the response as a concise RAG answer with a source citation."
      ], DESC_WORD_AGT),
      tool(T_PPT_AGT, M365_LIC, M365_ACCT, [
        "You are the Programme Director at Agensi Pemodenan Perkhidmatan Madani. Create a PowerPoint briefing from GOV_01_Programme_Performance.xlsx, GOV_02_Programme_Governance_Manual.docx, and GOV_03_Public_Service_Policy.docx, then create a new agent called 'Programme Review Deck Guide'. Describe it as a deck navigator that helps leaders answer questions about programme delivery, audit closure, and public-service reform, the major Red items, and the decisions required this month. Share it with the sponsor ministry, programme directors, and public service leadership and configure the opening prompt to point users to the highest-risk slide first.",
        "You are the Chief Digital Officer at Agensi Pemodenan Perkhidmatan Madani. Demo the 'Programme Review Deck Guide' agent by asking which slide best explains the current Red items from the KPI Scorecard, Stakeholder Engagement Log, and Procurement Dashboard sheets in GOV_01_Programme_Performance.xlsx. Then ask for a 60-second RAG summary of the story the presenter should tell to programme sponsors and implementing agencies. Require the answer to cite the slide topic it is drawing from."
      ], DESC_PPT_AGT),
      tool(T_XL_AGT, M365_LIC, M365_ACCT, [
        "You are the Programme Director at Agensi Pemodenan Perkhidmatan Madani. In Excel for the web, use GOV_01_Programme_Performance.xlsx to create a new agent called 'Programme Performance Q&A'. Describe it as an assistant that answers questions on the KPI Scorecard, Budget Utilisation, Stakeholder Engagement Log, Audit Findings Tracker, and Procurement Dashboard sheets and translates workbook signals into RAG-ready management insight for programme recovery and service delivery reform. Share it with programme and procurement leads and set the starter prompt to surface the top Red metrics automatically.",
        "You are the Head of Policy Delivery at Agensi Pemodenan Perkhidmatan Madani. Demo the 'Programme Performance Q&A' agent by asking which indicators in the KPI Scorecard, Audit Findings Tracker, and Procurement Dashboard sheets are currently Red and what action would most likely move each one to Amber. Then ask for the single metric management should watch weekly if it can only track one item. Require the reply to be a RAG summary that names the exact sheet for every answer."
      ], DESC_XL_AGT),
      tool(T_BUILDER, M365_LIC, M365_ACCT, [
        "You are the Programme Director at Agensi Pemodenan Perkhidmatan Madani. Go to Copilot Studio and create a new agent called 'Madani Delivery Copilot' using GOV_01_Programme_Performance.xlsx, GOV_02_Programme_Governance_Manual.docx, and GOV_03_Public_Service_Policy.docx as knowledge sources. Describe it as an assistant for the sponsor ministry, programme directors, and public service leadership that supports programme recovery and service delivery reform, add the topics KPI Delivery, Budget Use, Audit Closure, and Procurement Discipline, and publish it to Teams for the right audience. Make the starter prompts explicitly return Red, Amber, or Green recommendations when users ask for priorities.",
        "You are the Chief Digital Officer at Agensi Pemodenan Perkhidmatan Madani. Demo the 'Madani Delivery Copilot' agent with a question that combines the KPI Scorecard, Stakeholder Engagement Log, and Procurement Dashboard sheets in GOV_01_Programme_Performance.xlsx with the policy direction in GOV_02_Programme_Governance_Manual.docx. Ask for the top Red issue, the fastest Amber recovery action, and the Green area management should preserve while programme recovery and service delivery reform is under way. Require the answer to cite the file evidence it used for each RAG judgement."
      ], DESC_BUILDER),
    ],
    companyID='Badan Layanan Publik Nusantara',
    taglineID='Serapan anggaran lambat dan temuan audit terbuka menunda program prioritas.'),
]

print(f"Batch 6 written: {len(INDUSTRIES_6)} entries")
