# -*- coding: utf-8 -*-
"""
What's New banner content with full BM (Bahasa Malaysia) and BI (Bahasa Indonesia) translations.
Each entry has: title/titleBM/titleID, badge/badgeBM/badgeID, summary/summaryBM/summaryID, tip/tipBM/tipID, license, link.
Updated for June 2, 2026 Microsoft 365 Copilot release notes.
"""

WHATS_NEW = [
    # ─────────────────────────────────────────────────────────────────────
    # June 2, 2026 release-notes additions (newest first so they show first)
    # ─────────────────────────────────────────────────────────────────────
    {
        "id": "wn-copilot-redesign",
        "title": "✨ Redesigned Copilot — task-aware workspace (NEW)",
        "titleBM": "✨ Reka Bentuk Baharu Copilot — ruang kerja peka tugas (BAHARU)",
        "titleID": "✨ Desain Baru Copilot — ruang kerja sadar tugas (BARU)",
        "badge": "App-wide refresh (May 28, 2026)",
        "badgeBM": "Naik taraf seluruh aplikasi (28 Mei 2026)",
        "badgeID": "Pembaruan seluruh aplikasi (28 Mei 2026)",
        "summary": "Microsoft 365 Copilot has a cleaner, faster, more task-aware design. The prompt line is now a workspace: context-sensitive controls, history, and agent management live next to your prompt. Copilot proactively suggests relevant actions across apps so you switch tasks without copy-paste.",
        "summaryBM": "Microsoft 365 Copilot kini lebih kemas, pantas dan peka tugas. Baris arahan kini menjadi ruang kerja: kawalan kontekstual, sejarah dan pengurusan ejen berada bersebelahan arahan anda. Copilot secara proaktif mencadangkan tindakan berkaitan merentas aplikasi supaya anda boleh bertukar tugas tanpa salin-tampal.",
        "summaryID": "Microsoft 365 Copilot kini punya desain yang lebih bersih, cepat dan sadar konteks tugas. Baris prompt kini menjadi ruang kerja: kontrol kontekstual, riwayat dan manajemen agen ada di sebelah prompt Anda. Copilot secara proaktif menyarankan tindakan relevan di seluruh aplikasi sehingga Anda berpindah tugas tanpa salin-tempel.",
        "tip": "Open m365.cloud.microsoft/chat — notice the new prompt-line workspace, the agent picker, and the proactive action suggestions that follow you across Word/Excel/PPT/Outlook.",
        "tipBM": "Buka m365.cloud.microsoft/chat — perhatikan ruang kerja baris arahan baharu, pemilih ejen, dan cadangan tindakan proaktif yang mengikut anda merentas Word/Excel/PPT/Outlook.",
        "tipID": "Buka m365.cloud.microsoft/chat — perhatikan ruang kerja baris prompt yang baru, pemilih agen, dan saran tindakan proaktif yang mengikuti Anda di Word/Excel/PPT/Outlook.",
        "license": "Microsoft 365 Copilot",
        "link": "https://www.microsoft.com/en-us/microsoft-365/blog/2026/05/28/introducing-a-new-design-for-microsoft-365-copilot/"
    },
    {
        "id": "wn-word-default-edit",
        "title": "📝 Word — Copilot edits your document by default (NEW)",
        "titleBM": "📝 Word — Copilot menyunting dokumen anda secara lalai (BAHARU)",
        "titleID": "📝 Word — Copilot mengedit dokumen Anda secara default (BARU)",
        "badge": "GA — June 2, 2026",
        "badgeBM": "Tersedia umum — 2 Jun 2026",
        "badgeID": "GA — 2 Juni 2026",
        "summary": "The default Copilot chat experience in Word now applies edits directly to the document instead of returning suggestions for copy-paste. All changes are tracked and fully reversible, and you can turn the behaviour off in settings. Roadmap ID 557673.",
        "summaryBM": "Pengalaman sembang Copilot lalai dalam Word kini menggunakan suntingan terus pada dokumen, bukan sekadar mengembalikan cadangan untuk salin-tampal. Semua perubahan dijejak dan boleh diundur sepenuhnya, dan anda boleh matikan kelakuan ini dalam tetapan. ID Hala Tuju 557673.",
        "summaryID": "Pengalaman chat Copilot default di Word kini langsung menerapkan perubahan ke dokumen alih-alih hanya memberikan saran untuk disalin-tempel. Semua perubahan dilacak dan dapat dikembalikan sepenuhnya, dan Anda dapat menonaktifkan perilaku ini di pengaturan. ID Roadmap 557673.",
        "tip": "Open Word for the Web > Copilot pane > ask 'Rewrite this section in board-paper tone'. The edits land directly in the document with track changes — review and accept/reject as usual.",
        "tipBM": "Buka Word untuk Web > anak tetingkap Copilot > tanya 'Tulis semula bahagian ini dalam nada kertas lembaga'. Suntingan akan terus muncul dalam dokumen dengan perubahan terjejak — semak dan terima/tolak seperti biasa.",
        "tipID": "Buka Word for the Web > panel Copilot > minta 'Tulis ulang bagian ini dengan nada makalah dewan direksi'. Perubahan langsung muncul di dokumen dengan track changes — tinjau dan terima/tolak seperti biasa.",
        "license": "Microsoft 365 Copilot",
        "link": "https://learn.microsoft.com/en-us/microsoft-365/copilot/release-notes"
    },
    {
        "id": "wn-studio-grader",
        "title": "🎓 Copilot Studio — Grader Framework for agent evaluation (NEW)",
        "titleBM": "🎓 Copilot Studio — Rangka Kerja Penggred untuk penilaian ejen (BAHARU)",
        "titleID": "🎓 Copilot Studio — Kerangka Penilai untuk evaluasi agen (BARU)",
        "badge": "GA — June 2, 2026",
        "badgeBM": "Tersedia umum — 2 Jun 2026",
        "badgeID": "GA — 2 Juni 2026",
        "summary": "Test cases now support Expected Responses with multiple grading methods: Exact match, Partial match, Similarity scoring, Compare Meaning (AI-based), and Intent grading. Import test sets from file, run evaluations across grading methods, and review per-case results to identify where the agent regressed.",
        "summaryBM": "Kes ujian kini menyokong Jawapan Dijangka dengan pelbagai kaedah penggredan: padanan Tepat, padanan Separa, pemarkahan Persamaan, Bandingkan Makna (berasaskan AI), dan penggredan Niat. Import set ujian dari fail, jalankan penilaian merentas kaedah penggredan, dan semak keputusan setiap kes untuk mengenal pasti regresi ejen.",
        "summaryID": "Kasus uji kini mendukung Respons yang Diharapkan dengan beberapa metode penilaian: kecocokan Persis, kecocokan Sebagian, penilaian Kemiripan, Bandingkan Makna (berbasis AI), dan penilaian Niat. Impor set uji dari file, jalankan evaluasi di berbagai metode penilaian, dan tinjau hasil per-kasus untuk mengidentifikasi regresi agen.",
        "tip": "In Copilot Studio > your agent > Analytics > Evaluation > New test set. Add 20 representative prompts with expected responses, then re-run after every prompt-engineering change to catch regressions before publishing.",
        "tipBM": "Dalam Copilot Studio > ejen anda > Analitis > Penilaian > Set ujian baharu. Tambah 20 arahan wakil dengan jawapan dijangka, kemudian jalankan semula selepas setiap perubahan kejuruteraan arahan untuk mengesan regresi sebelum diterbitkan.",
        "tipID": "Di Copilot Studio > agen Anda > Analytics > Evaluation > New test set. Tambahkan 20 prompt representatif dengan respons yang diharapkan, lalu jalankan ulang setelah setiap perubahan rekayasa prompt untuk menangkap regresi sebelum publikasi.",
        "license": "Microsoft 365 Copilot Studio",
        "link": "https://learn.microsoft.com/en-us/microsoft-copilot-studio/analytics-agent-evaluation-create"
    },
    {
        "id": "wn-org-messages",
        "title": "📣 Organizational Messages — usage-based targeting + email (NEW)",
        "titleBM": "📣 Mesej Organisasi — sasaran ikut penggunaan + e-mel (BAHARU)",
        "titleID": "📣 Pesan Organisasi — penargetan berbasis penggunaan + email (BARU)",
        "badge": "GA — June 2, 2026 (admin)",
        "badgeBM": "Tersedia umum — 2 Jun 2026 (pentadbir)",
        "badgeID": "GA — 2 Juni 2026 (admin)",
        "summary": "Microsoft 365 admin center can now send Organizational Messages based on real Copilot usage (e.g. Inactive Copilot Users for past 28 days) instead of static groups, AND deliver via email alongside Taskbar / Spotlight / Teams Popovers. 9 premade templates in 15 languages plus a new Email insights tab.",
        "summaryBM": "Pusat pentadbir Microsoft 365 kini boleh menghantar Mesej Organisasi berdasarkan penggunaan Copilot sebenar (cth. Pengguna Copilot Tidak Aktif 28 hari lalu) bukan kumpulan statik, DAN menyampaikan melalui e-mel di samping Bar Tugas / Spotlight / Pop-up Teams. 9 templat siap-pakai dalam 15 bahasa serta tab pandangan E-mel baharu.",
        "summaryID": "Pusat admin Microsoft 365 kini dapat mengirim Pesan Organisasi berdasarkan penggunaan Copilot yang nyata (mis. Pengguna Copilot Tidak Aktif selama 28 hari terakhir) alih-alih grup statis, SERTA mengirim via email selain Taskbar / Spotlight / Popover Teams. 9 templat siap-pakai dalam 15 bahasa plus tab insight Email yang baru.",
        "tip": "Microsoft 365 admin center > Organizational Messages > New > pick the 'Inactive Copilot Users (28d)' segment > select Email channel > use the 'Welcome to M365 Copilot' template. Track open rate in the new Email insights tab.",
        "tipBM": "Pusat pentadbir Microsoft 365 > Mesej Organisasi > Baharu > pilih segmen 'Pengguna Copilot Tidak Aktif (28h)' > pilih saluran E-mel > guna templat 'Welcome to M365 Copilot'. Jejak kadar buka dalam tab pandangan E-mel baharu.",
        "tipID": "Microsoft 365 admin center > Organizational Messages > New > pilih segmen 'Inactive Copilot Users (28d)' > pilih kanal Email > gunakan template 'Welcome to M365 Copilot'. Lacak open rate di tab insight Email yang baru.",
        "license": "Microsoft 365 Copilot (admin)",
        "link": "https://learn.microsoft.com/en-us/microsoft-365/admin/misc/organizational-messages-microsoft-365"
    },
    # ─────────────────────────────────────────────────────────────────────
    # Existing entries (May 2026 and earlier) — translated
    # ─────────────────────────────────────────────────────────────────────
    {
        "id": "wn-researcher",
        "title": "🔍 Researcher — Critique + Model Council",
        "titleBM": "🔍 Researcher — Kritik + Majlis Model",
        "titleID": "🔍 Researcher — Kritik + Dewan Model",
        "badge": "New rollout (May 2026)",
        "badgeBM": "Pelancaran baharu (Mei 2026)",
        "badgeID": "Peluncuran baru (Mei 2026)",
        "summary": "Two demo modes inside Researcher: (1) Critique Mode self-critiques every source and flags claims it cannot verify; (2) Model Council convenes GPT and Claude — each return a full independent report, then a synthesis cover letter highlights where they agree, where they differ, and any unique findings.",
        "summaryBM": "Dua mod demo di dalam Researcher: (1) Mod Kritik mengkritik setiap sumber dan menandakan dakwaan yang tidak dapat disahkan; (2) Majlis Model menghimpunkan GPT dan Claude — setiap satu memulangkan laporan bebas yang lengkap, kemudian surat iringan sintesis menonjolkan di mana mereka bersetuju, di mana mereka berbeza, dan sebarang penemuan unik.",
        "summaryID": "Dua mode demo di dalam Researcher: (1) Mode Kritik mengkritik setiap sumber dan menandai klaim yang tidak dapat diverifikasi; (2) Dewan Model menghimpun GPT dan Claude — masing-masing mengembalikan laporan independen lengkap, lalu surat pengantar sintesis menyorot di mana mereka sepakat, di mana mereka berbeda, dan temuan unik apa pun.",
        "tip": "m365.cloud.microsoft/chat > Agents > Researcher > switch the mode pill at the top to 'Critique' or 'Model Council'.",
        "tipBM": "m365.cloud.microsoft/chat > Ejen > Researcher > tukar pil mod di bahagian atas kepada 'Kritik' atau 'Majlis Model'.",
        "tipID": "m365.cloud.microsoft/chat > Agen > Researcher > ganti pil mode di bagian atas menjadi 'Kritik' atau 'Dewan Model'.",
        "license": "Microsoft 365 Copilot",
        "link": "https://techcommunity.microsoft.com/blog/microsoft365copilotblog/introducing-multi-model-intelligence-in-researcher/4506011"
    },
    {
        "id": "wn-cowork",
        "title": "🤝 Cowork Frontier — refreshed (May 2026)",
        "titleBM": "🤝 Cowork Frontier — dinaik taraf (Mei 2026)",
        "titleID": "🤝 Cowork Frontier — diperbarui (Mei 2026)",
        "badge": "Frontier Program",
        "badgeBM": "Program Frontier",
        "badgeID": "Program Frontier",
        "summary": "Cowork is now an autonomous agent that you describe in plain language (16,000 chars + voice input). It runs end-to-end and shows every step. NEW: ⏰ run prompts on a schedule for recurring tasks; 🔍 search across the org for files/people/info; 🔬 deep research across multiple sources; 📊 daily briefings + meeting intelligence summaries; 📁 browse & manage OneDrive + SharePoint inline; ⏯️ Pause/Resume/Cancel any time; ✅ Approve / Approve & Remember / Reject for medium and high risk actions. Side panel shows Progress / Input folder / Output folder / Skills / Schedule / Permissions.",
        "summaryBM": "Cowork kini ejen autonomi yang anda terangkan dalam bahasa biasa (16,000 aksara + input suara). Ia berjalan dari hujung ke hujung dan menunjukkan setiap langkah. BAHARU: ⏰ jalankan arahan mengikut jadual untuk tugas berulang; 🔍 cari merentas organisasi untuk fail/orang/maklumat; 🔬 penyelidikan mendalam merentas pelbagai sumber; 📊 taklimat harian + ringkasan kepintaran mesyuarat; 📁 layari & uruskan OneDrive + SharePoint dalam talian; ⏯️ Jeda/Sambung/Batal pada bila-bila masa; ✅ Lulus / Lulus & Ingat / Tolak untuk tindakan berisiko sederhana dan tinggi. Panel sisi memaparkan Kemajuan / Folder Input / Folder Output / Kemahiran / Jadual / Kebenaran.",
        "summaryID": "Cowork kini menjadi agen otonom yang Anda jelaskan dalam bahasa biasa (16.000 karakter + input suara). Berjalan end-to-end dan menampilkan setiap langkah. BARU: ⏰ jalankan prompt sesuai jadwal untuk tugas berulang; 🔍 cari di seluruh organisasi untuk file/orang/info; 🔬 riset mendalam di banyak sumber; 📊 briefing harian + ringkasan intelijen rapat; 📁 jelajahi & kelola OneDrive + SharePoint inline; ⏯️ Jeda/Lanjutkan/Batalkan kapan saja; ✅ Setujui / Setujui & Ingat / Tolak untuk tindakan berisiko sedang dan tinggi. Panel samping menampilkan Progres / Folder Input / Folder Output / Skill / Jadwal / Izin.",
        "tip": "m365.cloud.microsoft > left nav > Agents > Cowork (Frontier). Try: hold the mic icon, dictate \"prep me for tomorrow's board meeting\", then schedule it to repeat every Monday at 6am.",
        "tipBM": "m365.cloud.microsoft > navigasi kiri > Ejen > Cowork (Frontier). Cuba: tahan ikon mikrofon, sebut \"sediakan saya untuk mesyuarat lembaga esok\", kemudian jadualkan ia berulang setiap Isnin jam 6 pagi.",
        "tipID": "m365.cloud.microsoft > nav kiri > Agen > Cowork (Frontier). Coba: tahan ikon mikrofon, diktekan \"siapkan saya untuk rapat dewan besok\", lalu jadwalkan agar berulang setiap Senin pukul 6 pagi.",
        "license": "Microsoft 365 Copilot + Frontier Program",
        "link": "https://support.microsoft.com/en-us/microsoft-365-copilot/get-started-with-cowork-frontier"
    },
    {
        "id": "wn-scout",
        "title": "🧭 Microsoft Scout — desktop AI app (NEW)",
        "titleBM": "🧭 Microsoft Scout — aplikasi AI desktop (BAHARU)",
        "titleID": "🧭 Microsoft Scout — aplikasi AI desktop (BARU)",
        "badge": "Frontier preview (June 2026)",
        "badgeBM": "Pratonton Frontier (Jun 2026)",
        "badgeID": "Pratinjau Frontier (Juni 2026)",
        "summary": "A separate desktop AI application that goes beyond Copilot Chat. Scout has direct access to your local file system, can run shell commands with permission tiers, controls a real browser via Playwright, and reaches into your M365 data. Capabilities: 📁 file system + Word/Excel/PowerPoint skills; 🖥️ shell commands (build/test/git) with sensitive-path guards; 🌐 browser automation for portal tasks; 📧 M365 access via WorkIQ; 🤖 sub-agents (Explore/Task/Code review/Research/General-purpose); ❤️ Heartbeat mode (recurring background prompt every 15min/30min/1h/2h, work hours only); 🔄 Automations (schedule- or condition-triggered); 🔐 granular Permissions UI.",
        "summaryBM": "Aplikasi AI desktop berasingan yang melangkaui Copilot Chat. Scout mempunyai akses terus ke sistem fail tempatan, boleh menjalankan arahan shell dengan peringkat kebenaran, mengawal pelayar sebenar melalui Playwright, dan mencapai data M365 anda. Keupayaan: 📁 sistem fail + kemahiran Word/Excel/PowerPoint; 🖥️ arahan shell (build/test/git) dengan kawalan laluan sensitif; 🌐 automasi pelayar untuk tugas portal; 📧 akses M365 melalui WorkIQ; 🤖 sub-ejen (Explore/Task/Semakan kod/Penyelidikan/Tujuan umum); ❤️ Mod Heartbeat (arahan latar belakang berulang setiap 15min/30min/1j/2j, waktu kerja sahaja); 🔄 Automasi (dicetus oleh jadual atau syarat); 🔐 UI Kebenaran terperinci.",
        "summaryID": "Aplikasi AI desktop terpisah yang melampaui Copilot Chat. Scout punya akses langsung ke sistem berkas lokal Anda, dapat menjalankan perintah shell dengan tingkatan izin, mengontrol peramban sungguhan via Playwright, dan menjangkau data M365 Anda. Kemampuan: 📁 sistem berkas + skill Word/Excel/PowerPoint; 🖥️ perintah shell (build/test/git) dengan penjaga jalur sensitif; 🌐 otomasi peramban untuk tugas portal; 📧 akses M365 via WorkIQ; 🤖 sub-agen (Explore/Task/Tinjauan kode/Riset/Serbaguna); ❤️ Mode Heartbeat (prompt latar berulang setiap 15min/30min/1j/2j, jam kerja saja); 🔄 Otomasi (dipicu jadwal atau kondisi); 🔐 UI Izin terperinci.",
        "tip": "Install the Scout desktop app, enrol in Frontier, then try Heartbeat: every 30 min during work hours, sweep email + Teams + OneDrive for new high-risk items and post to a private channel.",
        "tipBM": "Pasang aplikasi desktop Scout, daftar dalam Frontier, kemudian cuba Heartbeat: setiap 30 minit pada waktu kerja, sapu e-mel + Teams + OneDrive untuk perkara berisiko tinggi baharu dan siarkan ke saluran peribadi.",
        "tipID": "Instal aplikasi desktop Scout, daftar di Frontier, lalu coba Heartbeat: setiap 30 menit pada jam kerja, sapu email + Teams + OneDrive untuk item berisiko tinggi yang baru dan posting ke kanal pribadi.",
        "license": "Microsoft 365 Copilot + Frontier Program",
        "link": "https://learn.microsoft.com/en-us/microsoft-scout/use-microsoft-scout"
    },
    {
        "id": "wn-sharepoint-ai",
        "title": "🌐 AI in SharePoint — Floating Button (NEW)",
        "titleBM": "🌐 AI dalam SharePoint — Butang Terapung (BAHARU)",
        "titleID": "🌐 AI di SharePoint — Tombol Mengambang (BARU)",
        "badge": "Public Preview (April 2026)",
        "badgeBM": "Pratonton Awam (April 2026)",
        "badgeID": "Pratinjau Publik (April 2026)",
        "summary": "Microsoft 365 Copilot capabilities now live inside SharePoint pages, libraries, and sites. The Floating Button (bottom-right) surfaces context-sensitive actions based on your role + page + selection. Capabilities: 📄 Work with files — Ask, Summarize, Compare files, Audio Overview, Generate FAQ; 🗂️ Organize libraries — Autofill columns, Automate workflows / set up rules, Create views; 🎨 Pages and sites — Improve your SharePoint site (broken links / outdated pages / content gaps), Create Page / Section / FAQ Webpart, Refine pages with Design Ideas, Write/Rewrite. Roles: Site Manager / Content Manager / Content Creator / Content Consumer.",
        "summaryBM": "Keupayaan Microsoft 365 Copilot kini hidup di dalam halaman, perpustakaan dan tapak SharePoint. Butang Terapung (kanan bawah) memunculkan tindakan kontekstual berdasarkan peranan + halaman + pemilihan anda. Keupayaan: 📄 Bekerja dengan fail — Tanya, Ringkaskan, Banding fail, Gambaran Audio, Jana Soalan Lazim; 🗂️ Susun perpustakaan — Auto-isi lajur, Automasi aliran kerja / tetapkan peraturan, Cipta paparan; 🎨 Halaman dan tapak — Tambah baik tapak SharePoint anda (pautan rosak / halaman lapuk / jurang kandungan), Cipta Halaman / Bahagian / Webpart Soalan Lazim, Halusi halaman dengan Idea Reka Bentuk, Tulis/Tulis semula. Peranan: Pengurus Tapak / Pengurus Kandungan / Pencipta Kandungan / Pengguna Kandungan.",
        "summaryID": "Kemampuan Microsoft 365 Copilot kini hadir di dalam halaman, pustaka, dan situs SharePoint. Tombol Mengambang (kanan bawah) memunculkan tindakan kontekstual berdasarkan peran + halaman + seleksi Anda. Kemampuan: 📄 Bekerja dengan berkas — Tanya, Ringkas, Bandingkan berkas, Ikhtisar Audio, Buat FAQ; 🗂️ Atur pustaka — Isi-otomatis kolom, Otomasi alur kerja / siapkan aturan, Buat tampilan; 🎨 Halaman dan situs — Tingkatkan situs SharePoint Anda (tautan rusak / halaman usang / kesenjangan konten), Buat Halaman / Bagian / FAQ Webpart, Sempurnakan halaman dengan Ide Desain, Tulis/Tulis ulang. Peran: Manajer Situs / Manajer Konten / Kreator Konten / Konsumen Konten.",
        "tip": "Open any SharePoint document library, select 2 files, click the Floating Button > Compare files. Or open a long PDF and try Generate Audio Overview.",
        "tipBM": "Buka mana-mana perpustakaan dokumen SharePoint, pilih 2 fail, klik Butang Terapung > Banding fail. Atau buka PDF panjang dan cuba Jana Gambaran Audio.",
        "tipID": "Buka pustaka dokumen SharePoint mana saja, pilih 2 berkas, klik Tombol Mengambang > Bandingkan berkas. Atau buka PDF panjang dan coba Buat Ikhtisar Audio.",
        "license": "Microsoft 365 Copilot",
        "link": "https://support.microsoft.com/en-us/topic/ai-in-sharepoint-an-overview-c0b1efc3-81d0-4981-8be9-7ba3a75fae15"
    },
    {
        "id": "wn-doc-agents",
        "title": "📝🎯📊 Word / PPT / Excel Agents — dual tier",
        "titleBM": "📝🎯📊 Ejen Word / PPT / Excel — dwi-peringkat",
        "titleID": "📝🎯📊 Agen Word / PPT / Excel — dua tingkat",
        "badge": "Free Chat tier + Microsoft 365 Copilot",
        "badgeBM": "Peringkat Chat percuma + Microsoft 365 Copilot",
        "badgeID": "Tingkat Chat gratis + Microsoft 365 Copilot",
        "summary": "Type ONE prompt in m365.cloud.microsoft/chat and Copilot returns a fully drafted .docx / .pptx / .xlsx without you opening Word/PPT/Excel first. Now available in BOTH the free Copilot Chat tier (Sasha account) and with a Microsoft 365 Copilot license (MOD Admin account).",
        "summaryBM": "Taip SATU arahan dalam m365.cloud.microsoft/chat dan Copilot pulangkan .docx / .pptx / .xlsx yang siap dirangka tanpa anda membuka Word/PPT/Excel dahulu. Kini tersedia dalam KEDUA-DUA peringkat Copilot Chat percuma (akaun Sasha) dan dengan lesen Microsoft 365 Copilot (akaun MOD Admin).",
        "summaryID": "Ketik SATU prompt di m365.cloud.microsoft/chat dan Copilot mengembalikan .docx / .pptx / .xlsx yang sudah disusun penuh tanpa Anda membuka Word/PPT/Excel dulu. Kini tersedia di KEDUA tingkat Copilot Chat gratis (akun Sasha) dan dengan lisensi Microsoft 365 Copilot (akun MOD Admin).",
        "tip": "Try in the free tier: 'Build a 5-slide investor narrative deck for the Zava FY2025 Q4 results...'",
        "tipBM": "Cuba dalam peringkat percuma: 'Bina dek naratif pelabur 5-slaid untuk keputusan Zava FY2025 S4...'",
        "tipID": "Coba di tingkat gratis: 'Buat deck naratif investor 5 slide untuk hasil Zava FY2025 Q4...'",
        "license": "Either Free Copilot Chat (no extra license) OR Microsoft 365 Copilot license",
        "link": "https://techcommunity.microsoft.com/blog/microsoft365copilotblog/copilot-in-word-new-capabilities-for-document-workflows/4508974"
    },
    {
        "id": "wn-builder",
        "title": "🏗 Agent Builder — dual tier",
        "titleBM": "🏗 Agent Builder — dwi-peringkat",
        "titleID": "🏗 Agent Builder — dua tingkat",
        "badge": "Free Chat tier + Microsoft 365 Copilot",
        "badgeBM": "Peringkat Chat percuma + Microsoft 365 Copilot",
        "badgeID": "Tingkat Chat gratis + Microsoft 365 Copilot",
        "summary": "Create custom agents inside Copilot Chat — NOT Copilot Studio. Describe → Configure (knowledge, instructions, starter prompts) → Test → Create + share. Now usable in both the free Copilot Chat tier and with a Microsoft 365 Copilot license.",
        "summaryBM": "Cipta ejen tersuai di dalam Copilot Chat — BUKAN Copilot Studio. Terangkan → Konfigurasi (pengetahuan, arahan, arahan permulaan) → Uji → Cipta + kongsi. Kini boleh digunakan dalam kedua-dua peringkat Copilot Chat percuma dan dengan lesen Microsoft 365 Copilot.",
        "summaryID": "Buat agen kustom di dalam Copilot Chat — BUKAN Copilot Studio. Jelaskan → Konfigurasi (pengetahuan, instruksi, prompt awal) → Uji → Buat + bagikan. Kini dapat digunakan di tingkat Copilot Chat gratis dan dengan lisensi Microsoft 365 Copilot.",
        "tip": "m365.cloud.microsoft/chat > Agents > + Create an agent. Try building a 'Group CFO Briefing Bot' grounded in your finance reference files.",
        "tipBM": "m365.cloud.microsoft/chat > Ejen > + Cipta ejen. Cuba bina 'Group CFO Briefing Bot' yang berasaskan fail rujukan kewangan anda.",
        "tipID": "m365.cloud.microsoft/chat > Agen > + Buat agen. Coba bangun 'Group CFO Briefing Bot' yang berlandaskan berkas referensi keuangan Anda.",
        "license": "Either Free Copilot Chat (no extra license) OR Microsoft 365 Copilot license",
        "link": "https://techcommunity.microsoft.com/blog/microsoft365copilotblog/whats-new-in-microsoft-365-copilot--april-2026/4510935"
    },
    {
        "id": "wn-notebook",
        "title": "📓 Copilot Notebook — 5 sources + Quick Create + Mind Maps (refreshed)",
        "titleBM": "📓 Copilot Notebook — 5 sumber + Quick Create + Peta Minda (dinaik taraf)",
        "titleID": "📓 Copilot Notebook — 5 sumber + Quick Create + Peta Pikiran (diperbarui)",
        "badge": "Generally Available + Frontier preview",
        "badgeBM": "Tersedia Umum + Pratonton Frontier",
        "badgeID": "Tersedia Umum + Pratinjau Frontier",
        "summary": "Add up to 5 source files (Word/Excel/PDF/PPT) AND now reference SharePoint sites, OneNote notebooks, and external web links as live sources. Set a persistent Instructions field once, run multiple prompts. Quick Create now produces: 📄 full Word documents, 📊 PowerPoint presentations, 🎧 Audio Overviews (podcast-style), and a custom Page. 🧠 Interactive Mind Maps (Frontier preview) let you click any node to drill into the underlying source. 👥 Share notebooks with a Microsoft 365 Group for team co-grounding.",
        "summaryBM": "Tambah sehingga 5 fail sumber (Word/Excel/PDF/PPT) DAN kini rujuk tapak SharePoint, buku nota OneNote, dan pautan web luaran sebagai sumber langsung. Tetapkan medan Arahan berterusan sekali, jalankan pelbagai arahan. Quick Create kini menghasilkan: 📄 dokumen Word penuh, 📊 pembentangan PowerPoint, 🎧 Gambaran Audio (gaya podcast), dan Halaman tersuai. 🧠 Peta Minda Interaktif (pratonton Frontier) membolehkan anda klik mana-mana nod untuk menyelami sumber asas. 👥 Kongsi buku nota dengan Kumpulan Microsoft 365 untuk landasan bersama pasukan.",
        "summaryID": "Tambahkan hingga 5 berkas sumber (Word/Excel/PDF/PPT) DAN kini referensikan situs SharePoint, buku catatan OneNote, dan tautan web eksternal sebagai sumber langsung. Tetapkan field Instructions persisten sekali, jalankan beberapa prompt. Quick Create kini menghasilkan: 📄 dokumen Word lengkap, 📊 presentasi PowerPoint, 🎧 Ikhtisar Audio (gaya podcast), dan Page kustom. 🧠 Peta Pikiran Interaktif (pratinjau Frontier) memungkinkan Anda klik node mana saja untuk mendalami sumber dasarnya. 👥 Bagikan buku catatan dengan Grup Microsoft 365 untuk landasan bersama tim.",
        "tip": "m365.cloud.microsoft/chat > Notebook > + New Notebook. After grounding 5 files, try Quick Create > Audio Overview for a 12-minute commute briefing, then click Mind Map and drill into the riskiest concept node.",
        "tipBM": "m365.cloud.microsoft/chat > Notebook > + Buku Nota Baharu. Selepas melandaskan 5 fail, cuba Quick Create > Gambaran Audio untuk taklimat ulang-alik 12 minit, kemudian klik Peta Minda dan selami nod konsep paling berisiko.",
        "tipID": "m365.cloud.microsoft/chat > Notebook > + Buku Catatan Baru. Setelah melandaskan 5 berkas, coba Quick Create > Ikhtisar Audio untuk briefing perjalanan 12 menit, lalu klik Peta Pikiran dan selami node konsep paling berisiko.",
        "license": "Microsoft 365 Copilot",
        "link": "https://techcommunity.microsoft.com/blog/microsoft365copilotblog/whats-new-in-microsoft-365-copilot--april-2026/4510935"
    },
    {
        "id": "wn-federated",
        "title": "🔌 Federated Copilot Connectors — now GA",
        "titleBM": "🔌 Penyambung Copilot Bersekutu — kini Tersedia Umum",
        "titleID": "🔌 Konektor Copilot Federasi — kini GA",
        "badge": "GA — June 2, 2026",
        "badgeBM": "Tersedia umum — 2 Jun 2026",
        "badgeID": "GA — 2 Juni 2026",
        "summary": "Federated Copilot Connectors are now generally available across Microsoft 365 Chat, Researcher, and Agent Mode in Excel — using Model Context Protocol (MCP) for real-time third-party data without ingestion or indexing. Admins discover, review, enable/disable from Microsoft Admin Center > Copilot > Connectors with a 7-day review window. Microsoft-published connectors include Moody's, HubSpot, LSEG, Notion, ServiceNow.",
        "summaryBM": "Penyambung Copilot Bersekutu kini Tersedia Umum di seluruh Microsoft 365 Chat, Researcher, dan Mod Ejen dalam Excel — menggunakan Model Context Protocol (MCP) untuk data pihak ketiga masa-nyata tanpa pengingesan atau pengindeksan. Pentadbir menemui, menyemak, mengaktif/menyahaktif dari Pusat Pentadbir Microsoft > Copilot > Penyambung dengan tempoh semakan 7-hari. Penyambung terbitan Microsoft termasuk Moody's, HubSpot, LSEG, Notion, ServiceNow.",
        "summaryID": "Konektor Copilot Federasi kini GA di seluruh Microsoft 365 Chat, Researcher, dan Agent Mode di Excel — menggunakan Model Context Protocol (MCP) untuk data pihak ketiga real-time tanpa ingesti atau pengindeksan. Admin menemukan, meninjau, mengaktifkan/menonaktifkan dari Microsoft Admin Center > Copilot > Connectors dengan jendela tinjauan 7 hari. Konektor terbitan Microsoft mencakup Moody's, HubSpot, LSEG, Notion, ServiceNow.",
        "tip": "Try in Researcher: 'Pull LSEG 5-year CDS spreads for Zava Group's top-3 lender peers and Moody's latest rating action notes.'",
        "tipBM": "Cuba dalam Researcher: 'Tarik spread CDS 5-tahun LSEG untuk 3 pesaing pemberi pinjaman teratas Zava Group dan nota tindakan penarafan terkini Moody's.'",
        "tipID": "Coba di Researcher: 'Tarik spread CDS 5-tahun LSEG untuk 3 peer pemberi pinjaman teratas Zava Group dan catatan aksi pemeringkatan terbaru Moody's.'",
        "license": "Microsoft 365 Copilot",
        "link": "https://techcommunity.microsoft.com/blog/microsoft365copilotblog/federated-copilot-connectors---bringing-real-time-enterprise-data-within-microso/4515993"
    },
    {
        "id": "wn-word-legal",
        "title": "⚖️ Word Legal Agent (Frontier)",
        "titleBM": "⚖️ Ejen Undang-undang Word (Frontier)",
        "titleID": "⚖️ Agen Hukum Word (Frontier)",
        "badge": "Frontier Program",
        "badgeBM": "Program Frontier",
        "badgeID": "Program Frontier",
        "summary": "Specialised Word agent for contract / litigation / compliance work — redlines clauses against a playbook, highlights deviations from precedent, and proposes alternate language grounded in the firm's contract corpus.",
        "summaryBM": "Ejen Word khusus untuk kerja kontrak / litigasi / pematuhan — meredline klausa berdasarkan playbook, menonjolkan penyimpangan daripada preseden, dan mencadangkan bahasa alternatif berasaskan korpus kontrak firma.",
        "summaryID": "Agen Word khusus untuk pekerjaan kontrak / litigasi / kepatuhan — redline klausul terhadap playbook, menyorot penyimpangan dari preseden, dan mengusulkan bahasa alternatif berlandaskan korpus kontrak firma.",
        "tip": "Open a contract .docx in Word for the Web > Copilot pane > switch to 'Legal Agent'. Ask: 'Redline this MSA against our Tier-1 vendor playbook and flag any indemnity carve-outs.'",
        "tipBM": "Buka kontrak .docx dalam Word untuk Web > anak tetingkap Copilot > tukar ke 'Ejen Undang-undang'. Tanya: 'Redline MSA ini berdasarkan playbook vendor Tahap-1 kami dan tandakan sebarang pengecualian indemniti.'",
        "tipID": "Buka kontrak .docx di Word for the Web > panel Copilot > beralih ke 'Agen Hukum'. Tanya: 'Redline MSA ini terhadap playbook vendor Tier-1 kami dan tandai pengecualian indemnitas apa pun.'",
        "license": "Microsoft 365 Copilot + Frontier Program",
        "link": "https://techcommunity.microsoft.com/blog/microsoft365copilotblog/word-legal-agent-in-frontier/4516218"
    },
    {
        "id": "wn-models",
        "title": "🧠 Frontier Model Picker",
        "titleBM": "🧠 Pemilih Model Frontier",
        "titleID": "🧠 Pemilih Model Frontier",
        "badge": "May 2026 rollout",
        "badgeBM": "Pelancaran Mei 2026",
        "badgeID": "Peluncuran Mei 2026",
        "summary": "Switch the underlying frontier model for any chat or agent: GPT Instant, GPT and Claude, ChatGPT Images 2.0. Use Thinking models for board-grade reasoning; Instant for fast triage.",
        "summaryBM": "Tukar model frontier asas untuk mana-mana sembang atau ejen: GPT Instant, GPT dan Claude, ChatGPT Images 2.0. Guna model Thinking untuk penaakulan bertaraf lembaga; Instant untuk triaj pantas.",
        "summaryID": "Ganti model frontier yang mendasari chat atau agen mana pun: GPT Instant, GPT dan Claude, ChatGPT Images 2.0. Gunakan model Thinking untuk penalaran kelas dewan direksi; Instant untuk triase cepat.",
        "tip": "In any Copilot Chat thread, click the model pill at the top — try 'GPT' for the Strategy/Risk briefs; 'Claude' for nuanced legal/policy drafting.",
        "tipBM": "Dalam mana-mana utas Copilot Chat, klik pil model di atas — cuba 'GPT' untuk taklimat Strategi/Risiko; 'Claude' untuk penyusunan undang-undang/dasar yang berciri halus.",
        "tipID": "Di thread Copilot Chat mana pun, klik pil model di atas — coba 'GPT' untuk briefing Strategi/Risiko; 'Claude' untuk penyusunan hukum/kebijakan yang bernuansa.",
        "license": "Microsoft 365 Copilot",
        "link": "https://techcommunity.microsoft.com/blog/microsoft365copilotblog/available-today-anthropic-claude-opus-4-7-in-microsoft-365-copilot/4511666"
    },
    {
        "id": "wn-excel-plan-python",
        "title": "📈 Excel — Plan mode + Python",
        "titleBM": "📈 Excel — Mod Pelan + Python",
        "titleID": "📈 Excel — Mode Plan + Python",
        "badge": "May 2026 rollout",
        "badgeBM": "Pelancaran Mei 2026",
        "badgeID": "Peluncuran Mei 2026",
        "summary": "Plan mode lets Copilot in Excel outline a step-by-step approach BEFORE making any change — review and adjust before edits land. Python in Excel runs advanced data techniques (forecasts, regressions, custom visualisations) directly inside the Edit-with-Copilot flow without leaving the workbook.",
        "summaryBM": "Mod Pelan membolehkan Copilot dalam Excel menggariskan pendekatan langkah-demi-langkah SEBELUM membuat sebarang perubahan — semak dan laraskan sebelum suntingan diguna. Python dalam Excel menjalankan teknik data lanjutan (ramalan, regresi, visualisasi tersuai) terus dalam aliran Sunting-dengan-Copilot tanpa meninggalkan buku kerja.",
        "summaryID": "Mode Plan memungkinkan Copilot di Excel menyusun pendekatan langkah-demi-langkah SEBELUM melakukan perubahan apa pun — tinjau dan sesuaikan sebelum perubahan diterapkan. Python di Excel menjalankan teknik data lanjutan (forecast, regresi, visualisasi kustom) langsung di alur Edit-dengan-Copilot tanpa meninggalkan buku kerja.",
        "tip": "In Excel for the Web > Copilot pane, click the menu above the prompt box and pick 'Plan'. Or simply add 'use Python' to your prompt to invoke Python automatically.",
        "tipBM": "Dalam Excel untuk Web > anak tetingkap Copilot, klik menu di atas kotak arahan dan pilih 'Plan'. Atau tambah sahaja 'use Python' kepada arahan anda untuk memanggil Python secara automatik.",
        "tipID": "Di Excel for the Web > panel Copilot, klik menu di atas kotak prompt dan pilih 'Plan'. Atau cukup tambahkan 'use Python' ke prompt Anda untuk memanggil Python secara otomatis.",
        "license": "Microsoft 365 Copilot",
        "link": "https://techcommunity.microsoft.com/blog/microsoft365copilotblog/what%E2%80%99s-new-in-microsoft-365-copilot--april-2026/4510935"
    },
    {
        "id": "wn-ppt-web-images",
        "title": "🌐 PowerPoint — web grounding + image picker",
        "titleBM": "🌐 PowerPoint — pelandasan web + pemilih imej",
        "titleID": "🌐 PowerPoint — pelandasan web + pemilih gambar",
        "badge": "April 2026",
        "badgeBM": "April 2026",
        "badgeID": "April 2026",
        "summary": "Add a public webpage URL as a deck reference and Copilot pulls in current external context to build the outline. Choose the image model (GPT-Image, Flux, or Auto) when generating or editing visuals — align with quality, style, and governance expectations.",
        "summaryBM": "Tambah URL halaman web awam sebagai rujukan dek dan Copilot akan menarik konteks luaran semasa untuk membina garis besar. Pilih model imej (GPT-Image, Flux, atau Auto) semasa menjana atau menyunting visual — selaraskan dengan jangkaan kualiti, gaya, dan tadbir urus.",
        "summaryID": "Tambahkan URL halaman web publik sebagai referensi deck dan Copilot menarik konteks eksternal terbaru untuk membangun outline. Pilih model gambar (GPT-Image, Flux, atau Auto) saat menghasilkan atau mengedit visual — selaraskan dengan harapan kualitas, gaya, dan tata kelola.",
        "tip": "In PPT for the Web > Copilot pane > add a web reference URL (e.g. a Bursa Malaysia listing or BNM circular page). When generating an image, click the gear and pick the model.",
        "tipBM": "Dalam PPT untuk Web > anak tetingkap Copilot > tambah URL rujukan web (cth. halaman penyenaraian Bursa Malaysia atau pekeliling BNM). Semasa menjana imej, klik gear dan pilih model.",
        "tipID": "Di PPT for the Web > panel Copilot > tambahkan URL referensi web (mis. halaman pencatatan Bursa Malaysia atau surat edaran BNM). Saat menghasilkan gambar, klik roda gigi dan pilih modelnya.",
        "license": "Microsoft 365 Copilot",
        "link": "https://techcommunity.microsoft.com/blog/microsoft365copilotblog/what%E2%80%99s-new-in-microsoft-365-copilot--april-2026/4510935"
    },
    {
        "id": "wn-outlook-canvas",
        "title": "✍️ Outlook — first draft in canvas",
        "titleBM": "✍️ Outlook — draf pertama dalam kanvas",
        "titleID": "✍️ Outlook — draf pertama di kanvas",
        "badge": "March 2026 (new Outlook)",
        "badgeBM": "Mac 2026 (Outlook baharu)",
        "badgeID": "Maret 2026 (Outlook baru)",
        "summary": "Copilot now writes the email directly in place and asks clarifying questions about goal, audience, and tone, then iterates with the user in the same canvas. No copy-paste, no formatting surprises — every change is visible in Outlook as the message is refined.",
        "summaryBM": "Copilot kini menulis e-mel terus di tempat dan bertanya soalan menjelaskan tentang matlamat, audiens, dan nada, kemudian beritirasi dengan pengguna dalam kanvas yang sama. Tiada salin-tampal, tiada kejutan pemformatan — setiap perubahan kelihatan dalam Outlook semasa mesej dihalusi.",
        "summaryID": "Copilot kini menulis email langsung di tempat dan mengajukan pertanyaan klarifikasi tentang tujuan, audiens, dan nada, lalu iterasi dengan pengguna di kanvas yang sama. Tanpa salin-tempel, tanpa kejutan format — setiap perubahan terlihat di Outlook saat pesan disempurnakan.",
        "tip": "In new Outlook on the Web, open Compose > Copilot. After the first draft lands, answer Copilot's clarifying questions and watch the email update in place.",
        "tipBM": "Dalam Outlook baharu di Web, buka Karang > Copilot. Selepas draf pertama muncul, jawab soalan menjelaskan Copilot dan perhatikan e-mel dikemas kini di tempatnya.",
        "tipID": "Di Outlook baru di Web, buka Compose > Copilot. Setelah draf pertama muncul, jawab pertanyaan klarifikasi Copilot dan perhatikan email diperbarui di tempatnya.",
        "license": "Microsoft 365 Copilot",
        "link": "https://techcommunity.microsoft.com/blog/microsoft365copilotblog/what%E2%80%99s-new-in-microsoft-365-copilot--april-2026/4510935"
    },
    {
        "id": "wn-teams-call-interpret",
        "title": "📞 Teams — Call Delegation + Interpretation",
        "titleBM": "📞 Teams — Perwakilan Panggilan + Tafsiran",
        "titleID": "📞 Teams — Delegasi Panggilan + Interpretasi",
        "badge": "April-May 2026",
        "badgeBM": "April-Mei 2026",
        "badgeID": "April-Mei 2026",
        "summary": "Copilot Call Delegation: Copilot answers incoming Teams calls on the user's behalf, gathers context from the caller, and books follow-ups via Microsoft Bookings. Consecutive Interpretation: turn-based translation between two languages with Interpreter on the meeting stage — ideal for ASEAN cross-border meetings.",
        "summaryBM": "Perwakilan Panggilan Copilot: Copilot menjawab panggilan Teams masuk bagi pihak pengguna, mengumpul konteks daripada pemanggil, dan menempah susulan melalui Microsoft Bookings. Tafsiran Berturut-turut: terjemahan giliran-demi-giliran antara dua bahasa dengan Penterjemah di pentas mesyuarat — sesuai untuk mesyuarat rentas-sempadan ASEAN.",
        "summaryID": "Delegasi Panggilan Copilot: Copilot menjawab panggilan Teams masuk atas nama pengguna, mengumpulkan konteks dari penelepon, dan memesan tindak lanjut via Microsoft Bookings. Interpretasi Berurutan: terjemahan berbasis giliran antara dua bahasa dengan Interpreter di panggung rapat — ideal untuk rapat lintas-batas ASEAN.",
        "tip": "Teams > Settings > Calls > enable Copilot Call Delegation. For meetings, Interpreter on stage supports both real-time simultaneous and turn-based consecutive interpretation.",
        "tipBM": "Teams > Tetapan > Panggilan > aktifkan Perwakilan Panggilan Copilot. Untuk mesyuarat, Penterjemah di pentas menyokong tafsiran serentak masa-nyata dan tafsiran berturut-turut giliran-demi-giliran.",
        "tipID": "Teams > Pengaturan > Panggilan > aktifkan Delegasi Panggilan Copilot. Untuk rapat, Interpreter di panggung mendukung interpretasi simultan real-time dan interpretasi berurutan berbasis giliran.",
        "license": "Microsoft 365 Copilot",
        "link": "https://techcommunity.microsoft.com/blog/microsoft365copilotblog/what%E2%80%99s-new-in-microsoft-365-copilot--april-2026/4510935"
    },
    {
        "id": "wn-notebook-mindmap",
        "title": "🧠 Notebook — Mind Maps + PPT/Word generation",
        "titleBM": "🧠 Notebook — Peta Minda + penjanaan PPT/Word",
        "titleID": "🧠 Notebook — Peta Pikiran + pembuatan PPT/Word",
        "badge": "May 2026 (Frontier preview)",
        "badgeBM": "Mei 2026 (Pratonton Frontier)",
        "badgeID": "Mei 2026 (Pratinjau Frontier)",
        "summary": "Copilot Notebook can now generate full Word documents and PowerPoint decks directly from notebook content. Mind Maps give an interactive grounded view of relationships across all sources — click a node to drill in. SharePoint sites, OneNote notebooks, and external web URLs all qualify as sources.",
        "summaryBM": "Copilot Notebook kini boleh menjana dokumen Word lengkap dan dek PowerPoint terus daripada kandungan buku nota. Peta Minda memberikan pandangan interaktif berlandaskan tentang hubungan merentas semua sumber — klik nod untuk menyelami. Tapak SharePoint, buku nota OneNote, dan URL web luaran semuanya layak sebagai sumber.",
        "summaryID": "Copilot Notebook kini dapat menghasilkan dokumen Word lengkap dan deck PowerPoint langsung dari konten buku catatan. Peta Pikiran memberikan tampilan interaktif berlandaskan tentang hubungan di semua sumber — klik node untuk mendalami. Situs SharePoint, buku catatan OneNote, dan URL web eksternal semuanya memenuhi syarat sebagai sumber.",
        "tip": "After grounding the notebook, click Quick Create > Mind Map for an executive overview, or > Word document / PowerPoint presentation to draft a deliverable preloaded with visuals.",
        "tipBM": "Selepas melandaskan buku nota, klik Quick Create > Peta Minda untuk gambaran eksekutif, atau > dokumen Word / pembentangan PowerPoint untuk merangka penyampaian yang dipra-muat dengan visual.",
        "tipID": "Setelah melandaskan buku catatan, klik Quick Create > Peta Pikiran untuk ikhtisar eksekutif, atau > dokumen Word / presentasi PowerPoint untuk menyusun deliverable yang sudah dimuat dengan visual.",
        "license": "Microsoft 365 Copilot",
        "link": "https://techcommunity.microsoft.com/blog/microsoft365copilotblog/what%E2%80%99s-new-in-microsoft-365-copilot--april-2026/4510935"
    },
    {
        "id": "wn-agent-store",
        "title": "🏪 Agent Builder — submit to Agent Store",
        "titleBM": "🏪 Agent Builder — hantar ke Kedai Ejen",
        "titleID": "🏪 Agent Builder — kirim ke Toko Agen",
        "badge": "May 2026 rollout",
        "badgeBM": "Pelancaran Mei 2026",
        "badgeID": "Peluncuran Mei 2026",
        "summary": "Agent Builder now supports submitting agents for admin review and approval. Approved agents land in the \"Built by your org\" section of the Agent Store where the whole organisation can discover and install them — the right balance of citizen-developer scale and IT admin control.",
        "summaryBM": "Agent Builder kini menyokong penghantaran ejen untuk semakan dan kelulusan pentadbir. Ejen yang diluluskan akan muncul dalam bahagian \"Dibina oleh organisasi anda\" di Kedai Ejen di mana seluruh organisasi boleh menemui dan memasangnya — keseimbangan tepat antara skala pembangun warga dan kawalan pentadbir IT.",
        "summaryID": "Agent Builder kini mendukung pengiriman agen untuk tinjauan dan persetujuan admin. Agen yang disetujui muncul di bagian \"Dibangun oleh organisasi Anda\" di Toko Agen di mana seluruh organisasi dapat menemukan dan menginstalnya — keseimbangan tepat antara skala pengembang warga dan kontrol admin IT.",
        "tip": "After Test, click Submit for review (next to Create + share). Once your IT admin approves, the agent appears in the org's Agent Store automatically.",
        "tipBM": "Selepas Uji, klik Hantar untuk semakan (di sebelah Cipta + kongsi). Sebaik sahaja pentadbir IT anda meluluskan, ejen muncul dalam Kedai Ejen organisasi secara automatik.",
        "tipID": "Setelah Uji, klik Submit for review (di sebelah Create + share). Setelah admin IT Anda menyetujui, agen muncul di Toko Agen organisasi secara otomatis.",
        "license": "Microsoft 365 Copilot",
        "link": "https://techcommunity.microsoft.com/blog/microsoft365copilotblog/what%E2%80%99s-new-in-microsoft-365-copilot--april-2026/4510935"
    }
]
